examples/avatar.js, examples/formatting.js, examples/pingpong.js, examples/presence.js, examples/query.js, examples/status.js
I haven't tested these, please review them for correctness and test them if necessary.
=> Add some examples and improve older ones

entrypoint.js
I'm all for discouraging old versions but using process.exit and suggesting code edits in a vendor package is stupid.
Throw an exception instead and allow an override using a env variable seems more reasonable to me.
=> Do not use process.exit, throw instead

src/Client/InternalClient.js, src/Structures/Server.js, src/Util/Cache.js
Use hashmap instead of array for caching by discriminator
Optimize `get` method by using `for` loop instead of `forEach`
and returning hashmap cache for queries by discriminator
=> Improve Cache class performance

src/Voice/AudioEncoder.js, src/Voice/VoiceConnection.js
This should throw an error similar to the `Tried to use node-opus, but opus not available - install it!` error. This is untested (because I wasn't able to simulate a broken build environment) but it should work - at least it doesn't break working installs. If someone on Windows that has problems getting discord.js to work could test it, that would be really nice.
=> Add opus sanity check

lib/Client/Client.js, lib/Client/InternalClient.js, src/Client/Client.js, src/Client/InternalClient.js
Fixes #157 by using the original file name instead of `image.png`.
(It uses node's `path` module to resolve the basename, but I can try using other substring/regex methods to implement it.)
=> sendFile() to use original file name by default

lib/Client/Resolver/Resolver.js, src/Client/Resolver/Resolver.js
So far it has been the case that resolveServer has been returning
undefined in the case that the resource was a Message from a TextChannel.
This was the case because the conditional returned the value of member
"server" in the Message object. The Message object doesn't have a server
member though. The fix is to use the "channel" member of the Message
object and return its "server" member which was likely the original
intention considering the if statement.
=> fix resolveServer undefined when TextChannel

lib/Client/InternalClient.js, lib/Voice/VoiceConnection.js, src/Client/InternalClient.js, src/Voice/VoiceConnection.js
Detection on `.updateDetails()` was not detecting bot accounts so the `email/password required` error would throw wrongly.
Bot accounts also couldn't leave a voice channel without supplying the `guild_id` so fixed to provide that on leave. (based on some info that #q provided in the node-discord.js channel)
(both fixes have been tested by me and seem to work as intended)
=> Fixes for bot accounts

lib/Client/Client.js, lib/Client/InternalClient.js, src/Client/Client.js, src/Client/InternalClient.js
Allows for joining multiple voice channels. Should address #214, and the structure is based on that. The voice connections are now stored in a cache at `client.voiceConnections`. For oauth bot accounts a voice channel or voice connection must be specified to leave at `.leaveVoiceChannel`.
This also fixes another issue where when users are moved by a privileged user with the 'Move Members' permission, and the client is not aware of it. It is now aware of these changes and will update the cache accordingly. (and emit `voiceMoved` event)
For non-bot client connections, the legacy method is used, where it will automatically leave the current voice channel and join the one specified. Also, no parameters are required for `.leaveVoiceChannel` for such accounts as there can only be one connection …
=> Multi voice channel support (new oauth bot accounts and diff servers)

lib/Client/InternalClient.js, src/Client/InternalClient.js
First: `TypeError: Cannot read property 'id' of null` when another user moves from another server's voice channel that the client is in and then moves into another server's that it is in (sorry, a bit hard to explain). I also think that the code I wrote for that is intended to only keep track of the bot client itself and if it gets forcefully moved by another privileged user, not for other user's updates.
Second: just should be setting that friends stuff to null if its a bot account...
*(I think these two fixes are actually fixes at my own code...)*
=> Voice State Update crash & small friends property fix

lib/Client/InternalClient.js, lib/Voice/VoiceConnection.js, src/Client/InternalClient.js, src/Voice/VoiceConnection.js
The other Voice State Update fix doesn't seem to fix crashes where InternalClient.leaveVoiceChannel isn't used, and the connection is simply destroyed.
Modified VoiceConnection.destroy() to remove the connection from InternalClient.voiceConnections
Also removes instances where VoiceConnection.destroy() is called and then manually removed from InternalClient.voiceConnections
=> Voice State Update crash fix (different from other one)

lib/Client/InternalClient.js, src/Client/InternalClient.js
Nothing much really, `client.sendMessage(msg, array)` works just fine but the same isn't happening when sending a file both on `client.sendFile()` and on `client.sendMessage()` with file in options.
=> Fix use of Array as String Resolvable on sendFile with content

lib/Client/InternalClient.js, src/Client/InternalClient.js
Oops, looks like I ~~broke something~~ completely ignored `if (content) {...}` making the **content obligatory** on `sendFile` with https://github.com/hydrabolt/discord.js/commit/6f466a401e9053047bd993855d412a7ece59307e. Sorry for that. :confounded:
Fixing the cr*p I did there. (I tested this like 20 times before even opening this PR, I hope it was enough tests this time lol)
~~please kill me~~
=> Fix obligatory content on sendFile

docs/docs_client.rst, docs/docs_message.rst, docs/docs_resolvables.rst, docs/docs_server.rst, docs/docs_serverchannel.rst, docs/docs_voiceconnection.rst, docs/vars.rst
- 257: Add proper eplanation of callback, like in every other method
- 433: Fix linking for Invite Resolvable
- 90 : Replace ':' with '-', just for consistency with the others
- 92 : String doesn't link to anything (?) -> Link removed
- 109 : Properly indent code-block because it didn't show at all on rtfd
- 53 : Remove doulbe '`' causing it not to display properly
- 67 : Remove 'currently, it currently
- 32 : Add links for Role Resolvable, as used in client#addMemberToRole,
client#removeMemberFromRole and client#memberHasRole
=> Some doc fixes

docs/docs_voiceconnection.rst, src/Voice/AudioEncoder.js, src/Voice/VoiceConnection.js
I wasn't able to setup the correct dev environment, so I couldn't test this fully.
I also hope it was ok to handle the volume with a new variable.
Anyway, I hacked the lib files in a similar way for my own bot and it works.
And for anyone who wants to know what I used `playArbitraryFFmpeg` for, it's to pitch/speed up/down sounds. It is actually really funny, so I hope more people can use this now.
=> Fix for the playArbitraryFFmpeg issue

docs/docs_client.rst
Just found this missing function while I was doing some "research" on `voiceConnection.destroy`.
=> Add destroy to docs

lib/Voice/AudioEncoder.js, src/Voice/AudioEncoder.js
Fixes econnreset when stream is interrupted.
```
Error: read ECONNRESET
at exports._errnoException (util.js:953:11)
at Pipe.onread (net.js:563:26)
```
=> fix econnreset in playRawStream

lib/Util/Cache.js, src/Util/Cache.js
Fixes a bug where an invalid input into Cache.remove would delete its first value.
Example scenario:
```js
bot.servers[0].name; // Discord API
bot.servers[1].name; // Discord Developers
bot.servers.remove({}); // true
bot.servers[0].name; // Discord Developers
```
=> Cache.remove bugfix

docs/docs_client.rst, docs/docs_user.rst, lib/Structures/User.js, lib/Voice/VoiceConnection.js, src/Structures/User.js, src/Voice/VoiceConnection.js
This is the first time I've looked through the source of `discord.js`, so forgive me if the pull request contains code that doesn't follow the "rules" of the source. In the voice packet that gets sent over WS, there is a [speaking event](https://discordapp.com/developers/docs/topics/voice-connections#voice-events) that is sent when a user starts or stops speaking. It however was not implemented into `discord.js`, so I took the liberty of trying myself.
If there is anything wrong with the pull request, please feel free to let me know so I may fix said issue.
=> Added a voiceSpeaking event, fired when a user in a voiceChannel starts or stops speaking.

src/Structures/Server.js
I noticed that the voiceSwitch event is sometimes emitted when no user actually did anything. My bot logs all channel switch events and sometimes logged ```user switched to x from x```, so I made a small patch for that.
=> Voice event fixes

src/Structures/Message.js
Bug that caused Message.everyoneMentioned to be undefined if it was false.
Credits to @GexoXYZ
=> Fix undefined everyoneMentioned

lib/Client/InternalClient.js, src/Client/InternalClient.js
```
C:\Users\user\node_modules\discord.js\lib\Client\InternalClient.js:180
if (data.status === 429) {
^
TypeError: Cannot read property 'status' of undefined
at C:\Users\user\node_modules\discord.js\lib\Client\InternalClient.js:180:14
at Request.callback (C:\Users\user\node_modules\superagent\lib\node\index.js:587:12)
at ClientRequest.<anonymous> (C:\Users\user\node_modules\superagent\lib\node\index.js:539:10)
at emitOne (events.js:96:13)
at ClientRequest.emit (events.js:188:7)
at TLSSocket.socketErrorListener (_http_client.js:308:9)
at emitOne (events.js:96:13)
at TLSSocket.emit (events.js:188:7)
at emitErrorNT (net.js:1272:8)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
```
=> Fix data undefined error

lib/Client/Client.js, src/Client/Client.js
Noticed these a while ago. 
The option was always true on these, even if you set them to false in the options. Not sure about the way I'm checking them here, it worked fine for me, but there might be some cleaner way instead of checking if the option is undefined, so giff feedback pls.
=> Fixes some bool options

docs/docs_message.rst
The shortcut of message.delete example was missing the end parentheses.
See:
| **Shortcut of** ``client.deleteMessage(message, options, callback``
=> Added end parentheses to shortcut in delete method (Message)

src/structures/GuildChannel.js
Altered GuildChannel.type to return either 'text', 'voice' or the id of the type (if it does not fit the known types of channel).
=> Indev rewrite - Changed GuildChannel type

src/structures/User.js
This fixes `user.equals` when passing `null` or `undefined`.
=> Fixed user.equals(null)

src/util/Collection.js
This should improve performance of `find()` and `findAll()`, as they are no longer copying the map's values into an array before iterating.
Same goes for `deleteAll()`.
=> Make Collection.find and findAll use .values()

src/structures/interface/TextBasedChannel.js
Rather than creating an array copied from all of the keys to get the first element, just use the first value of the iterator.
This should drastically reduce both memory and CPU usage when pushing old messages out of the cache.
=> Massively improve performance of message caching

src/structures/ClientUser.js, src/structures/DMChannel.js, src/structures/GroupDMChannel.js, src/structures/TextChannel.js, src/structures/interface/TextBasedChannel.js
This replaces the `channel.setTyping()` method with `channel.startTyping()` and `channel.stopTyping()`.
Each time `startTyping` is called, an internal counter is incremented.
Each time `stopTyping` is called, the counter is decremented.
If the counter is at 0 or less, the typing indicator is finally stopped.
Alternatively, the indicator can be fully reset by using `stopTyping(true)`.
This allows long-running commands in bots to set the typing status without cancelling each others' status if one finishes before the other.
=> Overhaul channel typing system

package.json
As far as I'm aware, we don't actually depend on anything in the newer versions of Node.
=> Lower Node version requirement to 6.0.0

src/structures/Guild.js
Currently, the event will only be emitted if the member's nickname AND roles change.
This fixes that issue.
=> Change _updateMember's notSame check from && to ||

src/client/actions/GuildRoleUpdate.js
See https://github.com/hydrabolt/discord.js/blob/7fe032c785/src/util/Constants.js#L156
=> Fixes typo in GuildRoleUpdate's documentation

src/util/Constants.js
The default value on Discord's side was changed from 36953089 to 104324097 a while ago to include the `USE_EXTERNAL_EMOJIS` and `CHANGE_NICKNAME` permissions.
=> Update default permissions

src/client/voice/VoiceConnection.js
When using VoiceConnection.playConvertedStream no audio is played. This seems to fix it
=> Fix VoiceConnection.playConvertedStream not playing any audio

src/structures/GuildMember.js
It now returns the users role that is higher than the other roles, as opposed to before, where it would sometimes return a role that was lower than some of the other roles.
=> Fixed highestRole to return the highest role

src/structures/MessageAttachment.js
Currently, it returns the same url for both the normal url, and the proxied url. This is obviously incorrect.
For reference, click [here](https://discordapp.com/developers/docs/resources/channel#attachment-object) to see appropriate discord documentation.
=> Fix proxyURL for attachments

src/client/Client.js, src/client/ClientManager.js, src/client/rest/RESTMethods.js, test/destroy.js
There were a bunch of them. the ClientManager promise bug hid the fact that the logout() call was always failing, and the logout call failing made sure the faulty timeout-clearing code in Client.destroy never got called.
=> fix Client.destroy bugs

src/client/ClientManager.js
Relatedly, what was the reason #828 was reverted and a subset/rewritten version of it was recommitted? There wasn't any reason mentioned in #839.
=> fix ClientManager.destroy promise bug

src/client/Client.js
_timeouts and _intervals were changed to Set objects in
commit 6ede7a32fd29bd44e65e344e1f102332d30c2129 a month ago.
Like #844, this fix was reverted in 7d04863b66177c105a92b39ffc990be3b6bfe84f (#839)
without explanation and was never included in the followup rewrite in
commit 5e2ee2398ea5f7b30d8c1783be5cde05803e54fd.
=> fix Client.destroy

src/client/ClientDataResolver.js
`resolveChannel` was actually trying to look for the ìd`attribute even when a string was passed.
(That was unluckily my first experience with the new version and almost drove me crazy haha).
=> Fixed resolveChannel when using a string

lib/Constants.js, src/Constants.js
Export the constants from /lib/Constants using named exports so they can be imported using named imports. 
The reason why the current state of the library does not break is caused by named destructing acting on the default export but as of latest versions of babel and possibly the official spec this will and may not work respectively
=> Properly export constants using named exports - v8

src/structures/GuildChannel.js
Made it possible to pass null to GuildChannel.overwritePermissions's
PermissionOverwriteOptions to blank the permission out.
=> Nullable permission overwrites

src/client/voice/VoiceConnection.js
In v8 a field called [`playing`](http://discordjs.readthedocs.io/en/8.2.0/docs_voiceconnection.html?highlight=playing#playing) existed on VoiceConnection. When trying to migrate to v10, I realized it was missing from the docs. It turns out it is still present, but was renamed to `speaking` and is not set in the constructor. This keeps it from being documented. This PR fixes this.
=> Fixed unset field of VoiceConnection

src/client/ClientDataResolver.js
Hi,
I'd like to propose a fix for an `UnhandledPromiseRejectionWarning` caused by `resolveBuffer`:
```
(node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): TypeError: source.on is not a function
```
When calling `sendFile()` with an attachment URL that returns an empty page (ie. content-length=0), `resolveBuffer` in ClientDataResolver will return `res.body` as an empty object instead of a Buffer. This causes an UnhandledPromiseRejectionWarning further along the way, so my suggested fix would be to simply check if the `resource` actually returned a Buffer. 
Example:
```js
msg.channel.sendFile('http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=242500&type=broken', 'image.jpg', 'look at this cool image');
```
=> UnhandledPromiseRejectionWarning caused by resolveBuffer on empty resource body

docs/deploy/deploy.sh
As reported by @Gawdl3y on the discord.js server. If I am correct only the commit commands should ever fail (I haven't seen errors on push when testing locally) - if necessary this can be amended by simply appending `|| true` to the particular failing lines.
=> Fix builds failing due to no changes in webpacks

src/client/voice/VoiceConnection.js
Incorrect number of arguments was provided to [`AudioPlayer.playPCMStream`](https://github.com/hydrabolt/discord.js/blob/indev/src/client/voice/player/AudioPlayer.js#L55) resulting in an error that [`AudioPlayer.currentConverter.destroy`](https://github.com/hydrabolt/discord.js/blob/indev/src/client/voice/player/AudioPlayer.js#L55) wasn't a function when trying to disconnect.
=> fix playConvertedStream

src/structures/Message.js
`unshift` returns a number not the array that was unshifted.
=> fix message.edits

src/util/Collection.js
Adds an equals function that checks for differing size and differing
key-value pairs, and takes into account the edge case for when there's
an entry for the key, but the value is undefined.
=> equals function added

src/structures/RichEmbed.js
Might as well if we're erroring on number of fields when that's the one limit that doesn't actually throw a bad request.
=> Add more errors for RichEmbed builder char limits

src/client/rest/RESTMethods.js
As per an issue brought up in Discord, the `clearReactions` method was returning `undefined`.  This was the solution.
=> fix remove reactions return

docs/general/faq.md, src/client/voice/pcm/FfmpegConverterEngine.js
It will allow you to just do `npm i ffmpeg-binaries` to install and use ffmpeg.
I didn't add it as a peer dep because you can install ffmpeg through different methods
=> Add ffmpeg-binaries as a possible source of ffmpeg

src/structures/VoiceChannel.js
Fixed simple typo that prevented setBitrate method from working.
=> Fix setBitrate typo in VoiceChannel.js

src/client/rest/RESTMethods.js, src/util/Constants.js
Prompted by many questions asking what `cannot read property 'replace' of null` means.
=> friendlier notification of an invalid token

src/client/voice/dispatcher/StreamDispatcher.js
This seems to be a symptom of a larger issue....
It seems that streams aren't being properly ended, as this will emit after every song (effectively ruining queuing systems with this emitted as an error). This might account for some memory build up when playing many songs in a row. This PR is a band-aid fix, a real fix should be looked into.
=> Revert error emit on Slow Stream Gen

src/structures/Message.js
The `emojiID` that was used to remove a reaction from `this.reactions` was different from the `emojiID` that's used to add one.
`_removeReaction` would always return `null`, so the `messageReactionRemove` event could never get emitted. No more.
=> Fix _removeReaction's reaction lookup

src/client/voice/VoiceBroadcast.js
The issue is that one opus encoder is trying to encode at two different volumes and trying to interpolate between them, which causes a pretty bad sound.
This PR makes it so that every individual volume has its own encoder.
It also makes the encoding process asynchronous.
=> Fix VoiceBroadcaster per-dispatcher volume

src/util/Collection.js
basically... it just uses .get and .has internally... this provides a consistent api for all user or whatever properties, so you can have `Collection.get("id", "383838338")` or whatever next to `Collection.get("name", "macdja38")` and both will work and be efficient and all that.
=> This expands the consistency of .find and .exists to include the id property

src/util/Collection.js
Because Map has no enumerable properties and I got tired of seeing these when logging Collections
=> Make _array & _keyArray non-enumerable

src/client/rest/APIRequest.js
**move function getRoute(url) into class APIRequest**
this.route = getRoute(this.url);   `>>>`   this.route = this.getRoute(this.url);
#Error Console 
————————
Uncaught (in promise) ReferenceError: getRoute is not defined.    _[APIRequest.js]_
=> hotfix ReferenceError when built using Webpack

src/structures/Guild.js
The default channel for a Guild is always the first TextChannel in the Guild, it can't be a VoiceChannel.
I know this might come off as petty, and I'm sorry if it does, just came across this today and wanted to make it a bit more specific.
=> Changed return type of Guild.defaultChannel

src/client/rest/RESTMethods.js
The search function was sending requests to stuff like:
`search?author_id=&content=&channel_id=135823828352838352`
=> Fix empty search query parameters

src/client/rest/RESTMethods.js
The class names were renamed in cd657be8beaf852e969d660ec40c02130242578f, this fixes two places where references weren't renamed.
=> Fix createEmoji/deleteEmoji action name.

src/client/voice/receiver/VoiceReceiver.js
For some as yet undetermined reason the decode function fails when one specific person talks, reporting an error of "The compressed data passed is corrupted".
Even if the underlying issue can be fixed it probably wouldn't hurt to have error handling for this anyway.
=> Added try catch so that decode errors aren't fatal

src/structures/Message.js
Fixes #1089
When discord sends an array of mentions, it is a full list of mentions -- therefore, we should clear the old mention collection. The same goes for when we re-analyze the message for channel mentions.
=> Message patching: clear mention collections

src/client/rest/RESTMethods.js
`GuildEmojiCreateAction#handle` expects `guild, emoji`, the rest method had them backwards.
=> Fix backwards GuildEmojiCreate parameters in createEmoji restmethod

src/client/rest/RESTMethods.js
`addRole` would modify the cached GuildMember rather than letting it be handled internally when a guild member update packet is received from Discord, leading to the `oldMember` and `newMember` being identical following a call to `addRole`
This is currently how `addRoles` does it, and a correct oldMember is passed to the `guildMemberUpdate` event following a call to `addRoles`
=> Fix for incorrect oldMember in guildMemberUpdate event after addRole

src/client/rest/RESTMethods.js, src/structures/Guild.js
added RESTMethods#AddGuildMemberOptions and Guild#addMember with typedef AddGuildMemberOptions to be able to add user to guild as a member through `PUT/guilds/{guild.id}/members/{user.id}` https://discordapp.com/developers/docs/resources/guild#add-guild-member
=> Added support for adding users to guild 2

src/structures/RichEmbed.js, src/structures/interface/TextBasedChannel.js
Mostly for attaching local images that can be accessed within the embed image/author icon/footer icon via `attachment//filename.png` and the like.
=> Add RichEmbed#attachFile

src/client/voice/ClientVoiceManager.js, src/client/voice/VoiceConnection.js, src/client/voice/VoiceUDPClient.js, src/client/voice/VoiceWebSocket.js, src/client/voice/player/AudioPlayer.js, src/client/voice/receiver/VoiceReceiver.js, src/util/Constants.js
- improves codebase
- removes concept of pending connections
- attempts to fix memory leaks by removing EventEmitter listeners
- makes voice connections keep track of its own channel when it is moved by another user
- allows voice connections to reconnect when Discord falls back to another voice server or a region change occurs (fixes #1104)
- adds events for some of the aforementioned events
=> VoiceConnection rework

src/client/actions/ActionsManager.js, src/client/actions/GuildChannelsPositionUpdate.js, src/client/rest/RESTMethods.js, src/structures/Guild.js, src/util/Util.js
Currently the library implements the ['Create Channels' endpoint via POST to /guilds/{guild.id}/channels](https://discordapp.com/developers/docs/resources/guild#create-guild-channel), but doesn't implement the ['Modify Guild Channel Positions' endpoint](https://discordapp.com/developers/docs/resources/guild#modify-guild-channel-positions) at all.
This change adds that support as well as a method on Guild which will shuffle all existing channels using a new utility method for shuffling arrays.
=> Implement 'Modify Guild Channel Positions' 

src/structures/ClientUser.js
`setGame` method would always result in an Object passed to `setPresence`.
Passing { game: null } (supported by discords WebSocket gateway to reset the current Game) to `setPresence` would still result in a Game Object sent to the endpoint.
Explicitly setting `game` to null should overwrite the `game` object provided by `localPresence` or `client.presence`.
This was neither supported by `setGame` or `setPresence`.
[Discord Documentation: Gateway#gateway-status-update](https://discordapp.com/developers/docs/topics/gateway#gateway-status-update)
=> Adding resetGame functionality

src/structures/Guild.js
In my last commit it looks like I changed 'createChannel' to 'updateChannel' at some point and never changed it back before committing, this flips it back to createChannel.
Sorry for the trouble.
=> Create channel accidentally changed to update channel

src/util/Collection.js
This was discussed the other day. I didn't need it for my earlier pr, so I made it a separate pr.
=> Add Collection.clone()

src/client/voice/util/Secretbox.js
Looking through the source of node-sodium, it looks like libsodium exposes a separate method for xsalsa20poly1305 encryption. If you look at the documentation for `crypto_secretbox(_open)` it shows that it requires four args: the text, the nonce, and two public keys from the sender and receiver. However, `crypto_secretbox_xsalsa20poly1305(_open)` takes just three args, as tweetnacl does: the text, the nonce, and the secret key.
=> Fix for #1219 (sodium methods)

src/structures/RichEmbed.js
See issue #1190.
Also removed `String(name)` because `name` is already a string.
=> Add RichEmbed fields error handling

src/structures/interface/TextBasedChannel.js
The filterOld variable was not being passed, when fetching internally.
=> Fix for bulkDelete, that is not filtering old messages when passing a number.

src/structures/GuildChannel.js
Everyone, Roles, and Member overwrites were all resolving in the same loop, instead of Separate application of Everyone -> Roles -> Member overwrites according to https://support.discordapp.com/hc/en-us/articles/206141927-How-is-the-permission-hierarchy-structured-
This means, if Everyone had allow on something a Role had deny on it, it would incorrectly resolve allow. And the same for if a Role had an allow, when a member would have a deny.
=> Fix #1253: Permission Overwrites Resolution

package.json, src/client/websocket/WebSocketManager.js
zlib gets a shim in browser which is pako anyway, so no need to manually require it
=> remove pako

src/structures/interface/TextBasedChannel.js
When using sendFiles, only the first argument (array of BufferResolvable or FileOptions) should be required.
Currently omitting the last argument results in 
```js
TypeError: Cannot convert undefined or null to object
```
Just a small fix for this.
It's tested.
=> Make the optional arguments for TextBasedChannel#sendFiles optional

src/structures/interface/TextBasedChannel.js
Basically just a shortcut to `fetchMessages({ limit: 1, around: ID })`, but it can be useful in case e.g. someone transfers their bot to an user account, or even be useful as a shortcut itself.
=> Make FetchMessage work for non-bot users

src/util/Constants.js
The endpoint for fetching the webhooks of a guild was missing.
Trying to fetch them resulted in:
```js
TypeError: Constants.Endpoints.guildWebhooks is not a function
```
Small tested fix for that.
=> (re)Adding the endpoint for fetching guildWebhooks

src/structures/Message.js
I have added a convenience field to mentions that maps guild members to their respective mentions, provided they already exist in the cache.
I also changed the users code to be a bit neater, but the functionality is exactly the same.
Frequently when doing operations on mentions, we need to map them to the member get function.
```js
if (message.mentions.users.size) {
const x = message.mentions.users.map(u => message.guild.members.get(u.id).displayName);
message.reply(`Members: ${x}`);
}
```
Using the convenience property, we can shorten this to:
```js
if (message.mentions.members.size) {
const x = message.mentions.members.map(m => m.displayName);
message.reply(`Members: ${x}`);
}
```
For moderation purposes such as checking for kickable:
```js …
```
=> Added mentions.members

package.json
The version 0.12.x of `uws` has been recently removed from NPM and only the latest version (0.14.1) is available.
The reason is described here: https://github.com/uWebSockets/uWebSockets/issues/551.
=> Update `uws` package version.

src/client/ClientDataResolver.js
Added support for:
* Vanity URLs
* Permanent Invites
Also fixed `discord.com/invite/{code}` being a valid invite
=> Fix invite resolver

src/client/rest/RESTMethods.js, src/structures/Guild.js
Currently the permission property of RoleData is just passed as is to discord api.
That will resolve them beforehand.
=> Add guild#createRole resolve permissions and RoleData optional

src/client/rest/RESTMethods.js, src/util/Constants.js
Fixed several things borked up by #1323, such as:
- Creating Channels
- Pass rejected add and remove role promises back to the top.
- Resolving ID of guildmember for api requests.
- Replacing client id with `@me` when modifying own member object, because discord api.
- Replaced plain strings with their corresponding Constants.Events for consistency when attaching or removing event listeners.
- One lined two if statements.
- VS Code apparently changed some formatting stuff, npm run lint wasn't complaining.
`ClientUser#acceptInvite` is untested for obvious reasons.
I hope that was all. I couldn't find anything else.
__Update:__
- One-lined 3 more if statements.
- Catch/Reject addRole and removeRole the same way as other methods.
- Resolve permissions on updateGuildRole with …
=> Fixing stuff, borked by #1323

src/client/ClientManager.js
Example:
```
const client = new require('discord.js').Client()
client.destroy()
```
atm this is throwing a TypeError
since calling .destroy() on a already destroyed client just resolves i'd say this also fits better then a reject and would make it possible to just call .destroy() no matter which state ur bot is in and wait for the resolve to ensure its dead
=> fix for .destroy() on never loggedin clients

src/client/voice/opus/BaseOpusEngine.js, src/client/voice/opus/NodeOpusEngine.js, src/client/voice/opus/OpusScriptEngine.js
Enables FEC (forward error correction) and PLP (expected packet loss percentage) settings for Opus encoding.
See Jake's PR to discord.py that adds this:
https://github.com/Rapptz/discord.py/commit/7efabce4b2a1ddc0193f9d544cd90185d4740042
=> Add FEC and PLP support for Opus encoding

src/client/actions/MessageReactionRemoveAll.js, src/client/rest/RESTMethods.js
Fix for #1285 
When using ``Message#react`` the messageReactionAdd event was fired twice, because the action was called one time by react and one time from the ws. This avoid the first, while returning the correct value.
Also a small correction for the messageReactionRemoveAll in the docs.
=> Not firing messageReactionAdd internally & doc fix

src/structures/Message.js, src/structures/MessageMentions.js
Currently the channels and members properties are always null and the roles collection is always empty.
=> Fix for MessageMentions properties always being null or empty

src/client/rest/RESTMethods.js, src/structures/MessageReaction.js
Steps to reproduce:
1.) Clone newest master
2.) Add the following to demo code
```js
client.on("messageReactionAdd", (reaction, user) => {
reaction.remove(user).catch(console.error);
});
```
3.) Add reaction to message 
4.) Receive error: `'Value "undefined" is not snowflake.'`
This was throwing an error because user was being resolved to an ID, while the REST method was treating it like a user object. Fix is to remove `.id` property. I have also changed it to userID to be consistent with the surrounding variables.
=> Fix for error on removing message reaction.

src/client/voice/util/VolumeInterface.js
I don't really understand where the conversion numbers come from but having this allows for an easy way to get the volume back based on what method you used to set it. I think the math is right, but yeah I've just used the conversion numbers from the other methods and rearranged the equations to get the original numbers
hopefully I did this right xD
=> getters for decibel and logarithmic volume

src/client/voice/opus/BaseOpusEngine.js, src/client/voice/opus/OpusEngineList.js
Many tests have shown that FEC and PLP cause issues such as untimely endings and performance decreases, respectively. It is possible that FEC and PLP would be able to help on certain weaker connections, however...
I considered it might be useful to have something exposed that allows the end-user to set these if they want, but our current code doesn't allow for that. It'll remain an internal feature for the time being.
=> Make FEC and PLP non-default

src/client/ClientDataResolver.js
Trying to react with `1⃣` (aka 1️⃣ ) will throw this error
```js
TypeError: Cannot read property 'identifier' of undefined
```
That's because `parseInt(`1⃣`);` returns `1`.
The Data Resolver will then try to get it from the client.emojis collection and throw that error.
Checking for a valid ID with `this.client.emojis.has(emoji)` rather than `parseInt()` would solve that.
=> Fix for failed emoji resolve attempts

src/client/voice/player/AudioPlayer.js
Looks like some leftover from commit [9eaf145](https://github.com/hydrabolt/discord.js/commit/9eaf1456b28f3152c84fff15c2afcbadb1684bde)
```js
TypeError: this.destroyAllStreams is not a function
```
Should be `this.destroyCurrentStream()`
=> Fix for AudioPlayer causing a crash on voiceConnection#closing

src/structures/Guild.js
it Fixes setOwner example in discord.js docs :eyes: 
-[  ] This PR changes the library's interface (methods or parameters added)
-[  ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
-[x] This PR **only** includes non-code changes, like changes to documentation, README, etc.
=> fix Guild setOwner example typo

src/structures/Message.js
`Message.editedTimestamp` is currently incorrectly the raw timestamp string from the discord api, rather than a number.
Converting it to a number was probably overlooked or forgotten in the Message#mentions / message update cleanup. [#fa016b6](https://github.com/hydrabolt/discord.js/commit/fa016b6b4178d18bf094646088a3d9f2d8c54a4d)
=> Fix for Message.editedTimestamp incorrectly being a string, rather than a number

src/structures/Guild.js, src/structures/interfaces/TextBasedChannel.js, src/util/Constants.js
- Added a warning indicating that that method may only be used by a user account.
- Made the MessageSearchOptions optional like in the docs stated.
- Fixed Endpoint for searching in a certain channel.
=> Made search argument optional, added useronly warning and fixed endpoint

src/client/rest/RESTMethods.js, src/structures/interfaces/TextBasedChannel.js, src/util/Constants.js
- `/channels/{channel.id}/ack` seems not to be a valid endpoint, it responds with 404.
Also the discord client itself uses `/channels/{channel.id}/messages/{message.id}` to ack channels.
Therefore I removed the seemingly not working endpoint from the Constants file and made the ackTextChannel method now using the working one.
Alse the `message.id` of the request url seems not to be a specific's message ID, more like just the current time as a discord snowflake, 
`Slowflake.generate()` seems to be the correct way to generate that snowflake, correct me if I am wrong.
- Fixed typo `ackTextMessage` -> `ackTextChannel`.
- It wouldn't hurt to add `acknowledge` to the full props in `applyToClass`, to actually implement …
=> Fixed acknowledging of channels

src/util/Snowflake.js
Adds a constructor to SnowflakeUtil similar to the Util constructor letting the user know that it cannot be initiated.
=> Throw an error if you try to initiate a new SnowflakeUtil class instance

src/client/ClientDataManager.js, src/client/websocket/WebSocketManager.js
ClientDataManager no longer uses the right status after the rewrite. Caused status to be in permanent idle state. WebSocketManager's status is unused, so it can be removed. 
=> fix for using wrong status, causing certain events not to be fired

src/structures/interfaces/TextBasedChannel.js
Currently a `TypeError: Cannot read property 'id' of undefined`, pointing to [this](https://github.com/hydrabolt/discord.js/blob/master/src/structures/interfaces/TextBasedChannel.js#L198) line, is thrown when using `TextChannel#fetchMessage` on an user account if the channel is either empty or the client has no `READ_MESSAGE_HISTORY` permission for that channel.
This is because `TextChannel#fetchMessages` resolves with an emtpy collection in that case and the `.first()` message will be undefined.
This will now throw `Error: Message not found` as probably expected.
=> Make TextChannel#fetchMessage abstraction throw a better error.

src/structures/Emoji.js, src/util/Constants.js
Emojis were using wrong endpoint, this should amend the issue.
=> emojis should use cdn endpoint

src/client/Client.js, src/structures/Guild.js
`client#status` now returns the status, instead of undefined
also `client#guildMemberUpdate` and `client#guildMemberAdd` are firing again
=> Using ws.connection.status rather than undefined ws.status

src/structures/ClientUser.js
This PR makes minor modifications to the `ClientUser#setStatus` function to make it function properly for user accounts (selfbots).
Previously using the generic endpoint, setting a status programmatically on a user account would not work most of the time, and it would never adjust it on the client settings.
By modifying the ClientUserSettings object, we can circumvent this issue.
1. Modifying statuses on a user account will work 100% of the time
2. Modifying statuses on a user account selfbot will reflect on the actual client
This PR accomplishes this by
1. Checking if the ClientUser is a bot
2. If it is a user, then use the `ClientUser#settings.update('status', value)` function to properly update the user status
3. If it is a bot, perform the presence update as per usual
I have made a …
=> better setstatus for selfbots

src/structures/MessageMentions.js
Currently using ``Message#isMentioned`` for a DM throws
```js
TypeError: Cannot read property 'has' of null
```
This is because ``MessageMentions#channels`` returns null here.
To fix that ``MessageMentions#channels`` could return an empty collection in DMs like ``MessageMentions#roles`` is doing that.
=> Make MessageMentions#channels return an empty collection in DMs

src/structures/GuildAuditLogs.js
- docblock updated because to the end user they aren't promises
- used `Target` variables because consistancy
=> consistency in audit logs owo

src/structures/Emoji.js
Adds convenience methods (similar to those of RichEmbed) to Emoji, for easier use:
- `setName`
- `addRestrictedRole`
- `addRestrictedRoles`
- `removeRestrictedRole`
- `removeRestrictedRoles`
Still a bit indecisive over either stay using array argument or use rest parameters for the `addRestrictedRoles` method. Let me know if I should use rest parameters.
**Edit:** I can also use both 🤔 
**Edit 2:** If I used both I could also merge the restricted role methods into one method 🤔
=> Emoji convenience methods

src/client/websocket/WebSocketConnection.js
- Readded documentation for `Client#reconnecting`
Note: Maybe needs to be reworded or moved to a different location.
- Readded `Client#disconnect`
Note: That event was previously only fired when the client was not currently reconnecting: [see](https://github.com/hydrabolt/discord.js/commit/195fcfa15cfdfbeede545f22009006f3a34a0dfc#diff-25533af2af0a39d16191a08cc17046b9L234)
Since the reconnecting itself is no longer behind that condition it's probably also no longer necessary for the event anymore: [see](https://github.com/hydrabolt/discord.js/blob/master/src/client/websocket/WebSocketConnection.js#L370)
I may be wrong here.
=> Readding Client#disconnect and docs for Client#reconnecting

src/client/websocket/WebSocketConnection.js, src/client/websocket/packets/WebSocketPacketManager.js
Errors in ready event were being emitted, rather than being properly thrown. These changes were made with the help of hydrabolt. 
=> Ready event will now throw errors properly

src/client/voice/VoiceConnection.js
When a voice server update is received with no endpoint, this means the client is awaiting an endpoint. This should not throw an error right away.
=> Allow await endpoint stage to not error

src/client/rest/DiscordAPIError.js
Improve the documentation for `DiscordAPIError.flattenErrors`. Also added some parens to make the order of ternary operations more clear to future readers.
=> Document flattenErrors keys param.

src/structures/Webhook.js
I hope this is the correct branch to PR to.
Sending a file with the webhook currently throws an error.
This will take care of that and allow sending multiple at once.
Tested with a Buffer, local path and an URL.
Also the documentation for other methods are slightly off or wrong, 
not sure if this should be in this PR, therefore left them out.
If they should be part of this PR, I could add them, shouldn't be that much.
=> Fix for sending files with Webhook class

src/client/rest/RESTMethods.js
fetchMeMentions -> fetchMentions :thinking:
I have no idea which one includes fixing typos :/
=> Fix typo in RESTMethods.js

src/structures/GuildAuditLogs.js
I am not sure whether ``target < 80`` is correct, it just seemed logical to me.
`this.options` should be `data.options`
Shouldn't at least GuildAudLogs.build be private, if not all methods?
=> update GuildAuditLogs for MESSAGE_DELETE and fixed extras

src/client/rest/RESTMethods.js, src/structures/ClientUser.js
- Setting an auth header works wonder when encountering a 401.
- makeRequest already resolves with the body, removed ``.body``
- Renamed ``res`` to ``data`` to be consistent with other methods.
- Solution to make the arguments parts truly optional, rather than all or nothing.
=> fix fetchMentions' auth header, options and data mapping

src/structures/Webhook.js, src/structures/interfaces/TextBasedChannel.js
Changed the for in loop to a traditional for loop, to avoid iterating through prototypes.
Not like they should be there in the first place, but a for in seems not to be necessary here.
=> Using a traditional for loop rather than a for in loop for options.files

src/structures/Message.js, src/structures/Webhook.js
Deprecates the webhook send aliases and editCode, because someone forgot them for 11.1 :eyes:
=> Deprecate webhook send aliases and editCode

src/structures/GuildAuditLogs.js
See #1471 
The not catchable rejection is caused by a rejection when fetching webhooks or invites.
This will take care of that.
~~Appending a ``.catch(reject);`` would also work.
Not sure what is the preferred solution here, both will lead to the same result.~~
=> Handing promise rejections from GuildAuditLogs#build to the user

src/structures/GuildMember.js
When, while using GuildMember#addRole or GuildMember#removeRole, resolving a role fails, a TypeError is thrown rather than rejected, which makes it impossible to catch it with a ``.catch(someFunction)``.
=> Failing to resolve a role should reject and not throw an error

src/structures/GuildMember.js
Removes the member param from new Permissions in a couple places, since it is no longer an acceptable param.
=> Fix Permissions now that member is deprecated

src/structures/GuildChannel.js
Removed deprecation leftover that throws a ~~TypeError~~ RangeError when using ``GuildMember#permissionsIn`` and ``GuildChannel#permissionsFor``
=> Removing more deprecation leftovers

src/structures/Invite.js
=> add more stuff to invites!

src/structures/Message.js
Fixes the example for Message#createReactionCollector by changing `reaction.emoji.id` to `reaction.emoji.name`.
=> Fix reaction collector example

src/client/Client.js, src/structures/Guild.js, src/structures/GuildChannel.js, src/structures/interfaces/TextBasedChannel.js
- Changed redundant `rest.api` to `.api`
- Fixed `TextChannel#bulkDelete`'s endpoint
- Fixed `TextBasedChanne#acknowledge`'s endpoint
- Made `GuildChannel#createInvite`'s argument optional again, also included reason in the options object
=> Fix for bulkDelete, acknowledge, createInvite and remove some redundant stuff

src/client/ClientDataResolver.js, src/structures/Guild.js, src/structures/Message.js, src/structures/RichEmbed.js, src/structures/Role.js, src/structures/Webhook.js, src/structures/shared/SendMessage.js, src/util/Util.js
Moved the static data resolvers to the util class.
This change is motivated because #1345 has circular references between the data resolver and the message embeds. 
=> Refactored static resolvers to Util

src/client/voice/opus/OpusEngineList.js
If an Opus engine cannot be found for a reason other than it not being present, we shouldn't simply ignore the error.
=> Opus engine fetching: don't ignore non-missing errors

src/client/voice/VoiceBroadcast.js
VoiceBroadcast#guaranteeOpusEngine is an old method that shouldn't be used anymore.
=> Remove unused VoiceBroadcast#guaranteeOpusEngine (fixes #1556)

src/structures/User.js
Made ``User#displayAvatarURL`` a Method instead of a getter to allow specifying a format and a size.
Will still return a png for the default avatar for obvious reasons.
=> make User#displayAvatarURL a method and make it and avatarURL accept an options object

src/structures/PermissionOverwrites.js
At the moment, on the docs, it lacks any documentation on how to get permissions from the PermissionOverwrites. I'm not very good at this, and if I need to change something please tell me, but this is my _attempt_ to add support for the allowed/denied permissions on PermissionOverwrites.
=> Add denied/allowed permissions to PermissionOverwrites

src/util/Collection.js
[NON-BREAKING CHANGE]
An optional `count` argument is added to the following methods:
- random() and randomKey()
- first() and firstKey()
- last() and lastKey()
If `count` is used, the method returns an array instead of only the value. Performance impact non-existent for existing code. Performance for returning an array has been measured and this is the fastest I could find (array[i] = value is faster than array.push()).
=> Add `count` optional argument to Collection methods

src/client/Client.js, src/client/voice/VoiceConnection.js, src/structures/Message.js, src/util/Constants.js
Those typedefs are asked all the times in the support channels, usually I just link them to the constants file.
Why not just add them to the docs then?
Note: [`Status`](https://discord.js.org/#/docs/main/master/typedef/Status) is already documented, `Client#status` was just not pointing to it.
Edit:
``VoiceConnection#status`` points now to `VoiceStatus`
=> Added Client#status and Message#type typedefs

docs/topics/voice.md
Installing ffmpeg-binaries globally would not work.
=> Remove global flag from ffmpeg tutorial doc

src/structures/Guild.js
Small typo in `Guild#createEmoji` with great impact.
Creating emojis will be possible again.
=> Fixed typo in Guild#createEmoji

src/structures/Guild.js, src/structures/GuildChannel.js
Since [those](https://github.com/hydrabolt/discord.js/blob/1e47cfdd5df1654ac6ed47146e09f34e3e49b0c5/src/structures/PermissionOverwrites.js#L32-L33) two properties were renamed PermissionOverwrites require mapping before sending them to discord.
Changing the names of the properties back would be a better solution IMO.
Also passing now the overwrites as correct parameter when cloning a channel.
Edit:
Changed all `.deny` and `.allow` for permission related methods in `GuildChannel` to their new property names.
Related to #1595's problem with `.joinable` being incorrectly `true`.
=> Correctly mapping overwrites when creating a channel and renamed all relevant property names as of #1562

src/structures/ClientUser.js, src/structures/Guild.js
See #1523 
Waiting for the websocket event will avoid that issue.
[This](https://github.com/hydrabolt/discord.js/blob/11.1-dev/src/client/rest/RESTMethods.js#L324-L342) was already part of the lib before the rest rewrite, must have been overlooked.
Also called the method with the correct object after resolving the buffer.
=> Wait for the websocket event when creating a guild

src/structures/Guild.js
Also made it possible to set the guild's verification level to 0, by passing an explicit number 0.
Passing a string `'0'` was possible before, but ignoring the number seems wrong.
=> Added Guild#setExplicitContentFilter

src/structures/Message.js
Remove the implication that a Message object's ID is unique only to the channel it was sent on
Message ID's are snowflakes, and as stated in Discord's API documentation, globally unique throughout Discord
See the [API reference](https://github.com/hammerandchisel/discord-api-docs/blob/master/docs/Reference.md#snowflake-ids) and the [Message docs](https://github.com/hammerandchisel/discord-api-docs/blob/master/docs/resources/Channel.md#message-object)
=> Improve Message's ID attribute documentation

src/client/Client.js, src/client/rest/APIRouter.js, src/structures/OAuth2Application.js
- Shortened ``this.rest.api`` in ``Client#fetchApplication`` to ``this.api``
- Renamed ``OAuth2Application#reset`` to ``#resetSecret``, because it only resets the secret and not the token.
- Added a ``#resetToken`` method to reset the token.
- Added a warning, indicating that both methods are for user account only.
``Object.assign`` might not be the best solution for the ``resetToken`` method,
something different or just resolving with the new bot object may be better.
=> renamed OAuth2Application#reset to resetSecret and added resetToken

src/client/voice/VoiceConnection.js
This is the proper solution to #1595, and supersedes #1598.  The reason the `error` event was firing when the `failed` event should have been firing was a race condition of the VoiceConnection's state.
=> Fix VoiceConnection#authenticateFailed race condition

src/client/Client.js, src/client/WebhookClient.js
Fix for #1622 
args was getting passed to the timeout rather than the function itself.
=> settimeout should use its args

src/structures/Guild.js
Fix for #1632 
`Guild#deleteEmoji` was incorrectly using the ID of the guild rather than the ID of the emoji.
=> Fixed Guild#deleteEmoji, it should use the emoji's id

src/client/voice/VoiceConnection.js, src/client/voice/dispatcher/StreamDispatcher.js
A lot of users have been getting this error:
`TypeError: Cannot read property 'sendPacket' of null`. It's because a StreamDispatcher is attempting to change the speaking state while the VoiceConnection has been disconnected. The most prevalent instance of this occurs when a VoiceConnection disconnects: the StreamDispatcher process loop determines that it should end itself and calls its internal destroy method. This triggers a setSpeaking call, which obviously doesn't work since the VoiceConnection is disconnected.
Thanks to Deadlystrike for providing a stacktrace for this issue.
=> Ignore setSpeaking requests when VC isn't connected

src/client/Client.js
Previously it returned: `this.api.oauth2.applications was not a function`, missed fixing with the api router change
=> Fix client.fetchApplication

src/structures/interfaces/TextBasedChannel.js
Removed deprecated `file` option from the [MessageOptions](https://discord.js.org/#/docs/main/stable/typedef/MessageOptions).
Regarding the `WebhookMessageOptions`:
- There is also the `file` option which is not marked as deprecated.
Is this correct?
- The `embeds` array only accepts an `Object` but not a `RichEmbed`, which would behave differently than the `TextBasedChannel#send` because `RichEmbed#file` wouldn't be attached here.
This is correctly documented, but feels inconsistent.
Is this correct?
=> Removed deprecated file option from MessageOptions

src/structures/Guild.js, src/structures/OAuth2Application.js, src/structures/User.js
and removed a leftover in User#avatarURL
- ``Guild#splashURL`` is no longer a getter because it's now accepting an options object.
- ``OAuth2Application#iconURL`` now accepts an options object.
- Same for ``Guild#iconURL`` ^
- Removed a small leftover in ``User#avatarURL``
=> Made (hopefully) all url related methods accept an options objects

src/structures/Webhook.js
Moved a wrongly placed closing parenthesis to get a full message object back when sending a message with a webhook.
=> Fixed wrong parenthesis for Webhook#send and Webhook#sendSlackMessage

src/client/websocket/WebSocketConnection.js
if someone working with the raw event needs something from the cache for some reason, it won't be there, so we call raw *after* cache processing happens
=> move raw call so that any cache events happen before

src/client/websocket/WebSocketConnection.js
Currently throws a TypeError, since apply does not return the function with the correct context like bind does, but directly invokes it.
=> functions for setTimeout should get the context bound and not applied

src/client/Client.js
Updated a typo made by gawdl3y in the documentation of client.voiceConnections collection
proofed by aemino
=> Fix typo in client.voiceConnections docs

src/errors/Messages.js, src/structures/MessageEmbed.js, src/structures/interfaces/TextBasedChannel.js
Notable changes
- Removed the `EMBED_FILE_LIMIT` error message
- Made the `MessageEmbed#timestamp` an actual timestamp instead of a date
- (docs) `MessageEmbed#fields` should not be optional (it defaults to an empty array)
- Changed `MessageEmbed#attachFile` to `MessageEmbed#attachFiles`, which appends to `MessageEmbed#files` on multiple calls like addField.
Maybe the error should be kept since one can only use up to 3(?) different images in an embed?
=> fixed MessageEmbed#timestamp and changed attachFile to attachFiles

src/structures/MessageEmbed.js
As @BobbyWibowo mentioned sending a received embed results in this error:
```
Invalid Form Body
embed.timestamp: Could not parse 1500218461229. Should be ISO8601.
```
This is because I forgot to account for that in #1670, this will take care of that as well as convert a set date via ``MessageEmbed#setTimestamp`` to milliseconds, like the typedef of ``MessageEmbed#timestamp`` suggests.
=> Fixing MessageEmbed's timestamp transforming

src/structures/OAuth2Application.js
The documentation for the OAuth2 application were stating the secret is a boolean, which does not make sense. They now say it is a string as supposed to be.
=> Fix docs for Application secret type

src/structures/Guild.js
<guild>.afkChannelID returns an ID as an string what should be declared as an Snowflake in the docs
=> afkChannelID returns a Snowflake rather than an string

src/structures/GroupDMChannel.js
like my last PR <GroupDmChannel>.applicationID and <GroupDmChannel>.ownerID return both an ID as an string what should be declared as an Snowflake in the docs
=> .applicationID and .ownerID return a Snowflake rather than a string

src/structures/Guild.js
As mentioned in #1669.
The `options` paremeter for `Guild#fetchMembers` should be optional.
=> Guild#fetchMember's options paremeter should be optional

src/structures/GuildMember.js
Just a small enhancement that has been requested a couple of times.
Allows things like: ``someMember.addRole('someId', 'someReason');``
Instead of something like this:
```js
const roles = someMember.roles.map(r => r.id);
roles.push('someId');
someMember.edit({ roles }, 'someReason');
```
=> Adding reason parameter to GuildMember's methods

src/client/Client.js
Accessing `client.emojis` would throw an error if any guilds were unavailable.  This will check to make sure a guild is available before accessing its emojis.
=> check guild availability when aggregating client emojis

src/client/voice/ClientVoiceManager.js, src/client/voice/VoiceConnection.js
An attempt to fix #1494, this tries to help keep the Discord state and voice connection synchronous by doing the following:
if Discord sends a voice disconnect packet, but the voice connection still believes it isn't disconnected, forcefully disconnect the voice connection.
=> Handle unexpected disconnects via packets

src/client/rest/handlers/RequestHandler.js, src/client/rest/handlers/burst.js, src/client/rest/handlers/sequential.js
If the Request Handler queue was empty, this.limited was true, putting everything on cooldown until the x-ratelimit-reset time was fulfilled. This removes the check if the queue was empty from this.limited, and puts that check in the sequential/burst handlers, so that you may continue to request until you have no x-ratelimit-remaining left, or until you are globally rate limited. Whichever comes first.
**Semantic versioning classification:**  Patch
=> fix sequential and burst ratelimiters from going on timeout because the queue is empty

src/client/websocket/packets/handlers/GuildMembersChunk.js
The key of the members collection of the ``guildMembersChunk`` event is currently undefined because the raw member object does not have an ``id`` property; It's under its user property.
=> Fixed Client#guildMembersChunk's members collection's key being undefined.

src/client/rest/DiscordAPIError.js
Fixes #1725 
Allows the errors to be under a different key than `errors`.
Note to #1554: 
This looks pretty much abandoned to me, as it is broken in its current state for almost a month now.
=> Fixed DiscordAPIError#message sometimes being undefined

src/client/voice/VoiceWebSocket.js, src/errors/DJSError.js, src/errors/Messages.js
The VoiceWebSockets.js file uses the error message constructor incorrectly in 3 cases. The constructor is called with an invalid key that causes an AssertionError which crashes node.js. I added two new error message keys and replaced the error messages with the keys accordingly. This will allow the error messages to be created normally without causing an AssertionError.
**Semantic versioning classification:** Patch
=> fix node.js crash due to error messages being called with invalid error keys

src/structures/shared/SendMessage.js
replying and splitting would not work, as the lib would split before formatting the reply
=> fix reply splitting

src/structures/ClientUser.js, src/structures/GroupDMChannel.js, src/util/Constants.js
Fixes #1746
The method was expecting an array of `UserResolvable`s which is differently than the docs stated.
Going with an array of `GroupDMRecipientOptions` as it seems more natural.
Also removed an incorrect warning as the user property will be used on bot accounts.
Edit:
- Added `GroupDMChannel#setIcon`
- Fixed null handling for Group DM channel names, as they are nullable.
More commits:
- Added `GroupDMChannel#iconURL`
=> Fixed ClientUser#createGroupDM on user accounts and added some more GroupDMChannel stuff

src/client/voice/player/AudioPlayer.js
Resets the pausedTime property to 0 when the current stream is destroyed.  #1693 
=> Fixes #1693

src/client/voice/VoiceBroadcast.js
Dispatchers have a way for you to check if something is paused, but it's not currently possible to check if a Broadcast is paused without any dispatchers in it and pausing it first. This just initiates the variable like a Dispatcher :P
=> Init pause variable on VoiceBroadcast

.npmrc, src/structures/Guild.js
deprecate because it is removed in v12
=> deprecate Guild#defaultChannel

src/structures/ClientUser.js
Currently the property is not visible in the docs.
This will make them appear there.
Alternatively it probably is possible to multi line the if to only assign the settings prop when data.user_settings is existing.
I went with this solution since other user only props are being handled that way too.
=> Fix ClientUser#settings not showing up in the documentation

src/client/ClientDataResolver.js, src/errors/Messages.js, src/index.js, src/structures/Attachment.js, src/structures/MessageEmbed.js, src/structures/Webhook.js, src/structures/interfaces/TextBasedChannel.js
Adding on to #1451,  I have added an attachment structure, which enables seamless integration of files into send parameters and into embed options, removing a lot of ugliness there once was when uploading even one file.
```js
const buffer = canvas.toBuffer();
// You can insert streams now.
const pngStream = canvas.createPNGStream();
message.channel.send('Buffer test', new Attachment(buffer, 'file.jpg'));
message.channel.send('PNGStream test', new Attachment(pngStream, 'file.png'));
// You can also provide a path.
message.channel.send(new Attachment('../dog.png'));
// You may provide a buffer without any name, which will be assumed to be 'file.jpg'.
message.channel.send(new Attachment(buffer));
// You may also …
```
=> Add Attachment structure

src/structures/ReactionEmoji.js
because we should not use deleted/deprecated methods in docs 🤔 
=> updated docs for <ReactionEmoji>.toString() so it now uses send instead sendMessage in example

src/structures/Role.js
Fixes #1759 
The permissions property was missing in the data when patching a role.
Also sorted them the same way as the typedef and docs.
=> Readded permissions to Role#edit's payload

src/structures/Message.js
When adding a reaction via `Message#react` the count of the added reaction will be incremented twice, as the method itself calls the handler and the WebSocket event does too.
This will only increment if that user didn't reacted previously.
It should only fire twice for the client however.
=> No longer double increment the reaction count when the client reacts

src/client/ClientDataResolver.js, src/structures/Emoji.js, src/structures/Guild.js, src/structures/GuildMember.js, src/structures/Role.js
This will allow the user to use a `RoleResolvable` or `UserResolvable` to specify the target of an overwrite
And an array of `PermissionResolveable`s or the raw `number` for their target's permissions.
A small example: 
```js
message.guild.createChannel('something', 'text', { overwrites: [
{
allow: ['SEND_MESSAGES', 'READ_MESSAGES'],
id: message.author,
},
{
deny: ['SEND_MESSAGES'],
id: message.guild.id,
},
]});
```
Also added:
- `ClientDataResolver#resolverRole` method
- `RoleResolvable` typedef
- ~~`ChannelPermissionOverwrites`~~ `ChannelCreationOverwrites` typedef <- better names are welcome
~~Regarding the role resolver and its typedef:
This could (and probably should) be added to all other methods using roles. …
=> Improved Guild#createChannel, added RoleResolvable and fixed a bit of Emoji stuff

src/structures/ClientUser.js, src/structures/ClientUserChannelOverride.js, src/structures/ClientUserGuildSettings.js, src/structures/Guild.js, src/structures/GuildChannel.js, src/structures/User.js, src/util/Constants.js
- Used `Object.entries` over `Object.keys` as v12 is requiring node 8 and it is nicer.
- Defined and documented `ClientUserGuildSettings#Client` properly
- Removed obsolete `ClientUserChannelOverride#user` prop, which was always null anyway
- `ClientUserGuildSettings#guild` was always `undefined` as the guild object was not created when the class get instantiated.
Replaced it with `ClientUserGuildSettings#guildID`.
- `ClientUserGuildSettings#update` now uses the correct endpoint to patch
- Marked getters as `@readonly`, nullable and fixed indent wherever applicable
- Changed `ClientUserChannelOverrides` to `ClientUserChannelOverride` (singular) to make them appear in the docs in the Constants file
- Added type for …
=> Fixed a bunch of ClientUserGuildSettings stuff and its docs

src/structures/GuildChannel.js
Fixes #1769 
Multiply the local bitrate by thousand when patching a VoiceChannel as discord wants the bitrate in bits and not in kilobits.
I used  ternary here because sending `NaN` as bitrate when patching a TextChannel seems incorrect.
Also clarified that `userLimit` is for VoiceChannels only and not for GuildChannels in general.
=> Fix VoiceChannel#setName and ChannelData#userLimit is a only voice thing

src/structures/ClientUser.js
This fixes #1702 by correctly applying the password to the data object sent to the Discord API
This also fixes `<ClientUser>.setPassword` for MFA-enabled accounts by allowing the user to pass an MFA Code to the method
This also updates the token stored in `client.token` when any security related method is used on the clientUser
=> ClientUser Fixes

src/structures/Presence.js, src/util/Constants.js
- Added `GameType` typdef
- `Game#type` is now the string representation of the game type rather than its numeric value
Should I remove the `Game#streaming` getter as there are now more than two types or let it as is?
=> Add support for new game types

src/structures/ClientUser.js
Friendly reminder: This PR is for the `11.1-dev` branch. (Just to avoid confusion)
Discord changed validation for presence updates, a type for the game is now always required.
This will now send `type: 0` when no url is present rather than omitting the field.
=> Always send a type now when updating own presence

src/structures/ClientUser.js, src/structures/Presence.js
This will allow to set the new presence types `2` and `3` to be set using `ClientUser#setPresence` or `ClientUser#setGame`.
- `ClientUser#setGame` now accepts an `options` object as second paremeter with the keys `url` and `type`
- `ClientUser#setPresence` now additonaly accepts a `type` key under `data.game`
**Update:**
- The `type` key also accepts a string representation of a type
- Removed `Presence#streaming` getter as with now 4 types having just one or 4 (one for each) would be silly.
- Fixed an invalid presence type (not string) to throw an invalid message key error when attempting to throw a more descriptive error.
=> Allow to set the new game types via ClientUser#setPresence and ClientUser#setGame

src/structures/Guild.js, src/structures/Role.js
This fixes an issue with Guild#createRole where you could supply a permission (according to the docs), but it would not reflect in Discord. The role would be created, but the position would sort itself at the bottom, as you cannot create a role and set its position at the same time.
=> Fix Guild#createRole with position

src/client/rest/APIRequest.js, src/client/rest/RESTManager.js, src/client/rest/RESTMethods.js, src/structures/Emoji.js, src/structures/Guild.js, src/structures/GuildChannel.js, src/structures/GuildMember.js, src/structures/Invite.js, src/structures/PermissionOverwrites.js, src/structures/Role.js, src/structures/TextChannel.js, src/structures/VoiceChannel.js, src/structures/Webhook.js
Relevant commits:
- https://github.com/hydrabolt/discord.js/commit/0c0ec72cb88ceb679190e4bbdca2040fd2e2d4d0
- https://github.com/hydrabolt/discord.js/commit/eef87e5d97b02be63916005171a116a7ee2d2f50
- https://github.com/hydrabolt/discord.js/commit/278fe74a5859e1d5743e344586648278cb9755dd
- https://github.com/hydrabolt/discord.js/commit/66cc5b2b531eb5291453f090fbf7eb6bac7f12de
- And maybe more
I basically added a new parameter "reason" wherever possible, it's a bit ugly with optional parameters though.
As example `GuildChannel#clone`:
`clone(name = this.name, withPermissions = true, withTopic = true, reason)`
No clue how to improve that without a breaking change.
Maybe someone else has an idea.
Not too confident …
=> Backporting audit log reasons and createRole with position for 11.2

src/client/ClientDataResolver.js, src/client/rest/RESTMethods.js, src/index.js, src/structures/Attachment.js, src/structures/RichEmbed.js, src/structures/Webhook.js, src/structures/interfaces/TextBasedChannel.js
Relevant commits
- https://github.com/hydrabolt/discord.js/commit/62fc9fce6df9bca0401cdd9655c11104e8a32d3a
- https://github.com/hydrabolt/discord.js/commit/4520c801d370708bc1d914bfa2d9b61729dbdf1e
Other fixes
- Fixed a bunch of splitting issues, for example actually sending embeds and files with the last message.
- Implemented code and split options for webhook like they are stated in the docs; They were not present in the code at all.
- Some edge cases that would lead to overwriting file(s) key of the message options with embeds
=> Backporting Attachments

browser.js, src/client/Client.js, src/client/websocket/WebSocketConnection.js, src/index.js, webpack.config.js
people can now do `require('discord.js/browser')` if they are working in a webpack environment, and warnings and proper attachment to globals
=> make webpack over 9000 times better

src/client/ClientDataResolver.js, src/client/rest/RESTMethods.js, src/structures/ClientUser.js, src/structures/GroupDMChannel.js, src/structures/Guild.js, src/structures/TextChannel.js, src/structures/Webhook.js, src/util/Constants.js
Backports for #1820.
Removes a lot of duplicate code regarding setting images for the Guild, ClientUser classes and adds GroupDmChannel#setIcon.
Guild#setIcon and Guild#setSplash now accept remote URLs.
Added GroupDMChannel#iconURL getter.
=> resolveImage backport

src/client/ClientDataResolver.js, src/client/rest/RESTMethods.js, src/client/websocket/packets/handlers/Resumed.js, src/structures/Attachment.js, src/structures/ClientUser.js, src/structures/ClientUserChannelOverride.js, src/structures/ClientUserGuildSettings.js, src/structures/ClientUserSettings.js, src/structures/DMChannel.js, src/structures/GroupDMChannel.js, src/structures/Guild.js, src/structures/GuildChannel.js, src/structures/Message.js, src/structures/Role.js, src/structures/TextChannel.js, src/structures/Webhook.js, src/structures/interfaces/TextBasedChannel.js, src/util/Constants.js, src/util/Permissions.js
- Marked `ClientDataResolver#resolveImage`'s resolved string as nullable.
- Added return doc notation for `Attachment#_attach`.
- "Reverted" the wrongly cherry picked PR, which broke `ClientUser#createGuild`.
- Marked ClientUserChannelOverride and ClientUserguildSetings and ClientUserSettings `patch` method ass private and that it returns void.
- Added empty `createMessageCollector` method to `DMChannel` and `GroupDMChannel` to make it appear in the docs.
- Fixed the return notation for `GroupDMChannel#setIcon`, added one for `addUser`
and implemented `setName` and `removeUser` methods.
- Added `MessageSearchResult` typedef for `Guild#search` and `TextBasedChannel#search`
- Added `systemChannel` to `GuildEditData` …
=> Backporting, doc/bug fixes as well deprecation

src/structures/Message.js, src/structures/RichEmbed.js
Since `TextBasedChannel#send` accepts a `RichEmbed` as options parameter `Message#edit` should do that too.
Also fixed the `Richembed#file` type as it can be an Attachment, FileOptions or a string.
=> Allow Message#edit to accept a RichEmbed and fixed RichEmbed#file's type

jsdoc.json, package.json, src/client/ClientDataResolver.js, src/structures/ClientUser.js, src/structures/GroupDMChannel.js, src/structures/Guild.js, src/structures/TextChannel.js, src/structures/Webhook.js
Removes a lot of duplicate code regarding setting images for the Guild, ClientUser and GroupDMChannel classes.
Guild#setIcon and Guild#setSplash now accept remote URLs.
Also fixed unintentional breaking change with resolveFile (no longer breaking).
=> Added resolveImage to reduce code duplication

src/structures/MessageEmbed.js
Marks the video property of MessageEmbed as ready-only for documentation purposes
=> Mark video property as readonly

src/structures/MessageEmbed.js
This PR fixes the small copy paste mistake I found in MessageEmbed about the field value, which would've returned if the name wasn't a string, or the field description length was greater, instead of erroring if the value isn't defined at all, or if its length is too big.
=> Fix copy paste

src/structures/MessageMentions.js
Missing `.values()` was passing a tuple to `Collection#has`, which would never return true here.
=> Fix MessageMentions#has not returning true for role mentions

src/structures/ClientUser.js, src/structures/Guild.js, src/structures/TextChannel.js, src/structures/Webhook.js
Simplified `resolveFile` -> `resolveBase64` by using `resolveImage` wherever possible.
Also made `TextChannel#createWebhook` accept an options object as `avatar` and `reason` are both optional.
=> Simplified image resolving and used an options object when creating webhooks

src/client/Client.js, src/client/websocket/WebSocketManager.js, src/client/websocket/packets/handlers/Ready.js, src/client/websocket/packets/handlers/RelationshipAdd.js, src/client/websocket/packets/handlers/Resumed.js, src/errors/Messages.js, src/sharding/ShardClientUtil.js, src/structures/DMChannel.js, src/structures/GroupDMChannel.js, src/structures/Message.js, src/structures/TextChannel.js, src/structures/interfaces/TextBasedChannel.js, src/util/Constants.js
Fixes #1838 
- Replaced hopefully all `fetchUser`s and `fetchMessages` (couldn't find anything else) whith their respective Datastore method.
- Removed unused error messages.
- Removed no longer existing methods from Channel classes.
- Added `RESUMED` event constant
Also changed `Client#resume` to `Client#resumed` as that was a typo.
- Used event constants everywhere possible over hardcoded strings.
- Replaced mention ot `createCollector` with `createMessageCollector` as that method name was deprecated and already removed.
=> Fixed DataStore, deprecation leftovers and a bit of Event Constants

src/structures/Message.js
Make `Message#edit` also accept an `MessageEmbed` as direct options paremeter since `TextBasedChannel#send` does that too.
=> Allow Message#edit to accept a MessageEmbed as options parameter

src/structures/Message.js
If fetched via api the reactions are mapped by their unicode's as names, if from ws (or faked via `Message#react` they are mapped by their uri encoded value.
This will now key them always under their unicode.
Obviuosly only for default reactions.
=> Consistently store message reactions keyed under their unicode

src/stores/ReactionStore.js
Fixes #1856 
Wrong variable was being used when "creating" (or modifying) a MessageReaction.
=> Fixing MessageReaction#count always being 1

src/structures/Guild.js
Fixed issue where passing null to Guild#setAFKChannel, Guild#setSystemChannel and Guild#setIcon would resolve and do nothing, since the edit method was checking for truthy. Also makes the getters for each one return null if it is not set, in order to be consistent with similar getters.
=> fix removal of Guild#afk/system channels and icon

src/client/rest/DiscordAPIError.js, src/client/rest/RequestHandlers/Burst.js, src/client/rest/RequestHandlers/Sequential.js
Backported `DiscordAPIError#path` from #1577.
And fixed the burst request handler which was rejecting with the raw error instead of an DiscordAPIError when the response code was not `400`, for example a permission error which responds with `403`.
=> feat/fix: add DiscordAPIError#path and fixed Burst request handler handling api errors

src/structures/Guild.js
Should I make the getter return null as well?
I can imagine people doing `=== undefined` where this would break that for them.
=> Backporting #1863, allowing the afk and systemchannel to be set to null

src/client/Client.js, src/client/actions/GuildSync.js, src/client/rest/RESTManager.js, src/client/websocket/packets/handlers/PresenceUpdate.js, src/client/websocket/packets/handlers/Ready.js, src/index.js, src/stores/ClientPresenceStore.js, src/stores/PresenceStore.js, src/structures/ClientApplication.js, src/structures/ClientUser.js, src/structures/Emoji.js, src/structures/GroupDMChannel.js, src/structures/Guild.js, src/structures/Presence.js, src/structures/User.js, src/util/Constants.js, test/tester1000.js
Adds support for the richest of presence, switches to new presence caching
=> Rewrite presence a little bit

src/stores/ClientPresenceStore.js
When providing only a name. the type wasn't automatically set for you, as the docs declared it, so this picks up the type depending on the input. The type will be defaulted to 0.
Additionally, if the developer passes in a number for the name parameter, it will reject with an error.
=> fix: made options.type optional in ClientUser#setActivity

src/util/Collection.js
Since the return value of Collection#exists is basically just a boolean of Collection#find's result, the same documentation and arguments can and should be applied.
Also, note for semantic classification: While my commit _does_ rename one of the method parameters as part of the documentation adjustment, the functionality is **exactly** the same. This is why I have marked it as doc change and not interface change.
=> docs(Collection): Adjust exists documentation

src/structures/Emoji.js, src/structures/Guild.js
(Not sure whether refactor applies here, from the description it's the closest.)
Moved the deletion of an emoji from `Guild` to its `Emoji` instance.
Looked wrong to not have `Emoji#delete` when it would totally make sense to have it.
=> refactor(Emoji): remove Guild#deleteEmoji in favour of Emoji#delete

src/client/Client.js, src/client/actions/GuildSync.js, src/client/rest/RESTManager.js, src/client/websocket/packets/handlers/PresenceUpdate.js, src/client/websocket/packets/handlers/Ready.js, src/index.js, src/stores/ChannelStore.js, src/stores/ClientPresenceStore.js, src/stores/DataStore.js, src/stores/GuildChannelStore.js, src/stores/GuildMemberStore.js, src/stores/GuildStore.js, src/stores/PresenceStore.js, src/stores/UserStore.js, src/structures/Channel.js, src/structures/ClientApplication.js, src/structures/ClientUser.js, src/structures/Emoji.js, src/structures/GroupDMChannel.js, src/structures/Guild.js, src/structures/Invite.js, src/structures/Message.js, src/structures/Presence.js, src/structures/User.js, src/structures/Webhook.js, src/structures/shared/Search.js, src/util/Collection.js, src/util/Constants.js, test/tester1000.js
**Data Store:**
- Defined `client` property in the `DataStore`'s constructor before iterating the eventual passed iterable to avoid the client property being undefined when executing `create`.
- Moved other instantiating of store related classes into their data stores (added optional cache parameter where needed)
**(Guild)Channel Store:**
- Moved Channel instantiating to static `Channel#create` over instantiating in Channel Stores / any other files.
- `ChannelStore`'s iterable parameter in the constructor is actually a `Client`, renamed for clarity.
- Added an optional `iterable` parameter.
**GuildMember Store:**
- Fixed fetching of a single member without caching it (resolving of `FetchMemberOptions#user`)
- …
=> refactor/fix(DataStores): move instantiating of store related classes into their date stores

src/stores/MessageStore.js
The fetchPinned method of the MessageStore was broken, refering a non-existing ``message`` property of the MessageStore. It now properly references the channel property instead.
=> fix(MessageStore): Fix fetchPinned method and add notice.

src/util/Collection.js
* baba723
In the rest of the library, the `typeof` constructor is used to ensure values are not undefined, as opposed to strictly checking for an undefined value.
This commit changes deviating type checks to use typeof operators.
* c02d351
`Number.isInteger()` method will return false if the parameter's type is not a number. Thus, there is no need to check for number type in the previous if statement.
This commit removes any if statements that check for number type before a positive integer parameter check.
=> Fix code inconsistencies and redundancy in util/Collections.js.

docs/general/welcome.md
11.2.0 docs were missing a few line breaks now that trailing whitespace was removed from them in 4778a47.
=> Fix whitespace in 11.2.0 welcome docs.

src/client/Client.js
The sharding variables were assigned to the copied from options paremeter which is not referenced by `this.options` in the client.
Now assigning to `this.options` instead.
=> fix(Client): apply shardId and shardCount to the correct options object

src/client/websocket/packets/handlers/UserGuildSettingsUpdate.js, src/structures/ClientUser.js, src/structures/ClientUserGuildSettings.js
- avoid uncaught exception when patching user guild settings for newly joined guilds and group dms _(yes, user **guild** settings for group dms)_
- made the client for consistency first parameter in ClientUserGuildSettins' constructor
- patch the ClientUserChannelOverride instances if possible instead of creating a new one on every update
=> ClientUserGuildSettings: avoid uncaught exception and a bit of refactoring

src/util/Collection.js
Fixes:
- firstKey was using a [non-existent "iter" Map method](https://github.com/hydrabolt/discord.js/blob/3a503ef56e40277f1fad428036b4ae455f4b65a0/src/util/Collection.js#L86) instead of the ["keys" Map method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/keys)
- Adjust documentation to make clear that you don't need to pass ``undefined``, because someone may have interpreted it as literally passing ``count`` (now ``amount``) as ``undefined``
Changes:
- No more type checking (standard JS RangeError is output)
- other Methods in the lib also don't typecheck, for example Role#setColor, Emoji#setName or even JS internals like Math.round() and Math.floor()
- Negative count for …
=> feat(Collection): Negative amounts plus fixes and refactor

src/client/WebhookClient.js, src/structures/Webhook.js
Fixing a TypeError stating that class constructor's can't be called without using new by using a static applyToClass method.
Alos updated the example to no longer use a no longer existing method.
=> fix(WebhookClient): use applyToClass instead of multiple inheritance

src/structures/Guild.js
Fixes a typo in `guild.unban`, which had `resolverID` instead of `resolveID`.
=> Fix resolveID typo in guild.unban

src/client/Client.js
Just makes `client.emojis` be an EmojiStore.
=> Fix for emojis not being an EmojiStore

src/stores/DataStore.js
The DataStore resolveID method was for some reason using a non-existing ``channel`` variable and thus it always errored if the parameter was a string. This PR fixes the method to use the correct variable.
=> fix(DataStore): make resolveID work properly

src/structures/GuildChannel.js
You can now delete any channel you want, even if its ID is the same as the guild ID.
This PR just fixes the <Channel>#deletable property returning false when it should return true
=> Fix check for GuildChannel#deletable

src/stores/EmojiStore.js
EmojiStore#create is currently returning undefined which results in `Client#emojiCreate` and `Guild#createEmoji` emitting/returning undefined instead of an emoji.
=> fix(EmojiStore): return super.create in the create method

src/errors/Messages.js, src/structures/GuildChannel.js
Adds a getter to test if the channel is locked (syncing with the category channel in the client);.
Adds a method to lock into the category channel's overwrites.
Fixes a bug where \<GuildChannel\>.edit was using the calculated position instead of the raw position to patch.
=> Channel permissionLock support (syncing with category permissions)

.npmrc
fix .npmrc to *actually* not create package-lock.json
=> Fix .npmrc to not create package-lock.json

src/stores/ReactionStore.js
This was causing issues when resolving emoji identifiers for default emojis.
For example when removing a reaction; Trying to do so rejected with `"P"` is not a valid Snowflake.
Also MessageRection#id is stated as nullable `Snowflake`, which a unicode not is.
=> fix(Reactions): make MessageRection#id again null for default emojis

src/client/ClientManager.js, src/errors/Messages.js
When the client's connection to the gateway times out after 5 minutes, reject with an error stating that isntead of saying that the token was invalid.
Also reject when the WebSocket emits an error, like a connection failure.
=> fix(ClientManager): reject login with proper error on timeout or on connection failure

src/client/BaseClient.js, src/client/Client.js, src/stores/ClientPresenceStore.js, src/stores/GuildChannelStore.js, src/stores/GuildMemberStore.js, src/stores/PresenceStore.js, src/structures/CategoryChannel.js, src/structures/GuildAuditLogs.js, src/structures/Presence.js, src/util/Constants.js
This PR fixes a small typo in the type for GuildAuditLogEntry#target and CategoryChannel#children, amongst other things
~Also, quick question: Shouldn't the `target` return a message object when the `targetType` is `MESSAGE`?~ Nevermind, it apparently returns a user ID
=> docs: Fix some small typos or "missing" docs

src/client/ClientManager.js
`client.ws.connection.ws.once` is bad but `this.client.ws.connection.once` is good
=> fix typo in ws manager

src/structures/PermissionOverwrites.js
This PR just adds `OverwriteType`, a small typedef that shows all the possible returns of PermissionOverwrite.type
=> docs: Small doc improvement for PermissionOverwrites

src/stores/GuildMemberStore.js
~~Tries to resolve a member, which is uncached, so \<MemberStore\>resolveID returns null if using anything but an id, forcing fetch to move on and fetchmany the whole guild, instead of the one missing member we were looking for.~~
Fails at fixing 1870, but fixes member resolving as null, and instead of fetching the single member, it fetches the whole guild. This changes resolving to a user resolvable instead of member, so that the single user can be fetched instead of the whole guild. (matching current and past documentation suggesting the arg should be a user resolvable)
=> Rip, fixes a bug we didn't even know to look for... 1870 lives on.

src/structures/Role.js
Missed a deprecated method removal, and another that should be removed too.
~~\<role\>.hasPermission was marked as deprecated (incorrectly? it didn't show up in docs as deprecated).~~ and \<role\>.serialize() doesn't even make sense (OOP context). Especially when it's just an alias for \<role\>.permissions.serialize(), and all of the other permission based methods were deprecated and meant to be removed in favor of the permissions instance/methods.
**edit:** mis-read line 149 as meaning the whole method was deprecated, instead of that one argument. However, the method as a whole still doesn't really belong/should use \<role\>.permissions.has()...
=> Missed a deprecated method removal

src/structures/GuildMember.js
After `role.hasPermission` died, this check here did as well. This just fixes that by changing `hasPermission` to `permissions.has`.
=> Fix for a small hasPermission error

src/structures/MessageEmbed.js
Sending one or multiple large buffers will reject with `413: Request Entity Too Large` because the `files` property of the embed will be sent as part of `payload_json`.
That embed itself should not contain any attached files, simply removing them resolves that issue.
The file(s) will still be attached to the message like usually: [here](https://github.com/hydrabolt/discord.js/blob/master/src/rest/APIRequest.js#L35)
=> fix(MessageEmbed): don't send 'files' as part of the embed

src/index.js
Since Discord.js is exporting Collections and DataStore's are a pretty easy to use & extend DataStore Model, would i like to add it to the discord.js exports so users can use it in code as an Storage if they want (like Collections).
=> Export DataStore from the Discord.js module

src/structures/interfaces/TextBasedChannel.js
Allow to directly pass an array of IDs to `TextBasedChannel#bulkDelete`.
As well as not to error when none or one message(s) (id(s)) are being passed.
A single message will be deleted on its own and when no messages are being passed an empty collection will be returned.
This is motivated duo the `filterOld` parameter can result in all or all except one messages being filtered out, which would reject with above mentioned error.
Also moved the `isNaN` block below the main logic because isNaN would return false for an array with a single message id. ~~(JavaScript being great like usual)~~
=> enhancement/feature(bulkDelete): accept array of ids and handle case of 0 or 1 message(s)

src/structures/ClientUser.js
The `ClientUser#fetchMentions` calls and endpoint that is reserved to user accounts. However, the documentation does not mention it. This PR adds the warn message to said method.
=> [Documentation] Added a warn in fetchMentions

src/structures/GuildChannel.js, src/structures/Role.js
Fixes a major? typo in GuildChannel#setPosition and in Role#setPosition
=> fix: setPosition taking wrong IDs and edit with position 0 breaking

src/structures/Message.js
Small typo in `Message.awaitReactions()`
Changed: **"Similar to createMessageCollector but in promise form."**
To: **"Similar to createReactionCollector but in promise form."**
=> Typo in Message.awaitReactions docs

src/structures/Role.js
Fixed a simple typo where in the actions handler, it was expecting roles instead of the given channels from Role#setPosition.
=> fix(Role): setPosition typo

src/structures/GuildAuditLogs.js
Aimed to fix one thing, which was an undefined `this` reference within a `GuildAuditLogsEntry` structure. This passes a reference to it correctly to obtain the `webhooks` property from `GuildAuditLogs`.
Additionally ended updating Audit Logs for deleted webhook events, which provide nothing, so now there is a basic Webhook object returned at the end, if none is available.
=> fix(GuildAuditLogs): incorrect webhook reference

src/client/websocket/WebSocketConnection.js
i may have slightly misread the 120/60 ratelimit as 60/120
=> fix websocket ratelimits

src/client/Client.js, src/client/ClientManager.js, src/rest/RESTManager.js
`BaseClient` already defines the `rest` property, doing it again in `Client` is redundant.
See [source](https://github.com/hydrabolt/discord.js/blob/master/src/client/BaseClient.js#L25).
Also noticed that [`RequestHandler`](https://github.com/hydrabolt/discord.js/blob/master/src/rest/handlers/RequestHandler.js) no longer has a destroy method, thus removing a pointless method call including a loop.
=> refactor: remove redundant Client#rest and obsolete RESTManager#destroy

src/structures/Webhook.js
As requested in #2037 added `options.channel` in `Webhook#edit`.
With this it's now possible to change in which channel a webhook is in.
=> feature(Webhook): allow to edit the channel of webhooks

src/client/actions/GuildDelete.js
This seems to fix #1939
Maybe this also fixes #1870 (If those guilds are guilds that the bot left and joined)
Changes:
- Remove all channels of the left guild from `Client#channels`.
- Disconnect the voice connection if there is one.
Explanation:
Kicking a bot and readding it resulted in all guild channels being still in `Client#channels` with their old `GuildChannel#guild` reference.
Rejoining would not update those old channels because `ChannelStore#create` would just patch them.
Keeping channels after the bot left a guild seems unintended anyway.
A still active voice connection would not be disconnected by kicking the bot, the voice WebSocket on discord's seems not to care about it.
Joining to a different voice …
=> fix(GuildDelete): disconnect voice and cleanup GuildChannels

src/structures/GuildMember.js
The Discord API seems to send a timestamp of 0 for the joined_at on presence updates. This patch resolves this by ignoring timestamps of 0/null/undefined.
=> Patch timestamp of 0 on guild join date

src/structures/GuildChannel.js, src/structures/Role.js, src/util/Util.js
This PR fixes the `edit({ position: 1 })` issues, where editing a position would do nothing.
Now, if position wants to be changed, it'll attempt to change it, and if it was able to move the channel, it'll continue with the rest of the edit.
Tested and it works as expected. Works with other options as well.
This is probably janky, but it works as intended now. ~I might have to change some docs for the meaning of the position param~
This should also fix #1974 
=> fix(GuildChannel|Role.edit) Editing with a position not being right

src/client/actions/MessageDeleteBulk.js
This fixes #2036
The bulk delete action doesn't remove the deleted messages from the cache.
This causes the call to the bulk delete action from `TextBasedChannel#bulkDelete` to fire the event the first time and the gateway event to fire it the second time.
Removing the deleted messages from the cache resolves the issue. 
_Not like they were supposed to stay there in the first place._
=> fix(MessageBulkDeleteAction): remove deleted messages from cache

src/client/Client.js
Was changed from stable for some reason, didn't allow the passing of the token through environment variables (something useful in sharding) and just threw an error when trying to login without providing a token there.
=> fix(Client): login not using env.token

src/structures/GuildChannel.js, src/structures/TextChannel.js
Adds a method to set the NSFW flag on TextChannels. It should be merged because I want it to be.
=> Add TextChannel#setNSFW method

src/client/voice/VoiceBroadcast.js, src/client/voice/VoiceConnection.js, src/client/voice/dispatcher/BroadcastDispatcher.js, src/client/voice/dispatcher/StreamDispatcher.js, src/client/voice/player/AudioPlayer.js, src/client/voice/player/BasePlayer.js, src/client/voice/player/BroadcastAudioPlayer.js
Patches `BasePlayer#playUnknownStream` to handle streams of type string as arbitrary FFmpeg input. (also removes useless constructor param)
=> handle string ffmpeg input

src/structures/GuildMember.js
`GuildMember#hasPermission` would pass three parameters to `Permissions#has`, which only accepts two, making it impossible to disable the admin check.
Also removed the deprecated parameter `explicit` of the method itself.
=> fix(GuildMember#hasPermission): pass correct parameters to Permissions#has

src/structures/ClientUser.js, src/structures/User.js
This is more organization, but the user._patch method attempts to change the client.token if there is a data.token property, which should only come on a ClientUser._patch. So the check/assign moved to the ClientUser._patch instead...
=> user._patch shouldn't try to touch the token

src/structures/User.js
user.bot was either undefined or true, never false for user users. Also, double checked user.avatar for a similar bug, but discord sends null if someone unsets an avatar. So the code works, but the docs now reflect that the property is nullable.
=> Fix user.bot

src/structures/GuildMember.js, src/structures/Presence.js, src/structures/User.js
This (hopefully) fixes #2058 
https://github.com/hydrabolt/discord.js/blob/ee1d4c53f2770b5e4748d0d7402dc0291f9f869e/src/structures/Presence.js#L22
https://github.com/hydrabolt/discord.js/blob/243ff48a67446fba96da91503670cea0aba3a968/src/structures/Presence.js#L17
These two would explain why presences can have an `undefined` status:
- Solved by defaulting to `offline` again.
The `client` property can be undefined beacuse `GuildMember#presence` and `User#presence` default to `new Presence()` when no other presence was found and didn't pass the client to the constructor.
- Solved by passing the client to the constructor.
=> fix(Presence): pass client and default to offline

src/client/ClientManager.js, src/stores/ChannelStore.js, src/stores/DataStore.js, src/stores/EmojiStore.js, src/stores/GuildChannelStore.js, src/stores/GuildMemberStore.js, src/stores/GuildStore.js, src/stores/MessageStore.js, src/stores/PresenceStore.js, src/stores/ReactionStore.js, src/stores/RoleStore.js, src/stores/UserStore.js, src/structures/ClientApplication.js, src/structures/Guild.js, src/structures/GuildAuditLogs.js, src/structures/GuildMember.js, src/structures/MessageEmbed.js, src/structures/Presence.js, src/structures/Webhook.js
- `DataStore#resolveID` (and classes extending from it) are return `Snowflake`s
- Document `ClientManager#status` as readonly
- `ClientApplication#resetToken` and `ClientApplication#resetSecret` are returning a Promise
- `Guild#features` is an array of strings
- `Guild#ban` no longer accepts a number or string
- `GuildMember#ban` ^
- Fix `MessageEmbed#files`' docs, so it actually appears on the site
- `MessageEmbex#hexColor` is nullable
- `RichPresenceAssets#largeImage` and `RichPresenceAssets#smallImage` are `Snowflake`s
- `RichPresenceAssets#smallImageURL` and `RichPresenceAssets#largeImageURL` both accept an options object for the url formatting, not two parameters
- `WebhookMessageOptions` no longer has a …
=> Documentation improvements

src/structures/ClientApplication.js, src/structures/DMChannel.js, src/structures/Emoji.js, src/structures/GroupDMChannel.js, src/structures/Guild.js, src/structures/GuildChannel.js, src/structures/GuildMember.js, src/structures/ReactionEmoji.js, src/structures/Role.js, src/structures/User.js
This PR normalizes the docs examples for the `.toString()` method on all classes. Additionally, the ES5 examples were removed, and classes that were missing an example before now have one.
=> docs: Add/normalize .toString() docs on all classes

src/structures/interfaces/TextBasedChannel.js
This fixes #2040
Calling TextBasedChannel#startTyping now returns a promise.
This promise resolves when the bot stops typing (TextBasedChannel#stopTyping) or rejects when an error occurs.
Calling the method again returns the same promise as long the bot is still typing.
This is probably not the most elegant solution.
I am open for any suggestions.
Edit:
I also clarified what the count parameter is actually doing and how it is working.
=> fix(TextBasedChannel): return a promise in startTyping and clarify count parameter

src/structures/Webhook.js, src/structures/shared/CreateMessage.js, src/structures/shared/SendMessage.js
- `WebhookClient` is no longer instanceof `Webhook`, it's now extending `BaseClient`. 
Another instanceof is needed here.
- Read the correct property (`avatar_url`) to reflect per message avatar changes with webhooks.
- Removed deleting/setting to null of some options.
If that is in any way necessary, feel free to enlighten me.
- Readded message chunk sending (used when using SplitOptions).
=>  fix(Split/Webhook): readd message chunk sending and fix webhook avatar/username

src/structures/ReactionCollector.js
This will emit an event when a user removes a collected reaction. This is in addition to Collector#dispose, which will only fire when all users have unreacted to the same emoji.
Closes #2056 
=> emit ReactionCollector#remove on all unreactions

src/sharding/Shard.js
The Shard class is intended to emit events, but doesn't extend EventEmitter,
making it not possible to use sharding.
This PR resolves that issue by extending EventEmitter.
=> fix(Shard): extend EventEmitter to be able to emit events

src/client/BaseClient.js, src/client/Client.js, src/client/WebhookClient.js, src/rest/handlers/RequestHandler.js, src/structures/ClientUser.js, src/structures/Guild.js, src/structures/GuildMember.js, src/util/Constants.js
Fixes some return types for functions, defaults for the WebSocket options and ClientUser#fetchMentions, as well as return an error when someone tries running Guild#allowDMs on a bot account
=> docs: Fixed some missing docstrings or incorrect return types

src/structures/Channel.js, src/util/Structures.js
Individual channel types would extend a vanilla Channel, rather than an ExtendedChannel. This change gives more flexibility, and fixes the inconsistency by allowing each individual channel type to be extended, rather than the base Channel class (and then the types incorrectly extending the vanilla Channel).
=> Fix inconsistency with Channel Creation: CustomStructures

src/structures/MessageMentions.js
Previous `strict` option ignores both roles and everyone/here.  
New options allow ignoring individual kinds as well as direct mentions.  
=> Add more options to MessageMentions#has

src/structures/Guild.js, src/structures/GuildMember.js
Removes the whole `string or number` thing for `member.ban`. Because that's just deceiving.
=> docs: Remove leftover docstring from 11.2

src/structures/ClientUser.js, src/structures/Guild.js, src/util/Constants.js
Enables you to set `watching` and `listening` via either number form or via strings in `ClientUser#setPresence`. This also deprecates `ClientUser#setGame` in favour of `ClientUser#setActivity`
=> feature(ClientUser): deprecate ClientUser#setGame in favour of ClientUser#setActivity

src/structures/Guild.js
added a new typedef for Discord Bans because it looks cleaner than write it in the description and fixed a little typo in fetchAuditLogs.type type so its now correct and clickable
=> added a new Typedef for Bans you can get from <Guild>.fetchBans() and fixed a little typo in the fetchAuditLogs() method

src/stores/DataStore.js
fixes #2136 as Channel is not an extendable structure, all of the child structures are. Structures.get('Channel') returns undefined.
=> Fix channels.resolve

src/client/ClientDataManager.js
Fix for #2122, didn't return channel, so it sometimes returned null depending on the duplicate events that we get
=> fix(guild#createChannel): new channel returning null

src/client/rest/RESTMethods.js
Self explanatory. Caused various voice channel methods to fail because the edit method was setting the incorrect bitrate.
=> fix(VoiceChannel#edit): incorrect bitrate

src/client/ClientDataResolver.js, src/client/rest/RESTMethods.js, src/structures/Guild.js, src/structures/GuildChannel.js
Make this method not the atrocious garbage it currently is in stable. Mainly in the way that it takes an array of strings rather than forcing you to input a number (and it being poorly documented anyway)
I also made GuildChannel#overwritePermissions return a GuildChannel, instead of a buffer, because that was weird and stupid.
=> Backport: Guild#createChannel

src/client/websocket/packets/handlers/UserGuildSettingsUpdate.js
Fixes #2139 and #2140 (same thing), where the guild settings were not being properly instantiated if you recently joined a guild after the user bot was running and then tried to do some user setting stuff.
=> fix(UserGuildSettingsUpdate): not creating settings with new guilds

src/structures/shared/CreateMessage.js
Fixes  #1986, #2156 simultaneously and re-adds the feature of being able to send attachments as an array directly, as originally intended.
=> fix(CreateMessage): fix attachment and array sending

src/structures/GuildChannel.js, src/structures/VoiceChannel.js
instead of mixed kbps/bps
Makes the methods consistently use bps for bitrates.
=> Make all VoiceChannel bitrates in bps

src/structures/shared/CreateMessage.js
Fix for #2158, which broke `message.reply()` (it didn't mention anymore), so now it does again. Hurrah.
=> fix(CreateMessage): reassigning wrong content

src/client/rest/RESTMethods.js, src/structures/Guild.js
Re-adds the functionality from stable where not providing a channel type would default to `text`. Ironically, this is also incorrectly documented in stable. Also updated return type since we can also make categories with this method.
=> fix(Guild#createChannel): default to text

src/structures/interfaces/TextBasedChannel.js
Self-explanatory title. `BulkDelete` would attempt to mass delete 1 or 0 messages and reject regardless of ignoring old, so now it does (not reject).
=> fix(bulkDelete): stop rejections when filterOld=true

src/client/voice/receiver/VoiceReceiver.js
backporting the fix for #1310 to let people actuall use voiceReceiver on 11.3
=> backporting the fix for RTP header extensions

src/structures/Guild.js
Self-explanatory title. Keeps this behavior from stable to default to type 'text'.
=> fix(Guild#createChannel): default type to 'text'

src/structures/Message.js
It is not possible to edit a messages attachments in Discord after a message has been sent, discord.js however, does provide such functionality! (or at least tries to)
The docs for Message#edit say you can pass it a MessageEmbed, however if that embed contains attachments it breaks. Files should not be sent along with the `edit` request.
**Steps to reproduce:**
```js
const embed = new MessageEmbed()
.setTitle('foo')
.setDescription('bar')
.attachFiles(['src/assets/icons/play.png'])
.setThumbnail('attachment://play.png')
const m = await msg.channel.send(embed)
embed.setDescription('baz')
setTimeout(() => m.edit(embed), 1e3)
```
**Result:**
```
[00:31:37 DiscordAPIError] Invalid Form Body; CONTENT_TYPE_INVALID: …
```
=> Don't send files in edit request

src/structures/interfaces/Collector.js
checkEnd should be called whether or not a message passes the filter because the number of message processed is also updated by collect.  For instance, currently messageCollector keeps running even if it has reached the limit of processed messages if none of them passes the filter.
=> Fix Collector bug where checkEnd is only called on a valid message

src/structures/GuildMember.js
For consistency's sake, instead of two optional additional parameters, the method now takes one object.
=> GuildMember#hasPermission takes object

src/client/rest/RESTMethods.js, src/structures/MessageReaction.js, src/util/Constants.js
Commits:
- https://github.com/hydrabolt/discord.js/commit/f40a5e9f8875299aa6ec25a0491e4dc92868f54d
- https://github.com/hydrabolt/discord.js/commit/5cd42695aeb974e998d4b220cba1c27b30a55628
Summary:
- `MessageReaction#fetchUsers` now accepts as second argument an object with the optional keys `after` and `before` to allow fetching of more than the first 100 users.
- Internally moved its querystring building from Constants to RestMethods in favour, it's only used from that method anyway.
This resolves #2214 for 11.3; In master it's already possible to do so.
=> feat: backport after and before parameter when fetching a reaction's users

src/structures/Emoji.js, src/util/Constants.js, src/util/Util.js
Backporting support for animated emojis and their parsing via `Util.parseEmoji`.
See: #2182 / https://github.com/hydrabolt/discord.js/commit/84e4dd6a998294e8a9a50c885006c1a908ba09ba
Summary:
- Added `Emoji#animated`
- `Emoji#url` now correctly uses a `.gif` extension for animated emojis
- `Emoji#toString` now correctly includes an `a:` for animated emojis
- `Util.parseEmoji` now accounts for animated emojis and its returned object includes an `animated` boolean property
=> feat: backport animated emojis support

src/rest/APIRequest.js
Whenever gen() is called more than once (i.e. retrying after ratelimited) the query string is appended on extra times which breaks things.
=> Fix query string on requests after ratelimited

src/util/Util.js
Fixes #2228
The current regex does not match identifiers `name:id`, this will now allow it to.
=> fix: allow the Util#parseEmoji regex to match emoji identifier

src/client/websocket/packets/handlers/VoiceStateUpdate.js
Issue where creating a new voice channel (and then connecting to it) would not have the member set in the guild's perspective. This should ensure it's appropriately updated.
=> fix(voiceStateUpdate): incorrect members.size

src/structures/GuildChannel.js, src/structures/GuildMember.js
#2216 broke member.ban() and channel.clone(), this fixes them
=> Fix member.ban() and channel.clone()

src/sharding/Shard.js, src/sharding/ShardClientUtil.js
`eval((client) => client.token)` > `eval('this.token')`
=> allow functions in shard eval yay

src/stores/GuildChannelStore.js, src/stores/RoleStore.js, src/util/Permissions.js
Permissions#resolve() fix. Using 'this' inside of Array#map() doesn't work except if thisArg is provided to the map function.
=> Fix destructuring errors in GuildChannelStore and RoleStore

src/structures/Guild.js
Changed `Collection` to `RoleStore`
=> Guild#roles Documentation Has The Old Class

.gitignore, src/sharding/ShardClientUtil.js
There is a small typo in the broadcastEval method. 
It should be 
```
script = typeof script === 'function' ? `(${script})(this)` : script;
``` 
instead of 
```
script = typeof script !== 'function' ? `(${script})(this)` : script;
```
Additionally adding `.idea` to the .gitignore file, so that also jetbrain products like Webstorm and Idea are ignored (additionally to vscode)
=> Fix ShardClientUtil#broadcastEval - now really accepting functions

src/client/actions/GuildEmojisUpdate.js
Maps take iterables; and DataStores, collections, and maps are all iterables. Meaning we can pass the collection into a new Map() instead of using a function to create a map from the map.
=> Remove pointless function from GuildEmojisUpdate

.eslintrc.json, src/structures/MessageCollector.js, src/structures/ReactionCollector.js, src/structures/interfaces/Collector.js
This PR fixes the `ReactionCollector#remove`, it is now possible for it to emit!
Plus it now emits the user who removed the reaction as a second argument.
---
I also took the liberty of adding another possible property to the `options` object passed to the `Collector` constructor: `emitOnlyArgs`. It is not really a property that should be used by the lib users.
The property tells the collector whether to emit the element that was collected/disposed, as a separate argument or not. Some collectors collect the values that they receive without processing them into something else, which is why it is not necessary to emit those elements separately from the arguments because we're emitting the same object as 2 separate …
=> Fix ReactionCollector#remove and make Collector interface more consistent

src/util/Permissions.js
- Added `Permission#toArray`.
- Allow singular `PermissionResolvable`s as parameter to `Permissions#missing`.
- Fix JSDoc.
- Allow `Permissions` to be iterated over.
- Removed unnecessary (and bugged) conditional statement in constructor. (could accept negative bitfields before)
- [Updated typings](https://github.com/ZLima12/discord.js-typings/tree/permissions-improvements) will be submitted as a PR when/if this one gets merged.
=> Permissions improvements

src/client/Client.js, src/client/actions/GuildEmojiCreate.js, src/client/actions/GuildEmojiDelete.js, src/client/actions/GuildEmojiUpdate.js, src/client/actions/MessageReactionAdd.js, src/errors/Messages.js, src/index.js, src/stores/GuildEmojiStore.js, src/structures/Emoji.js, src/structures/Guild.js, src/structures/GuildAuditLogs.js, src/structures/GuildEmoji.js, src/structures/MessageReaction.js, src/structures/ReactionEmoji.js, src/util/Structures.js
Create new `Emoji` class as base for `GuildEmoji` and `ReactionEmoji` to avoid code duplication
Summary:
- Renamed `Emoji` to `GuildEmoji`, refelects in [Structures](https://github.com/hydrabolt/discord.js/pull/2230/files#diff-3bc3a95553c59d189184dba493493738L64)
- Created new `Emoji` class to avoid code duplication between `GuildEmoji` and `ReactionEmoji`
- Both `GuildEmoji` and `ReactionEmoji` extend said `Emoji` class
- Renamed `EmojiStore` to `GuildEmojiStore` to stay consistent with the class' name `GuildEmoji`
TODO:
=> Base Emoji class for ReactionEmoji and renamed GuildEmoji classes

src/structures/ClientUser.js
`ClientUser#setPresence` in master branch (latest) calls `client.presences.setClientPresence`,
but that in v11.3 does not.
so i change parameter sent to `setPresence` for clearing the game activity,
from `activity:null` to `game:null`,
for now until setPresence function gets updated
=> [v11.3.x] Fix param sent to setPresence in setActivity

src/stores/ChannelStore.js, src/stores/ClientPresenceStore.js, src/stores/EmojiStore.js, src/stores/GuildChannelStore.js, src/stores/GuildEmojiStore.js, src/stores/GuildStore.js, src/stores/PresenceStore.js, src/stores/ReactionStore.js, src/stores/RoleStore.js
Some DataStore Classes with important functionality are private, that causes the docs to not show it via the Searchbar and this should be changed.
~~If requested i could also make the other Stores not private anymore to stay consistent.~~ [Done]
=> Fix DataStores to be not private anymore.

src/structures/GuildChannel.js
The PR #2259 missed a little thing: if `options.parent` is given as `null` and the GuildChannel to clone has a parent, it'll default to it instead of being cloned as a channel with no parent, due to the usage of `||`.
=> Fix(GuildChannel#clone) options.parent not accepting (falsy) null.

src/client/Client.js
Fixes a stable documentation error describing `client#voiceConnections` as a collection of voice channels mapped by voice channel ID while it's actually mapped by guild ID now.
=> fix(client#voiceConnections): Incorrect docs description

src/index.js, src/stores/GuildMemberRoleStore.js, src/stores/RoleStore.js, src/structures/Guild.js, src/structures/GuildMember.js
This PR moves a few member role related functions to a new store, for consistency.
Also, should I rename the `GuildMemberRoleStore#highestRole`, `hoistRole` and `colorRole` to remove the role part? For some reason, it sounds better with and without. /shrug
Also, should I rename the store? It may be a little big too.. "big" for a name. But at the same time it represents exactly what it stores.
A list of what changed:
- `GuildMember#addRole` -> `GuildMemberRoleStore#add`
- `GuildMember#addRoles` -> `GuildMemberRoleStore#add` (it supports arrays OR one item only)
- `GuildMember#setRoles` -> `GuildMemberRoleStore#set`
- `GuildMember#removeRole` -> `GuildMemberRoleStore#remove`
- `GuildMember#removeRoles` -> …
=> refactor: Move member role-related functions to a special store

src/structures/GuildMember.js, src/structures/Role.js
Someone forgot to update the usages of `highestRole` in permission checking 👀 
=> fix(Role): Update usages of highestRole#comparePositionTo to use GuildMemberRoleStore

src/index.js, src/stores/DataStore.js, src/stores/GuildEmojiRoleStore.js, src/structures/GuildEmoji.js
This PR moves all emoji role related functions to a new store, called `GuildEmojiRoleStore`.
Due to how Discord works, you need to reload your client if you have the role required to use the emoji.
A list of what changed:
- `GuildEmoji#addRestrictedRole` -> `GuildEmojiRoleStore#add`
- `GuildEmoji#addRestrictedRoles` -> `GuildEmojiRoleStore#add` (it supports arrays OR one item only)
- Added `GuildEmojiRoleStore#set`
- `GuildEmoji#removeRestrictedRole` -> `GuildEmojiRoleStore#remove`
- `GuildEmoji#removeRestrictedRoles` -> `GuildEmojiRoleStore#remove` (as `GuildEmojiRoleStore#add`)
=> GuildEmoji: Move all role related functions to a separate store

src/util/Util.js
Since the context of a static function is the same as referencing the class variable, there's no reason to use `this` inside of it. This also makes it so that you can destructure them from the Util class and they will still work as intended. Mostly a developer standpoint here since the methods are private and would really only be used by someone who knows what they are doing.
I don't think this follows any of the versioning guidelines below.. so just going to leave these blank
=> Fix Destructuring Errors in Util

src/util/Util.js
The `splitMessage` method sometimes fails to deliver desired output because it does not take into account the length of the separator and that of the prefix and postfix (`prepend` and `append`).
**Examples**:
1.
```js
send(`${'a'.repeat(999)} | ${'b'.repeat(999)}`, { split: { maxLength: 2000, char: ' | ' } })
```
The separator is 3 characters long, the method only counts it as one making the message exceed 2k characters.
2.
```js
send(`${'a'.repeat(999)}\n${'b'.repeat(999)}\n${'c'.repeat(999)}`, { split: { maxLength: 2000, append: 'hello' } })
```
Expected to send 3 separate messages and postfix them properly, but instead it joins the first 2 parts (1998 chars) then adds the postfix (+5 chars), making it exceed 2k …
=> Make Util#splitMessage handle edge cases properly

src/errors/Messages.js, src/structures/MessageEmbed.js
This removes the length checks for the `MessageEmbed` class, since the api checks and gives decent error messages anyway.
Fixes #2299 
=> fix(MessageEmbed): remove length checks

src/structures/ClientUser.js
Currently there is no note that requesting a client users email only works with user accounts.
=> Store Mail - User Account Only

src/structures/Presence.js
This PR adds a toString method to Activity.
This allows, for example, stringifying the Activity with a fallback string without a large ternary.
As example, a probably common use case, some user info thing:
```js
const oldWay = `Current activity: ${message.author.presence.activity ? message.author.presence.activity.name : 'None'}`;
// As opposed to
const newWay = `Current activity: ${message.author.presence.activity || 'None'}`;
```
=> enhancement(Activity): add toString method

src/structures/GuildEmoji.js
Now that https://github.com/discordapp/discord-api-docs/issues/492 landed, you are able to fetch the author of an emoji.
Note: The user is not returned from the websocket on the `GUILD_EMOJIS_UPDATE` event. 
Now the question is, should the user get cached in the emoji? That can provide an interesting issue when the user doesn't fetch the author first. I feel like it's not needed, but I will still ask.
=> feature: add GuildEmoji#fetchAuthor

src/client/ClientManager.js, src/stores/ClientPresenceStore.js, src/util/Constants.js
You can give your client some presence data to use upon login via the client options, but it won't work if you try to use it the same way you would use `ClientUser#setPresence`; it'll only work if you send it the exact data the API expects (such as a `game` object instead of `activity`) . This PR normalizes that, as well as documents it in the `WebsocketOptions` typedef.
Example snippet:
```js
const { Client } = require('discord.js');
const client = new Client({
presence: {
status: 'dnd',
activity: {
name: 'YouTube',
type: 'WATCHING',
},
},
});
client.login('pleasedonthackme');
```
=> docs/feat(WebsocketOptions): Parse ws options presence

src/sharding/ShardClientUtil.js
Allow returning of promises via the `broadcastEval()` method. One good use-case:
```js
client.shard.broadcastEval(`this.channels.get('id').send('test').then(m => m.id)`);
```
This would not be possible otherwise- the developer would have to resort to other methods, such as using the api without the library convenience methods.
If there's anything I missed, do let me know, I'm fairly confident this is enough (I have had this on my production bot for over a year).
Requesting review from @Gawdl3y.
=> feat(ShardClientUtil#broadcastEval): allow promise resolve

src/client/voice/dispatcher/StreamDispatcher.js
Occasionally the timestamp of the data becomes extremely large due to this guard not doing its job because it was written wrongly. Basically the timestamp will explode in size.
This means that the timestamp + 960 becomes a number that is larger than UINT_MAX. This causes an error event to be emitted by the stream.
It may have been copypasta from a language that will simply overflow the number.
I understand that this section of the library is undergoing a rewrite from the changes occurring in master and it will likely no longer matter when the new code makes it into a release, but this bug has impacted the uptime of my bots that use it, so I am submitting this change in the interest of improving the stability of all …
=> fix what may or may not have been a typo of '+' to '<'

src/structures/GuildChannel.js
This PR adds support for the "Get Channel Invites" endpoint. ([api-docs](https://discordapp.com/developers/docs/resources/channel#get-channel-invites))
Adding a `GuildChannel#fetchInvites` method, which is "only" requires the MANAGE_CHANNEL permission, as opposed to `Guild#fetchInvites`, which requires the MANAGE_GUILD permission.
=> feat(GuildChannel): add fetchInvites method

src/util/Collection.js
This PR aims for performance improvements in the Collection -> Array conversion. In a [jsperf](https://jsperf.com/iterator-vs-array-from/1), I have achieved a 44% performance improvement by changing `Array.from(iterator)` to `[...iterator]`, using for this test, a simple iterator. Screenshot of test:
=> perf(Collection): Performance improvements

README.md, docs/general/welcome.md
Since [discordjs.guide](https://discordjs.guide/) became the official guide for d.js about 2 weeks ago, it only makes sense to add links for it on the readme/welcome page of the website.
=> docs: Add links for the guide

src/client/voice/dispatcher/StreamDispatcher.js
`StreamDispatcher#volumeChange` was not emitted when the volume changes even though `StreamDispatcher` implements `VoiceInterface` that has `volumeChange` event.
It should be emitted I think.
=> Emit StreamDispatcher#volumeChange when the volume changes

src/util/Util.js
The current implementation of `Util#discordSort()` puts objects with higher IDs before those with lower IDs if they share the same `rawPosition`, resulting in #2352. When two objects have the same `rawPosition`, the one created later (higher ID) should be put after the other. This fixes that issue.
Fixes #2352
=> Fix incorrect positions when rawPosition is same

src/stores/GuildChannelStore.js, src/structures/GuildChannel.js, src/structures/shared/resolvePermissions.js, src/util/Permissions.js
Thanks to @Tylertron1998 for noticing.
This PR replaces the original method, `GuildChannel#overwritePermissions`, to take multiple overwrites, similarly to creating a channel. In order to retain API coverage, I also made a new method, `GuildChannel#updateOverwrite`, to be what the original `GuildChannel#overwritePermissions` did.
Since there'd now be duplicate code, I refactored the main logic behind resolving permissions into a `shared` method.
Also added examples. Examples are nice.
=> feat: allow multiple permission overwrites when editing channel

src/structures/Role.js
There are 2 typos in the description of the `comparePositionTo()` function. This removes the typos, with no code changes.
=> Change 'the this' to 'this' in Role.comparePositionTo()

src/structures/GroupDMChannel.js, src/structures/Guild.js, src/structures/GuildChannel.js, src/structures/GuildMember.js, src/structures/User.js
Finds all locations where a getter may return undefined, and coerces the return value to null instead of undefined.
=> [consistency] getters return null instead of undefined

src/client/actions/MessageCreate.js, src/structures/DMChannel.js, src/structures/GroupDMChannel.js, src/structures/GuildMember.js, src/structures/TextChannel.js, src/structures/User.js, src/structures/interfaces/TextBasedChannel.js
Converts user/member/channel#lastMessage to be getters for the following reasons:
- Allows all messages to be properly swept completely from memory in all cases, when using messageSweeping.
- Fixes a memory leak: Bot leaves a guild, and no-longer shares a guild with some users from that guild. However, that user who nolonger shares any guilds with the bot has a lastMessage property (reference currently) which has the entire guild/roles/members/channels/unswept messages from those channels as references on that message. This prevents the referenced guilds/roles/channels/messages from ever being garbage collected, unless all users from the left guilds sends a message the bot can see in another guild (not likely to …
=> Convert lastMessage to getters

src/structures/MessageEmbed.js, src/structures/shared/CreateMessage.js
remove the toJSON method on message embeds so the raw data is exposed for JSON serialization. this removes the hexColor property, but it probably should not have been there in the first place. fixes #2419
=> fix message embed json serialization

src/structures/GuildChannel.js
GuildMembers have a `manageable` property to check if a bot has permission to manage them, it would great if Channels (specifically GuildChannels) could get the same kind of property. With this property we can easily check if we can i.e. change the channel name or its permissions before actually initiating that action. It appears that the bot requires both `VIEW_CHANNEL` and `MANAGE_CHANNELS` permissions to do it so I have implemented as in this PR.
Test output:
```
$ npm run lint && npm run docs:test
> discord.js@12.0.0-dev lint E:\UserFiles\DevProjects\djs
> eslint src *.js
E:\UserFiles\DevProjects\djs\src\client\Client.js
450:19  warning  Method '_validateOptions' has a complexity of 21  complexity …
```
=> Adds GuildChannel.manageable

src/structures/Role.js
This PR allows roles to finally be able to loose their colors by passing `null` in either setColor or edit({ color: null })
=> fix: Allow roles to have their color reset

src/client/ClientManager.js
This PR fixes a bug where if you set the presence through client options, the ClientUser#presence#activity would be null.
=> fix: ClientUser#presence#activity being null when set using client options

src/client/rest/RESTMethods.js
If I am not mistaken the only way atm to remove a channels parent atm is to do this to get the null value through the code.
channel.client.rest.methods.updateChannel({id:channel.id, name:channel.name,
topic:channel.topic,position:channel.position,
bitrate:channel.bitrate,userLimit:channel.userLimit,parent:{id:null}}, {});
This fixes the method allowing channel.setParent(null); to work
=> Fixed updateChannel being too protective

src/util/Snowflake.js
This will allow to generate snowflakes with a specific timestamp component.
Throws an error if the provided timestamp is not a number or date.
Closes #2038; There hasn't been any sign of activity in the last three months.
=> feat(SnowflakeUtil): allow snowflakes to be generated dynamically

src/structures/GroupDMChannel.js
This PR changes two slightly incorrect lines of text in [`GroupDMChannel#removeUser()`](https://discord.js.org/#/docs/main/master/class/GroupDMChannel?scrollTo=removeUser) and in [`GroupDMChannel#addUser()`](https://discord.js.org/#/docs/main/master/class/GroupDMChannel?scrollTo=addUser), which I believe appear as descriptions in the Discord.js docs.
The English language can be a little weird sometimes, so although "user" starts with a vowel, "a" is still used, rather than "an".
This PR contributes to ensuring grammatical consistency throughout, and makes the respective descriptions slightly more readable.
=> [docs] Minor text fixes: GroupDMChannel

src/structures/Guild.js
Modified `{GuildMember}` to `{?GuildMember}` so users will know, on the documentation, that the `owner` property **may be** undefined in some specific cases.
=> Fixed JSDoc information (Guild => owner)

src/stores/GuildChannelStore.js
The API provides the ability to send the topic, or description, of the channel within the creation post. Discord.js will now send it if its provided.
API consistency
=> Add Topic to GuildChannelStore#create

src/client/rest/RESTManager.js
Object.values() is behind a flag in Node v6. This restores Node v6 compatibility.
Fixes #2486 
=> Restore Node v6 compatibility to 11.x

src/client/websocket/packets/handlers/PresenceUpdate.js
While the current description is written similarly to the description in the [API docs](https://discordapp.com/developers/docs/topics/gateway#user-update), this is a little misleading. The API sends the `USER_UPDATE` event payload on **client** user update, but ours listen to the `PRESENCE_UPDATE` event payload which allows us to listen on **all** user updates. Therefore, if you disabled the `PRESENCE_UPDATE` event via [ClientOptions](https://discord.js.org/#/docs/main/master/typedef/ClientOptions).disabledEvents, it would not emit user updates on all users but only in the client user.
This PR adds a note for the end developer so they are aware of this.
=> [docs] Added a note in userUpdate event

src/structures/MessageEmbed.js
In the attachFiles method before we return `this` there was a useless for..of doing nothing so that is removed in place of a map at the top of the function. For some reason, in the constructor `this.files` would get assigned only if data.files was present which is probably not the case for most people using the MessageEmbed helper, So I've moved that out of the if and improved the JSDoc as its an array, not an Object.
=> Fix(MessageEmbed): Update attachFiles method and Make this.files out of the data.files check

src/stores/GuildEmojiRoleStore.js, src/stores/GuildMemberRoleStore.js, src/structures/GuildEmoji.js, src/structures/GuildMember.js, src/util/Util.js
Since we added stores to roles there was significant overhead and duplication in terms of memory usage, so this aims to reduce that by making roles just a filtered result of `Guild#roles`.
We're also missing specific implementations for adding or removing a single role on a `GuildMember`, so this takes care of that as well.
=> refactor: role stores

src/stores/GuildMemberRoleStore.js
This PR fixes a bug where the everyone role would not be added to `GuildMemberRoleStore#_filtered` getter, causing permissions to be inaccurate.
=> Added everyone role to GuildMemberRoleStore#_filtered

src/rest/DiscordAPIError.js, src/rest/handlers/RequestHandler.js
As mentioned in #2496, `DiscordAPIError` instances do not contain a property of method, this lack of information can affect error handling, specially when it comes to API errors from message edit or delete, which use the same endpoint (the former using the PATCH HTTP method, and the latter using the DELETE HTTP method).
To keep backwards compatibility, I added `method` as a third argument for the `DiscordAPIError` constructor.
=> feature: add DiscordAPIError#method

src/client/rest/RESTMethods.js
`GuildMember#addRole` and `GuildMember#removeRole` call `RESTManager#addMemberRole` and `RESTManager#removeMemberRole`, each of which make make a temporary listener for the event `GUILD_MEMBER_UPDATE`. However, if the request failed, it'd try to remove the event from `GUILD_BAN_REMOVE`, which is incorrect, causing this issue to make more and more unused events.
=> fix(RESTMethods) Removing wrong listener

src/util/Collection.js
Adds ~~`Collection#inspect`~~ `Collection#tap` which allows for easy debugging when chaining collection methods. 
Naming comes from ~~Rust~~ Laravel.
=> Add Collection#tap

src/structures/MessageCollector.js, src/structures/ReactionCollector.js
Since collectors implicitly add event listeners, they should also ensure that there are no issues with max listener counts.  I'm not pleased with how this is done, but I'm not sure how else to do it.
=> prevent max listener problems with collectors

src/structures/interfaces/TextBasedChannel.js
The current `TextBasedChannel#send` overload implementation is not only hard to read but also triggers false positives.
The current implementation is made in a way `TextBasedChannel#send` calls `Shared.sendMessage`, which calls `Shared.createMessage`, and in this line, the method calls `Util.resolveString`:
https://github.com/discordjs/discord.js/blob/7a3a4d1388c5f97d73a06021c1bd9167ea905656/src/structures/shared/CreateMessage.js#L47
Which calls this function:
https://github.com/discordjs/discord.js/blob/7a3a4d1388c5f97d73a06021c1bd9167ea905656/src/util/Util.js#L256-L260
However, with the false positives (e.g. `Date` instances or many other things that are typeof `object` and other things), but this method is meant …
=> Improved TextBasedChannel#send

src/structures/GuildEmoji.js
This PR adds `GuildEmoji#deletable` for consistency with `GuildChannel#deletable` and `Message#deletable`. The permission required for this action is `MANAGE_EMOJIS` according to the [API docs](https://discordapp.com/developers/docs/resources/emoji#delete-guild-emoji).
=> feat(GuildEmoji#deletable)

src/util/Collection.js
This PR reworks Collection a bit.
- Removed all methods `Collection#xxxArray` since the same can be done with `Array.from` or `Collection#array`.
- Removed the (prop, value) pattern you can use on `Collection#find`.
- Which also means `Collection#exists`  and `Collection#findAll` are removed.
- Added `Collection#partition`.
- Reworked some documentation and added more examples.
=> Remove unnecessary Collection methods and add Collection#partition

src/sharding/Shard.js
in accordance with #2452, there is no currently existing method of just killing a shard. this pr adds that functionality.
=> add shard#kill method

src/structures/TextChannel.js
To fix #2498. According to the guys over at the Discord API server, this is the proper way to check a channel's NSFW state.
=> Fix Incorrect NSFW Status on Channels

src/client/actions/ChannelDelete.js, src/client/actions/GuildDelete.js, src/client/actions/GuildEmojiDelete.js, src/client/actions/GuildMemberRemove.js, src/client/actions/GuildRoleDelete.js, src/client/actions/MessageDelete.js, src/client/actions/MessageDeleteBulk.js, src/structures/Channel.js, src/structures/Emoji.js, src/structures/Guild.js, src/structures/GuildMember.js, src/structures/Message.js, src/structures/Role.js
Fixes #2489 
This PR adds a new property called "deleted" to multiple structures throughout discord.js. The property allows for an easy way to check if the specific structure is stale.
Affected Structures:
- Channel
- Emoji
- Guild
- GuildMember
- Message
- Role
=> Add "deleted" property to multiple structures.

src/structures/Guild.js, src/util/Constants.js
The API sends the bot a property of `default_message_notifications` from both ws and rest. It is `0` when it mentions on all messages, and `1` when it mentions in only `@mentions`. This PR increases API coverage by supporting it.
~~**Note**: I have made that a boolean for user intuitiveness, when it's true, you get a notification in all messages, and when it's false, you only get them when you are mentioned.~~
=> feat(Guild#defaultMessageNotifications)

src/structures/Guild.js, src/util/Util.js
~~If you were to compare 2 guilds with the same features using `Guild#equals`, the second would lose all its features from the cache since [`Util.arraysEqual`](https://discord.js.org/#/docs/main/master/class/Util?scrollTo=s-arraysEqual) modifies the second array, removing all the values from the first. This PR clones the array from the given guild in said method using `Array#slice()`'s method.~~
~~[`Util.arraysEqual`](https://discord.js.org/#/docs/main/master/class/Util?scrollTo=s-arraysEqual) is not supposed to modify the array b but instead make a clone of it.~~
[`Util.arraysEqual`](https://discord.js.org/#/docs/main/master/class/Util?scrollTo=s-arraysEqual) has been removed as it was only used in `Guild#equals` …
=> Fix(Guild#equals) Array b being modified by the equality comparison

src/structures/User.js
Cover the totally new Discord API feature: the user's locale. The locale set on the user's client (desktop/mobile) will be sent through the User object to bots.
**More information:** https://github.com/discordapp/discord-api-docs/issues/535
=> feat(User#locale)

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
We get some feature requests that don't really fit with our existing issue template. This allows those feature requests to use a separate template. I'm open to suggestions on everything in here, especially with the feature request template (it's just the default one from GitHub, so there's probably some discord.js-specific information we should put in there).
=> use new multiple issue templates

src/structures/MessageMentions.js
MessageMentions is a quite unconsistent class, since it's one of the few classes whose property of `client` is not readonly. And making it consistent with the Message class, this also makes the property of `guild` readonly, and additionally, makes `_content` a hidden property for better inspection.
And also fixes two broken links that missed `@link` in the jsdocs.
=> refactor(MessageMentions)

src/structures/Message.js
when a _patch() is queued
Sometimes a _patch() will happen after the messageDelete action, making the message think it's not deleted anymore. By moving the deleted property for the message to the constructor, it will no-longer undelete itself (state) anytime _patch() is called.
=> Fix Messages un-deleting themselves

src/structures/MessageAttachment.js
In case of a video attachment the MessageAttachment object still has a height and width property.
This PR changes the corresponding line in the documentation to account for that possibility
=> docs: add video to MessageAttachment properties

src/structures/Guild.js
With https://github.com/discordjs/discord.js/pull/2538, `Guild#defaultMessageNotifications` was first introduced into the library, however, we could not edit it as `Guild#edit` was unedited. This PR adds the `defaultMessageNotifications` option into the `GuildEditData` typedef, and therefore, inside `Guild#edit`.
=> Added support for `defaultMessageNotifications`

src/client/ClientDataManager.js, src/structures/Message.js
This will make discord.js no longer cache webhook users.
Through this it's possible to access the actual used username and
avatar of webhook's messages as these can change every single message.
=> fix: do not cache webhook users

src/client/voice/player/BasePlayer.js
Because `args` was not a copy of `FFMPEG_ARGIMENTS`, but a reference to it, pushing `-ss` argument pushed it to `FFMPEG_ARGUMENTS`, making it persistent.
So if you called `play` with `seek` option and then without it, `-ss` was still there.
=> Fix seek option

src/structures/Guild.js
The docs currently state "The full amount of members in this guild __as of READY__" however the actual behaviour differs.
Guild#memberCount is updated on of GUILD_MEMBER_ADD and /_REMOVE respectively
Source: [GuildMemberAdd](https://github.com/discordjs/discord.js/blob/18646b72f902d79b73b8010013df2cb9141a2755/src/client/websocket/packets/handlers/GuildMemberAdd.js#L12) | [GuildMemberRemove](https://github.com/discordjs/discord.js/blob/18646b72f902d79b73b8010013df2cb9141a2755/src/client/actions/GuildMemberRemove.js#L11)
=> Docs: correct Guild#memberCount to actual behaviour

src/rest/RESTManager.js, src/rest/handlers/RequestHandler.js
**Fixes:**
- Adds Date header DeltaT calc back into ratelimits
- Fix x-ratelimit-reset is in seconds, not ms: ![img](https://puu.sh/AIXxY/9b3989b248.png)
- Fix remaining defaulting to 1, when 0 is remaining, as 0 is falsy
**Cleans Up:**
- removes legacy RESTManager#timeDifference code
- a duplicate check in `_inactive` that wasn't removed when the check was added to `limited`
=> fix: ratelimits

src/client/voice/util/PlayInterface.js
ytdl no longer recommends using filter: audioonly for reasons listed in [Issue 294](https://github.com/fent/node-ytdl-core/issues/294) as it can cause massive slowdowns in performance. As an alternative, using quality: highestaudio is recommended. This should be noted for new voice developers.
=> Change ytdl example

src/structures/Guild.js
Adds the `Guild#setDefaultMessageNotifications` method, after
#2538 introduced `Guild#defaultMessageNotifications` and #2592 added support for it in `Guild#edit`
=> Add support for Guild#setDefaultMessageNotifications

src/client/actions/MessageReactionRemove.js
The documentation states that the user parameter in the `messageReactionRemove` event is the user who removed the reaction. This is wrong; it is the user who initially reacted with the reaction. See [this conversation](https://discordapp.com/channels/222078108977594368/222078374472843266/467424090274267158) on the server.
=> Docs - Clarify messageReactionRemove user description

src/structures/Webhook.js
[`Client#token`](https://discord.js.org/#/docs/main/master/class/Client?scrollTo=token) is hidden with `Object.defineProperty` by making the property non-enumerable, however, [`Webhook#token`](https://discord.js.org/#/docs/main/master/class/Webhook?scrollTo=token) is not.
Other things to consider (but I need feedback from maintainers):
- ~~Make `Webhook#token` writable?~~
- Make `WebhookClient#token` non enumerable?
=> Make `Webhook#token` not enumerable

src/structures/GuildAuditLogs.js
Currently when fetching audit logs containing an invite to a deleted channel will reject the promise with an error.
This will now create a PartialGuildChannel instead.
But since there is neither a type, nor a name available,
the type will always be `'text'` and the name `undefined`.
No idea if it's possible to work around that, changing the type signature of `Invite#channel` to `GuildChannel|PartialGuildChannel|Snowflake` is probably semver: major.
=> fix(GuildAuditLogs): default to PartialGuildChannel if channel was deleted

src/structures/Invite.js
Since discord now allows invites for group dm channels, one can also fetch them.
Due to a missing guild there, doing so will throw an error since it was a guaranteed property so 
One issue remains:
The recipients array sent with the invite is formatted as `[{ username: string }]`; it does not contain ids.
This can't be really mapped to a Collection and will leave it as `undefined => partialLastUserInArray`.
=> fix(Invite): support group dm invites

src/structures/MessageReaction.js
For cases where the bot removes another user's reaction when there are 2 remaining reactions in a `ReactionUserStore`, the bot would remove that, correctly, but then, the gateway event received would decrement the count once more in `MessageReaction#_remove`, causing it to delete the entire reaction. This is the only way I can think to combat that issue, since there is no guarantee of the `count` ever being synchronized with the cached information, nor can I see a guarantee to keep it that way, as the count gets out of sync regardless.
Feel free to suggest something better, if anything comes up!
fixes #2653 
=> fix(MessageReaction): only delete reaction if cache and count is empty

src/sharding/Shard.js, src/sharding/ShardClientUtil.js, src/sharding/ShardingManager.js, src/util/Util.js
Backports a decent number of sharding-related commits, such as `Shard#kill`, `Shard#respawn`, the ability to pass `execArgv` into the Shard, and a few more.
Please suggest if there are any better ways to go about anything I've done. I've avoided a complete rewrite so as to keep it functioning as similarly to before as possible.
=> backport: Sharding utility methods

src/util/Collection.js
Using `new Collection()` within the Collection class causes unexpected behavior when extending it.
Example:
```js
class SuperCollection extends Collection {
hasItems () { return this.size > 0 }
}
const sc = new SuperCollection([[1, 'one'], [2, 'two']])
sc.hasItems() // => true
const filtered = sc.filter(item => item === 'one') // returns a Collection, not a SuperCollection
filtered.hasItems() // error
```
This PR makes sure to use the same constructor when filtering, cloning etc.
=> fix(Collection): use `new this.constructor` instead of `new Collection`

src/structures/MessageEmbed.js
Added a list of the four <MessageEmbed>.type's an embed could have, similar to how <channel>.type got a list of possible values
I also changed "color of the embed" to "color of this embed" since everything else on this page uses "this" instead of "that", and that will make it more streamlined.
=> Added docs for possible <MessageEmbed>.type's

src/structures/Message.js
The current message.reply() example contains a small mistake. `msg.author` will always be the ClientUser, instead of the author of the message that got replied.
=> Small typo in documentation of Message.js

src/structures/Guild.js, src/structures/GuildChannel.js
Replaces accepted type for GuildChannel#replacePermissionOverwrites with ChannelCreationOverwrites and adds master properties denied and allowed to the same
=> docschange for GuildChannel#replacePermissionOverwrites

src/util/Collection.js
- Changes `tap` to be `fn(this)` and adds `each` for what `tap` was (naming was inconsistent with other places like Laravel)
- Removes `deleteAll` - it was inconsistent to the rest of the interface, even the docs were not guaranteed
=> Collection debug methods, remove deleteAll

src/structures/Message.js, src/util/Util.js
Moves the method that makes up `Message#cleanContent` to our `Util` class so that it can be used by external sources more easily.
=> refactor: move Message#cleanContent function to Util

src/structures/Guild.js, src/structures/GuildChannel.js, src/structures/PermissionOverwrites.js
- Add Collection as parameter option to GuildChannel#replacePermissionOverwrites
- Add example for null to PermissionOverwriteOptions (akin to master PermissionOverwriteOption)
- Deprecated allow/deny in favor of allowed/denied
=> Docs small changes regarding permissions/overwrites

src/structures/GuildMember.js
changes the return type for GuildMember#speaking when there is no VoiceChannel & Connection to null to stay consistent with other getters
=> fix: use null for getter instead undefined

src/structures/GuildChannel.js
- Add Collection as possible param to GuildChannel#overwritePermissions, works as flawlessly but is currently undocumented
- Change PermissionoverwriteOptions description default to unset in accordance to #2718 and Lewdcario
=> add Collection as possible param to GuildChannel#overwritePermissions + wording port from 11.3-dev

src/stores/DataStore.js, src/util/Collection.js
Fixing collection extensions again. DataStore's should return Collections when derived.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/species.
With this changes:
```js
dataStore.filter(() => true) // returns Collection
superCollection.filter(() => true) // returns SuperCollection
```
=> fix(Collection): use Symbol.species for creating derived collections

src/stores/RoleStore.js
Fixes #2552. Also at the same time (somehow) addresses the current issues with the documentation for [RoleStore#resolveID](https://discord.js.org/#/docs/main/master/class/RoleStore?scrollTo=resolveID) and [RoleStore#resolve](https://discord.js.org/#/docs/main/master/class/RoleStore?scrollTo=resolve). ~~However, the solution seems to be a bit dirty, so I'm open to suggestions. I have tried things like `@override`, which did not seem to work (or perhaps I did it incorrectly).~~ ~~Dirtiness resolved thanks to @SpaceEEC suggestions.~~ jsdocs are dumb
=> docs fix: RoleResolvable typedef missing and incorrecty documented methods

src/structures/VoiceChannel.js
Closes #2736
Fixes the bug in VoiceChannel where `members` would return a Collection with `undefined, undefined` because of the map returning `[GuildMember]` and not `[[Snowflake, GuildMember]]`.
=> Fix(VoiceChannel): members returning collection of undefined.

src/structures/Guild.js, src/structures/GuildChannel.js
- Document missing properties ChannelData.parent and ChannelData.permissionOverwrites
<https://github.com/discordjs/discord.js/blob/stable/src/client/rest/RESTMethods.js#L324>
- Remove eslint disable/enable madness from defaultMessageNotification (not worth its own PR imo)
- Remove `PermissionOverwrites[]` where applicable
=> Docs: document ChannelData.parent and .permissionOverwrites, fix typedefs to not include Collection of ChannelCreationOverwrite 

src/client/Client.js
Fixes an issue with the process permanently hanging.
BaseClient (which Client extends) already defines the timeouts:
https://github.com/discordjs/discord.js/blob/0ad7c24aa394249a5213a8e11a826821d4b56266/src/client/BaseClient.js#L14-L26
On Client, a RESTManager was created using client.setInterval for the REST managers sweeper, however, the Sets were being overwritten, making it unaccesible from BaseClient#destroy, and thus, making the process hang forever.
tl:dr; When giving an unvalid token, this was instantiating BaseClient via super's call, then RESTManager (which creates an interval), and the sets were overwritten. On login, it attempts to login and fails, it automatically calls destroy, but the interval was …
=> fix: intervals and timeouts being overwritten

src/structures/GuildAuditLogs.js
This will avoid `GuildAuditLogsEntry#target` being undefined by defaulting it to `{ id: data.target_id }`.
This occurs when the target (role / channel / etc) was deleted.
Fixes #2741
=> fix(GuildAuditLogs): default target to object with target_id

src/rest/APIRouter.js
Fixes https://github.com/discordjs/discord.js/issues/2496
This fix modifies the error stacks from REST from this:
```
DiscordAPIError: Unknown Message
at parseResponse.then.data (/*/node_modules/discord.js/src/rest/handlers/RequestHandler.js:110:15)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
To this:
```
DiscordAPIError: Unknown Message
at KlasaMessage.delete (/*/node_modules/discord.js/src/structures/Message.js:453:9)
at eval (eval at eval (/*/node_modules/klasa/src/commands/Admin/eval.js:49:13), <anonymous>:2:11)
at module.exports.eval (/*/node_modules/klasa/src/commands/Admin/eval.js:49:13)
at module.exports.run (/*/node_modules/klasa/src/commands/Admin/eval.js:18:54)
at …
```
=> fix: Handle async stacks correctly

src/structures/GuildChannel.js, src/structures/Message.js, src/structures/VoiceChannel.js
ADMINISTRATOR has no meaning in a channel overwrite. permissionsFor already returns full permissions for guild owner and admin roles. Therefore, whenever using the returned Permissions from permissionsFor, you should never checkAdmin (which is default).
It has been stated that this is the [intended behavior](https://github.com/discordapp/discord-api-docs/issues/640) of the API by discord devs. Our permissionsFor also follows the [specified way](https://github.com/discordapp/discord-api-docs/blob/master/docs/topics/Permissions.md#permission-overwrites) of calculating permissions for a member in the context of a channel.
So the only answer is not checking Administrator in permissions returned from permissionsFor, as …
=> Fix permission checking for Administrator channel overwrites

src/client/websocket/packets/handlers/GuildBanAdd.js
This PR fixes the guildBanAdd event not getting emitted when an uncached user gets banned.
Since the inner payload is a user object, this is easy to do.
Also fixes inconsistency with client/actions/GuildBanRemove (which was indeed using `client.users.add`)
=> Gateway: Fix guildBanAdd not emitting with uncached user

src/structures/VoiceRegion.js
This PR removes VoiceRegion#sampleHostname, which is not longer available and always undefined (check [here](https://discordapp.com/developers/docs/resources/voice)).
<details>
<summary>Result of <code>this.client.api.voice.regions.get();</code>:</summary>
<br>
<pre lang="json">
[
{
"name": "Central Europe",
"deprecated": false,
"custom": false,
"vip": false,
"optimal": true,
"id": "eu-central"
},
{
"name": "London",
"deprecated": true,
"custom": false,
"vip": false,
"optimal": false,
"id": "london"
},
{
"name": "Amsterdam",
"deprecated": true,
"custom": false,
"vip": false,
"optimal": false,
"id": "amsterdam"
},
{
"name": "Japan",
"deprecated": false,
"custom": false,
"vip": false,
"optimal": false,
"id": "japan" …
=> cleanup: Remove VoiceRegion#sampleHostname

src/client/rest/RESTManager.js
Backports https://github.com/discordjs/discord.js/pull/2744 to 11.4-dev, changing the stack of all errors thrown from the API.
**Before:**
```
DiscordAPIError: Unknown Message
at item.request.gen.end (/*/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:79:15)
at then (/*/node_modules/snekfetch/src/index.js:215:21)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
**After:**
```
DiscordAPIError: Unknown Message
at RESTMethods.deleteMessage (/*/node_modules/discord.js/src/client/rest/RESTMethods.js:152:22)
at Message.delete (/*/node_modules/discord.js/src/structures/Message.js:477:39)
at Client.client.on (/*/index.js:8:17)
at Client.emit (events.js:182:13)
at …
```
=> backport: Handle async stacks correctly

src/structures/ClientApplication.js, typings/index.d.ts
Since this class was last updated, it seemed to set many properties that are undefined, after a check in the documentation, it seemed they do not exist anymore.
This PR removes the properties, `redirectURIs`, `rpcApplicationState`, `bot`, `flags`, and `secret`, since they're not referenced in the docs, makes `ClientApplication#owner` to not be nullable (always exists), and defaults `rpcOrigins` to an empty array if undefined, clarificating a little bit its description.
Thanks @KingDGrizzle for helping me finishing the cleanup with ee7e9a01aec9d65e5bdb0e01009150700d8255d0
=> misc: Update ClientApplication for the current API

src/structures/User.js
Backports https://github.com/discordjs/discord.js/pull/2773 to 11.4-dev.
**Note**: `|| null` has been removed since it would return a different value, changing this from `semver: patch` to `semver: major`.
**Status**
=> backport: User#dmChannel perf enhancement

README.md, docs/general/welcome.md, package.json, src/WebSocket.js
Should be pretty evident why we do this.
We do not have to rely on the broken NPM package that's currently out there and can maintain a variety of node versions on our own.
Additionally resolves #2685
**Status**
=> build(peer-deps): use uws fork

src/client/websocket/packets/WebSocketPacketManager.js, src/client/websocket/packets/handlers/WebhooksUpdate.js, src/util/Constants.js
Backports https://github.com/discordjs/discord.js/pull/2762 to 11.4-dev.
**Status**
=> backport: `WEBHOOKS_UPDATE` event

src/structures/Guild.js, src/structures/GuildMember.js
This PR changes the docs to approve `PermissionResolvable.{allow,deny}` again and deprecate `PermissionResolvable.{allowed,denied}`, plus deprecates `GuildMember#missingPermissions` to reflect the changes from https://github.com/discordjs/discord.js/pull/2765
**Status**
=> misc(Guild,GuildMember): Update deprecations for latest master

src/client/websocket/packets/handlers/Ready.js
According to the doc for Ready, private_channels is always an empty array - see [here](https://discordapp.com/developers/docs/topics/gateway#ready) and [here](https://discordapp.com/developers/docs/change-log#june-19-2018). No reason to do this as client.channels will never have anything added to it.
**edit:** answered by gus below, thank you!
~~I also had a question for line 19 - data.guilds comes back as an array of unavailable guilds:~~
~~The client.guilds is then populated by CREATE_GUILD events async, which get emitted pretty much immediately -- so is there actually any point in going through and calling guilds.add with the unavailable guilds on ready?~~
**Status**
=> private_channels always returns an empty array on ready

src/rest/APIRouter.js, src/rest/RequestHandler.js
2 bugs:
1. Each reaction doesn't have their own rate-limit, reactions are rate-limited by channel_id major.
2. Hardcoded reaction rate-limit calculation was wrong
**Status**
=> fix: reactions ratelimits

src/rest/RESTManager.js, src/rest/RequestHandler.js
fixes https://github.com/discordjs/discord.js/issues/2785 (I will give it some time for the developers to try if this PR fixes their issue completely).
tl;dr: A global timeout would only switch one `RequestHandler#busy` to false: the one after the request that got the `x-ratelimit-global` header, making the other RequestHandlers hang on forever. In this change, `RESTManager#globalTimeout` is not longer a `Timeout` but the promise from `Util.delayFor(this.retryAfter)`. 
**Status**
=> fix: Better global ratelimit management

src/structures/Invite.js
Fixes https://github.com/discordjs/discord.js/issues/2769 by adding `url` to the list. And added the [serial comma](https://en.wikipedia.org/wiki/Serial_comma)
**Status**
=> docs: Added `url` to Invite's warning comment

src/util/Constants.js, typings/index.d.ts
Typings as well as some additional lines of docs for the property were forgotten when it was removed in #2694.
**Status**
=> remove remaining apiRequestMethod property docs and typings

src/structures/Guild.js
This PR makes the checks in Guild#deleteEmoji more robust by requiring emoji to be an instance of Emoji before it's passed to RESTMethods, avoiding the following error:
```
TypeError: Cannot read property 'guild' of undefined
at RESTMethods.deleteEmoji ([...]/discord.js/src/client/rest/RESTMethods.js:702:66)
at Guild.deleteEmoji ([...]/discord.js/src/structures/Guild.js:1087:37)
[...]
```
**Status**
=> fix(Guild#deleteEmoji): Performing wrong checks

src/structures/Invite.js, typings/index.d.ts
- Adds `url` to the description (backported from #2804).
- Adds a better check for field existence, such as `Invite#temporary`, `Invite#maxAge` (for permanent invites), `Invite#maxUses` (for invites with no limits), `Invite#uses`... being defaulted to `null`.
- Added a check for `this.maxAge` in `Invite#expiresTimestamp`: maxAge is zero when the invite never expires.
- Optimized `Invite#expiresAt` to not run the `Invite#expiresTimestamp` getter twice.
- Removes `Invite#{textChannelCount,voiceChannelCount}`, they don't seem to be present anymore (tested with fetching a channels' invites and fetching the invite link from client, none of both return it, but together they display all other fields).
**Status** …
=> cleanup(Invite): Removed non-existant fields and fixed bad defaulting

src/structures/Guild.js
Correct Guild#memberCount to reflect actual behavior.   
The property is updated on the respective events leading to an always up-to-date number, not "as of READY" as the docs currently suggest.
The changed docs are already applied on master
**Status**
=> docs: correct Guild#memberCount

src/structures/MessageAttachment.js
This PR attempts to make the library more consistent by making the nullable properties `height` and `width` return null instead of undefined when they're not present.
**Status**
=> MessageAttachment#{width,height}: use null when it's not present

src/client/Client.js, src/rest/RESTManager.js, src/rest/RequestHandler.js, src/util/Constants.js, typings/index.d.ts
Adds the ability for users to toggle whether or not they want to retry (or however many times) in the event of outages, which come with their fair share of 5XX errors (yet sometimes still sending a successful response).
*I'd love to test this but I have no outage on me right now*
fixes https://github.com/discordjs/discord.js/issues/2655
**Status**
=> feat: add ClientOptions#retryLimit

src/errors/Messages.js, src/structures/GuildEmoji.js, typings/index.d.ts
Currently if you try to fetchAuthor on an emoji that belongs to a guild where the client doesn't have MANAGE_EMOJIS, it throws a wacky 'undefined has no id' error because the api doesn't return a user object in that case.  This PR adds a check for that before we make the request with matching error message.  I also added fetchAuthor to the typings since it wasn't there and that makes tsc mad.
Reference for needing MANAGE_EMOJIS to see user at all [here](https://github.com/discordapp/discord-api-docs/issues/593#issuecomment-386477863).
**Status**
=> GuildEmoji.fetchAuthor() error handling

src/structures/ReactionCollector.js
This PR aims to fix an issue where the `ReactionCollector#remove` is being emitted regardless of the `CollectorFilter` that was provided by the user. As far as I know, this event didn't exist in the stable release. I think this is the right solution but I'm open to feedback of course.
Fixes #2802.
**Status**
=> emit ReactionCollector#remove when reaction is removed by collected user

src/client/websocket/packets/handlers/ChannelPinsUpdate.js
According to the [API documentation](https://discordapp.com/developers/docs/topics/gateway#channel-pins-update), the field `last_pin_timestamp` is the time when the last pinned message was pinned, not "The time of the pins update".
This PR clarifies the misleading description and adds a warning because the `time` parameter will be a Unix Epoch Date object (due to constructing a Date object with null) when there are no pins left.
**Status**
=> docs(Client#channelPinsUpdate): clarify time param

src/structures/APIMessage.js, src/structures/Message.js, src/structures/Webhook.js, src/structures/interfaces/TextBasedChannel.js, typings/index.d.ts
This pr is a follow-on pr to #2774 to avoid duplicating send checks with split messages. This pr accomplishes this, by caching and lazy resolving the data and files, allowing send/edit to take an APIMessage directly, without redoing any of the resolutions.
This adds APIMessage#split() which returns an array of APIMessages, that way the same split behavior can be reused in both Webhook#send() and TextBasedChannel#send(), and additionally can be reused in frameworks for split message Command Editing.
**Status**
=> Remove duplicate send checks

src/client/Client.js, src/sharding/ShardingManager.js
Default `token` in ShardingManger to `process.env.CLIENT_TOKEN` like Client does.
https://github.com/discordjs/discord.js/blob/master/src/client/Client.js#L113
Not sure it's the best way to do it as it seems discord.js likes to use null as a default instead of undefined.
It doesn't break anything if it's not defined, Besides the token not being defined so the client won't login.
**Status**
=> Change default token

typings/index.d.ts
This PR adds the `HTTPError` class definition implemented from https://github.com/discordjs/discord.js/pull/2694
**Status**
=> typings: Add HTTPError class definition

src/client/WebhookClient.js
Adds parity with Client by adding the barest protection against accidental exposure
**Status**
=> make WebhookClient#token non-enumerable

src/client/Client.js, src/client/rest/RESTManager.js, src/client/rest/RequestHandlers/Burst.js, src/client/rest/RequestHandlers/Sequential.js, src/util/Constants.js, typings/index.d.ts
This PR adds the ability to set a retry limit for 5xx http responses.
See #2805
**Status**
=> backport(ClientOptions): add retryLimit

src/structures/MessageEmbed.js, typings/index.d.ts
Adds the ability to provide a timestamp as opposed to just a date object, otherwise would throw an `is not a function` error.
**Status**
=> feat: allow MessageEmbed#setTimestamp to take a timestamp

src/stores/GuildChannelStore.js, typings/index.d.ts
Allows channels to be created with the `rate_limit_per_user` property for API coverage.
**Status**
=> Feat: GuildChannelStore#create with rateLimitPerUser

src/structures/ClientPresence.js, src/structures/ClientUser.js, typings/index.d.ts
Allows people to specify a single object for setting an activity, rather than splitting it between a string param and options objects.
**Status**
=> feat(ClientUser): Allow options as first parameter to ClientUser#setActivity

src/client/websocket/packets/handlers/ChannelPinsUpdate.js, src/structures/DMChannel.js, src/structures/GroupDMChannel.js, src/structures/TextChannel.js, src/structures/interfaces/TextBasedChannel.js, typings/index.d.ts
And clarify Client#channelPinsUpdate's time parameter.
This PR backports #2813 and #2823.
Adding `TextBasedChannel#lastPinTimestamp` and `TextBasedChannel#lastPinAt`.
As well as clarifying `Client#channelPinsUpdate`'s time parameter.
**Status**
=> backport(TextBasedChannel): add lastPinTimestamp and lastPinAt

src/structures/Emoji.js, src/structures/GuildEmoji.js, typings/index.d.ts
This PR allows to retrieve the timestamp and the date for when emojis were created from `ReactionEmoji`s by moving the respective getters into the base `Emoji` class.
They will return null for unicode emojis.
**Status**
=> feat(Emoji): move createdAt and createdTimestamp getters from GuildEmoji

src/client/rest/RESTMethods.js, src/structures/Guild.js, src/structures/GuildChannel.js, typings/index.d.ts
This PR adds an options object "overload" to `Guild#createChannel` allowing to specify all available properties upon creating, rather than having to edit after creating again.
This also deprecates the old way of using multiple parameters, emitting a process warning.
Regarding `ChannelData#overwrites` ->`ChannelData#permissionOverwrites`:
- The property has been added with https://github.com/discordjs/discord.js/pull/2734 (after the last release)
- The actual code is also using `permissionOverwrites` (stable and current 11.4-dev) https://github.com/discordjs/discord.js/blob/b5df8603e8768b9b50ece24f94e455c3410ef9a2/src/client/rest/RESTMethods.js#L325-L326
So that's a documentation fix purely inside of 11.4-dev, and …
=> backport(Guild): createChannel with options object

src/util/Collection.js
The current example for `Collection.tap()` does not really demonstrate the functionality tap provides.
Changing it to verbose log instead provides a visual feedback for the user as to what's happening (size prior and after the filter) without modifying `this`
**Status**
=> docs: clarify example for Collection#tap

src/client/Client.js
Support for parsing the client's presence as provided in `ClientOptions` disappeared somewhere along the road on the road to getting internal sharding, so I re-added it.
**Status**
=> fix: re-add presence parsing from ClientOptions

src/client/rest/RESTManager.js
I have opened up a PR for this because I would like for us to consider possible alternatives for this issue.
Here is the issue at hand: 
I have managed to reproduce it with the following code sample:
```js
const djs = require('discord.js');
const { pichu } = require('./settings');
process
.on('unhandledRejection', console.error)
.on('uncaughtException', console.error);
new djs.Client()
.on('ready', () => {
console.log('ready');
})
.on('message', mes => {
if (mes.author.id === '84484653687267328' && mes.content === 'ping') mes.reply('pong');
})
.login(pichu);
```
This was done by denying the bot's `SEND_MESSAGE` permissions, and simply triggering the API call. The issue was reproduced every single time with no …
=> fix: revert #2768

src/client/websocket/packets/handlers/VoiceStateUpdate.js, typings/index.d.ts
Allows `Client#voiceStateUpdate` to emit when someone leaves *the server* while in a Voice Channel. I figured this acceptable because you have the ID of the member in the state anyway, so there is no need to concern ourselves with partials here or anything like that.
**Status**
=> fix: emit voiceStateUpdate on guildMemberRemove

src/client/voice/VoiceConnection.js
A bug fix so the `_stoppedSpeaking` event is fired when the user stops speaking. Best I can tell (I'm new to node.js), `speaking` used to be a bool/int, but is now an bitmask object in v12. This (tiny) patch uses the bitmask correctly.
I have attached my code that I use to record voice from Discord. Run it, and then in the text channel where the bot is registered, enter something such as: `!join my voice channel`
[voicebot12.js.zip](https://github.com/discordjs/discord.js/files/2481005/voicebot12.js.zip)
**Status**
- [/] Code changes have been tested against the Discord API, or there are no code changes
- [/] I know how to update typings and have done so, or typings don't need updating
**Semantic versioning …
=> Use match on speaking bitmask to fire _stoppedSpeaking

src/client/Client.js, src/sharding/Shard.js, src/sharding/ShardClientUtil.js, src/sharding/ShardingManager.js, typings/index.d.ts
This adds support for Node's Worker threads as an alternate mode to the ShardingManager. Web workers are unsupported due to API differences and the inability to tell when a worker has manually closed itself from within the master process.
**Status**
=> Add worker-based sharding to the ShardingManager

src/client/actions/UserUpdate.js
Adds the `Client#userUpdate` docstring - that somehow went missing on master - back
**Status**
=> docs: add missing docstring for Client#userUpdate

src/structures/GuildChannel.js
Wrong property names as of #2888 resulting in `GuildChannel#clone` ignoring overwrites.
Should fix #2931 
**Status**
=> fixes 2931 (GuildChannel#clone not taking overwrites into account)

.github/ISSUE_TEMPLATE/bug_report.md
The following PR deletes the user checkbox from the Bug Report issue template, since Discord.JS version 12 doesn't support user accounts
**Status**
[ ci skip ]
=> chore: Remove User account from Bug Report template

src/structures/GuildChannel.js, typings/index.d.ts
This PR allows to specify a different `topic` and `permissionOverwrites` when cloning a `GuildChannel` (rather than current one or none).
Additionally it allows you to set a `type`, and clone / override the current `rateLimitPerUser` (if text).
**Status**
=> feat(GuildChannel): allow to set all options when cloning

src/client/websocket/WebSocketManager.js, src/client/websocket/WebSocketShard.js, src/sharding/ShardingManager.js, src/structures/ClientPresence.js, src/structures/Guild.js, typings/index.d.ts
This PR fixes the reconnect issues that sharding has received, and does some cleanup
- WebSocketManager#shards is now a `Collection<number, WebSocketShard>`
- Using an array made it have holey items, and uneeded filter / null checks
- In WebSocketManager#handlePacket, bring back the disabledEvents check
- On session invalidated, if the session is not resumable, wait 2.5 seconds (per `It's also possible that your client cannot reconnect in time to resume, in which case the client will receive a Opcode 9 Invalid Session and is expected to wait a random amount of time—between 1 and 5 seconds—then send a fresh Opcode 2 Identify.`)
- ~Destroy the shard onClose if it's expecting to close or is one of the error codes that …
=> fix: Sharding Fix / Cleanup

src/errors/Messages.js, src/structures/GuildMember.js
Currently if one does `<member>.edit({channel: 'invalidChannel'})`, whether it's a bad channel id, a random string or whatever, you get the error 
```
TypeError: Cannot read property 'id' of null
at Object.edit (/.../node_modules/discord.js/src/structures/GuildMember.js:251:67)
```
Adding the explicit error here might make the issue a bit more clear to users.
**Status**
=> Add explicit channel resolve error to member edit

src/errors/Messages.js, src/util/Util.js
This will cause the `Util.splitMessage` function to throw an error if a chunk is too large after splitting.
This is to fix #2935 and seems to be the intended behaviour, looking at the other error being thrown (`SPLIT_MAX_LEN`) in case of the message being too long without a split char.
Also gets rid of a duplicated error code.
**Status**
=> fix(Util): throw an explicit error if a chunk exceeds the max length

src/client/actions/GuildBanRemove.js
- "Events.GUILD_BAN_REMOVEGUILD_BAN_REMOVE" -> "Events.GUILD_BAN_REMOVE"
Basically fixes the Event string.
**Status**
=> fix: guildBanRemove event name

src/client/websocket/WebSocketShard.js, test/tester1000.js
In accordance with the [ws docs](https://github.com/websockets/ws#error-handling-best-practices), we should have a callback to handle errors encountered while sending a message over the websocket.
**Status**
=> websocket send error handling

src/stores/GuildChannelStore.js, typings/index.d.ts
This PR adds support for `GuildChannelStore#create` to accept a position option directly.
See [Discord Docs](https://discordapp.com/developers/docs/resources/guild#create-guild-channel) on that endpoint.
**"Issue"**
This currently accepts `position` as `GuildChannel#rawPosition` and not as `GuildChannel#position` (the calculated one).
- Should it be the other way? (Potentially a bit more complicated to achieve)
- Should that behaviour additionally be documented?
- Or is it fine as is?
**Status**
=> feat(GuildChannelStore): add support for create to accept a position

typings/index.d.ts
The typings for SnowflakeUtil didn't support the [optional argument "timestamp"](https://discord.js.org/#/docs/main/stable/class/SnowflakeUtil). This PR adds the timestamp argument to the typings
**Status**
=> update SnowflakeUtil typing

src/client/actions/MessageCreate.js, src/structures/interfaces/TextBasedChannel.js
This is a partial backport of #2384 without breaking changes so that #2986 doesn't break with the error
`TypeError: Cannot set property lastMessage of [object Object] which has only a getter`
**Status**
=> fix(TextBasedChannel): added missing lastMessage functionality in textchannels

typings/index.d.ts
Since we can do `message.channel.bulkDelete([id1, id2, id3]);`
**Status**
=> typings: Add `string[]` overload to bulkDelete

src/client/Client.js, src/util/Constants.js
fixes #3017 where `ShardClientUtil#id` would return `[0]` if the current shard was 0.
**Status**
=> fix(ShardClientUtil#id): erroneously reporting as an array

docs/examples/greeting.js
The `Collection#find` method takes in an argument instead of a key/value pair. This example has been updated to adhere to that.
**Status**
=> fix: Updated deprecated method of Collection#find

typings/index.d.ts
To match the JS typedef: https://discord.js.org/#/docs/main/master/typedef/ImageURLOptions and the [`AllowedImageSizes`](https://github.com/discordjs/discord.js/blob/3dff5058f0beae01cec0abe27e3a43c8fd7c60ce/src/util/Constants.js#L105) constant which is `[16, 32, 64, 128, 256, 512, 1024, 2048]`.
**Status**
=> typings: Add missing ImageSize numbers

src/index.js
`HTTPError` is supposed to be public as it's documented, plus it is exported in [typings](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L611-L617).
**Status**
=> misc(index): Export HTTPError

typings/index.d.ts
Fixes #3050 and more (`topic` and some semicolons were missing).
**Status**
=> typings(GuildCreateChannelOptions): Added missing properties

typings/index.d.ts
When using internal sharding, `ShardClientUtil#id` is an array of numbers, otherwise it is a simple number.
Ref: https://github.com/discordjs/discord.js/blob/d98d464d748a75e242b6e95a1308235bf4016e1b/src/sharding/ShardClientUtil.js#L50
**Status**
=> typings(ShardClientUtil): Fix `id` property type

src/stores/GuildMemberRoleStore.js, src/structures/GuildMember.js
- Cleaned up `GuildMemberRoleStore#{add,remove}`, which were creating a rejected promise inside a promise, instead of rejecting the first one.
- Fixed a bug where `GuildMember#edit` with a specified unknown channel would throw synchronously, instead of rejecting asynchronously. (`message.member.edit({ channel: '1' });` would trigger a `DiscordAPIError` throw instead of `Promise<DiscordAPIError>`)
**Status**
=> cleanup(GuildMember{RoleStore}): Rewrite to async/await

src/structures/GuildChannel.js, src/structures/VoiceChannel.js, typings/index.d.ts
This PR adds `GuildChannel#viewable` and adds it as requirement to `VoiceChannel#joinable`.
Fixes #3005 as `VoiceChannel#join` will now early reject with a more appropriate error.
**Status**
=> fix: ensure VIEW_CHANNEL permissions before trying to join

src/client/websocket/WebSocketManager.js, src/client/websocket/WebSocketShard.js, src/client/websocket/handlers/GUILD_SYNC.js, src/util/Constants.js, typings/index.d.ts
This PR aims to fix all the sharding issues, from silent disconnects to who knows what happens. I'm waiting for feedback, reviews, suggestions ~~or just people to scream at me~~.
List of things changed:
- Move expectingClose from the WebSocketShard to WebSocketManager
- In my opinion, all shards should check the same property, on the manager. That should prevent a case where one shard gets destroyed and never reconnects in a process that (as an example) has 3 shards. This way, they are all connected or none, and we can re-use the destroy function for cleaning up before reconnecting. 
- Remove `spawning` property from WebSocketManager
- Moved the code that adds the shards to the spawn queue in the connect function
- …
=> [RFC] fix: Sharding issues, silent disconnects and code cleanup

package.json
And `engines.node` to require at least node.js 10 (#1386)
**To test**
If you use libsodium and any of those two libraries, please tell us if those versions work with discord.js.
**Status**
=> chore(deps): Updated all required, peer, and development dependencies

package.json
This PR fixes the warning displayed on console (after every webpack build):
```
WARNING in ./src/client/Client.js
Module not found: Error: Can't resolve 'worker_threads' in 'D:\Repositories\discordjs\discord.js\src\client'
@ ./src/client/Client.js
@ ./src/index.js
```
**Status**
=> webpack: Fix module warning when building

src/errors/Messages.js, src/structures/DMChannel.js, src/structures/GroupDMChannel.js, src/structures/Message.js, src/structures/TextChannel.js, typings/index.d.ts
search was removed a long time ago, this PR removes its remainings
**Status**
=> cleanup: Remove unused members of classes

src/structures/RichEmbed.js, typings/index.d.ts
This PR backports #3003 to the 11.4-dev branch adding `RichEmbed#length`.
**Status**
=> feat(RichEmbed): add length getter

src/client/rest/RESTMethods.js
This PR backports #2958 to the 11.4-dev branch throwing an explicit/better error when passing bad input to `GuildMember#setVoiceChannel` or its `GuildMember#edit` variant.
**Status**
=> fix(GuildMember): add explicit channel resolve error to member edit

src/util/Util.js
This PR backports #2936 to the 11.4-dev branch making `Util.splitMessage` throw an error when any chunk, not just the first, exceeds the max length.
**Status**
=> fix(Util): splitMessage throws an error if a chunk is too large

src/structures/RichEmbed.js, typings/index.d.ts
This PR backports #2875 allowing `RichEmbed#setTimestamp` to also accept a timestamp.
**Status**
=> feat(RichEmbed): add timestamp support for setTimestamp

src/structures/Emoji.js
This PR backports #2788 throwing an explicit / better error when trying to fetch the author of an emoji when the client has no `MANAGE_EMOJIS` permission.
**Status**
=> fix(Emoji): reject explicit error when MANAGE_EMOJI permissions are missing

src/structures/MessageEmbed.js
There's a (previously) undocumented embed type.
This PR resolves #3105
Checked the typings, they only specify "string", and thus didn't need to be changed (this was an explanation for the below checkbox about the typings)
**Status**
=> Added missing MessageEmbed.type documentation

src/structures/MessageEmbed.js, typings/index.d.ts
The video object provided from Discord contains a proxy_url property. This is not reflected in the documentation, and furthermore, the naming convention is proxyURL, so I made the video property of MessageEmbed behave identically to MessageEmbed.image.
**Status**
=> Added missing property to MessageEmbed.video

src/structures/User.js
This pr improves the performance of User#createDM()/deleteDM() by not running an expensive find() (through the User#dmChannel getter) multiple times per method. This also refactors those two methods to take advantage of async/await
**Status**
=> Avoid running a find on client.channels multiple times in User#createDM() and User#deleteDM()

package.json
Mark peer dependencies as optional to quiet warnings from yarn.
This structure was approved as https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md
Support was released in Yarn 1.13.
**Status**
=> Mark peer dependencies as optional

typings/index.d.ts
I don't know how this wasn't already there, but I added the missing defaultRole property to the typings. Did this because I found this issue myself when needing to use it and realized that it wasn't already in the typings file.
**Status**
=> src: Fix missing defaultRole property under Guild in typings.

src/util/Constants.js, typings/index.d.ts
And added `VOICE_SERVER_UPDATE` to `constants.Events`. Though unused inside discord.js, it's still a valid name outside it, and may be used in the future if we expose this event outside raw.
**Status**
=> src: Add missing events in constants

src/client/rest/RequestHandlers/Sequential.js, typings/index.d.ts
1.  Adapt the `rateLimit` event documentation to use the actual data property `limit` instead of the current `requestLimit` as actually emitted in:
https://github.com/discordjs/discord.js/blob/b5df8603e8768b9b50ece24f94e455c3410ef9a2/src/client/rest/RequestHandlers/Sequential.js#L97-L102
2. Change the order properties are documented in to reflect the emitted data
**Status**
=> fix doc for ratelimit data, fixes #3131

src/structures/APIMessage.js, src/structures/Message.js, typings/index.d.ts
This fixes an inconsistency with the api. If you patch only a data embed on a message, the content will be maintained. This allows Message#edit to match that behavior.
```js
const msg = await message.channel.send('test');
const edit = await msg.edit({ embed: { description: 'more tests' } });
return edit.content;
```
Before this pr the content would be '', after this pr the content will be 'test'.
Please note this also maintains the consistency for passing { content: null } which will remove the content, just as { embed: null } would remove the embed.
**Status**
Although this has breaking behavior in terms of the current library expectations, this should technically be …
=> Message#edit shouldn't remove content

src/structures/Guild.js, typings/index.d.ts
fixes #3141 
Removes the code and JSDoc for `options.after` in `Guild.fetchAuditLogs()` as this parameter is not supported by the API.  
Reference: https://discordapp.com/developers/docs/resources/audit-log#get-guild-audit-log-query-string-parameters
I tested the code - `Guild.fetchAuditLogs()` still works, and if anyone passes an `options.after` parameter it still does exactly what it did before: nothing. Therefore I consider this a non-breaking change.
**Status**
=> Removed code and documentation for Guild.fetchAuditLogs "after" option

src/client/actions/Action.js, src/client/actions/MessageReactionAdd.js, src/client/actions/MessageReactionRemove.js, src/client/websocket/handlers/MESSAGE_REACTION_ADD.js
Fixes #3123 
Within the action handler for the messageReactionRemove event, these lines caused it to ignore partial messages.
https://github.com/discordjs/discord.js/blob/579283dfe9c35284eaa5ec2a8c1e081c48a78377/src/client/actions/MessageReactionRemove.js#L30-L31
Due to the fact that, `message.reactions` won't initially be populated on an uncached message. In this PR the `Action.getReaction` method, creates a "filler" reaction to be used, similarly to how the `messageReactionAdd` event handles partial messages.
Here's a boilerplate to test the code changes.
```js
client
.on("messageReactionAdd", async (reaction, user) => {
if (reaction.message.partial) await reaction.message.fetch();
console.log(`${user.username} reacted with "${reaction.emoji.name}".`);
})
.on("messageReactionRemove", …
```
=> fix: messageReactionRemove not emitting for partial messages

src/stores/MessageStore.js, typings/index.d.ts
As discovered in https://github.com/discordjs/discord.js/issues/3153#issuecomment-473657777, in order to get reactions from a fetched pinned message, you had to uncache the message yourself. This PR allows the developer to specify whether they want the messages to be cached or not via the `cache` param, the same way it's done on MessageStore#fetch().
Missing typings for the `cache` param for MessageStore#fetch() have also been added in this PR.
**Status**
=> Adding cache param to MessageStore#fetchPinned()

src/client/rest/RESTMethods.js, src/structures/Guild.js, typings/index.d.ts
This PR adds Guild#fetchBan() to make use of the [Get Guild Ban endpoint](https://discordapp.com/developers/docs/resources/guild#get-guild-ban) and backports the `BanInfo` typedef from master. Also, Guild#fetchBans() has been slightly altered so that it also returns the reason  within the Collection... which was already the case within `client.rest.methods.getGuildBans()` but then was being ignored within the method for some reason. This would be pretty handy for those who want to retrieve the ban reason through the `guildBanAdd` event for instance, instead of having to fetch and filter through audit logs.
#2735 (master) is somewhat related to this PR as it also adds this method, although it seems to be pretty stale for past few months.
**Status**
=> feat(Guild): add Guild#fetchBan()

typings/index.d.ts
The typings for Collection#partition were missing from typings/index.d.ts, thanks DubiousDoggo for pointing that out.
This PR adds them back to it
**Status**
- [] Code changes have been tested against the Discord API, or there are no code changes
=> Added Collection#partition typings from master

typings/index.d.ts
Added the thisArg parameter to Collection#partition typings
**Status**
=> Added the thisArg parameter to Collection#partition typings

src/stores/ChannelStore.js, src/structures/Channel.js, src/util/Structures.js, typings/index.d.ts
A remake of #2138 with latest since original fork deleted. ~~Theoretically~~ *Confirmed even with partials enabled* fixes #3164
>PR based on comments from Gawdl3y. Requesting review from @Gawdl3y.
>Previously all known channel types are accounted for before defaulting to a generic GuildChannel if the channel type is unknown. If discord adds a channel type before the library properly handles it, this could lead to bugs of unknown impact (minor -> critical).
>Because of this fallback, GuildChannel was added to the extendable-structures. (this also is not ideal since extensions to GuildChannel were not inherited by TextChannel or VoiceChannel) Now that the fallback is gone, we can cleanly remove it from the extendable …
=> Remove GuildChannel fallback, and remove GuildChannel as extendable

src/structures/Webhook.js, typings/index.d.ts
You're able to retrieve this using the client, so it would be a nice little helper getter that the library could provide instead of having to construct this yourself.
**Status**
=> feat(Webhook): add url getter

src/client/Client.js, src/rest/APIRequest.js
This pr removes the reliance on querystring and switches to the new node global URLSearchParams (which is also a browser API). This also removes a place where the base API URL is hardcoded so that we use the constants/client.options base URL in case that's ever changed.
**Status**
=> utilize URLSearchParams

src/WebSocket.js
#3180 removed the reliance on the `querystring` package by making use of `URLSearchParams` within the APIRequest, this PR pretty much does the same but within the WebSocket.
**Status**
=> ref(WebSocket): utilize URLSearchParams

src/structures/Guild.js
Roles are currently sorted in the incorrect order.
For example once created the roles will appear in the role manager as the following:
* old role, `position` 2
* new role1, `position` 1
* new role2, `position` 1
* new role3, `position` 1
* `@everyone`, `position` 0
They would however be incorrectly sorted as:
* old role, `calculatedPosition` 4
* new role3, `calculatedPosition` 3
* new role2, `calculatedPosition` 2
* new role1, `calculatedPosition` 1
* `@everyone`, `calculatedPosition` 0
With this pr they are sorted correctly:
* old role, `calculatedPosition` 4
* new role1, `calculatedPosition` 3
* new role2, `calculatedPosition` 2
* new role3, `calculatedPosition` 1
* `@everyone`, `calculatedPosition` 0
For …
=> fix(Guild): sort roles with the same position in the correct order

src/client/Client.js, src/client/voice/ClientVoiceManager.js, typings/index.d.ts
Ever since commit c8225631c9f7906c0aa4966db701fe594074f27c, to create a broadcast you have to use `Client#voice#createBroadcast`. The property, however, was marked as private in the docs, meaning you had to toggle the privates to visible to find it. This PR updates that, and the typings for it.
**Status**
=> docs: make voice public

src/structures/GuildChannel.js
As discovered in #3198 there's a typo on the jsdoc for the param type of `options.reason`, same thing applies here.
**Status**
=> docs(GuildChannel): fix setPosition's reason type

src/client/voice/ClientVoiceManager.js, src/client/voice/VoiceBroadcast.js
this.client is a ClientVoiceManager and thus its this.client.broadcasts  instead of this.client.voice.broascasts
**Status**
=> fix end method in VoiceBroadcast

src/structures/Presence.js, typings/index.d.ts
=> docs(Presence): add missing descriptions to clientStatus

src/structures/Presence.js, typings/index.d.ts
This PR partially reverts https://github.com/discordjs/discord.js/pull/3127/commits/4ac9c5ddca2380ecd0854fe42d2adf6872a46fe2, since the types were correct before as Presence#clientStatus [doesn't](https://discordapp.com/developers/docs/topics/gateway#client-status-object) include the "offline" status and adds a ClientPresenceStatus typedef (which excludes "offline" from the PresenceStatus's typedef) to match the typings.
**Status**
=> docs(Presence): add ClientPresenceStatus typedef

src/structures/MessageEmbed.js, typings/index.d.ts
Make use of `resolveColor` utility method in `MessageEmbed` constructor to mirror `setColor`
https://github.com/discordjs/discord.js/blob/b759fc415e89c1f3eb3523deb23c5b514968c845/src/structures/MessageEmbed.js#L237-L240
Alternatively, I would say that this `resolveColor` method is kinda extraneous anyway, and I'd remove the whole thing. It might just not be worth it for backwards compatibility though
**Status**
=> Resolve color in embed constructor

src/client/websocket/WebSocketManager.js
This resolves #3191 where in resumed never fires. 
I don't think 1001 should be included on resetting the sessionID based on Line 372 & 373 of https://github.com/discordjs/discord.js/blob/master/src/client/websocket/WebSocketShard.js
Using latest master with this modification fixed my issue entirely, refer to screenshot below.
https://media.discordapp.net/attachments/222197033908436994/568036331452891146/unknown.png?width=297&height=211
**Status**
=> Only reset sessionID when close code is 1000 or 4006

src/structures/interfaces/Collector.js
The collector options typedef doesn't give what unit the collector is for, this PR fixes that
**Status**
=> docs: give the unit for collectoroptions time parameter

src/client/websocket/WebSocketManager.js, src/client/websocket/WebSocketShard.js, src/client/websocket/handlers/RESUMED.js, src/sharding/ShardClientUtil.js, typings/index.d.ts
Per #3191, the resumed event was not properly being emitted. This PR solves this, and closes #3191.
**Status**
=> src: Fix resume event not being emitted properly

src/util/Structures.js
=> Structures.extend checks the prototype chain

src/util/Util.js
Changes `Util.splitMessage` to allow a StringResolvable to be passed in instead of just a string, just a super tiny but useful improvement. I noticed that MessageEmbed had this in most of its methods and it would be great for this too.
**Status**
=> Use StringResolvable in Util.splitMessage

typings/index.d.ts
The [typings for `Collection#find` and `Collection#findKey`](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L297) currently suggest neither can return undefined, yet that is untrue.
- [Collection#find](https://github.com/discordjs/discord.js/blob/master/src/util/Collection.js#L172)
- [Collection#findKey](https://github.com/discordjs/discord.js/blob/master/src/util/Collection.js#L190)
**Status**
=> fix(typings): Collection#find & Collection#findKey

src/stores/GuildMemberStore.js, typings/index.d.ts
This PR adds support for the [compute_prune_count](https://discordapp.com/developers/docs/resources/guild#begin-guild-prune-query-string-params) query string param by adding a `count` option. I'm not sure about the typings since there's probably a nicer way instead of just having the return type as `Promise<number | null>`? So, I'll just leave that for now.
**Status**
=> feat(GuildMemberStore) add options.count to prune

src/client/websocket/WebSocketShard.js
Seems like more internal sharding issues showed themselves, but that's alright, I'll patch them all, one at a time.
Per the following logs:
<details>
<summary>Debug Logs</summary>
```
[04:06:30] - [36mverbose[39m: [Novus FM -- Shard 0] [WS => Shard 0] Session ID is present, attempting an immediate reconnect...
[04:06:30] - [36mverbose[39m: [Novus FM -- Shard 0] [WS => Shard 0] Trying to connect to wss://gateway.discord.gg/, version 6
[04:06:30] - [36mverbose[39m: [Novus FM -- Shard 0] [WS => Shard 0] Setting a HELLO timeout for 20s.
[04:06:30] - [36mverbose[39m: [Novus FM -- Shard 0] [WS => Shard 0] Opened a connection to the gateway successfully.
[04:06:30] - [36mverbose[39m: [Novus FM -- Shard 0] [WS => …
```
=> src: Hopefully fix random broken reconnects

src/client/websocket/WebSocketManager.js, src/client/websocket/handlers/READY.js
For some reason, Client#readyAt was set by the shard turning ready, not the Client turning ready... This PR fixes that
**Status**
=> src: Client#readyAt should be updated when triggerReady is called

src/client/actions/Action.js, src/client/actions/GuildMemberRemove.js, src/structures/Guild.js
Make use of partials for the GuildMemberRemove event as well as Guild#me. Although it doesn't provide much use as for retrieving accurate properties of the member (such as roles) as you can't fetch a member that left the guild for obvious reasons, it should allow developers to monitor the `guildMemberRemove` event for uncached members.
**Status**
=> feat(Partials.GuildMember): GuildMemberRemove & Guild#me

src/structures/VoiceChannel.js, typings/index.d.ts
The purpose of this PR is to accommodate for an edge case which is the fact that Discord requires the user to have the `CONNECT` and `MANAGE_CHANNELS` permissions in order to edit a VoiceChannel.
The reason why I didn't just override the `manageable` method inherited from GuildChannel is due to the fact that, you could "manage" the channel by modifying the position of the VoiceChannel even when you lack the `CONNECT` permission... Discord permissions are nice. However, not sure if this is the best way to go about this since changing the position of the channel is still technically editing the channel, which contradicts with this method. Also I'm not sure if the GuildChannel should also have this method to maintain consistency, since for other channel types the editable method wouldn't …
=> feat(VoiceChannel): add editable

src/client/voice/VoiceConnection.js, src/errors/Messages.js, src/structures/VoiceState.js, typings/index.d.ts
In this PR I've added `setSelfMute` & `setSelfDeaf` methods to the `VoiceState` class, I've also managed to add typings for implemented methods and `VoiceConnection#voice`.
Also managed to fix a slight bug where Error wasn't imported in VoiceState so some errors weren't being thrown with the proper string.
replaces #3171 
**Status**
=> Feat(VoiceState): self mute/deaf methods

src/client/actions/Action.js, src/client/actions/MessageDeleteBulk.js
Make use of partials for the MessageDeleteBulk event. Although it doesn't provide much use as for retrieving accurate properties of the messages (such as the content) as you can't fetch a message that was deleted for obvious reasons, it should allow developers to monitor the messageDeleteBulk event for uncached messages.
The `cache` param on DataStore.add(...) will be set to `false` for this since the message will immediately be deleted anyways, so it would be a bit redundant to cache the messages.
**Status**
=> feat(Actions): use partials for MessageDeleteBulk

src/structures/GuildMember.js, src/structures/VoiceState.js, typings/index.d.ts
Please see https://github.com/discordapp/discord-api-docs/pull/933/.
- Allows members to be kicked from voice channels
- Adds `VoiceState#setChannel`
- Improves reliability of using `voiceState.connection`
- Removes duplicated methods on GuildMember
- `member.setDeaf` => `member.voice.setDeaf`
- `member.setMute` => `member.voice.setMute`
- `member.setVoiceChannel` => `member.voice.setChannel`
**Status**
=> Add ability to kick members from VoiceChannels and remove duplicated methods

src/client/rest/RESTMethods.js, src/structures/GuildMember.js, typings/index.d.ts
This PR backports e64773e21bb4070d57ceb1910b30d753b2585c8b (#3242) implementing voice kicking of guild members from a voice channel.
**Status**
=> feat(GuildMember): add support for voice kicking

src/client/Client.js
Although not explicitly said, the current wording makes it seem like all channels are cached and available at any time in this store. Hopefully this variation makes it a bit clearer.
**Status**
=> Disambiguate the description of <client>.channels

src/client/actions/Action.js, src/client/actions/MessageReactionAdd.js, src/client/actions/MessageReactionRemove.js
This PR fixes #3248. 
When a message gets updated, the MessageUpdate action handler was passing [`data.author`](https://github.com/discordjs/discord.js/blob/master/src/client/actions/MessageUpdate.js#L10) into [Action.getMessage(...)](https://github.com/discordjs/discord.js/blob/master/src/client/actions/Action.js#L36-L45), if the developer has partials enabled for messages it will call [MessageStore.add(...)](https://github.com/discordjs/discord.js/blob/master/src/client/actions/Action.js#L39-L43) which will call [DataStore.add(...)](https://github.com/discordjs/discord.js/blob/master/src/stores/MessageStore.js#L18). 
Here's where the issue happens; since the passed `data` will exist within the store as it's previously been cached and Message._patch exists it will end up [calling the …
=> fix(Partials): Client#event:messageUpdate(oldMessage) and MessageReactionAdd on guild channels

src/client/websocket/WebSocketShard.js
When you have `zucc` installed, a global [TextDecoder](https://github.com/discordjs/discord.js/blob/master/src/client/websocket/WebSocketShard.js#L12-L15) is used which would throw `ReferenceError: TextDecoder is not defined` for node 10.x. Since `zstd` is truthy, this line
https://github.com/discordjs/discord.js/blob/0dd3ed72ef3e2c76fe330e13ec572ad05be505a2/src/client/websocket/WebSocketShard.js#L262
would execute and end up throwing `TypeError: Cannot read property 'decode' of undefined`.
TextDecoder is only global for node [>=11.0.0](https://nodejs.org/api/globals.html#globals_textdecoder) and since v12 enforces a minimum of 10.0.0 this PR will add backwards compatibility to maintain that by importing [TextDecoder](https://nodejs.org/api/util.html#util_class_util_textdecoder) from the …
=> fix(WebSocketShard): TextDecoder for node 10.x

typings/index.d.ts
Currently, [`Guild#member()`](https://github.com/discordjs/discord.js/blob/master/src/structures/Guild.js#L493) can return null, but the typings guranteed that it would return a `GuildMember`, this PR fixes that.
**Status**
=> fix(typings): Guild#member did not have null as a possible return type

src/structures/Message.js
This fixes a bug with Message#pinnable where it would falsely claim you can pin certain messages.
example:
**Status**
=> fix(Message#pinnable): you can't pin system messages

typings/index.d.ts
This brings some consistency with Array#reduce's typings and to reality, this is a backport from https://github.com/discordjs/collection/pull/4 for the meanwhile.
**Status**
=> typings(Collection): Use T in accumulator and initialValue

src/errors/Messages.js, src/structures/GuildAuditLogs.js, src/structures/GuildEmoji.js, src/structures/GuildMember.js, src/structures/Invite.js
Although it's very unlikely, Guild#me is nullable and could throw some unhelpful error messages in cases where it's uncached. This PR aims to avoid that by adding a custom error message that will be thrown instead.
**Status**
=> feat: add custom error message for uncached Guild#me

typings/index.d.ts
VoiceState has a connection property that is not described in the typings.
**Status**
=> fix: add connection to voice state typings

typings/index.d.ts
StreamOptions#volume takes a boolean to disable the volume transformer.
**Status**
=> fix: StreamOptions#volume typings

src/client/Client.js, src/structures/ClientUser.js, src/structures/Guild.js, src/structures/GuildChannel.js, src/structures/Message.js, src/structures/OAuth2Application.js, src/structures/PermissionOverwrites.js, src/structures/User.js, src/structures/interfaces/TextBasedChannel.js
This PR marks everything deprecated as `@deprecated` to generate a more prominent warning in the documentation.
---
`ClientUser#mfaEnabled` is not user account only, on bots it reflects the mfa status of the owning user account.
This is useful to determine whether the bot can make use of its administrative permissions, if it has them, when the guild requires server-wide 2fa.
---
`PermissionOverwrites#allow` and `#deny` have been undeprecated. (Although the type changes in v12)
`#allowed` and `#denied` however have been deprecated.
**Status**
=> chore: explicitly mark everything deprecated as `@deprecated`

typings/index.d.ts
This PR adds the typings to help allow the creation of `category` channels.
**Status**
=> Add CategoryChannel To `channels.create`

src/structures/Guild.js
This pull request allows for role positions to be batch-updated similar to how channel positions are. It uses the Discord API endpoint `PATCH /guild/:id/roles`.  It is a pull request to add the enhancement mentioned in issue #3280.
**Status**
=> Add setRolePositions function

src/client/rest/RESTMethods.js, src/structures/Guild.js
This PR fixes a bug not allowing one to fetch a member without having the user cached already.
Leading you to have more code and make more requests than necessary:
`client.fetchUser('id).then(u => guild.fetchMember(u)).then(member => /* ... */);`
to just
`guild.fetchMember(u).then(member => /* ... */);`
**Status**
=> fix(Guild): allow fetchMember to be used with an uncached user

src/structures/Presence.js
As per the title, documentation-only update to add the `Presence.client` as raised by Buckshot on Discord.
**Status**
=> Presence does not extend Base, therefore presence.client was undocumented

src/util/Constants.js
This PR changes `Guild#iconURL` to default to a `gif` extension for animated guild icons.
**Status**
=> feat(Guild): default iconURL to gif if animated

src/client/rest/RESTMethods.js, src/structures/Guild.js, src/util/Constants.js, typings/index.d.ts
This PR backports:
* Several properties of `Guild` from #3168
* * `banner` and the `bannerURL` getter
* * `description`
* * `embedChannelID`
* * `maximumMembers`
* * `maximumPresences`
* * `widgetEnabled`
* * `widgetChannelID`
* * `vanityURLCode`
* * `fetch` method
* `Guild#setRolePositions` from #3317
**Status**
=> feat(Guild): backport misc properties and setRolePositions

src/client/rest/RESTMethods.js, src/structures/Emoji.js, src/structures/Guild.js, typings/index.d.ts
This PR backports #1877 (c93c4ad21fc2272ab2269083dd94bbb6af4f7aa7) in a semver-minor manner.
- Add `Emoji#delete` method
- Deprecate `Guild#deleteEmoji`
**Status**
=> feat(Emoji): add delete method

src/index.js, src/structures/ClientApplication.js, src/structures/Team.js, src/structures/TeamMember.js, src/util/Constants.js, typings/index.d.ts
This adds support structures for Discord Teams. If you run Client#fetchApplication() you will now have a ClientApplication object that's owned by either a User or a Team along with all the other things the Teams data brings with it.
Note: TeamMember#permissions is likely to change in the future when proper permissions are implemented for them. I assume that property should become more like a BitField type object, but all of that data isn't available at this time as far as I am aware.
**Status**
=> feature: teams support

src/stores/VoiceStateStore.js, src/structures/Guild.js, typings/index.d.ts
This PR adds `.voiceStates` to typings and to the JSDocs
**Status**
=> Add Guild.voiceStates To Typings And JSDocs

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question---general-support-request.md
GitHub lets issue templates automatically add certain labels to an issue, and this PR adds that to discord.js's issue templates
**Status**
=> misc: Automatically add labels to issues that use the template

src/structures/Guild.js, typings/index.d.ts
Guild didn't have Guild.setBanner() yet, so here it is. I can't test it though, because I don't have a Tier 2 server.
**Status**
=> Add setBanner method to Guild

src/structures/OAuth2Application.js, src/structures/Team.js, src/structures/TeamMember.js, src/util/Constants.js, typings/index.d.ts
This PR backports #3350 (a22aabf6a827f8643cf84939e9065b6c37b289e0) in a semver-minor manner.
(Namingly adding a `team` property opposed to replacing `owner`)
**Status**
=> feat(Teams): backport support for teams

src/client/websocket/WebSocketManager.js, src/client/websocket/WebSocketShard.js, src/client/websocket/handlers/CHANNEL_PINS_UPDATE.js, src/sharding/Shard.js, src/sharding/ShardingManager.js, travis/deploy.sh, typings/index.d.ts
:blue_heart: Fix typos across **discord.js repository**
<details><summary>See all fixed files</summary>
<p>
```
discord.js/src/client/websocket/WebSocketManager.js:300:43: "occured" is a misspelling of "occurred"
discord.js/src/client/websocket/WebSocketShard.js:468:76: "conenction" is a misspelling of "connection"
discord.js/src/client/websocket/handlers/CHANNEL_PINS_UPDATE.js:17:79: "occured" is a misspelling of "occurred"
discord.js/src/sharding/Shard.js:322:20: "recieving" is a misspelling of "receiving"
discord.js/src/sharding/ShardingManager.js:76:79: "postive" is a misspelling of "positive"
discord.js/travis/deploy.sh:14:106: "commiting" is a misspelling of "committing"
discord.js/travis/deploy.sh:32:26: "commiting" is a misspelling of "committing" …
```
=> Fix typos across discord.js repository

.github/FUNDING.yml
Comment out (keep for reference) unused funding platforms. Also fixes a duplicate `github` key.
=> Fix duplicate key in FUNDING.yml

typings/index.d.ts
because compu told me to
**Status**
=> typings: switching of overload for RoleStore#fetch

src/structures/interfaces/Collector.js, typings/index.d.ts
A remake of #3239 with the requested changes, since that pr/branch was closed. This adds the ability to consume collectors with the for-await-of syntax.
**Status**
=> feat(Collectors): allow collectors to be consumed by for-await-of loops

src/stores/RoleStore.js, src/structures/Guild.js, typings/index.d.ts
Moves Guild#defaultRole to RoleStore, which suits the use of stores far better.
Also renames it to `everyone`, as others have suggested.
**Status**
=> Move Guild#defaultRole to RoleStore#everyone

src/util/Util.js
**Paragraph on this PR**
I changed the regex to output the results if you provide `<aemoji:123456789012345678>` and `<:aemoji:123456789012345678>` which will output `{ animated: false, name: "aemoji", id: "123456789012345678" }` or `<:emojiname:>` which outputs `{ animated: false, name: "emojiname", id: null }` or `<a:emoji:>` which would output `{ animated: true, name: "emoji", id: null }`. Before this PR the method would return that the emoji was animated if you provided something like `<anemojiname:emoji_id>` because the name started with an `a`.
---
**Simplified description of this PR (using examples)**
I changed the regex a bit for the `parseEmoji` function to fix a few parsing issues.
Parsing results before …
=> Small changes to parseEmoji regex

src/structures/Team.js, src/structures/TeamMember.js, typings/index.d.ts
The client property is already present on the Team object, so it doesn't need to be passed to the team member constructor when adding them to the Collection.
**Status**
=> Remove client from TeamMember constructor

src/client/actions/Action.js, src/client/actions/MessageReactionAdd.js, src/client/actions/MessageReactionRemove.js, src/structures/Message.js
**The PR #3250 should be merged before this PR**
When a message was deleted using the method [`Message#delete()`](https://github.com/discordjs/discord.js/blob/8b83e2fdcbead62ef018b6423f02e07ade0cd40f/src/structures/Message.js#L455), the MessageDelete action handler [was executed](https://github.com/discordjs/discord.js/blob/8b83e2fdcbead62ef018b6423f02e07ade0cd40f/src/structures/Message.js#L458) by it.
After that, the MessageDelete action handler [got executed](https://github.com/discordjs/discord.js/blob/8b83e2fdcbead62ef018b6423f02e07ade0cd40f/src/client/websocket/handlers/MESSAGE_DELETE.js#L4) again by the WebSocketManager.
Causing double emission.
The same problem can be found in …
=> Fix(Structure): Message#delete() cause event messageDelete to fires twice

src/structures/Invite.js, typings/index.d.ts
https://discordapp.com/developers/docs/resources/invite#invite-metadata-object-invite-metadata-structure
**Status**
=> feat(Invite): add targetUser(Type)

src/stores/ReactionUserStore.js
This PR fixes #3268.
Same problem as #3252.
[`ReactionUserStore#remove()`](https://github.com/discordjs/discord.js/blob/97de79bd5e34ab043a75db1f4fdb738bd20f21c3/src/stores/ReactionUserStore.js#L44) [execute](https://github.com/discordjs/discord.js/blob/97de79bd5e34ab043a75db1f4fdb738bd20f21c3/src/stores/ReactionUserStore.js#L52) messageReactionRemove action handler.
After that, it [got executed](https://github.com/discordjs/discord.js/blob/97de79bd5e34ab043a75db1f4fdb738bd20f21c3/src/client/websocket/handlers/MESSAGE_REACTION_REMOVE.js#L4) again by the WebSocketManager.
**Status**
=> Fix(Structure): ReactionUserStore#remove() cause event messageReactionRemove to fires twice

package.json, src/client/Client.js, src/rest/APIRequest.js, src/util/Constants.js, typings/index.d.ts
Lately I suffered from some requests that gets too long to resolve, and due to this, our bot slowed down a lot, as well causing us some problems specially in some of our modules. By adding a request timeout feature for Discord.js requests, we can make sure that requests that takes too long to resolve could get cancelled, hence solving the problem of requests that takes an inconsiderable amount of time to resolve.
**Status**
=> Feat: Abort Requests that takes a lot of time to resolve

src/structures/Webhook.js, typings/index.d.ts
Executing a Webhook under the Slack route will return just "ok" if the result worked. See https://github.com/discordapp/discord-api-docs/issues/1067
We could also add manual fetch, but that wouldn't work for the WebhookClient..
**Status**
=> src: Update Webhook#sendSlackMessage to be accurate with what the API returns

src/structures/Guild.js
Just sorts the guild flags and makes sure it's up to date with https://github.com/discordapp/discord-api-docs/commit/a8e12a2d18df9a71c97ba7940e7cd2779d289196
**Status**
=> src: Sort guild features and make sure they're up to date

src/util/Constants.js
Adds unit to clientoptions#restRequestTimeout
**Status**
=> docs: document ClientOptions#restRequestTimeout unit

src/util/Permissions.js, typings/index.d.ts
Backport #3309 patch for Permissions.STREAM to 11.5-dev branch
**Status**
=> src: Backport #3309 (STREAM permission) to 11.5-dev

typings/index.d.ts
Currently the typings indicate that [DataStore#resolve](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L1719) and [DataStore#resolveID](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L1720) are guranteed to return said object that the store keeps, or an id, which is, however, incorrect.
Also DataStore#remove correction.
**Status**
=> fix(typings): DataStore#resolve & DataStore#resolveID can also return null

src/stores/ChannelStore.js
Fixes #3324 and fixes #3437 
When ChannelStore#add() was being called for DMs [here](https://github.com/discordjs/discord.js/blob/master/src/client/actions/ChannelCreate.js#L10), the existing DM wouldn't be returned since `guild` param will be falsy
https://github.com/discordjs/discord.js/blob/3fcc862c5fa336bb26c570655245d57e2e532f20/src/stores/ChannelStore.js#L58-L61
This led to Channel.create() getting [called](https://github.com/discordjs/discord.js/blob/master/src/stores/ChannelStore.js#L63) where a new instance of a DMChannel was being [created](https://github.com/discordjs/discord.js/blob/master/src/structures/Channel.js#L99) everytime which explains #3437 and since its being initialised with an empty message store everytime, the initial message (which would have called createDM) …
=> fix(ChannelStore): return existing DMChannels within add()

src/util/Util.js
this PR fixes the `Utils#splitMessage` method because resolveString should be called as `Util.resolveString` since it's a static method.
___
**Update**
kyranet posted a better reason why this PR should be merged [here](https://github.com/discordjs/discord.js/pull/3456#issuecomment-526960062).
**Status**
=> Fix Util#splitMessage when destructured

src/util/BitField.js, src/util/Permissions.js, typings/index.d.ts
From `you never knew#0717` in d.js support who had the idea for this method.
It does what Permissions#has does (its basically a copypasta of it), but will return true if any of the Permissions provided exist, rather than all of them.
I'm not sure how common the use-case will be, but here it is for consideration.
**Status**
=> feat(Permissions): Add new method Permissions#any

typings/index.d.ts
Closes #3445 as the head repository was deleted, leaving the PR in an unfixable state.
(Can't apply requested changes nor run required checks)
The original PR moved the `members` getter to `GuildChannel` where it is actually defined:
https://github.com/discordjs/discord.js/blob/c86a6154aa736aee6bde9fa76ebd34b24225ee79/src/structures/GuildChannel.js#L270-L278
This PR now also removes the now redundant declarations in deriving classes and runs the checks.
**Status**
=> typings(GuildChannel): add members getter

src/structures/Role.js
`Role#comparePositionTo` will reject with a type error when an invalid `RoleResolvable` is passed. However this is a synchronous method and should throw instead.
This PR takes care of that.
**Status**
=> fix(Role): throw TypeError in comparePositionTo

src/structures/Guild.js, typings/index.d.ts
This PR adds a `Guild#partnered` property, taking advantage of #3441 and [discordapp/discord-api-docs@`a8e12a2`](https://github.com/discordapp/discord-api-docs/commit/a8e12a2d18df9a71c97ba7940e7cd2779d289196).
**Status**
=> feat: Guild#partnered

docs/topics/partials.md, src/client/actions/Action.js, src/client/actions/MessageReactionAdd.js, src/stores/ReactionStore.js, src/structures/DMChannel.js, src/structures/MessageReaction.js, src/structures/User.js, src/util/Constants.js, typings/index.d.ts
In partial DM channels the `recipient` is used to determine whether the channel is partial or not, however this property can safely be assumed since the author's id can be accessed in the scopes of where Action#getChannel() is called. This is done in this PR and now DMChannel#lastMessageID is used to determine whether the channel is partial. Since the recipient of the channel will now be present for partial channel this enables a DMChannel#fetch() to retrieve accurate properties of the partial channel, which has been added in this PR
___
When you have PartialTypes.MESSAGE enabled, the `messageReactionAdd` (and `messageReactionRemove`) client events behave like so for uncached messages:
```js
client.on('messageReactionAdd', async (reaction) => {
console.log(reaction.count); // will always …
```
=> feat(Partials): add DMChannel/MessageReaction#fetch() and PartialTypes.REACTION

.github/ISSUE_TEMPLATE/question---general-support-request.md, .github/SUPPORT.md
Recently, GitHub added [support resources](https://help.github.com/en/articles/adding-support-resources-to-your-project), which are there to, well, show ways of getting support (similar to what was done in the general questions issue template). This PR initializes this feature and redirects the general question template to the support document
**Status**
=> github: add support file and redirect to it

src/rest/APIRouter.js
`/reactions` endpoint shares rate-limits with `/reactions/:reaction` and `/reactions/:reaction/:id`. This corrects those 429s.
**Status**
=> fix(rate-limits): reactions buckets need to be shared with sub-routes

typings/index.d.ts
This PR just edits a few types for more clear interaction with channels in TypeScript.
- Creating channels now returns correct type (instead of union) based on specified kind of channel.
- Editing channels also returns correct type that allows to chain promises & assign awaited values
```ts
voiceChannel = await voiceChannel.setName('voice 1337')
.then(v => v.setBitrate(1337))
.then(v => v.delete())
```
P.S. I know these requests could be combined into single `.edit`. That's just an example.
**Status**
=> typings: make TypeScript interaction with channels better

src/stores/GuildEmojiRoleStore.js, src/stores/GuildMemberRoleStore.js
This defines Symbol.species as a Collection for both GuildMemberRoleStore and GuildEmojiRoleStore, as these don't actually extend DataStores.
Fixes a bug that I think comes from the polymorphic `new this` return values for functions like `<DataStore>.filter()`
**Status**
=> fix(stores): Add symbol.species for not-actual-stores

src/client/rest/RESTMethods.js
Backports #3496 to 11.5-dev
**Status**
=> backport(#3496): Default channel type incorrectly set

typings/index.d.ts
According to both discord.js and discord API docs GuildChannel#parentID is marked as nullable. This PR adapts the typings to reflect this behavior.
ref: https://discordapp.com/developers/docs/resources/channel#channel-object
ref: https://discord.js.org/#/docs/main/master/class/GuildChannel?scrollTo=parentID
**Status**
=> typings: GuildChannel#parentID is nullable

typings/index.d.ts
**Target: 11.5-dev**
According to both discord.js and discord API docs GuildChannel#parentID as well as GuildChannel#parent are marked as nullable. This PR adapts the typings to reflect this behavior and as such acts as backport and addition to #3508.
ref: https://discordapp.com/developers/docs/resources/channel#channel-object
ref: https://discord.js.org/#/docs/main/master/class/GuildChannel?scrollTo=parentID
**Status**
=> typings: GuildChannel#parent and #parentID are nullable

typings/index.d.ts
Fixes #3494 
This PR adds the missing `deleted` properties and makes `reason` optional in `TextChannel#setNSFW` as mentioned in #3494.
Also makes `Guild#setDefaultMessageNotifications`' `reason` parameter optional.
**Status**
=> typings: optional reason for setNSFW and add deleted properties

src/util/Util.js
**Targetting 11.5-dev**
This method causes bugs where it is used because it mutates the array.
1. Comparing guilds with `Guild#equals` may mutate the guild features array causing it to be inaccurate. (fixed for master in #2544)
2. Comparing `GuildMember._roles` with each other may mutate the underlying roles array which causes the `oldMember` parameter for the `guildMemberUpdate` event to have inaccurate roles.
**Status**
=> Make arraysEqual avoid mutating the input arrays

src/structures/GuildChannel.js, typings/index.d.ts
**target: 11.5-dev**
Backports the utility getter Guild#permissionsLocked to 11.5-dev
**Status**
=> backport GuildChannel#permissionsLocked

src/client/actions/ChannelDelete.js
Message#deleted as well as Message#deletable currently return false/true if the messages channel is deleted. Since our users use these properties to check if a message can be deleted before doing so this can lead to unexpected behavior.
If the channel is deleted the API will respond with an error since the respective endpoint is unavailable.
This PR attempts to change this behavior by setting messages deleted on channel_delete.
Since discord.js receives channel close events if DM channels are closed they should be excluded from this change. The typeof check should be more robust than checking the `.type` property and is possibly more likely to be detected should the class responsible for direct message channels be …
=> Consider messages deleted if their channel is deleted

src/structures/VoiceState.js, typings/index.d.ts
The `|| false` is because discord doesn't include the [`self_stream`](https://discordapp.com/developers/docs/resources/voice#voice-state-object-voice-state-structure
) field when the member isn't streaming anymore for some reason
**Status**
=> feat: add VoiceState#streaming

typings/index.d.ts
Fixes typing being inconsistent with the master version of Emoji class.
Originally found in Discord: https://discordapp.com/channels/222078108977594368/223867697312694272/63465929058549760
**Status**
=> Fix typings for Emoji class on master

src/client/actions/VoiceStateUpdate.js, typings/index.d.ts
ref:
https://github.com/discordjs/discord.js/blob/c3228b426370a6cc5d48cb41e28bbe9f731e8473/src/client/actions/VoiceStateUpdate.js#L13-L15
**Status**
=> docs: VoiceStateUpdate always sends an instance of VoiceState

src/structures/Message.js
If `data.edited_timestamp` is `undefined`, `this.editedTimestamp` becomes `NaN`. An example of when this happens is when you send an embed.
**Status**
=> fix(Message): check for edited_timestamp in data when patching message

typings/index.d.ts
Typings-only update.
PR #3542 accidentally resulted in removal of `deletable` on `GuildEmoji` - this PR fixes it.
**Status**
=> Typings: restore deletable on GuildEmoji

src/client/voice/receiver/VoiceReceiver.js
This PR fixes `VoiceReceiver`s failing to decode PCM data after the first silence of a user.
The cause is that the relevant `OpusEncoder` got reused after being destroyed.
It was destroyed here, but not removed from the map like it should.
https://github.com/discordjs/discord.js/blob/505df2ebb3b49503d98f635534e9644db7375925/src/client/voice/receiver/VoiceReceiver.js#L113-L115
After removing it from the map a new one was created in case the user starts speaking again and valid PCM data could be decoded.
This PR also fixes the documentation about the PCM format, it's actually `s16` and not `s32`.
**Status**
=> fix(VoiceReceiver): delete opus encoder from map in stoppedSpeaking

src/client/rest/RESTMethods.js
This PR filters out duplicated duplicated roles when patching a `GuildMember`.
The intend behind this is to apply this to `GuildMember#addRoles` where an error occurs when one is trying to add a role which is already there.
That behavior would be identical to the behaviour of `addRole`, `removeRole`, and `removeRoles` then.
**Status**
=> feat(GuildMember): filter out duplicate roles when updating

src/client/voice/receiver/PacketHandler.js
This fixes https://github.com/discordjs/discord.js/issues/3550. 
As mentioned in [my comment](https://github.com/discordjs/discord.js/issues/3550#issuecomment-546559404) a wrong assumption was seemingly made about incoming discord voice packets, which got revealed during a recent discord change that broke Opus voice streams. Right after the RTP Header Extensions and just before the Opus packet is a single undocumented byte that is seemingly used by the Discord client. Previously this byte was always 0x00 and probably assumed to be padding, but now it is 0x02 for most regular voice packets and 0x00 for tiny/silent voice packets.
Inspecting many packets I could always only find this single byte. This change ensures …
=> Fix broken opus voice streams

package.json
A while ago a RFC was made for yarn to allow marking peer dependencies as optional and with that silencing the warnings about missing peer dependencies. [You can read that RFC here](https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md). This was added in yarn in version 1.13.0 ([PR](https://github.com/yarnpkg/yarn/pull/6671) and pnpm version 3.2.0-1 ([PR](https://github.com/pnpm/pnpm/issues/1486)). Later it was also added to npm in version 6.11.0 ([Changelog](https://github.com/npm/cli/blob/latest/CHANGELOG.md#v6110-2019-08-20))
Since it is now available in all 3 major package managing CLI tools I think this repo should make use of the additional fields in package.json to silence …
=> chore: mark optional peerDependencies as optional

src/structures/MessageCollector.js, src/structures/ReactionCollector.js
A max listener count of `0` is considered no limit. See `EventEmitter#setMaxListeners` its [docs](event_emitter_docs)
(This also applies to `EventEmitter.defaultMaxListeners`)
This PR avoids `Collector`s to set another limit if its `0`.
[event_emitter_docs]:https://nodejs.org/api/events.html#events_emitter_setmaxlisteners_n
**Status**
=> fix(*Collector): account for a max listener count of 0

typings/index.d.ts
Fixes my extremely old pull #3212 that didn't actually update the typing (Didn't know at the time, I thought it just meant the jsdoc comments). Apologies! I'm not sure how I suddenly remembered 200 days later after learning some typescript.
**Status**
*^ actually made sure this time*
=> typings(Util): use StringResolvable (fixes old pull)

src/structures/MessageAttachment.js, typings/index.d.ts
QoL addition for checking if the attachment has been marked as a spoiler.
**Status**
=> feat(MessageAttachment): add spoiler property

docs/general/welcome.md
Original link pointed to https://github.com/discordjs/guide/blob/v12-changes/guide/additional-info/changes-in-v12.md, which is invalid. I have changed the link to direct users to the Discord.JS guide (https://discordjs.guide/additional-info/changes-in-v12.html), as per @Androz2091's feedback.
On the documentation for `master`, the original link to the Update Guide points to a "404 Not Found" page. 
**Status**
=> Fixed the Update Guide Link

typings/index.d.ts
`GuildAuditLogsFetchOptions.type` was originally defined as a `string | number`, so Typescript does not detect any errors when providing an invalid string for the type. This PR fixes this, and also allows suggestions for what is allowed in the field.
**Status**
=> typings(GuildAuditLogsFetchOptions): fix options.type typing

src/rest/APIRouter.js
NodeJS v10+ Util.inspect symbol name has changed from Node v8
**Status**
=> Fix(Node): use proper symbol for util.inspect

src/structures/Presence.js, src/util/Constants.js, typings/index.d.ts
This PR covers the custom status Discord recently released to the public. The PR was initially created 4 months ago based on data mined data but now that custom statuses are in the public the PR should enter the merge track.
Evals performed with code changes:
---
**_Original post from 4 months ago:_**
This is an upcoming feature that has been data mined from the Canary client. Presumably these few lines are all that is needed since in ClientPresence the number gets matched to the indexOf the ActivityType constant and the new options are as follows:
```json5
{
PLAYING: 0,
STREAMING: 1,
LISTENING: 2,
WATCHING: 3,
CUSTOM_STATUS: 4 // the newly added type
}
```
Example images after enabling the option, courtesy of a …
=> feat: support for CUSTOM_STATUS activity type

src/client/voice/ClientVoiceManager.js
Listening on the error event *outside* of the `authenticated` event.
While in most cases it works to only listen inside the `authenticated` event, sometimes it doesn't work and causes an unhandled error event which forces node to close.
See Issues:
https://github.com/discordjs/discord.js/issues/3487
https://github.com/discordjs/discord.js/issues/3476
**Status**
=> Handle voice errors outside of authenticated event

README.md, src/client/voice/VoiceConnection.js, src/client/voice/networking/VoiceWebSocket.js, src/client/voice/receiver/PacketHandler.js
Fixes the issue as per #3524. Based on the feedback from Discord (jhgg), and the other code posted by dragonbane0 and Kunikita. This is working after some testing in a produciton environment.
I'm not a node developer, so please be nice :)    will fix any issues that people find.
**Status**
=> Start/Stop speaking events on UDP packets

src/stores/ReactionStore.js
This PR simply fixes a bug in the documentation of `ReactionStore.resolveID()` which mentions the parameter should be a `Role`, not a `MessageReactionResolvable`
**Status**
- 
=> Docs: ReactionStore.resolveID should take Reaction, not role

src/structures/Webhook.js, typings/index.d.ts
This PR adds support for a `Webhook#avatarURL` function. Although not documented, a webhook's avatar follows the same format as a users.
I tested this with the following code in my eval command:
```js
(async () => {
const webhook = await msg.channel.fetchWebhooks().then(h => h.first());
return this.client.rest.cdn.Avatar(webhook.id, webhook.avatar);
})()
```
**Status**
=> feat(Webhook): addition of Webhook#avatarURL function 

typings/index.d.ts
Changes Iterator to IterableIterator for BitField
**Status**
=> Fix(typings): Use IterableIterator instead of Iterator

typings/index.d.ts
This PR adds the missing `NewsChannel` and `StoreChannel`s to the `Extendable` type to allow extending those using `Structures.extend`.
For reference:
https://github.com/discordjs/discord.js/blob/1352bff2fd969092b48368ebc1f05a080572f827/src/util/Structures.js#L78-L79
**Status**
=> typings(Extendable): add missing channels

src/structures/DMChannel.js, src/structures/TextChannel.js
This PR removes the acknowledge method from `TextChannel` and `DMChannel` as they no longer do anything
**Status**
=> Remove acknowledge method from TextChannel & DMChannel

typings/index.d.ts
In the typings the topic on TextChannels and NewsChannels suggests it is always a string. It is in fact optional.
**Status**
=> TextChannel.topic & NewsChannel.topic should be optional

src/index.js, src/structures/Guild.js, src/util/SystemChannelFlags.js, typings/index.d.ts
The current library lacks a field in the `Guild` object for the `system_channel_flags` bitfield, which indicates if welcome messages and boost messages are enabled. This PR adds this property to the `Guild` object.
**Status**
=> Add systemChannelFlags bitfield to Guild

src/stores/GuildStore.js, typings/index.d.ts
This PR widens the types `GuildStore#{resolve,resolveID}` accept to allow channels, members, and roles.
**Status**
=> feat: Widen GuildResolvable to include more structures

src/client/websocket/WebSocketShard.js, src/client/websocket/handlers/READY.js
If your bot was in 0 guilds, the call to `WebSocketShard#checkReady` would've triggered the `Client#ready` event BEFORE the packet was actually parsed, making `Client#user` null. This PR fixes that
**Status**
=> src: Fix race condition

typings/index.d.ts
This PR fixes the `hasParams` parameter type of `Bitfield#serialize` and `Bitfield#missing` and adds the same parameter to `Bitfield#toArray`.
It also overrides the above mentioned methods in `Permissions` and specifies the concrete parameter list.
Fixes #3564.
**Status**
=> typings(Bitfield): add hasParams to toArray, fix serialize's type

src/structures/Webhook.js, src/util/Constants.js, typings/index.d.ts
Resolves #3605
This PR adds `Webhook#type` to distinguish between incoming and channel follower webhooks.
See: https://github.com/discordapp/discord-api-docs/commit/b36723bcbcd708bc17fae935cc2e5ec396fa36bb
It also adds `createdAt` and `createdTimestamp` to `Webhook`  and adds those, as well as `url`, to the list of applied properties to `WebhookClient`.
**Status**
=> feat(Webhook): add type property and created* getters

src/structures/Webhook.js
When editing the avatar of a webhook the channel (if provided) was lost and not patched.
This PR fixes my oversight from #2039.
**Status**
=> fix(Webhook): edit channel when editing avatar

src/structures/MessageMentions.js
This PR will automatically cache mentioned members in messages making `MessageMentions#members` as reliable as `MessageMentions#users`.
**Status**
=> feat(MessageMentions): cache mentioned members

typings/index.d.ts
options.shardList is present in code here: https://github.com/discordjs/discord.js/blob/97eac663b3e1292cc399c56eb701069301f4637d/src/sharding/ShardingManager.js#L33
options.shardList is absent in typings here: https://github.com/discordjs/discord.js/blob/97eac663b3e1292cc399c56eb701069301f4637d/typings/index.d.ts#L1286
I have fixed this problem by adding shardList to typings.
**Status**
=> Add ShardingManager#options.shardList to typings

typings/index.d.ts
Since [`Emoji.url`](https://discord.js.org/#/docs/main/master/class/Emoji?scrollTo=url) is only available for custom emotes, it would make sense to have [`GuildEmoji.url`](https://discord.js.org/#/docs/main/master/class/GuildEmoji?scrollTo=url) not nullable because it is guaranteed to be a custom emote.
**Status**
=> typings(GuildEmoji): make url not-nullable

src/structures/Presence.js
Twitch presence large image asset has link leading to different place than discord endpoints, so using `largeImageURL()` returns `https://cdn.discordapp.com/app-assets/null/twitch:tipaka_.webp` instead of actual link.
The url link i added to code gives image in highest possible resolution, which is capped by the stream itself, leaving room for inconsistent picture resolution. However, the cdn is able to dynamically change resolution for the picture, by adding for example `-1920x1080` just before `.png`, or virtually any other resolution, even larger than stream is in or in different ratio (For example resolution in discord client is 108x60).
On the other side, most methods in library assume that pictures are …
=> Add Twitch preview link for largeImageURL

src/util/DataResolver.js
In DataResolver, stats can't be falsy if no error occurred.
**Status**
=> Fix: stats can't be falsy

src/util/Permissions.js, typings/index.d.ts
This PR backports the `Permissions#any` method from #3450, checking whether any of the requested permission bits are set.
**Status**
=> feat(Permissions): add any method

src/client/actions/ChannelDelete.js
This PR backports #3519, setting `Message#delete` to true once their channel was deleted.
**Status**
=> fix(ChannelDelete): mark messages of a deleted channel as deleted

src/client/rest/RESTMethods.js, src/structures/Webhook.js, typings/index.d.ts
This PR backports #2039 allowing one to edit the channel of a webhook to the 11.5-dev branch.
The old style `name, avatar` parameters are being deprecated in favor of `options, reason` as we do have in our master branch.
**Status**
=> feat(Webhook): add ability to change channel and specify reason to edit

typings/index.d.ts
There is no delay parameter on setImmediate in Node.JS docs:
https://nodejs.org/docs/latest-v12.x/api/timers.html#timers_setimmediate_callback_args
**Status**
=> Remove delay parameter from setImmediate typings

src/client/websocket/WebSocketConnection.js
As uws support was removed from master, it is good to give the users of 11.x a heads up
This mimics what `require('util').deprecate` does to an extent
**Status**
=> src: Add deprecation warning related to uws

src/client/Client.js, src/structures/Presence.js
- Backports #3342 
- Backports https://github.com/discordjs/discord.js/commit/6cd4c27faed8b3f1b9da41a87b7922cd286313b9
https://github.com/discordjs/discord.js/projects/5#card-31518709
https://github.com/discordjs/discord.js/projects/5#card-31518720
**Status**
=> Backport documentation fixes

src/structures/GuildAuditLogs.js
* GuildAuditLogsEntry should provide count as extra in case of  MESSAGE_BULK_DELETE
* The API does provide that information, discord.js does not currently expose it to the user in the GuildAuditLogsEntry
* This PR aims to fix this
* ℹI assume typings need no updating as they are typed as [`object | Role | GuildMember | null;`](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L790)
**Status**
=> fix(GuildAuditLogsEntry): provide count on bulk deletion

src/util/BitField.js
This PR fixes #3567 by replacing the `for..in` with an `Object.keys` making it ignore inherited properties.
**Status**
=> fix(BitField): remove for..in in favor of Object.entries

src/sharding/ShardingManager.js
This PR fixes #3642 by ensuring that the amount of shards specified in `shardList` are specified rather than the amount of shards being spawned (possibly across sharding managers) in general. 
**Status**
=> fix(ShardingManager): assert shardList to be spawned, not totalShards
