- src/structures/Guild.js
- src/structures/User.js
- src/util/Constants.js
- typings/index.d.ts
I added a property named `dynamic` to `ImageURLOptions` which will return a `gif` url if the image is animated, and a url in the type of format you specified otherwise (`webp` if nothing is specified). `webp` images don't display on my phone, so personally I would prefer to have a `png` link instead. 
Example:
```ts
//Returns gif url if the icon is animated, png otherwise. 
message.guild.iconURL({format: "png", dynamic: true}) 
```
Again maybe I'm wrong, but `AvatarOptions` in the typings seems to refer to the same thing as `ImageURLOptions`, so I renamed it since it's the name used in the docs. 
**Status**
> feat: dynamic property for ImageURLOptions

- src/index.js
Removes the `util` export from the library, as discussed from the team.
`Util` refers to a namespace, which name convention is to be PascalCase, it did not make sense for it to be camelCase (and less lowercase).
**Status**
> refactor: Remove `util` alias export

- src/client/websocket/WebSocketManager.js
- src/client/websocket/WebSocketShard.js
- typings/index.d.ts
This PR should prevent #3641 from happening again, as well as prevent double connections on a shard. It cleans up the event listeners on the connection before doing anything.
Well, you can see the code I used down in the details below, but, again, I am not fool proof. Those that encountered issues like #3641 should give this PR a shot.
<details not-open>
<summary>The code I used in a simple message listener to test different close scenarios</summary>
```js
if (message.content === '1000') client.ws.shards.get(0).connection.close(1000);
if (message.content === '1001') client.ws.shards.get(0).connection.close(1001);
if (message.content === '1002') client.ws.shards.get(0).connection.close(1002);
if (message.content === …
```
> src: Cleanup event listeners on WebSocket connections

- typings/index.d.ts
BroadcastAudioPlayer doesn't exist in the typings, so this causes build errors.
**Status**
> Remove BroadcastAudioPlayer

- src/structures/MessageMentions.js
Apparently the sort order of collections returned from the MessageMentions structure rise issues occasionally both on the discord server as well as the repository
<https://github.com/discordjs/discord.js/issues/2669>  and even upstream <https://github.com/IanMitchell/aquarius/issues/344>
This PR attempts to make the sort order of mention collections clearer on the documentation to prevent this sort of misunderstanding in the future.
If the text can be clearer/improved or changed from info to warning please let me know!
**Status**
> docs(MessageMentions): add sort order notice

- src/structures/GuildEmoji.js
- typings/index.d.ts
GuildEmoji's are custom emojis, which means they always have an ID.
**Status**
> Fix: GuildEmoji#id isn't nullable

- .github/CONTRIBUTING.md
- README.md
- docs/general/faq.md
- docs/general/welcome.md
- docs/topics/voice.md
- package.json
- src/client/voice/opus/DiscordJsOpus.js
- src/client/voice/opus/DiscordJsOpusEngine.js
- src/client/voice/opus/NodeOpusEngine.js
- src/client/voice/opus/OpusEngineList.js
- src/client/voice/opus/OpusScriptEngine.js
Adds support for `@discordjs/opus`, a performant alternative to `node-opus` with better audio quality.
**To-do:**
**Status**
> Add internal support for @discordjs/opus to v11

- src/structures/MessageCollector.js
- src/structures/ReactionCollector.js
- typings/index.d.ts
This PR makes it so `ReactionCollector` and `MessageCollector` are automatically stopped if the guild or channel is deleted, in the case of `ReactionCollector`, deleting the message also stops the collector. This would reduce needless collectors which do not have to be kept running.
**Status**
> feat(Collectors): make Collectors auto-stop when relevant structures are deleted

- src/structures/Message.js
- src/structures/MessageMentions.js
- Backports https://github.com/discordjs/discord.js/commit/8152841bab23eb37b2c83c4d2dc136ddc0c01cb4
- Backports #3601 
Also changes `Message#member` to a getter as per current v12 src
https://github.com/discordjs/discord.js/projects/5#card-31519290
https://github.com/discordjs/discord.js/projects/5#card-31518970
**Status**
> Implement caching of members from message data

- src/structures/ClientPresence.js
- src/structures/ClientUser.js
- src/structures/Presence.js
This PR fixes #3695 by accounting for the activities array from `Presence` in multiple places:
- Default `packet.game` to the first activity or null if none was set.
- Update example still using `activity`
- Use single activity / game if activities array is missing (for example when patching the `ClientPresence`)
- `_clone` the `activities` array
- Account for an `activities` array in `equals`
**Status**
> fix(Presence): account for multiple activities everywhere

- src/structures/MessageMentions.js
Since the channels mentions are parsed from the message content, it's fairly safe to assume they are in that order.
**Status**
> docs(MessageMentions): channels are actually in order

- src/structures/Guild.js
- typings/index.d.ts
This PR backports #3364 adding `Guild#setBanner` and `banner` to `Guild#edit`.
**Status**
> I don't have a qualifying guild at hand to test this.
> feat(Guild): add setBanner method and banner to edit

- src/client/voice/VoiceConnection.js
This PR backports #3553 by using `Client#clearTimeout` to clear timeouts.
**Status**
> fix(VoiceConnection): use Client#clearTimeout to clear timeouts

- typings/index.d.ts
This PR marks the `options` parameter in `RichPresenceAssets#largeImageURL` and `RichPresenceAssets#smallImageURL` as optional, (see [here](https://github.com/discordjs/discord.js/blob/master/src/structures/Presence.js#L304))
**Status**
> fix typings for RichPresenceAssets#largeImageURL (and smallImageURL)

- src/structures/NewsChannel.js
- typings/index.d.ts
Effectively backports #3628
While doing this I noticed `NewsChannel` directly extends `TextBasedChannel(GuildChannel)` in v12 and doesn't have `rateLimitPerUser`, so that has also been backported.
https://github.com/discordjs/discord.js/projects/5#card-31518940
**Status**
> TextChannel.topic can be null, backport NewsChannel typings

- src/client/websocket/packets/handlers/Ready.js
- src/structures/MessageCollector.js
- src/structures/ReactionCollector.js
This PR backports #3504 by only using `EventEmitter#setMaxListeners` if the listener count is not `0` (no limit).
This PR also handles this edge case when using the `fetchAllMembers` option where the listener could would be reset to 10 whatever it was before.
**Status**
> fix: only setMaxListeners when max listeners is not 0

- src/structures/MessageAttachment.js
- typings/index.d.ts
This PR backports #3561 by adding `MessageAttachment#spoiler`.
**Status**
> feat(MessageAttachment): add spoiler getter

- src/structures/Webhook.js
- src/util/Constants.js
- typings/index.d.ts
This PR backports the following properties of `Webhook`:
- `avatarURL` as a getter from #3625 
- `type`, `createdAt`, and `createdTimestamp` from #3585 
- `url` from #3178
**Status**
> feat(Webhook): backport missing properties

- src/structures/MessageCollector.js
- src/structures/interfaces/Collector.js
This PR fixes the "translation" of the `MessageCollectorOptions` from `{ max, maxMatches }` (v11) to `{ maxProcessed, max }` (v12), which did not clear `max` after assigning it to maxProcessed leaving it always set if specified.
This PR also ensures that `Collector#postCheck` (and potentially `Collector#stop`) is always getting called, even if nothing was collected.
Resolves #3717 
**Status**
> fix(*Collector): always run postCheck, remove 'translatation' of message collector options

- src/stores/GuildMemberStore.js
This PR changes `GuildMemberStore._fetchMany()` to have a more dynamic timeout.  The timeout used to be static and set at the start of the fetch call, now, the timeout will refresh every time a packet is received, this will fix the issue of the timeout triggering due to a large amount of members being fetched, and it will remove the need for users to change the hardcoded timeout if they must fetch a very large amount of guildMembers.
**Status**
> fix(GuildMemberStore): make timeout refresh after every packet

- src/structures/ClientUser.js
This PR fixes `ClientUser#verified` and `ClientUser#mfaEnabled` properties resetting when something triggers the _patch method, by only setting the properties if they exist in the data
**Status**
> fix(ClientUser) verified and enabled properties resetting

- src/structures/interfaces/TextBasedChannel.js
Calling MessageDeleteBulk#handle in order to return a Collection from TextChannel#bulkDelete was resulting in the event firing twice on the bot which performs the bulkDelete action.
This ensures that the method returns the Collection without handling it twice.
Actually fixes #3658 - I probably didn't need to close the other PR after all.
**Status**
> fix(TextChannel#bulkDelete): Use GenericAction#getMessage to handle return value correctly

- src/structures/Guild.js
`Guild#fetchBan()` should be marked as returning a Promise. Even the [typings](https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L738) state that it should return a Promise.
**Status**
> docs(Guild): fetchBan returns a promise

- README.md
The v12-changes of the guide has been merged into master, so the old link is invalid now.
This fixes this issue.
**Status**
> chore(README): update link to Discord.js guide v12 changes

- src/client/rest/RESTMethods.js
- src/client/voice/util/SecretKey.js
- src/client/websocket/packets/handlers/Ready.js
- src/structures/GuildChannel.js
- src/util/Permissions.js
This PR fixes #3567 by replacing all for..in with Object.keys which do not enumerate inherited properties.
**Status**
(Only the non-userbot parts)
> fix: remove for..in in favor of Object.keys

- src/client/voice/VoiceConnection.js
- src/client/voice/VoiceWebSocket.js
- src/client/voice/receiver/VoiceReceiver.js
- src/client/voice/util/Silence.js
- src/client/voice/util/SingleSilence.js
- typings/index.d.ts
This PR backports #3578 by synthesizing the speaking events from UDP packets.
- `Client#guildMemberSpeaking`, `VoiceConnection#speaking`
This PR backports #3555 by skipping over the undocumented Discord byte.
- Allowing opus packets to be decoded again.
This PR backports f826c9c75e976a8dca3fb4c88c130a1e12147a80 by playing a frame of silence before emitting ready on the voice connection.
- Allowing voice receive to work without sending anything further. (Since d.js does that now)
**Status**
> fix(Voice*): fix speaking event and voice receive

- src/structures/Presence.js
- typings/index.d.ts
This PR backports #3661 and #3703 by adding support for multiple activities.
This PR also backports #3353 by adding `emoji`, `createdAt`, and `createdTimestamp` to `Game`.
I removed the duplicated code in Presence by putting the initializing part into the update method.
The hack using MessageReaction is a bit ugly, but I couldn't come up with anything better.
**Status**
> feat(Presence/Game): multiple activities and custom status

- src/client/rest/RESTMethods.js
- src/index.js
- src/structures/Guild.js
- src/structures/Integration.js
- src/util/Constants.js
- typings/index.d.ts
Project card: https://github.com/discordjs/discord.js/projects/5#card-31828852
This PR backports #2760 by adding the `Integration` class and `Guild#fetchIntegrations` as well as `Guild#createIntegration`.
**Status**
Untested since I do not have any guilds with integrations or any partnered accounts on supported platforms.
> feat(Integration): add guild integrations

- src/client/websocket/WebSocketManager.js
- src/client/websocket/WebSocketShard.js
- typings/index.d.ts
In theory, this change should fix #3706 and should fix #3641! @xKesvaL, @NotSugden and @BannerBomb, please try this PR (since you guys reported the issue)
For anyone else reading this, if you've encountered any of the listed issues, please install this PR and reply here if it works or not! 
`npm i vladfrangu/discOwOd.js#fix-internal-sharding-again` or `yarn add vladfrangu/discOwOd.js#fix-internal-sharding-again`
The only notable thing is that `WebSocketShard#destroy` now takes an object of options and adds a few more options.
**Status**
> src: Fix up WebSocketShard errors

- src/structures/GuildMember.js
Bugfix
If the bot is owner of the guild it can manage the target regardless; no matter its role hierarchy.
This PR inserts the relevant check. The bug propagated to .kickable and .bannable, which are fixed with this change.
**Status**
> fix(GuildMember): manageable - let owner override

- typings/index.d.ts
This PR goes over & fixes two issues regarding the typings:
- The api property was missing from the HTTPOptions interface
- The Constants were being exported as an interface (just a type, didn't actually tell TS that they were usable values)
**Status**
> fix(typings): HTTPOptions#api missing & Constants not being exported correctly

- src/structures/TextChannel.js
This PR removes the old regex check for the nsfw property on a TextChannel, as channels are no longer labeled nsfw when naming it with the 'nsfw-' prefix
**Status**
> fix(TextChannel): remove old nsfw regex check

- src/managers/ChannelManager.js
- src/managers/GuildChannelManager.js
- src/managers/GuildEmojiManager.js
- src/managers/GuildManager.js
- src/managers/GuildMemberManager.js
- src/managers/MessageManager.js
- src/managers/PresenceManager.js
- src/managers/ReactionManager.js
- src/managers/ReactionUserManager.js
- src/managers/RoleManager.js
- src/managers/UserManager.js
- src/managers/VoiceStateManager.js
Apparently you need to use different annotations for properties instead of methods.
This PR takes care of them.
**Status**
> docs(*Manager): fix child classes' cache type annotations

- typings/index.d.ts
This PR fixes the typings showing that GuildMemberManager#fetch with no arguments returns a GuildMemberManager, it infact returns the cache of the manager
**Status**
> GuildMemberManager#fetch returns a collection

- src/util/Constants.js
This pr adds an info tag explaining that `CUSTOM_STATUS` is only for custom statuses received from users and that bots cannot set them, as currently setActivity states the activity's type can be any of ActivityType
**Status**
> feat(Presence): Add info tag to ActivityType regarding custom status

- src/util/Constants.js
This pr backports #3757 by adding an info tag to ActivityType explaining that bots cannot set custom statuses and it is only for custom statuses received from users
**Status**
> feat(Presence): Backport info tag in ActivityType.

- src/client/Client.js
- src/index.js
- src/structures/Presence.js
- src/util/BitField.js
- src/util/Constants.js
- src/util/Permissions.js
- typings/index.d.ts
This PR backports #2765 in a non-breaking manner. (No ActivityFlags or Speaking sadly)
Overview:
- Actually document `Game#flags` (has already been in the typings for quite some time)
- Document `ActivityType` typedef ( ^ ) 
- Add `BitField`
- Inherit from `BitField` in `Permissions`
- Hard-deprecate `Permissions#raw` (emitting an event on access)
- Fix documentation and definition of deprecated `Permissions#member` 
**Status**
> feat(BitField): add BitField base class

- src/structures/Message.js
Throw a TypeError if Message#delete is passed a parameter that is not an object, such as `<Message>.delete(5000)` which was accepted in v11.
**Status**
> feat(Error): Provide TypeError for Message#delete

- src/managers/BaseManager.js
- src/util/Util.js
`BaseManager#valueOf` should be it's cache, for `Util.flatten` and probably other purposes also.
Updates `Util#flatten` to handle the `valueOf instanceof Collection` use-case.
**Status**
> fix(BaseManager): BaseManager#valueOf should return cache

- src/structures/VoiceChannel.js
This PR just changes the permissions check for VoiceChannel#spekable to use Permissions.FLAGS.SPEAK instead of 'SPEAK' directly
**Status**
> use Permissions.FLAGS for VoiceChannel#speakable

- src/structures/Guild.js
This PR fixes a bug where editing a guilds system channel flags wouldn't work as 'systemChannelFlags' was being sent to the API, rather than 'system_channel_flags'
**Status**
> fix(Guild): Use snake case for system_channel_flags

- src/structures/Message.js
- typings/index.d.ts
This prevents an error being thrown internally from `Util#cleanContent` when the `Message#cleanContent` getter is accessed on a Partial Message.
eslint intentionally disabled in order to use `!=` to handle both undefined and null.
**Status**
> fix(Message): Handle undefined/null content in Message#cleanContent

- README.md
- docs/general/welcome.md
- src/util/Constants.js
Minor tweak to the doc string, nothing major. Closes #3783 
Because the ClientOption `ws.compress` is deprecated in favor of the query string parameter; this PR explains what enabled data compression.
This PR also removes the documentation for the `ws.compress` as you shouldn't use it unless you have zlib-sync installed, which automatically enabled compression anyways
**Status**
> docs: Clarify what zlib-sync does

- src/structures/APIMessage.js
- src/structures/Message.js
- typings/index.d.ts
Keeping it simple, adds support for suppressing and unsuppressing message embeds. Closes #3627
```js
// Suppresses embeds
await m.suppressEmbeds();
// Unsuppresses embeds
await m.suppressEmbeds(false);
// Also suppresses embeds
await m.edit({ flags: ['SUPPRESS_EMBEDS'] });
// Also unsuppresses embeds
// Note however that this method may cause other issues if Discord decides to add more flags that can be added (or removed) by the end user. 
// Message#suppressEmbeds handles it differently, adding (or removing) just the bits for SUPPRESS_EMBEDS
await m.edit({ flags: [] });
```
**Status**
> src: Add message embed suppression

- typings/index.d.ts
This PR fixes #3804 by marking Guild#afkChannel* as nullable, also marks Guild#applicationID as nullable as its only present if the guild is owned by a bot
**Status**
> typings(Guild): mark afkChannel* & applicationID as nullable

- src/structures/GuildChannel.js
- typings/index.d.ts
This PR backports the clone options used when cloning guild channels.
**Status**
> feat(GuildChannel): add support for clone options, deprecate old signature

- src/errors/Messages.js
- src/structures/Channel.js
- src/structures/PartialGroupDMChannel.js
- typings/index.d.ts
This PR fixes #3345 by adding a Partial Group DM Channel class for the partial data that is received when fetching an invite to a Group DM
**Status**
> Add PartialGroupDMChannel class

- typings/index.d.ts
This PR changes 'String' to 'string' in the AddGuildMemberOptions interface definition in the typings
**Status**
> typings(AddGuildMemberOptions): change accessToken from String to string

- README.md
- docs/general/faq.md
- docs/general/welcome.md
- package.json
- src/structures/MessageEmbed.js
- typings/index.d.ts
* remove MessageEmbed#spliceField
* add MessageEmbed#spliceFields
* allow multiple fields to be replaced/inserted
* update typings accordingly
* add MessageEmbed#addFields
* remove MessageEmbed#addField
* support multi-field input as Array and rest parameters
* bump node to 11 for Array#flat
The applied approach brings the embed utility methods more in line with the underlying actions done on the raw field array (push, splice) while (hopefully) cleanly handling both rest parameters as well as array passing.
While it does remove some convenience, namely  `.addField("foo", "bar")` we discussed that keeping both #addField and #addFields simultaneously should not be the way to go, adding more noise to the interface …
> feat: bring embed builder field manipulation in line with underlying array functionality

- src/structures/APIMessage.js
- src/structures/MessageEmbed.js
- typings/index.d.ts
This PR changes and documents `MessageEmbed#toJSON` to return what `_apiTransform` used to return and removes `_apiTransform`.
**Status**
> feat(MessageEmbed): change toJSON method to return an api-compatible object

- typings/index.d.ts
This PR fixes the typings for Invite#channel from being only a GuildChannel to a GuildChannel or a PartialGroupDMChannel
**Status**
> typings(Invite): channel can be a PartialGroupDMChannel

- src/structures/MessageAttachment.js
- typings/index.d.ts
This PR marks `MessageAttachment#spoiler` as readonly and moves the property in the typings to the correct place.
**Status**
> docs/typings(MessageAttachment): mark spoiler as readonly, order spoiler in typings

- src/util/SystemChannelFlags.js
- typings/index.d.ts
Currently the typedef for `SystemChannelFlagsResolvable` does not appear on the docs, this somehow is fixed by moving it outside of the class' definition.
Currently `GuildEditData#systemChannelFlags` is typed as `SystemChannelFlags`, but it should actually be `SystemChannelFlagsResolvable`.
This PR takes care of both.
**Status**
> docs/typings(SystemChannelFlags): properly document and use resolvable

- .github/workflows/test.yml
- src/structures/DMChannel.js
This PR removes DMChannel._cacheMessage as it has been removed from TextBasedChannel, and is now just an empty function that serves no purpose
**Status**
> cleanup(DMChannel): remove _cacheMessage

- typings/index.d.ts
This PR marks the color, description, provider, title, and url properties as able to be undefined, since they are able to be undefined
**Status**
- [] This PR **only** includes non-code changes, like changes to documentation, README, etc.
> typings(MessageEmbed): mark properties as able to be undefined

- src/structures/MessageEmbed.js
- typings/index.d.ts
Fix typings for `addFields `and `spliceFields `as well as the underlying `normalizeFields `call by introducing a second typing, **EmbedFieldData** alongside EmbedField to enable passing of **StringResolvable** to the builder methods while keeping the certain string for the accessor through the field structure e.g. `embed.fields[0].name` as well as a certain boolean for the inline accessor - as inline is defaulted to `false` in the normalizeField call
⚠ I have tested this with all possible inputs and accessors I could think of, however please let somebody proficient in typings review this before merging
**Status**
> typings(MessageEmebd): fix typings for addFields

- src/client/voice/receiver/PacketHandler.js
- src/client/voice/util/Secretbox.js
- src/client/websocket/handlers/index.js
- src/structures/ClientPresence.js
This PR just removes an unused error variable, to keep it consistent with other places that do the same thing
**Status**
> refactor: remove unused error in catch statements

- src/client/Client.js
This PR changes Client#sweepMessages to throw an INVALID_TYPE error instead of an CLIENT_INVALID_OPTION error if the `lifetime` parameter is not the correct type
**Status**
> fix: Client#sweepMessages should throw an INVALID_TYPE error

- typings/index.d.ts
This PR changes the typings for WebhookClient#client to be `this` instead of being a `Client` from the WebhookMixin, (as constructing a new WebhhokClient has no Client parameter, and defines it as `this`, see [here](https://github.com/discordjs/discord.js/blob/91a025caaaadb49a4f6610ef1ff2f06d69784987/src/client/WebhookClient.js#L23))
(also moves an Interface from the classes regionto the typedefs region)
**Status**
> typings(WebhookClient): client is not a Client

- package.json
- src/client/voice/util/VolumeInterface.js
- src/client/websocket/handlers/GUILD_CREATE.js
- src/rest/RequestHandler.js
- src/sharding/Shard.js
- src/structures/Guild.js
- src/structures/GuildChannel.js
- src/structures/Message.js
- src/structures/interfaces/TextBasedChannel.js
- src/util/Snowflake.js
- src/util/Structures.js
- src/util/Util.js
> chore(deps): update deps and fix lint

- typings/index.d.ts
Closes #3513 and replaces it because it was stale, and is incorrect anyway.
**Status**
> backport(typings): Return values when MessageOptions#split is provided

- src/client/Client.js
- src/structures/APIMessage.js
- src/structures/Webhook.js
- src/structures/interfaces/TextBasedChannel.js
- src/util/Constants.js
- src/util/Util.js
- test/disableMentions.js
- typings/index.d.ts
In an [earlier Pull Request](https://github.com/discordjs/discord.js/pull/3606), I tried fixing a bug where `disableEveryone` would not work if certain characters were in between the mention. At the time I was not aware that the RTL character (\u202e) can appear anywhere in the mention, which makes the Pull Request useless as it only works with `@\u202e?everyone`. Additionally, the Right to Left override character is not the only character that Discord strips.
A few months ago a [warning](https://discordapp.com/developers/docs/resources/channel#create-message) regarding message sanitization has been added to the API documentation:
> Discord may strip certain characters from message content, like invalid unicode …
> Better user input sanitization: replace disableEveryone with disableMentions

- src/structures/MessageEmbed.js
- typings/index.d.ts
Re-introduces MessageEmbed#addField as convenience wrapper to MessageEmbed#addFields to not have to provide a field data object.
**Status**
> feat(MessageEmbed): re-introduce MessageEmbed#addField

- src/structures/Guild.js
- src/util/Util.js
This PR refactors the Guild#edit function to use `this.client.users.resolveID` instead of `this.client.users.resolve(...).id`, also uses a regex for `Util#cleanCodeBlockContent` as its meant to replace all codeblocks and not just the first
**Status**
> refactor(Guild)/fix(Util): use resolveID and regex for cleanCodeBlockContent

- src/client/websocket/handlers/GUILD_MEMBERS_CHUNK.js
- src/managers/GuildMemberManager.js
- typings/index.d.ts
This PR adds support for [`presences`](https://github.com/discordapp/discord-api-docs/pull/1116/commits/12b414ee6627a1882452dc795c9b263a23ea28b9) field for the "Request Guild Members" gateway command along with making use of the [`user_ids`](https://discordapp.com/developers/docs/topics/gateway#request-guild-members-guild-request-members-structure) field which essentially allows you to fetch a presence on a member which is pretty useful for those who disable the `PRESENCE_UPDATE` event. The default value of an empty string for `options.query` has been removed in this PR since discord takes precedence on that over `user_ids` so it would always end up with all members being fetched and instead an empty string will be set within the `_fetchMany` method based on whether a `query` / `user` was …
> feat(GuildMemberStore): add options.withPresences to fetch()

- src/sharding/Shard.js
- typings/index.d.ts
This PR clears the ready timeout on a Shard, as to not reject the promise after it's already been resolved / rejected
**Status**
> fix(Shard): cleanup after settling spawn promise

- src/structures/GuildChannel.js
- typings/index.d.ts
This PR changes GuildChannel.overwritePermissions to accept an array of Permission Overwrites instead of an object, which previously would accept ChannelData, and the function just acting as an alias for GuildChannel.edit
**Status**
> refactor(GuildChannel): change overwritePermisions to accept an array of overwrites

- src/structures/MessageEmbed.js
If `undefined` or `null` was passed as an array element to MessageEmbed.normalizeFields, it would throw an error because of destructuring null/undefined. This change prevents it.
**Status**
> fix(MessageEmbed): prevent possible destructuring error

- src/client/Client.js
- src/structures/APIMessage.js
- src/structures/Webhook.js
- src/structures/interfaces/TextBasedChannel.js
- src/util/Constants.js
- src/util/Util.js
- test/disableMentions.js
- typings/index.d.ts
In PR  [3830](https://github.com/discordjs/discord.js/pull/3830), disableEveryone was removed and replaced with disableMentions which sanitized all mentions and "broke" all mentions even if unintentional. Although, the client option was a good idea, giving more power to the user. Although it took away what most users may have been using which was them not wanting to mention everyone. This PR keeps the ClientOptions#disableMentions but splits it's functionality into two expected values; "all" or "everyone". "all" being the behavior of  #3830 and "everyone" being an improved version of disableEveryone which _should_ not be subject to special characters.
I have tested this extensively with test/disableMentions.js and …
> feat: reimplement disableEveryone into disableMentions

- typings/index.d.ts
Inspired by #3807, originally going for a different solution but ultimately becoming a copy due to certain issues I ran into
Changes made:
- Each Channel class now has a corresponding type property
- GuildCreateChannelOptions#type now actually takes numbers
**Status**
> typings: Refactor how channel types are done

- typings/index.d.ts
* re-introduce Intents export
* properly type WebsocketOptions#intents
**Status**
> fix(typings): for intents

- src/client/voice/util/PlayInterface.js
This PR fixes #3859 by lazily requiring `VoiceBroadcast` from within `PlayInterface#play`.
**Status**
> fix(playinterface): lazy require VoiceBroadcast to avoid circular

- docs/general/updating.md
- docs/general/welcome.md
Bump's the version in the docs to the new stable version, i.e is 11.6.0
**Status**
> docs: Bump version to 11.6.0

- src/managers/GuildManager.js
This PR marks the `id` property of PartialRoleData as optional, since it is optional
**Status**
> docs(PartialRoleData): id is optional

- src/index.js
- src/managers/MessageManager.js
- src/util/LimitedCollection.js
- typings/index.d.ts
This PR documents `LimitedCollection` as a private implementation detail of `MessageManger` and adds `get[@@species]` to it.
This is in order to fix cloning of the then `Collection`.
So `message.channel.messages.cache.clone()` returns a collection actually including the cached messages unlike currently always returning an empty `LimitedCollection`.
The same applies to all other methods creating a new instance of this class. (filter, map, etc.)
**Status**
> refactor: make LimitedCollection an implementation detail

- src/structures/GuildMember.js
After a users confusion we discussed on the server about how we could be more semantic on what GuildMember#manageable does internally and what it is used for:
- Check for role hierarchy
- Guild ownership overrides (from either side)
- The client user can not manage itself
- basis for moderative actions
This PR is the conclusion of this conversation and proposes its outcome:
> Whether the client user is above this user in the hierarchy, according to role position and guild ownership.
> This is a prerequisite for many moderative actions.
**Status**
> docs: clarify which checks GuildMember#manageable does

- src/errors/Messages.js
- src/util/Constants.js
As per: https://discordapp.com/developers/docs/topics/opcodes-and-status-codes#gateway-gateway-close-event-codes
Discord added 4013 and 4014 which are invalid intent sent & no privileges on the privileged intent. This adds this codes on ws unrecoverable list, hence fixing the re-connection loop experienced for this code.
**Status**
> Fix reconnection loop on 4013 and 4014 close codes

- src/structures/MessageMentions.js
This PR fixes an error being thrown when using `MessageMentions#has` by lazily requiring `GuildMember`.
```js
TypeError: Right-hand side of 'instanceof' is not callable
at MessageMentions.has (<snip>\discord.js\src\structures\MessageMentions.js:177:30)
```
The error was caused by a circular require, see:
Client
-> GuildManager
-> Guild
-> GuildMemberManager
-> **`GuildMember`**
-> TextBasedChannel
-> MessageManager
-> Message
-> MessageMentions
-> **`GuildMember`**
**Status**
> fix(message_mentions): lazy require GuildMember to avoid circular

- docs/general/faq.md
`ffmpeg-binaries` has been deprecated, its deprecation message as well as [topics/voice](https://discord.js.org/#/docs/main/master/topics/voice) and [prism-media](https://npm.im/prism-media) say to use ffmpeg-static, but looks like the FAQ wasn't updated.
**Status**
> docs(faq): ffmpeg-binaries -> ffmpeg-static

- src/structures/GuildChannel.js
Discord implicitly denies any interaction on channels if the actor does not have their respective gatekeeper permission. For VoiceChannel this is actually `CONNECT` (exclusively, checked that) while for Category- and TextChannel `VIEW_CHANNEL`.
This PR aims to fix the behavior of GuildChannel#manageable based on its more specific type to properly reflect the state in terms of manageability.
**Status**
> fix: adapt #manageable to check for CONNECT for VoiceChannel

- src/sharding/Shard.js
- src/sharding/ShardingManager.js
This PR clarifies that `ShardingManager#createShard` does not actually _spawn_ the created shard and that this has to be done manually.
Resolves #3874 
**Status**
> docs(sharding): ShardingManager#createShard doesn't spawn the shard

- src/util/ActivityFlags.js
- src/util/BitField.js
- src/util/Intents.js
- src/util/MessageFlags.js
- src/util/Permissions.js
- src/util/Speaking.js
- src/util/SystemChannelFlags.js
This PR documents the constructors of all classes deriving `BitField`:
- ActivityFlags 
- Intents 
- MessageFlags 
- Permissions
- Speaking 
- SystemChannelFlags 
Before:
After:
(Also fixed a typo: `Bits(s)` -> `Bit(s)`)
**Status**
> docs(BitField): document constructors of deriving classes

- src/structures/Guild.js
This PR fixes two bugs in `Guild#setRolePositions`:
- Roles weren't resolved to ids
- A non existing handler was called resulting in an error:
`TypeError: Cannot read property 'handle' of undefined`
**Status**
> fix(Guild): resolve role id and call existing handler

- src/structures/Message.js
- src/structures/MessageEmbed.js
- typings/index.d.ts
This should fix #3892 by skipping validation on embeds when they are part of a parent message.
The library works fine with this change, but per discussion in #library-discussion, we can't actually reproduce the buggy embed to test this. One should be able to assume this will work though (assuming I've added the flag in the right places) as it is disabling the validation that was throwing the error.
**Status**
> fix(MessageEmbed): Skip validation of field when inside a message

- src/client/voice/VoiceConnection.js
This PR skips redundant decoding, volume transforming (by the factor 1), and encoding of the single silence frame being sent on join to enable audio receive.
**Status**
> perf(VoiceConnection): skip redundant volume transformer on join

- src/rest/APIRequest.js
This PR patches APIRequest to only make use of `FormData` when actually sending files.
This initially "broke" by `APIMessage` (consistently) returning an array for files even if no files are being sent. 
**Status**
> fix(APIRequest): only use form data when actually sending files

- src/structures/ReactionCollector.js
- src/structures/interfaces/Collector.js
This PR fixes that `ReactionCollector`s increment the `total` property and add the relevant user to `users` on _every_ reaction received.
Maybe there is a better solution than adding a new event to `Collector`, but I could not find a way to get the relevant user otherwise.
**Status**
> fix(ReactionCollector): only modify users and total on collect

- typings/index.d.ts
The `Client#typingStop` event was removed in v12, and thus shouldn't be in the typings
**Status**
> typings(Client): remove typingStop event

- src/managers/GuildEmojiManager.js
This PR fixes #3933. 
The method was recursing endlessly if anything falsy (such as omitting the parameter) was passed as attachment.
I moved the `DataResolver#resolveImage` call to the top of the method and made the method throw an error (`REQ_RESOURCE_TYPE`) if resolving failed.
**Status**
> fix(GuildEmojiManager): throw an error if image resolving fails

- src/managers/GuildMemberRoleManager.js
When passing an invalid object to `GuildMemberRolesManager#add` that is not an Array or Collection the error will mislead people into thinking the method *only* accepts Arrays or Collections of Roles, not single Roles as well.
**Status**
> fix(GuildMemberRolesManager): type error should mention Role and Snowflake too

- typings/index.d.ts
This PR fixes the overloads for the `send` method on `PartialTextBasedChannelFields`, before it seemed not possible to have the resulting `Message` be an array of `Message`s, (seemingly because of the order the overloads where defined, changing that order seemed to have fixed the issue), and also makes the first parameter of the method required, as trying to send with no parameters will always result in an error, 
**Status**
> typings(PartialTextBasedChannelFields): fix send overloads

- src/util/Util.js
`Util.cleanContent` currently removes possible everyone mentions then formats mentions, this could result in that being bypassed if a user had the username 'everyone' or a role had the name 'everyone'
**Status**
> fix(Util): cleanContent should remove mentions after formatting mentions

- src/structures/GuildChannel.js
- typings/index.d.ts
This PR adds three new union types to better define the return types of methods that return Channels, rather than having them all return the abstract classes `Channel` or `GuildChannel`.
By doing so, `channel.type` can be used as a type-guard in TS projects.
There are also a couple of other types improvements:
- `StoreChannel#type` was missing, added
- `GuildChannel#setParent` should accept `CategoryChannel`, not abstract `GuildChannel`
I haven't changed the type of function parameters being passed in as class extension is sufficient in these areas - open to discussion if this should also be done.
**Status**
> feat(Types): support type-guarding using Channel#type string literal

- typings/index.d.ts
This PR (partially-ish) reverts one part of my PR #3935, specifically the duplicate `MessageOptions`, as apperently TS throws an error if you try to cast the object as `MessageOptions`, since it isnt assignable to `MessageOptions & { split?: false }`
bit of an oopsies on my part, i didn't try casting the options object when testing the overloads
**Status**
> typings(PartialTextBasedChannelFields): fix send overload

- typings/index.d.ts
Reflecting change from [this commit](https://github.com/discordjs/discord.js/commit/653784b56445b015a1584de1b693e57fc9069050#diff-690d90be1a8e0c08183fa630152b9258), which removes said event in typings.
**Status**
> typings(StreamDispatcher): remove end event

- src/rest/RequestHandler.js
This PR modifies the `RequestHandler#limited` getter in that way, that an existing `globalTimeout` alone limits a handler regardless of their `reset` time.
This is necessary because hitting a global ratelimit with one handler should _always_ limit _all_ handlers until further requests may be made.
This did not apply to handlers before due to invalid parentheses in said getter:
`(global or no_requests_left) and (now < reset)`
Which should have been:
`global or (no_requests_left and now < reset)`
This issue can be reproduced by doing the following steps:
- Manually set a global timeout `client.rest.globalTimeout = somePromise;`
- Optionally test any existing `RequestHandler`; It will have a `limited` of `false` (if …
> fix(RequestHandler): a global timeout implies limited

- typings/index.d.ts
This PR allows us to extract the types of event listeners, there was no way of doing this
```typescript
// Chooses final overload ((...args: any[]) => void)
type Params = Client['on'] extends (event: 'guildMemberAdd', listener: infer P) => any ? P : never
```
**Status**
> feat(typings): allow event listener type param inference

- src/managers/ReactionManager.js
- src/structures/MessageReaction.js
Fixes #3946
After a "partial" MessageReaction (being a custom emoji) was completely removed, the `emoji` getter would [return an instance of GuildEmoji](https://github.com/discordjs/discord.js/blob/master/src/structures/MessageReaction.js#L83-L85) which was being [passed](https://github.com/discordjs/discord.js/blob/master/src/structures/MessageReaction.js#L105) into `ReactionManager#_fetchReaction()`. Since `GuildEmoji#reaction` will always return `undefined` it would end up throwing an error since `_patch()` was trying to be called on that
https://github.com/discordjs/discord.js/blob/7994b5612a8d791c02503648c954ca38072433b9/src/managers/ReactionManager.js#L84
And as for why this doesn't occur within the `messageReactionAdd` event (which was …
> fix(MessageReaction): fetching a removed partial custom emoji 

- src/structures/Channel.js
Partial DMChannels were never getting initiated after 161f90761aa357f17066f4171a5f43f76a552eb7. It expected a [`data.type` to compare](https://github.com/discordjs/discord.js/blob/master/src/structures/Channel.js#L103-L104), but that couldn't be determined within a partial dm's ["payload"](https://github.com/discordjs/discord.js/blob/master/src/client/actions/Action.js#L39-L43). This resulted in the DMChannel not getting initiated which made `PartialTypes.CHANNEL` useless as you would never receive events for uncached dms due to `Action#getChannel()` always returning [`null`](https://github.com/discordjs/discord.js/blob/master/src/managers/ChannelManager.js#L34).
This PR fixes this by not explicitly comparing the `data.type`, but instead checks for the `recipients` field which is only …
> fix(Channel): ensure partial DMChannels get created

- src/util/Permissions.js
- typings/index.d.ts
This PR adds the `VIEW_GUILD_INSIGHTS` permissions as documented in discordapp/discord-api-docs#1421
**Status**
> feat(Permissions): Add VIEW_GUILD_INSIGHTS

- src/structures/VoiceState.js
Added permission needed to edit a member's voice state and adjusted docs to say **"Disconnect"** instead of **"Kicking"** the member.
**Status**
> docs(VoiceState): improve phrasing of setChannel method

- src/structures/APIMessage.js
- src/structures/Webhook.js
- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
Ref: https://github.com/discordapp/discord-api-docs/pull/1396
**Status**
> feat(AllowedMentions): add support for MessageOptions#allowedMentions

- src/structures/Guild.js
Update the default value of maximum presences from 5,000 to 25,000 per discordapp/discord-api-docs#1428
**Status**
> fix(Guild): default max presences value

- src/client/actions/GuildDelete.js
Currently when an unavailable guild "becomes" unavailable it will be treated as a regular `guildDelete` instead.
- Removal from cache
- Emitting `guildDelete`
- etc.
This is because we only allow "available" guilds to become unavailable:
https://github.com/discordjs/discord.js/blob/df324e2c21171aa17bc4e43f4a36f78c2f0eaec1/src/client/actions/GuildDelete.js#L21
While this assumption seems sound, Discord seems to still emit such packets during outages (maybe for guilds that hit a presence limit too).
This PR will always treat guilds that became unavailable as such instead of treating them as "deleted" guilds.
This _might_ also fix unexpected guildCreate events during / after outages as those guilds are still kept …
> fix: always emit guildUnavailable if a guild became unavailable

- typings/index.d.ts
I can't think of a reason why the `Client#message` event would ever emit a PartialMessage.
If anyone else can, lets close this PR.
**Status**
> fix(Typings): client message event should not emit PartialMessage

- src/client/websocket/WebSocketShard.js
Currently when Discord sends a "HEARTBEAT" payload (opcode 1) discord.js simply calls `sendHeartbeat` with the appropriate label, without actually telling it to not check if the last heartbeat ever got the ACK.
What can end up happening in its current state is:
1. d.js sends a regular beat, on the interval
2. Discord acts for another beat using OP 1
3. d.js calls `sendHeartbeat` yet again which will check if the beat sent on step 1 recieved the ACK; if it has, nothing horrible happens, otherwise d.js will respawn the shard under the impression that we're dealing with a zombie connection.
**Status**
> fix(WebsocketShard): pass ignoreACK into sendHeartbeat when Discord asks for one

- src/structures/Webhook.js
- src/structures/interfaces/TextBasedChannel.js
- src/util/Constants.js
This PR corrects the JSDoc of `MessageMentionTypes` by moving the possible string values to the description and having `string` as the type. It also corrects the word `role` to `roles`, as specified in the [Discord API docs](https://discordapp.com/developers/docs/resources/channel#allowed-mentions-object-allowed-mention-types) and [typings](https://github.com/discordjs/discord.js/blob/f2fdb9331895da59546107efe245a2e0137ef2e7/typings/index.d.ts#L2656).
It also adds a new typedef `DisableMentionType` to avoid using literal string types in various instances for `MessageOptions#disableMentions`.
**Status**
> docs(MessageMentionTypes): move possible values to description

- src/structures/GuildChannel.js
- typings/index.d.ts
This PR reverts #3918 / 69d69f25b964b6a2bb13bd086696abec17782ca3.
(Aside from StoreChannel#type and GuildChannel#setParent, as those are unrelated to this)
Taking the following example here:
```js
guild.channels.cache.get(someID).setName('foo').then(channel => {
console.log(`New name: ${channel.name}`);
});
```
Results in an error like this:
```ts
This expression is not callable.
Each member of the union type
(<TResult1 = CategoryChannel, TResult2 = never>(onfulfilled?:
(value: CategoryChannel) =>TResult1 | PromiseLike<TResult1>, onrejected?:
(reason: any) => TResult2 | PromiseLike<...>) => Promise<...>)
| (<TResult1 = NewsChannel, TResult2 = never>(onfulfilled?: (value: NewsChannel) =>
TResult1 | PromiseLike<...>, …
```
>  revert: channel unions (#3918 69d69f2) 

- typings/index.d.ts
This PR removes the references to the removed channel union types.
I seem to somehow have missed those in #3978.
**Status**
> fix(Typings): use Channel instead of *ChannelTypes in ClientEvents

- typings/index.d.ts
userID property exists in docs but not in typings
**Status**
> Added `userID` property to `Presence` class

- src/structures/Message.js
This PR fixes `Message#mentions`'s `roles` property to not update due to using an incorrect field name; `mentions_roles` instead of `mention_roles`.
Fixes #4015.
**Status**
> fix(Message): update MessageMention's roles on message edit

- src/client/rest/APIRequest.js
This PR groups all reaction routes into one handler per channel.
All reactions in a channel share the same bucket when adding or removing them.
For example:
- `/channels/123/messages/:id/reactions/emoji:123/@me`
- `/channels/123/messages/:id/reactions/emoji2:456/@me`
- `/channels/123/messages/:id/reactions/emoji2:456/789`
Would be grouped together under:
- `/channels/123/messaages/:id/reactions`
This is a backport from our current release, where this has been fixed already:
https://github.com/discordjs/discord.js/blob/0e44ecd420ba94b490c2cba1f7a30d1fa5878183/src/rest/APIRouter.js#L20-L28
**Status**
> fix(APIRequest): group all reactions into the same route per channel

- src/client/websocket/WebSocketShard.js
If anyone wants to know if Discord asks us to reconnect, here you go. Simple debug message that just says "hey, Discord wants us to reconnect, so we will, and we'll attempt to resume too!"
**Status**
> chore(WebSocketShard): Log Discord requested reconnects

- typings/index.d.ts
Fixes #4057. It also sorts the properties & methods in alphabetical order. To be specific:
- Marked `StreamDispatcher#pausedSince` as nullable
- `StreamDispatcher#pausedTime` is a number, not a boolean (also not nullable)
**Status**
> typings(StreamDispatcher): correct property types

- src/util/Constants.js
- typings/index.d.ts
Discord also allows to open avatars/icons in ?size=4096 and discord.js was supporting upto 2048 so im opening this pr, also format .jpeg is a thing and it was not listed in d.js
**Status**
> Add 4096 image size and jpeg format that discord supports

- src/structures/Message.js
- typings/index.d.ts
This PR documents the `allowedMentions` part of `MessageEditOptions` as bots are now able to edit those too.
Relevant upstream PR: https://github.com/discord/discord-api-docs/pull/1483
**Status**
> feat(Message): add allowedMentions to MessageEditOptions

- typings/index.d.ts
This PR fixes the return type of `ClientApplication#fetchAssets` in your type declarations.
It incorrectly stated that it would return a `Promise<ClientApplicationAsset>` instead of `Promise<ClientApplicationAsset[]>`.
Fixes #4026.
**Status**
> fix(ClientApplication): type fetchAssets as resolving with an array

- typings/index.d.ts
* GuildPreview#features is `GuildFeatures[]` instead of `GuildFeatures`
* Integration#type is `string` instead of `number`
This is what the types should be and what they are in the documentation.
**Status**
> fix(Typings): GuildPreview#features and Integration#type

- src/structures/Guild.js
This PR sorts text, news, and store channels together, and fixes the `position`s of those channels. Fixes #3963.
**Status**
> fix(Guild): sort text, news, and store channels together

- typings/index.d.ts
I overrode the `ClientEvents` typings in my project so I could emit my own event on `Client` and noticed there's only the basic `@types/node` typings for `Client#emit`, and this PR fixes that.
**Status**
> chore(Typings): stricter def for Client#emit

- src/sharding/ShardClientUtil.js
This PR links `Shard#message` from `ShardClientUtil#send`'s documentation, since it's not immediately obvious where the message gets send to.
**Status**
> docs(ShardClientUtil): link Shard#message from send method

- src/managers/MessageManager.js
This PR documents the return type of `MessageManager#delete`.
The [documentation](https://discord.js.org/#/docs/main/stable/class/MessageManager?scrollTo=delete) currently states the return type of `void`, however it should be `Promise`.
**Status**
> docs(MessageManager): document return type of delete

- src/structures/MessageEmbed.js
This PR documents the constructor of `MessageEmbed`, which somehow was not yet documented.
Resolves #4000?
**Status**
> docs(MessageEmbed): document the constructor

- src/managers/GuildMemberManager.js
- typings/index.d.ts
This PR adds a `time` parameter to `FetchMembersOptions` in order to allow customisation of the timeout for receipt of members.
Many use cases do not require 120 seconds of timeout, also this can be a good workaround until https://github.com/discordjs/discord.js/issues/4018 gets fixed in Discord API itself.
https://i.imgur.com/DTw2QLh.png
An example of use case that would benefit from this feat can be found in the issue itself (or directly from the image that should tell enough of what's the issue behind this).
**Status**
> feat(GuildMemberManager): customisable timeout for _fetchMany

- src/managers/RoleManager.js
- typings/index.d.ts
This PR fixes the jsdoc of RoleManager ; the everyone role can't be null
**Status**
> docs(RoleManager): everyone role can't be null

- src/structures/APIMessage.js
- src/util/Constants.js
- typings/index.d.ts
This PR adds the ability to set `ClientOptions#allowedMentions` to be used as a default whenever `MessageOptions#allowedMentions` is not provided.
If not provided as an option, the default behaviour by Discord is to parse all mentions.
**Status**
> feat(ClientOptions): allow setting default allowedMentions

- package.json
- src/rest/APIRequest.js
- src/util/DataResolver.js
- typings/index.d.ts
I've noticed high memory usage when tried to send a few ~100mb files as message attachments so I went to the source code and discovered that, indeed, everything is being converted to Buffers for some reason. Since discord.js uses node-fetch under the hood, which accepts Streams, the fix seems to be pretty simple.
**Status**
> feat(DataResolver): prefer streams over buffers

- src/structures/Message.js
People in our support channels are regularly confused about how to use Message#delete with a timeout after updating from v11, where it used to be `<Message>.delete(5000)`.
The documentation does not reflect this change through an example. This PR adds a timeout to the Message#delete example.
**Status**
> docs(Message): add timeout to Message#delete example

- typings/index.d.ts
This PR adds the optional `unavailableGuilds` parameter to the argument list of the `shardReady` event in the typings.
For reference: <https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-shardReady>
**Status**
> fix(Typings): add optional Set<Snowflake> to shardReady event

- src/structures/Guild.js
Fixes the guild name acronym generation to be the same as the one the Discord app uses (taken from [DJScias/Discord-Datamining](https://raw.githubusercontent.com/DJScias/Discord-Datamining/master/2020/2020-04-18/40abc31adc473eefed44.js), search the page for `t.getAcronym = f` to find the definition).
**Status**
> fix(Guild): name acronym

- webpack.config.js
Theres no reason to not have this polyfill as I can spot right now.
Our bundle-size with this increases by 1KB.
**Status**
> fix(Webpack): add Buffer polyfill in browser

- src/client/voice/VoiceConnection.js
- typings/index.d.ts
`VoiceConnection#setSpeaking` has been declared as private, when its only usage was by an external method calling it, therefore ruining its declaration.
This PR fixes #4074 
**Status**
> Set speaking public

- src/structures/MessageEmbed.js
This PR explicitly adds the `proxyIconURL` property as `unfined` when calling `.setFooter()`.
This change may seem futile but it allows an exhaustive comparison between two MessageEmbed with the same properties.
```ts
import assert from 'assert';
let a = new discord.MessageEmbed({ footer: { text: "test" } })
let b = new discord.MessageEmbed().setFooter("test")
assert.deepStrictEqual(a, b) // => throw because of the missing `proxyIconURL`
```
https://nodejs.org/api/assert.html#assert_assert_deepstrictequal_actual_expected_message
This kind of behaviour is very widely used in unit tests to check the proper functioning of the system.
**Status**
- [] This PR **only** includes …
> fix(MessageEmbed): explicitly mark `proxyIconURL` as undefined

- src/structures/Guild.js
- typings/index.d.ts
This PR adds support for the new **`GET`** `guilds/:id` query parameter `with_counts` per https://github.com/discord/discord-api-docs/pull/1528. This includes two new properties: `approximate_member_count` and `approximate_presence_count` both assigned to `Guild#approximateMemberCount` and `Guild#approximatePresenceCount` respectively. 
I can add support for the `with_counts` query param for `GuildManager#fetch` once #4086 is merged.
This PR will be a draft until the feature is deployed. ~~I am still [yet to test this](https://discordapp.com/channels/613425648685547541/697489244649816084/701861149112664064).~~
**Status**
> feat(Guild#fetch): withCount param

- src/client/voice/networking/VoiceWebSocket.js
- src/client/voice/receiver/PacketHandler.js
Addresses an issue where if a voice event was fired on the WebSocket connection, the value written to the ssrcMap was incorrect (just an ID, not an object). The WebSocket connection fires voice events when changing from voice to video and vice-versa.
Also addresses a knock on issue where the speaking state was assumed to already be at least a`1` (it's a bitmask), but because the WebSocket event is fired on the reconnect, it starts as `0`, and needs to be updated on the first Voice packet.
This also addresses an issue where the first `speaking` event for a users session would have the wrong bitmask.
**Status**
> fix(Voice): correctly set speaking data in the voice ssrcMap

- src/structures/VoiceState.js
The docs on other methods do not reference permissions that are needed to perform them.  This removes the line from `voiceState#setChannel` to be consistent with the rest of the docs.
**Status**
> Remove permissions note from setChannel

- src/client/websocket/handlers/GUILD_MEMBERS_CHUNK.js
- src/errors/Messages.js
- src/managers/GuildMemberManager.js
- typings/index.d.ts
This PR exposes `chunk_index`, `chunk_count` and `nonce` (if provided) properties in the `guildMembersChunk` event.
As a result, `GuildMemberManager#_fetchMany` was slightly redesigned to use these values :
- `nonce` is set to the guild ID unless a custom one was provided (this will allow several fetches at the same time)
- `count` is compared to a counter incremented on each chunk received (see below why I have chosen to not use `index`)
I have made the choice to use a counter that I increment on each chunk because I haven't seen anywhere the chunks are sent in the right order all the time. However, if the chunks are sent in order I'll make it use `index`.
I have also kept timeout because I believe, even if I …
> feat(GuildMemberManager): nonce and chunk_count for _fetchMany

- src/sharding/ShardingManager.js
This changes the JSDoc for `ShardingManagerMode` to remove mention of Worker threads being experimental. Node 12+ is required for the master branch, and Worker threads are stable since Node 12, so it makes sense.
**Status**
> docs(ShardingManager): remove experimental status of Worker threads

- src/sharding/ShardingManager.js
Fix typo introduced in PR #4157 in the link to Node docs
Mea culpa, I botched the markdown on my previous PR.
**Status**
> docs(ShardingManager): fix typo in JSDoc

- src/client/BaseClient.js
- src/managers/GuildManager.js
- src/managers/GuildMemberManager.js
- src/structures/MessageCollector.js
- src/structures/ReactionCollector.js
- typings/index.d.ts
This PR fixes #3943 by temporarily incrementing the max listener count when attaching a temporary listener.
I also moved the logic to in- and decrement into `BaseClient#incrementMaxListeners` and respectively `BaseClient#decrementMaxListeners`.
**Status**
> fix: in/de-crement max listener for client events

- src/structures/Message.js
This PR reverts #4165 as it is a somewhat duplicate of #4090.
This went unnoticed because #4165 (or rather its branch) did not include the change of #4090, so it looked like the above example was not using an options object.
> revert "chore(docs): example for timeout in message.delete()"

- src/structures/APIMessage.js
Fixes #4170 this PR changes `APIMessage#makeContent` to return undefined if the content passed is undefined, like its supposed to, as previously having the `disableMentions` client option enabled would pass an empty string, removing content on methods such as `Message#suppressEmbeds`, it also only passes `allowedMentions` if there is content, this fixes a bug to do with using `Message#suppressEmbeds` on a message authored by another user while the `allowedMentions` client option is enabled (API would throw an error, because flags and allowed_mentions were passed and only flags should have been)
**Status**
> fix(APIMessage): only pass allowedMentions if content is defined

- src/managers/GuildChannelManager.js
This PR corrects the docs for `GuildChannelManager` for resolve to return a `GuildChannel
**Status**
fixes #4332 
> docs(GuildManager): resolve returns a GuildChannel

- src/structures/Guild.js
Guild#premiumSubscriptionCount returns the amount of boosts, not the amount of boosters which applied them (this metric is not available)
since discord now allows multiple boosts per person the current description is no longer applicable
**Status**
> docs(Guild): description of Guild#premiumSubscriptionCount

- src/util/DataResolver.js
Update resolveInviteCode method to support "discord.com/invite" links.
Will support the new discord.com domain for resolving link invites.
Only changed regex, nothing else. Theres probably a butt load of other things to do, but I figured this would help.
**Status**
> fix(DataResolver): resolveInviteCode to support new domain

- src/rest/APIRequest.js
This PR adds support for a request's `query` option to be either an object or URLSearchParams.
This is necessary for https://github.com/discordjs/discord.js/pull/4142 to function. [thanks vlad](https://github.com/discordjs/discord.js/pull/4142#discussion_r418109277)
**Status**
> feat(REST): allow options.query as URLSearchParams

- src/structures/Guild.js
The docs for vanityURLUses mention the need to use `Guild#fetchVanityCode` (and not `Guild#fetchVanityData`), which is wrong.
Also, this PR makes it that even when only calling fetchVanityCode, it will internally call fetchVanityData, so the users would be set anyway.
**Status**
**This PR includes internal code changes as well as documentation changes.**
> fix(Guild): change wrong description & call fetchVanityData internally

- src/structures/VoiceState.js
- typings/index.d.ts
Add the documented [self_video](https://discord.com/developers/docs/resources/voice#voice-state-object-voice-state-structure) property to the voiceState.
Per #4340 and [#1729](https://github.com/discord/discord-api-docs/pull/1729)
**Status**
> feat(voiceState): add self_video property

- src/client/websocket/handlers/TYPING_START.js
A user has recently reported the following error:
<details><summary>Stacktrace</summary>
```
node_modules\discord.js\src\client\websocket\handlers\TYPING_START.js:16    if (channel._typing.has(user.id)) {
^
TypeError: Cannot read property 'has' of undefined
at Object.module.exports [as TYPING_START] (C:\Users\--snip--\Desktop\bot\node_modules\discord.js\src\client\websocket\handlers\TYPING_START.js:16:25)
at WebSocketManager.handlePacket (C:\Users\--snip--\Desktop\bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
at WebSocketShard.onPacket (C:\Users\--snip--\Desktop\bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
at WebSocketShard.onMessage …
```
> fix: typing start event emitting on non text based channels

- typings/index.d.ts
- ⚠closes #4608
As #4608 pointed out User#dmChannel is wrongly typed. The DM channel can be uncached, in which case the getter returns `null`.
https://github.com/discordjs/discord.js/blob/d827544fbd12e827fb4b6ff99d8894ecd79ede02/src/structures/User.js#L213-L220
https://github.com/discordjs/discord.js/blob/d827544fbd12e827fb4b6ff99d8894ecd79ede02/typings/index.d.ts#L1474
**Status**
> fix(User): type dmChannel as nullable

- src/structures/Message.js
- typings/index.d.ts
- ⚠ closes #4359 
Message#pin and Message#unpin support reasons to be set as detailed in #4359 
<details>
<summary>
ℹ Note: The UI displays the reason for pin, not for unpin!</summary>
However it is still available in the audit log data returned from the API
</details>
<details>
<summary>Test code</summary>
```js
message.pin({ reason: 'pintest' })
.then(msg => {
msg.unpin({ reason: 'unpintest' });
})
.catch(console.error);
```
</details>
**Status**
> feat(Message): support pin and unpin with reason

- typings/index.d.ts
Currently, you are only allowed to emit and listen to discord.js events. However, this is not correct, you should be able to create and emit custom events (since the methods come from the Node.js EventEmitter).
This can be easily done by adding a method overload in the typings. I also included the `off()` and `removeAllListeners()` methods, because I thought it was weird that they were left out. 
**Status**
> fix(typings): allow custom events

- src/index.js
add ReactionManager to the manager exports in src/index.js
closes #4363
Export ReactionManager with discord.js. It is not marked private and is [documented](https://discord.js.org/#/docs/main/stable/class/ReactionManager).
**Status**
> feat(Module): add ReactionManager to exports

- src/util/Util.js
People figured out a new exploit to mention roles using bots, although users can be mentioned using that too.
(https://github.com/abalabahaha/eris/pull/990)
this issue also realized this one too.
It can username canbe mention exploit.
ex) if User set nickname/displayname `!236696896658341888` or `&566992616319877121` and insert a pair of `<>`
it can be role/user get pinged.
**Status**
> fix(Util): Fix cleanContent mention exploit

- typings/index.d.ts
APIErrror has been changed by APIError
**Status**
> fix(typings): correct spelling of APIError

- src/managers/ReactionManager.js
- typings/index.d.ts
[ReactionManager#cache](https://discord.js.org/#/docs/main/stable/class/ReactionManager?scrollTo=cache) returns a collection of [MessageReaction](https://discord.js.org/#/docs/main/stable/class/MessageReaction) mapped by either a `Snowflake` (for **custom emojis**) or a `string`(for **emojis**); but current type of [ReactionManager#cache](https://discord.js.org/#/docs/main/stable/class/ReactionManager?scrollTo=cache) is `Collection<Snowflake, MessageReaction>`.
Even if `Snowflake` is just a named typedef for `string`, it still seems a bit misleading and semantically incorrect.
**Status**
> docs(ReactionManager): clarify cache Collection keys type

- docs/examples/attachments.md
This PR changes **"The results are the same as the URL examples:"** image in **"Sending a local file or buffer"** Portion of **attachments.md**, looks like the result is different than that of Example Code.
**It should be :**
**Status**
> docs(examples): fix example img

- src/structures/Message.js
- typings/index.d.ts
[MessageEditOptions#embed](https://discord.js.org/#/docs/main/master/typedef/MessageEditOptions) allows a MessageEmbed structure to be passed. This is currently not reflected in documentation or typings which only allow the raw embed data (type: `MessageEmbedOptions`).
This PR adds the typings and documentation to rectify this.
```ts
import { MessageEmbed, MessageEditOptions } from 'discord.js';
const data: MessageEditOptions = {};
data.embed = new MessageEmbed();
```
```
(property) MessageEditOptions.embed?: MessageEmbedOptions | null | undefined
Type 'MessageEmbed' is not assignable to type 'MessageEmbedOptions'.
Types of property 'timestamp' are incompatible.
Type 'number | null' is not assignable to type …
```
> fix(Message): include MessageEmbed type

- typings/index.d.ts
This pull request provides support for changing the default ws#properties#$browser property for TypeScript. It can be done through vanilla JS without a problem, for example:
```js
const { Client } = require("discord.js");
const client = new Client({
ws: {
properties: {
$browser: "Discord iOS" // <-- a popular value to change $browser to
}
}
});
client.once("ready", () => console.log("Ready")); // The bot will now show online on a mobile device
client.login("<TOKEN>");
```
whereas using TypeScript you would get compilation errors such as:
```
Type '{ properties: { $browser: string; }; }' is not assignable to type 'WebSocketOptions'.
Object literal may only specify known properties, and 'properties' does not exist in type 'WebSocketOptions'.ts(2322)
index.d.ts(2208, 5): The expected type …
```
> feat(typings): TypeScript support for changing $browser

- typings/index.d.ts
So I found a typings issues. With the following code: 
```ts
channel.delete().catch()
```
where `channel` is `TextChannel | DMChannel | NewsChannel` and the statement fails with
```
TS2349: This expression is not callable.
Each member of the union type '(<TResult = never>(onrejected?: (reason: any) => TResult | PromiseLike<TResult>) => Promise<DMChannel | TResult>) | (<TResult = never>(onrejected?: (reason: any) => TResult | PromiseLike<...>) => Promise<...>) | (<TResult = never>(onrejected?: (reason: any) => TResult | PromiseLike<...>) => Promise<...>)' has signatures, but none of those signatures are compatible with each other.
```
Seems to be an issue introduced with v12 as the Channel typings changed from …
> fix(Typings): Channel#delete returns bad type

- src/structures/GuildMember.js
* closes #4640
According to #4640, the `.nickname` property of a guildmember returns `undefined` instead of `null` if not present.
This might be due to the way the library currently handles and assigns the initial `data` payload received from Discord itself.
**Status**
> fix: set #nickname to null as the default value

- typings/index.d.ts
- ⚠ closes #4371
This PR creates needed overlap "invisible" for the PresenceStatus type by changing the base typing from ClientPresenceStatus  to PresenceStatusData, serving as additive hierarchy. The naming of these properties is rather confusing, hence i'll explain the change in some more detail:
```ts
/**
* baseline, returned as value to the respective platform keys of <GuildMember>.presence.clientStatus
* thus can only be online, idle, dnd
*/
type ClientPresenceStatus = 'online' | 'idle' | 'dnd';
/**
* Acts as option for setting the client users presence via <Client>.user.setPresence (or derivatives)
* This can also include "invisible", this can not include "offline"
*/
type PresenceStatusData = …
```
> fix(PresenceStatus): include invisible in typings

- src/structures/StoreChannel.js
- src/structures/TextChannel.js
- ⚠ closes #4296 
As #4296 brought up, discord.js has `text` type channels in cache where the `.nsfw` property returns `undefined`.
**Problem breakdown:**
- After some investigation the initial guess of this being caused by discord.js handling channel updates can be dismissed
- This is indeed caused by discord not sending `nsfw` in its channel data on initial guild payloads
- There are no updates sent after ready to provide these missing properties
This PR attempts to fix this inconsistency by considering the channel to not be nsfw if the `.nsfw` key is not present in the initial channel data.
<details>
<summary><b>Changes breakdown:</b></summary>
**TextChannel**
- assign `.nsfw` in the constructor with `this.nsfw …
> fix: consider #nsfw false if not present in data

- src/util/Util.js
- ⚠ closes #4299 
As mentioned in #4299 Util.flatten currently fails for empty arrays (through Collection#toJSON - library extension, not part of the separate Collection package). 
**Problem breakdown:**
The code in question is supposed to determine the object keys to use from the passed object by returning an array of key/boolean mapping objects akin to the second parameter of Util.flatten ` @param {...Object<string, boolean|string>} [props]`.
Through spread operators the first such key object is used as template for Object#assign, to which the rest keys of the original object are assigned. This will currently fail on an empty Array due to trying to assign the spread `...props` to `undefined`. (there is no key …
> fix(Util): support empty array for flatten

- src/structures/Message.js
https://i.imgur.com/6RlLWOW.png
First PR yeet
**Status**
> fix(Message): Message#createdTimestamp uses deconstructed message id to get timestamp

- src/structures/APIMessage.js
- ⚠closes #4300
An oversight in two positions leads to `allowedMentions` being ignored when `splitOptions` are present.
<details>
<summary>Breakdown of changes</summary>
- https://github.com/discordjs/discord.js/pull/4588/files#diff-3916ea503ae839d34e6dd447ef035977R194 : required to not pass undefined if `content` is an array (which is the case when split options are passed)
- https://github.com/discordjs/discord.js/pull/4588/files#diff-3916ea503ae839d34e6dd447ef035977R249-R250 : allowed_mentions/allowedMentions need to be passed to split messages that are not the last message as well. `allowed_mentions` is used in `data` since it represents the data sent to the API. `allowedMentions` is used in `opt` since it …
> fix(ApiMessage): respect allowedMentions with split

- src/client/actions/VoiceStateUpdate.js
- src/managers/VoiceStateManager.js
This PR properly imports the VoiceState class by using `Structures.get` rather than directly requiring it, as it is an extendable structure
**Status**
> fix: correctly import VoiceState

- typings/index.d.ts
BaseManager#valueOf returns its cache collection, but the return is currently typed as `:Object`. This PR documents types the return value based on key and holdings.
**Further considerations:**
Whether or not valueOf should even return a Collection in the first place is another topic, which should be discussed for the next semver major. This is (according to @Monbrey) the case due to Util#toJSON expecting to find Collections there to extract the appropriate data for use cases like broadcast evaluations.
**Status**
> fix(BaseManager): properly type valueOf

- src/util/DataResolver.js
I could not get browser based discord.js file attachments working with dynamic content (string).
I tried the different methods BufferResolvable/Stream.
Using a TextEncoder, I can convert the string into an ArrayBuffer. After some tinkering, the main issue is that FormData.append() expects a Blob instead of an ArrayBuffer. The Blob was rejected in resolveFile. I patched one line to pass through Blobs and now it works for my use case.
At least with Google Chrome Version 83.0.4103.97 (Official Build) (32-bit) and Firefox.
One problem is that stream in the documentation refers to discord.js audio streams instead of std stream, but I am not sure about that. Anyway, it rejected my File stream as File Attachment.
**Status**
> feat: add Blob support for browser

- src/sharding/Shard.js
with this change it is possible to process' stdin/stdout/stderr when using sharding.
currently we can't listen to those streams, because node regresses those.
see [node documentation](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options)
**Status**
- [✅] Code changes have been tested against the Discord API, or there are no code changes
- [✅] I know how to update typings and have done so, or typings don't need updating
- [❎] This PR changes the library's interface (methods or parameters added)
- [❎] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [❎] This PR **only** includes non-code changes, like changes to documentation, README, etc.
> fix missing child_process silent option of Shard to allow listening to output

- src/structures/interfaces/Collector.js
- typings/index.d.ts
Previously, collectors (such as awaitMessages or awaitReactions) did not support an async filter. Instead, they would return true always leading to unexpected behaviour.
```js
let message = await channel.send("React with :thumbsup: to confirm");
message.react("👍");
// Async is not required here, but it may be for more complex filters
await message.awaitReactions(async (reaction, user) => !user.bot && reaction.emoji.name == "👍", {max: 1, time: 30000});
// Previously, this would continue instantly since the bot reacted. (Despite !user.bot filter)
console.log("Done");
```
This PR will not break compatibility
**Status**
> fix(Collector): support async

- src/client/Client.js
This PR fixes the documentation for `Client#login` by marking the `token` parameter as optional and adding a small description.
**Status**
> docs(Client): fix docs for login method

- src/structures/GuildChannel.js
- ⚠closes #4144
I decided to make this (original) PR separate from #4598 since it allows a quick fix of the issue at hand in case the required Discord API documentation takes more time than anticipated. The client handles this situation differently, however. After documentation on the API documentation this will be applied as a feature in #4598.
Should #4598 me merged before this issue will auto-close as it is obsolete.
as #4144 has brought to light the `lockPermissions` option in GuildChannel#setParent (and as direct cause GuildChannel#edit) does currently not lock permissions.
I tracked this down due to the API no longer accepting a `lock_permissions` field when patching a channel as per …
> fix(GuildChannel): make lockPermissions use parent overwrites

- src/structures/BaseGuildEmoji.js
- src/structures/GuildEmoji.js
- typings/index.d.ts
`GuildEmoji#fetchAuthor` fetches the emoji's author by fetching the entire emoji via `GET /guilds/:id/emojis/:id` and returns `.user`, but only adds it to `Client#users#cache`. This PR also assigns it to `GuildEmoji#author` to reduce API calls.
**Status**
> feat(GuildEmoji): cache the author

- src/structures/Integration.js
- typings/index.d.ts
After the recent release of application integrations (discord/discord-api-docs#1886), `user` may not be present, which causes issues as discord.js expects it to be. This PR should fix #4690, but it does not add the new features.
**Status**
> fix(Integration): user might not be present

- typings/index.d.ts
Resolve #4601 
Change `BitFieldResolvable` subtype `RecursiveArray` into `RecursiveReadonlyArray`.
A resolvable's purpose is to be resolved, so its data don't need to be changed, that's why a read only version of array is more suitable.
**Status**
> feat(types): BitFieldResolvable use ReadonlyArray

- src/managers/GuildMemberManager.js
- src/structures/GuildMember.js
Documents that the `days` option for banning must be 0-7.
hopefully we can rename this misleading option name eventually
**Status**
> docs(Ban): days must be 0-7

- src/structures/Guild.js
- typings/index.d.ts
Adds support for reading and setting a guild's Discovery splash
Looks like it got into GuildPreview but was never added to Guild
The CDN stuff was added in #3965
**Status**
> feat(Guild): discovery splash

- package.json
- src/managers/ChannelManager.js
- src/managers/GuildMemberManager.js
- src/managers/MessageManager.js
- src/managers/RoleManager.js
- src/managers/UserManager.js
- src/structures/Channel.js
- src/structures/DMChannel.js
- src/structures/GuildMember.js
- src/structures/Message.js
- src/structures/User.js
- typings/index.d.ts
This PR adds the parameter `forceFetch` on various functions that would check a manager's cache before falling back to requesting the API. If true, the cache check will be bypassed and hit the API. If undefined, the parameter will default to `false`.
Effected functions include:
- Managers
- `ChannelManager#fetch`
- `GuildMemberManager#fetch` (added to the options object)
- `MessageManager#fetch`
- `RoleManager#fetch`
- `UserManager#fetch`
- Structures
- `Channel#fetch`
- `DMChannel#fetch` (relies on `User#createDM`)
- `GuildMember#fetch`
- `Message#fetch`
- ~~`MessageReaction#fetch`~~ may not be necessary here
- `User#fetchFlags`
- `User#fetch`
- `User#createDM` (underlying support for `DMChannel#fetch`)
**Status** …
> feat: bypass cache check with forceFetch param

- src/client/actions/MessageReactionAdd.js
This fixes #4284.
The method [Message#react()](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=react) calls MessageReactionAdd#handle() (`this.client.actions.MessageReactionAdd.handle()`, [line 493 at Message.js](https://github.com/discordjs/discord.js/blob/master/src/structures/Message.js#L493)). So, if the user is listening for the `messageReactionAdd` event and the bot client react using [Message#react()](https://discord.js.org/#/docs/main/stable/class/Message?scrollTo=react), MessageReactionAdd#handle() method is called twice (second time when data is received from the API and handled at [WebSocketManager#handlePacket()](https://github.com/discordjs/discord.js/blob/master/src/client/websocket/We …
> fix(MessageReactionAdd): prevent double messageReactionAdd triggering

- src/structures/APIMessage.js
This PR changes `APIMessage#resolveData` to add the specified `reply` user to allowedMentions
**Status**
> fix(APIMessage): add reply user to allowedMentions

- typings/index.d.ts
the `setExplicitContentFilter()` does accept number for the level and it doesn't work using typescript.
**Status**
> feat(typings): add number type for setExplicitContentFilter method

- src/structures/ReactionCollector.js
The ReactionCollector#remove event is only emitted when the `dispose` option is true. The docs don't properly document this.
**Status**
> docs(ReactionCollector): update remove and dispose events

- typings/index.d.ts
Use readonly arrays in parameters. For example, these now work:
```ts
declare const guild: Guild
declare const positions: readonly ChannelPosition[]
guild.setChannelPositions(positions)
declare const member: GuildMember
declare const permissions: readonly PermissionString[]
member.permissions.has(permissions)
```
`T[]` is assignable to `readonly T[]`, so the following will continue to work:
```ts
declare const positions2: ChannelPosition[]
guild.setChannelPositions(positions2)
declare const permissions2: PermissionString[]
member.permissions.has(permissions2)
```
**Status**
> feat(typings): use readonly arrays in parameters

- src/managers/GuildMemberManager.js
- typings/index.d.ts
This PR adds support for https://github.com/discord/discord-api-docs/pull/1563.
**Status**
> feat(GuildMemberManager#prune): roles query param

- src/client/actions/UserUpdate.js
- src/client/websocket/handlers/GUILD_MEMBER_UPDATE.js
The `USER_UPDATE` gateway event only triggers when the bot's user itself is updated, but discord.js's userUpdate event triggers when any user known user is updated.
Currently, the userUpdate event triggers on the `USER_UPDATE` gateway event as well as the `PRESENCE_UPDATE` event. 
However, due to the addition of Intents, Discord now also sends user updates in the `GUILD_MEMBER_UPDATE` event:
> `GUILD_MEMBER_UDPATE` will now fire when a user changes so that bots that want to opt out of presence can still receive updated user attributes.
(from https://github.com/discord/discord-api-docs/pull/1307#issuecomment-581561519)
This PR updates discord.js to also trigger the userUpdate event on the `GUILD_MEMBER_UPDATE` …
> feat: trigger userUpdate on GUILD_MEMBER_UPDATE

- package-lock.json
The version in `package.json` has been changed to `12.3.0`, however `package-lock.json` does still contain the old version.
**Status**
> chore: bump version in package-lock.json

- src/sharding/Shard.js
Reverts discordjs/discord.js#4308
This was a breaking change which required you to listen to `stdout`, `stderr`, etc manually.
Needs to be reworked if it should land in any minor version to let users control the way of doing it.
> revert(Shard): "fix missing child_process silent option of Shard to allow listening to output"

- src/structures/User.js
- Closes #4702 
#4636 recently introduced a bug where `User#bot` was set to `null` instead of `false`. This is the case because it checked if the bot property was present in the data to see if it was a partial or not, however this property also does not exist for a regular user. This has been fixed by using `User#partial` which checks if the username property exists instead.
**Status**
> fix(User): set User#bot to false if not partial

- src/client/Client.js
- typings/index.d.ts
This PR deprecates the old method of passing a `PermissionResolvable` into `Client#generateInvite` and instead allows an object of options to be provided consisting of `permissions`, `guild`, and `disableGuildSelect`, ([API Docs reference](https://discord.com/developers/docs/topics/oauth2#bot-authorization-flow))
Wasn't sure about adding `redirect_uri` seeing as its not apart of the bot authorisation flow
**Status**
- [  ] This PR changes the library's interface (methods or parameters added)
> feat(Client): allow options for generateInvite

- src/client/Client.js
the `Client#toJSON` method attempts to omit `presences` when json-ifying the client, however that property was removed with v12 
https://github.com/discordjs/discord.js/blob/da39e858a1d4bd23a2af2e693024512426615557/src/client/Client.js#L115-L121
**Status**
> refactor(Client): remove non-existant property from toJSON

- typings/index.d.ts
fix #4728 
Add `Message`, `GuildChannel` and `{ id: Snowflake }` as possible type for `GuildAuditLogsEntry#target`.
**Status**
> types: add all types for GuildAuditLogsEntry#target

- src/managers/PresenceManager.js
- src/structures/GuildMember.js
- src/structures/User.js
fixes #4742 
This PR changes the `GuildMember` and `User` classes to import `Presence` (and `VoiceState` on `GuildMember`) using `Structures.get(...)` rather than a require import, to correct instantiate any custom extended class
Notes: the [`NewsChannel`](https://github.com/NotSugden/yeetcord.js/blob/patch-16/src/structures/NewsChannel.js#L3-L9) and [`ClientPresence`](https://github.com/NotSugden/yeetcord.js/blob/patch-16/src/structures/ClientPresence.js#L3-L8) classes seem to not extend `TextChannel` and `NewsChannel` respectively, but i wasn't sure the best way to go about fixing that, so i've left it for now
**Status**
> fix: correctly import extendable classes

- typings/index.d.ts
- typings/index.ts
Previously, this was allowed:
```ts
channel.send({embed: {tilte: 'meant to be title'}})
```
This commit fixes this for `TextBasedChannel#send`, `Message#reply` etc. so that TS would emit an error.
This PR also changes `Message(Edit)Options.content` from `string` to `StringResolvable` and includes `NewsChannel` in `MessageTarget`.
**Status**
> types: don't allow any object in the first parameter if second parameter is not given in TextBasedChannel#send

- src/client/websocket/WebSocketShard.js
- typings/index.d.ts
fix #4754 
Using `NodeJS.Timeout` is more relevant than `NodeJS.Timer`.
**Status**
> fix(Typing): change NodeJS.Timer into NodeJS.Timeout

- src/util/UserFlags.js
- typings/index.d.ts
user flags `DISCORD_PARTNER` and `VERIFIED_DEVELOPER` have been renamed, this PR reflects those changes by deprecating the old names, and adding the renamed flags
see https://github.com/discord/discord-api-docs/pull/2011
**Status**
> feat(UserFlags): add renamed UserFlags

- src/structures/Guild.js
This PR modifies the `Guild#fetchWidget` function to cache the data received as it is not sent in the initial `GUILD_CREATE` packets ([API Docs ref](https://github.com/discord/discord-api-docs/issues/1102))
this PR also changes `setEmbed` and `fetchEmbed` to instead return the respective widget function,
this was to avoid duplicated code - both methods do technically call a different endpoint but they yield the same result
**Status**
> fix(Guild): cache fetched widget data

- package.json
- src/index.js
- src/structures/ClientApplication.js
- src/structures/Guild.js
- src/structures/Integration.js
- src/structures/IntegrationApplication.js
- src/structures/interfaces/Application.js
- typings/index.d.ts
api docs ref: https://github.com/discord/discord-api-docs/pull/1886/files
this PR (was meant to initially) adds `Integration#application`, and `IntegrationApplication#bot`
due to adding the new `IntegrationApplication` class, i opted to make an abstract `Application` class as its very similar to `ClientApplication`, except missing a few properties, and one of its own, and so wouldn't be duplicating 90% of a class
**Status**
- Tried to avoid that obviously but comment if I broke something
> feat(Guild): add includeApplications option for fetchIntegrations

- src/structures/Channel.js
- typings/index.d.ts
Currently, there is no easy way in TypeScript to find out if a channel is text-based or not.
```ts
['text', 'dm', 'news'].includes(channel.type)
channel.type === 'text' || channel.type === 'dm' || channel.type === 'news'
```
Both of these examples work fine during runtime, but don't act as a type guard; If `channel` had the type `Channel` before the check, it will also keep it afterwards.
```ts
channel instanceof TextChannel || channel instanceof DMChannel || channel instanceof NewsChannel
channel as TextChannel
```
These two would actually narrow the type down to only text-based channels, but both aren't really optimal. The former option is too long and the latter doesn't actually check the type, it just tells the …
> feat(Channel): add isText() type guard

- typings/index.d.ts
Currently `Partialize` is adding the `deleted` property to all partial types using it, including `PartialUser`, which is wrong as a `User` can't have the `deleted` property.
Additionally, `Partialize` is already making all properties nullable, so explicitly setting `username` to null isn't required - even on a partial user it can be populated after e.g. a `USER_UPDATE` event.
Fixes #4615
**Status**
> typings(PartialUser): fix PartialUser remove `deleted` property

- src/util/Util.js
- ⚠fixes #4778
As #4778 has brough to light we currently throw the response if an invalid token is provided when fetching the recommended amount of shards from the API.
While changing the kind of error to throw here could be framed as major i am so bold to say that this can not be deliberate design (as it results in the rather unhelpful ` #<Response>` being thrown) and thus will tag it as patch and consider it a fix rather than a feature.
https://github.com/discordjs/discord.js/blob/b0ab37ddc0614910e032ccf423816e106c3804e5/src/util/Util.js#L246-L247
Seeing that providing an invalid token will result in a 401 response adding a line to throw TOKEN_INVALID instead if that's the case provides more context to the user …
> fix(Util): throw token invalid for fetching rec. shard amount

- src/structures/GuildChannel.js
the docs for the `options.rateLimitPerUser` parameter in `GuildChannel#clone` seems to have its default value documented as `ThisType.rateLimitPerUser`, however `ThisType` should be `this`
**Status**
> docs(GuildChannel): ThisType should be this

- typings/index.d.ts
The typings mark more event arguments as possibly partial than required.
- `GUILD_BAN_ADD`/`GUILD_BAN_ADD` always includes a full User object
- `GUILD_MEMBER_ADD`/`GUILD_MEMBERS_CHUNK` always includes a full Member object
- `USER_UPDATE` always includes a full User object
- `GUILD_MEMBER_UPDATE` as well, which d.js-internally emits `userUpdate`
I've tested that the gateway indeed seems to emit full objects for those events.
As the gateway always emits full objects in those cases the d.js-emitted objects will never be partial.
**Status**
> fix(Typings): remove Partial types from some events

- typings/index.d.ts
This reverts some of the changes in f451be05 so that this works:
```ts
const embed: MessageEmbedOptions = {
fields: [{
// fixed stuff
}],
};
if (/* condition */) {
embed.fields.push({
// conditional stuff
});
}
```
See https://github.com/discordjs/discord.js/pull/4692#issuecomment-687252066.
**Status**
> types: don't use readonly arrays in interfaces

- src/rest/RESTManager.js
Fixes the following warning on every pull request:
**Status**
> fix(lint): RESTManager warning

- src/structures/Guild.js
The docs example was incorrect, as the parameter is called `updated` but was later referenced as `guild`.  This PR fixes that by changing it to `updated` to match other examples, such as `setRegion()`
**Status**
> docs(Guild): Guild.setName() example

- src/structures/Role.js
The setName example is incorrect and will display the wrong data for the name before the method is called.  Additionally, it's inconsistent with other examples, such as `GuildChannel#setName`
**Status**
> docs(Role): Update various Role method descriptions

- src/client/actions/Action.js
- src/client/actions/ActionsManager.js
- src/client/actions/GuildMemberRemove.js
- src/client/actions/MessageReactionAdd.js
- src/client/actions/TypingStart.js
- src/client/websocket/handlers/TYPING_START.js
The Gateway includes a member object wrapping a user object in `MESSAGE_REACTION_ADD` and `TYPING_START` events, if those events originated from a guild. Those were previously ignored. If available, that data is now used.
Similar story for `GUILD_MEMBER_REMOVE`, it includes a full `user` object. Use that instead of just the ID.
**Status**
> fix(Partials): Use more user objects available from the gateway

- src/client/actions/Action.js
- src/client/actions/TypingStart.js
Fixes #4821
this.getMember() returns undefined if there is no cached member and partials are disabled for members.
Also only checks for the correct channel type in TypingStart if there actually is a known channel, I've missed this in my previous PR.
**Status**
> fix(Action): Don't crash when partials are disabled

- src/structures/Message.js
ty to @NotSugden for drawing to my attention that this should be a Promise rejection.
I don't believe this one is breaking because it only addresses one method by which the previously thrown error could not be handled (Promise.catch) with no impact to try/catch.
**Status**
> fix(Message): use Promise#reject instead of Throw on Message#delete

- src/rest/APIRequest.js
- src/rest/AsyncQueue.js
- src/rest/RESTManager.js
- src/rest/RequestHandler.js
Better alternative to #2744.
- Fixes #2496.
- Fixes #4792.
- Fixes #3665.
When running the following code as an example `message.channel.send();`, REST gives us this stack trace:
```javascript
DiscordAPIError: Cannot send an empty message
at RequestHandler.execute (***/node_modules/discord.js/src/rest/RequestHandler.js:170:25)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
After this patch, it returns this one:
```javascript
DiscordAPIError: Cannot send an empty message
at RequestHandler.execute (***/node_modules/discord.js/src/rest/RequestHandler.js:157:13)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async RequestHandler.push …
```
> feat(Rest): switch queue to AsyncQueue

- src/client/actions/Action.js
Fixes #4840
I would've expected Discord to _alyways_ include _both_ a `guild_id` and a `member` if the event came from a guild but - guess not.
Make sure that the fields we are interested in are actually present in the payload.
**Status**
> fix(Action): Sanity-Check if Discord includes all required data

- src/errors/Messages.js
- src/sharding/Shard.js
This fixes #4286 by ensuring that a cached call to `eval/fetchClientValue` will never exist where both `process` and `worker` are `null` in a shard.
**Status**
> fix(Shard): avoid caching null child in eval/fetchClientValue

- src/managers/GuildManager.js
- test/createGuild.js
- typings/index.d.ts
This PR adds support for the `afk_channel_id`, `afk_timeout`, and `system_channel_id` parameters in the [create guild](https://discord.com/developers/docs/resources/guild#create-guild-json-params) endpoint by adding the `afkChannelID`, `afkTimeout`, and `systemChannelID` options in `GuildManager#create`.
This PR also fixes a minor bug in `create` when specifying types for the channels due to the channel types not being changed from `'text'`, `'voice'` etc to the corresponding numbers, so Discord would return an error.
**Status**
> feat(GuildManager): add AFK and system channel options in create

- src/managers/MessageManager.js
The `MessageManager#delete` method could silently resolve without making any API call if the supplied param was not MessageResolvable.
```js
message.channel.messages.delete("755203620831756368") // successfully deletes message
message.channel.messages.delete("1") // throws DiscordAPIError: Unknown Message
message.channel.messages.delete() // would silently resolve
message.channel.messages.delete({ foo: "bar" }) // would silently resolve
```
This addresses case 3 and 4 above by throwing a TypeError for params which are not `MessageResolvable`
semver:major
**Status**
> fix(MessageManager): throw if delete param is not MessageResolvable

- src/managers/ReactionUserManager.js
`ReactionUserManager` has a `.client` property, so why not use it?
**Status**
> refactor(ReactionUserManager): use client property

- src/rest/RequestHandler.js
#4835 introduced a regression in 4xx errors, the following chunks of code are not identical - the old one rejected with DiscordAPIError if there was a 4xx error, but the new one throws, and then re-throws but as a HTTPError:
https://github.com/discordjs/discord.js/blob/7b38f46caf9790357eed5b24c118123a00c867fd/src/rest/RequestHandler.js#L167-L175
https://github.com/discordjs/discord.js/blob/169d4c3bff75858d84ed91d1a92b0c1f3bedbc02/src/rest/RequestHandler.js#L150-L158
My apologies for anyone affected, even though nobody reported this issue (yet) since the names and properties are nearly identical for error handlers that don't check for `instanceof`. But the good news, retried AbortErrors!
<details>
<summary>Stack …
> fix(Rest): resolved a regression, added retried AbortError

- src/structures/GuildChannel.js
- typings/index.d.ts
[Modify Channel](https://discord.com/developers/docs/resources/channel#modify-channel) API accepts `null` for topic to unset it, and already we can use `channel.setTopic(null)` in discord.js.
This PR document the method accept `null` and fix typing.
**Status**
> fix(GuildChannel): make setTopic argument nullable

- typings/index.d.ts
The typings don't state that the description of a `GuildPreview` can be null. It can be null if a guild has never set a description before for which this pull request addresses.
**Status**
> types(GuildPreview): Make description nullable

- typings/index.d.ts
This PR moves the `flags` property from `Presence` to `Activity` in the typings. There is no `Presence#flags` but there is [`Activity#flags`](https://discord.js.org/#/docs/main/stable/class/Activity?scrollTo=flags).
**Status**
> types(Activity): move flags from Presence to Activity

- typings/index.d.ts
This PR makes `TextBasedChannel#lastPinAt` nullable in the typings, like it is [documented](https://discord.js.org/#/docs/main/stable/class/TextBasedChannel?scrollTo=lastPinAt).
**Status**
> types(TextBasedChannel): make lastPinAt nullable

- src/client/Client.js
- src/client/actions/MessageUpdate.js
- src/structures/Message.js
- src/util/Constants.js
- typings/index.d.ts
This fixes #4826 by adding a new client option to set a fixed limit on the edit history stored for each message in the client cache.
This has been tested in production on my bot (where the original memory issue was observed) for roughly a month and seems to be fine.
**Status**
> feat(Message): add messageEditHistoryMaxSize to limit stored msg edits

- src/managers/GuildMemberManager.js
Fixes #4883
If you call the function mulltiple times immediately after another (within the same millisecond), both request would have the same nonce, resulting in the second request resulting with the data of the first request.
To fix this, make sure to use an actually random nonce when fetching members.
**Status**
> fix(GuildMemberManager): Use actually random nonce in fetch

- src/client/actions/InviteCreate.js
Fixes #4851
Previously the code was only checking for either of channel and guild to be present, and only exited early if _neither_ was present. However in a scenario where the client receives an invite with a known guild but an unknown channel, this would have crashed further down the line because of `channel` being undefined.
I don't really see a reason to keep the guild check so I've just removed it alltogether.
**Status**
> fix(Actions): Avoid crash in InviteCreate with unknown channel

- src/structures/GuildChannel.js
Fixes #4868
This issue did not just affect CategoryChannels, it affected any channel type.
This seems to be the only place where `parentID` is being set, so make sure that it defaults to null there. The API documentation also actually states that `channel_id` may be unset unstead of null.
**Status**
> fix(GuildChannel): Default `parentID` to `null`

- .github/workflows/deploy.yml
- .github/workflows/test-cron.yml
- .github/workflows/test.yml
Use npm ci instead of npm install when installing dependencies in CI.
This PR makes changes to CI workflows, more particularly, the `Install dependencies` steps in workflows. It replaces all instances of `npm install` with `npm ci`, which is a better way of installing npm dependencies in a CI enviroment. You may read more about `npm ci`, it's differences with `npm install` why it's better to use it in this case by looking at [the npm CLI documentation for `npm ci` here.](https://docs.npmjs.com/cli/ci.html)
**Status**
> ci: use npm ci instead of npm install

- src/managers/GuildMemberManager.js
Since https://github.com/discordjs/discord.js/commit/257371da288d5ac0d796de6802b951fa30245c0d was merged, it allowed an array of values to be passed through a query's value (as explained [here](https://github.com/discordjs/discord.js/pull/4143#pullrequestreview-405182638)). https://github.com/discordjs/discord.js/commit/f1194afd7c046a0ac3a89036f917187e4e95b4ec did not accommodate for these changes that were committed beforehand to make `include_roles=foo&include_roles=bar` possible. 
As of https://github.com/discord/discord-api-docs/commit/b9edace323c9df64c79f104d85984690ae4e2977#diff-c4e1390fca89ecc96b01a093f988fa1cR720 Discord now accepts a "comma-delimited array of snowflakes"... but the old `key=value&key=value` still works (and is even being used in the client). This PR changes the …
> fix(GuildMemberManager): options.roles on 'prune'

- src/client/actions/GuildEmojiCreate.js
This pull request addresses the issue where creating emojis via the application would fire the `emojiUpdate` event twice. A simple check has been added which will prevent this.
This pull request will resolve issue #4857.
**Status**
> fix(GuildEmojiCreate): Prevent double fire from emoji creation

- src/structures/GuildMember.js
This PR fixes a bug to do with `GuildMember.hasPermission`, to explain:
if a server had 2 roles, `@everyone` and `Role A`, if `@everyone` only had `SEND_MESSAGES`, and `Role A` only had `VIEW_CHANNEL`, `GuildMember.hasPermission(['SEND_MESSAGES', 'VIEW_CHANNEL'])` would inaccurately return `false`, this is because `GuildMember.hasPermission` checks if any of the members roles has the provided permissions, instead of combining all the permissions the member has, and then checking that
**Status**
> fix(GuildMember): properly check permissions for hasPermissions

- src/errors/Messages.js
- src/managers/GuildEmojiManager.js
- typings/index.d.ts
`Client#emojis` and `Guild#emojis` both return a `GuildEmojiManager`, however the current code base does not account for former not having a valid guild property. `client.emojis.create(...)` before resulted in `DiscordAPIError: 405: Method Not Allowed`, this PR aims to fix that by checking if a guild is present before using it for methods and throwing a custom error.
**Consideration**
There's also the option to create two separate classes for `Client#emojis` and `Guild#emojis`, I've decided to take this approach for now but I'm open to suggestions.
**Status**
> fix(GuildEmojiManager): check for guild in methods that use it

- src/managers/GuildEmojiManager.js
- ⚠resolves #4006
Currently the `"<:name:id>"` and `"<a:name:id>"` emoji "mention" format strings are not valid input to Message#react, as #4006 brought up. This PR aims to support this input by utilizing the libraries [Util.parseEmoji](https://discord.js.org/#/docs/main/stable/class/Util?scrollTo=s-parseEmoji) method.
The length check is required as the parseEmoji function also returns a valid object with nonsensical input. A name will always be present, if the emoji is valid - either by the custom emoji name or the unicode representation.
**Status**
> feat(Message): allow custom emoji format for react

- src/structures/GuildChannel.js
fixes #4918 
fixes an issue that my PR #4845 introduced - setting `GuildChannel#parentID` to null in the constructor
**Status**
- untested but i will test it later to make sure
> fix(GuildChannel): parentID shouldn't be set in the constructor

- src/sharding/Shard.js
Fixes a regression from https://github.com/discordjs/discord.js/pull/4845/files#diff-75a4f785c550209a707697c399a87938fad288bbd1c571614808ed8c08edbd04L99 that currently means shards don't restart when their process exits.
This fixes #4927.
**Status**
> fix(Shard): don't pass event arguments to exit handler

- .github/CONTRIBUTING.md
Use `npm ci` instead of `npm install` after cloning the repository. When running on my (old) machine, `npm ci` finished in about 26 seconds after a fresh clone where `npm install` took about 42 seconds to finish. Since you already have a `package-lock.json` file, `npm ci` will also make sure that everyone uses the same package versions consistently.
**Status**
> docs: use npm ci instead of npm install

- src/structures/Message.js
- typings/index.d.ts
This PR adds the Message#crosspostable property, to know if a message can be crossposted.
**Status**
> feat(Message): add crosspostable property

- typings/index.d.ts
I created an issue #5002 this is the PR to resolve it.  I wasn't 100% sure i've followed the contribution guidelines.
This solves the missing `client` property from the `MessageReaction` typing
**Status**
> fix(MessageReaction): defines the client property in the type

- src/client/actions/Action.js
- src/client/actions/MessageReactionAdd.js
- src/client/actions/MessageReactionRemove.js
This PR fixes a bug involving partials around the `messageReactionAdd` event causing it to emit a partial user with an id with the value `undefined`, as well as caching incoming members and users from said event and `typingStart`.
The above mentioned bug was caused due to `getUser` being called with a raw user object, rather than an object with an `user_id` key, which it actually is expecting.
https://github.com/discordjs/discord.js/blob/b8fd3f65d964f080afb42dd37eb21a13c0d84f8f/src/client/actions/Action.js#L87-L90
---
`MESSAGE_REACTION_ADD`, as well as `TYPING_START`, emit a member and user, which now will be added to the cache, removing the requirement to enable the `USER` partial type for this event to work on …
> fix(MessageReaction*Action): correctly cache incoming members and users

- src/client/actions/ActionsManager.js
- src/client/actions/GuildMemberUpdate.js
- src/client/websocket/handlers/GUILD_MEMBER_UPDATE.js
This PR ensures that the incoming member (update) data is always cached, even if the member was not cached.
If using partials, the guildMemberUpdate event will be emitted with a partial 'old' member.
If not using partials, the guildMemberAvailable event will be emitted.
I also added the guildMemberAvailable event doc string back, which was erroneously removed from the documentation some time ago. (See: f3cad81f5314a3997ac188277e2471ba84cbd771 )
**This is not tested yet.**
**Status**
> fix(GuildMemberUpdate): cache incoming members & use partials if enabled

- src/structures/User.js
Fixes #4985 and fixes #4943.
This PR fixes the bot property of a bot to erroneously changing into `false` when the USER partial was enabled and their partial is requested through something like `Action#getUser` or explicitly through `UserStore#add` with just an `id` property.
This is solved by only initially setting the property, or updating it if the payload actually includes a `bot` property
**Status**
> fix(User): only assign to bot initially or if info is actually present

- .eslintrc.json
- src/errors/Messages.js
- src/sharding/Shard.js
- src/sharding/ShardClientUtil.js
- src/sharding/ShardingManager.js
- src/util/Snowflake.js
- typings/index.d.ts
Adds the ability to call `broadcastEval` and `fetchClientValues` from a shard to run on different target shard, instead of broadcasting to all and using an `if` in the given script to filter by shard.
Now you can target a shard directly:
```javascript
const { ShardClientUtil } = require('discord.js');
const guild = '433980600391696384';
// Get the shard Id -- `client.shard.constructor.shardIdForGuildId` could also be used
const shard = ShardClientUtil.shardIdForGuildId(guild, 2);
// Get the guild from that shard only
const name = await client.shard.broadcastEval(`this.guilds.cache.get('${guild}').name`, shard);
return [name, shard, client.shardId];
```
We get back `[JetBrains Community, 1, 0]`, so we can see it …
> feat(Shard): shard-specific broadcastEval/fetchClientValues + shard Id util

- src/managers/GuildMemberManager.js
Consistent with the error thrown by `Message#delete()` when passing a number instead of an object, implements the same TypeError to `GuildMemberManager#ban()` and subsequently `GuildMember#ban()` to catch people passing a string instead of an object.
Not sure how to semantically version this.
**Status**
> feat(GuildMemberManager): throw TypeError on incorrect GuildMemberManager#ban params

- docs/examples/moderation.md
- src/client/voice/VoiceConnection.js
- src/structures/Guild.js
- src/structures/Message.js
- src/structures/MessageMentions.js
- src/structures/Role.js
- test/random.js
- typings/index.d.ts
Remove `Guild#member` as it's a poorly-named helper method for `Guild#members#resolve` (although not a 1-to-1, I do understand).
Fixes #4888
**Status**
> Remove Guild#member

- src/structures/User.js
- typings/index.d.ts
User#locale is currently a useless property as Discord does not expose the locale property to bots (can only be accessed via the Get Current User endpoint), and it is always `null` or `undefined` in d.js (depending on the exact version).
This breaking PR removes it.
**Status**
> remove User#locale

- src/managers/RoleManager.js
- typings/index.d.ts
1. When using `RoleManager#fetch` with a single ID, [it tries to get the role from `this.cache`](https://github.com/discordjs/discord.js/blob/master/src/managers/RoleManager.js#L58), however that won't work when `cache` is set to `false` and it will return `null` even when the role was fetched correctly. This has ben fixed by getting the role from the collection instead.
2. Unlike any other manager, fetching without passing an ID returns the manager instead of the fetched collection, this has been changed for consistency.
**Status**
> fix(RoleManager): fix ID return value, change return type to collection

- esm/discord.mjs
- src/client/Client.js
- src/index.js
- src/managers/BaseGuildEmojiManager.js
- src/managers/GuildEmojiManager.js
- typings/index.d.ts
[Continuing from #4917] This adds a new manager class `BaseGuildEmojiManager` to be used for `Client#emojis`, `GuildEmojiManager` then extends that to provide methods to interact with the API.
**Status**
> feat: BaseGuildEmojiManager

- src/client/voice/VoiceConnection.js
- src/client/voice/networking/VoiceWebSocket.js
- src/client/voice/receiver/PacketHandler.js
- src/client/voice/util/Silence.js
**Problem:**
This resolves #5019. When a user has video enabled, they send silent audio frames continually even if they are not speaking. Discord.js didn't check whether a received audio packet was silence or not for performance reasons. This shortcut is no longer applicable since it causes the incorrect behaviour described in the issue above.
**Fix:**
Instead of decoding all the received packets, we only decode the packets from users with video enabled (which is where the issue occurs). If a packet is received from such a user and it turns out to be silent audio, the packet is ignored which is a graceful fix for this issue. This means performance will only degrade (and even then, I doubt it will be by a lot) in …
> fix(Voice*): filter out silent audio from video users

- src/structures/MessageReaction.js
Fixes #5046 by setting `MessageReaction#me` in `MessageReaction#_patch` ensuring it gets updated when fetching partials.
**Status**
> fix(MessageReaction): set MessageReaction#me in patch method

- src/client/websocket/WebSocketManager.js
[`WebSocketManager`](https://discord.js.org/#/docs/main/master/class/WebSocketManager?scrollTo=status) has a type of `number`, but [`Status`](https://discord.js.org/#/docs/main/master/typedef/Status) is more descriptive.
The type is already `Status` in the typings, just not in the docs.
**Status**
> docs(WebSocketManager): fix type of status

- .github/workflows/deploy.yml
- .github/workflows/test-cron.yml
- .github/workflows/test.yml
- README.md
- docs/general/faq.md
- docs/general/welcome.md
- package.json
For v13.x, we are permitted to do breaking changes, and can clean up a lot of code (specially nullability checks) with the new ES2020 syntax, specially with `?.` and `??`.
Node.js v14.0.0 is the lowest version that supports both features.
**Status**
> chore(Engine): bump Node.js to v14.0.0

- src/structures/BaseGuildEmoji.js
This fixes a typo in the BaseGuildEmoji#requiresColons property which was missing the "s" in requires.
**Status**
> fix(BaseGuildEmoji): typo in requiresColons

- src/structures/interfaces/Collector.js
This PR asserts that the provided filter-function is actually a function, if that fails, an error indicating such is thrown.
**Status**
> fix(Collector): throw an error if a non-function was provided as filter

- src/util/UserFlags.js
- typings/index.d.ts
This PR resolves #5102 by renaming the user flag `EARLY_VERIFIED_DEVELOPER` to `EARLY_VERIFIED_BOT_DEVELOPER`.
This is the name we [and Discord](https://discord.com/developers/docs/resources/user#user-object-user-flags) actually document.
This PR also removes the deprecated aliases.
**Status**
> fix(UserFlags): correct early bot dev name, remove deprecated aliases

- src/structures/GuildChannel.js
The methods `GuildChannel#updateOverwrite` and `#createOverwrite` had some awkward wording in the description: `. (...)` does not look good.  This PR cleans up the descriptions to be one sentence that's clearer in meaning.  There's also changes to make `permission overwrite/s` consistent - some lines had `permissions overwrite/s`.
**Status**
> Change permission overwrite methods descriptions

- src/structures/GuildMember.js
- typings/index.d.ts
Passing null into GuildMember#setNickname will reset the nickname. But neither the typings nor the jsdoc indicate that you can pass that in.
**Status**
> feat(GuildMember): make GuildMember#setNickname first param nullable

- src/client/Client.js
- typings/index.d.ts
- Move `InviteGenerationOptions` typedef from below the class to above the method (consistency)
- Passing a `PermissionResolvable` is deprecated, so it now throws an error if the passed options are not an object
- ~Fetching the application doesn't seem required, so the method doesn't return a promise anymore~
- Only add permissions to the query if they aren't `0`
**Status**
> cleanup(Client): improve generateInvite()

- src/structures/Message.js
- src/util/Constants.js
- typings/index.d.ts
As of discord/discord-api-docs#2118 not all non-zero message types are system. 
Type 19 `Reply` is the only current type that benefits from this change.
Note: the reply type will only be recieved once #4879 is implemented.
This PR also introduces SystemMessageTypes so that future message types can be more easily sorted.
**Status**
> fix(Message): #system non-zero message types are not guaranteed to be system

- src/rest/APIRequest.js
Removed null and undefined being filtered out in string forms which caused issues in `Client#api`, closes issue: https://github.com/discordjs/discord.js/issues/5072
This PR is meant to remove the filtering of string forms of null and undefined to prevent `DiscordAPIError` being thrown when given them as a string in the query of the `Client#api`
**Status**
> Remove filtering of string forms of null and undefined

- src/client/Client.js
- src/structures/ClientPresence.js
- src/structures/Presence.js
this PR adds data about the client's presence to the ClientPresence class from the options that were passed in the client constructor. without this PR, the client cannot display its status or activity in any way, because by default, ClientPresence is changed only using the setStatus, setActivity, and setPresence methods. so if these methods are not used, the ClientPresence class always contains only standard values, although in fact the values may differ from those displayed in the Discord. 
this PR also fixes an issue where the setStatus and setActivity methods overwritten values for each other. that is, if I set the idle status to the client via setStatus, and then use setActivity to set the activity, the idle …
> fix(ClientPresence): add presence to ClientPresence from ClientOptions

- src/managers/MessageManager.js
- src/structures/Message.js
- typings/index.d.ts
Removes options for `Message#delete` (and `MessageManager#delete`):
- `timeout` because that implementation is prone to errors (see e.g. #4916) and inconsistent with others, being the only method which takes a timeout value
- `reason` because messages deleted by bot users won't create audit log entries
**Status**
> cleanup(Message): remove options for Message#delete

- src/managers/GuildEmojiRoleManager.js
- src/managers/GuildMemberRoleManager.js
- typings/index.d.ts
Currently BaseManager#valueOf returns the cache collection, while this is not the case for the pseudo managers GuildEmojiRoleManager and GuildMemberRolemanager. 
This PR brings the needed consistency and implements the pseudo managers #valueOf method akin to the BaseManager.
**Versioning considerations:**
- This could be seen as semver **major** as it changes the behavior of the public facing API #valueOf to be consistent with BaseManager
- This could be seen as **patch** since it fixes inconsistent behavior, which appeared due to an oversight (as already briefly mentioned in #4594 the return value for BaseManager was picked to properly allow passing the structure through broadcast evaluation without loosing all …
> fix: implement valueOf on pseudo managers

- src/structures/interfaces/TextBasedChannel.js
Documents that system messages cannot be replied to. 
There is no built in check for this as it is unlikely to attempt a reply to a system message, but it should be documented.
**Status**
> docs(MessageOptions): indicate that replyTo cannot be system

- src/structures/MessageReaction.js
Reverts #5047 because I think it introduced more bugs than it solved. 
There's still a very strange issue in here somewhere which results in `MessageReaction#me` being updated when you fetch it... but not until after fetch has returned... just in the cache.
**Status**
> revert: 5047

- src/structures/Message.js
MessageEditOptions had an optional flags parameter that was undocumented.
The parameter is already used by Message#suppressEmbeds
**Status**
> docs(MessageEditOptions): add the flags parameter

- src/client/Client.js
- src/structures/Message.js
- src/util/Constants.js
- typings/index.d.ts
An alternative to #5154, we should consider outright removing the internally stored edit history of a message, and rely on the user storing this themself by listening to the MessageUpdate event, which will emit the old message once the message has been patched.
**Status**
> refactor(Message): remove stored edit history

- package-lock.json
- package.json
- src/client/BaseClient.js
[`setimmediate`](https://github.com/yuzujs/setImmediate) is a browser polyfill that is executed when `global.setTimeout` does not exist, and since we do not support webpack anymore, there is no reason to keep it here.
**Status**
> chore(Deps): remove setimmediate

- .gitignore
- .npmignore
This PR removes the webpack files from `.npmignore` and `.gitignore` as they no longer need to be ignored
**Status**
> chore: remove webpack from .*ignore files

- src/structures/MessageEmbed.js
> fix(MessageEmbed): include `author.name` in length getter

- typings/index.d.ts
Adds labels to the tuple types in the ClientEvents interface (typings). These labels will appear as argument names when using IntelliSense, instead of 'args_0', 'args_1', etc. They will be helpful for knowing exactly what each argument represents, mostly in update events (which pass the 'old' and 'new' version of the object), and shard events (which pass the shard ID).
Although most labels are self-explanatory, some other may need slight changes to be more accurate.
**Status**
> feat(ClientEvents): add tuple labels to event arguments

- src/errors/Messages.js
- src/util/BitField.js
This PR moves the invalid bit for BITFIELD_INVALID errors into the error message. This was previously the preferred approach, reverted due to forcing semver major by changing a public-facing message (#4617).
This should greatly increase the visibility of invalid bits being passed in various places, reducing the number of requests regarding typos and outright wrong flags being used in support.
**Status**
> feat(BitField): move problematic bit into the error message

- typings/index.d.ts
As shown below, [`Webhook(Client)#send()`](https://discord.js.org/#/docs/main/stable/class/Webhook?scrollTo=send) would either return a Message (if the client was initiated and the channel was cached) or it would return the raw message response from the API (which has been added as a `APIRawMessage` interface in this PR).
https://github.com/discordjs/discord.js/blob/d2341654fe6ef87c6048bb5bf74c394062f3f618/src/structures/Webhook.js#L162-L164
Cuurently the typings do not reflect this behaviour, this PR fixes that.
I did consider making use of the [`APIMessage`](https://github.com/discordjs/discord-api-types/blob/main/v6/payloads/channel.ts#L53-L81) over on [`discord-api-types`](https://github.com/discordjs/discord-api-types) but that would mean introducing another dependency which be a …
> fix(typings): return types for 'Webhook(Client)#send()'

- src/structures/Message.js
#5056, check to make sure return from channel#permissionsFor isn't null before calling .has on it. Open to refactoring to avoid duplicate permissionsFor calls
closes #5056 
**Status**
- [] Code changes have been tested against the Discord API, or there are no code changes
> fix(Message): update getters to take null permissions into account

- src/structures/GuildChannel.js
- src/structures/TextChannel.js
- typings/index.d.ts
Discord.js did not support providing `type` in the GuildChannel#edit payload, this adds support for that and a `setType` helper method on TextChannel and NewsChannel.
The API will throw an error if attempting to convert to anything other than Text or News.
**Status**
> feat(GuildChannel): support conversion between text and news 

- typings/index.d.ts
fixes: #5205
The `dispatcher` property of `VoiceConnection` is marked as nullable in docs but only got `StreamDispatcher` as its type in typings. This PR fixes it.
**Status**
> fix(VoiceConnection): make #dispatcher nullable

- src/structures/GuildEmoji.js
The available property was unchecked in `GuildEmoji#equals` causing updates to available to go uncached.
closes: #5200
I do not have an available guild where the state of available can change to test this on, please do test this if you can.
**Status**
> fix(GuildEmoji): check for changes to available in equals

- src/sharding/ShardingManager.js
> feat(ShardingManager): Allow b-Eval/fetchClientValues on a specific shard when not all are ready

- typings/index.d.ts
This PR removes the "timeDifference " property from the RateLimitData type, since this property no longer exists in the implementation:
```javascript
this.manager.client.emit(RATE_LIMIT, {
timeout,
limit: this.limit,
method: request.method,
path: request.path,
route: request.route,
});
```
**Status**
- [ x] Code changes have been tested against the Discord API, or there are no code changes
- [ x] I know how to update typings and have done so, or typings don't need updating
- [ x] This PR **only** includes non-code changes, like changes to documentation, README, etc.
> types(RateLimitData): remove timeDifference property

- typings/index.d.ts
The behaviour of GuildChannel#permissionsFor, is that if it's able to resolve the data, it will always return permissions (since the private methods `memberPermissions` and `rolePermissions` never return `null`):
https://github.com/discordjs/discord.js/blob/9ffcd83027f0fc06d69df21475865ad55138de01/src/structures/GuildChannel.js#L113-L119
For data to be resolvable, it expects either an instance or a string:
https://github.com/discordjs/discord.js/blob/9ffcd83027f0fc06d69df21475865ad55138de01/src/managers/BaseManager.js#L59-L63
If an instance is provided, it will always return the instance itself, therefore, when passing a value that matches `Holds`, the type return should always be `Holds` as well.
When passing a …
> fix(GuildChannel): overload permissionsFor and BaseManager#resolve[id]

- typings/index.d.ts
This PR removes `resolve()` and adds the `isMessage` in `APIMessage`'s typings.
**Status**
> fix(ApiMessage): remove resolve() from typings

- src/managers/BaseManager.js
This PR adds an extra check in the `BaseManager#resolveID` method to make sure that it doesn't return the `idOrInstance` parameter back when it is a non-numeric string. I am aware of the fact that the method only expects a string in the case of a `Snowflake` and passing any other type of string is the fault of the user, but I think in case a user does pass a string, which is not a snowflake the method should return `null` instead of the string that was passed.
I had a chat about this in the discord server with @kyranet and that is from where I got the `regex` used in the PR. It was him who advised me to use regex instead of what I was doing in a somewhat related project. Using `{17, 19}` instead of `{17, 18}` in …
> docs(BaseManager): fix a typo in #resolveID description

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/SUPPORT.md
- GitHub uses checkboxes as todo lists only. We currently use them as checkboxes for versioning classification, which intersects badly with GitHub native features (milestone progress, progress notifications, the progress bar in PR overview), to solve the issue this PR moves classification and optional lines into a comment at the bottom (see next point) to be moved out if applicable.
- Fix grammar and typo in various places, streamline wording to be more concise and compact
- Remove comments from the top. The "please ask questions on discord.js" is now covered with a button in the issue view. The comment is not stripped when posted to our webhook, blocking any and all useful information in favor of those lines.
> chore(*): streamline issue and PR templates and redirects

- src/client/websocket/WebSocketShard.js
I just changed an incorrect key name that was introduced in Pull Request #3722. When destroying the websocket from the WebSocketShard#_send method it's using `close` as the key name instead of `closeCode`. This was just a small thing that I noticed while going through the files and I did a little bit of testing before I made this pr and it didn't break or solve anything that I know of.
> fix(WebSocketShard): key name in WebSocketShard#_send.

- src/client/Client.js
- src/errors/Messages.js
- src/util/Constants.js
- typings/index.d.ts
This PR adds the ability to generate an invite link with additional scopes. 
It does not accept all scopes as valid due to whitelist requirements and that combining those scopes with the bot scopes is highly unlikely
**Status**
> feat(Client): add InviteGenerationOptions#additionalScopes

- src/structures/Role.js
The `toJSON()` method from the `Permissions` class returns the bitfield as a string, however the bitfield is passed directly here, resulting in `TypeError: Do not know how to serialize a BigInt`
> fix(Role): pass Permissions class, not the bitfield

- src/structures/Guild.js
- src/structures/GuildChannel.js
I fixed an issue where the following methods were passing the reason argument as a property to the edit method instead of a parameter.
Most of these methods have had it that way for 3 years in which I don't know if y'all will want to fix it at this point. But I brought it up in case.
`Guild#setIcon` -> was introduced in #1975 (3 years ago)
`Guild#setSplash` -> was introduced in #1975 (3 years ago)
`Guild#setBanner` -> was introduced in #3364 (2 years ago)
`Guild#setDiscoverySplash` -> was introduced in #4619 (7 months ago)
`GuildChannel#overwritePermissions` -> was introduced in #3853 (1 year ago)
- Code changes have been tested against the Discord API, or there are no code …
> fix(Guild/GuildChannel): methods reason arg usage

- src/managers/ChannelManager.js
- typings/index.d.ts
ChannelManager#fetch can return Promise\<null> but is only documented to return Promise\<Channel>, this PR fixes the docs and typings.
fetch:
https://github.com/discordjs/discord.js/blob/d744e51c1bdb4c7a26c0faeea1f2f45baaf5fd3c/src/managers/ChannelManager.js#L92
add:
https://github.com/discordjs/discord.js/blob/d744e51c1bdb4c7a26c0faeea1f2f45baaf5fd3c/src/managers/ChannelManager.js#L32-L35
> docs(ChannelManager): `fetch` can return Promise<null>

- src/structures/GuildChannel.js
⚠️ closes #5273
The merge of #5022 has caused a regression, which this PR aims to fix.
When no channel is provided in data the PR defaults to `this.type`. This is however not the required numerical for the channel type the API expects resulting in
```
DiscordAPIError: Invalid Form Body
type: Value "text" is not int.
```
~~The other case (type is present in data) chooses to do the defaulting through the ChannelTypes enum and uppercasing the expected text value, which I have accordingly replicated in the defaulting case.~~
**Status**
> fix(GuildChannel): regression on default channel type

- src/managers/GuildManager.js
This PR adds missing `toString` functions on various `Permissions#resolve(...)` functions within GuildManager#create.
This should be treated with high severity.
> fix(GuildManager): add missing toString() on Permission#resolve fns

- src/structures/GuildMember.js
Document the implicit owner override in the GuildMember#permissions getter.
> docs(GuildMember): document owner override in permissions getter

- typings/index.d.ts
This PR fixes the typings for `PermissionOverwrites#resolveOverwriteOptions` to accept `PermissionOverwriteOption` instead of `ResolvedOverwriteOptions`
> typings(PermissionOverwrites): use correct parameter type for resolveOverwriteOptions

- src/managers/ReactionUserManager.js
- typings/index.d.ts
The `before` option is apparently not actually supported as per <https://github.com/discord/discord-api-docs/issues/1324#issuecomment-579019973> (despite documented)
> fix(ReactionUserManager): remove before query option

- src/structures/MessageCollector.js
- src/structures/ReactionCollector.js
- src/structures/interfaces/Collector.js
- typings/index.d.ts
`endReason` only returns a value, so there's no reason why it should be a method.
> refactor(Collector): make endReason a getter

- src/managers/ReactionUserManager.js
The description currently says that fetching returns all users on the reaction.  This is incorrect, as there is an API limit of 100 users per fetch.  This PR changes the description to better match the actual behavior.
> docs(ReactionUserManager): fetch description

- src/client/Client.js
- src/rest/RESTManager.js
- src/rest/RequestHandler.js
- src/util/Constants.js
- typings/index.d.ts
Currently, there is no support for preemptively avoiding the global rate limit - any requests in-flight to Discord at the time the limit is reached will simply result in 429s. This PR adds a configurable preemptive global rate limit option `restGlobalRateLimit` (defaulting to zero, which maintains the current behavior). Additionally, it makes the following related enhancements:
- Report the real timeout when the global rate limit is hit
- Handle rate sublimits for individual requests more cleanly
- Remove unnecessary double wait from some rate limit handling code paths
This PR also adds tracking for the number of invalid REST requests (those that result in a 401, 403, or 429 status code) to aid in avoiding the 10k …
> feat(Rest): better handling of global rate limit and invalid request tracking

- src/client/actions/InviteDelete.js
The recent addition of stage channels has brought up a bug in our handling of the `INVITE_DELETE`. We currently only return if both the channel as well as the guild can not be found in the cache, however, according to [upstream documentation
](https://discord.com/developers/docs/topics/gateway#invite-delete) `guild_id?` can be missing.
We should instead return if the channel can not be found, no matter if the guild can be. 
Trivia: came to light, since currently stage channels never enter the cache to begin with, meaning it can never be retrieved here.
- Code changes have been tested against the Discord API, or there …
> fix(InviteDelete): guild can be missing

- src/client/voice/ClientVoiceManager.js
Resolves an issue where bots will hard crash if they are moved from a voice channel into a stage channel. As stage channels are not currently cached by the library, the bot will unrecoverably crash when trying to access the channel.
This fix will cause a voice connection to be disconnected if it is updated with a channel that is not cached.
> fix(Voice): disconnect if voice channel not cached

- typings/index.d.ts
The `Client#disconnect` event was removed in v12 but the typings for it weren't. This PR removes them.
> types: remove typings for Client#disconnect event

- package.json
According to the [contribution guide](https://github.com/discordjs/discord.js-next/blob/master/.github/COMMIT_CONVENTION.md) these three are valid commit message type but the rules still block them. 
> chore: allow three more types of commit msgs

- esm/discord.mjs
- src/index.js
- Add the missing IntegrationApplication structure export to `index.js` (introduced in #4762)
- Add the missing IntegrationApplication structure export to `esm/index.js` (introduced in #4762)
> fix(IntegrationApplication): add missing export to index.js

- src/structures/Guild.js
- typings/index.d.ts
This method has been deprecated in #4103. Also adds a `Vanity` interface.
> refactor(Guild): remove fetchVanityCode()

- src/structures/GuildChannel.js
`GuildChannel#members` currently reads
> A collection of members that can see this channel, mapped by their ID.
- This is not true for `voice` type channels, where it instead reflects the members in the channel (which can differ from members being able to view the channel)
- This does not specify that only cached members are considered (due to it being a convenience wrapper around a `Guild#members` cache filter)
> docs(GuildChannel): #members add cached spec, include voice

- typings/index.d.ts
Adds the missing `username` and `avatarURL` props and removes the `replyTo` prop from `WebhookMessageOptions` interface.
> fix: typings for 'WebhookMessageOptions'

- src/client/voice/receiver/PacketHandler.js
Discord's Chrome client doesn't add a certain undocumented byte to voice packets, this implements a workaround for it that prevents a crash. Fixes #5105.
> fix(Voice): only skip undocumented voice packet byte if present

- src/structures/GuildMember.js
This PR fixes a bug introduced by #4636, `GuildMember#premiumSinceTimestamp` was being set to 0 every time rather than null
> fix(GuildMember): correctly check for premium_since

- src/structures/GuildChannel.js
Currently, `GuildChannel#deletable` will return true regardless if the channel is required for a community (rules, public updates) and will throw a `50074: Cannot delete a channel required for Community guilds`. This PR adds an inequality check between the `GuildChannel#id` and the `Guild#rulesChannelID` or `Guild#publicUpdatesChannelID`
--
**Status**
> fix(GuildChannel): check for community required channels in GuildChannel#deletable

- src/managers/GuildEmojiManager.js
- src/managers/GuildEmojiRoleManager.js
- src/managers/GuildMemberRoleManager.js
- src/structures/Guild.js
- src/structures/GuildMember.js
answers/fixes: #5242
This PR is an extension of #5489 (unlike that PR. this one doesn't add any new parameter) and aims to fix errors that arise due IDs that belong to structures which aren't cached. This happens because the library tries to check for the validity of the resolvable by using `<Manager>#resolve`, this doesn't work in case of the resolvable being uncached. All of this can be fixed by using `<Manager>#resolveID` instead. This way we let the API do the validity test. I've tested **most** of the changes and the errors returned by API do a good job in letting the user know what's wrong.
⚠️ *The only change that I haven't tested belongs to `Guild#addMember` due to it being related to OAuth2. Even though it …
> fix(Resolvables): valid resolvables throw error when uncached

- typings/index.d.ts
CollectionFilter is now generic. All collectors are now properly typed. For example the filter for `channel.awaitMessages` is now `(arg0: Message) => boolean`
PremiumTier is now typed explicitly instead of simply as number
The only case in which these changes are breaking is if the user did something wrong in which case their code would break anyway
> feat(typings): explicitly type PremiumTier and Collectors

- src/structures/MessageMentions.js
- typings/index.d.ts
Change type of channels mentions from TextChannel to GuildChannel.
`MessageMentions#channels` are defined as `Collection<Snowflake, TextChannels>` even though they return `Collection<Snowflake, GuildChannels>`.
> fix(MessageMentions#channels): Fix type of channels of mentions

- typings/index.d.ts
Fixes the typings for `GuildMemberRoleManager` to match the [documentation](https://discord.js.org/#/docs/main/stable/class/GuildMemberRoleManager) and js implementation.
Also removed `OverridableManager` as it is unecessary, it was only used by `GuildMemberRoleManager`.
Ran into this bug myself when trying to call `member.roles.resolve()`, which doesn't exist but existed in the typings because `GuildMemberRoleManager` (indirectly) inherits from `BaseManager`.
> fix(typings): update GuildMemberRoleManager typings to match implementation

- src/structures/GuildTemplate.js
- src/structures/Invite.js
- src/util/DataResolver.js
- typings/index.d.ts
This moves the regular expressions used in the `DataResolver` class to static properties for external use.
> feat: move internal regular expressions to static properties

- src/util/SystemChannelFlags.js
- typings/index.d.ts
As per https://github.com/discordjs/discord-api-types the flag names for system channel flags are inconsistent with the client, this PR aims to streamline this. Additionally, a new Flag for the new "Send helpful tips for server setup" guild setting has been introduced.
> feat(SysChanFlags): new flag and rename in sync with client

- src/structures/GuildAuditLogs.js
- typings/index.d.ts
As per https://github.com/discord/discord-api-docs/pull/1659 `user_id` is nullable, which should accordingly be handled in `GuildAuditLogsEntry#executor`
ℹ️  Note: This is the case when a webhook is deleted using a webhook token rather than a user or bot through a guild.
> fix(GuildAuditLogsEntry): executor can be missing

- src/structures/MessageAttachment.js
- typings/index.d.ts
As per https://github.com/discord/discord-api-docs/pull/2762
> feat(MessageAttachment): support for #contentType

- src/managers/GuildChannelManager.js
- typings/index.d.ts
`news` and `store` were missing from the `options.type` listing.  `stage` will be introduced at a later date
> docs(GuildChannelManager): fix type options in description

- src/structures/Guild.js
- typings/index.d.ts
Removes Guild#owner and adds Guild#fetchOwner
Guild#owner relies on cache, so it is unreliable and will not always work. This is more of an issue now due to intents, as much fewer members are usually cached.
Guild#fetchOwner is a reliable way to get the owner, while still being simple.
This change has been proposed in the d.js server a few times: [1](https://canary.discord.com/channels/222078108977594368/222197033908436994/771448280126586900), [2](https://canary.discord.com/channels/222078108977594368/222197033908436994/797968166588383262), [3](https://canary.discord.com/channels/222078108977594368/682166281826598932/806912661178023968) (paste the msg links into Quick Switcher) …
> feat(Guild): replace `owner` with `fetchOwner`

- src/structures/Message.js
- src/util/Util.js
- typings/index.d.ts
Currently `Util#cleanContent` takes a Message object in addition to the string. All the info accessed from the Message object can also be accessed from the message's channel. This PR makes it take a channel instead.
This is beneficial because now `Util#cleanContent` can be used in other contexts, such as interactions.
> feat(Util): make `cleanContent` take a channel instead of a message

- src/util/Constants.js
Change the default value in the HTTPOptions typedef from `7` to `8`.
> fix(HTTPOptions): change default value in jsdoc to 8

- typings/index.d.ts
Typings are missing the `crosspostable` property on the `Message` class.
> fix: typings for 'Message'

- package-lock.json
- package.json
- typings/index.d.ts
This adds `discord-api-types` as a dev dependency. This way we don't need to keep interfaces of raw data in the declaration file and more imports can be added later if needed.
The imports were renamed from `API...` to `Raw...` to avoid conflicts with the local `APIMessage` class.
> refactor: add discord-api-types as a dependency

- src/structures/VoiceState.js
- In the documentation, `#setRequestToSpeak` and `#setSuppressed` returns `void`
- In the typings and source code, it returns `Promise<void>`
> docs(VoiceState): `#setRequestToSpeak` and `#setSuppressed` returns a `Promise` instead of `void`

- src/util/UserFlags.js
- typings/index.d.ts
> In the next API deploy the system user flag will disappear. None of our clients use it, and it looks to be a mistakenly exposed internal flag value.
<https://github.com/discord/discord-api-docs/issues/2494#issuecomment-816970401>
The `SYSTEM` flag was removed from API docs as of https://github.com/discord/discord-api-docs/commit/9293f0d490ac6acf9d627e429e5a8131b303b528
> chore(UserFlags): remove system flag

- src/structures/Guild.js
- typings/index.d.ts
- `Guild#edit` now allows modification of features (`COMMUNITY`, to enable community features)
- `Guild#edit` now allows the discovery description to be modified
as per https://github.com/discord/discord-api-docs/pull/1764
> feat(Guild): allow description and features in edit

- src/managers/GuildMemberRoleManager.js
fixes: #5555
Sorry for this oversight (see #5495) 🤦‍♂️
The `roleOrRoles` is an array of role IDs instead of roles now. This means the function passed to the `filter` method for creating `newRoles` array should be using `role.id` and not `role`.
> fix(GuildMemberRoleManager): unable to remove roles when passed an array

- src/structures/Webhook.js
- typings/index.d.ts
Webhooks can have a `source_guild` and a `source_channel` as per https://github.com/discord/discord-api-docs/pull/1837
- `owner `user data is fully available, meaning we can always construct a user here, and even cache it
- `source_guild` data is not fully available, by not caching but constructing a Guild instance we can leverage some guild methods (invites use the same approach to construct "partial" guilds - very empty guilds)
- `source_channel` for guilds the bot is not on, only consists of name and id, not enough to construct a channel from, meaning the data object default is required here
**Edit: Object fallbacks are needed for WebhookClient**
- Code changes have been …
> feat(Webhook): sourceGuild, sourceChannel, improve owner

- src/sharding/Shard.js
- src/sharding/ShardClientUtil.js
- src/sharding/ShardingManager.js
- typings/index.d.ts
This refactors the spawn/respawn methods on Sharding classes to use a single, optional object parameter with optional properties, rather than up to three separate optional parameters.
This should make it easier for developers to address the `SHARD_READY_TIMEOUT` issue by providing the `spawnTimeout` without needing to fill the other two optional params. It also renames the `spawnTimeout` parameter to `timeout` for simplicity and ease of use.
> refactor(Sharding): use options objects

- src/structures/Emoji.js
- typings/index.d.ts
Emoji#name can be null when received as reaction emojis, in case of:
1. unavailable custom emojis (based on guild boost level)
2. message history being queried
ℹ️  While technically breaking this should be considered a fix to handle existing API behavior properly.
> fix(Emoji): name can be null

- src/client/websocket/handlers/index.js
This PR removes the try/catch block around requiring event handlers. Before, errors would be silently swallowed, resulting in impacted events unexpectedly not firing. This should only happen due to a bad change or incompatible toolchain (e.g., a bundler that doesn't support dynamic require statements).
Previous change statement:
~**Please describe the changes this PR makes and why it should be merged:**~
~This PR changes how action handlers are loaded. Previously, file paths would be resolved via dynamic …
> refactor: remove error-silencing try/catch on event handler imports

- src/structures/Guild.js
- typings/index.d.ts
- `Guild#setChannelPositions` takes the options `parent` and `lockPermissions` as per https://github.com/discord/discord-api-docs/pull/1776
- This makes the `position` key optional, however is still only a patch level PR, since the old approach (position being mandatory) can still be used, making this non-breaking.
- c732669d49713efa707fe5df9731028f40ffbc2e adds CategoryChannelResolvable for this PR only, #5521 to keep track of and apply the type to the rest of the library
- This PR changes the library's …
> feat(Guild): setChannelPositions parent, lockPermissions keys

- src/structures/Webhook.js
- typings/index.d.ts
Ref: https://github.com/discord/discord-api-docs/pull/2812
~~This PR will be marked as draft until the referenced PR above has been merged.~~
> feat(Webhook): add 'fetchMessage' method

- src/managers/ApplicationCommandManager.js
This PR fixes a typo in the JSDoc usage example of the `ApplicationCommandManager` where `client.commands` was used instead of `client.application.commands`.
> fix(ApplicationCommandManager): fix typo in JSDoc

- src/structures/APIMessage.js
- src/structures/Message.js
- typings/index.d.ts
This adds support for removing attachments from a message.
> feat(Message): allow removing attachments

- src/errors/Messages.js
- src/structures/Message.js
- typings/index.d.ts
This replaces the cache-reliant `Message#referencedMessage` with a more reliable way to resolve the Message
This follows precedent set by #5480 
The method with throw an error if `Message#reference` is null, or if the channel to fetch the message from is not in the client's cache, as is likely to be the case when the message is a crosspost rather than a reply.
This seemed like the best way to handle it without getting into raw APIs calls and partial channels and all that mess.
- I know how to update …
> feat(Message): replace referencedMessage with fetchReference

- src/rest/APIRequest.js
- src/util/Constants.js
- typings/index.d.ts
Adds support for setting ClientOptions#http#headers to an object of headers which will be set on all API requests.
This is useful for using the canary API, setting a global audit log reason, and maybe other stuff in the future
The unrelated typings changes seem to have been automatically done by commit hooks
(commitlint didn't like naming the scope `APIRequest`)
> feat(APIRequest): support setting global headers in HTTPOptions

- src/structures/APIMessage.js
- src/structures/Message.js
- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
Add support for new `fail_if_not_exists` parameter in `message_reference`
ref: https://github.com/discord/discord-api-docs/pull/2572
This also changes the replyTo parameter to be more in line with the API
> refactor(MessageOptions): move replyTo to reply#messageReference and add failIfNotExists

- src/managers/GuildEmojiManager.js
- src/managers/GuildEmojiRoleManager.js
- src/managers/GuildMemberManager.js
- src/managers/GuildMemberRoleManager.js
- src/structures/Guild.js
This PR uses the new error from #5215 to provide more detailed errors when erroring from an Array or Collection.
⚠️ This has not been fully tested
⚠️ This changes some methods to use Promise.reject instead of throw or vice-versa
> refactor(*): return the invalid element when erroring from Array

- src/structures/MessageEmbed.js
This PR adds the MessageEmbedOptions typedef to the docs and updates the MessageEmbed data param to link to this typedef instead of a general object. This has no impact in the code and its purpose it to only improve the docs for MessageEmbed. I went off of the interface found in https://github.com/discordjs/discord.js/blob/master/typings/index.d.ts#L2922 but please let me know if there is anything that needs changing before this is merged.
- This PR **only** includes non-code changes, like changes to …
> docs(MessageEmbed): MessageEmbedOptions typedef

- typings/index.d.ts
#5298 replaced `replyTo` with `reply` in `MessageOptions`. This PR updates typings for `WebhookMessageOptions` to reflect this change.
> typings(WebhookMessageOptions): omit reply instead of replyTo

- src/sharding/ShardingManager.js
- typings/index.d.ts
This PR adds typings for the ShardingManager options parameter, along with adding documentation for the option.
*lets hope github doesn't rebase this again*
> feat(ShardingManager): add options typings

- src/managers/GuildChannelManager.js
- typings/index.d.ts
The `stage` type was missing in the options of `GuildChannelManager.create`.
- This PR **only** includes non-code changes, like changes to documentation, README, etc
> docs(GuildChannelManager): add stage option

- src/errors/Messages.js
- src/structures/MessageEmbed.js
`normalizeField` was made with a custom error to throw, this PR removes that so that a proper API error with path will be thrown instead.  This makes the error message more informative.
> feat(MessageEmbed): remove normalizeField validation

- src/structures/Message.js
This fixes a bug I caused in `Message#react` when I moved the functionality to the manager.
Because emoji resolution was moved, this meant a GuildEmoji object could be passed directly to `Util#parseEmoji`, which would throw as it expected a string.
> fix: resolve emoji in Message#react

- src/structures/CommandInteraction.js
- typings/index.d.ts
This adds a new method `CommandInteraction#followUp` for sending ephemeral followup messages (if the option is provided).
This would not be possible via `CommandInteraction#webhook#send` as regular Webhook messages cannot be ephemeral. The methods should otherwise be equivalent for non-ephemeral messages.
> feat(CommandInteraction): ephemeral followup messages

- src/structures/ApplicationCommand.js
Fixes the returned `ApplicationCommandOption.type` of child-options.
The current output of `options`:
```js
ApplicationCommand.options = [
{
name: 'parent',
description: 'parent description',
type: 'SUB_COMMAND', // <-- Returns the string equivalent of the ApplicationCommandOptionType ✅
options: [
{
name: 'child',
description: 'child description',
type: 6, // <-- Returns the raw API value of the ApplicationCommandOptionType ❌
}
]
}
]
```
The proposed output of `options`:
```js
ApplicationCommand.options = [
{
name: 'parent',
description: 'parent description',
type: 'SUB_COMMAND',
options: [
{
name: 'child',
description: 'child description',
type: 'USER',
}
]
}
]
```
- Code …
> fix(ApplicationCommand): return string equivalent of ApplicationCommandOptionType

- src/structures/GuildAuditLogs.js
> docs: correct casing of `object` -> `Object` in AuditLogChange

- src/structures/CommandInteraction.js
- typings/index.d.ts
Closes: #5629
⚠️This PR is not a direct fix for that issue, see [this](https://github.com/discordjs/discord.js/issues/5629#issuecomment-841115233)
`CommandInteraction#editReply` can take `MessageAttachment` too. This PR updates the typings and docs for it.
> fix(CommandInteraction): update typings and docs for #editReply

- src/errors/Messages.js
- src/managers/ApplicationCommandManager.js
- src/managers/GuildApplicationCommandManager.js
- src/structures/ApplicationCommand.js
- typings/index.d.ts
These endpoints are not available for global commands.
> fix(ApplicationCommandManager): limit permission methods to guilds

- src/util/DataResolver.js
- test/escapeMarkdown.test.js
- test/resolveGuildTemplateCode.js
- test/resolveGuildTemplateCode.test.js
- test/templateCreateGuild.js
> fix(DataResolver): fix circular dependency error with GuildTemplate

- package.json
The project is now using lockfile v2, which is designed for use with npm 7.x and above.
The project documentation currently points to Node 14 being the minimum version, and while this is true for use of the package, Node 14 ships with npm 6 which is not meant for lockfile v2 and so this may cause issues with folks developing on the library itself.
This PR sets the minimum npm version to 7.0.0 to ensure that lockfile v2 is supported.
- This PR **only** includes non-code changes, like changes to documentation, …
> chore: set minimum npm version

- src/structures/CommandInteraction.js
- src/structures/Message.js
- src/structures/Webhook.js
- src/structures/interfaces/TextBasedChannel.js
ℹ️ Preview: https://preview-5632.netlify.app
Currently, `InteractionReplyOptions` extends jsdoc of `WebhookMessageOptions` which results in a slightly wrong documentation as the latter one has some extra fields. The reason @vaporox gave for not making a new typedef from scratch for it was "code duplication". Which is correct because `MessageOptions`, `WebhookMessageOptions`, and `ReplyMessageOptions` all have a lot of common fields and these fields are documented for each of them.
This PR adds a new typedef `BaseMessageOptions` that contains fields that are common among the above typedefs. The above mentioned typedefs now extend this new typedef, making documention correct while keeping the code duplication at …
> docs: add new typedef to properly doc InteractionReplyOptions

- src/structures/Message.js
Currently, `Message#edit` passes `this.channel` as `target` to `APIMessage#create`. This makes `isMessage` false in `APIMessage` as target is a channel in this case and not a message and hence the flags don't get set [here](https://github.com/discordjs/discord.js/blob/ab82cafcde0ee259a32ef14303c1b4a64dea8fae/src/structures/APIMessage.js#L159). This results in a bug where `Message#suppressEmbeds` doesn't do anything. This change was introduced in #5612, I've tested the fix and it works but It would be great if @SpaceEEC can check that I didn't break something else.
Thanks, @toastersticks for noticing the bug 👍 
- Code changes have been tested against the Discord API, or …
> fix(Message): bug in #suppressEmbeds due to #5612

- src/structures/APIMessage.js
- typings/index.d.ts
This PR documents that `Interaction` is a valid `MessageTarget`, which is used as first parameter of `APIMessage.create`.
> fix(APIMessage): document Interaction as valid MessageTarget

- typings/index.d.ts
This PR removes the unused `PermissionOverwriteOptions` interface from `index.d.ts`. There is another interface named `PermissionOverwriteOption` whose jsdoc typedef is `PermissionOverwriteOptions`. So, I renamed this interface to `PermissionOverwriteOptions` so that it matches with the typedef.
This PR is a result of the [convo](https://discord.com/channels/222078108977594368/682166281826598932/844544178179932160) I had with **CheeseBoye** in the support server.
> types(PermissionOverwriteOptions): remove unused interface

- src/structures/Guild.js
- src/util/Constants.js
- typings/index.d.ts
This PR adds the new `nsfw_level` guild property.
Source: [discord-api-docs](https://github.com/discord/discord-api-docs/pull/2976)
> feat(Guild): add the new nsfw_level property

- src/util/Util.js
This PR adds the new Discord color FUCHSIA to the ColorResolvable typedef in the docs as this was missed in #5624. I also moved DARKER_GREY to its place in the Colors export on Constants.js.
> docs(ColorResolvable): Add Fuchsia to ColorResolvable typedef

- typings/index.d.ts
`ApplicationCommandOptionData`'s `options` property should be `ApplicationCommandOptionData` itself to allow the usage of the `ApplicationCommandOptionTypes` enum.
> fix(ApplicationCommandOptionData): options property should be itself

- src/managers/GuildEmojiRoleManager.js
This PR fixes a bug in `GuildEmojiRoleManager#remove`, where it wasn't removing role(s) from the emoji. This bug was a result of an [oversight](https://github.com/ckohen/discord.js/blob/217ea9d162762fa18f4d225c7e99131b0eeaef24/src/managers/GuildEmojiRoleManager.js#L86) in #5314. Since, `#keyArray` is being used there on `this._roles` collection, the `role` is already an ID, doing `role.id` returns `undefined` which results in `newRoles` containing IDs of the roles the emoji already has. This means no filtration happened and Discord got role IDs that were already on the emoji. Therefore, the role a user wants to remove from the emoji doesn't get removed.
ℹ️: Even tho the fix could be done by just changing `role.id` …
> fix(GuildEmojiRoleManager): bug in #remove

- typings/index.d.ts
When using `client.on` with a callback that returns a `Promise`, eslint will then complain if the `no-misused-promises` (from `@typescript-eslint` and various plugins) is enabled, as `Promise<?>` does not match `void`.
By making the return type of the callbacks `unknown`, we can now return any data, including promises. 
> fix(Types): make event listeners accept async callbacks

- src/structures/NewsChannel.js
- src/structures/TextChannel.js
This adds a warning to the docs denoting that setRateLimitPerUser is not available on NewsChannels
> docs(TextChannel): warning about setRateLimitPerUser NewsChannel

- src/client/actions/GuildMemberUpdate.js
- src/client/actions/PresenceUpdate.js
- src/structures/GuildMember.js
Attempt 2!
This is the continuation of #5161 in hopefully a much more accepted fashion.
GMU and PU are currently emitted regardless of the content of the update. Discord also send these events when the underlying user is updated. Since the library abstracts this away into `userUpdate` many PU and GMU events would contain the same exact data in both the old and new objects of their respective events. This simply guards against emitting the event when the objects are identical.
To note: GMU and PU are emitted by discord once for **every** guild the bot shares with a user normally, with this change, you will only get **1** `userUpdate` event, not 1 per guild.
I have not made any docs changes other than documenting …
> cleanup(Client): guard emitting GMU and PU on user updates

- src/structures/PermissionOverwrites.js
This PR fixes a small typo in the typedef jsdoc for PermissionOverwrites
> fix(PermissionOverwrites): fix typo in typedef jsdoc

- .github/workflows/publish-dev.yml
This removes the somewhat-hacky-looking regex and uses `jq` instead to parse the `package.json` file.
Tested the output with WSL:
Also tested in a private repo to validate the command in GitHub actions:
---
Original description:
~~While not strictly required in [Semantic Versioning rule 9](semver.org/#spec-item-9), based on their examples it seems strongly recommended to first add a hyphenated specification for pre-releases, ergo I added `-dev` before the Git SHA.~~
~~The addition of `--short=7` strips the Git SHA to the first 7 characters, which are the same as you would see when browsing commits on GitHub, making it a bit easier to match versions to their respective Git commit. AFAIK the first 7 characters are …
> ci(publish-dev): improve resolving of next version

- src/client/actions/TypingStart.js
- src/client/websocket/handlers/CHANNEL_PINS_UPDATE.js
- typings/index.d.ts
Below guard fails on `channelUpdate` client events, however works flawlessly on `channelDelete`. By adapting the typings to `DMChannel | GuildChannel` the types are much easier guardable but still encompass all channel types.
```ts
if (channel instanceof DMChannel || !channel.isText()) return;
```
> feat: easier guards for channelUpdate

- src/structures/Webhook.js
- typings/index.d.ts
Discord.js supports editing attachments for Webhooks but it isn't properly documented. As discussed in #5630, this PR adds documentation for this and also updates some jsdoc links to keep up with the changes made in #5632
> docs(Webhook): update typings and docs for #editMessage

- src/managers/MessageManager.js
- src/structures/Message.js
- typings/index.d.ts
This PR adds the ability to edit in new files to regular bot messages.
I changed the wording of the `attachments` option to remove the "can only remove" part to avoid confusion.
Relevant docs PR: https://github.com/discord/discord-api-docs/pull/2859
> feat(Message): allow editing files into messages

- typings/index.d.ts
This re-exports discord-api-types Snowflake type so it can be imported from discord.js directly.
This will help improve the user experience for Typescript developers encountering the `${bigint}` type.
> types(Snowflake): export the type

- esm/discord.mjs
- src/errors/Messages.js
- src/index.js
- src/structures/APIMessage.js
- src/structures/Message.js
- src/structures/MessageEmbed.js
- src/structures/Webhook.js
- src/structures/interfaces/TextBasedChannel.js
- src/util/Util.js
- test/sendtest.js
- test/voice.js
- test/webhooktest.js
- typings/index.d.ts
- typings/index.ts
This PR removes StringResolvable (which was just a nice naming scheme for "any" anyways) and enforces and tests for strings to be passed where before any could be resolved to strings.
We have a lot of issues in support regarding people wondering why certain parts of a message or embed may show "undefined" or "null" due to unexpectedly resolving them to strings ([despite it being documented](https://discord.js.org/#/docs/main/stable/typedef/StringResolvable), as space has pointed out).
This is majorly opinionated and I personally believe we should hand the responsibility of providing message content as a string (and how it might be composed from the respective structures) up to the developer. While I do see that …
> feat(*): enforce strings

- src/managers/GuildEmojiRoleManager.js
- src/managers/GuildMemberRoleManager.js
This PR removes the `_roles` getter from the `GuildEmojiRoleManager` and `GuildMemberRoleManager` classes because they return the same value as their public `cache` equivalent.
- This PR includes breaking changes, however only to internal parts of the library
> refactor: remove _roles from pseudo-managers

- typings/index.d.ts
This PR tries to fix the issue caused by re-export of `Snowflake` in #5722. The re-export of Snowflake made all the interfaces and types of discord.js non-importable. I tried to find a correct way of re-exporting types in a declaration file but couldn't find anything that helped. So, instead of importing the `Snowflake` type from `discord-api-types`, I defined the type in the lib itself just like other types. This kept the typings support that `Snowflake` introduced while also made it and other types importable again.
Thanks, @ToasterSticks for noticing a issue...again 😆
> fix: interfaces not importing due to re-export of Snowflake

- src/managers/GuildMemberManager.js
This will allow moving members to channels with type `stage`. Closes #5673 🙂 
> fix(GuildMemberManager): allow moving members to any non-text channel

- src/structures/CommandInteraction.js
- typings/index.d.ts
This PR change the Channel type from `CommandInteraction` to `TextChannel`, `DMChannel`, and `NewsChannel` because Slash Commands can't be used in another channel type than text
> fix(CommandInteraction): channel type should be text based channels

- src/structures/CommandInteraction.js
- typings/index.d.ts
Currently, `CommandInteraction#options` is an Array. This PR changes it to a Collection. As [discussed](https://discord.com/channels/222078108977594368/682166281826598932/848333889986101269) in the support server, `options` of a `CommandInteraction` have unique names. Thus, having a Collection with names as keys is much better than using an array in this case.
- This PR includes breaking changes (methods removed or renamed, parameters moved …
> feat(CommandInteraction): make options a collection

- src/structures/CommandInteraction.js
- typings/index.d.ts
*cough* So, I totally forgot about slash cmds with no options in #5705. The `options` param in `CommandInteraction#_createOptionsCollection` would be `undefined` for such cmds and thus iterating over it will throw error. This PR fixes the issue by returning an empty collection when `options` is undefined. I did think of making `CommandInteraction#options` null at first:
```js
this.options = data.data?.options ? this._createOptionsCollection(data.data.options, data.data.resolved) : null;
```
but then I saw that before #5705, it was set to an empty array for cmds that have no options, so I went with the empty collection fix.
- Code changes have been tested against the Discord …
> fix(CommandInteraction): cmds with no options throw error

- src/rest/DiscordAPIError.js
- src/rest/HTTPError.js
- src/rest/RequestHandler.js
- src/structures/APIMessage.js
Now you know what Discord means by your embed being wrong... or that color being invalid...Or just in general what we sent that caused the error you received
- Above is a stretch, because this is internals
> feat(Rest): show the data that is sent to Discord when an errors occurs 

- README.md
This changes the color of the Discord.js server invite badge to match the new hex of 5865F2, instead of the former light blurple. 
> chore: update the color of the discord.js server badge

- src/client/websocket/WebSocketShard.js
This PR adds the used intents to the debug output emitted whenever a shard sends an identify.
This will help debugging (or ruling out) issues caused by missing intents.
> debug(WebSocketShard): emit intents used in identify

- src/structures/Message.js
- typings/index.d.ts
This PR fixes the following:
1. The jsdoc of `Message#edit` doesn't show `content` can be null
2. `Message#edit` can take `MessageAttachment` or array of it in `options`
3. The `content` field in `MesssageEditOptions` can be null
4. The jsdoc of `MessageEditOptions` doesn't show `content` can be null
Thanks X 3, @ToasterSticks for noticing this issue too 👍 
> fix(Message): update typings and docs related to #edit

- src/structures/Message.js
So, turns out `?` (nullable) does work for `@param` tag in jsdoc but if the param can be of more than one type (excluding null) we have to wrap them in parentheses. This time I made sure to test how it will look in docs. This is how it will render valid types for `content` now:
also: *docs preview for PRs when :(*
> docs(Message): fix content param in #edit not showing as nullable

- src/managers/RoleManager.js
`if (permissions)` is really bad idea, because somehow passing `0n` or **falsy value**. it will be directly passed to api
That resulting an error: `TypeError: Do not know how to serialize a BigInt`
```js
RoleManager#create({
name: 'role-name',
permissions: 0n
}) // -> TypeError: Do not know how to serialize a BigInt
```
* Typings don't need updating
> fix(RoleManager): bug in #create

- typings/index.d.ts
Fixes a bug in the typings where MessageComponentInteractionCollector didn't pass type to the base Collector correctly.
> types: extend MessageComponentInteractionCollector correctly

- typings/index.d.ts
This PR fixes #5759 by specifying that `MessageComponentInteraction#defer` optionally accepts a `InteractionDeferOptions`.
> fix(MessageComponentInteraction): correctly type defer method

- src/structures/Webhook.js
This PR fixes a bug in `Webhook#editMessage` where it throws an error when the `content` param is `null`, even tho discord.js supports it as a way to remove content on edits. It also documents that `content` can be `null` in `Webhook#editMessage`. The typings already support `null` as a valid type for `content` so it doesn't need any change.
> fix(Webhook): #editMessage throws error when content is null

- src/util/Constants.js
- typings/index.d.ts
This fixes #5751 as well as a bug in two typedefs that had their possible types listed incorrectly.
Decided to make this smaller PR to fix that issue as it can be quite annoying for users that are just now starting to try MessageComponents to have to wait for #5692 to be merged, as this will clearly take a while
> fix(Interaction): add missing types and fix docs lists

- src/client/WebhookClient.js
- src/index.js
- src/structures/APIMessage.js
- src/structures/CommandInteraction.js
- src/structures/InteractionWebhook.js
- src/structures/MessageComponentInteraction.js
- src/structures/Webhook.js
- src/structures/interfaces/InteractionResponses.js
- typings/index.d.ts
Currently, interactions create a `WebhookClient` for handling additional response to the interaction. This works great, except for a few places, such as `InteractionResponses#followUp` which has to be done without the `WebhookClient` due to `APIMessage` not resolving ephemeral as a valid option.
This PR creates an `InteractionWebhook`, which allows `APIMessage` to resolve `isInteraction` more accurately and allows the removal of the inapplicable methods.
Since this PR is touching all of the webhook handling, I have also added the empty functions to the bottom of `WebhookClient` to allow them to be documented properly.
~~⚠️ The base for this PR is #5674 as it refactors interactions quite a bit, this will be rebased …
> feat(Interactions): add InteractionWebhook for better internals

- src/structures/Message.js
- src/structures/Webhook.js
- src/structures/interfaces/TextBasedChannel.js
Adds the docstring for the `components` prop to `BaseMessageOptions`, `MessageEditOptions` and `WebhookEditMessageOptions`
> fix: add components to MessageOption typedefs

- src/structures/interfaces/InteractionResponses.js
The `InteractionDeferOptions` isn't showing up in the docs because it got a little wrong when it was moved in #5674. This PR fixes it by correctly defining this typedef.
> docs(InteractionDeferOptions): correctly define the typedef

- src/client/Client.js
- src/structures/Invite.js
Make use of the new `with_expiration` query option in Client#fetchInvite as per https://github.com/discord/discord-api-docs/pull/2858#event-4665641335
- leave fallback via age when not fetching via Client
> feat(Client): make use of with_expiration in #fetchInvite

- src/structures/Message.js
- typings/index.d.ts
- Provide application id for the application of the interaction that sent the response, if applicable - as per <https://github.com/discord/discord-api-docs/pull/2908>
-⚠ rename `application` to not conflict with the new `applicationID` parameter in `#toJSON` transformation
> feat(Message): applicationID for interaction responses

- src/sharding/ShardClientUtil.js
When a Error happens during sending, it can not overwrite err.message. So that a error happens: "TypeError: Cannot set property message of  which has only a getter"
The Error can be reproduced with having the Sharding Manager on Worker Mode and than broadcastEvaling `this.guilds.cache`,
the upper scenario works fine for child processes, bc they support many types, but worker threads does not support functions and some other types. So a error comes:  `DOMException [DataCloneError]: #<Object> could not be cloned.`
This Error can just be logged out when you merge the commit, bc there is a error itself on the _respond function, which should be fixed with the commit. I checked it, multiply times...
**Status and …
> fix(ShardingManager): client error event cannot be emitted

- src/client/websocket/WebSocketManager.js
- src/errors/Messages.js
- src/managers/GuildApplicationCommandManager.js
- src/managers/GuildBanManager.js
- src/sharding/ShardClientUtil.js
- src/structures/Invite.js
- src/structures/interfaces/InteractionResponses.js
Since, custom errors have same names as native errors, they get left un-imported sometimes. Which results in errors that don't have any message in it. This PR fixes it by importing these errors in places where they are being used but were not imported.
> fix(*): add missing imports for custom errors

- src/client/websocket/handlers/INTERACTION_CREATE.js
This PR moves two instances of a `Structures` import out of the `switch (data.type)` block in `INTERACTION_CREATE`, where they are assigned via unnecessary conditionals.
> refactor(Interactions): move Structures import out of switch block

- src/structures/CommandInteraction.js
- typings/index.d.ts
`CommandInteraction#channelID` is always type of `Snowflake` as Discord always sends this data.
Indirectly fixes inconsistency with `CommandInteraction#channel` always being type of `TextChannel | NewsChannel | DMChannel`.
> docs: CommandInteraction#channelID is type of Snowflake

- src/errors/Messages.js
- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
Putting this one up here for discussion.
Conceptually, I don't think collecting multiple interactions with the promisified `Message#awaitMessageComponentInteractions` made any sense, since all interactions need to be responded to within 3 seconds.
Instead, I've modified the function to singular, taking only a `time` option (in addition to the filter).
The Promise resolves to a `MessageComponentInteraction` if one passes the filter, or rejects if the time runs out.
> feat: promisified single interaction collection

- src/client/Client.js
- src/index.js
- src/rest/RateLimitError.js
- src/rest/RequestHandler.js
- src/util/Constants.js
- typings/index.d.ts
Adds new client option disableRateLimitQueue which takes either an array of routes or `(ratelimitData) => boolean`.
If a rate limit is hit, the RequestHandler first checks whether this rate limit should be thrown (route starts with one of the array values / function returns true) and if so throws an error instead of queueing the request
This closes https://github.com/discordjs/discord.js/issues/5449
> feat(Rest): optional ratelimit errors

- src/structures/DMChannel.js
- src/structures/Message.js
- src/structures/TextChannel.js
- src/structures/interfaces/TextBasedChannel.js
This changes `Message#awaitMessageComponentInteraction` to only collect one interaction, similar to how it was changed for TextBasedChannel in #5770. It also fixes a bug where `TextBasedChannel#applyToClass` would throw with `TypeError: Property description must be an object: undefined` because the method name wasn't updated there.
> fix: remove remnants of awaitMessageComponentInteractions

- src/structures/APIMessage.js
- src/structures/InteractionWebhook.js
- src/structures/Message.js
- src/structures/Webhook.js
- src/structures/interfaces/InteractionResponses.js
- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
- typings/index.ts
This PR refactors the methods across the the lib's sending/editing methods to avoid inconsistent overloads by removing multiple param options and enforcing single param usage as laid out in #5771.
(and let's pretend that there isn't a typo in the branch name)
- I pretend to know how to update typings and have done so, or typings don't need updating
> refactor: enforce single param on sending/editing methods

- src/managers/GuildBanManager.js
- src/managers/GuildMemberManager.js
The docs for `GuildMemberManager#search()` are using `@property` instead of `@param`, causing it to not show up on the docs site. To fix this, new typedefs have been added to be more consistent with the typings.
> docs(GuildMemberManager): fix docs for #search()

- src/client/websocket/handlers/INTERACTION_CREATE.js
- src/index.js
- src/structures/APIMessage.js
- src/structures/BaseMessageComponent.js
- src/structures/ButtonInteraction.js
- src/structures/Emoji.js
- src/structures/Interaction.js
- src/structures/Message.js
- src/structures/MessageActionRow.js
- src/structures/MessageButton.js
- src/structures/MessageComponentInteraction.js
- src/structures/MessageComponentInteractionCollector.js
- src/structures/Webhook.js
- src/structures/interfaces/InteractionResponses.js
- src/structures/interfaces/TextBasedChannel.js
- src/util/Structures.js
- src/util/Util.js
- typings/index.d.ts
By request, this PR extract several of the general improvements I had discovered while working on #5692 into a separate PR.
- Subclasses for `MessageComponentInteraction` per component type
- Support for parsing arrays of components as rows in raw options
- Improved raw emoji resolution in component builders
- Typings fixes
- Documentation improvements and consistency
> feat: general component improvements

- src/errors/Messages.js
- src/sharding/Shard.js
- src/sharding/ShardClientUtil.js
- src/sharding/ShardingManager.js
- typings/index.d.ts
This allows developers to write safer eval code by allowing them to pass functions and contexts to `broadcastEval` in both `ShardClientUtil` and `ShardingManager`.
This avoids directly injecting malicious code into your eval scripts. Instead, you can treat your functions as templates (which you can make sure are safe) which are then injected with a context later on.
For example, the following code is vulnerable (taken and adapted from https://github.com/oadpoaw/discordjs-bot-rce). It's important to recognise that this isn't a security issue with discord.js -- using eval is inherently dangerous, and this is the clearest case of passing unsanitised input to eval.
```js
function findUser(userId) {
return …
```
> feat(Sharding*): contexts for broadcastEval

- src/structures/APIMessage.js
#5758 Introduced a small bug with throwing on invalid content, this fixes that.
> fix(ApiMessage): only pass objects as options directly

- src/structures/GuildAuditLogs.js
Currently, for logs related to `CHANNEL_*` events, `GuildAuditLogsEntry#target` is an object containing only the id of the related channel. This PR turns this `target` prop into a channel using the data in the `changes` object. There are also some documentation related changes. 
> feat(GuildAuditLogs): make #target a channel for channel related logs

- src/managers/GuildManager.js
- src/structures/Guild.js
- typings/index.d.ts
Remove guild based region from guild data, methods and associated manager as per <https://github.com/discord/discord-api-docs/pull/3001> (guild based regions are no longer settable through the client and equal a noop in v8, will have to be removed with v9 so we might as well go ahead and do so prior)
⚠️ by nature of removal this is a breaking change
> refactor(Guild): remove region from guild and manager methods

- src/util/BitField.js
Currently `BitField#missing` assumes the passed bits are, if an array, an array of strings, this is not necessarily correct.
For example
```js
const missing = new Permissions([Permissions.FLAGS.SEND_MESSAGES, Permissions.FLAGS.VIEW_CHANNEL])
.missing([Permissions.FLAGS.VIEW_CHANNEL, Permissions.FLAGS.BAN_MEMBERS]);
console.log(missing); // [ 4n ] instead of [ "BAN_MEMBERS" ]
```
This PR ensures that `BitField#missing` always returns an array of strings.
> fix(BitField): ensure missing returns an array of strings

- src/structures/ClientPresence.js
- src/structures/ClientUser.js
This PR resolves #5706 and resolves #5584.
The [Gateway Presence Update Structure](https://discord.com/developers/docs/topics/gateway#update-presence-gateway-presence-update-structure)'s activities array is documented to not be nullable.
So this PR defaults it to an empty array then.
Also as noted for the [Activity Structure](https://discord.com/developers/docs/topics/gateway#activity-object-activity-structure), bots may only send `name`, `type` and optionally `url`.
So this PR maps previously set activities to only have those properties left (defaulting url to undefined since sending `null` invalidates your session too, albeit being documented as nullable).
- Code changes …
> fix(ClientPresence): produce valid activities for set presences

- src/client/Client.js
- src/errors/Messages.js
- src/structures/Webhook.js
Since Discord started sending application their own webhook's token again, #5731 is somewhat resolved.
This PR does the rest to resolve #5731.
- Use the optionally supplied token to `Client#fetchWebhook` if Discord did not include it in the payload. (i.e. fetching another application's webhook by id and token)
- Document when tokens are missing.
- Throw a more helpful error when trying to execute a message-related action on a webhook without a token.
- This PR includes breaking changes (methods removed or …
> fix(Webhook): throw an error if no token is available when it's required

- src/rest/RequestHandler.js
This PR adds more info into the string that gets emitted when a request gets a 429 response.
Being added is:
- Whether the rate limit is global
- The HTTP method / verb
- The path of the request
- The limit the rate limit bucket has
- The timeout to wait for
- Whether this is a sublimit (and if so, how long to wait)
I kept it similar to how the WebSocket emits debug events, since putting all of that into one line wasn't feasible:
https://github.com/discordjs/discord.js/blob/a1f763ee75a7d906bbe727f616e33206dcc6792c/src/client/websocket/WebSocketShard.js#L243-L247
- I know how to update …
> feat(RequestHandler): emit more info when a rate limit was hit

- src/structures/GuildChannel.js
This PR resolves #5553 by spreading the clone options instead of using `Util.mergeDefault`.
> fix(GuildChannel): spread clone options to avoid infinite recursion

- src/structures/Guild.js
- src/util/Constants.js
- typings/index.d.ts
Currently, `mfaLevel` prop of `Guild` gets set to the raw data sent by the API. This PR adds an `MFALevels` enum to make `Guild#mfaLevel` a bit more meaningful and not just a number.
> feat(Guild): add enum for mfa_level

- src/structures/GuildChannel.js
- src/structures/StageChannel.js
- src/structures/StoreChannel.js
- src/structures/TextChannel.js
- src/structures/User.js
This PR resolves #5605 by only updating properties of Channel and subclasses when they are in the payload.
In similar vein, if a user option was used, their last message properties would reset to null. Since this is something we provide on our own, there is no reason for those to be in `_patch`.
> fix: don't patch missing properties from partial payloads

- src/client/websocket/WebSocketShard.js
This PR fixes a bug that causes errors thrown in `WebSocketManager`'s event handlers to be caught and emitted as shard error.
This PR does the same with some other unmentioned event which resolves #4987.
> fix(WebSocketShard): don't catch errors thrown in event handlers

- README.md
- Restores the installation command, previously removed in #5402.
- Removes the peer dependencies warning, as discord.js does not longer have them.
- Removes the voice-related libraries, as they moved to `discordjs/voice`.
> docs(README): re-add install command, remove voice remnants

- typings/index.d.ts
In #4879 BitFields were updated to support other value types such as BigInts, however some of the typings weren't updated accordingly.
Reference: https://github.com/discordjs/discord.js/blob/f5f3f772865ee98bbb44df938e0e71f9f8865c10/src/util/BitField.js#L117-L123
> fix(Typings): Fix BitField toJSON/valueOf return types

- src/structures/APIMessage.js
- src/structures/MessageEmbed.js
- typings/index.d.ts
- typings/index.ts
Attaching files to MessageEmbeds doesn't do more than just adding them to the message options for the user. Especially with the changes in #5758, this has become less convenient than before, to the point where you could just pass the files directly with the message options.
It also fixes a "bug" where TypeScript lets you use `.send(<MessageEmbed>)` because MessageEmbed and InteractionReplyOptions both have a `files` property, however this is misleading because it doesn't actually send the full embed.
> refactor(MessageEmbed): remove files

- src/structures/Webhook.js
- src/structures/interfaces/TextBasedChannel.js
Previously, replying to a message (or passing an APIMessage to a `TextBasedChannel#send`) with `split` enabled threw a `DiscordAPIError: Invalid Form Body`.
Example: 
```js
message.reply({ content: '<message content>', split: true });
```
Error:
```
DiscordAPIError: Invalid Form Body
content: Could not interpret "['```\n<message content>\n```']" as string.
```
> fix(TextBasedChannel): allow passing an APIMessage with split

- src/structures/GuildChannel.js
This PR modifies `GuildChannel#memberPermissions` and `GuildChannel#rolePermissions` to use `Permissions.defaultBit` over the literal `0n`.
I don't think there are any other instances of us using a default bit as a literal.
> refactor(GuildChannel): use Permissions.defaultBit over 0n

- src/structures/Guild.js
- src/structures/GuildPreview.js
- src/structures/PartialGroupDMChannel.js
- src/structures/Presence.js
- src/structures/Team.js
- src/structures/TextChannel.js
- src/structures/Webhook.js
- src/structures/interfaces/Application.js
- src/util/Constants.js
- typings/index.d.ts
While working on #5785, I found some inconsistencies between typedefs and typings of options for editing/creating webhook and fetching image. For eg, the typings for `Webhook#edit` show that it takes only a single param, whereas in code it takes an object as first param and `reason` as second. Similarly, the `ImageURLOptions` typedef is used for even those methods that don't support/use `dynamic` param at all. This PR fixes all these inconsistencies by adding new typedefs and interfaces for these options.  
- This PR includes breaking changes ( just one 😺)
> fix(*): typedefs and typings for image & webhook options

- src/errors/Messages.js
- src/managers/ApplicationCommandManager.js
- src/managers/GuildApplicationCommandManager.js
- src/structures/ApplicationCommand.js
- typings/index.d.ts
The way the library currently handles global and guild application commands is via a manager that exists on the application or guild respectively. This poses a problem for applications that have guilds authorized only with `applications.commands` as the guild is not cached and therefore does not have a guild application command manager.
This PR addresses this issue by allowing the global application command manger to take `guildID` in all of its methods. It also moves the permissions methods from `GuildApplicationCommandManager` to `ApplicationCommandManager` for the same reason.
It also introduces a new typedef that will be used in an upcoming PR for more consistency in managers. 🚀 
-  Application Commands fetched …
> fix(ApplicationCommands): allow managing commands for uncached guilds

- src/structures/GuildChannel.js
Fixes #5819 by handling the edge case where there is an empty overwrite present on a channel and simply not present on the parent, or vice-versa.
(I should note that this fix only worked when I was actively fetching channel parents on each channel update from the API, but I think that's just a side-effect/requirement of the channels partial now)
> fix(GuildChannel): improve empty overwrite handling for permissionsLocked

- src/structures/APIMessage.js
- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
- typings/index.ts
The message create endpoint now supports up to 10 embeds just like the webhook endpoint, these changes reflect that addition within the typings and APIMessage#create function.
> feat(*): document and support embeds field in message create endpoint

- src/structures/GuildChannel.js
In #5796 a change was made that forced `parentID` to be null and `permissionOverwrites` to be an empty collection on all GuildChannels when they are created. This PR changes that logic to only apply those defaults if they're not set by the initial patch during the super call.
This should resolve the issue of channels firing an update event with parentID changing when they're patched by an event for the first time since the client starts.
Kudos to [muchnameless](https://discord.com/channels/222078108977594368/682166281826598932/853036819264569364) for spotting this before I could.
- I know …
> fix(GuildChannel): don't force parentID/permissionOverwrites to empty on create

- src/managers/GuildManager.js
This PR fixes a bug in `GuildManager#create` where it throws error if the optional `systemChannelFlags` param isn't provided. This happens because the method calls `SystemChannelFlags#resolve` without checking whether `systemChannelFlags` is defined or not. Since, it's an optional param, it can be undefined sometimes and passing undefined param to `SystemChannelFlags#resolve` always throws error.
> fix(GuildManager): #create throws when systemChannelFlags is undefined

- typings/index.d.ts
`MessageComponentInteraction#update()` was incorrectly typed as returning `Promise<Message | RawMessage>`.
> types(MessageComponentInteraction): update should return Promise<void>

- src/structures/APIMessage.js
This removes unused declarations that were falsely added back during a rebase in #5792.
> refactor(APIMessage): remove unused declarations

- src/structures/BaseGuildEmoji.js
- src/structures/GuildEmoji.js
- src/structures/GuildPreviewEmoji.js
- typings/index.d.ts
This PR changes the type of `GuildPreviewEmoji#roles` from `Set<Snowflake>` to `Snowflake[]` because pretty much no other getter/method returns a set.
> refactor(GuildPreviewEmoji): make roles an array

- typings/index.d.ts
I have updated a certain `fetchPermissions()` overload with command ~~set as optional~~ removed so typescript won't complain when the method is called without parameters.
~~Also, included null type to `command`~~ removed too, no use case for it
> types(GuildApplicationCommandManager): allow undefined command

- src/structures/ApplicationCommand.js
- typings/index.d.ts
The data sent by Discord for the `required` field in ApplicationCommandOption is undefined if the option is not required. This PR fixes this so that it defaults to false instead to make it easier to compare with local commands for command updaters.
> fix(ApplicationCommand): default option.required to false

- src/structures/Guild.js
- typings/index.d.ts
This fixes a couple of issues introduced in #5507 where not providing a parent to `Guild#setChannelPositions` would resolve to `null`, clearing the parent instead of leaving it unchanged.
This also prevented the method from being used to set more than one channel position, due to `DiscordAPIError: Only one channel can have a parent_id modified at a time`.
Additionally, the typings are updated to accept `null` in order to move the channel out of the parent category.
> fix(Guild): setChannelPositions null parenting

- src/managers/GuildBanManager.js
- src/managers/GuildChannelManager.js
- src/managers/GuildEmojiManager.js
- src/managers/GuildManager.js
- src/managers/GuildMemberManager.js
- src/managers/ReactionUserManager.js
- src/managers/RoleManager.js
- src/rest/RequestHandler.js
- src/sharding/Shard.js
- src/sharding/ShardClientUtil.js
- src/sharding/ShardingManager.js
- src/structures/CategoryChannel.js
- src/structures/Guild.js
- src/structures/GuildChannel.js
- src/structures/GuildMember.js
- src/structures/GuildTemplate.js
- src/structures/MessageComponentInteractionCollector.js
- src/structures/MessageMentions.js
- src/structures/ReactionCollector.js
- src/structures/Role.js
- src/structures/interfaces/Collector.js
- src/util/Util.js
- typings/index.d.ts
This PR starts the work of creating typedefs for `options` params of all the methods that don't have one. I've created a few so far but there are still few more to add. Since, #5784 added some new typedefs too, I'll rebase this PR once that one is merged to remove duplicate changes. This PR also tries to add more helpful description of a property in places where the old one is a little vague.
ℹ️ The names for the new typedefs are taken from their respective interfaces in the typings.
> refactor(*): make typedefs for all options params

- src/structures/ApplicationCommand.js
#5838 introduced a bug that made it impossible to set the required option to `true` due to operator precedence, this PR fixes that
> fix(ApplicationCommand): default option.required fix

- src/client/actions/Action.js
- src/client/actions/ActionsManager.js
- src/client/actions/StageInstanceCreate.js
- src/client/actions/StageInstanceDelete.js
- src/client/actions/StageInstanceUpdate.js
- src/client/websocket/handlers/STAGE_INSTANCE_CREATE.js
- src/client/websocket/handlers/STAGE_INSTANCE_DELETE.js
- src/client/websocket/handlers/STAGE_INSTANCE_UPDATE.js
- src/errors/Messages.js
- src/managers/StageInstanceManager.js
- src/structures/Guild.js
- src/structures/GuildAuditLogs.js
- src/structures/StageChannel.js
- src/structures/StageInstance.js
- src/util/Constants.js
- src/util/Structures.js
- typings/index.d.ts
This PR starts the work of adding support for Stage Intances. Since, this PR isn't complete yet and a few PRs related to stage instances are still open in `discord-api-docs` ([3060](https://github.com/discord/discord-api-docs/pull/3060) & [2998](https://github.com/discord/discord-api-docs/pull/2998)), I'll keep this as a draft for now.
> feat: stage instances

- src/structures/ClientApplication.js
- src/structures/IntegrationApplication.js
- src/structures/interfaces/Application.js
Hi, small pull request!
I found a lil' typo in the `Application` interface ("Gets the clients rich presence assets.") so I decided to correct it by adding in the apostrophe. But then I noticed that the documentation doesn't use "client" anywhere else on the page, so I renamed it to "application's". Then I decided to change the inconsistent "app" vs. "application" in the `Application` files! Hope that's alright.
> docs: Consistent application name usage

- src/errors/Messages.js
- src/structures/Message.js
- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
This reverts the change to the second parameter of `<Message|TextBasedChannel>#awaitMessageComponentInteraction` back to being an options object, rather than a single `time` param. This maintains consistency with the other promisified collectors in the library.
The error message returned has also been slightly reworked just in case, even though I'm pretty sure "time" is the only reason it could end without collecting.
> refactor(awaitMessageComponentInteraction): use options object for lib consistency

- src/structures/Message.js
Since edited_timestamp is always present in the message data from Discord (see https://discord.com/developers/docs/resources/channel#message-object), the editedTimestamp property for messages that have never been edited would be 0. This fixes that so that it's null when it hasn't been edited, and the timestamp for edited messages, just like the data from Discord.
> fix(Message): editedTimestamp defaulting to 0

- src/managers/GuildManager.js
- src/structures/ClientPresence.js
- src/structures/Guild.js
- src/structures/Presence.js
- src/structures/Sticker.js
- src/structures/TeamMember.js
- src/structures/Webhook.js
- src/util/Constants.js
- typings/index.d.ts
Okay, there are a lot of related changes here:
1) Use enums instead of arrays. This brings consistency and speed (`indexOf` is slow).
2) Some enums (that were arrays earlier) had same name for the enums themselves and the type of elements they hold.
3) `WebhookTypes` enum (ex-array) was missing from typings for `Constants`
4) Some methods that used arrays as enums earlier wouldn't let user to pass `number` type.
5) `DefaultMessageNotifcations` is now `DefaultMessageNotificationLevels` to keep the naming consistent with other enums in djs (discord uses 'level' in the name for enums in documentaion).
6) `DefaultMessageNotifcations` types were not same as what the api has documented ( eg. `ALL` instead of …
> feat(*): use enums for consistency and speed

- package.json
This PR removes the last mention of the `/docs/examples` folder, as it not longer exists.
> refactor(Package): remove `runkitExampleFilename`

- typings/index.d.ts
The change from string to Snowflake removed a valid case where string was a correct type (unicode emojis for `MessageReactionResolvable`). This adds the type back.
> types(MessageReactionResolvable): add string

- src/structures/Guild.js
- src/util/Constants.js
- typings/index.d.ts
This PR adds `PremiumTiers` enum for `Guild#premiumTier` because *unknown numbers bad, words good* + (consistency) 😸
> feat(Guild): add enum for premium_tier

- src/structures/Invite.js
- src/structures/InviteStageInstance.js
- src/structures/StageInstanceInvite.js
- typings/index.d.ts
This PR starts the work of adding support for `stage_instance` field in the invite object. 
> feat: stage instance invite

- src/structures/Message.js
- Removed `ReplyMessageOptions#embed` to match typings
> docs(ReplyMessageOptions,MessageEditOptions): replaced `embed` with `embeds`

- src/structures/VoiceState.js
The docs does not show that VoiceState#channel can be null
This should fix the issue
> docs(VoiceState): channel can be null

- src/managers/BaseGuildEmojiManager.js
- src/managers/ChannelManager.js
- src/structures/AnonymousGuild.js
- src/structures/BaseGuild.js
- src/structures/Channel.js
- src/structures/Emoji.js
- src/structures/Guild.js
- src/structures/Invite.js
- src/structures/InviteGuild.js
- src/structures/WelcomeChannel.js
- src/structures/WelcomeScreen.js
- typings/index.d.ts
Implement `Guild#fetchWelcomeScreen`, `Guild#editWelcomeScreen`, add welcome screen data to invites retrieved via invite fetching (`Client#fetchInvite`) as per:
- https://github.com/discord/discord-api-docs/pull/1636
- https://github.com/discord/discord-api-docs/pull/2398
**Notes:**
- *(reverted)* ~~QoL change for `BaseGuildEmojiManager` to accept the `<:name:id>` and `name:id` syntax in resolve* methods~~ 
- ⚠️  Due to the nature of the emoji data we receive, this requires for Emoji#animated to potentially return null, making this a semver major PR. (upstream issue see below, not too much hope on that happening, though)
- ⚠  Changing the return value of Invite#guild (major)
- implement "enabled" via getter from …
> feat(WelcomeScreen): welcome screens

- src/structures/Presence.js
Add support for firing presence update events when the only thing that changes is an activity's state or details.
Fixes https://github.com/discordjs/discord.js/issues/5845
> fix(presenceUpdate): fire when only state/details change on an activity

- src/structures/AnonymousGuild.js
- src/structures/Guild.js
- typings/index.d.ts
When `_patch` gets called by `super()` the instance properties created after the super call don't exist yet...causing hard crashes.
fixes #5884
> fix(Guild): don't patch before instance properties

- src/structures/AnonymousGuild.js
Master docs currently does not show properties Guild#name nor Guild#id (and possibly others). This should fix it :)
> docs(AnonymousGuild): add missing extends tag

- src/structures/Message.js
- src/structures/Webhook.js
- src/structures/interfaces/InteractionResponses.js
- src/structures/interfaces/TextBasedChannel.js
Another field that is common among all that extend `BaseMessageOptions`
Thanks, **Apokalypt** for noticing 👍
> docs: move embeds field into BaseMessageOptions

- src/index.js
This removes the additional exports for some of the util methods because the methods that get exported there seem rather arbitrary and you can access them from the Util class anyway. They were also not added to the typings, meaning that TypeScript users were never able to import them to begin with.
> refactor: remove exported shortcuts to util methods

- src/managers/MessageManager.js
- src/structures/APIMessage.js
- src/structures/Message.js
- typings/index.d.ts
One of those rabbit hole bugs that made me change a few things.
To start with, `Message#suppressEmbeds` was broken. This is because:
1. Internally that method calls `Message#edit({ flags: 4 })`.
2. That method then calls `MessageManager#edit(this.id, options)`
3. `MessageManager#edit` constructs an `APIMessage` with `this` as the target.
4. `APIMessage#resolveData` only resolves `flags` if the `APIMessage#target` is a `Message` or `Interaction`.
https://github.com/discordjs/discord.js/blob/master/src/structures/APIMessage.js#L159-L164
So, I decided that:
1. `Message#edit` should pass `this` rather than `this.id`.
2. `MessageManager#edit` should pass the whole message to `APIMessage#target` if provided with one.
3. `APIMessage` should support `MessageManager` as a target also, for when …
> fix(Message): flags not being parsed on some edits

- src/errors/Messages.js
- src/structures/CommandInteraction.js
- src/structures/MessageComponentInteraction.js
- src/structures/interfaces/InteractionResponses.js
- typings/index.d.ts
Replaces and closes #5665 as that PR was abandoned. This applies the suggestions and also adds the error handling to the `deleteReply()` method.
> feat(Interactions): improve error handling for ephemeral responses

- src/structures/interfaces/InteractionResponses.js
When editing a deferred response (editReply), we are not able to check whether we have replied to this interaction.
- I know how to update typings and have done so, or **typings don't need updating**
> fix(InteractionResponses): set replied status on editReply

- src/util/Permissions.js
This PR ensures that calling `Permissions#missing` on an instance with `ADMINISTRATOR` always returns an empty array, except when `checkAdmin` is `false`.
> fix(Permissions): allow admin to override in the missing method

- src/client/actions/ActionsManager.js
- src/client/actions/InteractionCreate.js
- src/client/websocket/handlers/INTERACTION_CREATE.js
- typings/index.d.ts
Ignoring the much larger issues about Websocket and Action handlers still being separate, this moves the INTERACTION_CREATE logic over to an Action handler.
This allows `Action#getChannel` to be used for caching a partial DMChannel, preventing `Interaction#channel` from returning null with the CHANNEL partial enabled
> feat(InteractionCreate): move to an Action handler

- src/structures/ApplicationCommand.js
Fixes a bug introduced in #5862 which could send strings to the API instead of integers when creating slash commands
> fix(ApplicationCommand): stringType isn't supposed to be sent to the API

- src/client/actions/ThreadListSync.js
- typings/index.d.ts
This fixes a couple of typos added with the PR #5570
Such as in the ThreadListSync actions file where `channels_ids` was used instead of `channel_ids`
and in the typings file where rateLimitPeruser was used instead of rateLimitPerUser.
> Fixed typos from commit #5570

- src/client/actions/InteractionCreate.js
- src/errors/Messages.js
- src/index.js
- src/structures/BaseMessageComponent.js
- src/structures/Interaction.js
- src/structures/MessageActionRow.js
- src/structures/MessageComponentInteraction.js
- src/structures/MessageSelectMenu.js
- src/structures/SelectMenuInteraction.js
- src/util/Constants.js
- src/util/Structures.js
- typings/index.d.ts
**Changelog**
- New class `MessageSelectMenu`
- New types `MessageSelectMenuOptions`, `MessageSelectOption`, `MessageSelectOptionData`
- New utility method `resolvePartialEmoji` for resolving emoji without a Client
- Improved emoji resolving in `MessageButton`, also applied to `MessageSelectOption` (fixes #5753)
- Improved consistency of documentation across all component classes
> feat(MessageSelectMenu): droppybois

- src/structures/ThreadChannel.js
- src/structures/ThreadMember.js
This PR adds links to the new APIThreadMember object as well as the existing APIChannel link to thread channels
> docs(Thread): add links to discord api docs

- src/structures/Message.js
- src/structures/MessageMentions.js
- typings/index.d.ts
This PR adds a `repliedUser` property to the message mentions so that users can more quickly see which user was replied to.
> feat(MessageMentions): add repliedUser

- src/structures/Webhook.js
This PR fixes `Webhook#edit` to also resolve non-string avatars (read: buffers) into the required data uris.
> fix(Webhook): resolve non-string avatars too

- typings/index.d.ts
> types(ThreadMemberManager): fix incorrect usage

- src/structures/MessageComponentInteraction.js
- typings/index.d.ts
Closes #5828
This currently uses generic Object/unknown typings for a raw message component, pending https://github.com/discordjs/discord-api-types/pull/132 being merged.
> feat(MessageComponentInteraction): component getter

- src/structures/Message.js
- src/structures/MessageCollector.js
- src/structures/MessageComponentInteractionCollector.js
- src/structures/ReactionCollector.js
- src/structures/interfaces/Collector.js
- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
This makes the filter for collectors optional because you shouldn't need to pass one. Currently, you need to do `createCollector(() => true, { ... })` to achieve the same result.
> refactor(Collector): make filter an option

- src/structures/APIMessage.js
- src/structures/Message.js
- src/structures/Webhook.js
- src/structures/interfaces/TextBasedChannel.js
- src/util/Util.js
- typings/index.d.ts
- typings/index.ts
:broom: clean-up service here, removing old remnants from old versions of discord.js
:warning: Removed `APIMessage#split`
:warning: Removed `MessageEditOptions#code`
:warning: Removed `BaseMessageOptions#code`
:warning: Removed `BaseMessageOptions#split`
- **Why?**
No other method in the entire library does two requests to the same path. This method was an exception for many years, and is something that should always been done by the user.
- **How do I restore this feature?**
You can still use the `Util.splitMessage` utility, and then with given array, send all the messages as you desire.
As for `code`, simply wrap the content into \`\`\`js\n${content}\`\`\`​. We're releasing an utility later in the future too, so …
> refactor: removed `code` and `split` options

- src/structures/User.js
- typings/index.d.ts
Due to the system property only being present in user objects when the user is a system user, it would end up always being null instead of false like it should be. This PR fixes that so that it's true for system users, false for non-system users and null for partial users (regardless of whether they're system or not, since we don't know that)
Another issue in the User class was that the bot property would always be false for partial users due to the check `typeof this.bot !== 'boolean'` which would return true since this.bot was set to null previously. This fixes that so that it's null for partial users, true for bots and false for regular users.
⚠️ I did test these changes but only by creating partial objects …
> fix(User): fix bot and system properties being incorrect in some cases

- src/structures/Channel.js
This PR fixes a small visual bug in the documentation causing `news_thread` to not render like the others (as an inline code-block).
> docs(Channel): make the type news_thread an inline code-block

- package-lock.json
- package.json
- typings/index.d.ts
This replaces the remaining instances of Raw typings after they had been renamed.
It also updates the discord-api-types dependency to the -next release to support the component typings
> types: fix remaining Raw type references, update discord-api-types dep

- src/structures/Message.js
- typings/index.d.ts
After #5905 PR, `data.referenced_message` property has been added to Message class (optional, non-nullable). Actually, however, the property is also nullable. This PR makes that nullable, and fixes issue caused by non-nullable property.
p.s. My english is not good. please understand if you find any wrong grammar..
> fix(Message): Make author of referenced message nullable

- src/util/BitField.js
- typings/index.d.ts
In #4879, some modifications were made to permissions and bitfield methods.
Especially on the type of bitfields that moves from **number** to **BigInt**.
This move has some impact on serialization and deserialization.
Take the example of a simple `JSON.stringify` and `JSON.parse`.
The method `toJSON()` (provided by BitField class) will be called and the type (BigInt in the case of Permissions) will be transformed into a string:
> `8n` => `"8"`
In the past, this type changing was not needed because a number remains a number.
In the actual Bitfield class if you try to pass permissions that went through serialization and deserialization you get the beautiful error `BITFIELD_INVALID`.
So a simple role or channel …
> revert(BitField): ⏪ Bring back-compatibility after BitField serialization

- src/structures/Webhook.js
One example in `Webhook#send` still uses the old way of sending messages with multiple parameters, which got removed as of #5758. This PR fixes that and uses a single param.
> docs(Webhook): fix thread example in send method

- src/structures/MessageButton.js
MessageButtonStyle resolvable was incorrectly documented as accepting any string
> docs: drop string from MessageButtonStyleResolvable

- src/structures/MessageComponentInteractionCollector.js
- src/structures/ReactionCollector.js
- src/structures/interfaces/Collector.js
- typings/index.d.ts
This PR is smaller than it sounds but I'm explaining every change in detail here because I don't want to open yet another fix PR lol
Docs:
- The return type of `MessageComponentInteractionCollector#collect()` was changed from `?(Snowflake|string)` to just `?Snowflake` because it only returns either null or the interaction ID
- The return type of `ReactionCollector#collect()` was changed from `Promise<Snowflake|string>` to `Promise<?(Snowflake|string)>` because it can return null as well
- The return type of `Collector#collect()` was changed from... whatever that was before to `?(*|Promise<?*>)` so that extended classes can specify whether it returns a promise or not
Types:
- `Collector` got another type parameter …
> fix(Collector): docs and types

- typings/index.d.ts
Currently, when using `ColorResolvable`, you wouldn't get the color names from IntelliSense because they merge with the `string` type. By changing this to a templated string, the strings don't merge and the names show up.
> types(ColorResolvable): change `string` to `#${string}`

- src/structures/Presence.js
In the `Activity` class, the syncID property was defined twice in the constructor.
> refactor(Presence): remove second assignment of `syncID`

- src/structures/Webhook.js
The typings for Webhook#delete says it returns `Promise<void>` but it really returns `Promise<Buffer>` with the buffer being an empty buffer because as https://discord.com/developers/docs/resources/webhook#delete-webhook states the route returns a 204 with no content. Webhook#deleteMessage has the same result from the route so to keep it consistent with that method and the typings this PR removes the return from the delete method.
> fix(Webhook): return void from #delete for consistency.

- src/errors/Messages.js
- src/managers/ApplicationCommandManager.js
- src/managers/ApplicationCommandPermissionsManager.js
- src/managers/GuildApplicationCommandManager.js
- src/structures/ApplicationCommand.js
- typings/index.d.ts
Replaces and closes #5695 as the PR seems to be abandoned.  This takes a good chunk of the code from that PR, but moves existing code and new code into a new manager while addressing requested changes.
Benefits of this approach:
Each command has its own way to access all of its permissions properties alongside the guild and global versions
Every function takes an object, making the somewhat confusing required vs optional parameters a little easier to understand.
Typescript users *hopefully* know exactly what they need to use the manager due to some hefty overloads and type passing.
(I did a lot of things that I don't know whether will work or not, but they should 🤞...I hope )
~~⚠️ This is untested as of now, …
> feat(Managers): new ApplicationCommandPermissionsManager

- .github/workflows/publish-dev.yml
Changed the git sha to only include the first 7 characters and added a UNIX timestamp in seconds. This should prevent issues with `npm update` and dependabot being stuck on older versions.
> ci: add UNIX timestamp to version number

- src/structures/CommandInteraction.js
- src/structures/Interaction.js
- typings/index.d.ts
closes #5809
This PR creates an `inGuild()` method ~~both~~ for `Interaction` ~~and `CommandInteraction`~~  checking if an interaction is used in a guild. Feel free to add suggestions, such as naming or implementation ,as i compeletely followed the ones from the issue
> feat(Interaction): add guild guard

- typings/index.d.ts
- typings/index.ts
Right now, `ShardClientUtil#broadcastEval` and `ShardingManager#broadcastEval`'s return types are the same as the callback's, as well as the context passed, however, the context data is serialized, and so is the return type.
This PR implements `Serialized`, which fixes this issue by converting rich types into their serialized counterpart.
> fix(Sharding): strict type context and return

- src/structures/ThreadChannel.js
- typings/index.d.ts
fix #5964
This PR makes `archivedTimestamp` and `archivedAt` not nullable as shown in [Discord API docs](https://discord.com/developers/docs/resources/channel#thread-metadata-object).
Since these properties indicate the date of the last archive status change and not only the last archived/unarchive date maybe we can change their actual names, but for now, I'll keep them.
> fix(Thread): make archive_timestamp not nullable

- typings/index.d.ts
This PR fixes the lack of the type parameter in ThreadManager#create's options
> types(ThreadManager): add type to ThreadManager#create options

- src/managers/ThreadManager.js
This PR fixes the jsdoc for `ThreadCreateOptions`
> docs(ThreadManager): fix reason prop of ThreadCreateOptions

- src/errors/Messages.js
- src/structures/MessageComponentInteraction.js
- src/structures/interfaces/InteractionResponses.js
- typings/index.d.ts
Stemming from internal discussion, this is one of two opposing PRs which provide a way to automatically fetch the reply/deferral/update to an interaction, assuming it's not ephemeral.
This PR adds an option to the methods, allowing the user to enable auto-fetching. The default maintains the existing behaviour. I've written it such that attempting to auto-fetch an ephemeral reply, or auto-fetch an update to an ephemeral message throws an error - this can be changed of course.
(Testing cross-PR closing) - Closes #5830
- This PR changes the library's interface (methods or parameters …
> feat(Interactions): option to auto-fetch replies

- package-lock.json
- package.json
- src/index.js
- src/util/Formatters.js
- typings/index.d.ts
ref: https://github.com/discordjs/discord.js/pull/5918
**Usage:**
```javascript
const { Formatters } = require('discord.js');
Formatters.bold('Hello there');
// **Hello there**
```
```javascript
const { Formatters: { bold, italic } } = require('discord.js');
bold(italic('General Kenobi!'));
// **_General Kenobi!_**
```
Or with TypeScript / ESM:
```typescript
import { Formatters } from 'discord.js';
Formatters.codeBlock('You are a bold one.');
// ```\nYou are a bold one.```
```
> **Note**: A namespace was used because it's the equivalent of `export * as Formatters from './util/Formatters';` in TypeScript.
- Code changes have been tested against the Discord API, or there are …
> feat(Util): added formatters

- typings/index.d.ts
In #5950 the type for ColorResolvable was changed from `string` to `#${string}`. This meant that assigning a hexColor from the library to a ColorResolvable parameter would error out, so this PR fixes that.
> types(*): make hex color types compatible with ColorResolvable

- src/structures/Channel.js
- typings/index.d.ts
This PR adds `Channel#isThread` method to help TS users narrow down a generic channel into a `ThreadChannel`
- This PR changes the library's interface (method added)
> feat(Channel): add isThread typeguard for better TS support

- src/managers/ThreadManager.js
This PR correctly defines the `FetchedThreads` typedef.
It also changes the description for `ThreadCreateOptions#startMessage`. Thread created without a message does default to private if no type was provided but we have `type` set to `public_thread` as default in the lib. So, it is not going to be a private thread if no `startMessage` was provided.
> docs(ThreadManager): fix FetchedThreads typedef and startMessage

- typings/index.d.ts
This PR just fixes typings for parameters `locked` in `ThreadChannel#setLocked` and `archived` in `ThreadChannel#setArchived` to be optional as showed in [docs](https://discord.js.org/#/docs/main/master/class/ThreadChannel?scrollTo=setLocked) and in the source code.
> types(ThreadChannel): make locked and archived param optional

- src/structures/MessageComponentInteraction.js
This PR adds links to Discord's documentation regarding MessageSelectMenus where they're needed. Also created a typedef for the current raw components from the API that includes the 2 new links I added.
> docs(MessageSelectMenu): add link to Discord docs

- typings/index.d.ts
- typings/index.ts
Fixes a subtle typings issue with the perms manager. There does remain the issue that set{ fullPermissions }) is invalid when used for an ApplicationCommands permissions manager, but I have no idea how to fix that.
> types(ApplicationCommandPermissionsManager): fix types

- src/managers/StageInstanceManager.js
- src/structures/StageChannel.js
- src/structures/StageInstance.js
- typings/index.d.ts
This PR adds a new `createStageInstance` method on `StageChannel` that lets the user create a stage instance associated to it. It also refactors the options typedef to keep it consistent with rest of the lib:
1) `CreateStageInstanceOptions` is now `StageInstanceCreateOptions`
2) The `channel` field is a seperate param now instead of being inside the options object
⚠️ As pointed out by @SpaceEEC, the term **"instance"** makes it sound like it is an instance of a Stage Channel which it isn't. This PR removes this ambiguity by using the complete term i.e. **"Stage Instance"** in all places. 
- I know how to update typings …
> feat(StageChannel): add createStageInstance method & use better naming convention

- src/structures/ThreadChannel.js
This resolves the crash detailed in #5960, allowing ThreadChannel to be selected as a channel type slash command option.
The outstanding issues around resolved channels and partials is still present.
> fix(ThreadChannel): check for existence of properties when patching

- src/util/Constants.js
On #5820, all guides present in this repo were removed in favor of the ones in https://discordjs.guide. This PR removes a reference to an article on the "sidebar" and adds the proper link to the guide.
> docs(Partials): add link to the guide

- typings/index.d.ts
Fixes an issue with `MessageOptions#components` typing that prevented users from combining different types due to the way the union was written.
> types(MessageOptions): improved component typings

- typings/index.d.ts
Fixes issues with `Interaction#reply` and `MessageComponentInteraction#update`, due to the overload types the return type would default to `Promise<Message | APIMessage>` if only a string was specified as the content.
> types(Interactions): fix function overload types

- .github/workflows/publish-dev.yml
This PR adds a step to the publish dev CI that automatically deprecates all dev versions before publishing a new one so that you don't have to manually do that yourselves every 12 hours. Here are the npm docs on [npm-deprecate](https://docs.npmjs.com/cli/v7/commands/npm-deprecate) and you can test the version range [here](https://semver.npmjs.com/)
> ci: deprecate old dev releases on publish

- src/util/Util.js
Util methods were removed from the base Discord object in #5904 but docs have not been updated. This PR only removes the phrase "*These functions are also available on the base `Discord` object.*" phrase in the js comment.
> docs(Util): methods removed on the base object

- src/managers/RoleManager.js
- src/structures/Role.js
- typings/index.d.ts
Fixes #5634
Also implements `RoleManager#edit` to be consistent with many other managers.
> feat(RoleManager): added `edit` method, alias `Role#edit`

- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
Since PR #5918 the TextBasedChannel#send method shouldn't return an array since it only did when using the split option.
and WebSocketShard#send was missing the `important` argument in the typings.
> docs: WebSocketShard#send and TextBasedChannel#send

- src/structures/Channel.js
- src/structures/Interaction.js
- src/structures/interfaces/InteractionResponses.js
This PR adds `@link`s to the isX() methods (isText, isThread, isButton, isSelectMenu, isMessageComponent, isCommand) and also fixes one outdated example in interaction.reply()
> docs(*): add class links to isX() methods

- typings/index.d.ts
#5987 Updated the component typings for MessageOptions but not for MessageEditOptions, causing compilation issues when trying to pass a MessageOptions type to `message.edit()`.
> fix(Typings): Improve components typings in MessageEditOptions

- typings/index.d.ts
This PR Fixes the ClientUser#setAFK typing where the return type was still set as Promise<Presence> and was missing the shardID argument.
> types(ClientUser): updated `setAFK` signature

- src/structures/VoiceState.js
- typings/index.d.ts
https://discord.js.org/#/docs/main/master/class/VoiceState
1. VoiceState.selfVideo can be null.
2. VoiceState.setChannel(channel, reason): Channel can be optional, as default is none. (according to docs on master)
> types(VoiceState): fix optional params

- typings/index.d.ts
This PR adds more specific typings for mentions like the example below:
```ts
type UserMention = `<@${Snowflake}>`;
```
> types(*): create mention types

- typings/index.d.ts
- typings/index.ts
This PR fixes an issue where you'd be able to pass an array of MessageComponents in the components property for MessageOptions where, in fact, you need to pass an array of arrays of MessageComponents. This also makes it so that initializing a MessageActionRow with an empty object in the constructor will now throw an error.
These scenarios will still work:
```ts
new MessageActionRow();
new MessageActionRow({ components: [MessageButton] });
message.channel.send({ content, components: [[MessageButton]]})
```
And these scenarios will now throw an error:
```ts
new MessageActionRow({});
message.channel.send({ content, components: [MessageButton] })
```
- Code changes have been …
> types(MessageOptions): fix components being optional

- src/structures/GuildChannel.js
The type for targetType in https://discord.js.org/#/docs/main/master/typedef/CreateInviteOptions was wrong, so I fixed that (now leads to https://discord.js.org/#/docs/main/master/typedef/TargetType)
> docs(CreateInviteOptions): fix TargetType link

- src/structures/MessageCollector.js
- src/structures/MessageComponentInteractionCollector.js
- src/structures/ReactionCollector.js
- src/structures/interfaces/Collector.js
- typings/index.d.ts
I stumbled upon `Collector#endReason` not appearing in the documentation, so here is a fix.
(Something about the parser not picking up `@name`'d properties after the last method?)
I added jsdocs to the deriving classes so the now implement property is no longer `abstract`.
I also marked `Collector#endReason` as `readonly` in the typings, all deriving classes do that themselves already however.
> docs(Collector): properly document endReason

- src/util/DataResolver.js
- src/util/SnowflakeUtil.js
- src/util/Structures.js
- src/util/Util.js
- typings/index.d.ts
When constructing a class extending null, the following error is thrown:
```javascript
TypeError: Super constructor null of Util is not a constructor
```
Which lets us skip a constructor, as well as it stops other static members from the Object class from being inherited.
> refactor(Util): make class extend `null`

- src/util/Util.js
fix #6006 
This PR fixes a problem with Util.splitMessage which doesn't work when the `char` option is set to an array. This is because the array of messages is mapped and messages splitted again causing the creation of an array of arrays. This PR adds a `.flat(1)` to prevent this from happening. I also tested this with all options but let me know if there are still problems.
*Sorry for too many commits but I accidentally pushed the content of another PR into my master branch*
> fix(Util): splitMessage not working with array

- src/client/websocket/WebSocketShard.js
> fix: Remove `connection.url` from open debug message

- src/structures/GuildChannel.js
After #5318, actual permission overwrites data is accessible via cache of PermissionOverwriteManager, However this structure hasn't changed even since the PR. Therefore, attempting to use the latest dev version results in numerous errors.
This PR adds missing `cache` property to GuildChannel structure, and resolves error caused by unchanged structure.
> fix(GuildChannel): Add missing 'cache' property

- src/managers/ThreadManager.js
- src/structures/ThreadChannel.js
- src/structures/ThreadMember.js
- typings/index.d.ts
1) This PR improves the typings by:
- Restricting values for `type` in `ThreadManager#create` depending on what type of channel the manager belongs to. This will provide better and valid autocompletion
- Adding interfaces where they were needed to make the typings look clean and tidy
- Fixing a TS bug in `ThreadManager#fetch` where it will never suggest `force` field for `cacheOptions` (the fact that it gets ignored in some specific circumstances has been documented too)
2) This PR also improves the documentation for threads by:
- Adding typedef for `ThreadEditData`
- Adding more detailed information where it was required
- Doing a little bit of sentence restructuring here and there
- Addressing caveats
**Status …
> refactor: improve typings and docs related to threads

- src/structures/ClientApplication.js
- src/structures/ClientUser.js
- src/structures/CommandInteraction.js
- src/structures/GuildAuditLogs.js
- src/structures/Interaction.js
- src/structures/InteractionCollector.js
- src/structures/Webhook.js
- src/structures/WelcomeChannel.js
*Let's use `ClientApplication#owner` as an example of a union type without parentheses*
https://github.com/discordjs/discord.js/blob/39db95352c91faf175c2fd8ed365f293f965a0e4/src/structures/ClientApplication.js#L58
Instead of the type being shown as "**?User** or **?Team**", it's shown as "**User** or **Team**"
*On the other hand, let's use `GuildChannelManager#resolve` as an example of a union type with parentheses:*
https://github.com/discordjs/discord.js/blob/39db95352c91faf175c2fd8ed365f293f965a0e4/src/managers/GuildChannelManager.js#L62
*** 
I removed the parentheses from `GuildAuditLogs#changes` as they are not necessary.
- This PR **only** includes non-code changes, …
> docs(*): wrap optional properties with union types in parentheses

- src/structures/DMChannel.js
- src/structures/InteractionCollector.js
- src/structures/Message.js
- src/structures/TextChannel.js
- src/structures/ThreadChannel.js
- src/structures/interfaces/TextBasedChannel.js
Missed renaming the MessageComponent methods in a few places so they weren't being documented properly.
> docs: fix some missed MessageComponent collector methods

- src/managers/MessageManager.js
The `options` param for `MessageManager#edit` is documented as optional, which isn't correct as the [typings](https://github.com/discordjs/discord.js/blob/610b0b4dd6b6e66c05c22eb852d2a752b99d07ba/typings/index.d.ts#L2591) for it states that it is a required param. Also, the said method calls `MessagePayload#create`, which requires the second param to be always defined, which is `options` in this case.
> docs(MessageManager): document options param for #edit as required

- typings/index.d.ts
At first, we used module augmentation so the types could be linked with the actual library's types, however, that ended up not working correctly (and I suspect it's because the `type` definition, which unlike `interface`s, they can't be augmented).
I moved the definitions into discord.js and prefixed them with `Internal` to not conflict with the /voice's definitions, as well as marked them as `@internal` with a description via TSDocs.
> types(Voice): move types to the library's definitions

- typings/index.d.ts
The Options class extends null in the javascript file, but not in the typings.
https://github.com/discordjs/discord.js/blob/185e37602b0fabf6f06a02886128aead9239c5d9/src/util/Options.js#L92
https://github.com/discordjs/discord.js/blob/185e37602b0fabf6f06a02886128aead9239c5d9/typings/index.d.ts#L512
> types(Options): should extend null

- src/client/Client.js
- src/errors/Messages.js
- src/util/Constants.js
- typings/index.d.ts
Previously this method would automatically include the bot scope - it's now required that the user provide scopes in the options, including one of either bot or applications.commands.
> feat(Client): enforce passing scopes to generateInvite

- src/structures/Team.js
- typings/index.d.ts
Fixes the typings for
Team#owner - the return type was missing null
Team#iconURL - the return type was missing null
TeamMember#toString - changed the return type to UserMention as for PR #6003
and changed the JSDOC for Team#ownerId to be type {?Snowflake} instead of {?string}.
> fix(TeamMember): Fixed incorrect return types.

- src/managers/GuildInviteManager.js
- src/structures/Guild.js
- typings/index.d.ts
Adds the new `GuildInviteManager` to `Guild` as `Guild#invites` since #5889 didnt, and extend the new `CachedManager`.
> fix(Guild): add invite manager property, extend CachedManager

- src/client/actions/MessageCreate.js
- src/structures/GuildMember.js
- src/structures/User.js
- typings/index.d.ts
- typings/index.ts
Only `TextBasedChannel#lastMessageId` is given by Discord (`data.last_message_id`), `User`'s and `GuildMember`'s were extensions from our side.
> refactor: remove `lastMessage` properties from `User` and `GuildMember`

- src/index.js
- src/util/LimitedCollection.js
- typings/index.d.ts
Closes #4274, I don't know why it isn't exported
> feat(LimitedCollection): export LimitedCollection

- src/util/Intents.js
- typings/index.d.ts
- typings/index.ts
- ⚠️ remove `Intents.ALL`
- ⚠️ remove `Intents.PRIVILEGED`
- ⚠️ remove `Intents.NON_PRIVILEGED`
We currently provide static shorthands on the Intents bitfield wrapper (inspired by Permissions when implementing). This raises multiple issues:
- End users are lead to just pass `Intents.ALL` no matter what they actually need for the bot to work, as evident from library support channels
- Discord might change the grouping of which intents are privileged and which are not at any time. They don't make any promise that this will stay at member presences and guild members. Removal accordingly improves maintainability, as we do not need to push releases to change groupings going forward. …
> refactor(Intents): remove computed shorts

- typings/index.ts
This utility is useful for checking whether classes that use mixins don't get any unintended property.
> test(Types): add `notPropertyOf` type-only utility

- src/util/Constants.js
- typings/index.d.ts
The `bot` invite scope was missing from the typings and from the docs.
The description of the bot scope on the docs might not be the best, let me know.
> fix(InviteScope): added missing 'bot' scope

- typings/index.d.ts
Readonly property "client" was missing from type definitions for class Presence.
Seeing as the client property is still being defined and is also still listed in the docs, this looks like it was missing. Feedback on PR is welcome, as I'd like to continue to contribute/do so properly. Thanks!
https://github.com/discordjs/discord.js/blob/master/src/structures/Presence.js#L41
> fix(Presence) missing client property definition

- src/structures/ThreadChannel.js
This PR fixes the docs for `ThreadChannel#setLocked` 🧵 🔒 
> docs(ThreadChannel): fix documentation for setLocked method

- src/client/actions/PresenceUpdate.js
- src/structures/GuildMember.js
- src/structures/User.js
- typings/index.d.ts
as well as on Client#presenceUpdate
This PR:
- removes `User#presence` as it was a hack traversing the guild cache in order to find a presence of any member representing the given user.
- makes `GuildMember#presence` nullable. That way you can distinguish between "This member is offline" and "The presence of this member is unknown" without having to check the cache yourself, rendering this getter pointless.
Additionally this was confusing when you did not enable the presence intent in the first place: "Why do I know this member is offline? I am not supposed to know!" (Despite you actually having no idea)
- makes `Client#presenceUpdate` first parameter `null` instead of `undefined`, because we don't do this in other …
> refactor(Presences): remove from User, nullable on GuildMember

- src/managers/PresenceManager.js
- src/structures/ClientPresence.js
- src/structures/Presence.js
- typings/index.d.ts
This PR brings a bit of consistency to `PresenceManager` and `Presence` with the other structures and managers.
`Presence` more or less implemented `Base`'s stuff itself in combination with `PresenceManager` patching it itself, while `CachedManager` could do that just fine.
Carefully going with `semver: patch` here, since I am not sure what making `Presence` extend `Base` could break.
> refactor(PresenceManager): have Presence extend Base and simplify add

- typings/index.d.ts
- typings/index.ts
This changes the type of the collector event parameters from `unknown` to something actually helpful.
> feat(Collector): better types for events

- typings/index.d.ts
This PR changes the types for all arguments from spread functions from `unknown` to `any`, introduced in #6047. This meant that  any conditions that relied on these functions would return false and break certain things (like Partials)
> types(*): revert incorrect unknown type changes

- src/errors/Messages.js
- src/managers/ChannelManager.js
- src/managers/GuildChannelManager.js
- src/structures/Channel.js
- src/structures/GuildChannel.js
- src/structures/StoreChannel.js
- src/structures/TextChannel.js
- src/structures/ThreadChannel.js
- typings/index.d.ts
This PR allows fetching channels from guilds that do not exist in the client cache (applicable mostly when sharding, but also possible to have guilds uncached via intents limiting or the new collection based limiting)
A big red flag warning here: channels obviously rely on guild internally a lot, however I did not want to change types when the majority of times the values will be present. I would expect people using this option to know exactly what they are doing and which properties can be accessed.
This also fixes up fetching single channels from the guild channel manager, making it cleaner and throwing when trying to fetch a channel from a  different guild (this is the only breaking change)
closes: #4929 …
> feat: allow channels from uncached guilds to be returned from fetch

- src/managers/ApplicationCommandManager.js
The `force` parameter is used only in line 88:
https://github.com/discordjs/discord.js/blob/2e078e44883c1ef5f85ef973d61a305ce2a34251/src/managers/ApplicationCommandManager.js#L88
Which is always unreachable for line 86, where this assignment is at.
> refactor(ApplicationCommandManager): remove unused assignment

- src/managers/ApplicationCommandPermissionsManager.js
- typings/index.d.ts
- typings/index.ts
This PR just fixes an error in typings where the option `permissionId` was typed as `permissionsId`.
> types(ApplicationCommand): fix option name

- src/structures/ClientUser.js
fix #6020 
This PR fixes some jsdocs where `shardId` was showed as nullable while it isn't, in fact, passing `null` as `shardId` throws a TypeError. However, it's still marked as optional and types are ok.
> docs(ClientUser): fix shardId nullable

- src/managers/GuildInviteManager.js
- typings/index.d.ts
This PR fixes the jsdocs and typings for GuildInviteManager's FetchInvitesOptions, since #6036 the fetch methods channelID param was changed to channelId which the casing wasn't fixed in the type declarations file, and channelId was missing completely from the JSDoc. The JSDoc was also inconsistent with what was in the typings file.
> typings(GuildInviteManager): FetchInvitesOptions

- src/structures/interfaces/InteractionResponses.js
Currently in `InteractionResponses#update`, the description and example refers to a button interaction, so this also gets displayed in e.g. `SelectMenuInteraction#update` on the docs. This is not done by any other methods on the interface. This PR generalizes the wording to a general component interaction, also probably making it future proof in case more component interactions will be added in the future. 
Also changed the description for the options param to be more accurate. 
> docs(InteractionResponses): generalize wording in update to fit other component interaction types

- src/structures/interfaces/InteractionResponses.js
The `reply` method returns `Promise<void>`, so `.then(console.log)` is pointless.  This replaces the log with a simple string to acknowledge success.  I left other methods that potentially resolve into `void` (`defer`, `followUp`, etc) alone.
> docs(InteractionResponses): reply docs example

- src/client/actions/PresenceUpdate.js
This PR fixes #6075 by using the presence returned from `PresenceManager#add`.
The cause for this is a combined effort of #6013 and #6055:
The first would discard the presence on insertion (as intended when not caching them), causing the getter to return a default presence here.
With the second the default presence was removed, causing the getter to now return `null`, causing this crash.
~~I should have spotted that.~~
> fix(PresenceUpdate): use added presence over nullable getter

- src/managers/PermissionOverwriteManager.js
- src/structures/GuildChannel.js
This PR fixes #6082 by cloning `GuildChannel#permissionOverwrites` when cloning the channel itself.
This PR also addresses the issue that a passed `iterable` would cause the then created `PermissionOverwrites` to be without a channel as the `channel` property would be initialized after the parent's constructor added them.
(This might be better solved with another private method to be called from the deriving classes, e.g. `this._init(iterable);` or similar)
> fix(GuildChannel): clone its PermissionOverwriteManager too

- typings/index.d.ts
`Guild#fetchVoiceRegions` was removed in https://github.com/discordjs/discord.js/pull/5766, but wasn't removed from the typings. This PR fixes that.
> types(Guild): remove fetchVoiceRegions

- src/structures/PermissionOverwrites.js
In some situations `PermissionsOverwrites#_patch` was being called with an existing `PermissionsOverwrites` object rather than raw packet data from Discord (I observed this locally when an overwrite was removed from a channel). This meant that `type` was already a string, and so the enum conversion was resulting in it incorrectly being stored as a number.
This PR tweaks the patch logic in `PermissionsOverwrites` to ensure that the enum conversion only occurs if the data provided is a number. If it is not, it is assumed that it is already a valid string type. This ensures that `PermissionsOverwrites#type` is always actually a string, as documented.
- Code changes have been …
> fix(PermissionsOverwrites): only convert type if number

- src/structures/BaseMessageComponent.js
- src/structures/Message.js
- src/structures/MessageActionRow.js
- src/structures/MessagePayload.js
- src/structures/Webhook.js
- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
- typings/index.ts
As nice as this was for the user interface, as per internal discussion it was considered not future proof should there ever be a different type of Row component.
This removes support for sending a nested array of components, e.g. no more:
`message.channel.send({ content, components: [[button]] })`
I also noticed that the way component types were being checked didn't work in some scenarios - this simplifies that process to ensure `client` is passed where it should be a debug event, and isn't everywhere else that it should throw.
- This PR includes breaking changes (methods removed or …
> revert: support for nested arrays of components, fix error handling

- typings/index.d.ts
Fixes an issue with `Interaction#defer` and `MessageComponentInteraction#deferUpdate`, due to the overload types the return type would default to `Promise<Message | APIMessage>` when no parameter was passed.
> types(Interactions): fix function overloads

- typings/index.d.ts
Without this change the following code does not compile:
```ts
const client = new Client();
(async function() {
const webhook = new Webhook(client, {id: '123', token: '456abc'});
const msg = await webhook.send({ content: 'Test' });
await webhook.deleteMessage(msg);  // Argument of type 'Message | APIMessage' is not assignable to parameter of type 'MessageResolvable | "@original"'.
})();
```
> types(PartialWebhookFields): add APIMessage to deleteMessage union

- src/structures/Interaction.js
- typings/index.d.ts
- typings/index.ts
This PR removes the `inGuild` method in `Interaction`, because, as discussed in the [Discord server](https://canary.discord.com/channels/222078108977594368/682166281826598932/863179005350903858), it's used only in this structure (not in any other `Structure` like Message or `Channel`) and doesn't provide any type guard for TS users so it's useless, as shown below:
```ts
client.on("interactionCreate", (interaction) => {
if (interaction.inGuild()) console.log(interaction.client.guilds.fetch(interaction.guildId));
})
```
```ts
client.on("interactionCreate", (interaction) => {
if (interaction.guildId) console.log(interaction.client.guilds.fetch(interaction.guildId));
})
```
These two codes are pretty much the same and …
> types(Interaction): change inGuild return type

- src/client/Client.js
- src/client/websocket/WebSocketManager.js
- typings/index.d.ts
- typings/index.ts
This PR adds conditional typings to the `Client` class, allowing for TypeScript to infer the ready state of the client and provide access to properties that are initialized at login, such as `Client#application` and `Client#user`. This also adds a client parameter to the `Client.on("ready")` event, defined in typings as a ready client.
This will be a major quality-of-life improvement for users of TypeScript and typings users, as it allows for access to client properties without optional chaining or non-null assertions.
- I know how to update typings and have done so, or typings don't need …
> feat(Client): add conditional ready typings

- src/client/actions/ChannelUpdate.js
- src/client/actions/GuildDelete.js
- src/client/actions/TypingStart.js
- src/errors/Messages.js
- src/structures/ClientUser.js
- src/structures/DMChannel.js
- src/structures/TextChannel.js
- src/structures/ThreadChannel.js
- src/structures/Typing.js
- src/structures/User.js
- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
- typings/index.ts
- Added `Typing` structure.
- Renamed `TextBasedChannel#startTyping` to `sendTyping`.
Additionally, this will not longer run a 9s interval sending additional requests, but instead, it will do so only once without any internal tracking.
- Removed `TextBasedChannel#stopTyping` as it relied on internal tracking.
- Removed `TextBasedChannel#typing` as it relied on internal tracking.
- Removed `TextBasedChannel#typingCount` as it relied on internal tracking.
- Removed `TextBasedChannel#_typing`.
- Changed `typingStart` event to take a `Typing` structure.
- Removed many timers, making typing events more scalable than ever.
- Removed `User#typingIn` as it relied on internal tracking.
- Removed `User#typingSinceIn` as it …
> refactor: remove typing caching

- src/client/Client.js
- src/rest/APIRequest.js
- src/util/Options.js
- typings/index.d.ts
This PR allows you to append information about the bot (like a website, version) to the end of the (already required) user agent. As specified in the [API documentations](https://discord.com/developers/docs/reference#user-agent), users should be able to do so and are encouraged to do it.
Discord.js users could alternatively modify the constants file, where the user agent string is defined, but it can lead to them not following the API specifications.
After having a talk with a few people, I decided to implement a `userAgentSuffix` option to `ClientOptions` for people to do this. Types are already updated. An example of the usage is down below.
```js
const { Client } = require("discord.js");
const botClient = new …
```
> feat(REST): append additional information to the required User Agent

- src/client/BaseClient.js
- src/client/Client.js
- src/client/actions/GuildDelete.js
- src/client/websocket/WebSocketManager.js
- src/client/websocket/WebSocketShard.js
- src/managers/GuildManager.js
- src/managers/GuildMemberManager.js
- src/rest/APIRequest.js
- src/rest/RESTManager.js
- src/rest/RequestHandler.js
- src/structures/GuildTemplate.js
- src/structures/interfaces/Collector.js
- typings/index.d.ts
:warning: This PR removes the following methods:
- `BaseClient#setTimeout`
- `BaseClient#setInterval`
- `BaseClient#setImmediate`
- `BaseClient#clearTimeout`
- `BaseClient#clearInterval`
- `BaseClient#clearImmediate`
**Why?**
The aforementioned methods existed to make timers not hang the process when it's destroyed and nothing else kept the process on (from the user's side). Since all timers have an `unref` method ([`Immediate#unref`](https://nodejs.org/dist/latest-v16.x/docs/api/timers.html#timers_timeout_unref), [`Immediate#unref`](https://nodejs.org/dist/latest-v16.x/docs/api/timers.html#timers_immediate_unref)), there is not longer a need to keep and track those timers, which can potentially lead to memory …
> refactor: remove timer utilities from Client

- typings/index.d.ts
`Message#thread` is marked as nullable in JSDocs, but not in the typings.
> types(Message): mark `#thread` as nullable

- src/structures/Channel.js
- src/structures/DMChannel.js
- src/structures/GuildBan.js
- src/structures/GuildMember.js
- src/structures/Message.js
- src/structures/User.js
Currently, (User|Channel|Message)#fetch ignores the `force` parameter, always treating it as false. This PR fixes it.
It also sets `force` to true on all instance fetch methods, after discussion in #library-discussions
> feat: make Instance#fetch force true by default, and fix force parameter

- src/errors/Messages.js
- src/structures/CommandInteraction.js
- src/structures/CommandInteractionOptionResolver.js
- typings/index.d.ts
This PR creates a new structure, `CommandInteractionOptionResolver`, which acts as a resolver for `CommandInteraction` options. This replaces the existing `Collection<string, CommandInteractionOption>` on `CommandInteraction#options` with the new class.
The new class will allow for easier usage and validation of command options. It also will serve as an additional check against users having mismatches between their option types and their execution code. This also allows for TypeScript users to access the properties in a cleaner and type-safe way without custom parsers or casting.
Example:
```typescript
import { Client, Snowflake } from "discord.js";
const client = new Client({ intents: [] });
client.on("ready", …
```
> feat(CommandInteraction): add CommandInteractionOptionResolver

- src/managers/GuildInviteManager.js
- src/structures/GuildChannel.js
Following the renaming of `ID` properties to `Id` (#6036), this particular instance was missed, which cases `GuildChannel#fetchInvites` to fetch all invites from the guild rather than just the specific channel.
> fix(GuildChannel): only fetch invites for the specific channel

- src/structures/GuildPreview.js
- typings/index.d.ts
GuildPreview is missing the `createdAt` & `createdTimestamp` fields since it doesn't extend the BaseGuild class, so this PR adds it.
> feat(GuildPreview): add createdAt & createdTimestamp

- typings/index.d.ts
- typings/index.ts
This fixes a typings issue on `CommandInteractionOption#options` which still referenced the `Collection` logic that was removed in f293132345294e33e80866272feaedf2e4a70d45. This PR updates the type to an array, as it is in the code. This PR also adds test cases for related typings and removes a removed method from `CommandInteraction`.
-    Code changes have been tested against the Discord API, or there are no code changes
-    I know how to update typings and have done so, or typings don't need updating
> fix(CommandInteraction): change options type from Collection to array

- package-lock.json
- package.json
- typings/index.d.ts
Forgot to write here, updates discord-api-types from the now-deprecated `-next` versions
> chore(Deps): update `discord-api-types` to 0.19.0

- src/structures/CommandInteractionOptionResolver.js
`MEMBER` isn't an option type, it should be `USER`.
> fix(CommandInteractionOptionResolver): type should be USER

- src/errors/Messages.js
- src/structures/CommandInteractionOptionResolver.js
- typings/index.d.ts
The reason why it accepted an array was because sub-commands and sub-command groups used to share the same method, however now that those are split up it is no longer needed.
> refactor(OptionResolver): accept single type instead of an array

- typings/index.d.ts
Add the `readonly` keyword on the tuple of `ColorResolvable`.
Since the tuple don't have to be mutated, make it `readonly` make `ColorResolvable` type wider.
> types(ColorResolvable): readonly tuple

- typings/index.d.ts
When you provide a parameter of type K to ```DataManager.resolveId(...)```, the typing consider that the result can be 'null' or 'K' type however, it will never be the case given the code of the function. So, this PR adds the type K for the parameter of the resolveId function which has as return type 'K' only.
More information here : https://discord.com/channels/222078108977594368/682166281826598932/866797061001052200
> types(DataManager): add 'K' to type parameter of 'resolveId'

- src/structures/Sticker.js
This PR fix a bug due the change of all xID into xId. In this function, the change has not been made resulting in an error all the time since ```!this.guildID``` is always true.
Bug report in Discord - https://discord.com/channels/222078108977594368/682166281826598932/867014005016756244
> fix(Sticker): replace 'this.guildID' (undefined) by 'this.guildId' in fetchUser

- src/structures/CommandInteraction.js
- src/structures/CommandInteractionOptionResolver.js
- typings/index.d.ts
- typings/index.ts
This moves the `_options` property to the public `data` property as a read-only array, which allows custom usage of options.
This closes #6143.
> refactor(CommandInteractionOptionResolver): add readonly data property

- src/client/actions/MessageUpdate.js
- src/structures/Message.js
- typings/index.d.ts
Two patch methods, both private, second often gets missed during changes. No more!
> refactor(Message): combine patch methods

- src/structures/CommandInteraction.js
Just correcting the documentation for this type definition! It is an array - not a `Collection`.
> docs(CommandInteraction): Correct type definition of `CommandInteractionOption`

- src/structures/GuildAuditLogs.js
Hi there!
Upon running `<Guild>.fetchAuditLogs({ type })` where `type` is 40 (`INVITE_CREATE`), 41 (`INVITE_UPDATE`) or 42 (`INVITE_DELETE`), there is a possibility that `target` on the returned `GuildAuditLogsEntry` will be `undefined`.
One case where this is easily reproducible is by simply creating and then deleting an invite and then running `<Guild>.fetchAuditLogs({ type: 40 })`.
I've simply added the nullish coalescing operator after that check to ensure that if an invite code cannot be found, it will default to `null` and not `undefined`.
- I know how to update typings and have done …
> fix(GuildAuditLog): Assert `target` to null upon not finding invite codes

- src/structures/CommandInteractionOptionResolver.js
- typings/index.d.ts
- typings/index.ts
This adds a `required` parameter to the `getSubCommand()` and `getSubCommandGroup()` methods, defaulted to `true` (as opposed to `false` in option getters), to allow for optional checking of sub-commands if needed (e.g. logging) without changing the current default behavior that enforces strict command definitions.
> feat(CommandInteractionOptionResolver): add sub-command required option

- typings/index.d.ts
Currently, if you want to remove attachments from a message you have to use `message.removeAttachments()`, and if you need to edit the content as well that is 2 API calls. Assigning `attachments: []` does work, but sparks errors in TypeScript that require `// @ts-ignore` - which is generally considered a bad practice. This PR fixes the typings allowing you to assign `attachments: []` without having to use ts-ignore.
I know how to update typings and have done so, or typings don't need updating
> fix(Typings): type attachments to InteractionUpdateOptions

- src/client/websocket/handlers/APPLICATION_COMMAND_CREATE.js
- src/client/websocket/handlers/APPLICATION_COMMAND_DELETE.js
- src/client/websocket/handlers/APPLICATION_COMMAND_UPDATE.js
- src/managers/ApplicationCommandManager.js
- src/structures/ApplicationCommand.js
- typings/index.d.ts
The applicationCommandCreate/Update/Delete events are sent when guild commands owned by _any_ bot in the server are created, updated, or deleted - and not just the commands owned by the client user. This meant that Discord.js was caching commands owned by other bots.
This PR:
- makes sure the command events only cache commands from the own bot (thanks @vladfrangu for the code suggestions)
- adds `ApplicationCommand#applicationId`
- modifies some of the `ApplicationCommandManager` methods so that they don't patch the cache in place (_this fixes a bug where the applicationCommandUpdate event would emit the oldCommand with the new data_), unless the targeted command is a global command. (The command events aren't …
> refactor: only cache commands from own user

- src/client/Client.js
- src/structures/Guild.js
- typings/index.d.ts
Currently, you can fetch a guild's widget data with Client#fetchWidget(guild), but you can't do it from the guild object. Now, you can use Guild#fetchWidget() as a shortcut. The old fetchWidget and setWidget methods have been renamed to fetchWidgetSettings and setWidgetSettings to more accurately explain their functionality.
> feat(Guild): add fetchWidget() for getting widget data

- src/managers/ChannelManager.js
- src/managers/GuildChannelManager.js
- src/managers/ThreadManager.js
- src/structures/Channel.js
- src/structures/CommandInteraction.js
- src/structures/Invite.js
- src/structures/ThreadChannel.js
- typings/index.d.ts
Sets thread auto archive to 0 when not sent in a paylod (exception for interactions)
closes: #6151 
Also Fixes docs and typings for ThreadChannels
> fix(ThreadChannel): better property handling

- src/structures/interfaces/InteractionResponses.js
- typings/index.d.ts
Hey!
`InteractionResponses` did not document a few `fetchReply` properties to the methods, so I've gone ahead and added those in.
The documentation for the type definition `InteractionDeferUpdateOptions` was completely missing, so I've added that in too!
I also noticed that the `.update()` method documented `WebhookEditMessageOptions` to be sent across. This didn't include the `fetchReply` property, but I did see an interesting `InteractionUpdateOptions` type that wasn't being used _anywhere_ other than itself being defined. It looks a bit wrong though, because it extended `WebhookMessageOptions` which allowed properties like `tts` to be sent through when it wouldn't do anything, ~~so I adjusted this to extend …
> docs(InteractionResponses): Document missing properties

- src/managers/GuildInviteManager.js
- typings/index.d.ts
The typings and documentation both detailed a `Snowflake` to be used for `GuildInviteManager#cache` and `GuildInviteManager#fetch()` instead of a `string` (invite code). This pull request should resolve this!
Resolves #6199 also.
> fix: Use `string` instead of `Snowflake` for invites

- src/util/Util.js
- typings/index.d.ts
Implements the changes described in #5672. This changes Util.fetchRecommendedShards to take in a FetchRecommendedShardsOption which includes guildsPerShard which is the number of guilds per shard the user wants and a boolean largeBotSharding option which decides if discord.js will round their shards up to a multiple of 16 which is [required for large bot sharding.](https://discord.com/developers/docs/topics/gateway#sharding-for-very-large-bots)
- This PR changes the library's interface (methods or parameters …
> feat(FetchRecommendedShardsOptions): account for large bot sharding

- src/structures/PermissionOverwrites.js
This PR fixes a bug that causes invalid permission flags to be reported back as `undefined`
e.g.
```js
channel.permissionOverwrites.edit(role, {
FOO_BAR: true,
});
```
Would throw this error: `RangeError [BITFIELD_INVALID]: Invalid bitfield flag or number: undefined.`
With this PR it will throw: `RangeError [BITFIELD_INVALID]: Invalid bitfield flag or number: FOO_BAR.`
> fix(PermissionOverwrites): throw better error if resolving option fails

- src/client/WebhookClient.js
- src/errors/Messages.js
- test/webhooktest.js
- typings/index.d.ts
This allows `WebhookClient`'s to be made with URLs, without the need of removing it or doing any type of parsing. This is useful for pass-through services like Webhook senders, etc., allowing a more convenient time for developers who don't want to use IDs and tokens. Example:
```ts
import { WebhookClient } from 'discord.js';
const webhook = new WebhookClient({ url: 'https://discord.com/api/webhooks/1234567890/abc' });
webhook.send({ content: 'Hi.' });
```
This PR also updates:
* Typings.
* Errors (URLs are passed to a RegEx and validated, although 100% perfection is not possible).
* Tests.
It now mandates initializing Webhook clients should have *one* object parameter, that can contain either ID + token or just a …
> feat(WebhookClient): allow creation of clients via URLs

- src/structures/Guild.js
- src/structures/Integration.js
- typings/index.d.ts
The method no longer exists (and/or bots don't have access to it)
> DiscordAPIError: 405: Method Not Allowed
> chore(Integration): Cleanup removed methods

- src/structures/Guild.js
The type definition for the `GuildTextChannelResolvable` in the documentation was missing, so I've gone ahead and added it in!
> docs(Guild): Add GuildTextChannelResolvable type definition

- src/structures/MessageMentions.js
`MessageMentions#members` works also in a ThreadChannel
> docs(MessageMentions): fix documentation for members property

- src/util/Constants.js
Fixes the name of the typedef for Constants.StickerTypes.
> docs(Constants): fix StickerTypes typedef

- src/structures/interfaces/TextBasedChannel.js
Because messageCreate fires twice per send if the bot sends it when cache size of MessageManager is Zero.
This PR fix that problem.
> fix(TextBasedChannel): Fix MessageCreate handling

- src/structures/WelcomeChannel.js
`WelcomeChannel#guild`'s return type should be either a `Guild` or an `InviteGuild`. `WelcomeGuild` was incorrectly documented here!
> docs(WelcomeChannel): Correct guild return type

- src/structures/Guild.js
> docs(Guild): Correct `GuildRolePosition` typo

- src/errors/Messages.js
- src/structures/Message.js
- typings/index.d.ts
Fixes a bug where #thread is null after a message update because it does not contain the thread data, relying on thread create instead.
> refactor(Message): make thread a getter for accuracy

- src/util/Constants.js
This documents the exported and separately documented typedef values in `util/Constants.js` as one parent object, covering all of the ones that can be used in an enum-like way, e.g. `Constants.MessageButtonStyles.PRIMARY`. As discord.js doesn't export the TS enums in its packaged typings, this alternative allows us to support the usage of Constants instead of relying on magic strings.
I'm not sure if I've done it correctly, since this definition is referencing the enum/object/whatever of all the available types rather than just one singular selected value from the typedef. Open to feedback on this.
Constants that are just an array of string values such as `Constants.MessageTypes` are not documented here to avoid confusion, as they can't be property-accessed like the other. Not sure how to …
> docs(Constants): document the Constants object for enum-like usage

- src/managers/GuildManager.js
The property `defaultMessageNotifications` on `GuildCreateOptions` used the `DefaultMessageNotifications` type definition, but it should be using instead the `DefaultMessageNotificationLevel` type definition or a number.
> docs(GuildManager): Correct `GuildCreateOptions` typo
