discordjs/discord.js

src/structures/Sticker.js
Neither of the two previous PR renamed `Snowflake` to `SnowflakeUtil` (to keep consistency with the file name), so here's it.
=> refactor(Sticker): rename Snowflake variable

src/client/websocket/handlers/APPLICATION_COMMAND_CREATE.js, src/client/websocket/handlers/APPLICATION_COMMAND_DELETE.js, src/client/websocket/handlers/APPLICATION_COMMAND_UPDATE.js, src/util/Constants.js, typings/index.d.ts
Adds support for the application command create/delete/update events because they were overlooked in #5448.
=> feat: add support for application command events

src/managers/GuildMemberManager.js
=> fix: typo in GuildMemberManager

src/structures/Guild.js
=> docs(Guild): add proper punctuation to #fetchOwner jsdoc

.husky/pre-commit, package-lock.json, package.json
=> chore: fix husky install

src/structures/CommandInteraction.js, typings/index.d.ts
This PR adds a new `InteractionDeferOptions` type to be more future-proof against additional optional parameters.
=> feat: InteractionDeferOptions

src/structures/CommandInteraction.js
=> docs: fix InteractionDeferOptions typedef

src/structures/Message.js
This PR adds an example for `message.reply`.
=> docs(Message): add example for message.reply

package-lock.json, package.json, typings/index.d.ts
=> types: use Snowflake type

src/client/websocket/WebSocketManager.js, src/managers/GuildApplicationCommandManager.js, src/structures/ApplicationCommand.js, src/structures/Message.js
=> docs: all the missing object -> Object changes

src/structures/ApplicationCommand.js
=> docs(ApplicationCommand): Typos in ApplicationCommandPermissionData

src/structures/PermissionOverwrites.js
=> fix(PermissionOverwrites): optional allow/deny OverwriteData

src/util/Structures.js, typings/index.d.ts
While working on a TypeScript project with the master branch you will get an error when trying to extend a ButtonInteraction structure. The ButtonInteraction class is being used in the `INTERACTION_CREATE` event handler as `Structure.get("ButtonInteraction");` which implies that it can be extended. So I added the ButtonInteraction class under the Extendable type. Also removed the MessageComponentInteraction from the JSDoc since it was not extendable either.
=> types(Extendable): add ButtonInteraction

src/structures/ClientApplication.js
=> fix(ClientApplication): freeze flags

src/managers/ChannelManager.js, src/managers/GuildBanManager.js, src/managers/GuildChannelManager.js, src/managers/GuildEmojiManager.js, src/managers/GuildManager.js, src/managers/GuildMemberManager.js, src/managers/MessageManager.js, src/managers/RoleManager.js, src/managers/UserManager.js, typings/index.d.ts
Just some small consistency things...optional params something something
=> refactor: fetch options consistency

src/structures/ButtonInteraction.js
=> docs(ButtonInteraction): fix typo

typings/index.d.ts
Check out the changes on the [TypeScript playground](https://www.typescriptlang.org/play?target=7&jsx=0#code/C4TwDgpgBAwgNgSwgO2FAvFArsg1sgewHdkBuAKHIHoAqcqG2LAJ2ZWHpqsoVQmYBmAQwDG0AELMCQgCYihAZ2ABRAG5C4AeTDAEBZAoA8AFQzY8hEgD4oAb3pQFACyHMZAfgBcUZFgC2AEb8FFBQIvrAEAAewF5QxhQAvpQyECJwrtACOCK6+lABUrLySmoaJgA0UAAKVgAUAsjedelIqN7wbcBV4Xwx3tUAlBg2xlW2ji5u3jipArwQMj0R0cADUIlxktJyiirqWjp6BoMDUn4IChAmANoAulYUqemZUNnIuccFRbulB5U1eqNZqtdgdRDsZZ9NY1YboUbjSauGTeXyBfhQyL9GobbzbYp7MqHPInM4EC5XEyPShUKhQG4AZScBCwcBkBQgdygBwQMnIhR2JX2GjqdThNlsiUGFAFBL+5VUBF5VSUzF4AHN6mKRnZEojeliYQByI0baX8n5ComGRXKuw+VH+ILMDZa8W6-UrbETJpQACMACYAMwbM0yy2Eg6i92SxHOZHeAAMYYtgsj5VVGrdOpNcamKKgyalpCgtKgACUIABHLAINgKKABqCgSBQVzq-zsBSpuXCuA2pVLRzANXITXRnWx+0G …
=> types: corrected shard broadcastEval

src/structures/interfaces/TextBasedChannel.js
- Updated the embed example for `TextBasedChannel#send`
=> docs(TextBasedChannel#send): update embeds example

README.md
It hardly ever worked and was almost always showing `repo or path not found or david internal error`.
=> docs(Readme): remove dependencies badge

src/structures/MessageSelectMenu.js
=> docs(MessageSelectMenu): fix options typings

src/managers/ThreadMemberManager.js
This PR fixes two small bugs in ThreadMemberManager:
* ThreadMemberManager#add throwing an error due to requesting the wrong URL
* ThreadMemberManager#fetch throwing error(s) due to using the wrong method
=> fix(ThreadMemberManager): fix ThreadMemberManager#add and ThreadMemberManager#fetch

src/structures/Channel.js
=> docs(Channel): fix description of thread channel types

typings/index.d.ts
Readds the followUp type on CommandInteraction after it was accidentally removed in #5831.
=> types(CommandInteraction): Readd followUp type

src/structures/Message.js
Channel can be a `ThreadChannel`
- I know how to update typings and have done so, or typings don't need updating.
=> docs(Message): Add ThreadChannel as a channel type

typings/index.d.ts
A few fixes for places that ThreadChannel should be a valid type.
=> types: few missing thread channels

src/structures/ApplicationCommand.js
=> fix(ApplicationCommand): fix typo in JSDoc

src/structures/MessageButton.js, src/structures/MessageSelectMenu.js, typings/index.d.ts
I noticed a small issue, although I am not sure about it.
=> types(MessageSelectMenu): fix typings

src/managers/ThreadManager.js
This PR fixes the `fetchAll` check for private Threads in `ThreadManager#fetchArchived`.
=> fix(ThreadManager): fixed wrong private and fetchAll check

src/client/actions/ChannelUpdate.js, src/managers/ThreadMemberManager.js, src/structures/ThreadChannel.js, typings/index.d.ts
Threads fixup part 2: electric boogaloo
=> fix: correct permissions checks and cache on update

src/managers/PermissionOverwriteManager.js
=> fix(PermissionOverwriteManager): pass ID to API correctly

src/structures/GuildChannel.js
=> fix(GuildChannel): use map method on cache not its manager

src/structures/MessageEmbed.js
=> docs: add Partial typedef

typings/index.d.ts, typings/index.ts
So you want better typings huh
=> types: better fullPermissions typings

src/index.js
This is a small nit from #6027
=> chore: remove unnecessary getter

typings/enums.d.ts, typings/index.d.ts, typings/index.ts
This cleans up the exported typings. Because the diff is not helpful at all, I split it up into multiple commits, so this should be reviewed commit by commit instead.
- I know how to update typings and have done so (Obviously)
=> refactor(typings): general cleanup

src/structures/SelectMenuInteraction.js, typings/index.d.ts
=> fix(SelectMenuInteraction): set values to empty array if not provided

src/structures/MessagePayload.js, typings/index.d.ts
This PR fixes several incorrect typings and the JSDoc return type for MessagePayload#create.
=> docs: fixed several typings and MessagePayload#create JSDoc

typings/index.d.ts, typings/index.ts
This PR resolves some unreachable method overloads in some classes, which caused some type inaccuracies.
cc: @ckohen 
=> types: fixed unreachable overloads

src/client/actions/GuildDelete.js, src/client/actions/MessageReactionAdd.js, src/client/actions/MessageReactionRemove.js, src/client/actions/MessageReactionRemoveAll.js, src/client/actions/MessageReactionRemoveEmoji.js, src/client/actions/TypingStart.js, src/structures/GuildChannel.js
This PR fixes a bad check suggested in https://github.com/discordjs/discord.js/pull/6035#pullrequestreview-698709229 that would always return false since you can't check for values in an array.
=> fix: channel type check in actions

src/rest/APIRequest.js
Remove the usage of var in APIRequest class
=> chore(ApiRequest): remove mention of var

package.json, src/client/actions/ActionsManager.js
I've looked at the `ActionsManager.js` file, and saw that it was pretty impractical. So, here's my easier and way less complex version using `fs`.
=> refactor(ActionsManager): less complex code

src/util/Constants.js, typings/index.d.ts
The correct scope name is `identify` as referenced by Discord and the comment in `Constants.js`.
=> Updates `identity` to correct scope name of `identify`

src/structures/Message.js
Made an oopsie in a rebase, here comes the fix.
=> fix(Message): fix typo in sticker_items

src/structures/GuildAuditLogs.js, typings/index.d.ts
Audit Logs are fun, I don't use them so my testing may have missed something.
=> feat(GuildAuditLogs): add threads

src/structures/Channel.js
Oops, did everything possible for threads and channels...but not updating a channel 🤦 
=> fix(Channel): add default for destructured options

package.json, src/rest/RequestHandler.js
Discord's main organization name has been changed quite a long time ago, and the Discordapp name is considered obsolete, it is no longer being used.
=> chore: update discord domain name 

package-lock.json, package.json
=> chore(Deps): update `discord-api-types` to `0.21.0`

README.md
=> docs: update readme node version requirement

src/structures/GuildChannel.js, src/structures/Role.js, src/structures/interfaces/TextBasedChannel.js, src/util/Util.js
=> fix: array/keyArray removed

typings/index.d.ts, typings/rawDataTypes.d.ts, typings/tests.ts
-types is now a real dep so lets use it to the fullest
(sorry about the diff...its kinda massive, tried to make it easier by separating the raw tpes)
=> types: use api-types for stricter typings

package-lock.json, package.json
=> chore(Deps): update `discord-api-type`

src/util/Util.js
fixes collection import, no more chance of circular dependency either, so moved the import to the top
=> fix(Util): fix collection import

package-lock.json, package.json, src/util/Formatters.js, typings/index.d.ts
=> chore(Deps): update `@discordjs/builders`

src/structures/GuildChannel.js
This fixes an issue introduced by #6210 that made setParent not work at all. Fixes #6275 
=> fix(GuildChannel): setParent not working

README.md
Added a period to the first console.log for consistency. Corrected typo in second console.log to read "Successfully".
=> Fixed typos in the slash command register example

src/structures/Message.js
For ThreadChannel, errors occur because channel.threads do not exist.
This PR fix that problem.
=> fix(Message): fix thread getter

.github/workflows/deploy.yml, .github/workflows/publish-dev.yml, .github/workflows/test-cron.yml, .github/workflows/test.yml
The package was updated to node 16 on https://github.com/discordjs/discord.js/commit/a56ba097dce5b476939a10d6dc9250a966356594 so might as well update the CI too
=> ci: update to node 16

src/managers/GuildMemberManager.js
Fixed the redundant size checks (they aren't working for some time now anymore and with our caching strategy its completely haywire).
Additionally the way the checking for option || force is done could maybe be done differently? I'm open to suggestions on that front.
=> fix(GuildMemberManager): fetchMany fixes

README.md
The most important fix you'll ever see
=> docs: fix bad indentation

src/managers/GuildMemberManager.js
Refactors / Fixes the _fetchMany function in a non-breaking but also non-stupid way to actually work as intended (since this is not a REST endpoint either).
Reasons why this is non-breaking:
The functionality before was inherently broken and could not be relied on in anyway shape or form in the first place.
=> fix(GuildMemberManager): refactor fetchMany

src/managers/GuildMemberRoleManager.js
Fixed a typo in GuildMemberRoleManager
=> fix(GuildMemberRoleManager): typo

src/util/Constants.js
It's gonna happen again soon:tm:
=> docs: switch urls from upstream rearranging

src/managers/ApplicationCommandPermissionsManager.js, src/structures/ApplicationCommand.js, src/util/Constants.js
Leaving the ones in CommandInteraction untouched as those will change with #6176 
=> docs: update links for api-docs

src/managers/RoleManager.js
=> docs(RoleManager): error in examples

src/structures/Channel.js
=> refactor(Channel): make delete async

src/structures/Message.js
fixes a typo introduced in #6071 
=> fix(Message): fix typo

src/index.js
This PR adds ContextMenuInteraction to the index.js file.
=> feat: export ContextMenuInteraction

typings/index.d.ts
=> typings(GuildChannel): Added missing typing

src/util/DataResolver.js
=> docs(BufferResolvable): add warning for URL input

src/structures/ClientPresence.js, src/structures/ClientUser.js, typings/index.d.ts
I noticed that the ClientPresence class was empty on the docs as it did not extend Presence as it should and none of its methods were documented. Along with that, this class didn't appear in the typings either, and nor was Client#presence present either. This PR fixes all of that. One thing to keep in mind is that I made the set method public but this may not be wanted to please let me know if this should be changed.
Fixes #6460.
=> types(ClientPresence): add type declarations and docs

src/managers/MessageManager.js
=> docs(MessageManager): fix typo

src/index.js
Please describe the changes this PR makes and why it should be merged:
This PR adds BaseCommandInteraction to the index.js file.
This PR changes the library's interface (methods or parameters added)
=> feat: export BaseCommandInteraction

src/managers/ThreadManager.js
Fixes a typo. Also tweaked the wording to refer to the guild's features as this is more accurate.
=> docs(ThreadManager): Fix typo

src/structures/MessageAttachment.js
fixes an issue from #6509 that wasn't caught
=> fix(MessageAttachment): re-assign name

src/util/Constants.js
=> docs(Constants): Fix interaction type link

src/structures/WidgetMember.js
Fixes a typo for `WidgetMember.deaf`.
=> docs(WidgetMember): fix typo for deaf

src/managers/StageInstanceManager.js, typings/index.d.ts
For consistency with other channel `@typedef`s, this has been added.
=> types: `@typedef` for `StageChannelResolvable`

.github/ISSUE_TEMPLATE/bug_report.yml
Partials should not be required (probably pasted that from intents).
=> chore: issue forms

src/util/Constants.js, typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/3651
this might not actually ship
=> feat(MessageTypes): add CONTEXT_MENU_COMMAND (23)

src/structures/WelcomeChannel.js, typings/index.d.ts
Store channels can be used in Welcome Screens.
=> types(WelcomeChannel): Allow store channels

typings/index.d.ts
Leftover from #6629, fixes #6655
=> types(MessageOptions): allow APIEmbed

src/util/Permissions.js, typings/index.d.ts
* https://github.com/discord/discord-api-docs/pull/3805
=> feat(Permissions): add `START_EMBEDDED_ACTIVITIES`

src/structures/ApplicationCommand.js, typings/index.d.ts
🚀 
- https://github.com/discord/discord-api-docs/pull/3825
=> feat(ApplicationCommand): add support for channel_types

src/client/BaseClient.js, src/client/Client.js, src/client/actions/ActionsManager.js, src/client/websocket/WebSocketManager.js, src/client/websocket/WebSocketShard.js, src/rest/APIRequest.js, src/sharding/Shard.js, src/sharding/ShardClientUtil.js, src/sharding/ShardingManager.js, src/structures/interfaces/Collector.js, src/util/DataResolver.js, src/util/Util.js, test/createGuild.js, test/sendtest.js, test/tester1000.js, test/tester2000.js, test/webhooktest.js
- https://github.com/nodejs/node/issues/38343
- https://nodejs.org/api/modules.html#modules_core_modules
=> refactor: use the `node:` protocol

typings/index.d.ts
Docs already reflect that, just the typings that don't include Snowflakes
=> types(Role): Role#comparePositionTo accepts RoleResolvable

src/client/websocket/handlers/READY.js, src/managers/GuildBanManager.js, src/managers/GuildChannelManager.js, src/managers/GuildManager.js, src/managers/GuildMemberManager.js, src/managers/RoleManager.js, src/managers/StageInstanceManager.js, src/structures/GuildChannel.js, src/structures/Webhook.js
=> perf: use logical assignments instead of if statements

src/structures/Role.js
=> fix(Role): toJSON() throwing due to permission bigints

src/structures/MessageButton.js, src/structures/MessageSelectMenu.js
More accurate links to Discord's documentation for the `.toJSON()` methods of buttons and select menus.
=> docs: Better links for `.toJSON()` of button and select menu

src/client/actions/WebhooksUpdate.js, typings/index.d.ts
A `NewsChannel` may be emitted for this.
=> types(WebhooksUpdate): Allow `NewsChannel`s

src/rest/APIRequest.js, src/rest/RequestHandler.js, src/structures/Guild.js, test/sendtest.js, test/webhooktest.js
There were still a few places where optional chaining could be used but wasn't
=> refactor: use optional chaining

package.json
Discord.JS has a documentation site, so homepage changed to `https://discord.js.org`.
=> chore(package): change homepage

package-lock.json, package.json
prepare for next dev release
note: please take action before next 4 hour because dev workflow will be executed after that.
=> chore: next dev version

src/util/ApplicationFlags.js, typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/3999
=> feat(ApplicationFlags): add message content intent flags

src/util/ActivityFlags.js, typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/3877
=> feat: add new activity flags

src/structures/Guild.js
The `Guild#owner` has been removed due to changes in v13, so the method of getting the displayName has been changed.
(Due to my limited English, some of the sentences may not be correct)
=> docs(Guild): fix setOwner() example

src/client/BaseClient.js, src/client/Client.js, src/rest/RequestHandler.js, typings/index.d.ts
Noticed that its actually possible to listen to these events on a webhook client, so i've fixed documentation and typings for that. Shoutout to @Jiralite for being in a debugging state that needed the events, making realize this.
=> types(Events): rest events can be emitted on BaseClient

README.md
Adds NPM installation instructions on `@discordjs/voice` package to reflect with other optional packages in the README.
=> docs(README): add installation instruction on @discordjs/voice

typings/index.d.ts, typings/tests.ts
I apparently forgot how to TypeScript for a second
=> types: unify ApplicationCommandManager#create overloads

package-lock.json, package.json
=> chore: bump typescript to 4.5

src/managers/ThreadManager.js, typings/index.d.ts
Simplifies a lot of the type logic, and opts for manual mapped types instead.
=> chore: collector type cleanup

typings/index.d.ts
These interfaces are no longer needed because of #6991 
=> types: remove unneeded collector types

package.json
The contributors were probably copied from [discord.js-modules](https://github.com/discordjs/discord.js-modules/blob/7f1c9be817bbc6a4a11a726c952580dd3cb7b149/package.json#L22-L27), which somehow missed me, so I'm adding myself 😅
=> chore: add myself as contributor in package.json

.github/tsc.json
Format [.github/tsc.json](.github/tsc.json) using Prettier.
=> chore: format .github/tsc.json

src/util/Constants.js
Moves the warning after the type.
=> docs(Constants): Adjust `GUILD_STORE` warning placement

typings/index.d.ts, typings/index.test-d.ts
These types can be a lil' more specific! For example, the `extra` when you update a stage instance is obviously going to be a `StageChannel` and not any other `GuildChannel`.
=> types(GuildAuditLog): Strengthen types

src/structures/Sticker.js
Fixes a typo introduced by #7074.
=> docs(Sticker): Fix typo

src/index.js
added Sweepers to the exports from index.js, typings already export it
=> feat: export Sweepers

.github/workflows/auto-deprecate.yml
Continuation of #6930, looks like I missed a spot in the auto deprecate workflow, so this PR fixes it
=> ci: use correct capitalization of npm

package-lock.json, package.json
=> chore: bump dapi-types

packages/discord.js/src/util/Sweepers.js
=> fix(sweepers): provide default for object param

packages/discord.js/src/managers/GuildMemberManager.js
This fixes the examples for the kick and ban methods listed on the docs
=> docs: fixes the examples for kick and ban

packages/discord.js/src/structures/interfaces/TextBasedChannel.js
This PR fixes `#createMessageComponentCollector` description which states that the method creates button interaction collector.
=> docs(TextBasedChannel): fix #createMessageComponentCollector description

packages/rest/__tests__/DiscordAPIError.test.ts, packages/rest/__tests__/REST.test.ts, packages/rest/src/lib/REST.ts, packages/rest/src/lib/RequestManager.ts, packages/rest/src/lib/errors/DiscordAPIError.ts, packages/rest/src/lib/errors/HTTPError.ts, packages/rest/src/lib/handlers/IHandler.ts, packages/rest/src/lib/handlers/SequentialHandler.ts
=> refactor(rest): rename attachment to file

.gitignore, .vscode/extensions.json
This PR adds 2 extension recommendations to the .vscode folder. These are Prettier and ESLint, the formatter and linter used by discord.js. This is so that new users who install these extensions are able to notice errors before pushing and to fix them more easily in case they don't get automatically fixed by the pre-commit hook. Along with that the .gitignore file was updated to allow for this file to be committed but no others inside the .vscode folder
=> chore(VSCode): add extension recommendations

packages/builders/package.json, packages/collection/package.json
Same as https://github.com/discordjs/discord.js-modules/pull/83
=> chore: add myself to contributors

packages/discord.js/src/structures/Role.js, packages/discord.js/typings/index.d.ts
This removes deprecations from #7096.
=> refactor(RoleManager): Remove `comparePositions()`

packages/discord.js/src/structures/MessageContextMenuCommandInteraction.js, packages/discord.js/src/structures/UserContextMenuCommandInteraction.js
=> fix(Structues): rename old module's name

packages/discord.js/src/client/actions/InteractionCreate.js
Fixes the structure used in interaction create.
=> fix(InteractionCreate): use ChatInputCommandInteraction instead

packages/discord.js/src/structures/ChatInputCommandInteraction.js, packages/discord.js/src/structures/CommandInteraction.js
This could be the last one, maybe not.
=> docs: fix command interaction docs

packages/discord.js/src/util/Sweepers.js
Add the missing sweepStickers function.
=> fix(Sweepers): add sweepStickers function

packages/discord.js/src/client/actions/ChannelDelete.js, packages/discord.js/src/client/actions/GuildDelete.js, packages/discord.js/src/client/actions/GuildEmojiDelete.js, packages/discord.js/src/client/actions/GuildMemberRemove.js, packages/discord.js/src/client/actions/GuildRoleDelete.js, packages/discord.js/src/client/actions/GuildStickerDelete.js, packages/discord.js/src/client/actions/MessageDelete.js, packages/discord.js/src/client/actions/MessageDeleteBulk.js, packages/discord.js/src/client/actions/StageInstanceDelete.js, packages/discord.js/src/client/actions/ThreadDelete.js, packages/discord.js/src/structures/Channel.js, packages/discord.js/src/structures/Emoji.js, packages/discord.js/src/structures/Guild.js, packages/discord.js/src/structures/GuildMember.js, packages/discord.js/src/structures/Message.js, packages/discord.js/src/structures/Role.js, packages/discord.js/src/structures/StageInstance.js, packages/discord.js/src/structures/Sticker.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Fixes #7091, please check the linked issue for more information as for what motivated this change.
=> refactor: remove `deleted` field

packages/discord.js/src/client/WebhookClient.js
Made the webhook url regex more inclusive for webhooks that include the api version.
=> fix(WebhookClient): Updated webhook url regex

packages/discord.js/src/structures/Role.js
Remove unused process in Role file.
=> fix(Role): remove unused process

packages/discord.js/src/structures/GuildScheduledEvent.js
=> fix: SnowflakeUtil import

README.md, packages/builders/README.md, packages/collection/README.md, packages/discord.js/README.md, packages/voice/README.md
The old repository is archived
=> chore: update readme links

package.json
Reverts discordjs/discord.js#7236
=> revert "chore: optimize Turbo pipelines"

packages/discord.js/src/structures/Interaction.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Adds support for locales in interactions.
Ref:
- https://github.com/discord/discord-api-docs/pull/4265
=> feat: Add Locales to Interactions

packages/collection/src/index.ts
See: 
- https://github.com/discordjs/collection/issues/58
=> refactor: make `intersect` perform a true intersection

packages/collection/src/index.ts
Provides a utility type for ensuring a given collection doesn't get mutated.
=> types: add `ReadonlyCollection`

packages/discord.js/src/index.js
This fixes ApplicationCommandType export.
=> fix(exports): export ApplicationCommandType properly

packages/discord.js/src/client/actions/MessageCreate.js, packages/discord.js/src/client/actions/MessageDelete.js, packages/discord.js/src/client/actions/MessageDeleteBulk.js, packages/discord.js/src/client/actions/MessageReactionAdd.js, packages/discord.js/src/client/actions/MessageReactionRemove.js, packages/discord.js/src/client/actions/MessageReactionRemoveAll.js, packages/discord.js/src/client/actions/MessageReactionRemoveEmoji.js, packages/discord.js/src/client/actions/MessageUpdate.js, packages/discord.js/src/client/actions/TypingStart.js, packages/discord.js/src/structures/Channel.js, packages/discord.js/src/util/Sweepers.js, packages/discord.js/typings/index.d.ts
This PR creates typeguards for every channel type and renames the existing ones to isTextBased and isVoiceBased, as this was already what they did, allowing for accurate isText and isVoice typeguards.
=> feat(Channel): improve typeguards

packages/discord.js/src/managers/RoleManager.js, packages/discord.js/src/structures/GuildChannel.js
=> refactor: use setPosition inside edit

packages/discord.js/.eslintrc.json, packages/discord.js/src/client/BaseClient.js, packages/discord.js/src/client/websocket/WebSocketShard.js, packages/discord.js/src/managers/GuildManager.js, packages/discord.js/src/managers/GuildMemberManager.js, packages/discord.js/src/rest/APIRequest.js, packages/discord.js/src/sharding/Shard.js, packages/discord.js/src/structures/GuildTemplate.js, packages/discord.js/src/structures/interfaces/Collector.js, packages/discord.js/src/util/Sweepers.js
Fixes issue mentioned in https://github.com/discordjs/discord.js/pull/7157#issuecomment-1003307104
=> fix: import `clear{Timeout,Interval}` from `node:timers`

.github/workflows/documentation.yml, packages/rest/.gitignore, packages/rest/docs/README.md, packages/rest/docs/index.yml, packages/rest/package.json, packages/rest/scripts/docs.mjs
This adds the long awaited REST docs.
=> feat: rest docs

package.json
=> ci: fix docs workflow

packages/rest/__tests__/CDN.test.ts, packages/rest/src/lib/CDN.ts
=> chore(cdn): default to animated images

packages/discord.js/src/structures/Invite.js, packages/discord.js/typings/index.d.ts
https://github.com/discordjs/discord.js/pull/7089#discussion_r767199403
=> refactor(invite): make `channel` and `inviter` getters

packages/discord.js/src/structures/Interaction.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
@almostSouji will be happy about this
=> feat(interaction): add `isRepliable` type guard

packages/builders/src/index.ts
=> fix(builders): dont export `Button` component stuff twice

packages/discord.js/src/structures/StageInstance.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/4296
- This PR **only** includes non-code changes
=> docs(StageInstance): deprecate discoverableDisabled

packages/discord.js/src/managers/GuildChannelManager.js
=> fix(guildchannelmanager): remove reverse enum lookup

packages/rest/src/lib/RequestManager.ts
Discord may or may not care about  the ?, I didn't experience it being a problem, but it seems like best practice to not send it
=> fix(rest): don't add empty query

packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionBase.ts
=> types: make `required` a boolean

packages/builders/__tests__/messages/embed.test.ts, packages/builders/src/messages/embed/Embed.ts
This PR adds the Embed#setFields method to /builders, for compatibility with djs and to prepare for #7067
=> feat(embed): add setFields

packages/discord.js/src/structures/MessagePayload.js, packages/discord.js/src/structures/Webhook.js, packages/discord.js/src/structures/interfaces/InteractionResponses.js, packages/discord.js/src/structures/interfaces/TextBasedChannel.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/4356
- https://github.com/discord/discord-api-docs/pull/4357
=> feat: allow setting message flags when sending

packages/discord.js/src/managers/GuildInviteManager.js, packages/discord.js/src/structures/Integration.js, packages/discord.js/src/util/Constants.js, packages/discord.js/src/util/EnumResolvers.js, packages/discord.js/typings/index.d.ts
- fixes two more enum issues 
- strengthens enum resolver typings as suggested by @vladfrangu  https://github.com/discordjs/discord.js/pull/7331#pullrequestreview-862802014
I wasn't sure what to name the types so please let me know if they should be changed.
=> feat(enumResolvers): strengthen typings

packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/typings/index.d.ts
=> fix(thread): don't assign directly to getters

packages/discord.js/src/structures/Webhook.js
#7298 
This PR renames old method name to new one.
=> fix(Webhook): use correct method name

packages/discord.js/src/util/EnumResolvers.js
This PR adds the EnumResolvers class to the docs
=> docs: add EnumResolvers

packages/discord.js/src/managers/GuildMemberManager.js
=> fix(guildmembermanager): use rest in edit

packages/discord.js/package.json
Fixes documentation source link.
=> chore: Specify new root

.github/CONTRIBUTING.md
Apparently, we're using Yarn now, so I think this should be updated. I also provided a link for how to install Yarn for people who don't know.
=> chore(CONTRIBUTING.md): update to yarn instructions

packages/discord.js/src/structures/Channel.js
This pr fixed `isDMBased` docs
=> docs(channel): fix `isDMBased` docs

packages/discord.js/src/structures/ClientPresence.js
=> fix(clientpresence): fix used opcodes

packages/discord.js/src/structures/GuildMember.js, packages/discord.js/typings/index.d.ts
=> fix(guildmember): make `pending` nullable

packages/discord.js/src/structures/InteractionCollector.js, packages/discord.js/typings/index.d.ts
Small corrections to the options for interaction collectors (found thx to @favna). `guild` and `channel` support resolvables, not just full structures
=> typings: correct types for InteractionCollector guild and channel

packages/discord.js/typings/index.test-d.ts, packages/rest/__tests__/util.ts
=> fix(ci): ci error

packages/builders/__tests__/components/actionRow.test.ts, packages/builders/src/components/ActionRow.ts, packages/builders/src/components/selectMenu/UnsafeSelectMenu.ts
=> fix(components): setX should take rest parameters

packages/discord.js/src/client/actions/MessageReactionAdd.js, packages/discord.js/src/client/actions/MessageReactionRemove.js, packages/discord.js/src/client/actions/MessageReactionRemoveAll.js, packages/discord.js/src/client/actions/MessageReactionRemoveEmoji.js
=> refactor(actions): use optional chaining

packages/discord.js/src/managers/ThreadManager.js, packages/discord.js/typings/index.d.ts
Removes a duplicate rate limit property.
=> types: Remove duplicate rate limit for thread creation

packages/discord.js/src/structures/Invite.js, packages/discord.js/src/structures/InviteStageInstance.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/4479
=> refactor: deprecate invite stage instance

src/client/actions/ThreadCreate.js, typings/index.d.ts
Backports #7386 to version 13.
=> feat(thread): v13 add `newlyCreated` to `threadCreate` event

packages/builders/src/components/ActionRow.ts, packages/builders/src/components/Component.ts, packages/builders/src/components/selectMenu/UnsafeSelectMenu.ts, packages/builders/src/messages/embed/UnsafeEmbed.ts
Future proofs for any new fields added in the future.
=> refactor: make `data` public in builders

.github/ISSUE_TEMPLATE/bug_report.yml
Typo from converting over to discord-api-types enumerables.
=> chore: Correct gateway intent on issue form

src/structures/MessagePayload.js
=> fix(MessagePayload): v13 don't set reply flags to target flags

packages/discord.js/typings/index.test-d.ts
fix a typo `MessageActionRow` to `ActionRow`
=> fix(test): `MessageActionRow` to `ActionRow`

packages/discord.js/package.json, packages/discord.js/src/util/DataResolver.js, packages/discord.js/src/util/Util.js, packages/discord.js/test/sendtest.js, packages/discord.js/test/webhooktest.js, yarn.lock
Partially transitions from node-fetch to undici.
=> feat(discord.js): partial transition to undici

src/managers/GuildScheduledEventManager.js, typings/index.d.ts
=> feat(scheduledevents): add image option (v13)

packages/builders/README.md
The link doesn't work on the documentation website and npm - only GitHub. This should now be fully resolved.
=> docs: Completely fix builders example link

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Fixes situations where `type` would be required when providing `API` types. Also makes proper fields required in each component.
=> types: fix component *Data types

src/structures/GuildPreview.js, typings/index.d.ts
Backports #7152 to version 13.
=> feat(GuildPreview): Add stickers to version 13

src/structures/GuildMember.js
=> fix: check if member has admininistrator on `moderatable` (v13)

package.json, turbo.json, yarn.lock
=> chore: bump turborepo

packages/discord.js/src/managers/MessageManager.js
fixes the route for pinning messages
=> fix(MessageManager): pin route

packages/discord.js/src/managers/GuildStickerManager.js
=> fix(GuildStickerManager): correctly access guild ID

packages/discord.js/src/structures/interfaces/InteractionResponses.js
=> refactor(InteractionResponses): use ClientOptions.jsonTransformer

packages/discord.js/src/structures/Embed.js
setColor shouldn't exist on Embed
=> feat(embed): remove Embed.setColor

packages/discord.js/.eslintrc.json, packages/discord.js/src/structures/GuildAuditLogs.js, packages/discord.js/src/structures/GuildChannel.js, packages/discord.js/src/structures/GuildTemplate.js, packages/discord.js/src/structures/Invite.js, packages/discord.js/src/structures/Message.js, packages/discord.js/src/structures/MessageMentions.js, packages/discord.js/src/structures/PermissionOverwrites.js, packages/discord.js/src/util/ActivityFlagsBitField.js, packages/discord.js/src/util/ApplicationFlagsBitField.js, packages/discord.js/src/util/BitField.js, packages/discord.js/src/util/DataResolver.js, packages/discord.js/src/util/Formatters.js, packages/discord.js/src/util/IntentsBitField.js, packages/discord.js/src/util/MessageFlagsBitField.js, packages/discord.js/src/util/Options.js, packages/discord.js/src/util/PermissionsBitField.js, packages/discord.js/src/util/SystemChannelFlagsBitField.js, packages/discord.js/src/util/ThreadMemberFlagsBitField.js, packages/discord.js/src/util/UserFlagsBitField.js, packages/discord.js/typings/index.d.ts
Replaces the older direct prop assignments on structures with static fields.
=> refactor: use `static` fields

packages/builders/__tests__/components/selectMenu.test.ts, packages/builders/src/components/Assertions.ts, packages/builders/src/components/selectMenu/SelectMenu.ts
Select menu options are now properly validated.
=> fix: Validate select menu options

packages/discord.js/src/structures/GuildScheduledEvent.js
The `image` field may be missing
- https://github.com/discord/discord-api-docs/pull/4564
=> fix(GuildScheduledEvent): handle missing `image`

src/structures/GuildScheduledEvent.js
Backports the following pull request into v13:
- #7625 
=> fix(GuildScheduledEvent): handle missing `image` for v13

packages/discord.js/src/structures/Guild.js, packages/discord.js/typings/index.d.ts
Closes #7631
https://github.com/discordjs/discord.js/blob/dcd479767b6ec980a373f2ea1f22754f41661c1e/packages/discord.js/typings/index.d.ts#L1013
https://github.com/discordjs/discord.js/blob/dcd479767b6ec980a373f2ea1f22754f41661c1e/packages/discord.js/typings/index.d.ts#L1032
https://github.com/discordjs/discord.js/blob/dcd479767b6ec980a373f2ea1f22754f41661c1e/packages/discord.js/typings/index.d.ts#L1030
https://github.com/discordjs/discord.js/blob/dcd479767b6ec980a373f2ea1f22754f41661c1e/packages/discord.js/typings/index.d.ts#L1029
- I know how to update typings and have done so, or typings …
=> fix(GuildEditData): some fields can be null

.github/workflows/publish-dev.yml
This pull request aims to resolve #7467.
A small commit hash consisting of only numbers and starting with 0 would fail. However, this can be mitigated by separating the time & small commit hash via `-` instead of `.`. Visit [this link](https://regex101.com/r/UiZOqX/1) to test this against the regular expression.
=> ci: Resolve potentially invalid version

packages/discord.js/src/structures/ClientApplication.js, packages/discord.js/typings/index.d.ts
Ref:
- https://github.com/discord/discord-api-docs/pull/4112
=> feat(ClientApplication): app authorization links and tags

packages/discord.js/src/structures/IntegrationApplication.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/4686
=> refactor(IntegrationApplication): remove `summary`

src/managers/GuildChannelManager.js, src/managers/GuildEmojiManager.js, src/managers/GuildStickerManager.js, src/managers/RoleManager.js, src/structures/BaseGuildTextChannel.js, src/structures/GuildChannel.js, src/structures/GuildEmoji.js, src/structures/Role.js, src/structures/Sticker.js, src/structures/ThreadChannel.js, typings/index.d.ts
This PR backports #7300 and #7446 into v13. This was done through a cherry-pick which should mean the changes are the same, however, due to the rest client change in v14 there were some conflicts I had to resolve which could've caused me to miss something, although that's unlikely
=> feat: add methods to managers for v13

src/managers/GuildChannelManager.js
Fixes #7770, caused by an oversight from #7611
=> fix(GuildChannelManager): `delete` method using the wrong id

src/client/actions/InteractionCreate.js
Backports #7755 to version 13.
=> fix(InteractionCreateAction): Ensure text-based channel for caching messages (v13)

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
=> types(collectorOptions): `filter` should have a `collected` argument

packages/discord.js/src/managers/StageInstanceManager.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/4706
=> feat(StageInstanceManager): add `sendStartNotification` option to create

packages/discord.js/package.json, packages/discord.js/src/structures/Channel.js, packages/discord.js/src/structures/DirectoryChannel.js, packages/discord.js/typings/index.d.ts, yarn.lock
Adds `GUILD_DIRECTORY` channel type, and the `HUB` guild feature.
- https://github.com/discord/discord-api-docs/pull/4701
=> feat: add guild directory support

packages/discord.js/src/structures/ButtonBuilder.js, packages/discord.js/src/structures/ModalBuilder.js, packages/discord.js/src/structures/SelectMenuBuilder.js
oversights from #7718 and #7711
=> fix(builders): add constructor default param

packages/builders/src/components/ActionRow.ts, packages/builders/src/components/Component.ts, packages/builders/src/components/Components.ts, packages/builders/src/components/button/UnsafeButton.ts, packages/builders/src/components/selectMenu/UnsafeSelectMenu.ts, packages/builders/src/components/textInput/UnsafeTextInput.ts, packages/builders/src/interactions/modals/UnsafeModal.ts, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Greatly simplifies and reduces types in builders by removing duplicated and/or unnecessary typings. (Negative diff yay!)
=> chore(builders): simplify types

src/structures/IntegrationApplication.js, src/structures/StoreChannel.js, src/structures/VoiceRegion.js, src/structures/interfaces/Application.js, src/util/Util.js, typings/index.d.ts
Adds deprecations due to the following:
- #6759
- #7250
- #7729
- #7780
=> refactor: Deprecate v13 properties and methods

packages/discord.js/typings/index.d.ts
=> types(ThreadChannel): fix autoArchiveDuration types

typings/index.d.ts
Fix typings not existing for already existing code.
https://github.com/discordjs/discord.js/blob/v13/src/structures/ModalSubmitInteraction.js#L47-L51
=> Fix ModalSubmitInteraction Typings

packages/discord.js/src/structures/SelectMenuBuilder.js, packages/discord.js/typings/index.d.ts
It resolves changes made by #7797 and non in-time rebased #7759
=> fix(SelectMenuBuilder): options array

packages/discord.js/src/structures/Presence.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/commit/5822b0bc97fa8ad1f9e87d0426a309cbf680c5d3
=> refactor(Activity): remove undocumented properties

packages/discord.js/src/managers/MessageManager.js
This property is required in this type definition.
=> docs(MessageManager): Require `message` in `FetchMessageOptions`

packages/discord.js/src/structures/Integration.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/4803
=> fix(Integration): Mark `enabled` as nullable

src/structures/MessageEmbed.js
This PR fixes a typo in `MessageEmbed#provider`
=> fix(MessageEmbed): fix a typo

packages/discord.js/typings/index.d.ts
=> types(guildScheduledEvent): Mark `entityMetadata` as nullable

packages/builders/__tests__/interactions/ContextMenuCommands.test.ts, packages/builders/__tests__/interactions/SlashCommands/SlashCommands.test.ts, packages/builders/src/interactions/contextMenuCommands/ContextMenuCommandBuilder.ts, packages/builders/src/interactions/slashCommands/Assertions.ts, packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts, packages/builders/src/interactions/slashCommands/SlashCommandSubcommands.ts, packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionBase.ts, packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionWithChoicesAndAutocompleteMixin.ts, packages/builders/src/interactions/slashCommands/mixins/NameAndDescription.ts
=> fix: add localizations for subcommand builders and option choices

packages/builders/__tests__/messages/embed.test.ts, packages/builders/package.json, packages/builders/src/components/Assertions.ts, packages/builders/src/components/textInput/Assertions.ts, packages/builders/src/interactions/contextMenuCommands/Assertions.ts, packages/builders/src/interactions/modals/Assertions.ts, packages/builders/src/interactions/slashCommands/Assertions.ts, packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionWithChoicesAndAutocompleteMixin.ts, packages/builders/src/messages/embed/Assertions.ts, yarn.lock
updated shapeshift to v3 for faster object validation
=> chore: bump shapeshift for faster object validation

packages/rest/__tests__/RequestHandler.test.ts, packages/rest/src/index.ts
=> fix(REST): remove dom types

packages/collection/src/index.ts, packages/rest/src/lib/RequestManager.ts, packages/voice/src/audio/AudioResource.ts, packages/voice/src/networking/VoiceUDPSocket.ts, packages/voice/src/receive/VoiceReceiver.ts, tsconfig.json
This PR enables the `noUncheckedIndexAccess` TS compiler option, a generally useful safety feature.
=> chore: enable noUncheckedIndexAccess

packages/rest/src/lib/CDN.ts
- https://github.com/discord/discord-api-docs/pull/4955
=> feat(rest): add guild member banner cdn url

packages/discord.js/src/managers/CategoryChannelChildManager.js, packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/4867
=> feat(guildChannelManager): add `videoQualityMode` option for `create()`

src/util/Constants.js
There is a missing type in jsdoc and I added it.
13.7.0
=> fix(ApplicationCommandOptionType): Add attachment to jsdoc

src/structures/VoiceChannel.js
small fix for wrong property reference
`9alexx3#7747` said they would open an issue, but this commit was done before I saw one open, feel free to link when they open it
=> fix: video quality mode data property

src/managers/GuildChannelManager.js
Introduced in #7611, closes #7997
=> fix(guildchannelmanager): wrong parameter in _sortedChannels call

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
This pr fixes some attachment types
=> types: fix some attachment related typings

packages/discord.js/src/structures/interfaces/InteractionResponses.js, packages/discord.js/typings/index.d.ts
Ref: https://discord.com/channels/222078108977594368/937420598383108167/983063064557518938
=> types(modal): fix `showModal()` typings

packages/discord.js/src/structures/CommandInteraction.js, packages/discord.js/typings/index.d.ts
Adds `commandGuildId` to CommandInteraction.
Closes #7984.
=> feat(CommandInteraction): add 'commandGuildId'

packages/discord.js/src/structures/DirectoryChannel.js
This was missing what it was extending in the documentation.
=> docs(DirectoryChannel): Extend `Channel`

packages/docgen/src/documentation.ts, packages/docgen/src/index.ts, packages/docgen/src/types/item-meta.ts
consistency with everything else
=> refactor(docgen): use the `node:` protocol

packages/discord.js/src/structures/Attachment.js
=> fix(Attachment): do not destructure `data`

packages/discord.js/src/structures/Message.js, packages/discord.js/src/structures/ThreadChannel.js
oversight from the PR that changed `MessageManager#fetch`'s parameters
=> fix(Message): force fetching

packages/discord.js/src/errors/DJSError.js
These functions are not exported
=> docs: ignore docs of unexported functions

packages/collection/src/index.ts
=> refactor(collection): remove `default` property

packages/discord.js/src/structures/BaseGuildTextChannel.js, packages/discord.js/src/structures/DMChannel.js, packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/src/structures/VoiceChannel.js, packages/discord.js/src/structures/interfaces/TextBasedChannel.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/5013
=> feat(vcs): add missing property and methods 

packages/collection/src/index.ts
This pr adds function checks in all methods of `Collection`. Function check is present in `Array` methods so adding it in `Collection` also makes sense.
**Before**
**After**
=> fix: check for function type

packages/discord.js/src/structures/SelectMenuBuilder.js
=> fix: select menu options to accept both rest and array

packages/discord.js/src/structures/Guild.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/5032
Pending:
- https://github.com/discordjs/discord-api-types/pull/476
=> feat(guild): add support for setting MFA level

packages/discord.js/src/managers/GuildStickerManager.js, packages/discord.js/src/structures/interfaces/TextBasedChannel.js
=> docs: update outdated examples

src/structures/GuildAuditLogs.js, typings/index.d.ts
Backports #7880 to version 13.
=> fix(AuditLog): default changes to empty array

.github/ISSUE_TEMPLATE/bug_report.yml
Adds the `MessageContent` gateway intent to the issue form.
=> chore: Add `MessageContent` to issue form

packages/discord.js/src/structures/BaseGuild.js, packages/discord.js/src/structures/Guild.js, packages/discord.js/src/structures/WelcomeScreen.js
Some strings can be replaced with `GuildFeature`.
=> refactor: Use `GuildFeature` enum

packages/proxy-container/package.json, yarn.lock
Small nit from #8000. Didn't cause any issues in Docker builds and such, but seemed to cause issues locally while building.
=> fix(proxy-container): add @discordjs/rest to deps

.github/workflows/publish-dev-docker.yml, .github/workflows/publish-docker.yml
=> fix(ci): log into dockerhub properly

.github/workflows/publish-dev-docker.yml
=> ci: don't run publish workflow on forks

packages/discord.js/src/client/websocket/WebSocketShard.js
These are using the wrong case.
=> fix(WebSocketShard): Disconnected casing

typings/index.d.ts
=>  types(Shard#reconnecting): backport to v13 - fix event name

vitest.config.ts
=> fix: vitest recursion

packages/proxy-container/README.md
=> chore: update proxy-container README

packages/discord.js/src/structures/VoiceChannel.js, packages/discord.js/typings/index.d.ts
=> fix(vcs): nsfw property

packages/discord.js/src/errors/ErrorCodes.js, packages/discord.js/src/util/Colors.js, packages/discord.js/src/util/Events.js, packages/discord.js/src/util/Partials.js, packages/discord.js/src/util/ShardEvents.js, packages/discord.js/src/util/Status.js
Documents the following:
- `Colors`
- `Events`
- `Partials`
- `ShardEvents`
- `Status`
=> docs: Document missing type definitions

packages/discord.js/src/managers/ThreadManager.js, packages/discord.js/src/structures/BaseGuildTextChannel.js, packages/discord.js/src/structures/ThreadChannel.js
Missed documentation changes from #8145.
=> docs: Update threads to use `ThreadAutoArchiveDuration`

src/structures/Message.js, src/structures/MessagePayload.js
Backports #8110 to version 13.
=> docs: `TextBasedChannel`-> `TextBasedChannels` typos (v13)

src/structures/VoiceChannel.js, typings/index.d.ts
Backports #8132 to version 13.
=> fix(VoiceChannel): NSFW property (v13)

src/client/websocket/WebSocketShard.js
=> fix(WebSocketShard): backport error handler preservation on connections

src/client/websocket/WebSocketShard.js, typings/index.d.ts, typings/index.test-d.ts
=> types: add missing shard types (v13)

packages/discord.js/typings/index.d.ts
https://github.com/discordjs/discord.js/blob/c4653f97b1529eb0b99fccdba67c37eb4f467ff9/packages/discord.js/src/util/Status.js#L23-L33
=> types(Status): add missing members

packages/discord.js/src/client/actions/GuildMemberRemove.js
**The number of presences can no longer exceed the number of server members. ↓**
**bug-fix**
=> fix(GuildMemberRemove): remove member's presence

packages/discord.js/src/client/websocket/WebSocketShard.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Some types/documentation were missing for sharding.
=> types: add missing shard types

src/client/actions/GuildMemberRemove.js
=> fix(guildmemberremove): remove member's presence for v13

src/util/DataResolver.js
Backports #8177 to version 13.
=> fix: Use non-global flag whilst resolving regular expressions

packages/voice/examples/README.md
- The YouTube Music Vot example does not exist but is still documented. The documentation for this example has been removed.
=> docs: Remove Music bot in voice examples

packages/discord.js/src/client/websocket/WebSocketManager.js, packages/discord.js/src/client/websocket/WebSocketShard.js, packages/discord.js/src/sharding/Shard.js, packages/discord.js/src/structures/Integration.js, packages/discord.js/src/structures/ModalSubmitInteraction.js, packages/discord.js/src/structures/VoiceState.js, packages/discord.js/src/structures/Widget.js, packages/discord.js/src/structures/WidgetMember.js, packages/discord.js/src/structures/interfaces/Application.js, packages/discord.js/src/structures/interfaces/Collector.js
Some classes were not documenting what they were extending. This pull request resolves that.
=> docs: Add missing `@extends`

packages/builders/__tests__/components/textInput.test.ts, packages/builders/src/components/textInput/TextInput.ts
=> fix(TextInputBuilder): parse `custom_id`, `label`, and `style`

src/structures/Message.js
=> docs(MessageInteraction): update `commandName` description (v13)

README.md, packages/builders/README.md, packages/collection/README.md, packages/proxy/README.md, packages/rest/README.md, packages/voice/README.md
Adds badges to packages with a coverage report (did not do utilities) because who doesn't love badges :)
=> docs: add codecov coverage badge to readmes

packages/actions/src/uploadCoverage/action.yml, packages/docgen/package.json, yarn.lock
=> chore: remove `docgen` test stuff

packages/collection/__tests__/collection.test.ts
=> test(collection): improve coverage

packages/builders/src/components/selectMenu/SelectMenu.ts
=> types(builder): remove casting

packages/website/src/DocModel/DocClass.ts, packages/website/src/DocModel/DocFunction.ts, packages/website/src/DocModel/DocInterface.ts, packages/website/src/DocModel/DocMethod.ts, packages/website/src/DocModel/DocMethodSignature.ts, packages/website/src/DocModel/DocTypeAlias.ts, packages/website/src/components/DocContainer.tsx, packages/website/src/components/TypeParamTable.tsx, packages/website/src/components/model/Class.tsx, packages/website/src/components/model/Function.tsx, packages/website/src/components/model/Interface.tsx, packages/website/src/components/model/TypeAlias.tsx, packages/website/src/util/api-model.server.ts, packages/website/src/util/parse.server.ts
Adds tables for type parameters on api items if applicable.
=> feat(website): add support for type parameter documentation

packages/discord.js/src/managers/GuildChannelManager.js
=> fix(GuildChannelManager): edit lockPermissions

packages/discord.js/src/managers/GuildChannelManager.js
=> fix(GuildChannelManager): Access `resolveId` correctly

packages/builders/package.json, packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionChannelTypesMixin.ts, yarn.lock
I didn't expect the previous pr will be merged so fast lol. There is an issue with shapeshift typings which I'll fix but for now, we can use like this
- https://github.com/sapphiredev/shapeshift/pull/146
=> types: remove expect error

packages/discord.js/typings/index.d.ts
Fixes #8287. If you have better suggestions for the type feel free to leave them here.
=> types(CategoryChannelChildManager): fix Holds type

packages/builders/__tests__/components/components.test.ts, packages/builders/__tests__/interactions/ContextMenuCommands.test.ts, packages/builders/__tests__/interactions/SlashCommands/Options.test.ts, packages/builders/__tests__/interactions/SlashCommands/SlashCommands.test.ts, packages/builders/__tests__/interactions/modal.test.ts, packages/builders/__tests__/util.test.ts
=> test(builders): improve coverage

packages/discord.js/src/util/DataResolver.js
Closes #8307 
This is a bug introduced by #8290 - seems we forgot a call to `resolveFile`
=> fix(DataResolver#resolveImage): adjust to updated resolveFile

src/managers/ApplicationCommandManager.js, src/structures/ApplicationCommand.js
=> fix(ApplicationCommandManager): allow passing 0n to defaultMemberPermissions (v13)

src/structures/Presence.js
Backports #8340 to version 13.
=> refactor(Presence): Remove redundant date parsing (v13)

.github/check_deploy_branch.sh, packages/website/src/components/DocContainer.tsx, packages/website/src/components/HyperlinkedText.tsx, packages/website/src/components/ItemSidebar.tsx, packages/website/src/pages/_app.tsx, packages/website/src/pages/docs/[...slug].tsx
Uses `Link`s instead of `<a>` for instant page navigation
=> chore(website): use next links

src/structures/ThreadChannel.js
Backports #8351 to version 13.
=> fix(ThreadChannel): Omit webhook fetching (v13)

packages/website/package.json, packages/website/src/components/DocContainer.tsx, packages/website/src/components/ItemSidebar.tsx, packages/website/src/components/Section.tsx, packages/website/src/components/SidebarLayout.tsx, packages/website/src/components/model/Enum.tsx, packages/website/src/pages/index.tsx, packages/website/src/styles/main.css, packages/website/unocss.config.ts, yarn.lock
Improved typography in various areas and added animated and collapsible sections.
=> refactor(website): add typography improvements

README.md, packages/actions/README.md, packages/builders/README.md, packages/collection/README.md, packages/docgen/README.md, packages/proxy/README.md, packages/rest/README.md, packages/scripts/README.md, packages/voice/README.md, packages/website/README.md, packages/ws/README.md
This was updated in some places... but not all.
=> chore: Update update guide link

packages/discord.js/src/structures/GuildMember.js, packages/discord.js/typings/index.d.ts
This PR adds the dmChannel getter to the GuildMember class, similar to the one on the User class. If there's the createDM and deleteDM methods it only makes sense to have this
=> feat(GuildMember): add dmChannel getter

src/managers/GuildChannelManager.js
Backports #8359 to version 13.
=> fix(GuildChannelManager): allow unsetting rtcRegion (v13)

packages/website/src/components/DocContainer.tsx, packages/website/src/components/ItemSidebar.tsx, packages/website/src/components/ListSidebar.tsx, packages/website/src/components/SidebarLayout.tsx, packages/website/src/util/icon.tsx
The docs sidebar now groups items by their symbol kind
=> feat(website): group items by symbol kind

packages/discord.js/src/structures/Message.js
This should help developers realise that `Message#content` requires an intent.
=> docs(Message): Document gateway intent for content

packages/website/src/components/DocContainer.tsx, packages/website/src/components/ListSidebar.tsx, packages/website/src/components/Section.tsx, packages/website/src/components/Sections.tsx, packages/website/src/components/model/Enum.tsx
Adds icons next to each section.
=> feat(website): add icons for sections

packages/website/src/components/ListSidebar.tsx
=> docs: hide sections with no members

packages/website/src/DocModel/DocEnum.ts, packages/website/src/DocModel/DocItem.ts, packages/website/src/DocModel/comment/CommentNode.ts, packages/website/src/DocModel/comment/CommentNodeContainer.ts, packages/website/src/DocModel/comment/FencedCodeCommentNode.ts, packages/website/src/DocModel/comment/LinkTagCommentNode.ts, packages/website/src/DocModel/comment/PlainTextCommentNode.ts, packages/website/src/DocModel/comment/index.ts, packages/website/src/components/CodeListing.tsx, packages/website/src/components/Comment.tsx, packages/website/src/components/DocContainer.tsx, packages/website/src/components/MethodItem.tsx, packages/website/src/util/parse.server.ts
This PR enables to website to properly parse and display tsdoc comment elements.
=> feat(website): parse tsdoc comments

packages/website/src/components/DocContainer.tsx, packages/website/src/components/HyperlinkedText.tsx, packages/website/src/components/model/Class.tsx
This pr does 3 things
- add implements for class
- remove the underline from links
- removed duplicate `:` from extends in the class
=> feat(website): add implements for class

.github/workflows/documentation.yml
build only actions when pushing docs changes.
=> chore: build only actions

packages/discord.js/src/structures/Embed.js
These were documented as strings, but this is not the case.
=> docs(Embed): Ensure height and width are numbers

packages/ws/src/ws/WebSocketShard.ts
=> fix(WebSocketShard): account code 1000 with no prior indication

src/structures/Guild.js, typings/index.d.ts
Backports #8423 to version 13.
=> feat(Guild): Add `max_video_channel_users` (v13)

packages/discord.js/src/structures/MessageMentions.js, packages/discord.js/typings/index.d.ts
=> fix(MessageMentions): infinite loop in `parsedUsers` getter

README.md, packages/discord.js/README.md
Global commands are more familiar to users and make more sense in an example with little context. With commands v2, global commands deploy instantly so there is no point in using guild commands.
=> docs: change registration example to use global commands

packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/typings/index.d.ts
Resolves #8453 by checking whether the parent exists.
=> fix(ThreadChannel): Handle possibly `null` parent

src/structures/interfaces/TextBasedChannel.js, typings/index.d.ts
=> types(Message): correct `bulkDelete` return type (v13)

packages/website/src/DocModel/DocItem.ts, packages/website/src/components/DocContainer.tsx, packages/website/src/components/ItemSidebar.tsx, packages/website/src/components/ListSidebar.tsx, packages/website/src/components/SidebarLayout.tsx, packages/website/src/components/model/Function.tsx, packages/website/src/contexts/member.tsx, packages/website/src/pages/docs/[...slug].tsx, packages/website/src/util/model.server.ts, packages/website/src/util/parse.server.ts
Previously the website would interpret any functions with the same names as the same api item. With this PR the website properly interprets overloaded functions and provides UI for indicating the overload index.
=> feat(website): add support for function overloads

packages/discord.js/typings/index.d.ts
- Resolves #8477
- Resolves #8238
- Supersedes #8495
=> types: Implement max/min values for autocomplete

src/structures/interfaces/InteractionResponses.js
Backports #8484 to version 13.
=> Specify time unit in `awaitModalSubmit` (v13)

typings/index.d.ts
Backports #8496 to version 13.
=> types(ModalMessageModalSubmitInteraction): channelId is not nullable (v13)

packages/discord.js/src/managers/GuildMemberManager.js, packages/discord.js/typings/index.d.ts
=> feat(GuildMemberManager): addRole and removeRole

packages/builders/src/components/ActionRow.ts, packages/builders/src/components/Component.ts, packages/builders/src/components/button/Button.ts, packages/builders/src/components/selectMenu/SelectMenu.ts, packages/builders/src/components/selectMenu/SelectMenuOption.ts, packages/builders/src/components/textInput/TextInput.ts, packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts, packages/builders/src/util/equatable.ts, packages/builders/src/util/jsonEncodable.ts, packages/collection/src/collection.ts, packages/website/src/DocModel/TypeParameterMixin.ts, packages/website/src/DocModel/comment/LinkTagCommentNode.ts, packages/website/src/components/DocContainer.tsx, packages/website/src/components/MethodList.tsx, packages/website/src/components/TypeParamTable.tsx, packages/website/src/components/tsdoc/BlockComment.tsx, packages/website/src/components/tsdoc/TSDoc.tsx, packages/website/src/util/parse.server.ts
Similar to #8519 except for type parameters
This PR also addressed some bugs with `@link`s not resolving properly and some `key` props for react not being propagated properly.
=> feat(website): show descriptions for `@typeParam` blocks

packages/website/src/DocModel/DocClass.ts, packages/website/src/DocModel/DocInterface.ts, packages/website/src/DocModel/DocMethod.ts, packages/website/src/DocModel/DocMethodSignature.ts, packages/website/src/DocModel/DocProperty.ts, packages/website/src/components/CodeListing.tsx, packages/website/src/components/InheritanceText.tsx, packages/website/src/components/MethodItem.tsx, packages/website/src/components/PropertyList.tsx
Classes and interfaces now include and indicate members that they've inherited.
=> feat(website): show inherited members

packages/discord.js/typings/index.d.ts
=> types(GuildAuditLogs): Remove static `Entry`

packages/proxy/src/handlers/proxyRequests.ts
=> fix(proxyRequests): Typo in error message

src/managers/GuildChannelManager.js, typings/index.d.ts
Backports #8531 to version 13.
=> types: Disallow some channel types from webhook creation

packages/docgen/src/types/item.ts
All the classes are `null` in the uploaded docs
- https://github.com/discordjs/docs/blob/f4a58fa73b73d2655c6f0980fb3b0cbd54c8710a/discord.js/main.json
=> fix: docgen

package.json, packages/builders/package.json, packages/collection/package.json, packages/discord.js/package.json, packages/proxy-container/package.json, packages/proxy/package.json, packages/rest/LICENSE, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json
Typical day things, switching names.
=> docs: change name

packages/collection/src/collection.ts, packages/discord.js/src/client/websocket/WebSocketShard.js, packages/discord.js/src/managers/GuildManager.js, packages/discord.js/src/structures/Guild.js, packages/discord.js/src/structures/InteractionWebhook.js, packages/discord.js/src/structures/MessagePayload.js, packages/discord.js/src/structures/interfaces/Collector.js, packages/voice/src/DataStore.ts, packages/voice/src/networking/Networking.ts, packages/voice/src/networking/VoiceUDPSocket.ts, packages/voice/src/networking/VoiceWebSocket.ts, packages/voice/src/receive/SSRCMap.ts, packages/voice/src/receive/SpeakingMap.ts, packages/voice/src/util/Secretbox.ts, packages/ws/src/strategies/context/WorkerContextFetchingStrategy.ts, packages/ws/src/strategies/sharding/WorkerShardingStrategy.ts, packages/ws/src/strategies/sharding/worker.ts, packages/ws/src/ws/WebSocketShard.ts
=> chore: remove unused eslint disable comments

packages/builders/__tests__/components/button.test.ts
Renames a test that was named incorrectly.
=> test: rename incorrect test

typings/index.d.ts
Introduced in e6ee7d8374ddc157037c258b63225384c154a2e6
=> chore: fix typescript tests (v13)

packages/discord.js/src/managers/GuildTextThreadManager.js
This was not documenting the correct class it was extending.
=> docs(GuildTextThreadManager): Document correct `@extend`

packages/proxy-container/Dockerfile
https://github.com/discordjs/discord.js/actions/workflows/publish-dev-docker.yml
=> chore: fix proxy-container Dockerfile

packages/discord.js/src/structures/Guild.js, packages/discord.js/typings/index.d.ts
Forum channels can be set via bots for the widget channel well as in the client. This pull request reflects this functionality.
=> feat(Widget): Allow forum channels

packages/discord.js/src/structures/ForumChannel.js
The applied methods were not documented due to this missing tag.
=> docs(ForumChannel): Add `@implements`

packages/builders/package.json, packages/discord.js/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, yarn.lock
=> chore(deps): bump discord-api-types

packages/proxy-container/README.md
Internal discussion thread: https://canary.discord.com/channels/222078108977594368/1020044900282138744/1020044900282138744
- I know how to update typings and have done so, or typings don't need updatin
=> chore(proxy-container): update README for proper request forwarding

packages/discord.js/typings/index.d.ts
=> types(ModalBuilder): fix constructor typings

packages/ws/src/ws/WebSocketShard.ts
=> fix(WebSocketShard): add ready data parameter to ready event

packages/util/.cliff-jumperrc.json
=> chore(util): add missing cliff-jumper config file

packages/discord.js/src/structures/ActionRowBuilder.js, packages/discord.js/src/util/Components.js
=> fix(Components): error with unknown components

src/structures/ContextMenuInteraction.js, src/structures/UserContextMenuInteraction.js
This PR updates the documentation for the UserContextMenu class so it's properties make more sense. This PR mirrors the v14 request #8717 
Originating issue: #8713 
Any issues with this PR? Please lmk as this is my first attempt at contributing to djs.
=> docs: update UserContextMenu documentation v13

packages/voice/package.json
The voice package's postbuild script was missed in the build script when merging #8324. 
Fixes #8740.
=> fix: voice postbuild script

packages/scripts/src/template/template.package.json
=> chore: remove downlevel-dts dependency from template

packages/ws/README.md
These did not do anything in the examples.
=> docs: Remove unused imports

packages/builders/package.json, packages/discord.js/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, yarn.lock
=> chore: Bump discord-api-types

packages/brokers/__tests__/index.test.ts, packages/brokers/src/brokers/redis/BaseRedis.ts
Should now work even with how we bundle files
=> fix(BaseRedisBroker): proper import path to lua script

packages/brokers/package.json
=> fix(brokers): publish the scripts folder

packages/discord.js/src/managers/AutoModerationRuleManager.js
Describes `AutoModerationRuleManager`'s cache instead of simply `Collection`.
=> docs(AutoModerationRuleManager): Describe cache

src/structures/Message.js, src/structures/interfaces/TextBasedChannel.js, src/util/Constants.js, typings/index.d.ts
=> feat: add `Message#bulkDeletable` (v13)

packages/builders/src/messages/formatters.ts
=> types(Formatters): allow boolean in `formatEmoji`

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/workflows/documentation.yml, .github/workflows/npm-auto-deprecate.yml, .github/workflows/publish-dev.yml, apps/website/src/app/docs/[...slug]/page.tsx, apps/website/src/util/constants.ts, packages/scripts/src/generateIndex.ts
Adds /core to a variety of places where apps/packages are defined.
=> chore: Update /core constants

.github/labeler.yml
This bug so far has caused me ~0.4222156 seconds of extra work on #8877.
=> ci: Fix typo for /core labels

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, packages/scripts/src/generateIndex.ts
- Adds brokers to `PACKAGES` in /scripts
- Adds brokers to the feature request form
- Sorts the issue and feature request package list
=> chore: Add brokers to package list and labels in issue forms

packages/discord.js/src/structures/ActionRow.js, packages/discord.js/src/structures/BaseInteraction.js, packages/discord.js/typings/index.d.ts
Fixes malformed links in deprecated descriptions.
=> docs: Fix deprecated links

packages/core/src/api/applicationCommands.ts, packages/core/src/api/channel.ts, packages/core/src/api/guild.ts, packages/core/src/api/interactions.ts, packages/core/src/api/invite.ts, packages/core/src/api/sticker.ts, packages/core/src/api/thread.ts, packages/core/src/api/user.ts, packages/core/src/api/voice.ts, packages/core/src/api/webhook.ts
Adds links to the route documentation on each method
=> feat: add links to each routes documentation

packages/discord.js/src/util/Util.js
=> fix(resolveColor): invalid colors

.github/labels.yml
=> chore: Add backport label

packages/ws/README.md
Added to the `README.md`:
- optional packages
- an example on how to add a listener to the ws manager
It's useful to have this kind of info available here.
=> docs: updated @discordjs/ws README.md to include optional packages

apps/website/src/app/docs/packages/page.tsx
=> fix(website): package selector page height on small devices

packages/discord.js/src/structures/ApplicationRoleConnectionMetadata.js
This did not appear in the documentation due to lack of... documentation.
=> docs(ApplicationRoleConnectionMetadata): Add documentation

src/managers/BaseGuildEmojiManager.js, src/managers/ReactionManager.js, typings/index.d.ts
Backports #8969 to version 13.
=> types: Swap message reaction and emoji identifier types

packages/discord.js/src/client/websocket/handlers/GUILD_MEMBERS_CHUNK.js, packages/discord.js/src/util/Util.js, packages/discord.js/typings/index.d.ts
Implements `not_found` which was added in https://github.com/discord/discord-api-docs/pull/1078.
=> feat: Add `not_found` to guild member chunk data

packages/ws/__tests__/strategy/WorkerShardingStrategy.test.ts, packages/ws/src/strategies/sharding/IShardingStrategy.ts, packages/ws/src/strategies/sharding/SimpleShardingStrategy.ts, packages/ws/src/strategies/sharding/WorkerShardingStrategy.ts, packages/ws/src/strategies/sharding/worker.ts, packages/ws/src/ws/WebSocketManager.ts, packages/ws/src/ws/WebSocketShard.ts
Closes #8960.
Ended up taking a different approach than what was originally proposed with https://github.com/discordjs/discord.js/issues/8960#issuecomment-1363232818 and later discussed internally.
The new `WebSocketManager#fetchStatus` method and the new `HeartbeatComplete` event should be more than enough for all intents and purposes. I can't really envision what else you might want to track that you can't accomplish with the tools already provided, otherwise.
- This PR changes the library's interface …
=> feat(ws): metrics

packages/rest/src/lib/RequestManager.ts, packages/rest/src/lib/utils/constants.ts
Closes #8557 - stuck between a rock and a hard place with https://github.com/sindresorhus/file-type/issues/559 and https://github.com/discord/discord-api-docs/issues/5390
=> fix(RequestManager): inference of image/apng

src/managers/UserManager.js, src/structures/AutocompleteInteraction.js, src/structures/Sticker.js
Backports #8697 to version 13.
=> fix: Import errors correctly

src/structures/Guild.js, typings/index.d.ts
Backports #9011 to version 13.
=> feat(GuildAuditLogs): Support `after`

src/client/websocket/handlers/GUILD_MEMBERS_CHUNK.js, typings/index.d.ts
=> feat v13: add `not_found` to guildMembersChunk data

packages/discord.js/src/structures/DMChannel.js
Reverts discordjs/discord.js#8950
Fixes #9007
=> revert: fix(DMChannel): `recipientId` edge case

packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionChannelTypesMixin.ts, packages/discord.js/typings/index.d.ts, packages/formatters/src/formatters.ts, packages/rest/src/lib/utils/constants.ts, packages/ws/__tests__/strategy/WorkerContextFetchingStrategy.test.ts, packages/ws/__tests__/strategy/WorkerShardingStrategy.test.ts
CI started failing after the prettier version bump in 8dfd0037b53ec6ef0900a53a0fb1b68fa2cbaf72 
=> style: run prettier

src/structures/ThreadChannel.js
Backports #9020 to version 13.
=> docs(ThreadEditOptions): Move info tag back to `invitable`

apps/website/src/components/model/enum/EnumMember.tsx, apps/website/src/components/model/method/MethodHeader.tsx
=> fix(website): scroll to method when clicking anchor

packages/ws/__tests__/strategy/WorkerContextFetchingStrategy.test.ts, packages/ws/__tests__/strategy/WorkerShardingStrategy.test.ts, packages/ws/src/strategies/context/WorkerContextFetchingStrategy.ts, packages/ws/src/strategies/sharding/WorkerShardingStrategy.ts, packages/ws/src/utils/WorkerBootstrapper.ts
don't talk about it don't talk about it don't talk about it don't talk about it don't talk about it don't talk about it 
=> fix: ws typo

.github/issue-labeler.yml, .github/workflows/issue-labeler.yml, .github/workflows/issue-triage.yml, packages/scripts/src/createPackage.ts
jiralite 2.0 but automated 
tested in https://github.com/imranbarbhuiya/test-issue-labeler repo and works fine
=> ci: automated issue labeler

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/issue-labeler.yml
- Automates formatters
- Automates next
- Fixes parsing for feature requests
=> ci: Update issue labeller

packages/discord.js/src/index.js
Fixes an unnoticed bug from #8855, spotted while reviewing #9072, thanks @jaw0r3k.
I checked all the other exports just in case, and they seem to be fine.
<details>
<summary>Updated exports</summary>
```js
{
BaseClient: [class BaseClient extends EventEmitter],
Client: [class Client extends BaseClient],
Shard: [class Shard extends EventEmitter],
ShardClientUtil: [class ShardClientUtil],
ShardingManager: [class ShardingManager extends EventEmitter],
WebhookClient: [class WebhookClient extends BaseClient],
DiscordjsError: [class DiscordjsError extends Error],
DiscordjsTypeError: [class DiscordjsError extends TypeError],
DiscordjsRangeError: [class DiscordjsError extends RangeError],
DiscordjsErrorCodes: {
// ...
}, …
```
=> fix(ApplicationRoleConnectionMetadata): export the class correctly

packages/discord.js/src/structures/MessageReaction.js, packages/discord.js/typings/index.d.ts
=> fix(MessageReaction): `toJSON()` infinite recursion

packages/discord.js/src/util/Formatters.js
https://github.com/discordjs/discord.js/blob/8b70f497a1207e30edebdecd12b926c981c13d28/packages/formatters/src/formatters.ts#L230-L240
=> docs(chatInputApplicationCommandMention): parameters are not nullable

src/structures/interfaces/InteractionResponses.js, src/util/Util.js
Fixes two typos. One is important!
=> chore: Fix typos

src/structures/Webhook.js, typings/index.d.ts
=> feat (Webhook): v13 add `channel` prop

src/index.js, src/structures/ApplicationRoleConnectionMetadata.js, src/structures/ClientApplication.js, src/structures/interfaces/Application.js, src/util/Constants.js, typings/enums.d.ts, typings/index.d.ts, typings/rawDataTypes.d.ts
=> feat(ClientApplication): v13 add role connections

.github/.kodiak.toml, .github/auto_assign.yml, .github/labeler.yml, .github/workflows/pr-triage.yml
Automates requesting reviews, pull request labelling, and merging via kodiakhq—just like on the main branch.
=> ci: Add pull request triage and Kodiak merge workflow

src/client/websocket/WebSocketShard.js, typings/index.d.ts
This PR backports: https://github.com/discordjs/discord.js/pull/8784
=> feat(WebSocketShard): v13 add resume url 

.github/workflows/tests.yml, codecov.yml, vitest.config.ts
Ever since CI was changed to only run tests on changed  files, coverage reporting has been wrong, this fixes it
=> test: fix coverage reporting

packages/brokers/package.json, packages/core/package.json, packages/ws/package.json, packages/ws/src/ws/WebSocketShard.ts, yarn.lock
=> fix(WebSocketShard): proper error bubbling

.github/workflows/publish-release.yml
=> ci: create publish release workflow v13

.github/workflows/publish-release.yml, packages/actions/__tests__/formatTag.test.ts, packages/actions/src/formatTag/formatTag.ts, packages/actions/src/formatTag/index.ts
This PR creates a publish-release workflow that will automatically publish any github releases to npm (using the respective tags content). 
=> ci: create publish release workflow

packages/discord.js/src/managers/AutoModerationRuleManager.js, packages/discord.js/src/structures/AutoModerationRule.js, packages/discord.js/src/util/Transformers.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/5955
=> feat(AutoModeration): Support `custom_message`

src/util/Constants.js, typings/enums.d.ts
https://github.com/discordjs/discord.js/pull/9038
https://discord.com/developers/docs/resources/sticker#sticker-object-sticker-format-types
=> feat: add support for gif stickers (v13)

packages/core/README.md
=> docs: fix /core README example

packages/core/src/api/interactions.ts
=> fix(core): use `auth: false` for interaction callback methods

packages/core/src/api/guild.ts, packages/core/src/api/user.ts
=> refactor(core): move `setVoiceState` to `GuildsAPI`

packages/discord.js/src/util/APITypes.js
=> docs: Update `APISelectMenuComponent`

packages/discord.js/src/managers/ThreadManager.js, packages/discord.js/typings/index.d.ts
This property has no effect on any code. It is purely optional and influences nothing.
=> refactor(FetchThreadsOptions): Remove `active`

README.md, apps/guide/README.md, apps/website/README.md, packages/actions/README.md, packages/api-extractor-utils/README.md, packages/brokers/README.md, packages/builders/README.md, packages/collection/README.md, packages/core/README.md, packages/discord.js/README.md, packages/docgen/README.md, packages/formatters/README.md, packages/next/README.md, packages/proxy-container/README.md, packages/proxy/README.md, packages/rest/README.md, packages/scripts/README.md, packages/ui/README.md, packages/util/README.md, packages/voice/README.md, packages/ws/README.md
This PR:
- Fixes readmes being out of sync. e.g., some readmes only having a partial contributing section.
```diff
- See [the contribution guide][contributing] if you'd like to submit a PR.
+ Before creating an issue, please ensure that it hasn't already been reported/suggested, and double-check the 
+ [documentation][documentation].
+ See [the contribution guide][contributing] if you'd like to submit a PR.
```
- Adds semantic changes for improved grammar:
```diff
- See also the [Update Guide][guide-update], including updated and removed items in the library.
+ Also see the v13 to v14 [Update Guide][guide-update], which includes updated and removed items from the library.
```
- Adds or changes some about sections …
=> chore: overhaul readmes

packages/core/package.json, packages/core/src/http-only/index.ts, packages/core/tsup.config.ts, yarn.lock
=> feat(core): http-only wrapper

src/structures/AutocompleteInteraction.js
This was sending an object, but it should be an array.
=> fix(AutocompleteInteraction): Fix responding

apps/website/src/app/page.tsx, apps/website/src/util/constants.ts
This could be using the `DESCRIPTION` constant.
=> refactor: Use description constant in landing page

src/structures/ClientUser.js
This needed to be wrapped in `data`.
=> fix(ClientUser): Fix modifying self

src/structures/Message.js
Backports #9319 to version 13.
=> fix(Message): Fix permissions check in locked threads

apps/website/src/components/documentation/tsdoc/BlockComment.tsx, apps/website/src/components/documentation/tsdoc/TSDoc.tsx
Adds support for the `@returns` tag.
=> feat: Support `@returns`

apps/website/src/components/model/function/FunctionBody.tsx
=> fix(website): dont show parameters header on functions without parameters

packages/formatters/__tests__/formatters.test.ts, packages/formatters/src/escapers.ts, packages/formatters/src/formatters.ts
- Adds descriptions to everything.
- Adds type parameters where necessary.
- Since #9363, default values show up in the documentation. They look better in backticks!
- Fixes faces.
=> docs(formatters): Enhance the documentation

src/managers/AutoModerationRuleManager.js, src/structures/AutoModerationRule.js, typings/index.d.ts, typings/rawDataTypes.d.ts
=> feat(AutoModeration): v13 support `customMessage` 

apps/guide/src/components/DocsLink.tsx, apps/guide/src/util/constants.ts
Implements the `DocsLink` component. Closes DJS-29.
=> feat(DocsLink): Implement the component

src/util/Permissions.js, typings/index.d.ts
Adds:
- https://github.com/discord/discord-api-docs/pull/6017
Code changes have been tested against the Discord API
I know how to update typings and have done so
=> feat: v13 `VIEW_CREATOR_MONETIZATION_ANALYTICS` and `USE_SOUNDBOARD` permissions

src/structures/Role.js, typings/index.d.ts
=> feat(roleTagData): v13 add guildConnections

apps/guide/src/content/03-additional-info/01-async-await.mdx
Updates this code snippet to ESM.
=> chore(async-await): Update to ESM

apps/guide/src/content/03-additional-info/03-updating-to-v14.mdx
JavaScript prioritisation; TypeScript alternative.
=> fix(updating-to-v14): Prioritise JavaScript

packages/builders/README.md, packages/rest/README.md
This PR changes `@discord.js` to `@discordjs`
=> docs: reference package names properly

.github/workflows/issue-triage.yml
Apparently, you need to be explicit in the version.
=> ci: Fix issue triage

packages/core/README.md
This needs modifying due to #9410.
=> docs: Update example usage

apps/guide/src/content/03-creating-your-bot/04-handling-command-interactions.mdx
The rows/focus stopped the rest of the TypeScript code block from being shown.
=> fix(guide): Show rest of TypeScript code block

.github/ISSUE_TEMPLATE/01-package_bug_report.yml, .github/ISSUE_TEMPLATE/02-application_bug_report.yml, .github/ISSUE_TEMPLATE/03-feature_request.yml, .github/issue-labeler.yml, packages/scripts/src/createPackage.ts
Adds a new issue form for our applications (documentation + guide websites) and tweaks some wording.
=> docs: Add new issue form for applications

apps/guide/src/content/05-additional-info/03-updating-to-v14.mdx, apps/guide/src/util/constants.ts
=> feat(guide): Update to 14.10.0

packages/discord.js/src/client/Client.js
A recent Sapphire update requires this link to update. I've also added the guide link in brackets.
=> docs(Client): Update Sapphire's snowflake utility links

packages/voice/package.json
I noticed that everywhere else you were using "Node.js" instead of "node.js" so I think this should change too.
=> chore(voice-description): being consistency with Node.js casing

packages/ws/__tests__/strategy/WorkerShardingStrategy.test.ts, packages/ws/__tests__/ws/WebSocketManager.test.ts
things happened when we bumped vitest
=> tests(ws): fix tests

packages/discord.js/src/client/websocket/WebSocketManager.js
=> fix(WebSocketManager): properly emit shard error events

src/structures/GuildAuditLogs.js, typings/index.d.ts
=> feat(GuildAuditLogsEntry): add missing channel property to extra

apps/guide/src/app/guide/[...slug]/page.tsx, apps/guide/src/components/Footer.tsx, apps/guide/src/components/Sidebar.tsx
| Before  | After |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/15116870/236655966-964aad7b-0022-4572-a0b6-0b94fcb4beeb.png) | ![image](https://user-images.githubusercontent.com/15116870/236655959-7035fcef-ed63-40a2-8733-29a97d6b5e52.png)  |
| ![image](https://user-images.githubusercontent.com/15116870/236655998-22d16d61-165d-458e-8cc4-4f6ad60b58be.png)  | ![image](https://user-images.githubusercontent.com/15116870/236656577-d6b4c6b8-f516-4b4f-9fef-b6db7827e77a.png) |
| [gif that won't embed](https://um.syn.gay/z77q0r.gif) | [gif that won't embed](https://um.syn.gay/baua3f.gif) |
- This PR **only** includes non-code changes, like …
=> fix(guide): various UI improvements

.github/workflows/test.yml, package.json, typings/rawDataTypes.d.ts
Running `npm run-script format` picks these up.
I also amended the package.json scripts so the respective workflow will pick them up.
=> chore: Run format script

packages/create-discord-bot/README.md
=> docs: add Cloudflare sponsorship in `create-discord-bot` readme

packages/create-discord-bot/template/JavaScript/package.json
=> fix(create-discord-bot): Fix start script

packages/create-discord-bot/template/JavaScript/src/index.js
Event file exports it by default
=> fix: Non-existing data property

packages/create-discord-bot/template/JavaScript/src/index.js, packages/create-discord-bot/template/TypeScript/src/index.ts
Resolves #9545. The Windows operating system failed to load files.
=> fix: Resolve imports for Windows

packages/create-discord-bot/src/create-discord-bot.ts
Resolves #9537. Requiring a fresh directory (or a directory that is empty) rather than allowing some files to be present.
=> feat: Check for empty directory

packages/create-discord-bot/package.json
Adding the `directory` under the `repository` (monorepo things).
=> chore: Add repository directory

apps/guide/src/content/04-popular-topics/04-webhooks.mdx
These properties may not be modified when editing a message.
=> fix(webhooks): Remove incorrect properties in edit message code sample

packages/discord.js/src/client/websocket/WebSocketShard.js, packages/discord.js/src/structures/UserSelectMenuBuilder.js
Fixes the broken documentation links to the new website.
=> docs: Fix broken links to new documentation

packages/discord.js/src/client/actions/InviteCreate.js, packages/discord.js/src/client/actions/InviteDelete.js
- https://github.com/discord/discord-api-docs/pull/6131
=> docs(Client): Correct invite gateway permission checks

src/structures/Presence.js
=> feat(presence): feature parity in image resolve

packages/builders/package.json, packages/core/package.json, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, yarn.lock
=> chore: bump discord-api-types to 0.37.45

packages/core/src/api/applicationCommands.ts, packages/core/src/api/channel.ts, packages/core/src/api/guild.ts, packages/core/src/api/interactions.ts, packages/core/src/api/invite.ts, packages/core/src/api/roleConnections.ts, packages/core/src/api/stageInstances.ts, packages/core/src/api/sticker.ts, packages/core/src/api/thread.ts, packages/core/src/api/user.ts, packages/core/src/api/voice.ts, packages/core/src/api/webhook.ts
This PR implements the changes outlined in #9618.
Additionally, I've removed `createForumThread` as it was essentially an alias for `createThread` just with types constrained to forum thread JSON payload options.
Closes #9618
=> fix(core): fix inconsistencies on `core`

packages/discord.js/src/structures/StringSelectMenuOptionBuilder.js
=> docs(BuildersSelectMenuOption): Update link

src/client/actions/ChannelUpdate.js
Backports #9697 to version 13.
=> fix(ChannelUpdate): Check against unknown channels

packages/ws/src/strategies/context/IContextFetchingStrategy.ts, packages/ws/src/strategies/context/WorkerContextFetchingStrategy.ts, packages/ws/src/ws/WebSocketShard.ts
=> refactor(WebSocketShard): throttling error handling

packages/discord.js/src/client/websocket/handlers/GUILD_CREATE.js, packages/discord.js/src/util/Events.js, packages/discord.js/typings/index.d.ts
Alternative to #9676, lets (alongside an optional `client.ready` check) developers fetch members if they want to.
=> feat(Client): add `guildAvailable` event

apps/website/src/components/OverloadSwitcher.tsx, apps/website/src/components/model/function/Function.tsx, apps/website/src/components/model/method/Method.tsx
Adds ability to switch overloades based on hash location.
=> feat(website): switch overload on hash location

packages/discord.js/src/client/BaseClient.js
#9722 removed the `requestManager` property and these methods are now in the `REST` class.
Fixes #9741 
=> fix(BaseClient): fix destroy method

packages/discord.js/src/structures/DMChannel.js
=> fix(DMChannel): Correct partial typo

packages/discord.js/src/managers/GuildInviteManager.js, packages/discord.js/typings/index.d.ts
Forum channels may have invites created on them. This is an available method on the `ForumChannel` class already—just not here.
=> types(GuildInvitableChannelResolvable): Allow forum channels

packages/discord.js/src/structures/EmbedBuilder.js
The length should be `@readonly`.
=> docs(EmbedBuilder): `@readonly` length

packages/discord.js/src/structures/GuildAuditLogsEntry.js
This pull request abstracts reduce logic into a new function to remove some code repetition.
=> refactor(GuildAuditLogsEntry): abstract reduce logic into a new function

packages/discord.js/src/structures/interfaces/TextBasedChannel.js
=> docs: Remove `FileOptions`

packages/brokers/LICENSE, packages/proxy-container/LICENSE, packages/proxy/LICENSE, packages/ws/LICENSE
I was doing this in #9541 but I have no idea what we're doing with it.
I am making the change to my legal name for personal reasons.
=> chore: update license files

packages/collection/src/collection.ts
Minor documentation change to add articles.
=> docs(collection): Minor article additions

package.json
This needs `--args` so the example in the contributing guidelines will work.
=> build: Fix create-package script

README.md
=> fix(readme): test badge svg

src/client/actions/Action.js
Backports #9774 to version 13.
=> fix(Action): Conditionally add recipient

src/index.js
These classes should be exported.
=> fix: Export `AttachmentFlags` and `RoleFlags`

packages/collection/__tests__/collection.test.ts, packages/collection/src/collection.ts
Stage 4 proposal:
- https://github.com/tc39/proposal-change-array-by-copy
Overview of the changes:
- `sorted` -> `toSorted`
- Added `toReversed`
=> feat: align some methods with the Change By Copy proposal

packages/discord.js/package.json, pnpm-lock.yaml
=> chore: pin `@discordjs/collection` version in discord.js

packages/discord.js/src/client/Client.js
=> fix(Client): Ensure destroyed connections are not ready

.github/workflows/publish-release.yml
Related pnpm issue: https://github.com/pnpm/pnpm/issues/5894
related: https://github.com/discordjs/discord.js/pull/9817
=> chore(ci): fix release workflow

packages/create-discord-bot/CHANGELOG.md, packages/create-discord-bot/package.json, packages/create-discord-bot/template/Bun/JavaScript/package.json, packages/create-discord-bot/template/Bun/TypeScript/package.json, packages/create-discord-bot/template/Deno/src/commands/index.ts, packages/create-discord-bot/template/Deno/src/events/index.ts, packages/create-discord-bot/template/Deno/src/events/ready.ts, packages/create-discord-bot/template/Deno/src/index.ts, packages/create-discord-bot/template/Deno/src/util/deploy.ts, packages/create-discord-bot/template/Deno/src/util/registerEvents.ts, packages/create-discord-bot/template/JavaScript/package.json, packages/create-discord-bot/template/TypeScript/package.json
Bumps dependency versions due to recent releases.
=> feat: bump package versions

packages/discord.js/src/client/BaseClient.js
Prevents losing some defaults.
=> fix(BaseClient): Default in objects properly

src/structures/ClientPresence.js
=> fix(ClientPresence): correctly set activity state on CUSTOM activity type

packages/rest/src/lib/errors/RateLimitError.ts, packages/rest/src/lib/handlers/BurstHandler.ts, packages/rest/src/lib/handlers/SequentialHandler.ts, packages/rest/src/lib/utils/types.ts
Just useful for debugging purposes, it's not something we need to handle as our current ratelimit impl already takes care of it
=> feat: present x-ratelimit-scope for 429s hit

packages/core/CHANGELOG.md, packages/core/package.json, packages/rest/CHANGELOG.md, packages/rest/package.json
Fixes ESM builds for core and rest 
=> chore: release @discordjs/rest@2.2.0 & @discordjs/core@1.1.1

apps/website/src/util/addPackageToModel.ts, packages/discord.js/typings/index.d.ts, packages/scripts/src/generateIndex.ts
=> fix(website): search index generation

.github/workflows/documentation.yml
fix documentation.yml CI to only check if branch or tag once
=> ci: documentation.yml refactor branch/tag check to one place only

packages/actions/src/uploadDocumentation/index.ts
Exposes the full error so we can debug better.
=> chore(uploadDocumentation): Expose full error

packages/discord.js/src/managers/RoleManager.js, packages/discord.js/src/structures/Emoji.js
=> fix: replace internal calls to Emoji#url

packages/discord.js/src/managers/CategoryChannelChildManager.js
The reference was pointing nowhere.
=> docs(CategoryCreateChannelOptions): Update reference

apps/website/src/util/builtinDocumentationLinks.ts
Add some more links to types that are documented outside of the monorepo / docs website.
=> feat(website): more builtin docs links

packages/discord.js/src/structures/ThreadMember.js
ref: [#10023](https://github.com/discordjs/discord.js/pull/10023#pullrequestreview-1797454116)
* This PR **only** includes non-code changes, like changes to documentation, README, etc.
=> docs(ThreadMember): fix docblock async return type

packages/ws/src/utils/constants.ts, packages/ws/src/ws/WebSocketShard.ts
After consulting with Discord and some conversations in an internal thread[^1], this is the resolution we came up with for the following:
- Fixes #8918
- Fixes #10089
[^1]: https://discord.com/channels/222078108977594368/1196094076395716608/1196094076395716608
=> refactor(WebSocketShard): payload sending

packages/core/src/api/guild.ts
Resolves #10039 in a non-breaking way.
=> feat(guild): Add `with_counts` to getting guilds

.github/workflows/documentation.yml
Causes source code links in documentation to link to the correct branch/tag that was used to generate the documentation.
=> ci: use correct github tag in docs source links

packages/discord.js/typings/index.d.ts
`ReadonlyCollection` had not been exported previously.
=> fix(types): Export `ReadonlyCollection`

packages/discord.js/src/errors/ErrorCodes.js, packages/discord.js/src/errors/Messages.js, packages/discord.js/src/managers/GuildBanManager.js, packages/discord.js/src/managers/GuildMemberManager.js, packages/discord.js/typings/index.d.ts
- Depends on:
- https://github.com/discordjs/discord-api-types/pull/908
- https://github.com/discordjs/discord-api-types/pull/909
- https://github.com/discordjs/discord-api-types/pull/910
- https://github.com/discord/discord-api-docs/pull/6720
=> feat(GuildBanManager): Add `bulkCreate()` method

packages/api-extractor/src/api/IConfigFile.ts, packages/core/src/api/interactions.ts, packages/util/src/functions/range.ts
=> docs: remove duplicated words

.github/.kodiak.toml
=> ci: Ensure reviews in progress label do not merge

packages/ws/README.md, packages/ws/src/strategies/sharding/WorkerShardingStrategy.ts
=> feat(ws): support for custom worker messaging

packages/ws/README.md
=> docs: Remove duplicate word in comment

packages/discord.js/typings/index.d.ts
I noticed this was in the Message structure but not in the TypeScript type
patch
=> types: add `Poll` to `Message`

.github/workflows/documentation.yml
Fixes "sed: couldn't edit packages/X/: not a regular file" by running sed directly on the target file instead
https://github.com/discordjs/discord.js/actions/runs/8952254090/job/24589436997
=> ci: fix documentation workflow

.github/labeler.yml
This file needed to be updated since #10270.
=> ci: Fix labels action

packages/ws/src/ws/WebSocketShard.ts
See https://canary.discord.com/channels/222078108977594368/1237471430887604375/1239037602699546645
=> fix: deno compat

packages/builders/src/components/selectMenu/ChannelSelectMenu.ts, packages/builders/src/components/selectMenu/MentionableSelectMenu.ts, packages/builders/src/components/selectMenu/RoleSelectMenu.ts, packages/builders/src/components/selectMenu/UserSelectMenu.ts
Corrects gramatical errors in the documentation for various set methods.
=> docs(SelectMenuBuilder): correct grammatical errors 

packages/discord.js/src/structures/Invite.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/6568
=> feat(Invite): add `type`

.github/labeler.yml, packages/scripts/turbo/generators/config.ts
Since #10272, the script to create packages needed updating regarding the labeller file.
=> fix: Update config file to address labeller file changes

packages/core/src/api/stageInstances.ts
This change fixes the issue with the URL of a specific method.
=> docs(stageInstances): Correct reference for stage instance creation

.github/workflows/pr-triage.yml
Kodiak creates commits based on a pull request's title. This will ensure no improper titles are merged so the changelog picks them up properly.
=> ci: Check pull request titles for the commit convention format

apps/website/src/components/DocNode.tsx
For example https://discord.js.org/docs/packages/collection/main/Collection:Class#at showed an additional `undefined`. This gets fixed with this PR.
=> fix(website): link tags with explicit URL showed undefined

packages/builders/package.json, packages/builders/src/components/button/Button.ts, packages/core/package.json, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, pnpm-lock.yaml
Bumps discord-api-types to 0.37.90.
=> build: Bump discord-api-types to 0.37.90

packages/discord.js/typings/index.d.ts
=> types(ApplicationCommandManager): `Snowflake` fetch

packages/collection/__tests__/collection.test.ts
Add missing tests to achieve 100% coverage on the collection package
=> test: complete collection coverage

packages/discord.js/src/structures/GuildMember.js, packages/discord.js/src/structures/User.js
=> docs: Lowercase "image" URL

packages/ws/src/strategies/sharding/SimpleShardingStrategy.ts, packages/ws/src/ws/WebSocketManager.ts
=> fix(WebSocketManager): heartbeat event had outdated types

packages/builders/package.json, packages/core/package.json, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, pnpm-lock.yaml
Bumps discord-api-types to 0.37.93 for #10399
=> build: bump discord-api-types to 0.37.93

package.json, packages/brokers/package.json, packages/builders/package.json, packages/collection/package.json, packages/core/package.json, packages/create-discord-bot/package.json, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/proxy-container/package.json, packages/proxy/package.json, packages/rest/package.json, packages/scripts/turbo/generators/templates/default/package.json.hbs, packages/ui/package.json, packages/util/package.json, packages/voice/package.json, packages/ws/package.json
Sorry not sorry for the requested reviews, but it was about time to bring my email in sync with my GitHub email. Jiralite also updated their email
=> chore: update emails

packages/builders/package.json, packages/core/package.json, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, pnpm-lock.yaml
Unblocks:
- #10443
- #10445
- #10440
=> build: bump discord-api-types to 0.37.94

packages/discord.js/package.json, pnpm-lock.yaml
=> chore: pin builders in discord.js

packages/brokers/cliff.toml, packages/builders/cliff.toml, packages/collection/cliff.toml, packages/core/cliff.toml, packages/create-discord-bot/cliff.toml, packages/discord.js/cliff.toml, packages/formatters/cliff.toml, packages/next/cliff.toml, packages/proxy/cliff.toml, packages/rest/cliff.toml, packages/scripts/turbo/generators/templates/default/cliff.toml, packages/ui/cliff.toml, packages/util/cliff.toml, packages/voice/cliff.toml, packages/ws/cliff.toml
Not all footers are breaking changes
since version 2 of git-cliff the tag_pattern option is a regex, fixes discord.js tag matching 
=> chore: update cliff configs

packages/discord.js/src/client/Client.js
=> fix(Client): never pass token in ws constructor

packages/discord.js/src/client/Client.js
Unfortunately https://github.com/discordjs/discord.js/pull/10519 was merged automatically by Kodiak after a bad rebase, which reverted some changes made by other commits.
=> fix: rebase fail

packages/builders/__tests__/components/button.test.ts, packages/builders/__tests__/types.test.ts
Updates the builder methods to their correct name. Also removes an unused import.
=> test: Fix builder methods in type test

packages/builders/package.json, packages/core/package.json, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, pnpm-lock.yaml
Bumps `discord-api-types` to `0.37.107`
=> chore(deps): bump `discord-api-types`

packages/discord.js/src/util/APITypes.js
=> docs: correct discord-api-types URLs

packages/discord.js/src/managers/RoleManager.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Remnant of #10421—the code was already modified, just not the typings or documentation.
=> fix(RoleManager): Fetching roles is not nullable

packages/discord.js/src/managers/ApplicationCommandManager.js, packages/discord.js/src/structures/ApplicationCommand.js, packages/discord.js/src/structures/Message.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
=> refactor!: Remove deprecations

packages/discord.js/src/structures/Subscription.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/7304
=> feat(Subscription): add `renewalSkuIds`

packages/create-discord-bot/template/Bun/JavaScript/package.json, packages/create-discord-bot/template/Bun/TypeScript/package.json, packages/create-discord-bot/template/Deno/src/commands/index.ts, packages/create-discord-bot/template/Deno/src/events/index.ts, packages/create-discord-bot/template/Deno/src/events/ready.ts, packages/create-discord-bot/template/Deno/src/index.ts, packages/create-discord-bot/template/Deno/src/util/deploy.ts, packages/create-discord-bot/template/Deno/src/util/registerEvents.ts, packages/create-discord-bot/template/JavaScript/package.json, packages/create-discord-bot/template/TypeScript/package.json
=> feat: Upgrade create-discord-bot dependencies

packages/brokers/cliff.toml, packages/builders/cliff.toml, packages/collection/cliff.toml, packages/core/cliff.toml, packages/create-discord-bot/cliff.toml, packages/discord.js/cliff.toml, packages/formatters/cliff.toml, packages/next/cliff.toml, packages/proxy/cliff.toml, packages/rest/cliff.toml, packages/scripts/turbo/generators/templates/default/cliff.toml, packages/ui/cliff.toml, packages/util/cliff.toml, packages/voice/cliff.toml, packages/ws/cliff.toml
Even when the scope is build, chore, etc... if it's breaking it goes in the changelog....
=> chore(cliff): don't skip breaking commits

packages/rest/__tests__/CDN.test.ts, packages/rest/src/lib/CDN.ts
See https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints.
=> fix: Correct guild member banner URL

packages/builders/package.json, packages/core/package.json, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, pnpm-lock.yaml
=> build: bump discord-api-types to 0.37.118

packages/discord.js/src/client/actions/PresenceUpdate.js
#10672 introduced some changes that had incorect relative path. This doesn't need changing in the `main` as #10666 removed the concered file
=> fix: incorrect relative path

.github/ISSUE_TEMPLATE/01-package_bug_report.yml
=> chore: Update `GuildEmojisAndStickers` in bug report form

packages/actions/package.json, packages/discord.js/package.json, packages/proxy/package.json, packages/rest/package.json, packages/scripts/package.json, packages/ws/package.json, pnpm-lock.yaml
This PR **only** includes non-code changes, like changes to documentation, README, etc.
Closes #10729
=> build: Update undici to 6.21.1

packages/discord.js/src/structures/MessagePayload.js
=> fix(MessagePayload): preserve existing flags when editing

packages/create-discord-bot/src/util/constants.ts
Pointing the guide to the updated one rather than the stale one.
=> refactor(constants): Update guide URL

packages/discord.js/typings/index.d.ts
=> types(ModalSubmitFields): fix `fields` type

package.json
https://pnpm.io/settings#peerdependencyrulesallowany
=> build: `allowAny` instead of `allowedAny`

packages/actions/package.json, packages/discord.js/package.json, packages/proxy/package.json, packages/rest/package.json, packages/rest/src/strategies/undiciRequest.ts, packages/scripts/package.json, packages/ws/package.json, pnpm-lock.yaml
Finally updating Undici to 7.8.0.
=> build: Bump Undici to 7.8.0

apps/website/src/components/UnionMember.tsx, packages/scripts/src/generateSplitDocumentation.ts
=> fix(website): add type to variables

packages/create-discord-bot/template/Deno/src/util/loaders.ts, packages/create-discord-bot/template/JavaScript/src/util/loaders.js, packages/create-discord-bot/template/TypeScript/src/util/loaders.ts
=> fix: structure imports on windows

packages/discord.js/src/structures/ApplicationCommand.js
Changes the method in the example to the correct one
=> docs(ApplicationCommand): incorrect method in example

packages/builders/src/index.ts
Adds a missed export for the Container component in the builders package
=> fix(builders): export container component

packages/discord.js/src/managers/GuildSoundboardSoundManager.js, packages/discord.js/src/structures/GuildAuditLogsEntry.js, packages/discord.js/typings/index.d.ts
- Fixes `data.map is not a function` error
- Consolidates `fetch` parameters into a single `options` parameter and also aligns it with other fetch methods
- Adds missing soundboard sound audit log changes missed in #10843 
=> feat: soundboard missing things

packages/discord.js/src/structures/GuildAuditLogsEntry.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Backports https://github.com/discordjs/discord.js/pull/10591/
=> fix(GuildAuditLogEntry): fix some incorrect types and runtime logic

.github/workflows/cleanup-cache.yml, .github/workflows/documentation.yml, packages/actions/package.json, packages/actions/src/pnpmCache/action.yml, packages/actions/src/uploadDocumentation/index.ts, packages/actions/src/uploadSplitDocumentation/index.ts, packages/actions/tsconfig.test.json, pnpm-lock.yaml
Should fix our docs not uploading to the website
=> chore(ci): backport actions updates

packages/discord.js/src/managers/GuildSoundboardSoundManager.js
=> fix(GuildSoundboardSoundManager): value "undefined" is not snowflake

apps/website/src/components/ConstructorNode.tsx, apps/website/src/components/DocItem.tsx
Constructors were missing examples and see blocks.
=> feat(website): show examples on constructors

packages/builders/CHANGELOG.md, packages/builders/package.json, packages/core/package.json, packages/formatters/package.json, packages/rest/CHANGELOG.md, packages/rest/package.json, packages/ws/package.json
=> chore: forward-port release metadata from side branches

packages/proxy-container/Dockerfile
Fixes #10884 
https://discord.com/channels/222078108977594368/999796393810067607/1359887883372068895
=> build: fix deploy failure

packages/create-discord-bot/template/Bun/JavaScript/package.json, packages/create-discord-bot/template/Bun/TypeScript/package.json, packages/create-discord-bot/template/Deno/src/commands/index.ts, packages/create-discord-bot/template/Deno/src/events/index.ts, packages/create-discord-bot/template/Deno/src/events/ready.ts, packages/create-discord-bot/template/Deno/src/index.ts, packages/create-discord-bot/template/Deno/src/util/deploy.ts, packages/create-discord-bot/template/Deno/src/util/registerEvents.ts, packages/create-discord-bot/template/JavaScript/package.json, packages/create-discord-bot/template/TypeScript/package.json
=> chore: update create-discord-bot dependencies

packages/discord.js/src/util/Components.js
=> perf(Components): Hash table

apps/website/src/components/Badges.tsx, apps/website/src/components/DocItem.tsx, apps/website/src/components/DocNode.tsx, apps/website/src/components/EventNode.tsx, apps/website/src/components/MethodNode.tsx, apps/website/src/components/PropertyNode.tsx
=> fix: codeblock background and other mobile issues

packages/create-discord-bot/README.md, packages/create-discord-bot/scripts/rename-to-app.mjs
Fixes prettier linting when the script is called
=> chore: fix create-discord-bot -> create-discord-app formatting

README.md, apps/guide/README.md, apps/website/README.md, packages/actions/README.md, packages/api-extractor-utils/README.md, packages/brokers/README.md, packages/builders/README.md, packages/collection/README.md, packages/core/README.md, packages/create-discord-bot/README.md, packages/discord.js/README.md, packages/docgen/README.md, packages/formatters/README.md, packages/next/README.md, packages/proxy-container/README.md, packages/proxy/README.md, packages/rest/README.md, packages/scripts/README.md, packages/ui/README.md, packages/util/README.md, packages/voice/README.md, packages/ws/README.md
Wake up the entire org to correct the tests badge on packages
=> chore: update tests badge across repository

packages/builders/src/components/v2/Assertions.ts
- https://github.com/discord/discord-api-docs/pull/7534
=> fix(containerPredicate): Remove maximum limit

packages/builders/package.json, packages/core/package.json, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, pnpm-lock.yaml
=> build: bump discord-api-types to 0.38.15

packages/discord.js/src/util/Events.js, packages/discord.js/typings/index.d.ts
=> fix(Events): `WebhooksUpdate` enum value

apps/guide/content/docs/legacy/additional-info/meta.json, apps/guide/content/docs/legacy/additional-info/proxy.mdx, apps/guide/content/docs/legacy/oauth2/oauth2.mdx, apps/guide/content/docs/legacy/sharding/additional-information.mdx, apps/guide/content/docs/legacy/slash-commands/permissions.mdx, apps/guide/content/docs/legacy/slash-commands/response-methods.mdx, apps/guide/content/docs/voice/meta.json, apps/guide/content/docs/voice/seeking.mdx
Apply suggestions and PRs from the legacy guide repository
=> feat(guide): port remaining prs/issues from legacy

packages/discord.js/src/managers/GuildMemberRoleManager.js, packages/discord.js/src/managers/RoleManager.js, packages/discord.js/src/structures/Role.js, packages/discord.js/src/util/Constants.js, packages/discord.js/typings/index.d.ts
=> feat: Role gradient colours

packages/core/package.json, packages/core/src/api/oauth2.ts, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, pnpm-lock.yaml
Upgrades discord-api-types for v14.
=> build: Upgrade discord-api-types

packages/discord.js/src/managers/MessageManager.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
=> feat(MessageManager): New pinned messages routes

packages/core/src/api/guild.ts, packages/discord.js/src/managers/GuildManager.js, packages/discord.js/typings/index.d.ts
Per https://discord.com/developers/docs/change-log#deprecating-guild-creation-by-apps, the endpoint is no longer available.
=> fix!: Remove guild creation

.github/workflows/release.yml, packages/actions/src/releasePackages/action.yml, packages/actions/src/releasePackages/generateReleaseTree.ts
- Added @discordjs/structures
- Resolves yaml-schema errors
- Added a description
- Fixed a typo
- Made booleans a string
- Corrected `ssh_key` to `ssh-key`
- Running with Node.js 22
- Fixes dev releases typo
=> ci(release): Miscellaneous fixes

.github/workflows/publish-dev.yml
Fixes messed up removal of strategy from rebase and adds description for input
=> ci(release): fix dev releases

packages/rest/__tests__/UndiciRequest.test.ts, packages/rest/src/strategies/undiciRequest.ts
=> fix: attachment sending

packages/ui/src/lib/components/Alert.tsx, packages/ui/src/lib/components/Section.tsx, packages/ui/src/lib/components/discord/Message.tsx, packages/ui/src/lib/components/discord/Messages.tsx, pnpm-lock.yaml
Regenerating this file should solve a lot of alerts we get.
=> build: Upgrade pnpm-lock.yaml

packages/create-discord-bot/template/Bun/JavaScript/package.json, packages/create-discord-bot/template/Bun/TypeScript/package.json, packages/create-discord-bot/template/Deno/src/commands/index.ts, packages/create-discord-bot/template/Deno/src/events/index.ts, packages/create-discord-bot/template/Deno/src/events/interactionCreate.ts, packages/create-discord-bot/template/Deno/src/events/ready.ts, packages/create-discord-bot/template/Deno/src/index.ts, packages/create-discord-bot/template/Deno/src/util/deploy.ts, packages/create-discord-bot/template/JavaScript/package.json, packages/create-discord-bot/template/TypeScript/package.json
=> feat: bump discord.js in create-discord-bot/app

packages/discord.js/src/managers/GuildManager.js, packages/discord.js/src/structures/Guild.js, packages/discord.js/src/structures/GuildTemplate.js, packages/discord.js/typings/index.d.ts
Backports:
- #11012
- #11021
- #11068
=> docs: Deprecate API related to guild ownership

packages/builders/package.json, packages/builders/src/components/label/Label.ts, packages/builders/src/interactions/modals/Modal.ts, packages/core/package.json, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/rest/package.json, packages/structures/package.json, packages/voice/package.json, packages/ws/package.json, pnpm-lock.yaml
=> build: Update discord-api-types to 0.38.23

packages/discord.js/src/errors/ErrorCodes.js, packages/discord.js/src/errors/Messages.js, packages/discord.js/src/structures/CommandInteraction.js, packages/discord.js/src/structures/LabelComponent.js, packages/discord.js/src/structures/Message.js, packages/discord.js/src/structures/ModalSubmitFields.js, packages/discord.js/src/structures/ModalSubmitInteraction.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/src/util/Components.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Adds support of other select menus and text display
Resolves #11085 and implements ##11111.
Requires:
- #11090 
=> feat: text display and more selects in modal for v14

packages/discord.js/src/structures/GuildMember.js
Conditionally chooses which edit route to use based on the user id.
=> fix(GuildMember): Use `editMe()` conditionally for `setNickname()` helper

packages/builders/__tests__/components/v2/separator.test.ts, packages/builders/__tests__/components/v2/textDisplay.test.ts, packages/builders/src/Assertions.ts, packages/builders/src/components/Assertions.ts, packages/builders/src/components/label/Assertions.ts, packages/builders/src/components/textInput/Assertions.ts, packages/builders/src/components/v2/Assertions.ts
There was no predicate for ids. The tests I have added are expected to fail, and would otherwise succeed without this change.
=> fix: Add `idPredicate`

packages/discord.js/src/util/APITypes.js
=> docs(APITypes): Add `APISelectMenuDefaultValue`

packages/builders/src/components/Assertions.ts
Small mistake, happens to the best of us
=> fix(builders): correct assertion for select menu string min/max values

packages/formatters/__tests__/escapers.test.ts, packages/formatters/src/escapers.ts
=> feat!: add `escapeQuote` and `escapeBlockQuote`
