hydrabot/hydrabot.js
index.js

Major load time improvements. around 33% performance gains

bring some very cool optimisations

---

index.js

speed boost helps to relieve startup times by around 500ms (however long it takes to get a response from login approx)

pull impressive startup speed boost

---

index.js

Hey! (Don't know if you saw my previous pull request but had to correct it)
Basically, I was using your bot and I needed a getChannelByName getter. So I decided to add it to your code. Do you think this should be there? Or was there already a better way to do it?
Thanks! Also, great work so far. Thanks a lot for this.

Added function to get channel by name.

---

README.md

Specifically the code formatting codes.

Fix formatting of Discord text format codes

---

src/ChannelPermissions.js
src/Member.js

Fix `ChannelPermissions.asAllowDisallow()` and `Member.permissionsIn(channel)`

Fix permissions

---

docs/docs_events.rst

I've added a new doc page to list the events fired by the client with (very) basic code examples and the available parameters. I followed your restructured text code style. Please tell me if anything is missing and/or incorrect so I can change it.

Version 1 of the event documentation of the client (bot) class.

---

lib/Client/Client.js
lib/Client/InternalClient.js
lib/Client/Resolver/Resolver.js
lib/Voice/AudioEncoder.js
lib/Voice/StreamIntent.js
lib/Voice/VoiceConnection.js
lib/Voice/VoicePacket.js
lib/index.js
package.json
src/Client/Client.js
src/Client/InternalClient.js
src/Client/Resolver/Resolver.js
src/Voice/AudioEncoder.js
src/Voice/StreamIntent.js
src/Voice/VoiceConnection.js
src/Voice/VoicePacket.js
src/index.js
test/bot.1.js

Added basic voice capabilities

---

lib/Client/Client.js
lib/Client/InternalClient.js
src/Client/Client.js
src/Client/InternalClient.js
src/Client/Resolver/Resolver.js
src/Constants.js
src/Structures/Channel.js
src/Structures/ChannelPermissions.js
src/Structures/Invite.js
src/Structures/Message.js
src/Structures/PMChannel.js
src/Structures/PermissionOverwrite.js
src/Structures/Role.js
src/Structures/ServerChannel.js
src/Structures/TextChannel.js
src/Structures/User.js
src/Util/Equality.js
src/Voice/AudioEncoder.js
src/Voice/VoiceConnection.js
src/Voice/VoicePacket.js

Not sure if this fully conforms with existing code standards, but pulling anyway. Implementations appeared to work in testing, but I'm the only one to have tested these.

Get bans, unban, kick, and trailing spaces

---

src/Client/InternalClient.js

promise simplification and optimisation
use Array.map instead of forEach for mapping
added missing rethrows
emit error events in typing
removed unusued EventEmitter import
no braces for single arg arrow function
added missing semicolons

make use of qs instead of manually building querystring

---

src/Voice/VoiceConnection.js

This will hopefully fix #61 so far @koriwi said it fixes his problems and I haven't found any compatibility problems so far.
Apparently sublime also changed some of the white-spaces to tabs, so I guess that's something extra :)

Potential fix for streams not terminating

---

src/Client/Client.js
src/Client/ConnectionState.js
src/Client/InternalClient.js
src/Client/Resolver/Resolver.js
src/Constants.js
src/Structures/Channel.js
src/Structures/ChannelPermissions.js
src/Structures/Invite.js
src/Structures/Message.js
src/Structures/PMChannel.js
src/Structures/PermissionOverwrite.js
src/Structures/Role.js
src/Structures/Server.js
src/Structures/ServerChannel.js
src/Structures/TextChannel.js
src/Structures/User.js
src/Structures/VoiceChannel.js
src/Util/ArgumentRegulariser.js
src/Util/Cache.js
src/Util/Equality.js
src/Voice/AudioEncoder.js
src/Voice/StreamIntent.js
src/Voice/VoiceConnection.js
src/Voice/VoicePacket.js
src/index.js

Mostly eye candy.
But this will also make sure imports aren't overwritten since they are const.

Use import/export since we are using babel, removed unused imports

---

.npmignore

Add TODO.md to npmignore

---

src/Client/InternalClient.js
src/Client/Resolver/Resolver.js

Cleans up some logic removes some redundant code by making error messages useful.

Resolvererrors

---

entrypoint.js

This should hopefully prevent questions from people running a version less than that.

Add hard check that exits node if the node version is less than 0.12.7.

---

src/Client/InternalClient.js

Added user-agent with discord.js information

---

lib/Voice/AudioEncoder.js
lib/Voice/VoiceConnection.js
src/Voice/AudioEncoder.js
src/Voice/VoiceConnection.js

Fix ffmpeg stalling and timestamps/sequence resetting on each `playStream` call

Voice fixes

---

lib/Client/Client.js
lib/Client/ConnectionState.js
lib/Client/InternalClient.js
lib/Client/Resolver/Resolver.js
lib/Constants.js
lib/Structures/Channel.js
lib/Structures/ChannelPermissions.js
lib/Structures/Invite.js
lib/Structures/Message.js
lib/Structures/PMChannel.js
lib/Structures/PermissionOverwrite.js
lib/Structures/Role.js
lib/Structures/Server.js
lib/Structures/ServerChannel.js
lib/Structures/TextChannel.js
lib/Structures/User.js
lib/Structures/VoiceChannel.js
lib/Util/ArgumentRegulariser.js
lib/Util/Cache.js
lib/Util/Equality.js
lib/Util/TokenCacher.js
lib/Voice/AudioEncoder.js
lib/Voice/StreamIntent.js
lib/Voice/VoiceConnection.js
lib/Voice/VoicePacket.js
lib/index.js
src/Client/Client.js
src/Client/InternalClient.js

A set of internal changes and bugfixes inside Client. This fixes #105, #111, #112, #113, #114, #115, #116 and #117. I also rebuilt the lib/ folder as it was done previously, i.e. not minified, if it should be minified instead, tell me and I'll rebuild it like that.

Callback bugfixes

---

lib/Client/Client.js
lib/Client/InternalClient.js
lib/Structures/User.js
src/Client/Client.js
src/Client/InternalClient.js
src/Structures/User.js

Fixes issues #123 and #130, the problem reported [here](https://github.com/hydrabolt/discord.js/commit/404829a19d0b23aa22fdaf83fe199f21ba9897e9#commitcomment-15258094) and a latent issue that hasn't appeared before (see f51fecf comment).

Various fixes

---

src/Voice/AudioEncoder.js

fixed volume option and set default to 25% to avoid hearing loss

---

docs/docs_client.rst
lib/Client/Client.js
lib/Client/InternalClient.js
src/Client/Client.js
src/Client/InternalClient.js

This adds a new method `Client.loginWithToken` which logs the bot in using just a token. See #159

Allow tokens to be used for login

---

docs/docs_client.rst
lib/Client/Client.js
lib/Client/InternalClient.js
src/Client/Client.js
src/Client/InternalClient.js

Fixes #144; "Voice Move" on the library comparison.

Allow moving users to voice channels

---

lib/Client/InternalClient.js
src/Client/InternalClient.js

- Fix syntax error on setUsername()
- Fix Game Status not been set to null when a game is closed.

Fix setUsername() Crash and Game Status

---

docs/docs_voiceconnection.rst
lib/Voice/AudioEncoder.js
src/Voice/AudioEncoder.js

Allow seeking for FFmpeg

---

lib/Util/TokenCacher-shim.js
lib/Voice/AudioEncoder.js
lib/Voice/VoiceConnection.js
lib/Voice/VolumeTransformer.js
src/Voice/AudioEncoder.js
src/Voice/VoiceConnection.js
src/Voice/VolumeTransformer.js

Adding volume wrapper

---

lib/Util/TokenCacher-shim.js
lib/Voice/VoiceConnection.js
lib/Voice/VolumeTransformer.js
src/Voice/VoiceConnection.js

Add ability to pause and resume audio thats being played

---

lib/Voice/VolumeTransformer.js
src/Voice/VolumeTransformer.js

Fixes #242. I went with not changing the way the multiplier is computed by default to the new way (I changed it back to the linear way), but instead giving the user a simple way to set the volume exactly as they want it.

Volume fixes

---

lib/Client/Client.js
lib/Client/InternalClient.js
lib/Constants.js
src/Client/Client.js
src/Client/InternalClient.js
src/Constants.js

Had a go at trying to implement something. Mostly tested but still not quite sure if everything is very efficient or 100%, need some verification.
As a note, `addFriend` can mean requesting someone, or accepting someone's friend request. The same for `removeFriend`, it can mean removing someone as a friend, or ignoring someone's friend request. (they each use the same endpoints)

Friends (relationships) support

---

lib/Client/Client.js
lib/Client/InternalClient.js
src/Client/Client.js
src/Client/InternalClient.js

Since the unofficial api docs don't have this documented, I had to go off of discord.io. Seems to be working without issues.
-Side note: Github for windows sucks.

Added mute, unmute, deafen, undeafen

---

lib/Client/InternalClient.js
src/Client/InternalClient.js

Should fix #275 and also another case where send outgoing from other cilent and also that is removed on that other client.
(Correct branch this time)

Friend request remove packet fixes

---

docs/docs_client.rst
lib/Constants.js
src/Constants.js

If you'd like it to be at the bottom I'm gonna change it

Add nickname permission constants

---

docs/docs_permissionconstants.rst
docs/docs_server.rst
lib/Client/InternalClient.js

Also some docs additions from previous udpates.
*Please don't hit me for creating a PR :c*

Fix not being able to set own nick

---

docs/docs_client.rst
lib/Client/Client.js
lib/Client/InternalClient.js
src/Client/Client.js
src/Client/InternalClient.js

bot.setStreaming(name, url, type, callback); added
logic for Internal setStatus updated to check if string or object

Added support for new game objects

---

lib/Client/Client.js
lib/Client/InternalClient.js
src/Client/Client.js
src/Client/InternalClient.js

`client.deleteMessages(messages)`
Where `messages` is an array of `Message` resolvables.
It does check whether the messages are from the same channel as you can only delete from one channel at a time...

Bulk deleting endpoint support (#336)

---

lib/Util/Cache.js
src/Util/Cache.js

Fixed the function so it complies with the documentation

Fixed Cache.has function

---

docs/docs_client.rst
docs/vars.rst

Not too dramatic but led to some confusion for some1

Fix linking in indev docs

---

docs/docs_client.rst
docs/docs_serverchannel.rst
docs/docs_voiceconnection.rst
lib/Client/InternalClient.js
lib/Structures/ServerChannel.js
lib/Structures/TextChannel.js
src/Client/InternalClient.js
src/Structures/ServerChannel.js
src/Structures/TextChannel.js

Also documented two methods for voice connections. (pause and resume)

Update channel improvements

---

lib/Client/InternalClient.js
lib/Util/TokenCacher-shim.js
src/Client/InternalClient.js

Also return error if no server (dm)
*This token cacher thing always changes when I do grunt --dev, so this time I decided to just leave it in the commit <.<*

Fix bulk deletion error if < 2 messages (#374)

---

lib/Client/InternalClient.js
lib/Util/TokenCacher-shim.js
lib/Voice/AudioEncoder.js
src/Voice/AudioEncoder.js

I am by no means sure that this will work. This is an experimental fix.
Please review it carefully; I’m not the best at working with
audio/streams.

Potential FFMPEG process fix

---

lib/Voice/AudioEncoder.js
lib/Voice/VoiceConnection.js
src/Voice/AudioEncoder.js
src/Voice/VoiceConnection.js

FFMPEG fix (finally!)

---

lib/Voice/AudioEncoder.js
src/Voice/AudioEncoder.js

Fixes `ReferenceError: _this4 is not defined`

fix typo in hookEncodingProcess

---

lib/Voice/AudioEncoder.js
src/Voice/AudioEncoder.js

This is a more proper fix.
Change functions to arrow functions in src to generate the right output in lib.

fix bug in hookEncodingProcess causing playRawStream to not work

---

lib/Client/Client.js
lib/Client/InternalClient.js
src/Client/Client.js
src/Client/InternalClient.js

Adds support for guild sharding by adding `shardId` and `shardCount` options to client. Closes #376

add guild sharding support

---

docs/docs_client.rst

Simple explanation of shardId, shardCount.

add docs for shardId, shardCount client parameters

---

docs/docs_client.rst
lib/Client/Client.js
lib/Client/InternalClient.js
src/Client/Client.js
src/Client/InternalClient.js

I'm sure everyone gets tired of dealing with this themselves.

Add disableEveryone option

---

lib/Client/InternalClient.js
src/Client/InternalClient.js

Unsets the game if empty string is passed in `setPlayingGame()` or `setStatus()`.

unset game if empty string is passed

---

lib/Client/InternalClient.js
src/Client/InternalClient.js

Sometimes the VOICE_SERVER_UPDATE packet will contain a valid guild_id
but no token/endpoint.

Handle incomplete websocket message

---

docs/docs_client.rst

Small change fixes disableEveryone and adds User Resolvable to sendMessage and sendFile

sendMessage doc fix

---

docs/docs_client.rst
docs/docs_user.rst
lib/Client/Client.js
lib/Client/InternalClient.js
lib/Constants.js
lib/Structures/User.js
src/Client/Client.js
src/Client/InternalClient.js
src/Constants.js
src/Structures/User.js

Suggestions in comments pls kthx

Add notes (#327)

---

lib/Constants.js
src/Constants.js

Discord.Constants was undefined from what seems to have been an issue with babel and the way they were being exported.

Change the way constants are exported

---

lib/Constants.js
src/Constants.js

Missed the Endpoints references to self in the first PR, this should resolve the issue, and there aren't any others.

fix Endpoints bug created in constants pr

---

docs/docs_client.rst
docs/docs_message.rst
lib/Client/Client.js
lib/Client/InternalClient.js
lib/Constants.js
lib/Structures/Message.js
src/Client/Client.js
src/Client/InternalClient.js
src/Constants.js
src/Structures/Message.js

Added methods:
`pinMessage()`
`unpinMessage()`
`getPinnedMessages()`
Added params for getChannelLogs:
`around`

Add pinning

---

lib/Structures/Server.js
lib/Util/TokenCacher-shim.js
src/Structures/Server.js

Should fix https://github.com/hydrabolt/discord.js/issues/430
Issue was .has() has specific meaning for the cach, while .includes() will check if the cach contains the user

fix voice state updates

---

docs/docs_client.rst
lib/Client/Client.js
lib/Client/InternalClient.js
lib/Structures/TextChannel.js
lib/Util/TokenCacher-shim.js
src/Client/Client.js
src/Client/InternalClient.js
src/Structures/TextChannel.js
test/lib-test.js

The original code wasn't valid anyway. If y'all want to keep the function, we could just fix the function, however I doubt anybody uses that.
¯\\(ツ)/¯

Removed Client#setChannelNameAndTopic and any relevant references (fixed).

---

docs/examples.rst
docs/index.rst
docs/vars.rst

Lots of people complain that the lack of usage examples on the docs make it difficult for beginners. I started this today, and while it isn't done, it's a start. I'm open to any critique of course :stuck_out_tongue:

Added examples section to docs

---

docs/examples.rst

Wrote some simple examples on how to send and reply to messages. Also, atom made those weird whitespace changes :100: :ok_hand: :facepunch: 
I saw Technoguyfication make a PR to master so I hope I am supposed to do so to.
If something needs to be changed, then let me know!

Moar doc examples

---

docs/examples.rst
docs/vars.rst

Docs update

---

lib/Structures/ChannelPermissions.js
src/Structures/ChannelPermissions.js

Update ChannelPerimssions.serialise() and make it future proof

---

docs/examples.rst

Another batch of examples. Tell me if something needs to be changed.

Doc examples for sending files, deleting messages and logging in

---

docs/examples.rst

Fix typos and status update examples

---

docs/docs_client.rst
src/Client/Client.js
src/Client/InternalClient.js

This works, but I'm not sure about the Promise at the end of loginWithToken. Does that token return at L531 do anything?
#508

Add 'Bot' prefix to token

---

lib/Client/Client.js
lib/Client/InternalClient.js
lib/Util/TokenCacher-shim.js
src/Client/InternalClient.js

Added nonce support to 'sendMessage'

---

lib/Structures/Emoji.js
lib/Structures/Message.js
lib/Structures/PMChannel.js
lib/Structures/PermissionOverwrite.js
lib/Structures/Role.js
lib/Structures/Server.js
lib/Structures/ServerChannel.js
lib/Structures/TextChannel.js
lib/Structures/User.js
lib/Structures/VoiceChannel.js
lib/Util/TokenCacher-shim.js
src/Structures/Emoji.js
src/Structures/Message.js
src/Structures/PMChannel.js
src/Structures/PermissionOverwrite.js
src/Structures/Role.js
src/Structures/Server.js
src/Structures/ServerChannel.js
src/Structures/TextChannel.js
src/Structures/User.js
src/Structures/VoiceChannel.js

Adds a `.toObject()` method to structures for converting to plain objects.

add .toObject() method to structures

---

lib/Structures/Role.js
src/Structures/Role.js

Don't return true for manageRoles!
Added administrator to serialize as well.

change role hasPermission to return true for administrator

---

src/client/Client.js
src/client/actions/ActionsManager.js
src/client/actions/UserGet.js
src/client/rest/RESTMethods.js
src/util/Constants.js

This allows you to forcefully add a user to the cache with their ID, in order to ensure their information is accessible.

Add client.cacheUser method

---

src/Structures/ChannelPermissions.js

administrator should allow all commands, not manageRoles.

ChannelPermissions changed manageRoles to administrator. fixes #507

---

src/structures/interface/TextBasedChannel.js

https://images.typicalbot.com/i/57c4dcc5d74b7.png

Fixed sendFile

---

lib/Structures/ChannelPermissions.js
lib/Structures/Role.js
src/Structures/ChannelPermissions.js
src/Structures/Role.js

Forgot to change ChannelPermissons inside lib directory. Should actually be correct now.
Also fixed commenting in Role.js related to same bug.

Fixed manageRoles bug in lib. Fixes #507

---

src/client/ClientDataResolver.js

For consistency with `resolveUser` and `resolveChannel`

Add string guild resolving

---

src/client/actions/Action.js
src/client/actions/ActionsManager.js
src/client/actions/ChannelCreate.js
src/client/actions/ChannelDelete.js
src/client/actions/ChannelUpdate.js
src/client/actions/GuildBanRemove.js
src/client/actions/GuildDelete.js
src/client/actions/GuildMemberRemove.js
src/client/actions/GuildRoleCreate.js
src/client/actions/GuildRoleDelete.js
src/client/actions/GuildRoleUpdate.js
src/client/actions/GuildSync.js
src/client/actions/GuildUpdate.js
src/client/actions/MessageCreate.js
src/client/actions/MessageDelete.js
src/client/actions/MessageDeleteBulk.js
src/client/actions/MessageUpdate.js
src/client/actions/UserGet.js
src/client/actions/UserUpdate.js
src/client/rest/RESTMethods.js
src/client/websocket/packets/handlers/MessageCreate.js
src/client/websocket/packets/handlers/MessageDelete.js

Clean up Actions code

---

docs/custom/documents/updating.md

initial "more information" about updating

---

docs/custom/documents/welcome.md

Just noticed that the command needs updating on the welcome page. :P

Update installation command in welcome

---

src/index.js

Add more exports

---

src/client/voice/player/BasePlayer.js

fix epipe error and probably fixes econnreset

---

src/client/voice/pcm/FfmpegConverterEngine.js

add a message, because WHY THE HELL DID NO ONE EVER DO THIS

---

.eslintrc.json
src/client/Client.js
src/sharding/Shard.js
src/sharding/ShardingManager.js

makes sharding smarter and automatic.

wumpus and i had a heart2code talk and this is what we came up with

---

src/client/ClientManager.js
src/client/websocket/WebSocketManager.js
src/util/Constants.js

makes login actually reject when login is incorrect WHO WOULD HAVE THOUGHT IT WAS POSSIBLE AMIRITE

make login sane

---

src/client/ClientManager.js

this is quite the facepalm moment

fix heartbeat

---

src/structures/EvaluatedPermissions.js
src/structures/GuildMember.js

Decided to take a crack at my request #755 ... Seems to work functionally, but do double check that I did the docs right. Still unsure of myself on them.

Added .missingPermissions()

---

src/client/Client.js
src/client/ClientDataResolver.js

Add InviteResolvable

---

src/util/Collection.js

Cache array and keyArray in the Collection class to improve consecutive
calls of collection.random() by around 400,000%, I think lel.
The speed decrease (I assume) compared to the previous version when
calling after it has changed is most likely negligible.

Cache array and keyArray in Collection

---

src/client/Client.js
src/client/websocket/packets/WebSocketPacketManager.js

Convert disabledEvents Array to Object

---

src/client/voice/VoiceWebSocket.js
src/structures/Guild.js

such quality, much wow

---

.travis.yml
docs/deploy/deploy.sh

See the commit log for what this PR does, the messages should be fairly straightforward.
**This PR depends on #907!** It also requires an orphan `webpack` branch with at least one commit that is ignored by Travis.
cc @GusCaplan

Update the Travis build process

---

package.json
typings/index.d.ts
typings/tsconfig.json

Add typings

---

src/client/rest/RESTMethods.js
src/structures/GuildMember.js
src/util/Constants.js

see hammerandchisel/discord-api-docs#179

support new guild member role endpoints for cleaner role updates

---

docs/custom/documents/faq.md

fixed typo in documentation

---

docs/custom/documents/faq.md

Reverts hydrabolt/discord.js#949

Revert "fixed typo in documentation"

---

src/structures/RichEmbed.js

Because I'm tired and unobservant with regards to the things I'm typing.

Fix embed footer text length error

---

src/structures/RichEmbed.js
test/random.js

Simplified the parsing for color arrays.
Throwing some errors on values that would result in Bad Requests.
Changed setAuthor and setFooter's icon parameter to icon_url to match
the embed object's property name.
Changed the docs for setFooter to reflect that icon_url is optional.

new errors for richembed yay

---

src/client/rest/RESTMethods.js
src/structures/Guild.js
src/structures/GuildChannel.js
src/structures/PermissionOverwrites.js

added only because it was asked for, and the client has this feature.

add GuildChannel#clone

---

src/structures/User.js

looks like someone forgot how to caps

fix defaultAvatarURL

---

src/structures/GroupDMChannel.js
src/structures/GuildChannel.js

Utilizing Collection.equals in GuildChannel.equals
Utilizing Collection.equals in GroupDMChannel.equals

Using the thing

---

src/client/Client.js
src/client/rest/RESTMethods.js

see https://github.com/hammerandchisel/discord-api-docs/issues/69

update per issue 69 on the h&c github

---

src/client/rest/RESTMethods.js
src/structures/ClientUser.js
src/structures/User.js

*i know how annoying those changed update methods are*

fix some things with user updates and tokens and such

---

src/client/rest/APIRequest.js

add payload_json instead of the current iterator

---

src/structures/RichEmbed.js

Changed RichEmbed to take StringResolvable instead of string for all
methods except setColor.
Also changed a few lines in setColor to make sure that the value
assigned to this.color is always a number.

Change RichEmbed to take StringResolvables

---

src/client/ClientDataResolver.js

To reflect the resolver supporting Guild ID strings

Update GuildResolvable typedef

---

src/structures/ClientUser.js

fix setting avatar to buffer

---

src/client/ClientDataResolver.js
src/index.js
src/structures/Channel.js
src/structures/ClientUser.js
src/structures/Emoji.js
src/structures/GroupDMChannel.js
src/structures/Guild.js
src/structures/GuildChannel.js
src/structures/GuildMember.js
src/structures/Message.js
src/structures/MessageAttachment.js
src/structures/MessageCollector.js
src/structures/MessageReaction.js
src/structures/OAuth2Application.js
src/structures/PartialGuild.js
src/structures/PartialGuildChannel.js
src/structures/PermissionOverwrites.js
src/structures/ReactionEmoji.js
src/structures/Role.js
src/structures/TextChannel.js
src/structures/User.js
src/structures/VoiceChannel.js
src/structures/Webhook.js
src/structures/interface/TextBasedChannel.js
src/util/Snowflake.js

The main point of this was to clear up documentation, as `string` was confusing many people, so I added a `Snowflake` typedef.
As a side project, (and since we happened to have `longjs` in our package.json anyway) i added a discord snowflake generator.

snowflakes

---

src/structures/Guild.js

Would either be true or undefined.

Fix <Guild>.large

---

src/util/Collection.js

Reverts hydrabolt/discord.js#1072

Revert "This expands the consistency of .find and .exists to include the id property"

---

src/client/rest/RESTMethods.js
src/structures/interface/TextBasedChannel.js

hammerandchisel/discord-api-docs#208

why you should never make a pr using the github web editor

---

src/client/websocket/packets/handlers/GuildMembersChunk.js
src/structures/Guild.js

GuildMembersChunk packet handler hotfix

---

src/client/voice/receiver/VoiceReceiver.js

silly hydar... you can't have one Opus engine instance for every stream

VoiceReceiver: multiple streams fix

---

src/client/actions/MessageCreate.js
src/structures/GuildMember.js
src/structures/User.js
src/structures/interface/TextBasedChannel.js

This way, you can identify where the message is coming from and plus get all the data about it. 👍 
(See issue #1134)

Add User.lastMessage, GuildMember.lastMessage and TextBasedChannel.lastMessage

---

src/structures/GuildChannel.js

check if a guildchannel is deletable

---

src/client/voice/VoiceBroadcast.js
src/client/voice/VoiceConnection.js
src/client/voice/dispatcher/StreamDispatcher.js
src/client/voice/opus/BaseOpusEngine.js
src/client/voice/opus/OpusEngineList.js
src/client/voice/opus/OpusScriptEngine.js
src/client/voice/player/AudioPlayer.js
src/client/voice/receiver/VoiceReceiver.js
src/client/voice/util/VolumeInterface.js

Opus stream support is important if you want to easily stream Opus data.
The volume code for StreamDispatcher and VoiceBroadcast was almost completely identical, so I merged it into one interface.
Also did various cleanups and fixes around voice-related things.

Added Opus stream support, added volume interface

---

src/client/voice/opus/OpusEngineList.js

Properly check whether an Opus engine exists

---

src/client/ClientDataManager.js
src/client/actions/GuildEmojiUpdate.js
src/client/rest/RESTMethods.js
src/structures/Emoji.js
src/util/Constants.js

This adds support for editing emojis.
I wasn't quite sure what to change in the ClientDataMananger or GuildEmojiUpdate action, but I based it sort of on the GuildUpdate action.

Add support to edit emojis

---

src/client/rest/RESTMethods.js

fix sending code when you aren't splitting the message

---

src/structures/GuildChannel.js

Bool (default to false) to clone the channels topic in a channel.clone()

clone topic in channel.clone()

---

src/client/rest/RESTManager.js
src/client/rest/RequestHandlers/Burst.js
src/client/rest/RequestHandlers/Sequential.js
src/util/Constants.js

fix up ratelimits, **make burst mode finally work!**

Ratelimits

---

src/client/voice/util/VolumeInterface.js

VoiceBroadcast relies on this event to initialize a new Opus engine

Added volumeChange event to VoiceInterface

---

src/client/voice/VoiceConnection.js

Updated VoiceConnection to use new Util class

---

src/client/Client.js
src/client/ClientDataResolver.js
src/client/WebhookClient.js
src/structures/Emoji.js
src/structures/Guild.js
src/structures/GuildMember.js
src/structures/Message.js
src/structures/MessageReaction.js
src/structures/RichEmbed.js
src/structures/Role.js
src/structures/TextChannel.js
src/structures/interface/TextBasedChannel.js

Doc fixes, mostly pertaining to Snowflakes

---

src/structures/GuildMember.js
src/structures/Role.js

Ignore the title of my first commit, it is incorrectly named. This goes with @Gawdl3y 's commits last night.

[Docs] Evaluated Permissions References

---

src/structures/ClientUser.js

Added docs warning for acceptInvite method (user account only iirc)

Added docs warning for acceptInvite method

---

src/client/rest/RESTMethods.js

Otherwise the promise would never resolve.

Fix addRole/removeRole when the user has/doesn't have the role

---

src/client/rest/UserAgentManager.js

was completely tested, don't worry about web commit

make useragent better because data is fun

---

src/structures/MessageReaction.js

Make MessageRection#fetchUsers() return a collection isntead of an array

---

.eslintrc.json
src/client/rest/APIRequest.js
src/client/rest/RESTMethods.js
src/util/Constants.js
src/util/Util.js

makes endpoints follow a nice spec and lets you change the endpoint version and root for things like staging

rewrite endpoints for consistancy and modularity

---

src/client/rest/RESTMethods.js

Replaced all `'del'`s with `'delete'`s in RESTMethods.

Make delete request snekfetch compatible

---

src/structures/Emoji.js
src/structures/User.js

Fixed User#defaultAvatarURL and Emoji#url

---

src/client/rest/RequestHandlers/RequestHandler.js
src/client/voice/VoiceBroadcast.js
src/client/voice/dispatcher/StreamDispatcher.js
src/client/voice/player/AudioPlayer.js
src/structures/Guild.js
src/structures/GuildChannel.js
src/structures/MessageEmbed.js
src/structures/MessageReaction.js
src/structures/Role.js
src/structures/User.js
src/structures/VoiceChannel.js
src/util/Permissions.js

Marked getters as readOnly, if not already.
Also marked propertys with a leading underscore as private, if not already.

Correcting docs regarding readOnly and private propertys

---

src/client/websocket/packets/WebSocketPacketManager.js
src/util/Constants.js

Reverts hydrabolt/discord.js#1339

Revert "add auth session change handling"

---

src/client/voice/VoiceConnection.js

VoiceConnection speaking bugfix

---

src/util/Constants.js

Readded the inviteLink endpoint required for getting the url from an invite.

Readded inviteLink endpoint

---

src/client/ClientDataResolver.js

Adds support for custom emoji IDs and does not return null for pre-encoded unicode

Improved EmojiIdentifierResolvable support

---

src/util/Util.js

- Fixed wrong if statement
- Changed from `for ... in` to `for ... of`
- Also wrote better docs

Fixed Util.arraysEqual, made it better and updated its docs

---

docs/examples/greeting.js
docs/examples/ping.js
docs/examples/webhook.js

fix examples

---

src/client/websocket/WebSocketConnection.js
src/client/websocket/WebSocketManager.js

fix browser websocket skullduggery

---

package.json

snekfetch v3 hype

---

src/structures/MessageCollector.js
src/structures/ReactionCollector.js
src/structures/interfaces/Collector.js

Documentation for the new collector system wasn't correct as merged.

Docs fixes

---

src/structures/GroupDMChannel.js
src/structures/TextChannel.js
src/structures/interfaces/TextBasedChannel.js

TextChannel#nsfw

---

src/structures/GroupDMChannel.js
src/structures/TextChannel.js
src/structures/interfaces/TextBasedChannel.js

fix nsfw stuff

---

src/util/Constants.js

small typo fix in emoji id endpoint

---

src/structures/MessageCollector.js
src/structures/ReactionCollector.js
src/structures/interfaces/Collector.js

Collector docs aren't correct.
**Still to-do:**

[wip] Fix collector documentation (again)

---

src/util/Constants.js

I'm not pr farming, I swear.
Gus told me to fix it.

incorrect variable name convention

---

src/client/rest/DiscordAPIError.js
src/client/rest/DiscordHTTPError.js
src/client/rest/RequestHandlers/Burst.js
src/client/rest/RequestHandlers/Sequential.js
src/util/Constants.js

add cool http errors

---

src/structures/GuildAuditLogs.js

breaking not checked because no releases yet

entries should be a collection <.<

---

src/structures/GuildAuditLogs.js

add doc blocks

---

src/structures/GuildAuditLogs.js

add audit logs "extras"

---

src/structures/GuildMember.js
src/structures/Role.js
src/structures/VoiceChannel.js
src/structures/interfaces/TextBasedChannel.js

update code to stop using deprecated methods

fix deprecation stuff

---

src/structures/GuildAuditLogs.js

add time stuff to guild audit log entries

---

src/structures/GuildAuditLogs.js

adds message_delete to action logs

add MESSAGE_DELETE to audit logs

---

src/util/Constants.js

`[object global]/emojis/<someID>.png` seems not quite right.
Now using the correct endpoint.

Fix for Guild#deleteEmoji and Editing related Emoji methods

---

src/client/websocket/WebSocketConnection.js

Must have been overlooked in the WS rewrite.

Readd docs for Client#error and Client#ready

---

src/structures/GuildAuditLogs.js

Fixed some small mistakes that are currently throwing an error when fetching invite audit log entries.

Using correct properties for invites in GuildAuditLogsEntry

---

src/structures/Invite.js
src/util/Constants.js

Maybe the parameter belongs into RESTMethods, maybe not.

added Invite#presenceCount and Invite#memberCount

---

src/client/rest/RESTMethods.js

Looks like someone forgot to remove the full channel object from the PATCH payload. Fixes #1476

GuildMember#setVoiceChannel fix

---

src/structures/User.js
src/util/Constants.js

make default avatar resolving better

---

src/client/rest/DiscordAPIError.js

fixes infinite loop which throws max call stack range errors

fix infinte loop issue

---

src/structures/interfaces/TextBasedChannel.js

Fixes an issue in awaitMessages that would throw a TypeError.

Fix awaitMessages

---

src/util/Permissions.js

relink Permissions.FLAGS

---

src/util/Permissions.js

Reverts hydrabolt/discord.js#1510

Revert "relink Permissions.FLAGS"

---

src/client/websocket/WebSocketConnection.js

you can't mutate a socket event in some browsers (webpack fix)

---

src/structures/GuildAuditLogs.js

they can be more than just string/num/bool

---

src/structures/shared/SendMessage.js

so arrays are joined again, instead of sent as one new message per element
fixes send(array)

Add resolve content back into send

---

src/structures/User.js

User#defaultAvatarURL should use CDN

---

src/util/Constants.js
src/util/Util.js

I'm not sure who thought this was a good idea, but by removing gateway from Constants.js, it broke fetchRecommendedShards() in Util.js as it uses ${Constants.Endpoints.gateway.bot}. This pull request fixes fetchRecommendedShards.

Fix Util.js : fetchRecommendedShards()

---

src/structures/interfaces/TextBasedChannel.js
src/structures/shared/Search.js

add nsfw option to search

---

src/structures/shared/SendMessage.js

Fix for the issue in #1537 
Sending DM to members works in stable branch, this is only fix for master.

.send() not working on members

---

src/structures/GuildAuditLogs.js

Add MEMBER_ROLE_UPDATE to returning 'UPDATE' array (#1538)

---

src/client/rest/RESTMethods.js
src/structures/interfaces/TextBasedChannel.js

crawl will be less butthurt now

add nsfw options to 11.1 search

---

src/structures/Role.js

`<Role>.editable` errors due to the permission flag changed from "MANAGE_ROLES_AND_PERMISSIONS" to "MANAGE_ROLES". This commit fixes that.

Fix <Role>.editable

---

src/structures/ClientUser.js

Fixes #1548. Adds possibility to remove a set avatar.

Fixes #1548

---

src/client/rest/DiscordAPIError.js
src/structures/ClientUserSettings.js

use object.entries in all the places where it applies

object.entries

---

src/client/voice/opus/OpusEngineList.js

we use node 8 bois

---

src/structures/User.js

I'm sorry to be this petty.
Noticed the a number looked a little off while viewing the 12.0.0 docs.

Replacing ticks

---

src/client/rest/APIRequest.js

discord uses cool uri encoding in reason headers now

---

docs/examples/avatars.js

User.displayAvatarURL was changed from a property to a method so I changed the example accordingly

Update avatar example for v12.0

---

test/shard.js
test/voice.js

Update examples so that users are not mistaken for old versions of the library.
Extended PR of #1382

Update voice and shard examples

---

src/structures/Guild.js
src/structures/interfaces/TextBasedChannel.js
src/structures/shared/Search.js

just some stuff that bothered me

sanity changes to search

---

src/util/Constants.js

splashes can be like the other ones

clean up cdn resources

---

src/client/rest/DiscordAPIError.js

update docs for discord api error

---

src/client/Client.js

Prevent accidental display of the client token.

make token not enumerable

---

src/structures/GuildAuditLogs.js

fix up toLowerCase errors

---

.tern-project

update tern file to actually work

---

.github/ISSUE_TEMPLATE.md

add user account checkbox

---

src/client/Client.js
src/client/WebhookClient.js
src/client/rest/APIRouter.js
src/client/rest/DiscordAPIError.js
src/client/rest/RESTManager.js
src/client/rest/RequestHandlers/Burst.js
src/client/rest/RequestHandlers/Sequential.js
src/structures/Channel.js
src/structures/ClientUser.js
src/structures/ClientUserSettings.js
src/structures/Emoji.js
src/structures/GroupDMChannel.js
src/structures/Guild.js
src/structures/GuildChannel.js
src/structures/GuildMember.js
src/structures/Invite.js
src/structures/Message.js
src/structures/MessageReaction.js
src/structures/PermissionOverwrites.js
src/structures/Role.js
src/structures/TextChannel.js
src/structures/User.js
src/structures/Webhook.js
src/structures/interfaces/TextBasedChannel.js
src/structures/shared/SendMessage.js

REST speed upgrades

---

src/structures/Emoji.js
src/structures/GuildChannel.js
src/structures/OAuth2Application.js

Fixes several api router invalid syntaxes.

rest api route fixes

---

src/client/voice/VoiceConnection.js
src/errors/Messages.js

Cleaning up Gus's mess... as usual 😅 

Add VoiceConnection errors

---

src/util/Util.js

make sure something isn't undefined
note: things can still be null

undefined check to merge default

---

src/util/Util.js

fix this again

---

src/structures/Message.js

allow content in edit options like in message send options

---

src/structures/GuildChannel.js

add new unique property to invites

---

src/structures/GuildAuditLogs.js

use webhooks cache in guild audit log

---

src/client/rest/APIRequest.js
src/structures/Invite.js
src/util/Constants.js

update http options to fit discord spec

---

src/index.js
src/structures/interfaces/TextBasedChannel.js

important build stuff

---

src/util/Util.js

Did you change the ConstantsHttp? This wasn't working until I replaced it with this.

Fix Recommended Shards

---

src/structures/TextChannel.js

discord moved nsfw channels from having a prefix to being an actual prop in the api

move nsfw to the new prop

---

src/structures/Guild.js

if no query or limit is provided it will resolve with this.members instead of just collected members

update fetch member to work in a more consistent way

---

src/client/rest/handlers/RequestHandler.js

it was recommended we retry on 500

retry on 500

---

src/structures/GuildAuditLogs.js

fix guild audit log fetching of stuff

---

docs/topics/voice.md

in the docs under topics/voice there is said that you need to give .playFile() an absolut path what is wrong since my own bot use dynamic paths with .playFile() and it works fine so i added a dynamic path example aswell as update the ReadableStream example

docs update to topics/voice playFile example

---

src/client/websocket/WebSocketConnection.js

fix unpack weird issues

---

src/client/websocket/packets/handlers/GuildMembersChunk.js

Fixes #1733 as guildMembersChunk doesn't return a collection until v12

Fix guildMembersChunk documents for v11.1-dev

---

src/structures/Message.js
src/structures/MessageMentions.js

check if mentions includes a user without being weird about it

add MessageMentions#has, remove old method

---

src/structures/ClientUser.js

guilds might not be created yet (race condition)

fix race condition

---

src/structures/ClientUser.js
src/structures/ClientUserGuildSettings.js

fix more race conditions

---

src/structures/Guild.js

default channel doesn't exist anymore

---

.npmrc

kill this thing once and for all

---

src/util/Constants.js

we don't need them anymore, keeping up to date

where we're going we don't need referrers

---

src/client/voice/VoiceConnection.js
src/structures/ClientUser.js
src/structures/ClientUserGuildSettings.js
src/structures/GroupDMChannel.js
src/structures/Guild.js
src/structures/GuildChannel.js
src/structures/MessageMentions.js
src/structures/Role.js
src/structures/User.js
src/structures/UserProfile.js
src/structures/Webhook.js
src/structures/interfaces/Collector.js
src/util/Constants.js

- Fixed a common copy paste fail `the the <thing>` in various places
- Apparently I can't type Resolvable correctly,
Fixed that wherever applicable
- Documented `GroupDMChannel#nicks` so that it will be displayed on the docs
- `GroupDMChannel#icon` is nullable
- Removed empty `InviteOptions` typdef, as its properties are now documented in `GuildChannel#createInvite`
- `MessageMentions#channels` is no longer nullable
- `RoleData#permissions` takes a `PermissionResolvable` or an array of them
- `Webhook#avatar` is nullable
- Added `HTTPOptions` typedef and added it to `ClientOptions` typedef
- `ClientUserChannelOverride#muted` is for a channel and not a guild directly

Added and fixed a bunch of docs stuff

---

src/client/rest/handlers/RequestHandler.js

http is a strange and wonderful place

update retry case for 5xx

---

src/client/ClientDataManager.js
src/structures/Channel.js
src/structures/DMChannel.js
src/structures/GroupDMChannel.js
src/structures/Guild.js
src/structures/VoiceChannel.js
src/util/Constants.js

channel stuff

---

src/structures/ClientApplication.js

add cover image

---

src/util/Constants.js

update image sizes, adding some more

---

src/client/rest/RESTManager.js
src/client/websocket/WebSocketConnection.js

#1803 is bad and wrong and this is good and right

proper fix for #1685

---

src/client/websocket/WebSocketConnection.js

fix ws ratelimiting

---

src/structures/MessageMentions.js

This will make it easier to extract the ID from user and role mentions.  It will also make them consistent with channel mentions.

add capture groups to MessageMentions and validate snowflake ranges

---

src/client/ClientDataResolver.js
src/structures/Attachment.js
src/structures/Webhook.js
src/structures/interfaces/TextBasedChannel.js

Fixed an issue with setting a name when only a URL is provided, such as a case when needing to send an avatarURL, where providing a name is required. Also updated docs to reflect the original Attachment PR #1731.

update attachment & docs

---

README.md

link people to big readme in docs

update webpack readme

---

src/client/Client.js
src/client/ClientDataResolver.js
src/client/voice/VoiceConnection.js
src/structures/ClientApplication.js
src/structures/ClientUserChannelOverride.js
src/structures/ClientUserGuildSettings.js
src/structures/ClientUserSettings.js
src/structures/Guild.js
src/structures/GuildChannel.js
src/structures/Role.js
src/structures/Webhook.js

Fixes some documentation "issues"
Check the commit for everything that was fixed

Fix documentations that were incorrect or missing

---

src/structures/interfaces/TextBasedChannel.js

I missed this in my Doc PR.. This *should* be the last thing.

MessageOptions can take content

---

src/structures/Guild.js

Fixes #1866
Added an if to prevent the attempt to iterate over anything falsy.

fix(Guild): passing the constructor partial data from an invite no longer errors

---

src/structures/User.js

now all numbers have the same size 

fixed a little typo in docs of <User>.displayAvatarURL()

---

src/structures/GuildChannel.js

(backport from permissions cleanup)

Fix deny administrator edge case bug

---

src/structures/GuildChannel.js

Reverts hydrabolt/discord.js#1878

Revert "Fix deny administrator edge case bug"

---

src/structures/MessageReaction.js

Allow to fetch more than 100 users per reaction, by passing the last user's id from the previously received collection (or users collection)  to `MessageRection#fetchUser`.

feature(MessageReaction): add after option when fetching users who reacted with an emoji

---

src/WebSocket.js
src/client/ClientManager.js
src/client/voice/VoiceWebSocket.js
src/client/websocket/WebSocketConnection.js
src/index.js

move detection of correct websocket lib and erlpack to central module

websocket centralization

---

src/stores/MessageStore.js
src/structures/Emoji.js
src/structures/Role.js

This will throw a DiscordjsError one places where they were expected but not present duo a missing require of them.

fix(Errors): throw DiscordjsErrors where one would expect them

---

src/structures/Guild.js

- ``data`` variable renamed to ``updatedChannels`` (consistency with ``Guild#setChannelPosition``)
- map the channelPositions param and assign to updatedChannels that way (consistency with ``Guild#setChannelPosition``)
- make the method actually use the updatedChannels Array that gets created instead of passing the channelPositions param directly
- make patch request to API send the proper data (only the ``updatedChannels``, not a ``data`` object containing the guild ID and the updated channels)
- Fix example to use the proper method name
- Move the ``setChannelPosition`` method above the ``setChannelPositions`` method for organization purposes

fix(Guild): Fix setChannelPositions method

---

src/client/actions/ChannelDelete.js
src/client/websocket/packets/handlers/ChannelCreate.js
src/client/websocket/packets/handlers/ChannelPinsUpdate.js
src/client/websocket/packets/handlers/ChannelUpdate.js
src/structures/Guild.js
src/structures/GuildAuditLogs.js
src/util/Collection.js

It wasn't really obvious *which* types of channels were sent along with each channel event, so I clarified that here.
Also added some typedefs regarding Audit Logs.
Also a small error on how Collection#sort was documented.

docs: improve documentation

---

src/client/actions/MessageCreate.js
src/structures/Message.js

fix cache, save cpu cycles
closes #1906 

update webhook cache and message cache stuff

---

src/stores/ChannelStore.js
src/stores/GuildChannelStore.js
src/stores/GuildStore.js
src/stores/MessageStore.js
src/stores/ReactionStore.js
src/stores/RoleStore.js

Fix DataStore cleanup docs

---

src/structures/Message.js

Fix GuildMember being undefined

Fix GuildMember being undefined

---

src/structures/CategoryChannel.js
src/structures/Guild.js
src/structures/GuildChannel.js

Just some doc fixes
Gonna check everything now..

Fix some documentation about the category channels

---

src/stores/MessageStore.js
src/stores/PresenceStore.js

Should probably hold this open while I review other docs when I get home to make sure I didn't make any more mistakes in the documentation.

More docs stragglers I didn't see (DataStore cleanup)

---

src/client/actions/GuildChannelsPositionUpdate.js
src/client/actions/GuildRolesPositionUpdate.js
src/structures/Guild.js
src/structures/GuildChannel.js
src/structures/Role.js
src/util/Util.js

wow code dupe is down things are fantastic
closes #1918 
closes #1909 

clean up positions

---

src/util/Util.js

fix a thing

---

src/structures/Guild.js

fix sorting things

---

src/util/Permissions.js

Permissions add/remove was not resolving correctly. This should fix it.

fix permissions not resolving correctly

---

src/util/DataResolver.js

this.constructor is undefined in a static method

Fixes #1929

---

src/structures/ClientApplication.js
src/structures/GroupDMChannel.js
src/structures/Guild.js

all Image getter size options should now have the same size in the docs and added a example to guild.setSystemChannel()

fixed small typo's in the Docs and added an example to <Guild>.setSystemChannel()

---

package.json

discord changed their GitHub org name. this updates the GitHub erlpack dep we have from them

update dep for org name change

---

package.json
src/rest/APIRequest.js
test/webpack.html

This makes requests much faster, as the connection is kept open.

add persistent agent support to the request generator

---

src/structures/Guild.js

Added support for the `nsfw`, `bitrate`, `userLimit`, `parent` properties when creating a new channel.
Also fixed an error when omitting `allow` or `deny` in the `ChannelCreationOverwrites`.

fix/feature(createChannel): add support for more properties and fix overwrites optionals

---

README.md
docs/general/welcome.md

Discord moved from `hammerandchisel` to `discordapp` on Github, and erlpack moved too. Time to adapt to the change

docs: Change repo for erlpack

---

travis/deploy.sh

run builds without committing to find potential errors

run builds for prs without commiting

---

src/client/voice/VoiceConnection.js

fix(setSpeaking) Fix #2005

---

src/util/Util.js

Fixes an issue where setPosition wouldn't update the rawPositions (the actions for ChannelPositions and RolePositions were getting triggered with an empty buffer).
*Note: This still doesn't fix the edit problem for channels, I will look into that*

fix(setPosition): rawPosition never getting updated when setPosition was called

---

src/client/Client.js

fix Client#login from other invalid things

---

src/structures/Guild.js

add Guild#verified

---

src/client/voice/player/AudioPlayer.js

This PR is patch for #2034.
Cancelling: https://github.com/hydrabolt/discord.js/pull/1745/files#diff-31d1bb7c08f2176ba026497c2e8d9b3fR81

Fixes #2034

---

package.json
travis/deploy.sh
webpack.config.js

clean up webpack/deploy stuff

---

src/rest/handlers/RequestHandler.js
src/rest/handlers/burst.js
src/rest/handlers/sequential.js
src/util/Constants.js
test/tester1000.js

useful event for when you get ratelimited

add ratelimited event

---

src/util/Constants.js

fix bug avatar url generation

---

src/rest/RESTManager.js
src/rest/handlers/RequestHandler.js

moves diff stuff to rest manager and averages for a more useful number that can be used

move time diff stuff to rest manager and average

---

src/structures/shared/Search.js

Changes docs in MessageSearchOptions. 

Change recent to timestamp because DiscordAPIError

---

src/client/websocket/WebSocketConnection.js

fix raw event

---

src/client/voice/VoiceBroadcast.js
src/structures/Guild.js
src/structures/Presence.js

Added missing semicolon in example code.

Typos in docs

---

src/structures/Message.js
src/structures/Webhook.js
src/structures/interfaces/TextBasedChannel.js
src/structures/shared/CreateMessage.js
src/structures/shared/SendMessage.js
src/structures/shared/index.js

we had so much code dupe between webhook, message, and itextchannel, now it is all in once place.

standardize message object creation

---

src/structures/Guild.js

Fixes #2089 
As in the issue specified: The user wasn't resolved correctly.
This will take care of that.

fix(Guild): correctly resolve user in Guild#addMember

---

src/structures/GuildChannel.js
src/structures/VoiceChannel.js

it should stay consistent with other methods tbh 🤔 

enhanced setUserLimit to reset when passing null to stay consistent with other methods

---

src/index.js
src/stores/MessageReactionUserStore.js
src/stores/ReactionUserStore.js
src/structures/MessageReaction.js

since we're doing OOP stuff MessageReaction.fetchUsers() wasn't really consistent, so I made a store for it, so we can do MessageReaction.users.fetch() now.

 refactor(MessageReaction): ReactionUserStore

---

src/structures/Guild.js

Guild#features was abstract/not very obvious so I added typings for it, which I feel is necessary because it can only be a specific subset of strings in an array.

docs: add Guild#features type

---

src/structures/GuildMember.js

fix(GuildMember): permissions.missing is not a function

---

src/client/ClientDataManager.js
src/client/rest/RESTMethods.js
src/structures/CategoryChannel.js
src/structures/Guild.js
src/structures/GuildChannel.js
src/structures/OAuth2Application.js
src/util/Constants.js

Self explanatory- it backports the `ChannelCategory` structure and the ability to create these channels and also set and get `GuildChannel`'s parents (which are categories).

feature(CategoryChannel): backport

---

src/structures/ClientApplication.js

fix client app asset stuff

---

src/client/ClientDataManager.js

DMChannels were getting their channels reset in the collection without properly checking if it already exists - this just fixes that check.

fix(DMChannel): messages not being cached

---

src/structures/GuildAuditLogs.js

Backported the typings and correct webhook references (for deleted webhooks) from master branch.

fix(GuildAuditLogs): backport

---

package.json

Backport: erlpack dep fix [11.3-dev]

---

package.json

fix(package.json): update version

---

src/structures/Emoji.js
src/util/Constants.js
src/util/Util.js

emojis can be animated now and my mom thought you might like to know so uhhhh... here you go

animated emojis

---

docs/general/welcome.md

...to show that it's docs for version 11.3

Update 11.3 Readme

---

src/structures/Guild.js

Changes docs for createChannel to reflect that Type is now part of the options object, so the example should reflect that.
- [x ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

updating channelCreate example to reflect recent changes

---

src/structures/Channel.js
src/structures/GuildChannel.js

fix location of toString for channels

---

src/structures/interfaces/TextBasedChannel.js

backport(Channel#startTyping): returns Promise

---

src/stores/GuildMemberStore.js
src/structures/Channel.js
src/structures/Guild.js
src/structures/GuildChannel.js
src/structures/GuildMember.js
src/structures/Message.js
src/structures/interfaces/TextBasedChannel.js

Similar to the doc examples improvements from 11.3-dev branch. Adds some examples and formats them nicer with production in mind.

docs: improve examples (master branch)

---

src/structures/Channel.js
src/structures/Guild.js
src/structures/GuildChannel.js
src/structures/GuildMember.js
src/structures/Message.js
src/structures/interfaces/TextBasedChannel.js

Adds some examples, not much else to say. Open for more suggestions.

docs: improve examples

---

src/structures/GuildChannel.js

docs: fix guildChannel#toString() example

---

src/util/Util.js

Just some refactoring for the Util methods.
(Are you guys sure you don't want to use path.basename 👀? )

Minor refactor to Util methods

---

src/util/Constants.js

`?size=2048` made gifs not animated. This should fix that.

fix(avatarURL): gifs not being animated

---

src/structures/Channel.js

Fixes the Channel.delete() example docs.

Fix Channel.delete() example

---

src/structures/interfaces/TextBasedChannel.js

The method keeps the changes introduced in Master branch and stops after one rejection and doesn't return a Promise. Also rejects silently since it can't be caught by the end developer.

 fix(Channel#startTyping): less breaking

---

src/util/Util.js

Fix #2217, wrong regex. Didn't allow normal emojis to go through.

fix(Message#addReaction): incorrect regex

---

src/structures/MessageEmbed.js

There is an issue where these two values are left undefined

Fix MessageEmbed Height & Width

---

src/structures/GuildChannel.js

Addresses #2255 missing options in GuildChannel.clone()

Add parent, nsfw, bitrate, and userLimit options to GuildChannel.clone()

---

src/structures/ClientUser.js

fixes #2103 according to how crawl says it should be fixed in #2104

Address missing application docs in setPresence

---

src/util/Collection.js

To be compliant with Array.find() / findIndex() (instead of null when no match is found). Fixes #2222

Return undefined from Collection.find() / findKey()

---

src/structures/GuildMember.js

Noticed some nearly completely identical code in both getters, so I made a more general getter to reduce code duplication, which can also help for more general purposes such as checking if a member can have his nickname changed by the client.

refactor(GuildMember#manageable): refactored kickable and bannable

---

src/structures/GuildChannel.js
src/structures/GuildMember.js
src/structures/Role.js

Updated version of #1421 using the latest datastore resolvers.

GuildChannel.permissionsFor(role)

---

src/client/voice/VoiceBroadcast.js

docs: fix VoiceBroadcast documentation

---

src/client/Client.js

It's not necessarily confusing looking at the value through eval or something similar, but just in case for those who can't figure it out, it's better off being stated.

Specify "in milliseconds"

---

src/structures/Role.js

Changed a while loop to padStart in the Role class for consistency with the rest of the library.

Consistency In the Role Padding Method

---

src/structures/Presence.js
src/util/Constants.js

spotify stuff

---

src/structures/Message.js
src/structures/Presence.js

Add TypeDef for MessageActivity

---

src/util/Permissions.js

Minor addition to enhance the permissions class' usability with primitive calculations.

add valueOf method to permissions

---

src/structures/DMChannel.js
src/structures/GroupDMChannel.js
src/structures/TextChannel.js

This PR ensures that the message store of text channels are actually documented (for some reason they aren't, even though the text channels implement TextBasedChannel)

docs: Document the MessageStore for all TextBasedChannels

---

src/sharding/ShardClientUtil.js

docs: Fix missing parameter type/description from #2193

---

src/structures/GuildMember.js

This way is cleaner and better, imo
Just added object destructuring, also not breaking change but I think that's the only semvar it fits in.

Object Destructuring for Presence

---

src/stores/GuildStore.js

https://discordapp.com/developers/docs/resources/guild#create-guild

[docs] Make a correction to GuildStore#create()

---

src/structures/Guild.js

Adds the mfaLevel property to Guild.

[feature] add Guild#mfaLevel

---

src/client/voice/dispatcher/StreamDispatcher.js

If the player is a BroadcastAudioPlayer it have no voiceConnection

Check if player have a voiceConnection

---

src/stores/GuildEmojiStore.js
src/stores/GuildMemberStore.js
src/stores/MessageStore.js
src/stores/PresenceStore.js
src/structures/Message.js
src/structures/Presence.js
src/structures/interfaces/Collector.js

This fixes a number of spelling mistakes in Structures and Stores.

Fix a number of spelling mistakes

---

src/client/websocket/WebSocketManager.js

Fixes a docs typo in the Internal Sharding branch

[internal-sharding] Fix a docs typo

---

src/client/websocket/handlers/READY.js

This branch broke the custom user inheritance from custom structures. (caching the ClientUser class before the structure could be inherited from a custom User class) This fixes that bug.

[internal-sharding] Fix custom ClientUser

---

src/util/Util.js

Fixes a TypeError in the mixin function.

Fix TypeError in mixin function

---

src/structures/GuildMember.js

Fixes GuildMember#toJSON not having an array of roles

fix: GuildMember#toJSON not having roles

---

src/util/Collection.js

Fixes some docs typos in the Collection class.

docs: Fix typos in Collection class

---

src/client/rest/DiscordAPIError.js
src/client/rest/RequestHandlers/Burst.js
src/client/rest/RequestHandlers/Sequential.js

Commits:
- [`62605c4`](https://github.com/discordjs/discord.js/commit/62605c4470bc78b4f302b7d40f2492f066b3e5b8)
Summary:
- Added `DiscordAPIError#method` for more descriptive API errors.

feat: backport DiscordAPIError#method

---

src/client/Client.js
src/util/Collection.js

Adds sweep method to Collections with the same interface as the filter method, but removes items from the collection and returns the number of "swept" items instead.

feature: add Collection#sweep()

---

src/util/Util.js

Makes the codebase/docs 100% US English.

docs(Util): fix spelling of 'behavior'

---

src/rest/handlers/RequestHandler.js

This will make discord.js no longer retry indefinitely on 5xx.
Reason for this is deadlocking request handlers for channels so no messages can be send here until the bot is restarted.
This is caused by a request which always gets a 5xx response due to an error on discord's end.
Example to deadlock a request handler for a channel (as of now):
```js
channel.send({ embed: { fields: [{}, {}, {}] } });
```
Might be worth to take a look at #1682 and maybe reject with a `DiscordAPIError` instead.
> Note: This maybe is `semver: major` since we would be rejecting on 5xx as well, I am not sure there.

fix(RequestHandler): only retry once on 5xx

---

src/rest/RESTManager.js

Reworks RESTManager#handlers to use a collection for lib consistency and sweep performance. Removes RESTManager#rateLimitedEndpoints as it wasn't being used by the library, only initialized as `{}`. (per hydra to just delete, instead of making it a getter)

refactor: RESTManager#handlers to use Collection

---

src/structures/DMChannel.js
src/structures/GroupDMChannel.js
src/structures/TextChannel.js

Pretty much what the title says.

Adds JSDocs for TextChannel.lastMessageID

---

src/rest/handlers/RequestHandler.js

fix response parsing

---

src/sharding/Shard.js
src/sharding/ShardingManager.js

Adds `execArgv` to the `ShardingManager`, since we don't have that already. Feel free to suggest documentation improvements, since they're somewhat lackluster and I'm not sure how to improve on the wording myself.
closes #1714

feat(ShardingManager): add execArgv option

---

src/structures/ClientApplication.js
src/structures/GroupDMChannel.js
src/structures/Guild.js
src/structures/User.js
src/util/Constants.js

In this pullrequest we document the sizes `16`, `32`, `64`, as these sizes can also be used and it would be a shame to not documente these!

documented sizes 16, 32, 64

---

src/structures/Message.js

Not much to say- adds the brand spanking new feature of jumping to messages.

feat(Message): add url getter

---

docs/general/welcome.md

This is a pretty minor change, but hard-coding the domain here breaks CSP (discordjs/website#19) when testing production builds of the site.

remove hard-coded domain in welcome logo

---

src/structures/GuildEmoji.js

This PR fixes some issues that showed up in GuildEmoji, and closes #2671 

fix: Wrong _patch call from GuildEmoji#edit and other issues

---

src/util/Collection.js

Reverts discordjs/discord.js#2709 until we can think of a better way of doing this

Revert "fix(Collection): use `new this.constructor` instead of `new Collection`"

---

src/structures/shared/CreateMessage.js

Made it setting the `code` option when sending text-messages work with the `reply` option.
Also fixed a bug where if `split` was set to `true`, which is supported according to the docs, and `reply` was set, the mention prepend property was set on the boolean value rather than creating an empty object and adding that. Also made prepend/append carry over into the codeblock injector, so mentions carries over into split messages.
This resolves #2691

Fixed splitting messages with codeblocks and replies

---

src/structures/VoiceState.js

More consistency with getters.

Consistency with Getters.

---

src/structures/User.js

Corrects @amishshah 's discord tag in docs

docs: Important typo fix /s

---

src/client/websocket/packets/handlers/PresenceUpdate.js
src/structures/GuildMember.js
src/structures/Presence.js

~~Should~~ fixes #2749
Reduces a bit of code dupe
Fixes some related docs (nullable getters)
Fixes some related repo conventions (getters return null not undefined)

Presence change fixes and cleanup

---

src/errors/Messages.js
src/structures/Guild.js

Added the fetchVanityURL method to the guild structure
- implements GET/guilds/{guild.id}/vanity-url endpoint to get the vanity code of a partnered discord server
Added VANITY_URL error message

Add guild.fetchVanityURL()

---

src/structures/User.js

This PR replaces the double iteration in User#dmChannel with one find check
**Status**

perf: Remove double iteration

---

src/structures/Guild.js
typings/index.d.ts

This PR adds support for fetching and modifying the guild embed. API Docs: https://discordapp.com/developers/docs/resources/guild#get-guild-embed

feat: Guild embed support

---

src/structures/Emoji.js

This PR fixes a typo (moej -> emoji)
**Status**

typo(Emoji): Fixed typo in Emoji#deletable

---

src/client/rest/RESTMethods.js
src/structures/Guild.js
typings/index.d.ts

Backports https://github.com/discordjs/discord.js/pull/2766 to 11.4-dev.
**Status**

backport: Guild#{fetchEmbed,setEmbed}

---

README.md
docs/general/welcome.md
package.json
src/client/voice/VoiceWebSocket.js
src/client/websocket/WebSocketConnection.js

build(peer-deps): use uws fork backport

---

typings/index.d.ts

message was missing url, messageAttachment was missing size
**Status**

Message and MessageAttachment typing update

---

src/client/websocket/packets/handlers/ChannelPinsUpdate.js
src/structures/DMChannel.js
src/structures/GroupDMChannel.js
src/structures/TextChannel.js
src/structures/interfaces/TextBasedChannel.js
typings/index.d.ts

Pretty self-explanatory, this PR adds two properties to TextBasedChannels.
**Status**

feat(TextBasedChannel): add lastPinTimestamp and lastPinAt

---

typings/index.d.ts

This PR will fix compilation using tsc with the strict option enabled.
Fixes #2842 
**Status**

fix(typings): fix compilation with 'strict' enabled

---

src/util/Constants.js
src/util/Util.js

This PR adds the colour white to Discord.js. It makes it easier to make white embeds, etc.
**Status**

Add white to colours

---

src/client/Client.js
src/client/websocket/WebSocketManager.js
src/client/websocket/WebSocketShard.js

Adds support for the new session limit responses. I'm not confident on how well this was implemented to please make suggestions on how to improve it, if any.
Typings will be done soon, preferably after a review (also requires another rebase).
**Status**

feat: handle new session rate limits

---

src/client/rest/RESTMethods.js
src/structures/Guild.js
src/util/Constants.js
typings/index.d.ts

This PR backports #2732 adding the `Guild#fetchVanityCode` method.
**Status**

backport(Guild): add fetchVanityCode

---

src/errors/Messages.js
src/structures/MessageEmbed.js

Provides a way to replace, delete, and insert fields into existing embeds. (Such as reusing a fetched mod-log MessageEmbed, to just update one existing field. Or to insert fields into an embed template.)
**Status**

feat(MessageEmbed): MessageEmbed#spliceField()

---

src/structures/ClientUser.js

master switched to presence.activity from presence.game, the example currently does not represent that change.
**Status**

docs: fix example for setActivity

---

package.json
typings/index.d.ts

Update Typings to reflect current ClientOptions & fix DOM types from @types/ws in the Internal Sharding branch
**Status**

fix(Typings) Fix 2 issues with Typings

---

src/client/Client.js
src/client/websocket/WebSocketShard.js
src/sharding/Shard.js
src/util/Constants.js
typings/index.d.ts

**Changelog:**
Renamed `actualShardCount` to `totalShardCount`
Renamed ShardingManager env variables `SHARD_ID` and `SHARD_COUNT` to `SHARDS` and `TOTAL_SHARD_COUNT` to match Internal Sharding naming
Remove unused `internalSharding` ClientOption
Use constant values from `Constants.js` to set default values for `shardCount` & `totalShardCount`
~~Dynamicly set `shardCount` if `shards` is an array of IDs~~ not needed
Use `totalShardCount` instead `shardCount` as value for the `IDENTIFY` OP (This allows to spawn multiple IS client with the ShardingManager to allow hybrid sharding)
Refactored the documentation of `totalShardCount` and `shardCount` to be more specific about what each property represent
**Status** …

fix(Sharding) fixes several things in Internal Sharding

---

src/client/actions/GuildIntegrationsUpdate.js
src/client/actions/VoiceStateUpdate.js
src/client/actions/WebhooksUpdate.js
src/client/websocket/handlers/VOICE_STATE_UPDATE.js

fixes inconsistencies which let the client crash on different events because of Reference Errors
**Status**

Fix(Sharding) fix different actions not expecting the correct data

---

src/client/Client.js

if you dont have the env variables set (using ShardingManager) and set the totalShardCount (so not only using Inernal Sharding) the last else override the totalShardCount to shardCount whats wrong if you want to have more then only one Client instance.
**Status**

Fix(Sharding) Fix edge case in dynamic setting of totalShardCount if not provided

---

src/sharding/ShardClientUtil.js

fixes #2945 and also corrects ShardClientUtil#id typedef with Internal Sharding Update.
**Status**

[Fix] Fix ShardClientUtil#count using wrong shardCount

---

src/client/Client.js

This is already fixed in master, resolves #3022
**Status**

fix missing parenthesis in fetchInvite docs

---

src/client/Client.js

add missing jsdoc tag & closing parenthesis

---

src/stores/ChannelStore.js
src/stores/RoleStore.js
typings/index.d.ts

Adds a `fetch()` method to RoleStore and ChannelStore for consistency with MessageStore, GuildMemberStore, ReactionUserStore, UserStore...
**Status**

feat(RoleStore, ChannelStore): `fetch()` method

---

.travis.yml

Updates CI to use Node.js 10 and 11 (Node.js 9 reached End-Of-Life [8 months ago](https://github.com/nodejs/Release#end-of-life-releases)). And run the deploy script with Node.js 10 (current LTS).
**Status**

ci: Test in Node.js 10 and 11, deploy with Node.js 10

---

src/client/ClientDataResolver.js
src/util/Constants.js
typings/index.d.ts

This PR backports #2853 adding `WHITE` as a color resolvable.
**Status**

feat(Util): add WHITE as color resolvable

---

README.md

Better wording

---

typings/index.d.ts

Implements typings to #3070 
**Status**

typings: Updated typings for the partials branch 

---

src/errors/Messages.js

Removed some unused keys from the error messages constants.
**Status**

cleanup: Error messages cleanup

---

src/structures/Presence.js
typings/index.d.ts

This PR backports #2997 to the 11.4-dev branch adding `Presence#clientStatus`.
**Status**

feat(Presence): add clientStatus

---

src/client/rest/RESTMethods.js

This PR backports #2965 adding support to provide a position to `Guild#createChannel`.
**Status**

feat(Guild): add position to createChannel's implementation

---

src/client/voice/VoiceBroadcast.js

This PR solves a VoiceBroadcast TypeError, since it tried emitting on an undefined property instead of itself
**Status**

src: Fix VoiceBroadcast TypeError

---

src/client/voice/VoiceBroadcast.js

This PR fixes broadcasts not actually playing music by... actually making sure the dispatcher is added to the broadcasts list of dispatchers... Like it should be...
@SpaceEEC ❤️ 
**Status**

src: Make broadcasts work again

---

src/rest/RequestHandler.js

Removed the additional "s" to "requessts"
**Status**

Fixed a comment typo

---

src/structures/Role.js

Fix Role#setPosition reason type

---

src/structures/ClientPresence.js
src/structures/DMChannel.js
src/structures/Guild.js
src/structures/GuildChannel.js
src/structures/GuildEmoji.js
src/structures/GuildMember.js
src/structures/Message.js
src/structures/MessageReaction.js
src/structures/Presence.js
src/structures/Role.js
src/structures/TextChannel.js
src/structures/User.js
src/structures/VoiceState.js
typings/index.d.ts

This PR adds the constructors of extendible structures to the documentation so developers know what and how many parameters to expect when extending.
**Status**

docs: document constructors of extendible structures

---

test/webhooktest.js

Just extends the original plain message tests but for webhooks as well. This is definitely needed because we frequently run into issues that come across webhooks but nobody uses them and consequently, fails to remember to test them. Hopefully this makes things easier.
**Status**

test: add WebhookClient testing file

---

src/util/Collection.js

backports https://github.com/discordjs/discord.js/commit/7457985e60e4f92b3c833491636f37e2fdd11081
**Status**

docs(Collection): fix findKey jsdoc

---

src/client/websocket/WebSocketShard.js

docs: Imagine having an optional nullable param

---

typings/index.d.ts

fix(typings): remove duplicated Guild#defaultRole

---

docs/general/faq.md

docs(faq): bump to node 10.0.0

---

src/stores/GuildMemberRoleStore.js
src/structures/GuildMember.js

src: Don't use the GuildMemberRoleStore to patch the GuildMember _roles

---

src/client/websocket/WebSocketShard.js

src: Fix type error in WebSocketShard#onError

---

src/WebSocket.js
src/client/Client.js
src/client/websocket/WebSocketManager.js
src/stores/GuildEmojiRoleStore.js
src/stores/GuildMemberRoleStore.js
src/structures/APIMessage.js
src/structures/Webhook.js
src/structures/interfaces/TextBasedChannel.js
src/util/BitField.js
src/util/DataResolver.js
src/util/Util.js

This PR replaces all `instanceof Array` checks with `Array.isArray` and `instanceof Buffer` with `Buffer.isBuffer`. There really isn't much to say...
**Status**

src: Replace instanceof Array checks with Array.isArray and instanceof Buffer with Buffer.isBuffer

---

src/structures/GuildChannel.js
src/structures/TextChannel.js

Specify setRateLimitPerUser number is in seconds

---

src/structures/Guild.js

- Fixed incorrect docs in Guild.js
**Status**

Fix incorrect docs in Guild.js

---

src/WebSocket.js
src/client/websocket/WebSocketShard.js

fix websocket unpacking

---

src/util/Permissions.js
typings/index.d.ts

This updates Permissions to include the new Stream permission that is currently going out over the WebSocket. I can only assume this is used for screen share, but that's irrelevant.
**Status**

Add Stream permission

---

src/client/websocket/WebSocketShard.js
typings/index.d.ts

This PR removes the trace packet as per https://github.com/discordapp/discord-api-docs/pull/967.
> Later, at some point in the future, the `_trace` field will be dropped.
\- zorkian
**Status**

Removes the trace packet

---

src/structures/Presence.js

Backports Presence#clientStatus documentation from master.
**Status**

fix(docs): backport documentation for Presence

---

src/structures/Guild.js

The addition of missing guild features that were added in the Nitro boost update, such as ANIMATED_ICON
**Status**

Added missing features

---

docs/general/welcome.md

Adds zucc as an optional dep on the docsite welcome...
**Status**

docs: Add zucc to docsite welcome page

---

src/structures/Guild.js
typings/index.d.ts

Includes the addition of the `DISCOVERABLE` and `FEATURABLE` features, which I wasn't aware of when I submitted #3336
**Status**

Add more missing features

---

typings/index.d.ts

feat: overload for split always returning an array

---

src/stores/GuildMemberStore.js

src: Turn uncatchable error in MemberStore#unban into a catch-able one

---

src/stores/GuildMemberRoleStore.js

fix defaultRole change

---

docs/topics/voice.md

client.createVoiceBroadcast() -> client.voice.createBroadcast()
**Status**

fix voice broadcast example code

---

src/structures/GuildAuditLogs.js

Should be the fix required for https://github.com/discordjs/discord.js/issues/3372
**Status**

src: Backport an audit log fix from master to d.js 11.5

---

typings/index.d.ts

corrected shardResumed & removed old resumed event
**Status**

fix(typings): Update Client event typings

---

src/structures/Message.js

docs: Document Message#author as nullable

---

docs/topics/partials.md
src/client/actions/Action.js
src/client/actions/MessageReactionAdd.js
src/stores/ReactionStore.js
src/structures/DMChannel.js
src/structures/MessageReaction.js
src/structures/User.js
src/util/Constants.js
typings/index.d.ts

Reverts discordjs/discord.js#3261

revert: "feat(Partials): add DMChannel/MessageReaction#fetch() and PartialTypes.REACTION"

---

typings/index.d.ts

Merge only after <https://github.com/discordjs/collection/pull/11>.
**Status**

fix: typings for this-polymorphism of collections

---

typings/index.d.ts

I mean, I don't wanna be like that snake, but I really can't write an in-depth changelog for a one line typings fix
**Status**

typings: Add missing rateLimitPerUser property

---

src/structures/Guild.js
typings/index.d.ts

https://github.com/discordapp/discord-api-docs/commit/09136eee7ccc4b91bbb8c89fb3f41527c557ca3d
**Status**

docs/typings: Rename LURKABLE to PUBLIC and update GuildFeatures type

---

src/util/BitField.js

#3490 - Checked to see if a permission actually exists if the supplied was a string.
**Status**

fix(BitField): throw when resolving invalid string constant

---

typings/index.d.ts

typings: mark GuildMember#nickname as nullable

---

typings/index.d.ts

backport(typings): mark GuildMember#nickname as nullable

---

docs/topics/partials.md

fix(docslink): partialtypes

---

src/structures/GuildChannel.js
typings/index.d.ts

* document ChannelData#reason
* update respective typings
* should take care of #3548
property is not currently documented
**Status**
(does include typing addition)

fix: document ChannelData#reason

---

src/client/voice/VoiceConnection.js
src/util/Constants.js

This PR documents what the number of `VoiceConnection#status` actually is, as well as what the number means.
**Status**

docs(VoiceStatus): document name -> value, link in VoiceConnection#status

---

src/client/websocket/packets/handlers/VoiceStateUpdate.js
src/structures/Guild.js
src/structures/GuildMember.js
typings/index.d.ts

This PR backports #3521 adding a `selfStream` property to `GuildMember`.
**Status**

feat(GuildMember): add selfStream

---

src/client/voice/VoiceConnection.js

Fix(VoiceConnection): clear the timeouts properly

---

README.md

Easy links in readme to make it easy to read it quickly.
**Status**

docs(readme): table of contents

---

src/structures/Channel.js
src/structures/GuildChannel.js

Not sure why `NewsChannel` and `StoreChannel` are not in the documentation. If they shouldn't be, feel free to close this.
This pull request adds them into the documentation.
**Status**

docs: NewsChannel and StoreChannel

---

README.md

Removes the Travis status badge for the Github Actions badge.
**Status**

travis badge => github actions badge

---

src/client/Client.js

docs(Client): clarify whose ToS are being violated

---

src/structures/Invite.js
typings/index.d.ts

Fixes Invite#valueOf returning undefined (As Invite#id is not a thing).
**Status**

Fix(Invite): Fix valueOf returning undefined

---

src/structures/User.js
src/util/MessageFlags.js
typings/index.d.ts

See https://github.com/discordapp/discord-api-docs/pull/1219/commits/ec18e654894f1e7d938f0b71eac57676f966a03d
**Status**

feat: add new MessageFlags.FLAGS & User#system

---

package.json

Marks the new peer dep from #3393 as optional
**Status**

Mark utf-8-validate as optional

---

package.json

Node version was bumped to `10.2.0` with the merge of #3578 
**Status**

chore: node version in package.json

---

typings/index.d.ts

Fixes #3675 
Not sure if that's all there is to it, but to my understanding of [ this commit](https://github.com/discordjs/discord.js/commit/bcb0cd838b9fbcbb7467d4618280a820baf2e0a2) that's literally all.
**Status**

fix(typings): Remove VoiceChannel#connection

---

src/util/Speaking.js
typings/index.d.ts

See https://discordapp.com/developers/docs/topics/voice-connections#speaking for the added bit.
**Status**

feat(Speaking): add PRIORITY_SPEAKING bit

---

typings/index.d.ts

Fixes build error in TS projects, [ref](https://github.com/discordjs/discord.js/commit/8014ddcd1c651749fc64e8dfc0b0863422d57203#commitcomment-36775342).
Fixes #3690
**Status**

typings: Fixed build error

---

typings/index.d.ts

This pull-request does not change or modify code. Further, it replaces the property 'broadcasts' with 'subscribers' and adds a new property 'player'.
**Status**

types(VoiceBroadcast): add subscribers property

---

src/client/websocket/packets/handlers/Ready.js
src/client/websocket/packets/handlers/Resumed.js

https://github.com/discordjs/discord.js/projects/5#card-31518692
**Status**

src: Remove `_trace` from different places in the WS

---

src/structures/Presence.js
typings/index.d.ts

This PR adds support for multiple activites.
That way bots can access, for example, the currently played spotify song, custom status, and game of a user.
**Status**

feat(Presence): add support for multiple activities

---

docs/topics/voice.md

ffmpeg package changed from `ffmpeg-binaries` to `ffmpeg-static`.
**Status**

chore: ffmpeg package in the voice doc

---

.github/workflows/test-cron.yml
.github/workflows/test.yml

Mainly to get rid of the annoyances when you delete a file that the lint fails, or on PRs the inability to post annotations.
**Status**

feat/fix: use updated eslint action

---

.github/CONTRIBUTING.md
README.md
docs/general/faq.md
docs/general/welcome.md
docs/topics/voice.md
package.json

docs: replace all occurances of node-opus with @discordjs/opus

---

src/structures/MessageMentions.js

backports #3693 and #3705 7f99be7 into 11.5-dev
Fulfills <https://github.com/discordjs/discord.js/projects/5#card-31608750>
**Status**

backport(MessageMentions): mention order notice

---

src/client/ClientDataResolver.js

This PR fixes #3666 by resolving a `Guild` to a `User` in `ClientDataResolver#resolveGuild`.
**Status**

fix(ClientDataResolver): return a user in resolveUser when passing guild

---

LICENSE

Bumps the year to 2020 in the LICENSE file.
**Status**

chore(License): bump license year

---

src/errors/Messages.js
src/structures/Guild.js
typings/index.d.ts

This PR adds `Guild#fetchBan` to fetch a single ban, see [here](https://discordapp.com/developers/docs/resources/guild#get-guild-ban) on the API Docs
**Status**

Add `Guild#fetchBan`

---

src/structures/Presence.js

This PR backports #3655 by adding an `if` handling twitch previews.
**Status**

fix(RichPresenceAssets): add Twitch preview link for largeImageURL

---

src/structures/MessageReaction.js
src/structures/ReactionEmoji.js
typings/index.d.ts

This PR backports #2230 in a non-breaking way.
**Status**

feat(MessageReaction): backport animated, client, created*, and url

---

src/client/voice/dispatcher/StreamDispatcher.js
src/client/websocket/WebSocketManager.js
src/client/websocket/handlers/CHANNEL_PINS_UPDATE.js
src/structures/Guild.js
src/structures/MessageCollector.js

I scanned the repository with [deepscan](https://deepscan.io/) to find any underlying issues or unneeded checks and this is what I found. If needed I can split this up into multiple PR's, and if any of the changes are incorrect let me know and I can fix them.
**Status**

cleanup: fix deepscan issues.

---

package.json

**Please describe the changes this PR makes and why it should be merged:** To avoid confusion with the dev branch beeing listed as 11.5.1 in `npm ls``the Version has been bumped to 11.5-dev.
**Status**

Bump Version to 11.5-dev

---

src/structures/interfaces/Collector.js
typings/index.d.ts

This PR backports #2942 adding the `idle` option to collectors.
**Status**

feat(Collector): add idle option

---

src/structures/GuildMember.js

fix(GuildMember):  backport #3765

---

src/managers/BaseManager.js
src/managers/ChannelManager.js

Add the "Extends BaseManager" info to the doc
**Status**

Add extends jsdoc tag to ChannelManager

---

src/structures/Guild.js

This PR corrects the jsdoc for Guild#channels, the deacription now states its a manager of channels
**Status**

docs(Guild): Guild#channels is a manager of channels

---

src/managers/ReactionManager.js

This PR patches the existing cached message after fetching it from the API if it is a partial message
**Status**

fix(ReactionManager): update partial message

---

src/client/websocket/WebSocketManager.js

This PR isn't a bug fix per say, as the code still worked, but it just cleans up a useless if check and updates the `shards` property accordingly
**Status**

src: Update client options and shards value if fetching shard count

---

typings/index.d.ts

Adds missing typings for Constants#VerificationLevels
**Status**

typings(Constants): add typings for VerificationLevels

---

src/index.js
src/structures/Guild.js
src/util/SystemChannelFlags.js
typings/index.d.ts

This PR backports support for system channel flags.
Relevant PR: https://github.com/discordjs/discord.js/pull/3559
**Status**

feat(Guild): add support for system channel flags

---

src/structures/Guild.js
typings/index.d.ts

This PR adds Guild#rulesChannel(ID) and Guild#publicUpdatesChannel(ID)
ref: https://github.com/discordapp/discord-api-docs/commit/c370aab0e073257c72c67e4b74118baaa4d8080e
**Status**

feat(Guild): Add rulesChannel and publicUpdatesChannel

---

src/structures/MessageEmbed.js

It's a minor code change to how MessageEmbed#files is defined, it removes multi-line defining and instead does it in one line.
**Status**

refactor(MessageEmbed): simplify initialization of files property

---

typings/index.d.ts

chore(typings): semicolon consistency

---

package.json
tsconfig.json
tslint.json
typings/index.d.ts

tooling(typings): new linter for typings

---

src/structures/interfaces/Collector.js
typings/index.d.ts

Re-opening #3405 with @Monbrey's suggestions as I orphaned the last one somehow
**Status**

feat(Collector): Addition of resetTimer()

---

src/structures/MessageEmbed.js
typings/index.d.ts

fixes some typos and other things
**Status**

fix(MessageEmbed): various typos and fixes

---

typings/index.d.ts

Fixes #3832
Partially reverts discordjs/discord.js#3829

Partial-revert "typings(WebhookClient): client is not a Client"

---

package.json

Lets get rid of people abusing our CI as their linter shall we?
**Status**

chore(githooks): husky

---

typings/index.d.ts

This PR re-implements #3879, which was reverted as it was broken, tested the typings in ts and it seems to work properly now
**Status**

typings(WebhookClient): client is not a client

---

src/structures/MessageEmbed.js

https://github.com/discordapp/discord-api-docs/pull/1364 documented a new embed type `article`, this PR documents that new embed type in MessageEmbed
**Status**

docs(MessageEmbed): document `article` embed type

---

package.json

90% of our contributors already use the proper commit-style convention, but theres still a few that need manual changing.
Automating this process, or making people aware of what needs to be done will be easier in the long run to automatically generate changelogs based on the commits.
**Status**

chore(githooks): commitlint

---

src/structures/MessageEmbed.js
typings/index.d.ts

feat(MessageEmbed): Support EmbedFieldData[] instead of EmbedField[] in constructor

---

src/sharding/Shard.js

Adds a missing `.cache` to the `fetchClientValue` example in `Shard`
**Status**

docs(shard): add .cache to GuildManager in fetchClientValue example

---

src/structures/interfaces/TextBasedChannel.js

This PR fixes a typo in the jsdoc for disbleMentions
p.s: accidentally put Guild in the commit message
**Status**

docs(TextBasedChannel): fix typo

---

src/client/Client.js
src/client/websocket/WebSocketManager.js
src/index.js
src/util/Constants.js
src/util/Intents.js
typings/index.d.ts

Discord has documented and enabled intents <https://discordapp.com/developers/docs/topics/gateway#gateway-intents>
This PR attempts to add a BitField extension to allow flag-based manipulation and adds it as documented WebsocketOption
**Status**

feat: Intents bitfield

---

typings/index.d.ts

remove duplicate VerificationLevels
**Status**

fix(typings): remove duplicate VerificationLevels

---

typings/index.d.ts

Adds enum values to ChannelTypes
**Status**

fix(typings): enum values for ChannelType

---

.github/workflows/deploy.yml

chore(ci): deploy docs for tags

---

src/structures/Guild.js

Now verification levels can be set with the corresponding string again.
**Status**

fix(guild): VerificationLevels

---

test/random.js
test/shard.js
test/sharder.js
test/voice.js

This PR updates the test files to use v12 methods instead of v11 methods
**Status**
- Haven't had time to test it all, but i believe it should work

test: update tests

---

src/managers/GuildMemberManager.js

an member -> a member
**Status**

docs(GuildMemberResolvable): an member -> a member

---

src/util/Collection.js

This does come with the drawback that we remove the actual documentation on the class itself but since it was an empty page, I don't really see how it was beneficial to us in the first place.
Fixes #3896
**Status**

docs: make collections more accessible in docs

---

package.json
src/util/Structures.js

The extendable structures via `Structures.extend` weren't documented. This PR adds an "ExtendableStructure" typedef.
**Status**

docs(Structures): add ExtendableStructure typedef

---

src/client/voice/util/PlayInterface.js

This PR updates an example for [PlayInterface#play](https://discord.js.org/#/docs/main/stable/class/VoiceConnection?scrollTo=play).
[reported by shane](https://discordapp.com/channels/222078108977594368/682245387985092711/689145451647074357)
**Status**

docs(PlayInterface#play): update example for v12

---

src/structures/MessageEmbed.js

this PR corrects the description for MessageEmbed#createdAt
**Status**

docs(MessageEmbed): correct description of createdAt

---

typings/index.d.ts

This PR fixes some unexpected errors from running TSC from the commit 8b906c69bb72e223c3956467d8e780ead5e27f42
never thought to run TSC when making that PR, because i assumed the tslint would pick up any errors that TSC would pickup
**Status**

typings/fix(Partials): fix unexpected TSC errors

---

src/structures/MessageReaction.js

This PR fixes the JSDoc for `MessageReaction#count`.
**Status**

docs(MessageReaction): fix jsdoc for count

---

typings/index.d.ts

The commit 495cfa96c26a89b09a73c7dd11d85cfce6d3c7a8 removed a part of my commit a6605155f0ed2090c9d629da68b7697b62c8fa13
**Status**

typings: add back accidental removal

---

.github/ISSUE_TEMPLATE/feature_request.md

This PR switches Ex. to Eg. in the Feature Request template. 
[Why?](https://blog.prepscholar.com/ie-vs-eg-vs-ex-definition)
**Status**

chore: incorrect word in issue template

---

src/structures/Guild.js
typings/index.d.ts

This PR adds 2 features not listed in discord.js but [documented in Discord](https://github.com/discord/discord-api-docs/blob/master/docs/resources/Guild.md#guild-features): `PUBLIC_DISABLED` and `WELCOME_SCREEN_ENABLED`.
**Status**

Add PUBLIC_DISABLED and WELCOME_SCREEN_ENABLED features

---

typings/index.d.ts

Fixes #4022. A BaseManager#remove method was in the typings but doesn't exist.
**Status**

Typings(BaseManager): remove non-existent method

---

src/structures/PermissionOverwrites.js

This pr changes resolveOverwriteOptions description to be more appriopriate to what it does.
**Status**

fix(PermissionOverwrites): resolveOverwriteOptions description

---

docs/examples/webhook.js

docs(Webhook): id and token information

---

src/structures/User.js

This PR fixes the JSDoc for `User#flags`.
**Status**

fix(User): jsdoc for User#flags

---

.github/CONTRIBUTING.md

I was initially confused why my commit wasn't going through (It isn't very intuitive in GitKraken, not sure about CLI Git)
Continuation of #3836 
**Status**

chore(tooling): include mention of commit convention

---

typings/index.d.ts

This PR marks `User#locale` and `User#flags` as being able to be undefined, as they are able to be undefined
**Status**

typings(User): mark `locale` and `flags` as optional

---

typings/index.d.ts

fix(Typing): dmChannel bulkDelete

---

typings/index.d.ts

This PR adds the typings for User#fetchFlags that I missed in #4060.
**Status**

typings: User#fetchFlags typings

---

src/structures/VoiceState.js

Last PR was to stable oops, this is to master.  Thanks @SpaceEEC
**Status**

docs(VoiceState): remove permissions required from description

---

src/structures/Message.js

This PR should help users unfamiliar with the new syntax to use the timeout parameter properly by providing an example.
**Status**

chore(docs): example for timeout in message.delete()

---

src/client/websocket/WebSocketShard.js

This PR adds documentation for properties that are defined with `Object.defineProperty` by adding `@name` to their JSDoc(s).
**Status**

docs(WebSocketShard): add missing properties

---

src/managers/GuildMemberRoleManager.js
src/structures/GuildChannel.js
src/structures/PermissionOverwrites.js

This PR replaces some `an`s with `a`s in some TypeErrors:
- GuildMemberRoleManager#add
- GuildChannel
- - updateOverwrite
- - createOverwrite
*Thanks to @Jiralite [[context]](https://discordapp.com/channels/222078108977594368/682166281826598932/710125302873063515) and to @kav2k [[context]](https://discordapp.com/channels/222078108977594368/682166281826598932/710137730235105380).*
**Status**

fix: grammatical errors in INVALID_TYPE errors

---

src/structures/MessageMentions.js
typings/index.d.ts

This PR fixes typings and docs of the `MessageMentions` class and changes the `MessageMentions#has` method to allow a `Message` to be passed as it's included in the `UserResolvable` type.
**Status**

feat(MessageMentions): fix typings/docs, add resolvables support

---

README.md
docs/general/welcome.md
package.json

Seems like the Discord github organization moved from @discordapp to @discord, so this PR updates references of `discordapp/erlpack` to `discord/erlpack`.
**Status**

docs(erlpack): discordapp to discord

---

README.md
docs/examples/attachments.md
docs/examples/avatars.js
docs/examples/embed.js
docs/examples/greeting.js
docs/examples/moderation.md
docs/examples/ping.js
docs/examples/webhook.js
docs/general/welcome.md
src/client/websocket/WebSocketManager.js
src/client/websocket/WebSocketShard.js
src/structures/Message.js
src/structures/Webhook.js
src/structures/interfaces/TextBasedChannel.js
src/util/ActivityFlags.js
src/util/Constants.js
src/util/Intents.js
src/util/MessageFlags.js
src/util/Permissions.js
src/util/Speaking.js
src/util/UserFlags.js

Discord recently announced that they've switched their service from discordapp.com to discord.com and require all developers to comply by November 7th, 2020
**Status**

Change domain to discord.com

---

package.json

Fixes #4271 
We still have a mention of them in the README, which should be more than sufficient.
**Status**

chore(deps): remove peer-deps as per npm@7

---

.github/ISSUE_TEMPLATE/bug_report.md

Partials and gateway intents have recently become of increasing interest for the ability to reproduce issues. This PR adds this as section to the issue template in hope to receive more information from future issues where this data is sensitive to reproduction and fixing.
**Status**

chore: add relevant client options section to issue template

---

src/structures/interfaces/TextBasedChannel.js
typings/index.d.ts

docs: make use of MessageResolvable type for bulkDelete

---

src/structures/Message.js
typings/index.d.ts

docs(Message): add NewsChannel type to Message#channel

---

src/structures/CategoryChannel.js

docs(CategoryChannel): Fix children being incorrectly marked as nullable

---

src/managers/GuildMemberManager.js

https://github.com/discord/discord-api-docs/commit/b9edace323c9df64c79f104d85984690ae4e2977 changed the `PUT guilds/:id/bans/:id` to accept JSON params rather than querystring params
**Status**

refactor(GuildMemberManager): use data instead of query

---

src/structures/Guild.js

Not easy to test as many people don't have servers with vanity URLs
Small documentation change to vanity URL description
**Status**

docs(Guild): clarify vanity URL documentation

---

README.md
docs/general/welcome.md

Changes the discord badge in the docs welcome page to a shields.io badge to be consistent with the other badges
**Status**

docs(Welcome): change discord badge to shields.io for consistency

---

src/errors/Messages.js
src/util/BitField.js

Provide the offending bitflag to the BITFIELD_INVALID error for easier debugging
**Status**

feat(BitField): add problematic bit to error

---

src/structures/GuildMember.js
src/structures/Message.js
src/structures/User.js
typings/index.d.ts

This PR changes some properties to be explicitly set to null, as they are supposed to be, from structures that can be partial
There is also a change from truthy checks to `'x' in data` in the _patch methods of said structures
**Status**
- I've done a brief check, but it seems to all be covered by the `Partial*` interfaces

fix(Partials): correctly set properties as nullable

---

src/structures/Guild.js
src/util/Constants.js

Updates the large_threshold default value to 50, as that's the [discord default](https://discord.com/developers/docs/topics/gateway#identify)
this was included in #3371, but that was closed
**Status**

chore(Constants): update large_threshold default

---

docs/examples/attachments.md
docs/examples/avatars.js
docs/examples/embed.js
docs/examples/greeting.js
docs/examples/moderation.md
docs/examples/ping.js

The URL that is shows in the docs is the old url for applications. In this pull request I updated the URL to the right url.
The URL that is shows in the docs is the old url for applications. In this pull request I updated the URL to the right url. In the future Discord might show a 404 page for that url so everything needs to be ready and updated.
**Status**
- [ Yes ] Code changes have been tested against the Discord API, or there are no code changes
- [ Yes  ] I know how to update typings and have done so, or typings don't need updating
- [ No ] This PR changes the library's interface (methods or parameters added)
- [ No ] This PR includes breaking changes (methods removed …

docs: updated applications URL

---

src/managers/GuildManager.js
typings/index.d.ts

Adds support for the **`GET`** `/guilds/:id` endpoint. API support! :^)
**Status**

feat(GuildManager): adds GuildManager#fetch

---

.eslintrc.json
.gitignore
.npmrc
package-lock.json
package.json
src/client/websocket/WebSocketManager.js
src/managers/MessageManager.js
src/structures/GuildEmoji.js
src/structures/interfaces/TextBasedChannel.js
src/util/Snowflake.js
typings/index.d.ts
webpack.config.js

chore(Deps): upgrade deps

---

src/structures/User.js

Title says it all!
Honorable mention: https://github.com/discordjs/discord.js/pull/4706#issuecomment-674624855  
**Status**

docs: update jsdoc type for User#bot

---

src/structures/APIMessage.js

Adds a missing word to a comment on the resolveData function
**Status**

docs(APIMessage): fix wording on comment

---

src/util/Constants.js

This PR fixes a typo in ClientOptions#restTimeOffset.
**Status**

docs(ClientOptions): fix typo

---

typings/index.d.ts

#4706 missed the typings for it's change, this PR corrects the the typings
**Status**

fix(typings): bot cannot be null

---

src/structures/BaseGuildEmoji.js
typings/index.d.ts

docs(BaseGuildEmoji): account for optional properties

---

src/util/Snowflake.js

style: remove unnecessary eslint comment

---

src/managers/MessageManager.js

Docs example is updated to properly show the method as part of messageManager and not channel
**Status**

docs(MessageManager): Update example for fetchPinned

---

src/structures/ReactionCollector.js

docs(ReactionCollector): Revise JSDoc for ReactionCollector#dispose and #remove

---

src/structures/Guild.js
typings/index.d.ts

upstream: https://github.com/discord/discord-api-docs/pull/2038
this PR documents the `RELAY_ENABLED` guild feature
**Status**

typings(Guild): document RELAY_ENABLED feature

---

src/structures/Message.js
src/structures/NewsChannel.js
typings/index.d.ts

This PR adds supports for bots to crosspost messages in News Channels.
This resolves #4089 however is currently undocumented as per discord/discord-api-docs#1510
**Status**

feat(Message): add support for crossposting

---

src/util/Constants.js
typings/index.d.ts

Adds activity type 5, Competing (https://github.com/discord/discord-api-docs/commit/cd6c72a9a297c32ef59f3243eaddd9167fb4e1c3)
**Status**

feat(ActivityTypes): add Competing (type 5)

---

src/errors/Messages.js
src/structures/NewsChannel.js
typings/index.d.ts

Adds support for bots to follow NewsChannels (https://github.com/discord/discord-api-docs/pull/1692)
**Status**

feat(NewsChannel): add support for following

---

src/errors/Messages.js
src/managers/GuildEmojiManager.js
typings/index.d.ts

Reverts discordjs/discord.js#4886

revert: "fix(GuildEmojiManager): check for guild in methods that use it"

---

src/structures/ClientUser.js

[`ea223c6`](https://github.com/discordjs/discord.js/commit/ea223c6e640050d64ef25fdab61c95fb05ed1a30): [The streaming type currently only supports Twitch and YouTube.](https://discord.com/developers/docs/topics/gateway#activity-object-activity-types)
[`03487af`](https://github.com/discordjs/discord.js/commit/03487af9597f01a824a0348525afd0487ae973fc): [Bots are only able to send `name`, `type`, and optionally `url`.](https://discord.com/developers/docs/topics/gateway#activity-object-activity-structure)
**Status**

docs(PresenceData): add YouTube and remove application

---

src/client/actions/Action.js
src/client/actions/MessageReactionAdd.js

fix(Action): attempt to get a User if GuildMember not returned

---

src/structures/Guild.js

This PR fixes a bug that caused an internal error to be thrown when trying add a member to a guild using `Guild#addMember`.
The error was only thrown if the member was already part of the guild, but not in the cache.
This is due to Discord responding with `204 No Content if the user is already a member of the guild.` in that case, as stated in [their Documentation](https://canary.discord.com/developers/docs/resources/guild#add-guild-member).
I solved this by checking for this no content response (which is an array or arrabuffer, depending on the environment), and then fetch the member from the guild to keep the documented return value.
**Status**

fix(Guild): fetch member if already in the guild

---

src/structures/GuildTemplate.js

fix(GuildTemplate): 'guild' getter

---

src/structures/User.js

docs(User): fix typos in jsdoc

---

src/client/Client.js

In #4934, Client#emojis was changed to a BaseGuildEmojiManager, but docs weren't updated
**Status**

docs(Client): #emojis is a BaseGuildEmojiManager

---

src/client/actions/GuildDelete.js
src/client/voice/VoiceConnection.js
src/structures/Guild.js
typings/index.d.ts

Similar to other removals for v13, this removes `guild.voice` as it's functionally the same as `guild.me?.voice`. Also does some nice Node.js v14 refactoring in relevant places.
**Status**

cleanup(Guild): remove Guild#voice

---

typings/index.d.ts

Because of the removal of browser support (#5113) `Client#voice` is always non-nullable.
**Status**

types: make Client#voice non-nullable

---

src/util/Collection.js

fix(Collection): toJSON() errors if the collection includes empty values

---

src/structures/GuildMember.js
typings/index.d.ts

https://github.com/discord/discord-api-docs/pull/2299
Previously (when it was still undocumented) that field was nullable, the new merged docs now say it's always present; however someone already noted that this field is not actually always present. Will update once that has been clarified.
**Status**

Add GuildMember#pending

---

.github/workflows/deploy.yml

This PR removes an extraneous filter on the deployment job for webpack missed in #5113
**Status**

chore: remove webpack from deploy workflow

---

src/util/Util.js
typings/index.d.ts

`Buffer.from()` accepts strings.
**Status**

refactor(Util): remove convertToBuffer

---

src/client/Client.js
src/client/websocket/WebSocketManager.js
src/client/websocket/handlers/GUILD_CREATE.js
src/util/Constants.js
test/random.js
test/voice.js
typings/index.d.ts

Removes the `fetchAllMembers` from the client options, per https://github.com/discordjs/discord.js/discussions/5246, https://github.com/discordjs/discord.js/issues/5123#issuecomment-766329225, etc.
Updates the `random.js` test to have a version of the old internal logic for `fetchAllMembers`, for folks that really need it.
**Status**

refactor(Client): remove fetchAllMembers option

---

package.json

feat: jsdelivr default file support

---

src/structures/Guild.js

- Removed the phrase "**partnered guilds**" from the description of `guild.features`
**Reasoning:**
- To prevent the assumption that **any / all** `guild.features` will be indicative of `guild.partnered`.

docs(Guild): clarified description of guild.features

---

test/createGuild.js

Destroys the client after the test is done/failed
The previous file will exit if the test succeeded, and hang if it failed.

test: client should destroy

---

typings/index.d.ts

typings(MessageReaction): allow message to be partial

---

docs/general/faq.md

chore: update d.js guide FAQ link

---

src/client/websocket/WebSocketManager.js
typings/index.d.ts

⚠️ closes #5282
✔️  ~~untested~~ now tested by @vladfrangu 

feat(WebSocketManager): let identify throw on depleted limits

---

README.md
docs/examples/attachments.md
docs/examples/avatars.js
docs/examples/embed.js
docs/examples/greeting.js
docs/examples/moderation.md
docs/examples/ping.js
docs/examples/webhook.js
docs/general/welcome.md
docs/topics/voice.md
test/createGuild.js
test/random.js
test/reactionCollectorCreated.test.js
test/sendtest.js
test/shard.js
test/tester1000.js
test/voice.js
test/webhooktest.js

This PR updates examples and documentation from #4879.

 docs: update docs and examples for #4879 

---

src/managers/GuildMemberManager.js
src/structures/GuildMember.js

docs(BanOptions): make days description more clear

---

esm/discord.mjs
src/index.js

fix(ApplicationFlags): export class

---

src/structures/ClientUser.js

Remove then and catch callbacks from ClientUser#setPresence, as the method no longer returns a Promise.

docs(ClientUser): #setPresence does not return a promise

---

.github/workflows/test-cron.yml
.github/workflows/test.yml

Updates the [setup-node](https://github.com/actions/setup-node) action to v2

chore(ci): Update actions/setup-node action to v2

---

typings/index.d.ts

This change adds the "ShardingManager.shardList" property that was previously missing from the typescript definitions file.
Patch (only index.d.ts affected)

feat(typings): add ShardingManager.shardList to type definitions

---

src/structures/Guild.js
typings/index.d.ts

This PR adds the typings for  `MEMBER_VERIFICATION_GATE_ENABLED` and `PREVIEW_ENABLED` in `GuildFeatures`
Also added comments in `Guilds.js` for possible guild feature values.

feat(GuildFeatures): added the new screening features

---

src/rest/RequestHandler.js

As of https://github.com/discord/discord-api-docs/issues/2702 the x-ratelimit-reset-after header should be present on routes that have ratelimits. I have verified this to be the case, and that it indeed does have how long until the current reset in seconds, to ms precision.
This PR adds handling for this header, preferring it when it is present. It retains old handling in the event that this header is not present.
It prefers this header due to this method not requiring calculation of the API offset, which is a looser timing due to reliance on the second-precise date header.
This theoretically makes using a lower restTimeOffset more viable as well. I tested on the reactions route with this set to 0 and had no …

refactor(RequestHandler): use x-ratelimit-reset-after when present

---

src/structures/Sticker.js

Fixes #5572.
This is caused by #4909 not having updated the import after the merge of #5502.

fix(Sticker): file renamed to SnowflakeUtil
