- .github/workflows/publish-dev.yml
This PR changes the version number format of dev builds to be alphabetically sortable by putting the timestamp first, followed by the commit SHA.
This should address issues with `yarn outdated` caused by version numbers that aren't compliant with semver (yarnpkg/yarn#3560).
This also corrects the version number to be compliant with semver.
A `t` is prepended to the timestamp of the version to ensure it sorts higher than any prior versions' commit hashes. This can be removed after the next publish to NPM.
*Old commit format:*
`13.0.0-dev.2675b08.1627646567`
*New commit format:*
`13.0.0-dev.t1627646567.2675b08`
- Code changes have been tested against the Discord API, or there …
> ci(PublishDev): change version number to be sequential

- src/structures/Widget.js
Just a correction of docs, the typedef was not include in the first place 
(typings are already done btw)
> docs(Widget): Add the typedef WidgetChannel

- src/structures/GuildEmoji.js
- src/structures/Sticker.js
- src/structures/TextChannel.js
- src/structures/interfaces/TextBasedChannel.js
This pull request tweaks some `@returns` descriptions that I have judged... strange.
When I was looking through the documentation for a [`GuildEmoji`](https://discord.js.org/#/docs/main/master/class/GuildEmoji), I noticed the `GuildEmoji#equals()` method had a `@returns` description on it. I also noticed the description is quite literally the same as the initial description. So like, why is it there? This is the same for [`Sticker#equals()`](https://discord.js.org/#/docs/main/master/class/Sticker?scrollTo=equals), but there does not appear to be a `@returns` description for other `equal()` methods around discord.js such as [`User#equals()`](https://discord.js.org/#/docs/main/master/class/User?scrollTo=equals) or …
> docs: Refactor a few `@returns` descriptions

- src/managers/GuildChannelManager.js
- src/structures/CategoryChannel.js
- src/structures/Guild.js
- src/structures/GuildChannel.js
- src/structures/GuildMember.js
- src/structures/Role.js
- src/structures/VoiceState.js
- src/structures/Webhook.js
- typings/index.d.ts
Per #5521, methods and typings that were solely for category channels (and ids) were instead allowing any channel to go through instead of just `CategoryChannelResolvable`. This pull request should address this and resolve #5521.
Additionally, this pull request changes the type definition for `ChannelData`. Before, it only could take the parent id (`Snowflake`) of a potential category channel, but now, it is possible to take a `CategoryChannelResolvable` instead. This means a rename is in order, so I've changed `parentId` here to just `parent`. This also makes it a breaking change, but this also matches nicely now with the `GuildChannelCreateOptions` type definition!
- Code …
> refactor: Strengthen channel typings in appropriate places

- src/managers/GuildChannelManager.js
- src/managers/ThreadManager.js
- typings/index.d.ts
Guild wide route for fetching active threads! And since channel wide route its being removed in v10, already based the per channel fetch on guild wide.
> refactor: use guild-wide route for fetching active threads

- src/managers/GuildMemberManager.js
- src/structures/Guild.js
- typings/index.d.ts
- typings/index.ts
The long awaited move is here.
Also comes with a bug fix to the method (throws properly when a role is invalid), along with no more param mutation.
Further adds a force param for those of you that don't get member events (if a member has left while the bot is running, they still are cached 😢 )
> refactor: move member adding to manager

- src/managers/ThreadManager.js
- src/structures/Message.js
- typings/index.d.ts
This changes the Message#startThread parameters to be consistent with ThreadManager#create to also prevent the need for any breaking changes in the future if extra parameters need to be added.
> refactor(Message): accept a single object instead of 3 arguments

- typings/index.d.ts
With discord buttons and link button components, there are certain property combinations that aren't allowed. Basically, You can't use a `customID` property for buttons with the `LINK` style, for non-link buttons you can't use the `url` property. The issue is that it is only presented at runtime:
```
DiscordAPIError: Invalid Form Body
components[0].components[0].custom_id: A custom id and url cannot both be specified
```
With this PR it adjusts the `ButtonMessageOptions` type to provide a compile-time error, if an invalid `ButtonMessageOptions` combination is provided.
- Code changes have been tested against the …
> types(ButtonMessageOptions): make button/link button typings more specific

- src/structures/Guild.js
- src/structures/ThreadChannel.js
- typings/index.d.ts
This PR adds a fetchOwner() method that returns the ThreadMember object corresponding to the Owner of the thread
> feat(ThreadChannel): add fetchOwner() method

- src/structures/MessageEmbed.js
- typings/index.d.ts
This PR adds a setFields method to MessageEmbed that overwrites the current fields in the MessageEmbed with the provided ones.
> feat(MessageEmbed): add setFields method

- src/structures/GuildMember.js
- src/structures/VoiceState.js
- typings/index.d.ts
This changes `VoiceState#kick()` to `VoiceState#disconnect()`.
Changing it to use disconnect reflects well on descriptions elsewhere such as `VoiceState#setChannel()` and `GuildMemberEditData` and the [Discord documentation](https://discord.com/developers/docs/resources/guild#modify-guild-member). Even in the Discord client when you right click someone, the option is "disconnect". I feel like this is a consistent change that should be made.
- This PR includes breaking changes (methods removed or renamed, …
> refactor(VoiceState): Change kick to disconnect

- src/structures/interfaces/InteractionResponses.js
The response methods did not correctly reflect the typings on `@returns`, so I've gone ahead and corrected them!
> docs(InteractionResponses): Correct `@returns` on responses

- src/client/actions/ChannelUpdate.js
#6114 accidentally removed a line which caused a converted TextChannel to not be updated.
> fix(ChannelUpdate): restore accidentally removed line

- src/structures/BaseGuildVoiceChannel.js
- src/structures/GuildChannel.js
This PR modifies `GuildChannel` to use `Collection#filter` for its `members` getter. `BaseGuildVoiceChannel#members` remains unchanged for optimization purposes (one iteration with a for-of loop instead of two using .filter and .map).
Also removes the administrator permission ignore from `GuildChannel#members`, not sure why this was set? If someone has got Administrator permission, even if they don't have View Channel, they are still supposed to see that channel so they should be included in their members.
> refactor(GuildChannel): use filter method for #members

- README.md
Since we are using application commands instead of message based commands for all examples, the readme should do it too for consistency
>  docs: change example in readme to slash command

- src/client/Client.js
- src/managers/GuildEmojiManager.js
- src/managers/GuildManager.js
- src/managers/GuildMemberManager.js
- src/managers/GuildStickerManager.js
- src/managers/MessageManager.js
- src/managers/PermissionOverwriteManager.js
- src/managers/ReactionManager.js
- src/managers/ReactionUserManager.js
- src/managers/RoleManager.js
- src/managers/ThreadMemberManager.js
- src/sharding/Shard.js
- src/structures/Guild.js
- src/structures/GuildAuditLogs.js
- src/structures/GuildChannel.js
- src/structures/GuildEmoji.js
- src/structures/GuildPreview.js
- src/structures/GuildTemplate.js
- src/structures/Integration.js
- src/structures/Invite.js
- src/structures/Message.js
- src/structures/Role.js
- src/structures/TextChannel.js
- src/structures/ThreadChannel.js
- src/structures/ThreadMember.js
- src/structures/Webhook.js
- src/structures/interfaces/Application.js
- src/structures/interfaces/TextBasedChannel.js
- src/util/Util.js
This PR refactors all functions to be async instead of chaining a `.then(...)` - also fixes a couple issues where errors are thrown instead of returning a `Promise.reject(...);`
untested
> refactor(*): use async functions

- README.md
The new example of the README was missing a semicolon, added it for consistency with the styling since the guide has that semicolon and it's used everywhere else at the end of functions
> docs: add missing semicolon to readme

- README.md
Yet another README pr, this one removes the "this is still for stable" message from the guide link and changes the update guide link to v13 changes, since the old one is for v12
> docs: update link of the guide to v13 changes

- src/client/actions/ChannelUpdate.js
- typings/index.d.ts
Add GuildStickerManager and GuildInviteManager to list of configurable Caches, as both extend CachedManager.
> types(Caches): add GuildStickerManager and GuildInviteManager

- src/client/Client.js
Client#_finalize is currently showing up in the docs due it being not marked as private
> docs(Client): mark _finalize as private

- src/structures/MessageButton.js
- src/structures/MessageSelectMenu.js
- typings/index.d.ts
MessageButton#setDisabled and MessageSelectMenu#setDisabled currently need to be passed a parameter set to true to actually disable them. This PR defaults said parameter since the method name implies this functionality
> refactor(MessageComponents): default setDisabled to true

- src/client/actions/Action.js
Since #5906 interaction channels get resolved by Action#getChannel, however this method does not account for the User being in data.user for interactions instead of data.author. Since the interaction data does not include a 'user_id' field a partial user with the id of `undefined` gets added to the cache if the interaction is triggered from a DM channel.
I am not too familiar with discord.js internals, so I hope this change does not break something elsewhere (tested it for a few days on a fork and my bot ran fine with it)
- I know how to update typings and have done so, or typings don't …
> fix(Action): getChannel interaction DM

- src/client/websocket/handlers/CHANNEL_PINS_UPDATE.js
- src/managers/MessageManager.js
- src/structures/Channel.js
- src/structures/CommandInteraction.js
- src/structures/Interaction.js
- src/structures/InteractionCollector.js
- src/structures/Message.js
- src/structures/MessageCollector.js
- src/structures/Typing.js
- src/util/Constants.js
- typings/index.d.ts
- typings/tests.ts
At the moment, if Discord adds a new channel type, we have to update the types in many places, this creates issues as far as the type consistency go, such as `MessageCollector` not accepting `NewsChannel` as a valid channel type.
I also considered #6262 as an alternative fix for this, however, a generic type doesn't have many of the benefits from an union, such as being able to exclude certain types (`channel.guild ? <channel is TextChannel | NewsChannel | ThreadChannel> : <channel is DMChannel | PartialDMChannel>`).
I also made a typedef in the JavaScript side so the documentation for it is readily available in the documentation website, and refactored the TS type for `TextBasedChannelTypes` to read the new type's …
> refactor: added `TextBasedChannels` type

- src/client/websocket/WebSocketShard.js
Fixes a bug where the client would not emit ready despite being ready, having to wait 15 seconds instead when no guilds intent was specified
> fix(WebSocketShard): mark shard ready if no guilds intent

- src/managers/GuildStickerManager.js
This PR fixes a grammar mistake in the documentation, which can be found somewhere like [here](https://discord.js.org/#/docs/main/master/typedef/StickerResolvable). "An Sticker" is not correct, and neither is "an StickerResolvable", and should be "A sticker" instead because Sticker is not a vowel. 
> docs: grammar fix 

- typings/index.d.ts
@kyranet and I found the bug when updating `@skyra/editable-commands` when our custom function that accepted an argument of `MessageTarget` was suddenly no longer accepting `message.channel`. Turns out it was because of a mistake @kyranet made lulz
> types: make MessageTarget extend on TextBasedChannels

- src/managers/MessageManager.js
- src/managers/ReactionManager.js
- src/managers/ReactionUserManager.js
- src/structures/Message.js
- src/structures/MessageCollector.js
- src/structures/MessageMentions.js
- src/structures/MessagePayload.js
- src/structures/MessageReaction.js
- src/structures/ReactionCollector.js
- test/random.js
- typings/index.d.ts
While the direct issue outlined in #6168 has been fixed in #6263, the same issue (`Message#channel` returning a text channel) still persists for old messages sent in this same channel before it was converted. As outlined in the issue the least intrusive way to fix this I could think of is making `Message#channel` a getter to retrieve the channel from cache on demand. I use the Client cache (versus the guild cache) to be robust against DMs, if that has any caveats I did not think of, please let me know
- Make `Message#channel` a getter
- Change`Message#guild` getter (relied on `Message#channel` before)
- remove the extra channel from the Message constructor and `MessageManager#_add` call
- use ids within Message …
> fix(Message): make #channel and #guild getters

- typings/index.d.ts
This is an addendum to #6212, it simply exports the different button option variants, and cleans up definitions.
> types(MessageButtonOptions): Clean up and export some button option type definitions

- src/structures/BaseGuildTextChannel.js
- src/structures/BaseGuildVoiceChannel.js
- src/structures/GuildChannel.js
- src/structures/NewsChannel.js
- src/structures/StageChannel.js
- src/structures/StoreChannel.js
- src/structures/TextChannel.js
- typings/index.d.ts
This addresses a number of issues with various channel properties being defined too generically, resulting in them existing on channel subclasses where they aren't supported by the API.
- New class BaseGuildTextChannel extends GuildChannel, implements TextBasedChannel
- TextChannel and NewsChannel both extend BaseGuildTextChannel
- rateLimitPerUser now only exists on TextChannel
- GuildChannel#setTopic moved to BaseGuildTextChannel and StageChannel
- GuildChannel#createInvite moved to BaseGuildTextChannel, BaseGuildVoiceChannel and StoreChannel
- GuildChannel#fetchInvites moved to BaseGuildTextChannel, BaseGuildVoiceChannel and StoreChannel
- BaseGuildTextChannel#setType now has override types
- I know how to update typings and have done so, or …
> refactor(Channels): fix incorrectly shared properties

- src/structures/BaseGuildTextChannel.js
Fixes a bug introduced in #6262 which meant TextChannel and NewsChannel weren't calling `_patch()` on creation.
> fix(BaseGuildTextChannel): call patch

- src/util/Options.js
Just fixed a small typo introduced in #6282
> docs: typo in ClientOptions

- src/structures/Channel.js
- typings/index.d.ts
Adds `isVoice()` type guard to Channel. We already have `isText()` and `isThread()`, so it's logical to have one for voice-based channels as well.
> feat(Channel): add isVoice()

- src/errors/Messages.js
- src/structures/CommandInteraction.js
- src/structures/MessageComponentInteraction.js
- src/structures/interfaces/InteractionResponses.js
- typings/index.d.ts
*Just one more PR to defer the v13 release*
This renames `.defer()` to `.deferReply()` and with it also `InteractionDeferOptions` for more correctness (you do not defer the interaction itself) and better consistency with `.deferUpdate()` and possible upcoming methods.
I wasn't sure if `.deferred` should be renamed to `.replyDeferred` or something like that, so I kept it at the current name for now.
> refactor(Interaction): rename defer to deferReply

- src/structures/interfaces/Collector.js
- typings/index.d.ts
This PR makes a small change to Collector#checkEnd to make it return a boolean representing whether or not the collector ended.
> feat(Collector): return a boolean on checkEnd

- src/rest/HTTPError.js
- src/util/DataResolver.js
This PR fixes two grammar mistakes. Since `HTTP` is an acronym, and when saying the first H, it sounds like a vowel, it should be "an HTTP" and not "a HTTP". 
This also fixes "an template code". 
Examples:
A HTTP request ❌
A SAT exam ❌
An HTTP request ✔️
An SAT exam ✔️
> docs: grammar fixes

- src/structures/InteractionCollector.js
This PR introduces a grammatical fix. `a interaction` is incorrect, and in turn has been fixed to `an interaction`.
> docs: grammatical fix

- package-lock.json
- package.json
- src/rest/APIRequest.js
This PR removes the [abort-controller](https://npmjs.com/package/abort-controller) package from the dependencies as a favor of the initial Node.js implementation of the [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) API which was graduated [here](https://github.com/nodejs/node/pull/35949).
The lib should use the initial implementation of the APIs if possible.
- I know how to update typings and have done so, or typings don't need updating.
> refactor: replace dependency with initial implementation

- src/managers/ChannelManager.js
- src/managers/GuildChannelManager.js
- src/util/LimitedCollection.js
- src/util/Options.js
- src/util/Util.js
- typings/index.d.ts
Fixes a bug in the current sweeping of caches where ThreadChannels would remain in the client and guild channel caches, only being removed from the thread channel caches.
Allows a bit more control over how thread channels are swept from these caches without triggering the process warning for overriding the channel caches.
Also fixes a minor documentation error in LimitedCollection.
- This PR includes breaking changes (methods removed or …
> fix(Caching): sweep archived threads in all channel caches

- src/structures/Message.js
- src/structures/MessageMentions.js
Fixes a hard crash when resolving mentioned roles in previously uncached messages being replied to.
Also passes the guild id that is received with said message reference so that it is more likely the mentions will be resolved.
> fix(MessageMentions): check guild exists before adding roles

- .github/FUNDING.yml
Adds the core maintainers with GitHub Sponsors enabled to the funding doc to help point folks in the right direction if they wanna sponsor those that keep this lib going.
Space, ily, but you don't have Sponsors enabled (which is in a way great 'cause the config only allows four usernames)
> chore: add other maintainers to GH Sponsors config

- typings/index.d.ts
Fixes this TypeScript error that was introduced cause of https://github.com/discordjs/discord.js/pull/6286
> types(Util): fix cleanContent parameter type

- src/structures/Message.js
PR #6271 has introduced a regression, because fetched messages do not include a `guild_id` property in the rest response. This causes `Message#guild` to become `null` for fetched messages, even if they were fetched from a guild channel.
- try to assign the guild id from the channel, if available
- adapt the `Message#guild` getter to also return the guild from the `Message#channel` getter, if necessary and available
> fix(Message): handle fetched messages

- src/util/Options.js
- typings/index.d.ts
Separates out the default options being passed to Options.cacheWithLimits.
This allows devs to change only a single one of the default overrides or add on top without having to redo the rest.
> refactor(Options): separate default settings for make cache

- src/managers/ChannelManager.js
- src/managers/GuildChannelManager.js
- src/managers/GuildManager.js
- src/managers/PermissionOverwriteManager.js
- src/managers/RoleManager.js
Fixes a typo in the warning for `UnsupportedCacheOverwriteWarning`.
> fix(Managers): fix typo in unsupported warning

- src/util/Constants.js
- typings/index.d.ts
CDN typings had a surprising number of issues so this fixes them:
- DefaultAvatar takes "discriminator" (number), not id
- a few used `userId` when they were not for users
- added `dynamic` option to Avatar and Icon (pulled from the banner prs)
- a bunch of id args were typed as `Snowflake | number` for some reason, changed those to just `Snowflake`
- some methods actually take format and size in an object (for some reason) but they were typed as separate args
also changes `clientId` to `appId` to reflect Discord now using "application id" in non-OAuth2 contexts
> fix(Constants): fix CDN endpoint typings

- typings/index.d.ts
`<User>.avatarURL({ format: 'gif' });` throws the following:
Type '"gif"' is not assignable to type 'AllowedImageFormat | undefined'.
> types(ImageURLOptions): allow 'gif' format

- typings/index.d.ts
The options type `this[]` as a self reference causes issues when implementing this interface. Changing this to `ApplicationCommandOptionData[]` fixes this issue https://imgur.com/a/0eVBoJU
> types(ApplicationCommandOptionData) changed options type

- .github/CONTRIBUTING.md
updates the conventional commit url, to use `discord.js-modules` instead of `discord.js-next`
> chore: update conventional commit URL

- src/util/Options.js
fix defaultMakeCacheSettings to be consistant with the actual name.
> docs(Options): defaultMakeCacheSettings typo

- src/client/actions/InviteCreate.js
- src/client/actions/InviteDelete.js
Fixes a doc typo. Should be MANAGE_CHANNEL**S**
> docs(Invite): `MANAGE_CHANNELS` instead of `MANAGE_CHANNEL`

- README.md
**Why this change should be merged:**
Because some people keep installing `discord-api-types` using `discord-api-types/v9` which is not available.
Probably because they just install by copy and paste the module name. So this is just to make it clearer.
> chore(README): more explanation in `README.md`

- typings/index.d.ts
Nothing important but why not update it.
Update a typing error.
> typings(Events): renamed `messageReactionAdd`'s reaction parameter

- typings/index.d.ts
Fixes a method name mismatch in the typings.
Preferred to edit the typing instead of the actual method name since `Options.createDefaultOptions` seems a little bit repetitive.
Closes #6375 
> typings(Options): createDefaultOptions => createDefault

- src/util/Util.js
[If an invalid string is passed into resolveColor, it never actually throws a `COLOR_CONVERT` error and will return NaN](https://user-images.githubusercontent.com/19440022/128658616-6420ae74-1021-4405-b2d0-3f8b5ca2c9ee.png). Why is this? Well because of this line:
https://github.com/discordjs/discord.js/blob/cd393fd4214e111f1cf6de779cfcc07315e80fbd/src/util/Util.js#L473
Because [NaN isn't a truthy value](https://cdn.discordapp.com/attachments/768856355255484469/874136189278519346/node_IBCxEagdZz.png), we don't get past that first condition to be able to check whether the color is NaN. This PR fixes that.
> fix(Util): remove truthy check before isNaN check

- src/managers/ApplicationCommandPermissionsManager.js
- src/structures/ApplicationCommand.js
- src/structures/CommandInteraction.js
- src/structures/CommandInteractionOptionResolver.js
Some links related to interactions were wrong (you can tell straight away because there was no `-` separating the words!) - I've gone ahead and pointed them to the correct area.
`APIInteractionDataResolvedChannel` & `APIInteractionDataResolvedGuildMember` were missing documentation links, so I've gone ahead and pointed them to https://discord.com/developers/docs/interactions/slash-commands#interaction-object-application-command-interaction-data-resolved-structure instead of the usual structure's object. This is because in this link, it tells you _exactly_ what to expect from the data received rather than looking at the whole object and taking guesses:
> Partial Member objects are missing user, deaf and mute fields …
> docs: Correct wrong interaction links

- src/client/actions/InteractionCreate.js
- src/managers/ApplicationCommandManager.js
- src/structures/ApplicationCommand.js
- src/structures/BaseCommandInteraction.js
- src/structures/CommandInteraction.js
- src/structures/CommandInteractionOptionResolver.js
- src/structures/ContextMenuInteraction.js
- src/structures/Interaction.js
- src/util/Constants.js
- typings/enums.d.ts
- typings/index.d.ts
- typings/tests.ts
This adds support for creating Application Commands in right-click context menus, and receiving the interactions.
The received data is parsed into the CommandOptionResolver as seamlessly as possible:
- A command acting on a user creates a `USER` type option: `getUser('user)` / `getMember('user')`
- A command acting on a message creates a fake `_MESSAGE` type option for the new `getMessage('message')`
The type of application command is yet to be included in the interaction data, but when it is this will be updated to use that rather than relying on the existence of `target_id`.
- This …
> feat: right-clickybois (context menu support for ApplicationCommand and CommandInteraction)

- src/structures/ApplicationCommand.js
Fixes the type property of ApplicationCommandData to use ApplicationCommandType
> docs(ApplicationCommandData): fix type property

- typings/index.d.ts
This introduces compile-time constraints for the changes recently added to `ApplicationCommandData`:
- `description` is required when type is set to `'CHAT_INPUT'`
- `options` is only available to commands of `'CHAT_INPUT'` types as per the discord docs
> types(ApplicationCommandData): Stronger typings for `ApplicationCommandData` variants.

- src/structures/ContextMenuInteraction.js
Fixes a bug in context menus where the raw message wasn't being used, resulting in the option returning undefined.
> fix(ContextMenuInteractin): store message as raw value

- src/structures/BaseCommandInteraction.js
- src/structures/CommandInteraction.js
- src/structures/CommandInteractionOptionResolver.js
- src/structures/ContextMenuInteraction.js
- typings/index.d.ts
In the absence of a good way to expose individual resolved data as "mentions", this exposed the complete, parsed `interaction.data.resolved` object as a number of Collections, similar to how MessageMentions are provided.
Aim is to do this in a non-breaking way for 13.1.0, hence using the "resolved" property name, leaving "mentions" available if we want to do a better filtering of it somewhere else down the track.
> feat(CommandInteractionResolvedData): access to "raw" resolved data

- src/structures/Guild.js
- typings/index.d.ts
#6299 modified this to be nullable, but upon looking through Discord's documentation (and all prior versions) with testing on non-community guilds, it seems it is documented to always return a string and testing has verified this. Thus, this property will be modified to be only a string!
> fix(Guild): `preferredLocale` to always be a string

- src/structures/WidgetMember.js
- typings/index.d.ts
The [`WidgetMember`](https://discord.js.org/#/docs/main/main/class/WidgetMember) class had a bunch of properties that would default to `undefined` if said member was not in voice or did not have an activity. The documentation already assumed them to be nullable, but the typings didn't! Side note: `WidgetMember#avatar` typings were wrong as they return `null` if not found.
I've defaulted them now to `null`. The JSDocs are already nullable, so no change there. The typings have been updated from them being optional properties to nullable.
I believe the linter modified the typings file, so that went in here as well.
- Code changes have been tested against the Discord API, or …
> fix(WidgetMember): Default to `null` and not `undefined`

- src/structures/StageInstance.js
- typings/index.d.ts
`StageInstance#discoverableDisabled` was possibly `undefined`.
This can occur via the following steps:
1. Start a stage channel instance
2. End the stage channel instance
3. Restart the bot to ensure that the instance is not cached
4. Fetch the audit log entry for this stage instance
<details>
<summary>Response</summary>
```JavaScript
GuildAuditLogsEntry {
targetType: 'STAGE_INSTANCE',
actionType: 'DELETE',
action: 'STAGE_INSTANCE_DELETE',
reason: null,
executor: User {},
changes: [
{ key: 'topic', old: 'hi', new: undefined },
{ key: 'privacy_level', old: 2, new: undefined }
],
id: '875086920567377920',
extra: {
channel: StageChannel {
type: 'GUILD_STAGE_VOICE',
deleted: false,
guild: [Guild],
guildId: …
```
> fix(StageInstance): Ensure `discoverableDisabled` is not `undefined`

- package.json
This allows to import from specific paths.
**Why?**
In my case:
Jest does not currently support `exports`. So when ESM is enabled, and discord.js is imported, Jest resolves its CJS version (`main`). This commit will  allow to import from `discord.js/src/index.mjs` into the source code to avoid problems with Jest.
In other cases it would allow to import a specific path which is rather interesting.
> chore(exports): allow imports of specific paths

- src/managers/GuildManager.js
Now that users can join 200 guilds with nitro, bots got a higher limit as well: https://discord.com/developers/docs/resources/user#get-current-user-guilds-query-string-params
> docs(GuildManager): increase fetch limit to 200

- src/client/WebhookClient.js
- src/structures/Guild.js
This removes two examples that the docgen doesn't parse because they are not on methods.
> docs: remove unparsed examples

- src/managers/GuildManager.js
- typings/index.d.ts
This allows setting the `with_counts` query parameter when fetching a guild. I'm not sure when you would want to disable it, but the option exists so it counts towards the API coverage
> feat(GuildManager): allow setting with_counts to false

- typings/index.d.ts
It has come to my attention that the discord API doesn't require the `type` field, and when not provided it defaults to `CHAT_INPUT`. This PR makes the `type` field optional, and assumes if not provided, that the `ApplicationCommandData` typings correspond to a slash command.
This also alleviates a breaking type change for typescript users going from v13 to v13.1, when using `ApplicationCommandData`
> typings(ApplicationCommandData): make `type` field optional

- src/managers/GuildMemberManager.js
- typings/index.d.ts
Add a method (list) on `GuildMemberManager` to support sending a request in order to [list guild members](https://discord.com/developers/docs/resources/guild#list-guild-members)
> feat(GuildMemberManager): add 'list' method

- src/structures/BaseCommandInteraction.js
Fixes missing documentation for `deferReply()`
> docs: rename implementation of deferReply

- src/util/Formatters.js
"id" should be used here rather than "ID" - this is inconsistent with everywhere else in the documentation.
> docs(Formatters): Use id over ID

- typings/index.d.ts
In PR #6071 the Message#_patch method was changed to return type Message because the old patch method did that. But looking at the _patch method it doesn't return anything.
> typings: Message#_patch typings return type

- src/structures/Sticker.js
Resolves #6420 - an instance where `._add()` was missed.
> fix(Sticker): Rename method correctly to _add

- src/errors/Messages.js
- src/structures/interfaces/InteractionResponses.js
It appears a recent API change now allows fetching of ephemeral messages - this removes the internal checks which were in place to prevent API errors.
Attempting to delete an ephemeral still responds with `Unknown Message`.
> feat(InteractionReponses): allow fetching of ephemeral messages

- src/client/BaseClient.js
- src/client/Client.js
- src/rest/RESTManager.js
Removing this will prevent people from raiding easier. Yes they can do fork, but I don't think a well known library like this should support it.
How can you make a self bot?
`new Client({_tokenType:""})`
> fix(BaseClient): Remove selfbot ability

- src/rest/APIRequest.js
- src/util/Options.js
- typings/index.d.ts
This exposes the `https.Agent` options object for `APIRequest` as a client option (`HTTPOptions#agent?: https.AgentOptions`). I am currently working on mock integration testing for discord.js applications, involving a mock REST API and gateway, but to work with a local server and x509 certificates, it is necessary to change some agent options (`rejectUnauthorized: false`). 
> feat(Rest): expose https.Agent options

- src/structures/Webhook.js
- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
Fixes some issues in the Typings (basically like my previous PR #6162)
`attachments` wasn't typed in `MessageOptions`, so I added that and update the Pick when defining `WebhookEditMessageOptions` to add attachments to the typings and to ensure this doesn't bug
Code changes have been tested against the Discord API, or there are no code changes
I know how to update typings and have done so, or typings don't need updating
> chore(Typings): fix WebhookEditMessageOptions not having attachments

- src/util/Constants.js
Following the tradition from #6299 this PR adds a link to Discord's API documentation regarding ApplicationCommandTypes
> docs(ApplicationCommandType): add DAPI link

- src/structures/Message.js
As suggested on the [discord server](https://discord.com/channels/222078108977594368/682245387985092711/876352650172596225), this PR adds a list of message "types" that can hold a MessageReference, as well as a link to the Discord API docs page about this.
> docs(MessageReference): add possible message types

- src/util/Util.js
Allow empty strings to be used in Util#splitMessage as there is not reason not to.
close #6436 
> fix(Util): allow empty strings in splitMessage

- src/errors/Messages.js
- src/structures/Message.js
After some testings, it seems that we can't use `.fetchWebhook()` on a message that was sent by an application (interaction). The way so check this is by comparing the applicationId in the message and the webhookId. If they match, this means that the message comes from an interaction and the webhook behind it cannot be fetched from the api.
The api returns `DiscordAPIError: Unknown Webhook`
Correct me if i'm wrong but i think that it's not possible to send webhooks from an applicationId except through interactions.
- I know how to update typings and have done so, or typings don't need …
> feat(Message): prevent fetching an interaction webhook.

- typings/index.d.ts
This PR adds the missing parameter called `resolved` in `CommandInteractionOptionResolver` that was introduced in #6384 but not added in the typings.
> typings(CommandInteractionOptionResolver): add missing parameter

- typings/index.d.ts
Opening this one up for discussion as to pros and cons - this change enforces the `type` property when using JSON object format for components, rather than builders.
This works and enforces the param, but does mean that objects typed as the base typedefs:
- `MessageActionRowOptions`
- `MessageButtonOptions`
- `MessageSelectMenuOptions`
are not compatible with `MessageOptions` anymore, and instead must be typed as:
- `Required<BaseMessageComponentOptions> & MessageActionRowOptions` for action rows
- `MessageActionRowComponentOptions` for buttons and selects.
Open to feedback on ways to address that without change the fact that the type is not required in the base typedefs, such as creating separately named types e.g. \
`type RawMessageActionRowData = Required<BaseMessageComponentOptions> & …
> typings: require component type in raw object formats

- src/structures/MessageEmbed.js
- typings/index.d.ts
This one is for @almostSouji. Can't post a screenshot of prof chat but y'all can find it there.
- Code changes have been tested against the Discord API (by Souji, as far as I can tell), or there are no code changes
> typings(MessageEmbed): allow `null` for `setTimestamp`

- src/structures/MessageActionRow.js
- src/structures/MessageSelectMenu.js
- typings/index.d.ts
Following the [PR](https://github.com/discordjs/discord.js/pull/6186) that added the setFields method for MessageEmbeds, this PR adds two new methods: setOptions for MessageSelectMenu and setComponents for MessageActionRow.
> feat: set methods for MessageActionRow and MessageSelectMenu

- src/structures/interfaces/InteractionResponses.js
Interaction should be MessageComponentInteraction instead of ButtonInteraction
> docs: fix wrong type being displayed in docs

- src/structures/Message.js
- typings/index.d.ts
Now that the API enforces custom ids to be unique in components in a message, I want to go ahead and propose this new method!
This will add the `<Message>.resolveComponent()` method. By supplying a custom id, the desired component will be returned (or `null` if not found). The use case for this is when the desired behaviour is altering the state of some other specific component upon the interaction of a component on the same message. For me, this is altering the `.disabled` property of a button or a select menu.
I understand I can simply index the components array like so: `<ButtonInteraction>.message.components[<number>].components[<number>]`. However, I don't think this is quite right. I am assuming that the …
> feat(Message): Add method to resolve a component by id

- src/client/actions/UserUpdate.js
When the `UserManager` cache is disabled, updating the client user will result in a crash. The user update action gets the old state of the user via the `UserManager` cache, even if it's the client user. However, when it's disabled, nothing is being returned and so `newUser._update` throws a type error.
This fix makes the code get `client.user` if `client.user.id` and `data.id` are equal.
> fix(UserUpdateAction): rely on client.user when ids match

- src/util/Formatters.js
This pr makes the style parameter of TimestampStyle to TimestampStylesString as the style is of string not an object
> docs(Formatters): fix typo of TimestampStyles

- src/managers/GuildChannelManager.js
The type of the type property in this typedef was set to `string|number` which is misleading since this is actually supposed to be a ChannelType, so this PR fixes that.
> docs(GuildChannelCreateOptions): fix #type type

- src/structures/ThreadChannel.js
- typings/index.d.ts
This PR adds a method to ThreadChannels called fetchStarterMessage that fetches the message that started the thread when this exists. I didn't find any better way to tell if a thread channel was started by a message or not so this just fetches the message with the same ID as the channel from the parent channel.
> feat(ThreadChannel): add fetchStarterMessage

- src/managers/MessageManager.js
- src/structures/MessageAttachment.js
- typings/index.d.ts
This allows users to mark media as spoilers before sending them to Discord's API. The motivation behind this is for convenience, as in, users not needing to place the `SPOILER_` string.
You'll see a validation if the given argument is false, as it's possible to have the spoiler string inside the *string itself*, hence removing the title users would expect. 
I have adapted this PR from `#6473` but I didn't make it an equivalent setter as the function is more easy to use.
Resolves #6473
- This PR changes the …
> feat(MessageAttachment): allow files to be marked as spoilers

- typings/index.d.ts
This PR fixes the type for the componentType property in a MessageComponentInteraction by excluding ACTION_ROW from the list of component types
> types(MessageComponentInteraction): fix componentType

- src/errors/Messages.js
- src/managers/ThreadManager.js
- src/structures/ThreadChannel.js
- typings/index.d.ts
Closes: #6379 
Fixes a bug in typings that didn't pass the allowable thread types properly for news channels since this relies on it.
⚠️ The `invitable` field in the thread creation endpoint does not seem to be respected at the moment, it is supported here, but the API does not utilize it, always setting true.
- https://github.com/discord/discord-api-docs/issues/3700
> feat(Threads): add support for invitable in private threads

- src/structures/BaseCommandInteraction.js
- src/structures/CommandInteractionOptionResolver.js
- typings/index.d.ts
Threads are a possible channel type via `CommandInteractionOptionResolver#getChannel()`. This wasn't in the typings & documentation, but they are now! discord.js already parses them, so no behavioural change is needed.
Also, I changed `APIGuildChannel` to `APIChannel`, as the former didn't have a link & would be the same link as the `APIChannel`. Let me know if it's desired to be the former way (with a link)!
> typings(CommandInteractionOptionResolver): Document & type thread channels

- typings/index.d.ts
- typings/tests.ts
As it stands now if you use this code:
```ts
const collector = message.createMessageComponentCollector({ componentType: 'SELECT_MENU' });
collector.on('collect', interaction => {
// Interaction is type of `MessageComponentInteraction`
});
```
You'll end up with a `MessageComponentInteraction` in the `collect` handler.
Currently there are two trivial ways to narrow this type.
1) Type Guard it:
```ts
collector.on('collect', interaction => {
if (!interaction.isSelectMenu()) {
return;
}
// Interaction is type of `SelectMenuInteraction`
});
```
2) Use the generic parameter:
```ts
.createMessageComponentCollector<SelectMenuInteraction>(...);
```
However, even though these methods are straightforward, these types really …
> typings: Allow message component interaction collectors to infer collected interaction types

- src/structures/GuildChannel.js
Resolves #6446
`<GuildChannel>.manageable` is not efficient with voice channels because `<GuildChannel>.viewable` is not checked on voice channels.
```js
if (VoiceBasedChannelTypes.includes(this.type)) { 
// connect permission check
} else if (!this.viewable) { 
return false;
}
```
> fix(GuildChannel): Fix manageable method for voice-channels

- src/structures/ClientUser.js
A typo in the JSDoc made the type definition for the `.edit` method not appear in the documentation. Also, the `@returns` type now exists for it!
> docs: Fix JSDoc for `ClientUser#edit`

- typings/index.d.ts
- typings/tests.ts
> fix: await message component collectors should return component interactions not collectors

- src/structures/ApplicationCommand.js
- typings/index.d.ts
Adds `ApplicationCommand#equals` since checking the equivalence of application commands is a non-trivial task. Especially when handling the instantiated class and raw data.
Oh, and also because @IanMitchell asked for it
> feat(ApplicationCommand): add #equals

- typings/index.d.ts
This PR fixes the types for MessageReference as guildId can be undefined and messageId can be undefined, not null.
> typings(MessageReference): correctly add undefined type

- src/structures/ThreadChannel.js
I have no idea what I was thinking when I made this but ThreadChannel#channel is not a thing... This PR fixes that so that the method uses ThreadChannel#parent instead
> fix(ThreadChannel): fetchStarterMessage bug

- src/structures/MessageButton.js
note tags don't exist on the website so this PR fixes the one in MessageButton#setURL to be an info tag instead
> docs(MessageButton): fix info tag

- typings/index.d.ts
Changed 'mewMembers' to 'newMembers'
It fixed a typo and changed 'mewMembers' to 'newMembers'
> fix(threadMembersUpdate): fixed typo

- jsdoc.json
Removes jsdoc.json, this file existed for @discordjs/docgen but it's not used anymore, the plugin has also been uninstalled so this file has become useless.
> chore: remove jsdoc.json

- src/structures/MessagePayload.js
Resolves #6604 by correcting the `@returns` documentation.
> docs(MessagePayload): Correct return type of `resolveFile()`

- typings/index.d.ts
These two are currently typed as `unknown` but should now take `HTTPAttachmentData`.
> types(MessagePayload): Specify typings for `files` and  `resolveFile`

- typings/index.d.ts
- typings/tests.ts
Simply uses `MessageComponentCollectorOptions<T>` instead of `InteractionCollectorOptions<T>` for `Message#createMessageComponentCollector`, since the latter type has options
that don't apply to message component collectors.
> typings: `Message#createMessageComponentCollector` use `MessageComponentInteractionOptions<T>`

- src/structures/Interaction.js
- src/structures/MessageComponentInteraction.js
- typings/index.d.ts
- typings/tests.ts
Closes #6591, references: https://discord.com/developers/docs/interactions/receiving-and-responding#interactions
> typings: make `channelId` non-nullable on `MessageComponentInteraction`

- src/structures/ApplicationCommand.js
- typings/index.d.ts
Adds the new `version` field of `ApplicationCommand`:
- discord/discord-api-docs#3524
- This PR changes the library's interface
> feat(ApplicationCommand): add version property

- src/structures/Message.js
This PR fixes a bug with Message#pinnable where it would return false if the type of message was not DEFAULT in some types that can be pinned. This PR fixes that so that it will now work on non system messages.
> fix(Message): pinnable returning false in non-DEFAULT messages

- typings/index.d.ts
This PR adds back the definition for `createMessageCollector` which was removed by #6476 in d10b63e (by mistake??)
@suneettipirneni
> types(TextBasedChannelFields): add back createMessageCollector

- src/client/actions/MessageReactionRemoveAll.js
- typings/index.d.ts
> feat: Give removed `MessageReaction`s on `messageReactionRemoveAll` event

- src/managers/PermissionOverwriteManager.js
The `@returns` description was missing the fact that it is a `Promise`.
> docs(PermissionOverwriteManager): Correct `@returns` of delete

- src/structures/MessageEmbed.js
- typings/index.d.ts
This PR adds support for the APIEmbed type in the MessageEmbed constructor. The code didn't need to be updated as it already supported this type. Fixes #6627
> types(MessageEmbed): allow APIEmbed type

- src/structures/BaseGuildTextChannel.js
- src/structures/ClientUser.js
- src/structures/Role.js
- src/structures/VoiceState.js
- typings/index.d.ts
This PR adds a default value of true for all setX methods across the library that accept a boolean. This follows the direction the library has recently been going in with #6279 and #6509.
This affects the following methods:
- BaseGuildTextChannel#setNSFW
- ClientUser#setAFK
- Role#setHoist
- Role#setMentionable
- VoiceState#setDeaf
- VoiceState#setMute
- VoiceState#setRequestToSpeak
- VoiceState#setSuppressed
> feat: default values for setX boolean methods

- src/structures/VoiceChannel.js
- typings/index.d.ts
To avoid confusion for library users, it is deprecated as a preliminary step to remove two getters that behave the same. 
related: https://github.com/discordjs/discord.js/pull/6551#discussion_r704167474
> docs(VoiceChannel): deprecate editable

- src/managers/GuildManager.js
- src/structures/BaseGuildTextChannel.js
- src/structures/ClientUser.js
- src/structures/Guild.js
- src/structures/Webhook.js
- typings/index.d.ts
This PR updates documentation and typings to allow `null` as a valid value for icon/avatar of a `Guild`, `ClientUser`, and `Webhook`.
It also fixes a bug in `ClientUser#edit` and `Guild#edit` where the `icon` option wasn't being resolved, making it impossible to set a new icon using a path to the local file.
⚠️ From the docs for [`Modify Guild Docs`](https://discord.com/developers/docs/resources/guild#modify-guild), it seems that `splash`, `discovery_splash`, and `banner` can also be set to `null`. My test guild doesn't have those features, so I didn't add changes related to them  here. It would be great if someone can confirm it.
- Code changes have been tested against the …
> fix: allow null to be passed in order to reset icon/avatar

- src/structures/GuildChannel.js
- src/structures/Message.js
- src/structures/VoiceChannel.js
In rare cases, the result returned by the current XXXable property may not return the exact result, but it will return the correct result.
However, it seems difficult to maintain this, so consider removing this property. 
- Cannot delete channels that are not viewable/connectable(have CONNECT permission).
- ~~Cannot edit messages on channels that cannot send messages.~~
- Cannot edit messages on channels that cannot view messages.
- Cannot pin messages on channels that cannot view messages.
- Cannot delete messages on channels that cannot view messages.
- ~~Messages that are not system messages can be pinned.~~
- #6585 
- Code changes have been tested against the Discord …
> fix(xxxable): follow more properly with discord behavior

- src/sharding/Shard.js
The events in the `@link`s didn't actually exist, but now they do!
One cannot do `{@link Client#shardReady}` as this would redirect to the method which doesn't exist. Prefixing `event:` to this will redirect to the correct area (the event). This will require https://github.com/discordjs/website/pull/104 to be merged as this is new parsing.
> docs(Shard): Point to correct events

- typings/index.d.ts
This PR improves the type control of the inGuild() function. Before, the type of the "channel" property was not modified, so if the interaction was sent in a guild the "channel" property could be of type DMChannel (in reality this is not possible)
> types(Interaction): improve type guard for inGuild()

- src/util/Constants.js
This PR mainly improves the error given when a user passes an invalid type to the size parameter in CDN endpoints, so it will now throw a TypeError instead, to prevent confusing errors like this one:
Along with that, there were also other minor changes:
- Removed the redundant webp default formats from all functions as the main makeImageUrl function already does this.
- Changed the dynamic if statement to only trigger if the hash starts with a_ to make it more readable
- Set the default value of dynamic in ImageURLOptions in the docs to false, instead of having that information written down.
- Code changes have been tested against the Discord API, or there are no code …
> refactor(Constants): better type error in cdn endpoints

- src/errors/Messages.js
- src/structures/VoiceState.js
This PR removes an error that was thrown when trying to edit an uncached GuildMember through the VoiceState (using VoiceState#setMute, VoiceState#setDeaf, or VoiceState#setChannel) and uses the GuildMemberManager#edit method instead which doesn't require the member to be cached
> refactor(VoiceState): use manager edit method to remove error

- src/structures/Guild.js
- src/structures/GuildAuditLogs.js
- src/structures/Integration.js
- src/structures/Role.js
- src/util/Constants.js
- typings/index.d.ts
This PR adds a few missing properties to Integration and properly documents all the other ones. I also created an enum in Constants with the expireBehavior and a TODO comment for v14 where we will be able to change all the undefined properties to null, which is what the library does most of the time.
Also added the `Snowflake|string` redundant type union just to make it more clear that some ids can be snowflakes and others can be stringified numbers that are not IDs (only on youtube/twitch integrations)
- This …
> feat(Integration): add missing props and fix docs/types

- src/managers/ApplicationCommandManager.js
- src/structures/ApplicationCommand.js
- typings/index.d.ts
Allows api types to be accepted in `ApplicationCommandManager` methods. This means typescript will no longer complain about type mismatches when using something like builders for example.
> feat: Add support for API command types in `ApplicationCommandManager`

- src/sharding/Shard.js
fix #6626 
Passing a function as a parameter in `Shard#eval()` would return a promise that never resolves due to stringifying the function as described in the linked issue.
This PR fixes that problem.
> fix(Shard): eval promise never resolves

- src/managers/ApplicationCommandPermissionsManager.js
`ApplicationCommandPermissionsManager.set` needs guild as an argument, the examples have been updated to reflect this
> docs(ApplicationCommandPermissionsManager): fix example set method

- typings/index.d.ts
guild emoji caching can be disabled but the types don't allow it
> types: add GuildEmojiManager to Caches

- src/managers/UserManager.js
- typings/index.d.ts
Allow [`UserManager#fetch`](https://discord.js.org/#/docs/main/stable/class/UserManager?scrollTo=fetch) to take a [`UserResolvable`](https://discord.js.org/#/docs/main/stable/typedef/UserResolvable)
- ~~This PR includes breaking changes ⚠️~~
> feat(UserManager): allow #fetch to take UserResolvable

- src/managers/GuildEmojiRoleManager.js
- src/managers/GuildMemberRoleManager.js
The `Set` in these two managers were being created improperly as it compared ids with `Role`s, which wouldn't work. This pull request resolves this (and resolves #6673).
> fix(*RoleManager): Create set of role ids correctly

- src/util/Constants.js
Fixes a bug accidentally introduced by #6637 where an error would be thrown when passing an undefined size (this is what happens when you only test the behavior you're looking for and not other scenarios 😅)
> fix(Constants): allow undefined size

- src/structures/GuildEmoji.js
Guild emojis that were restricted to roles were not being stored in discord.js over the gateway - an empty array would always be set. As such, methods like `GuildEmojiRoleManager.add()` would completely wipe all other roles from the emoji (since it calls `.set()` from the cache which is empty), and then only add what you specified, which is bad behaviour and not intended.
I believe I managed to fix this by setting the default value to the provided array. I have tested this and it works as expected.
> fix(GuildEmoji): Cache restricted roles and author data

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
This PR brings 2 changes to issue forms:
- Removed the default titles from both. This is so that users don't accidentally submit an issue without a proper title, so GitHub will alert them if they try to. The type of issue (bug/request) can already be inferred through the labels
- Changed the Node.js version field in the bug report form to mention that you can also provide your typescript version there, if your issue is strictly related to TS, as discussed [on the discord server](https://canary.discord.com/channels/222078108977594368/884983786545238047/888774406128689222)
And also fixes a small typo in "Codesample"
- Code changes have been tested against the Discord API, or …
> chore(IssueForms): remove default titles

- src/managers/CachedManager.js
fixes: #6667
Under the circumstances where a structure is present in the cache, `<Manager>_add()` returns stale data if `cache` is set to false instead of returning the updated data without caching it.
> fix(CachedManager): return updated data when cache is false

- src/errors/Messages.js
- src/structures/Message.js
This PR makes it so all Message methods/getters that depend on the message's channel either throw an error when the channel is missing (for methods) or account for the possibility of the channel being null (getters). This is due to the fact that Message#channel became a getter in v13 iirc and this can result in the channel being missing if the client loses access to the channel by either being kicked from the guild or the channel being deleted. Fixes #6578 
> fix(Message): throw error on missing channel

- src/structures/MessageAttachment.js
- typings/index.d.ts
- discord/discord-api-docs#3833
> feat(MessageAttachment): add support for ephemeral property

- src/managers/BaseGuildEmojiManager.js
Updates the description to make it clear that it's not referring to the [`identifier`](https://discord.js.org/#/docs/main/stable/class/Emoji?scrollTo=identifier) attribute.
- This PR **only** includes non-code changes
> docs(EmojiResolvable): update description of typedef to remove ambiguity

- src/structures/GuildMember.js
- src/util/Constants.js
- typings/index.d.ts
This PR adds server avatars to the GuildMember object.
discord-api-docs PR:
- https://github.com/discord/discord-api-docs/pull/3081
> feat(GuildMember): add guild avatars

- typings/index.d.ts
- typings/tests.ts
Forgot a thing 🤦 
Closes #6702 
> types: fix missing channel type in subcommand options

- typings/index.d.ts
This PR fixes the types for ActivityOptions#type by removing the ability to set CUSTOM types as this interface is only used when setting values for the client presence, as well as the type of Activity#id which was incorrectly marked as Snowflake (these are never snowflakes, instead they are strings of numbers and letters like `73ce6c5d7bcf522f`, `spotify:1` or `custom`). The docs didn't need to be changed as these were already correctly set.
> types(Presence): fix ActivityOptions#type and Activity#id types

- src/util/Util.js
> fix(Util): default `animated` to false when omitted on resolvePartialEmoji

- src/structures/BaseCommandInteraction.js
- typings/index.d.ts
This PR fixes the type of the key value in the CommandInteractionResolvedData collections in both the docs and the typings
> docs(CommandInteractionResolvedData): fix key type

- src/structures/Message.js
Fixes the return type of `Message#reply` from `Promise<Message | Message[]>` to `Promise<Message>`.
Due to #5918 `Message#reply` can no longer return an array of messages, which is also reflected in [the TypeScript typings][1].
[1]: https://github.com/discordjs/discord.js/blob/fe9500538e76423e49e16a1e1756eb04b5f40531/typings/index.d.ts#L1252
> docs(Message): fix return type for `reply`

- src/structures/PartialGroupDMChannel.js
- typings/index.d.ts
- Added recipients (array of objects consisting of only usernames)
- Name is `null` when a group direct message channel does not yet have a name (initially created)
> feat(PartialGroupDMChannel): Add recipients & fix name

- src/structures/Guild.js
- typings/index.d.ts
Guild#fetchVanityData() seems to always return a number for `uses`, even in the event that:
- A guild has no vanity URL access
- A guild has vanity URL access but has not set it
- A guild has a vanity URL with no uses
In the above cases, Discord returns 0 for `uses`, so this can never be `null`.
> types(Vanity): Make `uses` non-nullable

- typings/index.d.ts
- typings/tests.ts
same as #6562 but for TextBasedChannels
> types(TextBasedChannels): fix awaitMessageComponent return type

- src/managers/GuildManager.js
- typings/index.d.ts
Updated PartialChannelData at [/typings/index.d.ts#L4509](https://github.com/discordjs/discord.js/blob/839974ca432c70d57e82e9b47334f743e0c20281/typings/index.d.ts#L4509) to match [/src/managers/GuildManager.js#L83](https://github.com/discordjs/discord.js/blob/839974ca432c70d57e82e9b47334f743e0c20281/src/managers/GuildManager.js#L83).
Added missing converts (userLimit, rateLimitPerUser, overwrite.type) to `GuildManager#create`.
Made `PartialOverwriteData.type` to take `OverwriteType` instead of `string`.
> fix(GuildManager): add missing types and converts

- src/structures/Webhook.js
- src/util/Options.js
- typings/index.d.ts
This will allow webhooks to fetch, edit and delete messages in threads.
Webhook#fetchMessage() unfortunately didn't already have an object for its second parameter. I would have liked to change it to what I commented [here](https://github.com/discordjs/discord.js/issues/6592#issuecomment-927191151) but to keep it not breaking, I instead added a new client option for webhooks that as a sort of opt-in feature flag that makes the library parse the second parameter as an object, thus allowing access to fetching a message in a thread.
Here's an example:
```JavaScript
const { WebhookClient } = require("discord.js");
const webhook1 = new WebhookClient({
url: "webhook_url1"
});
const webhook2 = new WebhookClient({
url: …
```
> feat: Allow webhooks to fetch, edit and delete messages in threads

- src/structures/Invite.js
This PR fixed a bug with Invite#guild where it was documented as possibly being InviteGuild or Guild but it could never be the latter since `data.guild` can never be an instanceof Guild, since that's the raw data received from Discord. This shouldn't be breaking as the docs and types already had this behavior predicted, it was just poorly implemented
> fix(Invite): #guild never resolving into a Guild

- typings/index.d.ts
This PR simply removes the ability to put UNKNOWN in the channelTypes array in a CHANNEL option on a chat input application command.
> types(ChannelTypes): remove unknown from CHANNEL options

- src/managers/GuildChannelManager.js
- src/structures/CategoryChannel.js
- typings/index.d.ts
This PR adds a method to CategoryChannel called createChannel that creates a channel inside that category. It also fixes a bug in the options interface to disallow GUILD_NEWS_THREAD types on both the GuildChannelCreateOptions and the CategoryCreateChannelOptions interfaces
> feat(CategoryChannel): add createChannel shortcut method

- src/structures/Interaction.js
- typings/index.d.ts
Implements `<Interaction>.member.permissions`, if exists, sent with an interaction. `null` if the interaction was sent via DM.
Attempting to fetch an _uncached_ channel without `VIEW_CHANNEL` will result in a `Missing Access` error. However, interactions can still be received and responded to in channels which a bot does not have `VIEW_CHANNEL` for. Unless we use `<Interaction>.member.permissions` [sent with the interaction](https://canary.discord.com/developers/docs/interactions/slash-commands#receiving-an-interaction) , it's impossible to get the permissions of a member in an uncached channel.
Large bots which cannot afford to cache tens of millions of channels, roles, and permissions, could rely on the …
> feat(Interaction): add memberPermissions

- src/managers/GuildInviteManager.js
- src/structures/NewsChannel.js
- typings/index.d.ts
- Discord rejects fetching invites from category channels and thread channel
- Discord rejects creating an invite on category channels and thread channel
- Discord rejects NewsChannel#addFollower() from anything that isn't a text channel
> types: More accurate types instead of `GuildChannelResolvable`

- src/sharding/Shard.js
- src/sharding/ShardClientUtil.js
- src/structures/BaseGuildTextChannel.js
- src/structures/ClientPresence.js
- src/structures/DMChannel.js
- src/structures/Guild.js
- src/structures/GuildBan.js
- src/structures/GuildChannel.js
- src/structures/GuildEmoji.js
- src/structures/GuildMember.js
- src/structures/GuildPreview.js
- src/structures/GuildTemplate.js
- src/structures/Message.js
- src/structures/MessageReaction.js
- src/structures/Presence.js
- src/structures/Role.js
- src/structures/Sticker.js
- src/structures/StickerPack.js
- src/structures/StoreChannel.js
- src/structures/ThreadChannel.js
- src/structures/ThreadMember.js
- src/structures/Typing.js
- src/structures/User.js
- src/structures/VoiceState.js
- src/structures/Widget.js
- src/structures/WidgetMember.js
- typings/index.d.ts
This PR removes documentation for private constructors.
Those being documented confused library consumers into thinking that they are supposed / intended to instantiate those classes themselves.
Some constructors were intended to be documented due to `Structures.extend` use-cases, but this feature has, since then, been removed.
Changed classes:
- `Shard`
- `ShardClientUtil`
- `BaseGuildTextChannel`
- `ClientPresence`
- `DMChannel`
- `GuildBan`
- `GuildChannel`
- `GuildEmoji`
- `GuildTemplate`
- `Message`
- `MessageReaction`
- `Presence`
- `Role`
- `Sticker`
- `StickerPack`
- `StoreChannel`
- `ThreadChannel`
- `ThreadMember`
- `Typing`
- `User`
- `VoiceState`
- `Widget`
- `WidgetMember`
This PR also modifies the …
> docs: undocument private constructors

- src/sharding/Shard.js
- typings/index.d.ts
This PR resolves #6575 in a semver: patch manner by attaching the provided timeout to the exit listener which then passes this timeout back to the spawn method.
Also resolved a bug where `Shard#spawn` would not return a promise when the timeout was disabled.
A semver: major solution would be to remove timeout parameters and make them properties to be specified when constructing the sharding manger (or at least the shard).
> fix(Shard): use provided timeout when respawning

- src/structures/ReactionCollector.js
- typings/index.d.ts
This PR resolved #6461 by only calling the filter function once.
> fix(ReactionCollector): only call the filter function once

- src/client/actions/MessageUpdate.js
- src/structures/Message.js
- typings/index.d.ts
This PR fixes #6431 and maybe also fixes #6368 by only updating properties if they are part of the payload.
> fix(Message): avoid overwriting properties in _patch

- src/managers/RoleManager.js
- src/structures/Guild.js
- src/structures/Role.js
- src/util/Constants.js
- typings/index.d.ts
Starts work on role icons:
- discord/discord-api-docs#3815
- discord/discord-api-docs#3847
> feat: add support for role icons

- src/structures/Webhook.js
- typings/index.d.ts
The [`source_channel`](https://discord.com/developers/docs/resources/webhook#webhook-object-webhook-structure) is:
> the channel that this webhook is following (returned for Channel Follower Webhooks)
This is only ever going to be a `NewsChannel`.
> types(Webhook): More accurate type for `sourceChannel`

- src/managers/GuildBanManager.js
- typings/index.d.ts
This PR fixes the types and docs for GuildBanManager#remove which can return null
> types(GuildBanManager): remove can return null

- src/structures/VoiceState.js
This fixes a regression from #6694: Discord sends `self_stream`, not `self_streaming`. This resulted in this property always being `null`.
> fix(VoiceState): Patch streaming value

- src/client/actions/GuildMemberUpdate.js
This PR simply removes a line in the Client#guildMemberUpdate event that said the event would fire for updates in the user object, which is not true and cannot be fixed in a semver minor way, as it would require the userUpdate event to not be emitted with this event. See the the [discussion on Discord](https://canary.discord.com/channels/222078108977594368/682166281826598932/894293511522897960) for more info on this
> docs(GuildMemberUpdateAction): event doesn't get emitted on user update

- src/client/actions/GuildMemberUpdate.js
- src/client/actions/PresenceUpdate.js
- src/structures/User.js
- typings/index.d.ts
This PR compares the users' flags in User#equals. I had to create a new _equals method to be used in actions as these compare a user object with an API user, which does not have the same properties as a Discord.js User and thus would always return false when used this way. This wasn't necessarily needed as the user update action compares 2 User objects, but it's better than having broken code. Alternatively we can drop the checks on the GuildMemberUpdate and PresenceUpdate actions and this function won't be needed, let me know what you prefer
- I know how to update typings and have done …
> fix(User): compare flags in #equals

- typings/index.d.ts
With https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/, we'll eventually run into a name conflict between the built-in `Awaited<T>` type, and our type.
This PR fixes the conflict by renaming our type to `Awaitable<T>`
> types: rename `Awaited<T>` to `Awaitable<T>`

- src/util/Constants.js
- typings/index.d.ts
The user banner update added two new image sizes — 300 and 600. These new sizes work for all images, including guild icons, user avatars, and user banners.
> fix(AllowedImageSizes): add new image sizes

- src/errors/Messages.js
- src/structures/User.js
- typings/index.d.ts
This PR changes the accentColor and banner properties in User to default to undefined when they're not present in the payload since they need to be force-fetched for the client to receive them. I'm doing this because these properties can actually be null after being fetched (meaning they're not present) and that would make it hard to tell those two scenarios apart. To go along with these changes I also made hexAccentColor return accentColor when this is falsy (so either null or undefined, to avoid duplicating code) and made User#bannerURL throw an error when being called before the user is fetched. Despite the new error, this should not be semver major as these properties are not live on stable yet.
**Status and …
> refactor(User): set accentColor and banner to undefined when not yet received

- src/structures/interfaces/InteractionResponses.js
Users often get confused when trying to get a message from `CommandInteraction#reply`, as per default the returned Promise resolved with a void value. 
This PR clarifies this with an infobox as well as example code. To not overload the first example, the embed usage moved into the second example, together with the `ephemeral` option, providing an alternative non-empty message to `content`. 
> docs: fetchReply info + example

- src/structures/MessagePayload.js
There is a typo - the missing "h". Changes `wether` to `whether`.
> docs(MessagePayload): change the typo of "wether" to "whether"

- src/managers/GuildChannelManager.js
- src/managers/RoleManager.js
This PR fixes a stupid oversight introduced in #6875 where guild IDs were incorrectly accessed through the manager instead of through the guild. My bad!
> fix: correctly access guild IDs inside managers

- typings/index.d.ts
This PR improves the return type of the toJSON() method for the MessageActionRow, MessageButton, MessageEmbed and MessageSelectMenu classes. Also added the API type as a valid type for the constructor of all of those classes except MessageEmbed, which already supported this. This makes the types in line with the documentation which already had the return types documented this way. There are plenty other toJSON methods on the library that still return unknown but I decided not to touch those as those do not return API objects, instead returning an object representation of the class, which would require countless interfaces to be made.
- Code changes have been tested against …
> types: improve toJSON methods for message components & embeds

- src/structures/MessageEmbed.js
This PR removes proxy_url, height and width comparisons in all image related fields in embeds for the #equals method as the library does not set these values (they get ignored by the API), making it impossible to compare a local embed with an embed received from the API.
> fix(MessageEmbed): only compare image urls in #equals

- src/client/actions/MessageCreate.js
- src/client/actions/MessageDelete.js
- src/client/actions/MessageDeleteBulk.js
- src/client/actions/MessageReactionAdd.js
- src/client/actions/MessageReactionRemove.js
- src/client/actions/MessageReactionRemoveAll.js
- src/client/actions/MessageReactionRemoveEmoji.js
- src/client/actions/MessageUpdate.js
- src/client/actions/TypingStart.js
This PR ensures that message related actions take place in a channel that is supported to avoid throwing an unhandled exceptions. (Read: text in voice, also future-proofing)
Changed actions:
- MessageCreate
- MessageDelete
- MessageReactionAdd
- MessageReactionRemove
- MessageReactionRemoveAll
- MessageReactionRemoveEmoji
- MessageUpdate
- TypingStart
The reaction actions previously were ensuring that the action was not taking place in a voice channel (as per type) and the typing start action in a text channel (as per type).
I went with `Channel#isText` since it seems to be the less error-prone method to check whether messages can be accessed in said channel, since it's just `return 'messages' in this`.
**Status …
> fix: assert channel types in message actions

- src/util/UserFlags.js
- typings/index.d.ts
Adds the `BOT_HTTP_INTERACTIONS` user flag, which removes the offline status indicator for bots that only use interactions over HTTP in the client.
- https://github.com/Discord-Datamining/Discord-Datamining/commit/816e51e609e7baf0f34b2bf23d5dc4c00479a9b1#commitcomment-57376404
- https://github.com/discord/discord-api-docs/pull/3903
> feature(UserFlags): add BOT_HTTP_INTERACTIONS

- src/client/websocket/handlers/APPLICATION_COMMAND_CREATE.js
- src/client/websocket/handlers/APPLICATION_COMMAND_DELETE.js
- src/client/websocket/handlers/APPLICATION_COMMAND_UPDATE.js
- src/util/Constants.js
- typings/index.d.ts
Deprecated the application command events as Discord no longer emits them.
I've linked the issue on Discord's GitHub issue tracker for more information in the deprecation warning.
> refactor: Deprecate application command events

- src/util/SystemChannelFlags.js
- typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/3977
> feat(SystemChannelFlags): add new flag

- src/structures/ApplicationCommand.js
- typings/index.d.ts
Adds support for number and int types max and min values
- https://github.com/discord/discord-api-docs/pull/3967
Typings are not yet updated due to a potential issue with choices and min / max that I will be noting upstream
> feat(ApplicationCommand): add support for min and max values

- src/structures/MessageReaction.js
It is inconsistent that I am not cached in `ReactionUserManager` when `MessageReaction#me` is `true`.
So when I create a `ReactionUserManager`, I cache myself.
> fix(MessageReaction): Cache myself when `MessageReaction#me` is `true`.

- typings/index.d.ts
- typings/tests.ts
Fixes a nasty type bug where fallback types weren't properly being populated.
Closes #6960 
> types: fix cache type fallback types

- typings/index.d.ts
- typings/tests.ts
Prevents combinations where `choices` and `autocomplete` are present, and instead makes them mutually exclusive props on `ApplicationCommandOptionData`.
> types: Strengthen autocomplete option types

- src/rest/APIRequest.js
- src/structures/MessageAttachment.js
- src/structures/MessagePayload.js
- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
This adds the description property to the MessageAttachment class which is used for alt text added in the client (just added in the latest build but behind an experiment)
- https://github.com/discord/discord-api-docs/pull/3860
> feat(MessageAttachment): description (alt text) support

- src/structures/MessageEmbed.js
- typings/index.d.ts
As described in #6963, accessing the last parameter when one did not need the parameter before led to an ungraceful situation. This pull request resolves #6963.
> refactor(MessageEmbed): Utilise an object approach for `.setAuthor()`

- typings/index.d.ts
- Removes unnecessary `& this`'s for interaction typeguards. With the introduction of generic interaction classes in #6668, these are not needed anymore.
- Added `in*Guild` typeguards in all interaction classes that didn't have it already, this way you won't get `MessageComponentInteraction<"cached"> & ButtonInteraction<CacheType>` anymore for example.
- In the `AutocompleteInteraction` typeguards, `CommandInteraction` was accessed for some reason. This PR fixes that too.
> types: fix interaction typeguards

- typings/index.d.ts
- typings/tests.ts
> types(ApplicationSubcommandData): allow `autocomplete` to be `true`

- src/structures/VoiceState.js
This PR fixes #6967 by checking for a different property (so partial updates, in case those happen, don't incorrectly clear it).
There is no reason I chose `self_video` over the others.
I added a comment explaining why it's done like that.
> fix(VoiceState): set streaming to false when the stream ended

- src/sharding/Shard.js
- src/sharding/ShardClientUtil.js
This PR fixes that an error occuring in `fetchClientValues` would be uncatachable and fatal when it should be propagated back to the caller. (Be that through `ShardClientValues#fetchClientValues` or `Shard#fetchClientValues`)
`ShardClientUtil#fetchClientValues` already was able to do this; No changes were required here.
`Shard#fetchClientValues` however wasn't.
As well as `ShardClientUtil#_handleMessage` which wouldn't try/catch at all here.
Fixes #6946 
> fix(Sharding): properly handle errors in fetchClientValues

- src/managers/ThreadManager.js
- src/structures/Message.js
- typings/index.d.ts
Allows newly created threads to specify the amount of time a user has to wait before sending a consecutive message.
- https://github.com/discord/discord-api-docs/commit/d56be860c5dd4c04e80337556d82eb3a04f971a2
> feat(ThreadManager): add slowmode option on thread creation

- src/structures/Message.js
- src/structures/ThreadChannel.js
- typings/index.d.ts
> feat(ThreadChannel): add `ThreadChannel#viewable`

- typings/index.d.ts
- typings/tests.ts
Uses mapped types instead of manually declaring them twice within each class that extends `EventEmitter`. Similar to what `Client` already does for its events. 
> types: make event emitters use mapped event types

- src/util/Constants.js
Fixes the typo "ANNOUCEMENT" to "ANNOUNCEMENT". The actual APIError has the correct spelling, just the docs that have a typo.
> docs(Constants): fix typo "announcement"

- src/sharding/Shard.js
- typings/index.d.ts
Adds a context parameter to Shard#eval.
> feat(Shard): add eval context

- src/structures/Message.js
- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
This PR removes the ability to send stickers in webhook messages from the docs and the types as this is not resolved by Discord and results in an empty message when sent with nothing else.
> types(WebhookMessageOptions): disallow stickers

- src/structures/AutocompleteInteraction.js
- src/structures/Webhook.js
- src/structures/interfaces/InteractionResponses.js
This PR changes requests that use a token to authorize themselves to not use bot auth (Authorization header).
See: https://github.com/discord/discord-api-docs/issues/4142 (this might be fixed on Discord's end, but definitely can't hurt to be fixed here [too])
> fix: avoid sending bot auth on token endpoints

- src/structures/Guild.js
- src/structures/MessageEmbed.js
- src/structures/VoiceChannel.js
- src/structures/Webhook.js
- src/util/Util.js
This pull request emits deprecation warnings to deprecated parts of the library.
This was not done for `MessageEmbed#type` as that was just a property (though it could technically be made into a getter?) and the application events that don't emit at all.
> chore: Emit deprecation messages

- src/managers/MessageManager.js
- typings/index.d.ts
Well, `MessageManager#edit()`'s second parameter is not documented nor typed to take a string when it is possible and is already being done by the library.
> fix(MessageManager): Allow a string for `edit()`

- src/structures/MessagePayload.js
When passing `attachments: []` to `MessageOptions` and no `files` (to clear all attachments in a message edit), this code would result on the following logic to be executed:
```javascript
const attachments = this.options.files?.map((file, index) => ({
id: index.toString(),
description: file.description,
}));
if (Array.isArray(this.options.attachments) /* true */) {
this.options.attachments.push(...attachments /* undefined */);
} else {
this.options.attachments = attachments;
}
```
When spreading `undefined`, a `TypeError` is thrown with the message `undefined is not iterable (cannot read property undefined)` on Node.js v16.3.0.
Defaulting attachments to an empty array in that branch resolves the issue with the …
> fix(MessagePayload): prevent spread of `undefined`

- src/managers/MessageManager.js
Fixes #6248
Tested with the following inputs, and all worked just fine:
- `message.react('<:CrowOfJudgement:697940233710338148>');`
- `message.react(':CrowOfJudgement:697940233710338148');`
- `message.react('CrowOfJudgement:697940233710338148');`
- `message.react('697940233710338148');`
- `message.react('😄');`
- `message.react('%F0%9F%98%84');`
- `message.react(message.guild.emojis.cache.first());`
- `message.react({ id: '697940233710338148' });`
- `message.react({ name: '😄' });`
The only case that didn't was passing an encoded emoji inside `{ name }`, since it gets `encodeURIComponent`'d twice:
- `message.react({ name: '%F0%9F%98%84' });`
However, this doesn't work in latest stable (13.3.1), so it's not breaking …
> fix(MessageManager): do not use `client.emojis`

- src/util/SnowflakeUtil.js
- src/util/Util.js
- typings/index.d.ts
Removes two unneeded private utilities (`Util.binaryToId` and `Util.idToBinary`) and increases the performance of `SnowflakeUtil.generate` and `SnowflakeUtil.deconstruct`:
| Iterations | Old `deconstruct` | New `deconstruct` |     Diff | Old `generate` | New `generate` |      Diff |
| :--------: | :---------------: | :---------------: | :------: | :------------: | :------------: | :-------: |
|    `10000` |           44.40ms |           26.15ms | **1.70** |        97.67ms |        14.64ms |  **6.67** |
|   `100000` |          400.57ms |          209.11ms | **1.92** |       746.16ms |        85.01ms |  **8.78** |
|  `1000000` |             3.68s |             2.07s | **1.78** |          7.72s |       479.30ms | …
> refactor(SnowflakeUtil): clean up utils and improve perf

- src/structures/Message.js
First of all, `{@link MessageFlags#FLAGS message flag})` is an invalid redirect as it's a static link. Instead of correcting it, I removed the extra description as it seemed to fit the others. Feel free to request changes to only correct the redirect instead.
> docs(MessageReference): Fix static link

- package-lock.json
- package.json
- tslint.json
- typings/index.d.ts
- typings/index.test-d.ts
This reverts commit 2c91c488e8d00444ec0a14049654cdb496f2e757.
> Revert "types(ApplicationCommandManager): Deprecate old `*Data` type …usages and allow camel cased dapi types to be used

- src/util/Util.js
`Util#discordSort` sorts Ids descending when the `rawPosition` is the same, which is consistent with `Role` sorting, but is not for `GuildChannel` sorting, which sorts Ids ascending
~~Note: I've been unable to test the changes nor some similar versions, due to issues as I mentioned [here](https://discord.com/channels/222078108977594368/682166281826598932/909663555312291920); I'm not sure what I'm doing wrong, as I've only modified the required files and this method, but it seems to break the entire `Util` exports
I've just decided to create this PR in the hopes that someone else with more experience can fix these mistakes~~
Issues resolved, …
> fix(Util): fix sorting for GuildChannels

- src/structures/Invite.js
This PR removes the main warn block on the Invite class and adds info blocks on individual properties specifying what methods need to be run in order to obtain them.
> docs(Invite): add info blocks for missing props

- src/managers/GuildManager.js
- src/structures/Guild.js
- typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/4001
This PR adds Discord's new feature: premium_progress_bar_enabled, which is only available on certain Guilds at the moment. Here's what it looks like:
And in the settings:
Upstream PR:
- None yet!
> feat(Guild): add premiumProgressbarEnabled

- src/structures/GuildChannel.js
When cloning channels, the default value for `position` is `this.position`, which is different to discord's positions (stored as `rawPosition`), which sometimes puts the new channel far off from the correct position, where `rawPosition` would be more reliable as it would send the same value discord uses.
> fix(GuildChannel): default to `this.rawPosition` in `clone()`

- typings/index.d.ts
Narrowing this type as it is present from guilds.
Note: Prettier modified the file elsewhere.
> types(Interaction): Narrow `memberPermissions`

- src/structures/ApplicationCommand.js
- src/structures/BaseGuild.js
- src/structures/Channel.js
- src/structures/Emoji.js
- src/structures/GuildAuditLogs.js
- src/structures/GuildPreview.js
- src/structures/Interaction.js
- src/structures/Message.js
- src/structures/Role.js
- src/structures/StageInstance.js
- src/structures/Sticker.js
- src/structures/StickerPack.js
- src/structures/Team.js
- src/structures/User.js
- src/structures/Webhook.js
- src/structures/interfaces/Application.js
- src/structures/interfaces/TextBasedChannel.js
- src/util/SnowflakeUtil.js
- typings/index.d.ts
Also refactors anything using `SnowflakeUtil.deconstruct(id).timestamp` to use this new utility. This continues the work in #7036.
`SnowflakeUtil.timestampFrom` is a performance-focused utility designed to skip a lot of the decoder's overhead, as shown in the chart below:
| Iterations | `deconstruct(id).timestamp` | New `timestampFrom` |     Diff |
| :--------: | :-------------------------: | :-----------------: | :------: |
|    `10000` |                     36.08ms |              4.29ms | **8.41** |
|   `100000` |                    191.35ms |             31.97ms | **5.99** |
|  `1000000` |                       1.83s |            264.89ms | **6.91** |
In retrospective, the `deconstruct` method in main is almost …
> feat(SnowflakeUtil): add `timestampFrom`

- src/structures/ReactionCollector.js
`Message#channel` becomes `null` when the channel is deleted, so we cannot rely on it for handling channel deletions of a thread's parent. However, we can do the reverse and check whether the message's channel ID is a thread contained by the deleted channel.
Fixes #7066
> fix(ReactionCollector): check for channel.threads

- src/structures/InteractionCollector.js
Backports the thread (and thread parent) channel deletion from #6902 to `InteractionCollector` with the fixed checks from #7069.
Fixes #6905
> fix(InteractionCollector): handle thread (and parent) deletion

- src/structures/ApplicationCommand.js
- typings/index.d.ts
This PR adds 4 new methods to ApplicationCommand to make it easier to edit them. These are setName, setDescription, setDefaultPermission and setOptions. Although the edit method says that type conversions are supported, this does not seem to be the case when testing with the API so I decided not to add a setType method.
> feat(ApplicationCommand): add setX methods for easier editing

- typings/index.d.ts
- typings/index.test-d.ts
Marks `StoreChannel` and all methods to create new ones as deprecated in the typings, as per [Self-serve Game Selling Deprecation](https://support-dev.discord.com/hc/en-us/articles/4414590563479).
Probably fixes #6610?. This is semver-patch, and Discord might re-add the possibility of creating new store channels (or a workaround to do so), so I'm not removing the support just yet. We can remove the class and anything related to it as soon as Discord removes them.
> fix(StoreChannel): mark as deprecated

- src/managers/GuildStickerManager.js
The docs have improper examples and can result in confusion. The proper input for the `tags` parameter in `.create()` shouldnt take in a unicode emoji; as per Discord's docs and as indicated in the Discord.js docs itself in the tags description, the proper input should be the **string name** of a unicode emoji.
e.g. 🍌 should be "banana"
I was confused as to why when I would create a sticker, there would be no unicode emoji attached to it - until I read the actual discord docs and saw the error. With this fix in the docs, hopefully users - like me - won't become confused as to why there is no emoji representation of their sticker(s).
**What the discord.js docs promote:**
**What the actual input should be:**
**Status …
> docs(GuildStickerManager): fix create() example

- src/managers/GuildChannelManager.js
- src/structures/StoreChannel.js
- src/util/Constants.js
This PR continues the work started in #7072 by adding deprecation warnings to the docs and to GuildChannelManager#create when creating a store channel. Had to go slightly over the maximum length for the deprecation warning so if anyone has a suggestion that doesn't go over the limit I'll gladly replace it.
> docs(StoreChannel): add deprecation warnings

- src/client/websocket/WebSocketManager.js
- src/rest/RequestHandler.js
- src/sharding/Shard.js
- src/sharding/ShardingManager.js
- src/util/Util.js
- typings/index.d.ts
Similar to #7036, this PR removes `Util.delayFor` in favor of built-ins (`node:timers/promises` exports a promisified `setTimeout`, which we import as `sleep` to avoid ESLint issues and naming conflicts).
This PR is also not `semver: major` because `Util.delayFor` is marked as `@private`, despite the typings saying it's public.
> refactor(Util): replace `Util.delayFor` with `tp.setTimeout`

- src/sharding/ShardingManager.js
`Shard#respawn` takes `delay`, however, `ShardingManager#respawnAll` was passing `shardDelay`.
https://github.com/discordjs/discord.js/blob/25b84912351617f42de055ff0351286a0c9425da/src/sharding/Shard.js#L203
Also fixes the return type being keyed with strings when it's keyed with numbers (shard IDs).
> fix(ShardingManager): fix respawnAll not passing delay correctly

- src/structures/AnonymousGuild.js
- src/structures/Guild.js
This removes two methods from the `Guild` class that are inherited by `AnonymousGuild`, as well as fixing the parameter type there.
> refactor(Guild): remove duplicate methods

- typings/index.d.ts
- typings/index.test-d.ts
`<MessageComponentInteraction>.component` cannot be `null` and was addressed in #6835. However, #6867 reverted this.
I have also narrowed the received component structure if one already narrowed the interaction type to a `ButtonInteraction` or a `SelectMenuInteraction`. Previously, either of the two would yield either structures but now, they will yield their own structures.
> types(MessageComponentInteraction): Ensure `component` is not `null`

- src/structures/GuildAuditLogs.js
- src/structures/Invite.js
- typings/index.d.ts
The constructor shouldn't be utilising `Promise`s, so I've removed them by checking the cache and defaulting to creating an `Invite`.
`changes` also included `channel_id` & `inviter_id` which weren't being stored in the `Invite` class. I think this would be a loss if we don't expose that data as at least the developer can fetch the user/resolve the channel themselves as full objects are not sent across.
> fix(GuildAuditLog): Remove `Promise`s in constructor

- typings/index.d.ts
- typings/index.test-d.ts
This PR goes through and removes any places where manual overloads are being used instead of mapped types. It also slims down that amount of type-logic needed for these functions.
> types: use mapped enums instead of overloads

- src/managers/RoleManager.js
- src/structures/Role.js
- typings/index.d.ts
This moves the following methods to the manager:
- `comparePositions()`
- `delete()`
The `RoleManager` can manage the `delete()` API method.
As for `Role.comparePositions()`... not too sure why it's a static method on `Role` to be honest. It would make more sense for this to be moved to the manager. The manager stores the cache of roles, so I believe this method may reside here nicely. It's also no longer a static method and accepts `RoleResolvable`s.
```JavaScript
// client is a Client
const guild = client.guilds.resolve("guild_id");
const role1 = guild.roles.resolve("role_id1");
const role2 = guild.roles.resolve("role_id2");
// Old way of using the method
const { Role } = require("discord.js"); …
```
> refactor(RoleManager): Move some methods over from Role

- src/structures/Message.js
Fixes an oversight from #7107 that I noticed while rebasing #7092.
> fix(Message): remove usage of `.deleted`

- typings/index.d.ts
- typings/index.test-d.ts
These properties are typed as possibly `null`, but this is not the case. A component is received from a message and is returned in all cases as well as a message context menu interaction is received from a message and is returned in all cases.
> types: Fix possibly `null` message properties

- src/client/Client.js
- src/util/Constants.js
- src/util/LimitedCollection.js
- src/util/Options.js
- src/util/Sweepers.js
- src/util/Util.js
- typings/index.d.ts
<div align="center">
| ⚠️ This is tested, but not all combinations of sweepers have been validated. |
| - |
</div>
- This aims to tackle point 2 in  #6539: Global Sweepers. This does not completely satisfy what was outlined there however, it still relies on `LimitedCollection` to provide max size functionality. After doing the work to get to this point, that seemed out of scope, and can easily be tackled in another PR. This does mean that you are still storing extra properties on LimitedCollection for now, however hopefully not tracking a timeout.
In order to keep this semver: minor, default options have unfortunately <strong>not</strong> been switched to use the sweepers in this PR. …
> feat(Client): add global sweepers

- src/managers/GuildMemberManager.js
To edit the client's nickname in a guild, it was using [this path](https://discord.com/developers/docs/resources/guild#modify-current-user-nick) which has been marked as deprecated. The correct path to use is right above it.
> chore(GuildMemberManager): Update nick path

- typings/index.d.ts
- typings/index.test-d.ts
Fixes an issue where filters couldn't use the cached/raw variants in as an argument type.
> types: forward cache types to collector filters

- src/structures/Webhook.js
Fixes the typeguards on webhook objects giving false negatives because it was compared against numbers instead of strings.
> fix: webhook typeguards should use string comparisons

- src/structures/StickerPack.js
- typings/index.d.ts
The Snowsgiving Surprise Pack does not have a `banner_asset_id`, so this is `undefined`. Was also just documented as such:
- https://github.com/discord/discord-api-docs/pull/4245
> fix(StickerPack): Nullify `bannerId`

- typings/index.d.ts
- typings/index.test-d.ts
Brings a new set of strict channel types based on @ImRodry's typeguards from #6957. This change also makes sure that the set of possible channel types are strict, explicit, and matching the actual classes obtained during runtime.
> types: make channel types a lot stricter

- src/structures/interfaces/InteractionResponses.js
If a followUp is called when no interaction is deferred or replied will give a better error than "Unknown Webhook" 
> fix: Make the followUp function error more clear

- typings/index.d.ts
- typings/index.test-d.ts
Fixes issue where if `type` isn't explicitly set in the options the return type wouldn't be a text channel.
> types(CategoryChannel): `createChannel` should default to a text channel

- src/managers/UserManager.js
- src/structures/GuildMember.js
- src/structures/User.js
- typings/index.d.ts
This moves the following methods to the manager:
- `createDM()`
- `deleteDM()`
- `fetchFlags()`
The `send()` method is also on the manager.
The `User` class isn't needed for these requests which in turn only made these possible via doing:
```JavaScript
<Client>.users.fetch("user_id").then(async user => {
const dmChannel = await user.createDM();
// ...
});
```
But now, only one API call will be made:
```JavaScript
<Client>.users.createDM("user_id").then(dmChannel => {
// ...
});
```
A nice change from this is the `send()` method on the manager. To send a message to an uncached user, you would first have to fetch them (`UserManager#fetch()`) and then run `User#send()` which internally calls `User#createDM()`. That's …
> refactor(UserManager): Move methods to the manager

- src/managers/GuildMemberManager.js
- src/structures/BaseGuildVoiceChannel.js
- src/structures/GuildChannel.js
- src/structures/GuildMember.js
- src/structures/Message.js
- src/structures/ThreadChannel.js
- src/structures/VoiceChannel.js
- src/util/Permissions.js
- typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/4075
- Typings have been updated
- This pull request changes the library's interface
> feat(GuildMember): Add timeouts

- src/structures/BaseMessageComponent.js
Feel free to give the PR a better title as I didn't know what to call this but this basically resolves #7139 by returning the component instance in BaseMessageComponent#create when the received data is already a discord.js class
> fix(BaseMessageComponent): don't create new class instances

- typings/index.d.ts
- typings/index.test-d.ts
This PR fixes the return type of CategoryChannel#createChannel (regression from #7132 and #7088)
> types(CategoryChannel): fix createChannel return type

- src/util/Util.js
- typings/index.d.ts
> fix: Remove deprecation warning on `Message#cleanContent`

- src/util/Permissions.js
- typings/index.d.ts
When a member is an administrator, he does have all permissions but it's still possible to add/remove other permissions. Although it doesn't have any effect, the bitfield is still different and the `toArray()` method should return the permissions of the bitfield.
This can be done by passing `false` to the `toArray()` call.
This change also resolves #6267, which seems a regression added in #5911.
I've also considered defaulting the `checkAdmin` parameter to false in `Permissions#toArray()` but it would be inconsistent with other methods and useless as I don't see any use case where an array with all the flags is needed for an administrator and could be confused with a person with really every permission.
**Status …
> fix(Permissions): toArray shouldn't check admin

- src/managers/GuildMemberManager.js
#7104 introduced a regression to `Guild#me#setNickname` since `communication_disabled_until` is always added to `_data`, even if `communicationDisabledUntil` is `undefined`. Due to this `Object.keys(_data).length` will be 2 and the check in line 272/274 won't add `@me` to the endpoint.
> fix(GuildMemberManager): nick endpoint

- src/structures/GuildMember.js
- typings/index.d.ts
> feat(GuildMember): add method to check timeout

- src/structures/MessageEmbed.js
- typings/index.d.ts
Due to #7067, `setAuthor()` and `setFooter()` should only passing objects and not strings as per the builder's implementation. This pull request deprecates the passing of strings.
> refactor(MessageEmbed): Deprecate strings for `setAuthor()` (completely) and `setFooter()`

- src/util/Sweepers.js
This fixes the typo "hvae" to "have" and removes an extra space which were both introduced in [#6825](https://github.com/discordjs/discord.js/pull/6825).
> docs(Sweepers): fix typo

- packages/discord.js/src/managers/GuildChannelManager.js
- packages/discord.js/src/managers/RoleManager.js
- packages/discord.js/src/structures/Guild.js
- packages/discord.js/typings/index.d.ts
Removes the methods that were deprecated in #6875
> refactor(Guild): remove deprecated setXPositions methods

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
GitHub issue form changes to fit the new mono repository structure. You can test the new workflow by creating (but not submitting (thanks)) an issue on my fork https://github.com/almostSouji/discord.js
- add `No Intents` for issues unrelated to intents
- add selects to reflect "not applicable" for intents and partials (for subpackage issues/bug reports)
- rephrase to be package agnostic
> chore: issue template changes for monorepo

- packages/discord.js/src/managers/RoleManager.js
This PR fixes the example provided in `RoleManger#delete()` where `deleted` is used as a `Role` when it is `undefined`
> docs(RoleManager): fix incorrect example

- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
> types: fix cache types resolving to `never`

- packages/discord.js/src/structures/interfaces/TextBasedChannel.js
> docs(TextBasedChannel): fixed syntax error in examples

- packages/discord.js/src/structures/interfaces/Collector.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
Fixes #4139 by yielding an array of all the parameters received from the `collect` event.
> feat(Collector): yield all collected values

- packages/discord.js/src/client/Client.js
- packages/discord.js/src/client/actions/ChannelDelete.js
- packages/discord.js/src/client/actions/GuildDelete.js
- packages/discord.js/src/structures/Guild.js
- packages/discord.js/src/util/Options.js
- packages/discord.js/typings/index.d.ts
This removes a map on `ChannelDelete` and `GuildDelete` actions which keeps track of the deleted guilds. This can be circumvented by not calling the handle method in the method and relying on the websocket event instead. I'm unsure if this will break anything, however from my testing everything still works as expected.
> refactor(Actions): remove deleted maps

- packages/collection/src/index.ts
`intersect` and `difference` can now accept collections with different value types.
> types(Collection): union types on `intersect` and `difference`

- packages/discord.js/src/client/Client.js
- packages/discord.js/src/managers/CachedManager.js
- packages/discord.js/src/managers/ChannelManager.js
- packages/discord.js/src/managers/GuildChannelManager.js
- packages/discord.js/src/util/Constants.js
- packages/discord.js/src/util/LimitedCollection.js
- packages/discord.js/src/util/Options.js
- packages/discord.js/src/util/Util.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
The semver:major half of #6825 
> chore(Caching): clean up deprecated cache sweeping

- packages/discord.js/src/structures/User.js
- packages/discord.js/typings/index.d.ts
Makes `User#bannerURL` not throw even if the user hasn't been forced fetched, it will just return `undefined`. (breaking change)
> fix(User): `bannerURL()` should not throw when not present

- packages/discord.js/src/client/websocket/handlers/index.js
* #6492
After above pull request, all handlers related to application command have been completely removed.
This PR remove the remaining codes that handles removed event.
> fix(WebSocket): Remove application command handler

- .github/workflows/documentation.yml
#7175 tweaked the documentation CI which now requires the DJS_DOCS secret, which obviously doesn't exist on forks and thus causes the action to fail there. Despite not breaking anything on the main repo, this is a bit annoying for contributors so it's just a small QOL change to address that.
No other CI *needs* this fix since none of them fails without the required tokens but I could add them to prevent them from running if you wish
> ci(documentation): add repository_owner check

- packages/discord.js/src/structures/Presence.js
Added support for YouTube image URLs, and custom URLs in rich presence images similar to how the client does it.
You can now set the rich presence images as custom URLs which are prefixed with mp:
> feat(RichPresenceAssets): add YouTube and custom image support

- packages/discord.js/src/client/Client.js
- packages/discord.js/src/client/websocket/WebSocketManager.js
- packages/discord.js/src/client/websocket/handlers/CHANNEL_PINS_UPDATE.js
- packages/discord.js/src/rest/RequestHandler.js
- packages/discord.js/src/structures/BaseGuildTextChannel.js
- packages/discord.js/src/structures/DMChannel.js
- packages/discord.js/src/structures/Guild.js
- packages/discord.js/src/structures/GuildMember.js
- packages/discord.js/src/structures/GuildTemplate.js
- packages/discord.js/src/structures/Invite.js
- packages/discord.js/src/structures/Message.js
- packages/discord.js/src/structures/MessageEmbed.js
- packages/discord.js/src/structures/Presence.js
- packages/discord.js/src/structures/ThreadChannel.js
- packages/discord.js/src/structures/ThreadMember.js
- packages/discord.js/src/structures/VoiceState.js
- packages/discord.js/src/structures/interfaces/TextBasedChannel.js
- packages/discord.js/typings/index.d.ts
- `Client#readyAt`, `GuildTemplate#createdAt` and `GuildTemplate#updatedAt` are now getters as opposed to their timestamp counterparts which are now properties
- Change from `new Date(x).getTime()` to `Date.parse(x)` where applicable for improved performance
- Fixed the timestamp property on the result of `MessageEmbed#toJSON` which was a `Date` instance and not a string
- Consistent implementation of date getters
- Code changes have been (partially) tested against the Discord API
> refactor(Dates): save timestamps everywhere and use Date.parse

- packages/discord.js/src/managers/ThreadManager.js
- packages/discord.js/src/managers/ThreadMemberManager.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
@Jiralite pointed out this one out
> chore(ThreadMemberManager): make `#fetch` only take one object parameter

- packages/discord.js/src/client/actions/MessageCreate.js
- packages/discord.js/test/tester2000.js
- packages/discord.js/typings/index.d.ts
First(?) semver major PR ready for v14 -- removes the deprecated client `message` event.
> refactor(MessageCreate): remove message event

- packages/discord.js/src/client/actions/InteractionCreate.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
Akin to #6324, removes the deprecated client `interaction` event.
> refactor(InteractionCreate): remove interaction event

- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
#7197 didn't update the typings for some of the renamed typeguards
> types(interaction): remove renamed typeguards

- packages/discord.js/src/structures/GuildMember.js
This PR improves the error thrown on GuildMember#kickable and #bannable for when ClientUser's member object isn't cached.
> refactor(GuildMember): throw better errors on #kickable and #bannable

- packages/discord.js/src/structures/MessageEmbed.js
* #7108
After above PR, `createdAt` field can be a number 0. It will result in an error since `Number` class doesn't have `toISOString` method.
This PR changes the value of `timestamp` field, to deal with number zero.
> fix(MessageEmbed): createdAt field can be zero

- packages/builders/src/interactions/slashCommands/SlashCommandSubcommands.ts
This PR changes the old Discord developer portal link `interactions/slash-commands` to the new page `interactions/application-commands`.
> docs(SlashCommandSubcommands): updating old links from Discord developer portal

- packages/rest/LICENSE
The `@discordjs/rest` module has an Apache-2.0 license in the package.json, so I created it. I'm not sure exactly who I was supposed to put in there for copyright, so I took the license from the collection package.
> chore: license for REST module

- packages/discord.js/tsconfig.json
- tsconfig.json
`skipLibCheck` needs to be false in discord.js.
> chore: allow typescript to typecheck .d.ts files

- packages/discord.js/src/structures/MessagePayload.js
Just like in #7140, this PR avoids creating new MessageEmbed instances when sending a message if the given embed is already a MessageEmbed object
> refactor(embeds): don't create new embed instances when unnecessary

- packages/discord.js/src/managers/GuildMemberManager.js
- packages/discord.js/src/structures/MessageEmbed.js
For some reason, @kyranet's suggestion in #7218 was ignored so this PR fixes all instances where timestamps could be 0 on the library. I had to disable the eqeqeq rule for this in order to check for null and undefined timestamps but if you have a better idea please let me know.
Note about the change on the GuildMemberManager file: Discord throws an error when passing a timestamp that is more than 28 days in the past or the future, however, without this fix you'd be able to pass 0 and get no error, as the API would treat that as null which ends up doing the same thing but is not exactly the expected behavior. With this fix, we transform every timestamp into an ISO string and let Discord error when it should. I'll …
> fix(timestamps): account for timestamps of 0 when creating Dates

- package.json
- packages/rest/package.json
- packages/voice/package.json
- yarn.lock
The `rest` package is the only one which requires the build script to run before testing or linting.
This changes the Turborepo pipeline to avoid running `build` to test/lint packages that don't require it.
Also, 2 unrelated formatting errors in the `test` scripts.
> chore: optimize Turbo pipelines

- .github/COMMIT_CONVENTION.md
After monorepo setup, commit scope name casing was changed to lowercase. But in [Commit_Convension](https://github.com/discordjs/discord.js/blob/main/.github/COMMIT_CONVENTION.md) page, the example is in Pascal case. So I changed the example 
> chore: commit scope name in lowercase

- packages/rest/__tests__/REST.test.ts
- packages/rest/src/lib/RequestManager.ts
The data for a file is directly appended to formdata, which accepts a multitude of types, not just a buffer, this corrects the types and changes the name of the property accordingly (not every single stream type is covered, but it is the natively supported set)
> refactor(files): file data can be much more than buffer

- packages/discord.js/src/sharding/Shard.js
- packages/discord.js/src/sharding/ShardClientUtil.js
- packages/discord.js/typings/index.d.ts
Attaching a message listener to the parent and child during the broadcastEval and fetchClientVlaues throws a `MaxListenersExceededWarning:`
ErrorLog: https://sourceb.in/GBCHPCxLr5
The above changes were tested for 24 hours+ and it fixed the warning for all of my shards.
Code changes have been tested against the Discord API, or there are no code changes
This PR changes the library's interface (methods or parameters added)
> fix(Shard): EventEmitter listener warning

- packages/discord.js/src/client/actions/PresenceUpdate.js
- packages/voice/src/util/demuxProbe.ts
In the `PresenceUpdate#handle` there are **null** checks at lines 9 and 12. It's redundant since at line 8 the `id` is accessed from `data.user` without any null check.
In the `demuxProbe` function, Execution falls through after this Promise 'reject' call. So adding a return statement after the reject to stop unintended code execution.
> refactor: PresenceUpdate and demuxProbe

- packages/discord.js/src/structures/interfaces/Application.js
- packages/discord.js/src/util/Constants.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
Unsupported endpoints 🚮
Resolves discordjs/discord-api-types#292
> refactor(application): remove fetchAssets

- packages/builders/__tests__/components/actionRow.test.ts
- packages/builders/__tests__/components/button.test.ts
- packages/builders/__tests__/components/selectMenu.test.ts
- packages/builders/src/components/ActionRow.ts
- packages/builders/src/components/Assertions.ts
- packages/builders/src/components/Button.ts
- packages/builders/src/components/Component.ts
- packages/builders/src/components/Components.ts
- packages/builders/src/components/selectMenu/SelectMenu.ts
- packages/builders/src/components/selectMenu/SelectMenuOption.ts
- packages/builders/src/index.ts
- yarn.lock
Adds all current component types to `/builders`.
> feat: add components to /builders

- packages/discord.js/.eslintrc.json
Added the [`prefer-object-has-own`](https://eslint.org/docs/rules/prefer-object-has-own) rule.
> chore: Add `prefer-object-has-own` rule

- packages/discord.js/src/client/Client.js
- packages/discord.js/src/rest/RateLimitError.js
- packages/discord.js/src/rest/RequestHandler.js
- packages/discord.js/src/util/Options.js
- packages/rest/src/lib/REST.ts
This fixes the typo "recieved" to "received" and uses "milliseconds" instead of "ms" (only in docs).
> docs: fix a typo and use milliseconds instead of ms

- packages/discord.js/src/structures/interfaces/TextBasedChannel.js
This enables the `import/order` lint in `TextBasedChannel.js`, which should only be disabled for the last import.
> refactor: don't disable import order lint

- packages/discord.js/src/structures/Interaction.js
This PR adds a link to a list of all possible locales from Discord's documentation to Interaction#locale
> docs(interaction): add locale list link

- .github/workflows/auto-deprecate.yml
- .github/workflows/publish-dev.yml
#7205, but for the auto-deprecate and publish-dev workflows
I'm not sure why the publish-dev script is [failing on my fork](https://github.com/almeidx/discord.js/actions/runs/1704256979), but there's no reason for it to be run there anyway. The same goes for auto-deprecate
**Edit**: Just found out you can simply disable actions from running on forks. Went with that instead. Feel free to close this if you don't want changes to the workflows
> ci: dont run auto-deprecated and publish-dev on forks

- packages/discord.js/src/sharding/ShardingManager.js
As the default value suggests, it is an array of strings
> docs(shardingmanager): fix type of `execArgv` option

- packages/rest/src/lib/REST.ts
- packages/rest/src/lib/RequestManager.ts
- packages/rest/src/lib/handlers/IHandler.ts
- packages/rest/src/lib/handlers/SequentialHandler.ts
- packages/rest/src/lib/utils/constants.ts
See https://github.com/discordjs/discord.js-modules/issues/40
Sweeps hashes based on the lifetime of a given hash. Lifetimes are based on the last time a particular hash was used relative to the current data/time. In addition this sweeps inactive handlers.
This introduces new options for `REST`:
- `hashSweepInterval`: The delay before each hash sweep interval.
- `hashLifetime`: The maximum amount of time a hash can exist before being swept.
- `handlerSweepInterval`: The delay before each handler sweep interval …
> feat: rest hash and handler sweeping

- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
This PR fixes multiple regressions introduced in #7077 which made certain types unusable.
Note for the future: That PR also introduced a huge inconsistency in the usage of the <Enum>Key type and `keyof typeof` but I believe that's out of the scope of this PR and of much lower priority, so there's a free PR if anyone wants to take it
> types: fix regressions and inconsistencies

- packages/discord.js/src/structures/CommandInteractionOptionResolver.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
All other getX methods required is default to false. But for `subCommand` and `subCommandGroup` it's true.
`getSubCommand` have a valid reason that it's default to true because if there is no subCommand then why you are trying to get the value. But `getSubCommandGroup` is different.
Here's an example of how it's different,
```js
{
name: "name",
description: "description",
type: 1,
options: []
},
{
name: "name-group",
description: "description",
type: 2,
options: [
{
name: "name",
description: "description",
type: 1,
options: []
},
]
},
```
Here when a user uses `name` subCommand (1st one) and I try to check which `name` command was used, so I'll check `interaction.options.getSubCommandGroup()` first,  but it'll …
> refactor(subcommandgroup): required default to false

- packages/discord.js/src/client/BaseClient.js
- packages/discord.js/src/sharding/ShardClientUtil.js
- Currently, the Client class cannot properly handle async errors being 
thrown.
- With this change, when an error is thrown within an event, Client will
automatically emit an error event if a listener exists, or otherwise
exits with an unhandledRejection as it currently does..
```js
client.on('ready', () => console.log('ready'));
client.on('error', (e) => console.error(e.message)); // "whoops"
client.on('messageCreate', async (m) => {
// do some async task here that throws an error
// this will no longer exit the program with an
// unhandled rejection!
throw new Error('whoops');
});
```
https://nodejs.org/api/events.html#capture-rejections-of-promises
This is experimental, but a [PR](https://github.com/nodejs/node/commit/9a85efaa7f5f22c6905bf47d672dd73738787437) has already been …
> BaseClient: pass `captureRejections` option

- packages/discord.js/src/structures/Webhook.js
- packages/discord.js/typings/index.d.ts
Removes the boolean option for `Webhook#fetchMessage` as it is superseded by `WebhookFetchMessageOptions`.
> refactor: Remove boolean option for `Webhook#fetchMessage`

- packages/discord.js/src/structures/VoiceChannel.js
- packages/discord.js/typings/index.d.ts
Removes `VoiceChannel#editable` as it is superseded by `GuildChannel#manageable`.
> refactor: Remove VoiceChannel#editable

- .github/workflows/publish-dev.yml
This PR fixes a bug causing publish-dev workflows to fail when the targeted commit has been published already.
(Seems to have been introduced with e07c3743375e2bf4470818f6d20c269edce7b7a1)
> ci(publish-dev): only build dependencies when releasing

- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
There were issues with creating channels in TypeScript:
1. `<GuildChannelManager>.create()` always required two arguments
2. Hovering over `<GuildChannelManager>.create()` would always yield a deprecation notice, despite being none
3. `<GuildChannelManager>.create("name", {})` would not be a `TextChannel`
4. Only "GuildStore" and not the enumerable as well were being checked for in the deprecation notice
This pull request fixes those issues.
> types: Fix channel create overloads

- packages/rest/src/lib/RequestManager.ts
Adds logic to utilize http agent over https when the api in use is not https (local instance / local proxy)
Moves agent to be a class property in the event one instance of rest is using http and another is not.
> fix(rest): use http agent when protocol is not https

- packages/builders/src/messages/embed/Embed.ts
> refactor(embed): mark properties as readonly

- packages/discord.js/src/structures/MessageMentions.js
- packages/discord.js/typings/index.d.ts
Fixed typings to allow for other channel types other than TextBasedChannel in MessageMentions.channels, such as voice. Also removed DMChannels from those types, as you cannot mention a DMChannel - the ID of a DMChannel is the user's ID, which is only valid under a user mention.
**Status and versioning classification:** Patch
> types: fix MessageMentions channel types

- packages/discord.js/src/structures/ThreadChannel.js
- packages/discord.js/typings/index.d.ts
This also adds an `isPrivate` type guard for threads.
> feat(threadchannel): add `createdTimestamp` field

- packages/discord.js/src/structures/Webhook.js
- packages/discord.js/typings/index.d.ts
Add the `application_id` property to the Webhook class. It is available with the Discord API itself, however, it is not exposed in discord.js
**Status and versioning classification:** Minor
> feat(minor): add application_id to Webhook

- packages/rest/__tests__/REST.test.ts
- packages/rest/src/lib/RequestManager.ts
Removes the now redundant file descriptor in file properties (this ones on me)
> refactor(files): remove redundant file property names

- packages/discord.js/src/managers/GuildScheduledEventManager.js
- packages/discord.js/src/managers/StageInstanceManager.js
- packages/discord.js/src/managers/ThreadManager.js
- packages/discord.js/src/structures/ApplicationCommand.js
- packages/discord.js/src/structures/BaseGuildTextChannel.js
- packages/discord.js/src/structures/CategoryChannel.js
- packages/discord.js/src/structures/ContextMenuCommandInteraction.js
- packages/discord.js/src/structures/Guild.js
- packages/discord.js/src/structures/GuildScheduledEvent.js
- packages/discord.js/src/structures/InteractionCollector.js
- packages/discord.js/src/structures/Message.js
- packages/discord.js/src/structures/Sticker.js
- packages/discord.js/src/structures/ThreadChannel.js
- packages/discord.js/src/util/Constants.js
- packages/discord.js/src/util/EnumResolvers.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
Some typings are out of date and a few enums are still being converted to strings. I also `{@link}`ed the enums in the JSDocs, if you want me to revert that I will.
> fix: missed enums and typings from #7290

- packages/discord.js/src/structures/Guild.js
- packages/discord.js/src/structures/Interaction.js
Blame @advaith1 for moving this
Marking as a draft until the Discord API docs website has been updated with the new link, the commit has already been pushed on their repo though
- https://github.com/discord/discord-api-docs/pull/4335
> docs(locales): update Discord API docs link

- packages/builders/src/components/ActionRow.ts
- packages/builders/src/components/Components.ts
This PR makes it so that if a builders class is passed onto createComponent it is returned as-is, without creating a new instance of it so we can keep referencing it. Also changed types of ActionRow slightly to make it easier to type it
> fix: don't create new instances of builders classes

- packages/rest/src/lib/CDN.ts
- https://github.com/discord/discord-api-docs/pull/4380
> feat(cdn): add support for scheduled event image covers

- packages/discord.js/typings/index.d.ts
All properties in the `RESTOptions` have a default. Therefore it can be marked as `Partial`
> fix(typings): mark `RESTOptions` as Partial in `ClientOptions`

- packages/collection/__tests__/collection.test.ts
- packages/collection/src/index.ts
#7211 removes a use-case from `intersection`, so might as well just cover them all with `merge`.
Then `combineEntries` is basically `merge` but for a bunch of entries instead of two collections.
Prior art [here](https://hackage.haskell.org/package/containers-0.6.4.1/docs/Data-Map-Lazy.html#v:intersection) and [here](https://hackage.haskell.org/package/containers-0.6.4.1/docs/Data-Map-Merge-Lazy.html#v:merge) and [here](https://hackage.haskell.org/package/containers-0.6.4.1/docs/Data-Map-Lazy.html#v:fromListWith).
@suneettipirneni 
- I know how to update typings and have done so, or typings …
> feat(Collection): add merging functions

- packages/discord.js/src/client/Client.js
- packages/discord.js/src/structures/GuildScheduledEvent.js
- packages/discord.js/typings/index.d.ts
Adds `#image` and `#coverImageURL()` for getting the scheduled event cover image.
- https://github.com/discord/discord-api-docs/pull/4380
Depends on:
- https://github.com/discordjs/discord.js/pull/7298
> feat(scheduledevent): add support for event cover images

- packages/rest/__tests__/RequestHandler.test.ts
This could fix the flaky unit test issues for /rest.
> Also unlike Date.now(), the values returned by performance.now() always increase at a constant rate, independent of the system clock (which might be adjusted manually or skewed by software like NTP).
[Source](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now)
> chore: use `performance.now` for time-based unit tests

- packages/discord.js/src/structures/MessageMentions.js
- packages/discord.js/typings/index.d.ts
This PR corrects the logic of the MessageMentions#has method.
| Message    | User Mention | Role Mention | Channel Mention |
|------------|--------------|--------------|-----------------|
| <@id>      | true         | false        | false           |
| <@&id>     | true/false   | true         | false           |
| <#id>      | false        | false        | true            |
| @everyone  | true         | false        | false           |
| Reply | true/false   | false        | false           |
- This PR changes …
> fix(messagementions): fix `has` method

- packages/discord.js/src/structures/AutocompleteInteraction.js
- packages/discord.js/src/structures/CommandInteraction.js
- packages/discord.js/src/structures/ContextMenuCommandInteraction.js
- packages/discord.js/src/structures/Interaction.js
- packages/discord.js/typings/index.d.ts
Adds `CommandInteraction#commandType` and `AutocompleteInteraction#commandType` and removes `ContextMenuCommandInteraction#targetType`.
This PR moves `ContextMenuCommandInteraction#targetType` to `CommandInteraction#commandType` and introduces `AutocompleteInteraction#commandType` for forward-compatability.
> feat(`Interaction`): add `.commandType` property to `CommandInteraction` and `AutocompleteInteraction`

- packages/discord.js/src/structures/Channel.js
- packages/discord.js/typings/index.d.ts
This PR adds a new typeguard to Channel to ensure a channel is DM-based, aka it's either a DM or a group DM. Along with that, this also adds the GroupDM channel type to the PartialGroupDM class as that was previously missing
> feat(channel): add isDMBased typeguard

- packages/discord.js/typings/index.d.ts
This PR fixes the capitalization of *BitField.Flags properties from #7313, as well as their type (was missing `typeof` before the enum name)
> types: fix *BitField.Flags properties

- packages/discord.js/src/structures/Invite.js
- packages/discord.js/typings/index.d.ts
This PR makes Invite.channel a regular property again as PartialGroupDMChannels do not get cached, so it was impossible to obtain them. This also removes Invite#channelId as this is not documented on Discord's side and thus is not sent
> revert: refactor(invite): make `channel` a getter

- package.json
- turbo.json
- yarn.lock
Bumps turborepo to the latest version. This also makes some migration changes that turborepo needs for this update.
- turborepo pipeline JSON is now in it's own dedicated `turbo.json` file
- `packageManager` is now specified in the package.json
> chore: bump turborepo

- packages/builders/tsup.config.ts
- packages/rest/tsup.config.ts
- packages/voice/tsup.config.ts
Add the `keepNames` option to tsup configs to avoid errors or such to have a minified name like `D`.
> chore: add keepNames tsup option

- packages/builders/src/components/ActionRow.ts
- packages/builders/src/components/Button.ts
- packages/builders/src/components/selectMenu/SelectMenu.ts
Make property `type` in components constructor optional as it's not used by the class but just marked as constant.
I did a type intersection instead of using `Omit` because it caused problems with the Button class.
Close #7342
> fix(builders): make type optional in constructor

- packages/discord.js/src/structures/Message.js
- packages/discord.js/src/structures/MessageComponentInteraction.js
- packages/discord.js/src/structures/Webhook.js
- packages/discord.js/src/structures/interfaces/TextBasedChannel.js
Makes the docs links for builders in djs clickable.
> docs: add external builder docs links

- packages/builders/src/components/selectMenu/SelectMenu.ts
- packages/discord.js/typings/index.d.ts
- packages/rest/src/lib/handlers/SequentialHandler.ts
- packages/voice/src/networking/VoiceWebSocket.ts
Fixed some typos across the packages.
**NOTE: There are a couple of things that may break in some ways:**
- `sweepStageInstnaces` -> `sweepStageInstances` in typings; it was ok in the code so there shouldn't be any issues, at least for non-typescript users
- `lastHeatbeatSend` -> `lastHeartbeatSend`; is a private property and shouldn't be used
> fix: fix some typos

- packages/discord.js/src/client/actions/ThreadCreate.js
- packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/commit/1875d80011ea62bf555ce807459ccf97950291e9
> feat(thread): add `newlyCreated` to `threadCreate` event

- packages/discord.js/src/structures/MessageReaction.js
This fixes cases where the messageReaction.me is false when it shouldn't be.
fixes #7377 
Just a note I'm not sure if this is the right spot to pull to. Let me know if I messed this up.
> fix: messageReaction.me being false when it shouldn't

- packages/discord.js/src/index.js
- packages/discord.js/src/structures/BaseGuild.js
- packages/discord.js/src/structures/Guild.js
- packages/discord.js/src/structures/GuildPreview.js
- packages/discord.js/typings/index.d.ts
Removed the `GuildFeatures` type in favour of `GuildFeature` from discord-api-types
> types: use `GuildFeature` enum from `discord-api-types`

- packages/rest/__tests__/RequestHandler.test.ts
- packages/rest/src/lib/utils/utils.ts
A recent change to sublimits in Discord brought to light that unknown sublimits are not queued to the sublimit queue, which can cause a flood of 429s if not careful.
This PR fixes this by declaring any request that is being checked outside of known routes as sublimitted (only checked if you've actually hit a sublimit). Essentially we revert to the old behavior of stalling all requests on the route until we update the hasSublimit check to account for the route.
> fix(rest): sublimit all requests on unhandled routes

- packages/discord.js/src/structures/ApplicationCommand.js
- packages/discord.js/src/structures/CommandInteraction.js
- https://github.com/discord/discord-api-docs/pull/4318
This PR documents the supported option types for autocomplete.
> docs: add supported option types for autocomplete

- packages/discord.js/src/structures/MessageAttachment.js
Fixes `MessageAttachment#contentType` docs.
> docs(messageattachment): fix `contentType` docs

- packages/builders/src/components/Component.ts
- packages/builders/src/index.ts
- packages/builders/src/messages/embed/UnsafeEmbed.ts
- packages/builders/src/util/jsonEncodable.ts
Uses the unsafe field normalizer for unsafe embeds. Closes #7416
This also adds a new interface type: `JSONEncodable<T>`, for better type enforcement and reusability.
> fix: unsafe embed builder field normalization

- packages/discord.js/typings/index.d.ts
There is a duplicate interface for this. The other one is after it:
https://github.com/discordjs/discord.js/blob/b936103395121cb21a8c616f669ddab1d2efb0f1/packages/discord.js/typings/index.d.ts#L4224-L4227
Seems to have been introduced from #5318.
> types: Remove duplicate `GuildChannelOverwriteOptions` interface

- packages/discord.js/typings/index.d.ts
- `enforceOptionorder` -> `enforceOptionOrder` (as to match the atual function implementation parameter name)
- `regx` -> `regex` (same reason as above)
- `Sticket` -> `Sticker`
- `GUILD_SCHEDULED_EVENT_CREATE`, `GUILD_SCHEDULED_EVENT_UPDATE`, `GUILD_SCHEDULED_EVENT_DELETE` into pascal case, as to match the keys from discord-api-types (like the rest of the interface keys)
> types: fix `GuildAuditLogsTypes` keys & typos

- packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionWithChoicesAndAutocompleteMixin.ts
Remove conditional return types from autocomplete options. These did not work as intended.
> refactor: remove conditional autocomplete option return types

- packages/discord.js/src/structures/Channel.js
- packages/discord.js/src/structures/ThreadChannel.js
- packages/discord.js/typings/index.d.ts
This simply adds a `.url` getter on channels. This can be specifically useful when working with moving threads between 2 channels.
> feat(channel): add .url getter

- packages/discord.js/src/managers/GuildChannelManager.js
- packages/discord.js/src/managers/GuildEmojiManager.js
- packages/discord.js/src/managers/GuildStickerManager.js
- packages/discord.js/src/managers/RoleManager.js
- packages/discord.js/src/structures/BaseGuildTextChannel.js
- packages/discord.js/src/structures/GuildChannel.js
- packages/discord.js/src/structures/GuildEmoji.js
- packages/discord.js/src/structures/Role.js
- packages/discord.js/src/structures/Sticker.js
- packages/discord.js/src/structures/ThreadChannel.js
- packages/discord.js/typings/index.d.ts
This PR adds a bunch of methods to managers (without any intention to remove them from the structures of course). For some of these I had to use resolve instead of resolveId due to how the code works so if you believe this defeats the purpose of a manager method I can try refactoring or undoing some of those changes. This PR sort of continues the work from #7286 
> feat: add methods to managers

- packages/discord.js/src/managers/GuildChannelManager.js
oversight from #7300 
currently editing a GuildChannel without passing `parent` sets `parent_id` to `null`
> fix(guildchannelmanager): edit always sets parent to null

- packages/discord.js/src/managers/GuildScheduledEventManager.js
- packages/discord.js/typings/index.d.ts
According to the [API docs](https://discord.com/developers/docs/resources/guild-scheduled-event#create-guild-scheduled-event), on `Create Guild Scheduled Event` and `Modify Guild Scheduled Event` an optional field image `image` can be added
> feat(scheduledevents): add image option

- packages/discord.js/src/structures/Guild.js
The 25k default is no longer correct
- https://github.com/discord/discord-api-docs/pull/3145
- https://discord.com/channels/613425648685547541/697489244649816084/798701701540085812 (Discord Developers guild)
> fix(guild): remove `maximumPresences` default value

- packages/voice/__tests__/VoiceConnection.test.ts
- packages/voice/src/VoiceConnection.ts
This PR gets rid of a bug related to VoiceConnection groups introduced in [this PR](https://github.com/discordjs/voice/pull/147).
While `getVoiceConnection` takes second argument (`group`, defaults to `'default'`), in `createVoiceConnection` and `VoiceConnection.destroy()` it is called without `(this.)joinConfig.group`, ending up just trying to get VoiceConnection in 'default' group. This commit fixes this issue.
> voice: pass joinConfig.group to getVoiceConnection

- packages/discord.js/src/structures/GuildMember.js
Discord doesn't allow to timeout a member, which has administrator permission, even if he is manageable.
I added check to `guildMember.moderatable` which returns false if member has `Administrator` permission
> fix(guildmember): check if member has administrator permission

- packages/discord.js/src/managers/GuildBanManager.js
- packages/discord.js/src/managers/GuildInviteManager.js
- packages/discord.js/src/managers/GuildManager.js
- packages/discord.js/src/managers/GuildMemberManager.js
- packages/discord.js/src/managers/MessageManager.js
- packages/discord.js/src/structures/BaseGuildTextChannel.js
- packages/discord.js/src/structures/Message.js
- packages/discord.js/src/structures/interfaces/TextBasedChannel.js
This PR removes all defaults strictly defined in discord.js that were the exact same as the API ones. I left out some that didn't have documentation on Discord's side simply because I couldn't be bothered to test those, so I only removed the ones I'm 100% sure are redundant. Let me know if I missed any
> refactor!: remove redundant API defaults

- src/structures/MessageEmbed.js
If you set `embed.setFooter(null)` it set's footer to `{}`. When checking `MessageEmbed`.length, it checks `this.footer?.text.length`. In this case, footer is defined but footer.text isn't, so it'll throw an error `can't read property of undefined (reading length)`. 
In builder, it's correct, that's why after discussing in `library-discussion` I'm sending the pr in stable branch.
> fix(MessageEmbed): set footer to undefined

- packages/builders/__tests__/components/actionRow.test.ts
- packages/builders/__tests__/components/selectMenu.test.ts
- packages/builders/__tests__/messages/embed.test.ts
- packages/builders/babel.config.js
- packages/builders/src/components/ActionRow.ts
- packages/builders/src/components/Assertions.ts
- packages/builders/src/components/Component.ts
- packages/builders/src/components/Components.ts
- packages/builders/src/components/button/Button.ts
- packages/builders/src/components/button/UnsafeButton.ts
- packages/builders/src/components/selectMenu/SelectMenu.ts
- packages/builders/src/components/selectMenu/SelectMenuOption.ts
- packages/builders/src/components/selectMenu/UnsafeSelectMenu.ts
- packages/builders/src/components/selectMenu/UnsafeSelectMenuOption.ts
- packages/builders/src/messages/embed/Assertions.ts
- packages/builders/src/messages/embed/Embed.ts
- packages/builders/src/messages/embed/UnsafeEmbed.ts
- packages/discord.js/typings/index.test-d.ts
This is a replacement for the previous pr since gh is having trouble loading the diffs.
Stores raw api data in a `data` object and allows access to builder properties via getters.
There's quite a few benefits in using getters for builders:
- Currently builders relies on `Reflect#set` which is much slower than direct prop assignment, in one benchmark [I did it was waaay slower than direct assignment](https://www.measurethat.net/Benchmarks/ShowResult/263962). Beyond performance `Reflect#set` is less typesafe since property keys are strings and it allows values to be set as `any`. This PR removes the usage of these methods, and preserves the `readonly` nature of the fields.
- The classes are now more flexible. For …
> refactor: make public builder props getters

- packages/discord.js/src/managers/GuildBanManager.js
- packages/discord.js/src/managers/GuildMemberManager.js
- packages/discord.js/src/structures/GuildMember.js
- packages/discord.js/typings/index.d.ts
This PR renamed the `days` option in BanOptions to `deleteMessageDays` to be inline with the API name and to avoid confusion with users thinking it's a way to tempban people, which it's not. It also removes the default of 0 since that's handled by the API (not documented, but it is 0)
> refactor(guildbanmanager)!: rename days option to deleteMessageDays

- packages/rest/src/lib/RequestManager.ts
replaces the last occurrence of  `DiscordSnowflake.deconstruct().timestamp` with `DiscordSnowflake.timestampFrom()`
> refactor(requestmanager): use timestampfrom

- packages/discord.js/src/structures/AnonymousGuild.js
- packages/discord.js/src/structures/Guild.js
- packages/discord.js/typings/index.d.ts
Moved the `premiumSubscriptionCount` property from the `Guild` to the `AnonymousGuild` structure as it is only being used as a base for both the `Guild` and `InviteGuild` structures
- https://github.com/discord/discord-api-docs/pull/4493
> refactor(guild): move `premiumSubscriptionCount` to `AnonymousGuild`

- packages/discord.js/src/util/DataResolver.js
creating an emoji using a web URL is currently nonfunctional in `main` but working in `stable`.
`stable`->`main` removed `resolveFileAsBuffer` but `DataResolver.resolveBase64` still expected a Buffer,
and `resolveFile` provided a ReadableStream.
there's no reason to readd/reimplement that function since it only acted as an intermediary between those 2 other static methods, in this one specific case. so now `resolveFile` will directly return a Buffer, as the typing suggests it's supposed to.
> fix(dataresolver): ensure fetched file is convert to a buffer

- packages/rest/__tests__/REST.test.ts
- packages/rest/__tests__/RequestHandler.test.ts
- packages/rest/src/lib/utils/utils.ts
- `Response.buffer` is not a spec compliant method.
- Buffer only exists in node and it's just a wrapper for Uin8Arrays anyways.
- It's getting [removed](https://github.com/node-fetch/node-fetch/issues/1452) in v4, if its decided to stay with node-fetch and move towards ESM.
I have no idea if types need updating, sorry 😕 
> rest: prefer arrayBuffer over buffer

- packages/discord.js/typings/index.d.ts
The constructor already accepts these types:
https://github.com/discordjs/discord.js/blob/c1b27f8eed8ea04a48bc106453892bddcdc6b73e/packages/builders/src/messages/embed/UnsafeEmbed.ts#L44
(speaking of that line, it could use a logical assignment if anyone wants a free PR)
> types(embed): fix timestamp allowed types

- packages/discord.js/src/managers/CategoryChannelChildManager.js
- packages/discord.js/src/structures/CategoryChannel.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
This PR changes CategoryChannel#children to be a manager and moves CategoryChannel#createChannel to CategoryChannelChildManager#create. This allows for better organization and consistency with other methods in the library and also allows for easier expandability in the future
> feat!: add CategoryChannelChildManager

- packages/discord.js/src/structures/ApplicationCommand.js
Updated ApplicationCommandData documentation to add default value of `type`, that `description` only is used on CHAT_INPUT and that the name must be in all lowercase when used in a CHAT_INPUT
> docs: ApplicationCommandData typedef

- packages/discord.js/src/structures/MessagePayload.js
- packages/discord.js/src/util/Options.js
- packages/discord.js/typings/index.d.ts
The builder constructor json transformations can currently be opted out of if builders are imported from the external package. However there's currently no way to opt out of json transformation that occurs when djs sends outgoing requests. For example if a developer *always* uses snake_case for their json payloads the transformer is always used regardless if it's needed or not. 
With this PR they could avoid this with an identity function:
```ts
const client = new Client({ jsonTransformer: (obj) => obj });
```
This PR allows custom JSON transformer functions and adds an interface for controlling how json is transformed via a client option that takes a transform function.
- …
> feat(options): Add support for custom JSON transformers

- packages/builders/__tests__/components/actionRow.test.ts
- packages/builders/__tests__/components/button.test.ts
- packages/builders/__tests__/components/selectMenu.test.ts
- packages/builders/__tests__/messages/embed.test.ts
- packages/builders/package.json
- packages/builders/src/components/ActionRow.ts
- packages/builders/src/components/Component.ts
- packages/builders/src/components/button/UnsafeButton.ts
- packages/builders/src/components/selectMenu/UnsafeSelectMenu.ts
- packages/builders/src/messages/embed/Assertions.ts
- packages/builders/src/messages/embed/Embed.ts
- packages/builders/src/messages/embed/UnsafeEmbed.ts
- packages/builders/src/util/equatable.ts
- yarn.lock
Adds
- `Embed#hexColor`
- `#equals`
- Select menu allows objects to be passed in to `setOptions` and `addOptions` instead of exclusively just classes.
> feat: add missing `v13` component methods

- packages/discord.js/typings/index.d.ts
Doesn't seem like anything actually uses this type. It's basically just a copy of what it extends:
https://github.com/discordjs/discord.js/blob/dee27db35af379b0835f9fd5cc19563f7bf3dfc0/packages/discord.js/typings/index.d.ts#L770-L825
> types: Remove `ApplicationCommandInteractionOptionResolver`

- packages/builders/src/components/button/Button.ts
- packages/builders/src/components/button/UnsafeButton.ts
- packages/builders/src/components/selectMenu/SelectMenu.ts
- packages/builders/src/components/selectMenu/SelectMenuOption.ts
- packages/builders/src/components/selectMenu/UnsafeSelectMenu.ts
- packages/builders/src/components/selectMenu/UnsafeSelectMenuOption.ts
This PR brings #6279 back to builders
> refactor(components): default set boolean methods to true

- .commitlintrc.json
Commits may have many casings for the scope: RequestHandler for classes, `somethingHere` for others, and the rule enforced lowercased scopes by default. This PR disables the rule altogether
> chore: disable scope-case rule for commitlint

- packages/discord.js/src/structures/GuildPreview.js
- packages/discord.js/src/structures/Sticker.js
- packages/discord.js/typings/index.d.ts
- made all getters be typed correctly as getters - this improves typescript error messages and makes it clearer to the end-user that the value is calculated 
- remove `GuildChannel#calculatedPosition` from the typings since it doesn't exist in the source code
- corrected a few properties that should(n't) have been marked as readonly 
> docs: correctly type getters

- packages/builders/__tests__/messages/embed.test.ts
- packages/builders/src/messages/embed/Embed.ts
- packages/builders/src/messages/embed/UnsafeEmbed.ts
Other methods from builders do not support arrays either and it seems like it was a conscious decision https://github.com/discordjs/discord.js/pull/7395#discussion_r799831790
- removed support for arrays from `addFields()` and `spliceFields()`
- removed the `normalizeFields()` method as it no longer serves a purpose
> refactor(embed): remove array support in favor of rest params

- typings/index.d.ts
- typings/index.test-d.ts
Backports #7294 to version 13.
> types: V13 channel create overloads fix

- packages/discord.js/src/structures/MessagePayload.js
Fixes issue where unsafe embeds wouldn't be serialized, but regular embeds would.
> fix: allow unsafe embeds to be serialized

- packages/discord.js/src/util/Transformers.js
This fixes an issue where if a value is explicitly set to `undefined`, it would be serialized as `{}`.
Closes #7510 
> fix: properly serialize `undefined` values

- packages/builders/__tests__/interactions/SlashCommands/Options.test.ts
- packages/builders/src/interactions/slashCommands/options/integer.ts
- packages/builders/src/interactions/slashCommands/options/number.ts
Min/max value of number/integer options allow any double/integer between -2^53 and 2^53 
[Documentation - Application Command Option Type](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-type)
> fix(builders): allow negative min/max value of number/integer option

- packages/discord.js/src/structures/Invite.js
- packages/discord.js/typings/index.d.ts
This fixes a dumb regression from #7365 that removed the possibility of getting the channel id of an invite retrieved from audit logs. Both channel and channelId are still nullable, but this just covers another edge case that went unnoticed in that PR
> fix(invite): add back channelId property

- packages/discord.js/src/index.js
- packages/discord.js/src/structures/Guild.js
- packages/discord.js/typings/index.d.ts
the `AuditLogEvent` enum is currently not re-exported from discord-api-types like the other enums.
I also noticed the jsdoc for `GuildAuditLogsFetchOptions` not using this enum, the typings already do so.
> feat: re-export AuditLogEvent enum

- packages/discord.js/src/structures/MessagePayload.js
Replying to a message with suppressed embeds suppresses the replies embeds? No, I don't think so.
> fix(MessagePayload): don't set reply flags to target flags

- packages/discord.js/src/managers/MessageManager.js
- packages/discord.js/src/structures/Message.js
- packages/discord.js/typings/index.d.ts
> feat(message): add `reason` on pin and unpin

- typings/index.d.ts
Fixed type problem 
`sweepStageInstances` was miswritten to  `sweepStageInstnaces` in `index.d.ts` (typings)
- there are no code changes
> fix(typings): sweepStageInstances typo

- packages/discord.js/typings/index.d.ts
This fixes a bug with Channel#isDMBased() where it wouldn't correctly infer that a channel isn't a group DM
> types(anychannel): add PartialGroupDMChannel

- packages/discord.js/src/structures/Guild.js
Typo, should be calling resolveId on the UserManager and not ClientUser
> fix(guild): fix typo accessing user instead of users

- packages/discord.js/src/index.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
This PR replaces locale types definitions from `string` to `Locale` from discord-api-types.
> types: use discord-api-types `Locale`

- packages/builders/src/components/Components.ts
Previously a check was done for each component type. This simplifies the logic to one check for a class-based component.
> fix: only check `instanceof Component` once

- .github/COMMIT_CONVENTION.md
Reverts discordjs/discord.js#7246 due to #7507.
> revert: chore: commit scope name in lowercase

- packages/discord.js/src/managers/UserManager.js
- packages/discord.js/src/structures/DMChannel.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
As detailed in #7102, `Typing#user` had the potential to be an unwanted partial. This is because `DMChannel#_patch()` always adds the user, even if the data only contained the user id. Additionally, the typings weren't correct for this.
Since there is a possibility of not receiving the full recipient data, only the `recipientId` is now on the `DMChannel` class. `recipient` is now a getter. If the `USER` partial is specified or a full structure is received, we add the recipient to the cache which in turn will respectively emit `Client#typingStart`.
This fully resolves #7102.
- This PR …
> fix: Handle partial data for `Typing#user`

- src/structures/ThreadChannel.js
Backports #7406 to version 13.
> fix(ThreadChannel): Require `sendable` for `unarchivable`

- src/structures/ThreadChannel.js
- typings/index.d.ts
> feat(ThreadChannel): Backport creation timestamp

- src/structures/MessagePayload.js
- src/structures/Webhook.js
- src/structures/interfaces/InteractionResponses.js
- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
> feat: Backport sending message flags

- typings/index.d.ts
- typings/index.test-d.ts
Backports #7164 to version 13.
> feat: Backport cache types resolving to `never`

- typings/index.d.ts
Backports #7316 to version 13.
> feat: Backport `MessageMentions` channel type fixes

- packages/builders/__tests__/messages/embed.test.ts
- packages/builders/src/messages/embed/UnsafeEmbed.ts
This PR removes `Embed#addField` in favour of `Embed#addFields` because you are just saving a `s` when using `addField`.
For those who don't wanna replace all `addField` manually can try this regex replace. You can ofc make a better one but using these 2 also works fine. Idk how can I use condition in replace string else it can be simplified to one …
> refactor(Embed): remove add field

- packages/discord.js/src/util/Components.js
- packages/discord.js/typings/index.d.ts
- ModalSubmitFieldsResolver#components is documented but is not in the typings
- `TextInputComponentData` is defined in the typings but not for the docs, it is referenced for `ComponentData` but never declared
- ModalSubmitFieldsResolver#components is documented but is not in the typings
> types: modals type and doc fixes

- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
https://github.com/discordjs/discord.js/blob/6f7a3669568b7520c5e6c9ecbf7a95f85c3d1864/packages/discord.js/src/structures/interfaces/InteractionResponses.js#L237-L241
> types(showModal): align types with the documentation

- packages/builders/package.json
- packages/collection/package.json
- packages/rest/package.json
- packages/voice/package.json
Needed for TS@dev's module/moduleResolution: NodeNext
This doesn't affect discord.js because it doesn't have an exports mapping
> feat: add support for module: NodeNext in TS and ESM

- packages/discord.js/src/structures/ModalSubmitInteraction.js
- packages/discord.js/typings/index.d.ts
adds `deferred`, `replied` and `ephemeral` properties to `ModalSubmitInteraction`
> feat(ModalSubmitInteraction): add boolean properties

- packages/discord.js/src/structures/Embed.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
Originally I had assumed hex number literals would suffice over hex strings. However, many external services may return colors as hex strings because it's a popular format. This PR allows hex strings to be passed into `setColor` for discord.js embed builders.
> refactor(embed): allow hex strings in `setColor()`

- src/structures/MessageMentions.js
- typings/index.d.ts
This PR backports #7292 to v13
> fix(messagementions): fix `has` method for v13

- packages/builders/__tests__/interactions/SlashCommands/Options.test.ts
- packages/builders/__tests__/interactions/SlashCommands/SlashCommands.test.ts
- packages/builders/docs/examples/Slash Command Builders.md
- packages/builders/src/interactions/slashCommands/Assertions.ts
- packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionChannelTypesMixin.ts
- packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionWithChoicesAndAutocompleteMixin.ts
- packages/builders/src/interactions/slashCommands/mixins/SharedSlashCommandOptions.ts
- Removed `ApplicationCommandOptionChannelTypesMixin#addChannelType()`
- Removed `ApplicationCommandOptionWithChoicesAndAutocompleteMixin#addChoice()`
- `ApplicationCommandOptionChannelTypesMixin#addChannelTypes()` only accepts rest parameters instead of an array
> refactor: remove obsolete builder methods 

- packages/discord.js/src/util/Util.js
fixes: #7373
The purpose of this method is to remove all the markdowns but as shown in the issue that it's not able to remove `inlineCode` for some strings where additional backticks are used. The current change works fine for any input.
> fix(Util): escapeInlineCode properly

- packages/discord.js/src/structures/ActionRow.js
- packages/discord.js/typings/index.d.ts
This PR allows component classes to be passed to the components array of the action row constructor object
> types(ActionRow): allow components to be passed to constructors

- .github/ISSUE_TEMPLATE/bug_report.yml
- packages/discord.js/src/client/actions/Action.js
- packages/discord.js/src/client/actions/ThreadMembersUpdate.js
- packages/discord.js/src/structures/ThreadMember.js
- packages/discord.js/src/util/Partials.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
As explained in #6513, the event may emit the **same** `oldMembers` and `newMembers` which was... not useful. It's not possible to tell what actually changed there - only that _something_ changed. This is due to discord.js always assuming the thread member leaving is cached.
I believe it'd be best to do nothing (like other events) if only uncached thread members leave. By doing this, the event does not fire as it would emit the same `Collection` for both parameters. We can utilise a new partial (`Partials.ThreadMember`) for people who still want that data. This solves that issue, but there is another.
discord.js emits these added & removed thread members alongside the existing thread member cache. Since Discord …
> fix(ThreadMembersUpdate): Only emit added & removed thread members

- packages/rest/__tests__/REST.test.ts
- packages/rest/__tests__/RequestHandler.test.ts
- packages/rest/src/lib/REST.ts
- packages/rest/src/lib/RequestManager.ts
- packages/rest/src/lib/handlers/IHandler.ts
- packages/rest/src/lib/handlers/SequentialHandler.ts
Closes https://github.com/discordjs/discord.js/issues/7492 by resetting the token only when an authorized request fails with a 401.
> fix(RequestHandler): only reset tokens for authenticated 401s

- packages/discord.js/src/structures/VoiceState.js
- packages/discord.js/typings/index.d.ts
This PR adds a new method: VoiceState#edit to allow both editable parameters to be edited in 1 API call. It also changes the existing parameters to return the current voicestate instead of void like before
> feat(VoiceState): add edit method

- src/structures/GuildScheduledEvent.js
- src/util/Constants.js
- typings/index.d.ts
> feat(scheduledevents): Event cover images for v13

- packages/discord.js/src/structures/InteractionCollector.js
- packages/discord.js/src/util/Constants.js
Regression from #7452: `TextBasedChannelResolvable` did not exist.
> docs(InteractionCollector): Document channel option type

- packages/discord.js/src/structures/Embed.js
Since `src/util/Util.js` exports itself 'AS IS', old code causes syntax error.
This PR will fix the issue.
> fix(Embed): fix incorrect destructuring import

- packages/discord.js/src/structures/StageInstance.js
- packages/discord.js/typings/index.d.ts
Adds support to associated cached scheduled events with a stage instance if applicable.
- https://github.com/discord/discord-api-docs/pull/4583
> feat(StageInstance): Add support for associated guild event

- packages/builders/__tests__/components/selectMenu.test.ts
- packages/builders/src/components/Assertions.ts
- https://github.com/discord/discord-api-docs/pull/4551
> fix(SelectMenu): set `placeholder` max to 150

- src/structures/InteractionCollector.js
- src/util/Constants.js
- typings/index.d.ts
> types(InteractionCollector): Fix guild and channel types

- packages/discord.js/typings/index.d.ts
Fixes regression where action row data no longer accepted component classes.
> types: allow component classes in action row data

- packages/discord.js/src/index.js
The file no longer exists. Importing `ModalBuilder` is the replacement - this was left over.
> fix: Remove Modal export

- packages/discord.js/typings/index.d.ts
This PR simplifies the ColorResolvable type by using the keys of the Colors object instead of hardcoding all the strings again
> types(ColorResolvable): simplify string types

- packages/discord.js/src/structures/EmbedBuilder.js
#7593 but for `EmbedBuilder` instead of `Embed`, following up #7662 
> refactor(EmbedBuilder): allow hex strings in setColor

- packages/discord.js/typings/index.d.ts
This PR adds forgotten `footer` type to `Embed`
> types(Embed): add forgotten `footer` type

- .github/workflows/publish-dev.yml
Big misfortune due to the changes in #6879 happened: the first 3 letters/numbers in the commit hash matched the timestamp. This PR fixes that by removing the unnecessary `cut`
> chore(ci): fix dev deploy workflow

- packages/discord.js/src/errors/Messages.js
- packages/discord.js/src/structures/Guild.js
Fixes #7574 and changes the method to follow our prefer-async style.
I guess it's technically breaking since the method can now throw an error where it didn't before (although it probably should have)
> fix(guild): throw if ownerId falsey

- packages/discord.js/typings/index.d.ts
added `webhook` to `InteractionResponseFields`
this can also be added to #7563 
> types(InteractionResponseFields): add webhook

- packages/discord.js/src/client/websocket/WebSocketManager.js
Fixes an issue with the `AuthenticationFailed` error, when trying to log in with an invalid bot token. Which causes the error not to be thrown and instead, a Discord API error (`401: Unauthorized`) is thrown, which does not specify anything about the token.
> fix: `AuthenticationFailed` error not thrown at login with invalid token

- packages/discord.js/src/structures/Presence.js
As per https://github.com/discord/discord-api-docs/pull/4617, the following parsing should be removed:
- Twitch
- YouTube
- Spotify
It seems the media proxy is fine to stay.
This resolves #7635.
> refactor(RichPresenceAssets): Remove undocumented checks

- packages/discord.js/src/util/Util.js
fix regression from #7587 
Now it'll escape double backtics but not codeblocks.
> fix(util): allow `escapeInlineCode` to escape double backtics

- packages/discord.js/src/structures/AnonymousGuild.js
`Guild#premiumSubscriptionCount` could be possibly `undefined` per [the documentation](https://discord.com/developers/docs/resources/guild#guild-object-guild-structure). A check has been added to ensure that it defaults to `null`.
> fix(AnonymousGuild): Handle possibly missing `premium_subscription_count`

- packages/discord.js/src/structures/InteractionCollector.js
`Message#channel` and `Message#guild` are getters which use `Message#channelId` and `Message#guildId` internally, so there is no need to invoke them and use `resolveId`
the `empty` method is currently bound for each `IntereactionCollector` even though it is not used in any listener, probably a copy-paste from [`ReactionCollector`](https://github.com/discordjs/discord.js/blob/main/packages/discord.js/src/structures/ReactionCollector.js#L49)
> refactor(InteractionCollector): simplify constructor logic

- packages/discord.js/src/structures/Guild.js
- packages/discord.js/src/structures/GuildAuditLogs.js
- packages/discord.js/typings/index.d.ts
After #1660 and #7089, there are no more possible `Promise`s in the constructor of `GuildAuditLogs` and `GuildAuditLogsEntry`. Therefore, this method is redundant.
> refactor(GuildAuditLogs): Remove static build method

- README.md
- packages/discord.js/README.md
- packages/discord.js/src/util/Options.js
- packages/rest/src/lib/REST.ts
Djs incorrectly defaulted to v9 instead of v10.
> fix(gateway): use version 10

- packages/discord.js/src/managers/GuildChannelManager.js
- packages/discord.js/src/managers/ThreadManager.js
- packages/discord.js/src/structures/BaseGuildTextChannel.js
- packages/discord.js/src/structures/ThreadChannel.js
- packages/discord.js/src/util/Util.js
- packages/discord.js/typings/index.d.ts
Channels store the properties as numbers as-is from the API and the edit methods allow for a `MAX` helper. This pull request resolves #7687 and resolves supplying `MAX` via `GuildChannelManager#edit()` not working as intended.
Additionally, this paring has been refactored into a utility method for deduplication reasons.
> types: Fix auto archive duration type

- packages/discord.js/typings/index.d.ts
Correct `Constants` constant in the declaration file
- Add `Constants.NonSystemMessageTypes` and `NonSystemMessageType` type
- Remove `Constants.MessageTypes`, `Constants.SystemMessageTypes` and `SystemMessageType` type
> types(Constants): add `NonSystemMessageTypes` property

- packages/discord.js/src/structures/GuildAuditLogsEntry.js
- packages/discord.js/src/structures/GuildTemplate.js
- packages/discord.js/src/structures/Invite.js
- packages/discord.js/src/structures/MessageMentions.js
- packages/discord.js/src/util/ActivityFlagsBitField.js
- packages/discord.js/src/util/ApplicationFlagsBitField.js
- packages/discord.js/src/util/BitField.js
- packages/discord.js/src/util/Formatters.js
- packages/discord.js/src/util/IntentsBitField.js
- packages/discord.js/src/util/MessageFlagsBitField.js
- packages/discord.js/src/util/PermissionsBitField.js
- packages/discord.js/src/util/SystemChannelFlagsBitField.js
- packages/discord.js/src/util/ThreadMemberFlagsBitField.js
Regression from #7701: Removing the `@memberof` JSDoc resulted in static properties being incorrectly documented from the instance and static methods no longer existing.
> docs: Add back static properties and methods

- packages/builders/tsup.config.ts
- packages/collection/tsup.config.ts
- packages/rest/tsup.config.ts
- packages/voice/tsup.config.ts
Minification of the output code makes it harder to debug code because it makes it near impossible to set breakpoints in the code that gets extracted to `node_modules`. Therefore, by disabling modifications we make it easier for advanced users to debug their code in case they run into issues. This in turn can also lead to better contributions and issues as causes and effects can be traced more easily. Furthermore, because we are not bundling for the web where size is actually of concern, there really is no big gain in minifying anyway.
Other than the minification change I also set the tsup option to add the `"use strict";` banner to CJS bundles, something I discovered how to do when @vladfrangu and @kyranet asked …
> chore(build): disable tsup minification & add `"use strict";` banner to CJS bundles

- packages/builders/src/components/ActionRow.ts
- packages/builders/src/components/selectMenu/UnsafeSelectMenu.ts
- packages/builders/src/interactions/modals/UnsafeModal.ts
- packages/discord.js/src/structures/MessagePayload.js
- packages/discord.js/src/structures/ModalSubmitInteraction.js
- packages/discord.js/src/util/Components.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
This PR fixes a bunch of regressions and missed changes from #7584 
> types: fix regressions

- packages/discord.js/src/structures/BaseGuildVoiceChannel.js
- packages/discord.js/src/structures/StageChannel.js
- packages/discord.js/src/structures/VoiceChannel.js
- packages/discord.js/typings/index.d.ts
This field supports the `X-Audit-Log-Reason` header but was not being used in the helper methods. This has now been added in. Additionally, I have modified the examples to use `sydney` instead of `europe` as `europe` is not a valid region.
> fix: Support `reason` in `setRTCRegion` helpers

- packages/discord.js/src/managers/GuildChannelManager.js
- packages/discord.js/src/managers/GuildManager.js
- packages/discord.js/src/structures/VoiceChannel.js
- packages/discord.js/src/util/EnumResolvers.js
- packages/discord.js/typings/index.d.ts
Discord has [`video_quality_mode`](https://discord.com/developers/docs/resources/channel#channel-object) documented, but we have no support for it. No more will that be the case!
> feat(VoiceChannel): Support `video_quality_mode`

- packages/discord.js/src/structures/DMChannel.js
- packages/discord.js/src/structures/User.js
These methods passed `force` as a boolean. However, the second parameter is an object:
https://github.com/discordjs/discord.js/blob/520f471ac56cbc01402b79197333a8a34c4ac5c9/packages/discord.js/src/managers/UserManager.js#L45-L51
> fix: Pass `force` correctly

- src/structures/Presence.js
Due to #7635, YouTube has been removed from parsing here. The rest will be removed in version 14.
> refactor(RichPresenceAssets): Remove non-breaking custom image support

- src/structures/AnonymousGuild.js
- src/structures/Guild.js
- typings/index.d.ts
> feat: Add `premiumSubscriptionCount` to `InviteGuild`

- src/structures/Interaction.js
- typings/index.d.ts
- typings/index.test-d.ts
> feat: Backport `Interaction#isRepliable`

- packages/discord.js/src/client/actions/InteractionCreate.js
Text-in-Voice channels are gradually rolling out. When an interaction from a component is received in such a channel, discord.js will crash as it attempts to cache the respective message as we do not provide a message cache for voice channels.
This has been resolved by verifying that the channel an interaction came from is text-based (if it is going to cache the respective message). This logic has been applied to message context menu command interactions too despite being currently unusable in text-in-voice channels, but it is better to be safe than sorry.
This pull request resolves #7749. …
> fix(InteractionCreateAction): Ensure text-based channel for caching messages

- packages/discord.js/src/structures/CommandInteraction.js
- packages/discord.js/src/structures/MessageComponentInteraction.js
- packages/discord.js/src/structures/interfaces/InteractionResponses.js
- packages/discord.js/typings/index.d.ts
Adds the ability to `await` modal submissions via `MessageComponentInteraction#awaitModalSubmit`
> feat(modal): add `awaitModalSubmit`

- packages/discord.js/src/structures/Invite.js
- packages/discord.js/src/structures/VoiceState.js
These properties are potentially `null` which makes `Date.parse()` potentially return `NaN`. This pull request assures these properties to be `null` in this case.
> fix: Prevent `NaN` for nullable timestamps

- packages/discord.js/src/client/Client.js
- packages/discord.js/src/managers/GuildManager.js
- packages/discord.js/src/managers/GuildMemberManager.js
- packages/discord.js/src/managers/GuildScheduledEventManager.js
- packages/discord.js/src/managers/MessageManager.js
- packages/discord.js/src/managers/ReactionUserManager.js
- packages/discord.js/src/managers/ThreadManager.js
- packages/discord.js/src/structures/BaseGuild.js
- packages/discord.js/src/structures/Guild.js
- packages/discord.js/src/structures/Webhook.js
- packages/rest/__tests__/utils.test.ts
- packages/rest/src/index.ts
- packages/rest/src/lib/utils/utils.ts
When using `URLSearchParams`'s constructor, we had to be careful not to pass nullish values, and furthermore, TypeScript complains if we use non-string values in the constructor as it's typed as the record types are typed as `string[][]` and `Record<string, string>`.
The `makeURLSearchParams` is an utility that safely serializes the data, stripping out invalid values (undefined, null, symbol, function, objects without toString override, etc).
> feat: add `makeURLSearchParams` utility function

- packages/discord.js/typings/index.d.ts
Fixes the `components` type in `ModalSubmitInteraction`, since #7517 is now implemented.
`ModalSubmitActionRow[]` -> `ActionRow<ModalActionRowComponent>[]`
> types(ModalSubmitInteraction): fix `components` type

- packages/discord.js/src/structures/ButtonBuilder.js
- packages/discord.js/src/structures/SelectMenuBuilder.js
- packages/discord.js/typings/index.d.ts
This PR adds the feature from #7616 to builder constructors
> feat: allow emoji strings to be passed through constructors

- packages/discord.js/typings/index.d.ts
All `ModalSubmitInteraction`s have a (nullable) message property and the `isFromMessage` typeguard is supposed to narrow down that it is not null
> types(ModalSubmitInteraction): message

- packages/discord.js/src/managers/ApplicationCommandManager.js
- packages/discord.js/src/structures/ApplicationCommand.js
- packages/discord.js/src/structures/AutocompleteInteraction.js
- packages/discord.js/typings/index.d.ts
Add support for localized names and descriptions in slash command payloads.
> feat(CommandInteraction): add support for localized slash commands

- src/managers/GuildChannelManager.js
- src/managers/GuildManager.js
- src/structures/VoiceChannel.js
- src/util/Constants.js
- typings/enums.d.ts
- typings/index.d.ts
> feat(VoiceChannel): Support `video_quality_mode` (v13)

- packages/discord.js/typings/index.d.ts
This property is `null` if not sent. This was reflected in the code and in the documentation but not in the typings.
> types(VoiceChannel): Nullify `videoQualityMode`

- src/structures/BaseGuildVoiceChannel.js
- src/structures/StageChannel.js
- src/structures/VoiceChannel.js
- typings/index.d.ts
Backports #7723 to version 13.
> fix: Support `reason` in `setRTCRegion` helpers (v13)

- packages/discord.js/typings/index.d.ts
The utility method added in #7688 was not present in the typings. It now is.
> types(Util): Add `resolveAutoArchiveMaxLimit()`

- src/managers/StageInstanceManager.js
- typings/index.d.ts
Backports #7730 to version 13.
> feat(StageInstanceManager): add sendStartNotification option to create (v13)

- src/structures/Invite.js
- src/structures/VoiceState.js
Backports #7750 to version 13.
> fix: Handle nullable timestamps (v13)

- src/structures/Channel.js
- src/structures/DirectoryChannel.js
- src/util/Constants.js
- typings/enums.d.ts
- typings/index.d.ts
Backports #6788 to version 13.
> feat: Add guild directory support (v13)

- src/structures/ClientApplication.js
- typings/index.d.ts
> feat: app authorization links and tags for v13

- package-lock.json
- package.json
- src/managers/ApplicationCommandManager.js
- src/structures/ApplicationCommand.js
- src/structures/AutocompleteInteraction.js
- typings/index.d.ts
Backports https://github.com/discordjs/discord.js/pull/7684
> feat: add support for localized slash commands (v13 backport)

- src/managers/GuildMemberManager.js
- typings/index.d.ts
> fix(GuildMemberManager): `unban()` return type can be `null` (v13)

- src/managers/GuildChannelManager.js
- src/managers/ThreadManager.js
- src/structures/BaseGuildTextChannel.js
- src/structures/ThreadChannel.js
- src/util/Util.js
- typings/index.d.ts
Backports the following pull requests into version 13:
- #7688
- #7781
> types: Fix auto archive duration type (v13)

- src/structures/ApplicationCommand.js
Backports #7794 to version 13.
> docs(ApplicationCommand): Fix ApplicationCommandOptionChoice (v13)

- packages/discord.js/src/util/Util.js
- packages/discord.js/typings/index.d.ts
Resolves #7674. This method is going to be removed.
> refactor(Util): Remove splitting

- packages/discord.js/src/managers/MessageManager.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
This pull request resolves #7093. This implementation is actually the same as #7734, so this should feel familiar and consistent.
I have also renamed `ChannelLogsQueryOptions` to `FetchMessagesOptions` to better reflect this type definition and for consistency amongst other type definitions.
> fix(MessageManager): Allow caching option of an unspecified limit

- packages/builders/__tests__/interactions/SlashCommands/SlashCommands.test.ts
- packages/builders/package.json
- packages/builders/src/interactions/slashCommands/Assertions.ts
- packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts
- packages/builders/src/interactions/slashCommands/mixins/NameAndDescription.ts
- packages/builders/src/util/slashCommandUtil.ts
- yarn.lock
Allows builders to specific localizations dictionaries for `name` and `description`
> feat: Slash command localization for builders

- typings/index.d.ts
This PR backports #7816 into v13
> types(threadchannel): fix autoArchiveDuration types

- packages/discord.js/typings/index.d.ts
The type for the awaitModalSubmit method on the CommandInteraction class wasn't added in #7751, despite the method being available on it
> types(CommandInteraction): add awaitModalSubmit

- packages/discord.js/src/structures/InteractionCollector.js
- packages/discord.js/src/structures/interfaces/InteractionResponses.js
MessageComponents do not require an interaction to be sent - this was causing an `id of null` error.
> fix(InteractionResponses): use optional chaining on nullable property

- packages/discord.js/typings/index.d.ts
This PR fixes a regression from https://github.com/discordjs/discord.js/pull/7623.
BooleanCache was never resolving to true.
> types: fix BooleanCache never resolving to true

- packages/builders/src/messages/embed/Assertions.ts
- packages/builders/src/messages/embed/Embed.ts
Improves the error output of some EmbedBuilder methods by using an object validator rather than validating params individually.
This provides much better output for the most common errors seen due to old v13 style code such as `<EmbedBuilder>.setAuthor("Monbrey")`, which will now throw `Expected the value to be an object, but received string instead`.
I didn't see anywhere else this needed doing but feel free to point out any spots and I'll do the same.
> feat(builders): improve embed errors and predicates

- src/managers/GuildBanManager.js
- typings/index.d.ts
- typings/index.test-d.ts
Backports #7734 to version 13.
> feat(GuildBanManager): Support pagination results (v13)

- src/structures/Guild.js
- typings/index.d.ts
Backports the following pull request to v13:
- #7632
> fix(GuildEditData): some fields can be null for v13

- packages/discord.js/src/structures/SelectMenuBuilder.js
- packages/discord.js/src/structures/SelectMenuOptionBuilder.js
- packages/discord.js/typings/index.d.ts
Oversight from #7718 this PR adds the ability to add an emoji on a SelectMenuOptionBuilder's constructor, as well as the SelectMenuBuilder methods addOptions and setOptions
> feat(SelectMenu): allow emojis in options and option constructors

- packages/builders/__tests__/components/actionRow.test.ts
- packages/builders/__tests__/components/selectMenu.test.ts
- packages/builders/__tests__/interactions/modal.test.ts
- packages/builders/__tests__/messages/embed.test.ts
- packages/builders/src/components/ActionRow.ts
- packages/builders/src/components/selectMenu/SelectMenu.ts
- packages/builders/src/components/selectMenu/UnsafeSelectMenu.ts
- packages/builders/src/components/textInput/UnsafeTextInput.ts
- packages/builders/src/interactions/modals/UnsafeModal.ts
- packages/builders/src/messages/embed/Embed.ts
- packages/builders/src/messages/embed/UnsafeEmbed.ts
Originally I had the opinion that using rest parameters allowed for a clearer UI DSL. However I've since conceded this opinion.
The main reason for this is that this design decision has resulted in a degraded UX for many users. It seems that every other message in the dev channel has to do with someone using an array instead of rest parameters. Rest paramters seem to be an unexpected input type for most.
"Why not support both rest and array parameters"
To be clear JS doesn't support this. The only way to achieve this is via a workaround, that *emulates* this behavior. This workaround involves accepting a a rest parameter 2D arrays. 
I fear that the types here are confusing since they imply you must pass in multiple …
> refactor(builders): use arrays instead of rest parameters

- packages/discord.js/src/errors/Messages.js
- packages/discord.js/src/structures/MessagePayload.js
Currently if you send an embed with an empty string as the content you get a `RangeError [MESSAGE_CONTENT_TYPE]: Message content must be a non-empty string.` and are supposed to supply `null` when indicating that the message content is not needed. However the method, namely `makeContent`, that actually causes this error simply converts that null into an empty string.
It appears to be, and do correct me if I am wrong, that the method errors if an empty string is the content but then returns an empty string anyway?
To fix this I have changed the `verifyString` function to accept empty strings stopping the errors
- Code changes have been tested against the Discord API, or …
> makeContent should accept empty strings

- src/structures/ApplicationCommand.js
- src/structures/Guild.js
- src/structures/Interaction.js
- typings/index.d.ts
Backports https://github.com/discordjs/discord.js/pull/7804
> docs: fix and improve localization docs (v13 backport)

- packages/discord.js/src/structures/ApplicationCommand.js
- packages/discord.js/src/structures/Guild.js
- packages/discord.js/src/structures/Interaction.js
- packages/discord.js/typings/index.d.ts
This PR:
- adds a `Locale` typedef with all the possible locales to make it easier to document them in various places
- fixes the documentation of the *Localizations and *Localized properties
> docs(ApplicationCommand): fix and improve localization docs

- packages/discord.js/src/index.js
- packages/discord.js/src/structures/Presence.js
- packages/discord.js/typings/index.d.ts
https://discord.com/developers/docs/resources/channel#message-object-message-activity-structure
- `partyId` is optional and `type` is required
- changed the type of `type` to `MessageActivityType`
> types(Message#activity): make `partyId` optional and use enum for `type`

- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
Fixes #7835 
- `DMChannel#toString()` returns a `UserMention` https://github.com/discordjs/discord.js/blob/361709332bdc871822c2b9919f14fd090d68666a/packages/discord.js/src/structures/DMChannel.js#L100-L102
- `PartialGroupDMChannel` returns a `ChannelMention`
> types: fix return type of `toString()` on channels

- packages/discord.js/src/structures/InteractionCollector.js
- packages/discord.js/src/structures/MessageCollector.js
- packages/discord.js/src/structures/ReactionCollector.js
- packages/discord.js/src/structures/interfaces/Collector.js
- packages/discord.js/typings/index.d.ts
https://discord.com/channels/222078108977594368/682166281826598932/967515506884091904
`Collector.endReason` wasn't being set in the `stop` function, meaning it was essentially useless. Very useful when using `for await`;
```js
import { Collector } from 'discord.js';
const collector = new Collector(...);
setTimeout(() => collector.emit('collect', { hi: 'there' }), 1);
for await (const [i] of collector) {
collector.stop(Math.random() > 0.5 ? 'heads' : 'tails');
}
console.log('end reason is:', collector.endReason);
```
Classes that extend Collector still retain their `endReason` getters but rather than return null if no conditions are met, it will return the custom reason (if there is one, otherwise null).
**Status …
> fix: `endReason` not being properly set in base Collector

- src/sharding/ShardingManager.js
> docs(shardingmanager): fix type of `execArgv` option (v13)

- packages/discord.js/src/client/actions/WebhooksUpdate.js
- packages/discord.js/src/structures/BaseGuildTextChannel.js
- packages/discord.js/src/structures/DMChannel.js
- packages/discord.js/src/structures/Message.js
- packages/discord.js/src/structures/MessagePayload.js
- packages/discord.js/src/structures/VoiceChannel.js
- packages/discord.js/src/structures/interfaces/TextBasedChannel.js
- packages/discord.js/src/util/Constants.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
This PR adds support for the upcoming text in voice feature.
Notable changes:
- Voice channels are now text based channels (surprising, I know), they don't support pinning of messages though
- `fetchWebhooks` and `createWebhook` moved to `TextBasedChannel` (they previously were in `BaseGuildTextChannel`)
> feat(VoiceChannel): add support for text in voice

- packages/discord.js/src/structures/GuildAuditLogsEntry.js
- packages/discord.js/typings/index.d.ts
`GuildAuditLogsEntry` assumes `this.changes` exists for most action types even though we default it to `null`. This becomes an issue when resolving to `TargetType.Unknown` where `this.changes` is accessed without optional chaining.
Defaulting to an empty array rather than null fixes the error in a way that is resilient to changes overall, e.g. should Discord decide to stop sending changes with another audit log type where we expect them.
The alternative approach is to optionally chain access to `this.changes` everywhere else and make other properties optional/nullable. If this is preferred let me know and I'll switch.
- I know how to update typings and have done …
> fix(AuditLog): default changes to empty array

- packages/discord.js/src/structures/interfaces/InteractionResponses.js
after https://github.com/discordjs/discord.js/pull/7584 this example is now outdated as it should construct a `EmbedBuilder` and not an Embed
> docs(InteractionResponses): replace outdated Embed example for reply

- packages/discord.js/typings/index.d.ts
This PR specifies the `CacheType` generic in *hopefully* all missing places, to have more accurate method return types.
> types: make `CacheType` generic more accurate for return values

- packages/builders/src/interactions/contextMenuCommands/Assertions.ts
- packages/builders/src/interactions/contextMenuCommands/ContextMenuCommandBuilder.ts
- packages/builders/src/interactions/slashCommands/Assertions.ts
- packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts
Adds support for command permissions v2 in builders
> feat(builders): add new command permissions v2

- packages/builders/package.json
- packages/discord.js/package.json
- packages/rest/package.json
- packages/voice/package.json
- yarn.lock
This bumps the discord-api-types dependency to 0.32.1 for all packages. Since the voice package now uses the same discord-api-types version as the discord.js package, this will resolve #7884.
> chore: Bump discord-api-types

- packages/rest/__tests__/REST.test.ts
- packages/rest/src/lib/handlers/SequentialHandler.ts
Expands upon #7918 with a test.
Sorry I forgot <response>.ok accounted for status codes in the 2xx range.
> fix: ok statusCode can be 200..299

- packages/builders/__tests__/interactions/ContextMenuCommands.test.ts
- packages/builders/__tests__/interactions/SlashCommands/SlashCommands.test.ts
- packages/builders/src/interactions/contextMenuCommands/ContextMenuCommandBuilder.ts
- packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts
> fix(SlashCommandBuilder): import `Permissions` correctly

- packages/discord.js/src/util/DataResolver.js
The check for a stream is too strict and misses things that are streams.
Example: The package [archiver](npmjs.com/package/archiver) uses the [readable-stream](https://www.npmjs.com/package/readable-stream) which allows for compatibility for multiple node versions. But since the check only looks for the stream.Readable, the check fails.
I've changed the check to look for an asyncIterator, which I think is the simplest fix. If desired, it could be changed to check for a readable stream:
```js
static _isReadableStream(stream) {
return (
typeof stream === 'object' &&
typeof stream.pipe === 'function' &&
stream.readable !== false &&
typeof stream._read === 'function' &&
typeof stream._readableState === 'object'
);
} …
```
> fix(DataResolver): fix check for readable streams

- packages/discord.js/src/managers/ChannelManager.js
- packages/discord.js/src/managers/GuildChannelManager.js
Upon channel deletion, their respective invites are not deleted. These will linger around until manually removed, which is not ideal. This pull request should address that issue by removing them from the cache upon deletion & resolves #7930.
The channel delete handler was called in `GuildChannelManager#delete()` to handle a race limit where the cache would not be updated in time when `await`ed.
> fix: Remove trailing invites on channel deletion

- packages/discord.js/src/structures/interfaces/TextBasedChannel.js
Fixes #7882
As it turns out, calling `delete` caused the event handler to uncache the message before the `getMessage` call, causing bulk-deleting a single message to always return an empty collection.
> fix(TextBasedChannel#bulkDelete): return deleted message

- packages/discord.js/src/structures/ActionRowBuilder.js
- packages/discord.js/src/util/Components.js
- packages/discord.js/typings/index.d.ts
Djs action row builders mistakenly create builders from `/builders` instead of using the djs builders when json is passed in.
Fixes #7865
> fix: make sure action row builders create djs builders

- packages/discord.js/typings/index.d.ts
`oldGuildScheduledEvent` is potential `null`. This was reflected in the documentation, but not in the typings.
> types: nullify `guildScheduledEventUpdate`'s old parameter

- packages/builders/cliff.toml
- packages/collection/cliff.toml
- packages/discord.js/cliff.toml
- packages/rest/cliff.toml
- packages/voice/cliff.toml
Little while ago I remarked to @iCrawl in DM that there was a bug in the
git cliff configs that I had to fix for Sapphire. Namely when a commit
has the following body:
```
type: message
BREAKING CHANGE: One
BREAKING CHANGE: Two
... etc
```
These breaking changes weren't being listed in the changelog because of
how Git Cliff parses the commit body and footer.
That all said, this PR fixes that issue.
~~Lastly, when making the changes for Sapphire I thought it'd be fun to~~
~~add emojis to the scopes. Some other projects do this and it really~~
~~makes their changelogs look more fun. Please do let me know if for DiscordJS~~
~~you guys do not want the emojis and I'll remove them again.~~ …
> chore: fix git cliff configs

- packages/builders/src/index.ts
Closes: #7941 
Export types from `interactions/slashCommands/mixins`
> feat: Export types from `interactions/slashCommands/mixins`

- packages/discord.js/typings/index.d.ts
Previously the following code:
```ts
import { once } from 'node:events';
await client.login(process.env.DISCORD_TOKEN);
const [readyClient] = await once(client, 'ready');
```
Would improperly type `readyClient` as `any`
With this PR the types are properly provided so it resolves to `Client<true>`
> types: add types to `EventEmitter` static methods

- packages/discord.js/src/util/APITypes.js
Adds external links for references to dapi-types in discord.js
> chore: add external links for dapi-types

- packages/discord.js/src/structures/GuildAuditLogs.js
- packages/discord.js/typings/index.d.ts
This is [documented](https://discord.com/developers/docs/resources/audit-log#audit-log-object-audit-log-structure), but we were not handling it.
> fix(GuildAuditLogs): Cache guild scheduled events

- packages/discord.js/src/index.js
- packages/discord.js/src/managers/GuildStickerManager.js
- packages/discord.js/src/structures/Attachment.js
- packages/discord.js/src/structures/AttachmentBuilder.js
- packages/discord.js/src/structures/CommandInteraction.js
- packages/discord.js/src/structures/Message.js
- packages/discord.js/src/structures/MessagePayload.js
- packages/discord.js/src/structures/Webhook.js
- packages/discord.js/src/structures/interfaces/TextBasedChannel.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
This PR creates a seperate structure for attachments returned by the API. The builder structure has been renamed to `AttachmentBuilder`
> refactor(attachment): don't return attachment builders from API

- packages/discord.js/src/managers/GuildChannelManager.js
- packages/discord.js/src/managers/GuildManager.js
- packages/discord.js/typings/index.d.ts
Typings were wrong for channel create/edit, some properties are nullable but weren't set as such. When using Typescript this could force workarounds like // @ts-ignore which go against the point of Typescript.
> fix: typings

- packages/discord.js/src/structures/interfaces/Collector.js
- packages/discord.js/typings/index.d.ts
This PR adds an option to the collector class with a function to be called when an item is filtered out of the collector, useful when working with interactions and sending error messages for unwanted ones.
> feat(Collector): add `ignore` event

- packages/discord.js/src/structures/VoiceChannel.js
This PR documents that `VoiceChannel` implements `TextBasedChannel`.
(This should have been in #6921, but I must have missed that somehow)
That way methods like `send` and friends (full list at the end of the class as stubs) appear on the documentation.
> docs(VoiceChannel): annotate that it is implementing TextBasedChannel

- src/client/actions/WebhooksUpdate.js
- src/structures/BaseGuildTextChannel.js
- src/structures/DMChannel.js
- src/structures/Message.js
- src/structures/MessagePayload.js
- src/structures/ThreadChannel.js
- src/structures/VoiceChannel.js
- src/structures/interfaces/TextBasedChannel.js
- src/util/Constants.js
- typings/index.d.ts
- typings/index.test-d.ts
Backports #6921 and #8002 to v13
Closes #7998
Closes #7996
Closes #7995
> feat: backport text-in-voice support to v13

- packages/discord.js/src/structures/ActionRowBuilder.js
- packages/discord.js/src/structures/SelectMenuOptionBuilder.js
- packages/discord.js/typings/index.d.ts
Some builders were missing `from` method. This pr adds them.
> fix: add static method `from` in builders

- packages/discord.js/src/structures/CommandInteractionOptionResolver.js
- packages/discord.js/src/structures/ContextMenuCommandInteraction.js
- packages/discord.js/src/structures/MessageComponentInteraction.js
- packages/discord.js/src/structures/ModalSubmitInteraction.js
- packages/discord.js/src/structures/Webhook.js
- packages/discord.js/src/util/Util.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
When editing or fetching replies, the code in this PR will no longer return `APIMessage` objects for bots that aren't present in a guild. Instead it will always return a `Message` instance by creating a new `Message` from the `APIMessage` data. As result the return type for the interaction response methods (when `fetchReply` is set to `true`) is no longer `Message | APIMessage`.
Closes #7956
- This PR includes breaking changes (methods …
> refactor: always return `Message` instances in interactions

- packages/discord.js/typings/index.d.ts
This PR removes `name` parameter from `AttachmentBuilder` constructor typings as it isn't actually used in the source code.
> types(AttachmentBuilder): remove name parameter from constructor

- packages/discord.js/src/structures/Attachment.js
Despite having `@private` in the jsdoc, the constructor is still shown in the documentation (and it doesn't show it as private at all)
Removing the jsdoc removes it from the documentation completely
Example from the Message class, which also has a private constructor:
https://github.com/discordjs/discord.js/blob/7a1095b66be3c5d81185e026281e2908c10c1695/packages/discord.js/src/structures/Message.js#L33-L34
https://github.com/discordjs/discord.js/blob/7a1095b66be3c5d81185e026281e2908c10c1695/packages/discord.js/typings/index.d.ts#L1628-L1630
> docs(Attachment): remove constructor doc

- packages/discord.js/src/structures/MessageReaction.js
- packages/discord.js/typings/index.d.ts
This PR adds the MessageReaction#react method to make it easier to add an existing reaction to a message. Its purpose is to make it easier for bots to react with emojis they do not know in their cache. The name is up for debate if anyone has better ideas, this was the best I could come up with
> feat(MessageReaction): add react method

- packages/discord.js/src/structures/Channel.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
Channels are returned as discriminated unions which means *most* of the type guards on the channel class aren't needed anymore. For example, to narrow to a voice channel you can just do the following:
```ts
if (channel.type !== ChannelType.GuildVoice) {
return;
}
channel // Narrowed to Voice channel.
```
> refactor(channel): remove redundant channel type guards

- packages/builders/__tests__/components/actionRow.test.ts
- packages/builders/__tests__/components/selectMenu.test.ts
- packages/builders/__tests__/interactions/modal.test.ts
- packages/builders/__tests__/messages/embed.test.ts
- packages/builders/src/components/ActionRow.ts
- packages/builders/src/components/selectMenu/SelectMenu.ts
- packages/builders/src/components/selectMenu/UnsafeSelectMenu.ts
- packages/builders/src/index.ts
- packages/builders/src/interactions/modals/UnsafeModal.ts
- packages/builders/src/messages/embed/Embed.ts
- packages/builders/src/messages/embed/UnsafeEmbed.ts
- packages/builders/src/util/normalizeArray.ts
- packages/discord.js/typings/index.d.ts
This PR changes all builders methods that previously only accepted arrays as input to accept both arrays and rest params. This was done by partially reverting #7759 and adding util functions to make it easy to support these two forms of input. There is no significant performance hit as this is not using Array.prototype.flat like before, it instead uses Array.isArray to check the kind of input that was provided.
> feat: allow builders to accept rest params and arrays

- packages/discord.js/src/structures/Sticker.js
- packages/discord.js/typings/index.d.ts
So, after working with stickers I've realized that the Sticker's `tags` property doesn't really make that much sense. As of now its type is `string[]` even though the Discord API returns `string`.
For every sticker the string value is parsed with `.split(', ')` which doesn't make sense considering that only standard stickers have `tags` as  a comma separated list of keywords. This adds overhead with no purpose as you can't edit standard stickers and guild stickers ignore the commas and use the whole string for suggestion. Further more, this makes sticker comparison slower because it's comparing arrays of strings instead of just strings (O(n*k) vs O(n)).
It's also inconsistent with the create/edit methods as they …
> refact: Sticker's `tags` property

- packages/discord.js/typings/index.d.ts
This PR fixes the type of the `data` parameter in the AttachmentBuilder, making it possible to set a name on an attachment again
> types(AttachmentBuilder): fix data type

- packages/discord.js/src/structures/Channel.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
#8012 removed redundant channel type guards but also removed `isThread` which is a union of 3 channel type.
> fix: readd `isThread` type guard

- packages/discord.js/src/structures/Interaction.js
- packages/discord.js/src/structures/ThreadChannel.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
Same idea as #8012 but for interactions, this adds missed thread narrowing changes from the aforementioned PR.
> refactor(interactions): remove redundant interaction typeguards

- packages/discord.js/src/managers/ThreadMemberManager.js
- packages/discord.js/src/structures/ThreadChannel.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
`ThreadMemberManager#fetch()` has been made consistent with other managers, such as `MessageManager#fetch()` and `GuildBanManager#fetch()`. This also fixes an issue (by removing it) in which passing only a boolean was ignored and was deemed always `true`.
> refactor(ThreadMemberManager): Consistent thread member fetching

- packages/builders/cliff.toml
- packages/collection/cliff.toml
- packages/discord.js/cliff.toml
- packages/proxy/cliff.toml
- packages/rest/cliff.toml
- packages/voice/cliff.toml
Found an issue in literally every single cliff.toml file in every skyra/sapphire/favware/djs repo, yaaay. Actually thanks to another cliff-jumper user who remarked on initial versions being formatted wrong, still visible here: https://github.com/favware/colorette-spinner/blob/739b0bbab3cf9c7b2c46b167df08b781f14af51a/CHANGELOG.md?plain=1#L5. Basically new never before published packages would get the URL part on new line as opposed to the version. WOOPS.
- This PR **only** includes non-code changes, like changes …
> build: fix git cliff config files

- packages/discord.js/src/structures/CommandInteractionOptionResolver.js
- packages/discord.js/typings/index.d.ts
This pull request resolves #7595.
1. `ApplicationCommandOptionChoice` is not the correct return type for `CommandInteractionOptionResolver#getFocused()`. The correct type didn't seem to exist, so one was created.
2. During autocomplete interactions, `CommandInteractionOptionResolver#resolved` was `undefined`. This is now `null` and typed accordingly.
3. The `CommandInteractionOptionResolver` isn't keen on its methods returning anything for autocomplete interactions. Data was simply not sent to us. Therefore, the appropriate useless methods have been removed from the typings.
- I know how …
> fix(CommandInteractionOptionResolver): Handle autocompletion interactions

- README.md
- packages/discord.js/README.md
- packages/discord.js/typings/index.d.ts
- packages/voice/examples/recorder/src/bot.ts
`isAutocomplete` was removed but it's still present in typings. So this pr removes it from typings. Also updated readme and example to use `isChatInputCommand` instead of `isCommand`.
> typings: remove isAutocomplete typeguard from typings

- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
A regression from #8021: performing `<ThreadMemberManager>.fetch()` would yield a return type of a singular thread member. This should be a collection of thread members.
> types(ThreadMemberManager): Fix return type of fetching members with no arguments

- packages/discord.js/src/managers/CategoryChannelChildManager.js
- packages/discord.js/src/managers/GuildChannelManager.js
- packages/discord.js/src/managers/GuildEmojiManager.js
- packages/discord.js/src/managers/GuildManager.js
- packages/discord.js/src/managers/GuildMemberManager.js
- packages/discord.js/src/managers/GuildMemberRoleManager.js
- packages/discord.js/src/managers/GuildStickerManager.js
- packages/discord.js/src/managers/RoleManager.js
- packages/discord.js/src/structures/BaseGuildTextChannel.js
- packages/discord.js/src/structures/BaseGuildVoiceChannel.js
- packages/discord.js/src/structures/Guild.js
- packages/discord.js/src/structures/GuildChannel.js
- packages/discord.js/src/structures/GuildEmoji.js
- packages/discord.js/src/structures/GuildMember.js
- packages/discord.js/src/structures/Role.js
- packages/discord.js/src/structures/StageChannel.js
- packages/discord.js/src/structures/Sticker.js
- packages/discord.js/src/structures/TextChannel.js
- packages/discord.js/src/structures/ThreadChannel.js
- packages/discord.js/src/structures/VoiceChannel.js
- packages/discord.js/src/structures/VoiceState.js
- packages/discord.js/src/structures/Webhook.js
- packages/discord.js/src/structures/interfaces/TextBasedChannel.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
Another (hopefully) more complete take on #7448
- `Guild#edit` now takes `reason` in the `data` parameter
- `GuildChannel#edit` now takes `reason` in the `data` parameter
- `GuildEmoji#edit` now takes `reason` in the `data` parameter
- `Role#edit` now takes `reason` in the `data` parameter
- `Sticker#edit` now takes `reason` in the `data` parameter
- `ThreadChannel#edit` now takes `reason` in the `data` parameter
- `ThreadChannel#create` now takes `name` in the `options` parameter
- `GuildChannelManager#create` now takes `name` in the `options` parameter
- `GuildChannelManager#createWebhook` now takes `channel` and `name` in the `options` parameter
- `GuildChannelManager#edit` now takes `reason` as a part of `data` …
> refactor(*): include name/reason/etc fields into options/data params

- packages/discord.js/src/managers/ApplicationCommandManager.js
Fixes default member permissions assignment when creating or editing application commands.
> fix(ApplicationCommand): fix default member permissions assignment

- packages/discord.js/src/managers/GuildEmojiManager.js
- packages/discord.js/src/managers/GuildStickerManager.js
- Added a more suitable description instead of "Options" for `GuildStickerManager#create()`
- Added back the missing `GuildEmojiCreateOptions` type definition.
> docs: Description and missing `@typedef` fixes

- packages/discord.js/src/structures/AutocompleteInteraction.js
- packages/discord.js/typings/index.d.ts
Implements #8018 into autocomplete interactions too.
<details>
<summary>Example autocomplete interaction data payload</summary>
```JavaScript
{
type: 1,
options: [ { value: 'dde', type: 3, name: 'name', focused: true } ],
name: 'travelling-spirit',
id: '982764979583324180',
guild_id: '982741752098222090'
}
```
</details>
> feat(AutocompleteInteraction): Add `commandGuildId`

- packages/discord.js/src/structures/CommandInteractionOptionResolver.js
- packages/discord.js/typings/index.d.ts
The type of AutocompleteOption#value was wrong so I went ahead and fixed that and also made the other properties more accurate (made focused not optional and type more specific).
> types(AutocompleteOption): fix and improve types

- packages/discord.js/src/client/actions/ApplicationCommandPermissionsUpdate.js
- packages/discord.js/typings/index.d.ts
Adds missing `ApplicationCommandPermissionsUpdate` to `Events` in typings.
Also fixes `ApplicationCommandPermissionsUpdateData#permissions` property to be an array.
> types: fix `ApplicationCommandPermissionsUpdate` event typings

- packages/discord.js/src/structures/AutocompleteInteraction.js
\<AutocompleteInteraction>.respond doesn't really resolve to anything. So that console.log is pretty pointless. I am still unsure of exactly why all the methods having a then and a catch is necessary. Regardless, I have looked at other methods and changed the example to what I think would be more appropriate. 
> docs(AutocompleteInteraction): change useless log in responds example 

- packages/discord.js/src/managers/ThreadMemberManager.js
`member` is required for `FetchThreadMemberOptions` (duh).
> docs(ThreadMemberManager): Require `member` in `FetchThreadMemberOptions`

- typings/index.d.ts
This pr fixes type of `GuildChannel#isText()` method
> types(GuildChannel): fix type of `.isText()` method

- src/structures/CommandInteractionOptionResolver.js
- typings/index.d.ts
This PR backports #8069 to v13. This will be breaking for TS users but the types were wrong to begin with, so it's a semver: patch
> types(AutocompleteOption): backport fix and improve types

- src/client/websocket/WebSocketShard.js
- src/util/Options.js
reset only when `sessionId` is null
> fix: destroy options during cleanup

- README.md
- packages/discord.js/README.md
As of #7909 discord.js re-exports everything from discord-api-types, so there's no need in installing it as a redundant dependency. 
> chore: remove -types import in readme example

- packages/discord.js/src/structures/BaseGuildTextChannel.js
`BaseGuildTextChannel#setType()` does not take a string, but rather, `ChannelType.GuildText | ChannelType.GuildNews` (which are numbers).
> docs(BaseGuildTextChannel): Update `setType()`'s parameter type

- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
#8088, but for the typings
`Pick<typeof ChannelType, 'GuildText'>` creates an object, `{ GuildText: 1 }`
> types: fix `setType()` parameter and `ChannelData.type`

- src/structures/ModalSubmitInteraction.js
Adds `isFromMessage()` method to ModalSubmitInteraction.
The typings have the method but it really doesn't exist.
When the v14 Modals PR was backported to v13, this method was missing.
(I don't know if this has much importance, but I open this PR to avoid the method error)
> fix(ModalSubmitInteraction): add `isFromMessage()` missing method

- packages/discord.js/src/structures/ApplicationCommand.js
An application command does not have `autocomplete` at the top level, so this check wasn't ever doing anything.
As for `dmPermission`, this was improperly being checked. `APIApplicationCommand` has `dm_permission` as an optional property, so this was checking `undefined` (if not provided) against the API's returned values which is always `true` or `false`, leading to a false check. In addition, `dm_permission` was not supported here and now it is!
> fix(ApplicationCommand): Remove `autocomplete` check at the top level and correctly check for `dmPermission`

- packages/discord.js/typings/index.d.ts
> types(ApplicationCommand): fix typo in setDMPermission

- packages/discord.js/src/structures/InteractionWebhook.js
- packages/discord.js/src/structures/Webhook.js
- packages/discord.js/typings/index.d.ts
webhooks inherently can't cache messages & the way the library currently works is by attempting to cache messages if an APIMessage was returned from using `send`, `editMessage` or `fetchMessage`, but incorrectly makes the assumption that the client is the actual bot client, not a WebhookClient, so caching doesn't work in the first place. (#7917) 
in the event that the bot client already has the channel cached, it will already cache a message because of the information provided by the gateway. basically it's messy
- I know how to update typings and have done so, or typings don't need …
> fix(webhooks): revert webhook caching (and returning Message)

- packages/discord.js/src/util/Options.js
- packages/discord.js/typings/index.d.ts
- discord/discord-api-docs#5058
- https://github.com/discord/discord-api-docs/pull/5067
> refactor(ClientOptions): remove `$` prefix from `ws.properties` keys

- src/util/Options.js
- typings/index.d.ts
- https://github.com/discordjs/discord.js/pull/8094#issuecomment-1155549091
- https://github.com/discord/discord-api-docs/pull/5067
> refactor: deprecate `$` prefix from `ws.properties` keys

- packages/discord.js/src/structures/GuildAuditLogs.js
- packages/discord.js/src/structures/GuildAuditLogsEntry.js
- packages/discord.js/typings/index.d.ts
- `AuditLogAction` was missing in the documentation. This has been readded
- `GuildAuditLogsEntry.actionType()`'s parameter was incorrectly documented. This has been fixed to `AuditLogEvent`
- `GuildAuditLogsEntry.targetType()`'s parameter was incorrectly documented. This has been fixed to `AuditLogEvent`
- Renamed `GuildAuditLogsTarget` to `GuildAuditLogsTargetType` for consistency
> docs(GuildAuditLogs): Fix and reimplement type definitions

- packages/discord.js/src/managers/GuildManager.js
- packages/discord.js/src/managers/GuildScheduledEventManager.js
- packages/discord.js/src/managers/StageInstanceManager.js
- packages/discord.js/src/managers/ThreadManager.js
- packages/discord.js/src/structures/ClientUser.js
- packages/discord.js/src/structures/Guild.js
- packages/discord.js/src/structures/GuildScheduledEvent.js
- packages/discord.js/src/util/Constants.js
- packages/discord.js/typings/index.d.ts
- Many enums still were in union with `number`. This has been removed
- Typings for creating channels whilst creating a guild were fixed to not include directory channels or forum channels. The documentation reflects this
- `GuildDefaultMessageNotificationLevel` did not exist. This has been corrected to `GuildDefaultMessageNotifications`
- `GuildExplicitContentFilterLevel` did not exist. This has been corrected to `GuildExplicitContentFilter`
- `ThreadChannelTypes|number` wasn't the correct type to show in the documentation. This is now a union of possible types
- `TextBasedChannelTypes` was not documented as an array
- Code changes have been tested against the Discord API, …
> docs: Remove `number`s from enums

- packages/discord.js/src/structures/Message.js
- packages/discord.js/src/structures/MessagePayload.js
Some places incorrectly used the class `TextBasedChannel` instead of `TextBasedChannels`.
> docs: `TextBasedChannel` -> `TextBasedChannels` typos

- packages/discord.js/src/util/PermissionsBitField.js
The class is called `PermissionsBitField`, not `Permissions`. This was causing the following message to appear:
```xl
"bitfield" (member of "Permissions", packages/discord.js/src/util/PermissionsBitField.js:50) has no accessible parent.
```
> docs(PermissionsBitField): Fix `@name` of bitfield

- packages/proxy-container/package.json
- packages/proxy/package.json
- yarn.lock
Crawl is gonna hate me for this.
This PR:
1) bumps `@discordjs/proxy` in proxy-container. this was meant to be done right after #8000 but I guess we just didn't.
2) fixes an oversight I had yesterday with #8113 - indeed! `@discordjs/rest` should not have used the workspace protocol, I was even asked about this. I was thinking of version conflicts and things like that and completely forgot about the Docker build aspect.
3) as a result of 2, I also had to lock `@discordjs/rest` to an NPM build in `proxy` - otherwise we'd get a version miss match and the code wouldn't build.
To whoever merges this, please also dispatch the dev docker deploy workflow just to confirm everything finally works.
> fix(proxy-container): proper deps

- packages/discord.js/typings/index.d.ts
This PR fixes the typing for the event name `Shard#reconnecting` it should be merged to avoid confusing users that use TS and other features like Intellisense that rely on these typings.
Bug-fix
- Code changes have been tested against the Discord API, or there are **no code changes**
- **I know how to update typings** and have done so, or typings don't need updating
> types(Shard#reconnecting): fix event name

- typings/index.d.ts
See #8118 
Targets v13 branch instead of stable
> typings(Shard#reconnecting): Backport to v13 - Fix event name

- packages/discord.js/src/client/websocket/WebSocketManager.js
- packages/discord.js/src/errors/Messages.js
`ErrorCodes.AuthenticationFailed` did not exist, causing discord.js to crash when attempting to connect to the gateway. This resolves #8137.
> fix(WebSocketManager): Correct error name

- packages/discord.js/src/structures/interfaces/InteractionResponses.js
remnant of #7917 #8038, both prs missed it whoops.
allows for `ChatInputCommandInteraction.editReply`, `fetchReply`, etc. to actually show *only* `Message` as a return
> docs(InteractionResponse): fix return

- packages/builders/package.json
- packages/builders/src/interactions/slashCommands/Assertions.ts
- yarn.lock
this pr replaces @sindresorhus/is with shapeshift.
> refactor: remove @sindresorhus/is as it's now esm only

- packages/discord.js/src/structures/Message.js
- packages/discord.js/src/structures/ThreadChannel.js
- packages/discord.js/src/util/APITypes.js
- packages/discord.js/typings/index.d.ts
discord.js's `ThreadAutoArchiveDuration` was basically the same as discord-api-types's `ThreadAutoArchiveDuration`. So moving forward, it'd be great to use discord-api-types's `ThreadAutoArchiveDuration` to prefer enums.
I've also removed the "in minutes" text on some descriptions as the enum uses "OneDay", "OneHour" etc. which may cause confusion and also to discourage one from setting magic numbers.
> types: Use `ThreadAutoArchiveDuration` from discord-api-types

- packages/discord.js/src/client/websocket/WebSocketManager.js
- packages/discord.js/src/errors/DJSError.js
- packages/discord.js/src/errors/Messages.js
Fixes #8148
The ws magic:tm: passes strings to the Error constructor, which then passes said string to the `message()` function, which only accepts numbers
https://github.com/discordjs/discord.js/blob/a3799f9ebb027904830457119708d550e2009200/packages/discord.js/src/client/websocket/WebSocketManager.js#L248-L249
https://github.com/discordjs/discord.js/blob/a3799f9ebb027904830457119708d550e2009200/packages/discord.js/src/errors/DJSError.js#L15-L17
https://github.com/discordjs/discord.js/blob/a3799f9ebb027904830457119708d550e2009200/packages/discord.js/src/errors/DJSError.js#L39-L40
However, the (string) error codes passed by the WS are defined
https://github.com/discordjs/discord.js/blob/a3799f9ebb027904830457119708d5 …
> fix(DJSError): error code validation

- packages/discord.js/src/client/websocket/WebSocketShard.js
This PR (hopefully) fixes an uncaught exception happening when closing a WebSocket connection before it established a connection by attaching a noop error handler.
The connection was being destroyed by either the hello timeout or an attempt to send a packet without an open connection.
The then called method, `destroy`, removed the  error handler a statement before closing the connection, here:
https://github.com/discordjs/discord.js/blob/a3799f9ebb027904830457119708d550e2009200/packages/discord.js/src/client/websocket/WebSocketShard.js#L804-L807
I'm not sure if there is a reason to remove the listeners, maybe this issue could also be addressed by not calling `_cleanupConnection` there.
(The error is emitted next …
> fix(WebSocketShard): keep an error handler on connections

- packages/discord.js/src/util/Channels.js
This removes `createChannel()` from the documentation (which is completely blank) and adds some internal documentation to the method instead. This method is not meant for public use.
> docs(Channels): internally document channel creation

- packages/discord.js/typings/index.d.ts
Fixed an issue where the modal builder constructor was using the returned modal data instead of the input modal data.
> types: fix modal builder constructor data type

- packages/actions/tsconfig.eslint.json
- packages/builders/__tests__/messages/formatters.test.ts
- packages/builders/tsconfig.eslint.json
- packages/collection/tsconfig.eslint.json
- packages/docgen/tsconfig.eslint.json
- packages/proxy-container/tsconfig.eslint.json
- packages/proxy/tsconfig.eslint.json
- packages/rest/tsconfig.eslint.json
- packages/scripts/tsconfig.eslint.json
- packages/voice/tsconfig.eslint.json
- packages/website/tsconfig.eslint.json
.eslintrc.json is smart and loads from the local config based on the project parameter at root, tsconfig.eslint.json is not so smart, so it was ignoring the tsconfig from any given package
> revert: refactor: move eslint.tsconfig.json to root

- packages/discord.js/src/util/Constants.js
- packages/discord.js/typings/index.d.ts
Fixes the type for `SweeperKeys` from #8156.
> docs(Constants): fix SweeperKeys type

- packages/voice/__tests__/SpeakingMap.test.ts
- packages/voice/src/VoiceConnection.ts
- packages/voice/src/audio/AudioPlayer.ts
- packages/voice/src/networking/VoiceUDPSocket.ts
- packages/voice/src/receive/SSRCMap.ts
- packages/voice/src/receive/SpeakingMap.ts
d4b41dd0815b493b599d4f4d1b6dd18cd99f91ea commits removed all typed events for compatible with `docgen` I guess. But `AudioPlayer` event types are broken. That's why I bring back all removed typed events.
> types(voice): bring back typed events

- src/managers/ApplicationCommandManager.js
- src/structures/ApplicationCommand.js
- typings/index.d.ts
- typings/index.test-d.ts
- Backports the new command structure and creation of commands from the following pr to v13
- #7857  
- Deprecates `defaultPermission`
- Fixes `ApplicationCommand.edit()` and `ApplicationCommandManager.edit()` requiring `name` and `description` options
> feat: partially backport perms v2 for v13

- packages/discord.js/src/managers/ApplicationCommandManager.js
- packages/discord.js/src/structures/ApplicationCommand.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
- `edit()` already supported this
https://github.com/discordjs/discord.js/blob/70b42bb64a4f83da0da242569b9c7921c8d1e26f/packages/discord.js/src/managers/ApplicationCommandManager.js#L236-L240
https://github.com/discordjs/discord.js/blob/70b42bb64a4f83da0da242569b9c7921c8d1e26f/packages/discord.js/src/structures/ApplicationCommand.js#L195
- Fixes `ApplicationCommand.edit()` and `ApplicationCommandManager.edit()` requiring `name` and `description` options
> fix: edit() data can be partial and `defaultMemberPermissions` can be `null`

- packages/discord.js/src/client/WebhookClient.js
- packages/discord.js/src/util/Util.js
- packages/discord.js/typings/index.d.ts
This PR moves the URL parsing part out of the `WebhookClient` constructor and instead makes it a util
> feat(util): parseWebhookURL

- src/structures/Interaction.js
- typings/index.d.ts
> feat(interaction): add `appPermissions` (v13)

- packages/discord.js/src/structures/BaseInteraction.js
- packages/discord.js/typings/index.d.ts
Adds support for `app_permissions` field on Interaction payloads.
- https://github.com/discord/discord-api-docs/pull/5131
- https://github.com/discordjs/discord-api-types/pull/509
> feat(BaseInteraction): add support for `app_permissions`

- packages/discord.js/src/managers/ApplicationCommandManager.js
This fixes an oversight from #7684, where the `URLSearchParams` would be built with conditionals. We use `makeURLSearchParams` everywhere else, so let's make it consistent.
> refactor(ApplicationCommandManager): use `makeURLSearchParams`

- packages/discord.js/src/managers/GuildChannelManager.js
- packages/discord.js/src/structures/GuildChannel.js
- packages/discord.js/typings/index.d.ts
`ChannelEditData` did not exist in the documentation. It seems in the typings that `ChannelData`'s sole purpose was to be extended. So I've consolidated them into a singular, more up-to-date name called `GuildChannelEditOptions`.
> types: Implement `GuildChannelEditOptions`

- src/managers/GuildStickerManager.js
This PR fixes a typo that causes an error when `GuildStickerManager,fetchUser` is called. This PR should be merged to allow the method to be used without error.
bug-fix
> fix(GuildStickerManager.fetchUser): Changed guildId to guild.id

- .github/workflows/test.yml
- codecov.yml
- package.json
- packages/actions/package.json
- packages/actions/src/uploadCoverage/action.yml
- packages/builders/package.json
- packages/collection/package.json
- packages/docgen/package.json
- packages/proxy/package.json
- packages/rest/package.json
- packages/scripts/package.json
- packages/website/package.json
- vitest.config.ts
Moves test scripts to package level so that coverage can be reported per package.
> **Warning**
> For some reason yarn won't find vitest when trying to run yarn test in a package directory, but npx does 🤷 
Adds codecov as follows:
- Project level status reports only for now, set to informational to not fail CI at the moment. If we ever do enable patch status reports, we should probably only do it at the global level.
- Per package somewhat strict on coverage droop but as a whole a little more lenient
- Package separation is done via flags, packages that don't yet have coverage are automatically skipped (action is smart)
- Codecov will only post a report on PRs affecting coverage since there will be many that don't …
> feat: codecov

- packages/discord.js/src/structures/ApplicationCommand.js
- packages/discord.js/typings/index.d.ts
this pr adds min-max length support for string option
> feat(applicationCommand): add max min length in string option

- packages/discord.js/src/structures/Message.js
Documents breaking change for `Message#interaction`.
Source Docs:
> Starting **July 18, 2022**, the `name` field for message interaction objects will now include subcommands and subcommand groups in the value (along with the existing top-level command). In the future, we recommend not relying on this message interaction field.
https://github.com/discord/discord-api-docs/blob/main/docs/Change_Log.md#add-subcommand-groups-and-subcommands-to-message-interaction-objects
Inspiration for new description:
https://github.com/discord/discord-api-docs/pull/5140/files#diff-b44c2bafd9f1fb4cd3383e25770ef07d972796aa56dedd73ba1a7853df2d62d0R117
- This PR **only** includes non-code …
> docs(MessageInteraction#commandName): updated description

- packages/discord.js/src/managers/ApplicationCommandManager.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
- Fixes #8208 
- Explicitly allow passing JSON-encodable items to `create()`, `edit()`, and `set()` - via `transformCommand()`
- Fixed the return type of the `transformCommand()` method (typings)
- Fixed the type of the `data` parameter on `edit()` of `GuildApplicationCommandManager`, which was missed in:
- #8163
> fix(ApplicationCommandManager): explicitly allow passing builders to methods

- packages/discord.js/src/util/Util.js
Doing multiple `.replace` risks subsequent calls from running in the previous replaces, and this also comes with an extra performance impact where the content is scanned 3 times, and then each mention is scanned and replaced *again* to get the ID. This is a much simpler approach that uses a single call and RegExp capture groups to avoid extra processing.
The PR is https://github.com/discordjs/discord.js/labels/semver%3Amajor because it changes the matching ID in mentions from `[0-9]+` to the much stricter and safer `\d{17,19}`, which may result on different results if somebody injects arbitrary IDs outside the valid range in Discord's API.
- Code changes have been tested …
> refactor(Util): make single `replace` call in `cleanContent`

- packages/discord.js/src/structures/MessagePayload.js
- packages/discord.js/src/util/Util.js
- packages/discord.js/typings/index.d.ts
If a user specified `allowedMentions.replied_user`, it would be erroneously replaced with `allowedMentions.repliedUser`, which may not exist. This PR fixes that by checking against `allowedMentions.repliedUser`'s existence, and does no operation (nor a clone) if it's not specified.
Also removed `cloneObject` since that was the last instance of it.
> fix(MessagePayload): guard against `repliedUser` property

- packages/discord.js/src/structures/GuildTemplate.js
- packages/discord.js/src/structures/Invite.js
- packages/discord.js/src/structures/MessageMentions.js
- packages/discord.js/src/util/DataResolver.js
- packages/discord.js/typings/index.d.ts
Resolves #8175 by removing the global flag on regular expressions. Some are now imported from discord-api-types and they all used named capturing groups now.
> fix: Remove global flag on regular expressions

- packages/discord.js/src/structures/SelectMenuBuilder.js
- packages/discord.js/typings/index.d.ts
Fixes issue where djs builders wouldn't properly handle select menu option builders passed into a select menu builder.
> fix(`SelectMenuBuilder`): properly accept `SelectMenuOptionBuilder`s

- packages/discord.js/src/client/websocket/WebSocketManager.js
- packages/discord.js/src/client/websocket/WebSocketShard.js
- packages/discord.js/src/index.js
- packages/discord.js/src/sharding/Shard.js
- packages/discord.js/src/util/ShardEvents.js
- packages/discord.js/src/util/WebSocketShardEvents.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
- Renamed the current `ShardEvents` to `WebSocketShardEvents`, as they are the events of the `WebSocketShard` class
- Added `ShardEvents`, which are the events of the `Shard` class
> refactor: make `ShardEvents` the events of `Shard`

- packages/discord.js/typings/index.d.ts
This method does not return `void`. It always returns a `GuildMember`.
> types(GuildMemberManager): Non-void return of `edit()`

- typings/index.d.ts
Backports #8186 to version 13.
> types(GuildMemberManager): Non-void return of `edit()` (v13)

- src/managers/ApplicationCommandManager.js
This PR fixes a small bug in Application Command Managers that made the query parameter to never be passed down to the URL itself. *Yay for backporting pains*
> fix: pass in the expected query object type for application commands

- package.json
- packages/actions/package.json
- packages/builders/package.json
- packages/collection/package.json
- packages/docgen/package.json
- packages/proxy/package.json
- packages/rest/package.json
- packages/scripts/package.json
- packages/website/package.json
- yarn.lock
- Upgraded `vitest` to `0.17.0` 
- Added it as a `devDependency` on the packages that use it, to allow running scripts on individual workspaces
> chore: upgrade `vitest` and add it as dep on each workspace

- packages/collection/src/index.ts
This aligns the error message thrown by `Collection#ensure`, when the `defaultValueGenerator` is not a function, with the other ones thrown in the class (which are already the same as the ones thrown by the native Array).
I found this out when working on #8222 
Some examples:
https://github.com/discordjs/discord.js/blob/c7a205f7b992eea43af13a4638e2a03db7bc0d8a/packages/collection/src/index.ts#L243
https://github.com/discordjs/discord.js/blob/c7a205f7b992eea43af13a4638e2a03db7bc0d8a/packages/collection/src/index.ts#L322
https://github.com/discordjs/discord.js/blob/c7a205f7b992eea43af13a4638e2a03db7bc0d8a/packages/collection/src/index.ts#L413
This *could* be a major change, …
> fix(Collection): make error messages consistent

- packages/voice/src/receive/SpeakingMap.ts
The names of this event did not exist when parsed by the documentation generator (`'start' | 'end'`). It seems when splitting this overload out, the names are detected. This will allow the main voice documentation to load again.
> fix(SpeakingMap): Allow docgen to detect event name

- src/structures/ApplicationCommand.js
- typings/index.d.ts
> feat(ApplicationCommand): add `min_length` and `max_length` for string option (v13)

- packages/builders/__tests__/interactions/SlashCommands/Options.test.ts
- packages/builders/package.json
- packages/builders/src/interactions/slashCommands/options/string.ts
- packages/discord.js/package.json
- packages/rest/package.json
- packages/voice/package.json
- yarn.lock
- discord/discord-api-docs#5150
> feat(builder): add max min length in string option

- packages/discord.js/typings/index.d.ts
Changes `Events` ~~and `Colors`~~ to be an enum in the typings.
Motivation to convert `Events` to an enum stems from `ShardEvents` having similar usage: already being an enum, and `Events` is used as an enumerable object already.
~~The motivation to convert `Colors` to an enum is since it is also an enumerable object.~~
> types: convert `Events` to an enum

- src/structures/Presence.js
- typings/index.d.ts
Instead of just boring `number`, I added Documentation for `MessageActivity` (same as v14-dev)
> docs: Add `MessageActivityType` (v13)

- packages/discord.js/typings/index.d.ts
#7526 had `GuildMemberManager#fetchMe()`'s typings placed under `Guild`. This led to false assumptions.
> types(GuildMemberManager): Fix placement for `fetchMe()`

- packages/discord.js/src/structures/GuildAuditLogsEntry.js
Similarly to the switch from `string`s to `number`s in v14, this PR changes `GuildAuditLogsEntry.action` to return an `AuditLogEvent` rather than the string version of the action.
> refactor: make `GuildAuditLogsEntry.action` return an `AuditLogEvent`

- packages/builders/cliff.toml
- packages/collection/cliff.toml
- packages/discord.js/cliff.toml
- packages/proxy-container/cliff.toml
- packages/proxy/cliff.toml
- packages/rest/cliff.toml
- packages/voice/cliff.toml
Git Cliff released version 0.8.0 with a breaking change for how footers have to be parsed that affected the configs. As an added bonus the breaking changes will also show up better now in the changelogs so this is a win-win.
Note that after this change git-cliff v0.8.x is required. No changes/updates to cliff-jumper are necessary as that just calls `git cliff`.
> chore: update Git Cliff TOMLs

- packages/actions/package.json
- packages/builders/package.json
- packages/collection/package.json
- packages/discord.js/package.json
- packages/docgen/package.json
- packages/proxy-container/package.json
- packages/proxy/package.json
- packages/rest/package.json
- packages/scripts/package.json
- packages/voice/package.json
- packages/website/package.json
Opting to remove this option as uncommonly, `yarn lint` picks up, for example, a formatting issue that `yarn format` will not resolve due to the caching.
> chore: Remove `--cache`

- src/managers/GuildChannelManager.js
Backports #8296 to version 13.
> fix(GuildChannelManager): Access `resolveId` correctly (v13)

- packages/builders/__tests__/interactions/SlashCommands/SlashCommands.test.ts
- packages/builders/src/interactions/slashCommands/Assertions.ts
Explicitly adds the letter unicode properties to the slash command name regex, because the negated `{Lu}` resulted in the regex matching _any_ character except uppercase letters.
**Old regex:**
**New regex:**
> fix: slash command name regex

- packages/voice/src/receive/VoiceReceiver.ts
close #7647
This PR fixes the way @discordjs/voice strips RTP Header Extension in opus packet. See #7647 for details.
I have encountered a bug that this bug is responsible for.
~~*I still have to test this PR to check if this PR is valid.*~~ I have checked the minimum required test using locally built package.
> fix(VoiceReceiver): parsePacket correctly

- packages/discord.js/typings/index.d.ts
This was removed in #7736, but then was readded in #7716, likely due to the rebase
This type is not used and outdated
> types: remove `MemberMention`

- packages/discord.js/src/structures/MessagePayload.js
- packages/discord.js/src/util/DataResolver.js
- packages/discord.js/typings/index.d.ts
- packages/rest/package.json
- packages/rest/src/lib/RequestManager.ts
- yarn.lock
This PR adds a `type` to our `Blob`s that we use when we send files. As it turns out, Discord does *NOT* check for magic bytes, so for endpoints such as sticker creation that check for a png/apng file, if the content-type isn't precisely set to `image/png`, they will yield a 400.
For ref on the sticker endpoint, this worked fine in v13 since we actually hard coded the Content-Type to be an image, but this is not a great solution. If an endpoint that takes, say, only gifs were to be added, we'd be running into essentially the same problem.
We try our best to infer this:
- when passing in a URL, we'll read the `Content-Type` from the response
- if a Buffer was passed in without a content type, we use a 3rd party pkg …
> refactor(rest): add content-type(s) to uploads

- packages/discord.js/src/managers/PermissionOverwriteManager.js
Prevent the mutation of the user/role as it's passed into upset. 
The user passed into upset would always be of type "User" preventing the use of "GuildMember" in upset. 
It's only noticed if you have User cache disabled and only wish to use guild member cache, this fixes that limitation by passing along the original data. 
> fix(PermissionOverwriteManager): mutates user

- packages/discord.js/src/structures/Component.js
- packages/discord.js/src/structures/InteractionResponse.js
`Component` and `InteractionResponse` were not showing up in the sidebar in the documentation. Remove the documentation on the constructors resolves this.
> docs: Remove `@private` constructor documentation

- packages/discord.js/src/client/WebhookClient.js
- packages/discord.js/src/structures/Webhook.js
- packages/discord.js/typings/index.d.ts
- packages/discord.js/typings/index.test-d.ts
This is the part that matters (from the `send()` method). The other methods have (more or less) the same implementation
https://github.com/discordjs/discord.js/blob/33ae7df000f809d1534baacb4353d81b01811c9a/packages/discord.js/src/structures/Webhook.js#L215-L216
The only instance where `this.client.channels` will not exist is on the `WebhookClient` class, given that `WebhookClient#client` is a circular reference to itself. `Webhook#client` and `InteractionWebhook#client` is the `Client`
https://github.com/discordjs/discord.js/blob/33ae7df000f809d1534baacb4353d81b01811c9a/packages/discord.js/src/client/WebhookClient.js#L28
- I know how to update typings and have done so, or …
> docs: align webhook method return types with implementation

- packages/discord.js/typings/index.d.ts
This PR fixes the type of all the props using the GuildFeature enum to allow feature strings to be passed along and not limit that to enum properties only. This is the only situation where raw data received from Discord is passed as it is, so using the feature strings is correct and safe. This also mimics the behavior in v13
> types(GuildFeature): allow feature strings to be passed

- packages/discord.js/src/sharding/ShardingManager.js
- packages/discord.js/src/util/Util.js
- packages/discord.js/typings/index.d.ts
This PR renames the `Util#fetchRecommendedShards` method to `Util#fetchRecommendedShardCount` because it does not fetch shard data but only a count, which could lead to a misinterpretation of its purpose.
> refactor(Util)!: rename `fetchRecommendedShards`

- packages/discord.js/src/managers/ApplicationCommandManager.js
- packages/discord.js/src/structures/ApplicationCommand.js
`defaultMemberPermissions` can be `0n`, and it was being passed as a bigint to JSON.stringify(), which doesn't know how to serialize them
> fix(ApplicationCommandManager): allow passing 0n to defaultMemberPermissions

- packages/discord.js/src/client/BaseClient.js
- packages/discord.js/src/client/Client.js
This PR changes `Client#toJSON` (and `BaseClient#toJSON`) to
- Remove references to properties that are either no longer on the class or won't get included in the resulting json anyway
- Are private (and cause an error due to indefinitely recursing) and shouldn't be included in the resulting json
> fix(Client): omit private properties from toJSON

- packages/discord.js/src/structures/Presence.js
`Activity#createdTimestamp` was always `NaN` as it was calling `Date.parse()` on something that was always a [Unix timestamp](https://discord.com/developers/docs/topics/gateway#activity-object-activity-structure).
> fix(Presence): Do not return NaN for activity timestamp

- README.md
- packages/actions/README.md
- packages/builders/README.md
- packages/collection/README.md
- packages/discord.js/README.md
- packages/docgen/README.md
- packages/proxy-container/README.md
- packages/proxy/README.md
- packages/rest/README.md
- packages/scripts/README.md
- packages/voice/README.md
- packages/website/README.md
Ensures the Vercel logo appears on the documentation.
> chore: Use raw GitHub link to show Vercel logo on website

- src/structures/MessageEmbed.js
- typings/index.d.ts
should have been done before 14 released 
> refactor(embed): deprecate addField

- packages/docgen/src/interfaces/var-type.interface.ts
- packages/docgen/src/types/var-type.ts
The following pages don't have anything for their return value:
- https://discord.js.org/#/docs/discord.js/main/typedef/CacheFactory
- https://discord.js.org/#/docs/discord.js/main/typedef/GlobalSweepFilter
- https://discord.js.org/#/docs/discord.js/main/typedef/CollectorFilter (page fails to load)
This pull request resolves this.
> fix: Ensure returns for function type definitions

- packages/discord.js/src/sharding/ShardClientUtil.js
Currently, if something goes wrong here, we don't get a proper error, because `Error` here refers to our error class. This is meant to throw a global `Error`. This is likely caused because of #8068
https://github.com/discordjs/discord.js/blob/df42fdfc421f1190f0a2267a66efd3c921ec2348/packages/discord.js/src/sharding/ShardClientUtil.js#L208-L210
> fix(ShardClientUtil#_respond): construct global error

- packages/builders/__tests__/components/selectMenu.test.ts
- packages/builders/src/components/Assertions.ts
- packages/builders/src/components/selectMenu/SelectMenu.ts
Fixes an issue where select menu builders would say json options were invalid despite allowing json types.
> fix(selectMenu): allow json to be used for select menu options

- packages/discord.js/src/structures/GuildAuditLogsEntry.js
- This PR fixes a bug with GuildAuditLogsEntry.extra, since the overwrite type is a string and the wrong enum was used.
> fix(GuildAuditLogsEntry): replace OverwriteType with AuditLogOptionsType

- packages/discord.js/src/structures/ThreadChannel.js
Thread channels incorrectly had this method applied to the class. This should not be the case.
> fix(ThreadChannel): Omit webhook fetching

- packages/discord.js/typings/index.d.ts
https://github.com/discordjs/discord.js/pull/8345#pullrequestreview-1048618022
> types(GuildAuditLogsEntryExtraField): Use `AuditLogOptionsType`

- packages/ws/src/ws/WebSocketShard.ts
It seems `CONNECTING` and `OPEN` should be accessed via `WebSocket` here in ESM. This pull request resolves #8356.
> fix(WebSocketShard): Use correct import

- packages/discord.js/src/structures/BaseInteraction.js
- packages/discord.js/typings/index.d.ts
This restores the following typeguard methods:
- `BaseInteraction#isAutocomplete()`
- `BaseInteraction#isCommand()`
- `BaseInteraction#isMessageComponent()`
- `BaseInteraction#isModalSubmit()`
While I agree with the _principle_ that helper methods should not be provided where single equality checks suffice (e.g. channel typing) that principle cannot be consistently applied to Interaction types. For that reason, I believe having a consistent and intuitive library interface should take a higher priority.
Closes https://github.com/discordjs/discord.js/issues/8321 if …
> feat: restore missing typeguards

- packages/discord.js/src/client/Client.js
- packages/discord.js/src/client/actions/InviteCreate.js
- packages/discord.js/src/client/actions/InviteDelete.js
- packages/discord.js/src/client/actions/ThreadMembersUpdate.js
- packages/discord.js/src/client/actions/UserUpdate.js
- packages/discord.js/src/managers/GuildMemberManager.js
- packages/discord.js/src/managers/PermissionOverwriteManager.js
- packages/discord.js/src/managers/ThreadManager.js
- packages/discord.js/src/managers/ThreadMemberManager.js
- packages/discord.js/src/structures/GuildChannel.js
- packages/discord.js/src/structures/Message.js
- packages/discord.js/src/structures/PermissionOverwrites.js
- packages/discord.js/src/structures/Role.js
- packages/discord.js/src/structures/ThreadChannel.js
- packages/discord.js/src/structures/Webhook.js
Updates documentation strings and examples with PascalCase enums.
This was done just using a regex searching for all-caps strings, so feel free to point out any others I might have missed.
> docs: update docs and examples to PascalCase links

- .commitlintrc.json
Backports #7507 to version 13.
> chore: disable scope-case rule for commitlint (v13)

- packages/discord.js/src/managers/GuildChannelManager.js
This PR fixes the ability of `GuildChannelManager#edit` (and indirectly `GuildChannel#edit` as well as `BaseGuildVoiceChannel#setRTCRegion`) to unset the rtc region by providing `null`.
The cause for this was that the method was using `??` to default to the current value if the provided value was missing or nullish.
(Why are we even sending the current values back? They are optional. 🤔 )
> fix(GuildChannelManager): allow unsetting rtcRegion

- packages/discord.js/src/managers/PermissionOverwriteManager.js
- packages/discord.js/typings/index.d.ts
Modifies `GuildChannelOverwriteOptions`'s `type` to use the `OverwriteType` enumeration.
> refactor(PermissionOverwriteManager): Use `OverwriteType`
