packages/discord.js/src/client/WebhookClient.js, packages/discord.js/src/util/Util.js
`WebhookClientData` is now a union of two possible objects rather than one object containing all the properties. This reflects the typings exactly and also introduces `WebhookClientDataIdWithToken` & `WebhookClientDataURL` in the documentation which also reflects the typings exactly.
This also fixes an issue where the return type of the top-level function `parseWebhookURL()` documented the id as a `string` instead of a `Snowflake`.
=> docs(WebhookClient): Make constructor a union

packages/builders/__tests__/messages/formatters.test.ts, packages/builders/src/messages/formatters.ts
Adds a newline at the end of the codeblock, fixes #8368.
=> fix(Formatters): add newline in `codeBlock`

packages/discord.js/src/client/actions/InviteCreate.js, packages/discord.js/src/client/actions/InviteDelete.js, packages/discord.js/src/client/actions/ThreadMembersUpdate.js, packages/discord.js/src/managers/GuildMemberManager.js, packages/discord.js/src/managers/ThreadManager.js, packages/discord.js/src/managers/ThreadMemberManager.js, packages/discord.js/src/structures/GuildChannel.js, packages/discord.js/src/structures/Message.js, packages/discord.js/src/structures/Presence.js, packages/discord.js/src/structures/Role.js, packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/src/structures/Webhook.js, packages/discord.js/src/util/Options.js
- Standardises requirements for an event, method or property (This event/method/property requires the...)
- Places requirements in info tags to be more visible
- Links don't work in in-line code which caused [`Client#event:inviteDelete`](https://discord.js.org/#/docs/discord.js/main/class/Client?scrollTo=e-inviteDelete) to break
- Typo in [`Activity#toString()`](https://discord.js.org/#/docs/discord.js/main/class/Activity?scrollTo=toString)
=> docs: Use info blocks for requirements

packages/discord.js/src/structures/interfaces/InteractionResponses.js
The `@returns` of this method was not documented, so it showed up as `void` on the documentation instead of `Promise<void>`.
=> docs(InteractionResponses): Add `showModal()` return type

packages/builders/src/messages/formatters.ts, packages/collection/src/collection.ts
new docs site doesn't support `[name](link)`. So changed them to link tags
=> docs: use link tags

packages/builders/src/messages/formatters.ts, packages/collection/src/collection.ts
Previous PR forgot the `|` seperator for link text. Ref: https://tsdoc.org/pages/tags/link/
=> fix: use proper format for `@link` text

packages/discord.js/src/structures/MessageMentions.js, packages/discord.js/typings/index.d.ts
Fixes #8201
- The `ignoreRepliedUser` option was not being respected when paired with `ignoreDirect: false`
- Added a `parsedUsers` getter, which parses user mentions from the message content to address the following comment:
- https://github.com/discordjs/discord.js/pull/8202#issuecomment-1172209705
- Moved the `ignoreEveryone` condition to the top as the other options don't affect it
=> fix(MessageMentions): `ignoreRepliedUser` option in `has()`

src/structures/MessageMentions.js, typings/index.d.ts
=> fix(MessageMentions): `ignoreRepliedUser` option in `has()` (v13)

README.md, packages/discord.js/README.md, packages/discord.js/src/index.js, packages/discord.js/typings/index.d.ts
This PR exports all things from `@discordjs/rest`. `@discordjs/rest` is also a part of `discord.js` like `@discordjs/builders` or `@discordjs/collection`. This will simplify the interaction with `discord.js` and will also provide types from `@discordjs/rest` for TypeScript users.
=> chore: reexport rest

packages/actions/build.config.ts, packages/actions/package.json, packages/actions/src/formatTag/action.yml
`unbuild` uses `.cjs` extension which is failing docs workflows. But how it was passing earlier?
=> chore: fix file path

packages/discord.js/src/errors/DJSError.js, packages/discord.js/src/errors/ErrorCodes.js, packages/discord.js/typings/index.d.ts
You currently can't compare against `error.code` using the enum. This was an oversight from the error refactor I did a while back.
This is *technically* breaking (but will just be labeled a patch since as the enum was, no matter how you used it, it basically did nothing), but it's the best thing we can get.
In the future, we'll return back to a proper enum for the error codes.
=> fix(errors): error codes

packages/ws/src/ws/WebSocketShard.ts
This PR modifies `WebSocketShard#onError` to emit the received error directly instead of wrapping it in an object causing something like this:
`Uncaught Error UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".`
=> fix(WebSocketShard): emit errors directly instead of objects

packages/ws/src/ws/WebSocketShard.ts
If the connection closes with a 1000 code before the shard is ready, the shard would end up in a state where it wouldn't attempt to reconnect any further.
This PR fixes this by simply always reconnecting when the connection was closed with a 1000 code.
---
The other case that came up internally, 1006 close codes, are already appropriately handled by the `default` case.
I could implement a custom one to change the debug message if that is wanted.
=> fix(WebSocketShard): always reconnect on disconnected with 1000

packages/discord.js/src/structures/Guild.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/1512
=> feat(Guild): Add `max_video_channel_users`

packages/discord.js/src/util/DataResolver.js
[Buffer.concat(Array\<string>)](https://nodejs.org/docs/latest-v16.x/api/buffer.html#static-method-bufferconcatlist-totallength) is not a thing and we get an error when using a `Stream`.
=> fix(DataResolver): make `Buffer` from string

packages/discord.js/src/structures/AttachmentBuilder.js
Changes the type in the JSDoc for AttachmentBuilder to fix #8407
=> docs(AttachmentBuilder): fix #8407

packages/discord.js/src/util/Colors.js
Adds a description field to the Colors docs so people can know what the colour is (sort of) without opening source code.
=> docs(Colors): provide enum descriptions

packages/discord.js/src/structures/Guild.js
Currently you get an API error (Method Not Allowed) when trying to use `Guild#fetchTemplates`. This PR fixes that.
=> fix(Guild): unable to fetch templates

packages/discord.js/src/structures/interfaces/InteractionResponses.js, packages/discord.js/typings/index.d.ts
It's possible to send a `deferUpdate` response to a ModalSubmitInteraction even if the Modal was not shown in response to a MessageComponentInteraction.
However, our typings didn't allow this, and the `InteractionResponses#deferUpdate()` method would throw if `this.message` was null.
I'm not sure if this changes the interface or not - it does for TypeScript, not for JavaScript
=> fix(ModalSubmitInteraction): allow deferUpdate

packages/discord.js/src/util/Transformers.js
Alternative to #8458, adds a check to not convert `Date` objects into non-Date.
=> fix(Transformers): do not transform `Date` objects

packages/discord.js/src/client/actions/MessageDeleteBulk.js, packages/discord.js/src/util/Constants.js, packages/discord.js/typings/index.d.ts
The `channel` parameter from `Client#messageDeleteBulk` was of type `TextBasedChannel`. This included DM channels, which is not possible [as documented](https://discord.com/developers/docs/resources/channel#bulk-delete-messages):
> This endpoint can only be used on guild channels
=> fix: Remove DM channels from `Client#messageDeleteBulk`'s types

packages/discord.js/typings/index.d.ts
- Add `ApplicationCommandRoleOptionData` interface
- Add `ApplicationCommandRoleOption` interface
- Add `ApplicationCommandUserOptionData` interface
- Add `ApplicationCommandUserOption` interface
- Add `ApplicationCommandMentionableOptionData` interface
- Add `ApplicationCommandMentionableOption` interface
- Update `ApplicationCommandSubCommandData.options` union
- Update `ApplicationCommandOptionData` union
- Update `ApplicationCommandOption` union
Fixes #8440 
- This PR changes the library's interface …
=> types: fix missing types for mentionable options

src/structures/ThreadChannel.js, typings/index.d.ts
Backports #8466 to version 13.
=> fix(ThreadChannel): Handle possibly `null` parent (v13)

packages/discord.js/src/structures/interfaces/TextBasedChannel.js, packages/discord.js/typings/index.d.ts
Resolves #8410 (Partially)
This implements the patch fix detailed in #8410. I updated both the typings and the docs.
=> types(Message): correct `bulkDelete` return type

packages/discord.js/src/structures/Embed.js
Resolves #8472 by retrieving the video data instead of the image data when accessing... video data.
=> fix(Embed): Reference video in video

packages/builders/package.json, packages/discord.js/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, packages/ws/src/ws/WebSocketManager.ts, packages/ws/src/ws/WebSocketShard.ts, yarn.lock
See https://github.com/discord/discord-api-docs/pull/5282
Closes #8461
Also bumps `discord-api-types` across the repo since.. I needed it.
=> feat(WebSocketShard): support new resume url

src/structures/StoreChannel.js, src/util/Constants.js, typings/index.d.ts
Carrying on from #8478, [see comment](https://github.com/discordjs/discord.js/pull/8478#issuecomment-1213832967)
Cc @Jiralite 
---
There is a broken link in the documentation which leads to a 404 page on Discord's dev support site. This PR fixes this issue by replacing the link to the new article.
Thanks for Poldi#2898 [(linked GitHub)](https://github.com/poldis) on Discord who discovered this issue: [link](https://discord.com/channels/222078108977594368/1007618316837339136/1007618316837339136).
- This PR …
=> docs: fix broken discord support link

packages/discord.js/src/structures/interfaces/InteractionResponses.js
I couldn't find this documented anywhere. Had to scroll through a couple dozen messages in Discord to find how people were using it. "Time" can mean anything.
^^ At least I think comments are documentation
=> Specify time unit in `awaitModalSubmit`

packages/discord.js/typings/index.d.ts
This PR changes the type of the `ApplicationCommandSubCommand.options` field  in order to match the documentation and be able to use all the properties of this type (like `minValue`, `maxValue`, etc).
=> types: change type of ApplicationCommandSubCommand.options

build.config.ts, packages/actions/package.json, packages/builders/package.json, packages/collection/package.json, packages/proxy/package.json, packages/rest/package.json, packages/scripts/package.json, packages/website/package.json, packages/ws/package.json, vitest.config.ts, yarn.lock
Bumped vitest to 0.22.0 and added `@vitest/coverage-c8`
ref: https://github.com/vitest-dev/vitest/releases/tag/v0.22.0
=> chore: bump vitest and add @vitest/coverage-c8

packages/collection/src/collection.ts, packages/website/src/components/CodeListing.tsx, packages/website/src/components/DocContainer.tsx, packages/website/src/components/MethodItem.tsx, packages/website/src/components/MethodList.tsx, packages/website/src/components/SidebarItems.tsx, packages/website/src/components/tsdoc/TSDoc.tsx, packages/ws/src/utils/utils.ts, packages/ws/src/ws/WebSocketManager.ts
Method names are bigger and summaries and documentation items are now separated under properties and methods. In addition, items in the sidebar are now truncated with ellipses.
I also added the language specifier to fenced code examples in /ws and /collection.
=> refactor(website): adjust typography

packages/website/src/DocModel/DocItem.ts, packages/website/src/DocModel/comment/RootComment.ts, packages/website/src/components/CodeListing.tsx, packages/website/src/components/MethodItem.tsx, packages/website/src/components/PropertyList.tsx, packages/website/src/components/tsdoc/BlockComment.tsx, packages/website/src/components/tsdoc/TSDoc.tsx
Renders deprecated and remarks blocks. Since I couldn't find any relevant items that were deprecated here's a sample of what the UI looks like:
=> feat(website): render `@deprecated` and `@remarks` blocks

.github/labeler.yml
The chore war will be no more.
=> ci: Remove management of chore label

packages/website/package.json, packages/website/src/components/DocContainer.tsx, packages/website/src/components/tsdoc/TSDoc.tsx, yarn.lock
I'm using the dark color scheme for codeblocks in light mode since the light color scheme looks much worse and has less highlighing.
=> refactor(website): use mantine code blocks

packages/discord.js/src/structures/ActionRow.js
This PR adds a depreciation warning for `ActionRow.from()`
=> feat: deprecate `ActionRow.from()`

packages/builders/src/messages/embed/Embed.ts, packages/website/src/DocModel/comment/ParamBlock.ts, packages/website/src/DocModel/comment/index.ts, packages/website/src/components/DocContainer.tsx, packages/website/src/components/ParameterTable.tsx, packages/website/src/components/tsdoc/BlockComment.tsx, packages/website/src/components/tsdoc/TSDoc.tsx, packages/website/src/util/parse.server.ts
Previously param descriptions would always be "None" despite having descriptions in the source code. 
Additionally. this PR tweaks the table resizing. The columns that show types now break in a more legible way, previously the types would be smashed into 1-2 character lines which would render them unreadable in small breakpoints. Tables also now scroll horizonally when the content within them cannot be shrank any farther.
=> feat(website): show parameter descriptions

packages/rest/src/lib/CDN.ts, packages/rest/src/lib/REST.ts, packages/rest/src/lib/RequestManager.ts, packages/website/src/components/tsdoc/BlockComment.tsx, packages/ws/src/ws/WebSocketManager.ts
Members with `@defaultValue` tags will show their default value in the docs.
=> feat(website): render `@defaultValue` blocks

packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/typings/index.d.ts
Webhooks cannot be created in thread channels, category channels or stage channels.
=> types: Disallow some channel types from webhook creation

packages/discord.js/typings/index.d.ts
Fix return type of `EventEmitter.on (static)` to `AsyncIterableIterator`, `AsyncIterator` is incorrect.
=> types: Correct `EventEmitter.on (static)` return type

packages/discord.js/src/structures/GuildAuditLogsEntry.js, packages/discord.js/typings/index.d.ts
When fetching an entry which is of an application command permission update, `<GuildAuditLogsEntry>.extra.guild` is always `undefined`. This is [not documented](https://discord.com/developers/docs/resources/audit-log#audit-log-entry-object-optional-audit-entry-info), so it will be removed. It was useless anyway as we are already in a guild context.
=> refactor(GuildAuditLogsEntry): Remove `guild` from application command permission update extra

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
This resolves #8275. To explain: the issue was that calling `<Guild>.fetchAuditLogs()` (or `<Guild>.fetchAuditLogs({ type: null })`) would incorrectly assume that the returned `action` is always `null`, `actionType` is always `ALL`, `extra` is always `null` etc. instead of leaving these as all possible values.
A code sample of how this bug was in effect:
```TypeScript
import { AuditLogEvent, Guild } from "discord.js";
declare const guild: Guild;
const auditLog = await guild.fetchAuditLogs().then(({ entries }) => entries.first()!);
// We didn't specify a specific type to fetch. Therefore, it could be anything.
if (auditLog.action === AuditLogEvent.BotAdd) {
// never
}
```
- …
=> types(GuildAuditLogs): Allow fetching to return all possible values

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
The following code will not yield an error despite the type of the option being known:
```TypeScript
import { ApplicationCommandOptionType, ApplicationCommandType, Guild } from "discord.js"
declare const guild: Guild;
guild.commands.create({
name: "test",
description: "test",
type: ApplicationCommandType.ChatInput,
options: [
{
type: ApplicationCommandOptionType.String,
name: "test",
description: "test",
choices: [
{
name: "test",
value: 0 // No error!
},
],
required: true
}
]
});
```
This pull request strengthens the types around here and resolves #8528.
- I know how to update typings and …
=> types: Allow choice's value type to be strictly inferred

packages/discord.js/src/structures/Guild.js, packages/discord.js/typings/index.d.ts
1. Upon receiving a guild from Discord, I noticed `Guild#widgetEnabled` and `Guild#widgetChannelId` did not exist. This was documented as [potentially missing](https://discord.com/developers/docs/resources/guild#guild-object-guild-structure), so a `null` fallback has been added.
2. A widget channel can actually be more than a text channel. It can be an announcement channel, a voice channel and a stage channel too. Any other channel type returns an API error from Discord.
=> fix(Guild): Widget channel types and fixes

packages/discord.js/src/managers/GuildMemberManager.js
`@discordjs/rest` now returns an instance of `Uint8Array`
=> fix(GuildMemberManager): `add()` method throws an error

src/managers/GuildBanManager.js, src/managers/GuildMemberManager.js, src/structures/GuildMember.js, typings/index.d.ts
Backports #8326 to version 13.
=> feat(GuildBanManager): Add `deleteMessageSeconds`

src/util/Intents.js, typings/index.d.ts
https://discord.com/channels/222078108977594368/992166350640386090/1014655744597033040
=> add MESSAGE_CONTENT intent (v13) 

packages/discord.js/typings/index.d.ts
`Webhook#avatar` can be null if the webhook hasn't any avatar. The documentation is correct, and `Webhook#avatarURL()` handles it correctly, but types were missing the `null` type.
=> types(webhook): avatar can be null

packages/discord.js/src/structures/Integration.js, packages/discord.js/typings/index.d.ts
- discord/discord-api-docs#5311
=> feat(Integration): add `scopes`

packages/builders/src/interactions/contextMenuCommands/ContextMenuCommandBuilder.ts, packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts
Replaces "Note"s in summaries with `@remarks`
I copied the `toJSON()` note from the Component class because it seemed more complete
https://github.com/discordjs/discord.js/blob/4ffdada4f7a9f8d5bc242353e03c73d5604163a5/packages/builders/src/components/Component.ts#L25-L32
=> docs: use remarks instead of `Note` in descriptions

packages/discord.js/src/client/WebhookClient.js, packages/discord.js/src/managers/MessageManager.js, packages/discord.js/src/managers/UserManager.js, packages/discord.js/src/structures/Message.js, packages/discord.js/src/structures/MessagePayload.js, packages/discord.js/src/structures/Webhook.js, packages/discord.js/src/structures/interfaces/InteractionResponses.js, packages/discord.js/src/structures/interfaces/TextBasedChannel.js, packages/discord.js/src/util/Options.js, packages/discord.js/typings/index.d.ts
Some general refactoring around sending and editing messages. For example, `attachments` showed up when sending a message when it should not - it should appear when editing.
=> refactor: Split message send/edit types/documentation

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Emitted events should have a ready client. The types should now reflect this.
=> types: Ensure events possess `Client<true>`

src/managers/GuildChannelManager.js, typings/index.d.ts, typings/index.test-d.ts
=> types(GuildChannelManager): correct fetch return type (v13)

packages/discord.js/src/client/actions/GuildMemberUpdate.js
This event is emitted on any guild if an uncached member is updated and the client wasn't instantiated with the `GuildMember` partial
https://github.com/discordjs/discord.js/blob/d14d47b62fea9a57570f24195ca486886751c6fa/packages/discord.js/src/client/actions/GuildMemberUpdate.js#L21-L39
=> docs: update misleading `Client#guildMemberAvailable` event description

packages/discord.js/src/structures/GuildTemplate.js, packages/discord.js/src/structures/Invite.js
These RegExes are not global, but the docs say they are.
=> docs: fix regexps incorrectly being called global

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Pass the `Cached` generic parameter to the `reply`, `editReply`, `fetchReply`, `deferUpdate`, and `followUp` methods when `Message`s are returned
=> types(interactions): pass `Cached` type to return type of methods

packages/builders/__tests__/interactions/SlashCommands/SlashCommands.test.ts, packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts
=> fix(SlashCommandBuilder): missing methods in subcommand builder

packages/api-extractor-utils/src/ApiNodeJSONEncoder.ts, packages/website/src/components/DocContainer.tsx, packages/website/src/components/MethodItem.tsx, packages/website/src/components/MethodList.tsx, packages/website/src/components/SidebarLayout.tsx, packages/website/src/components/TableOfContentItems.tsx, packages/website/src/components/model/Function.tsx, packages/website/src/pages/docs/[...slug].tsx
I'll reduce code duplication in a followup.
=> feat(website): use dropdowns for overloads

packages/builders/__tests__/interactions/SlashCommands/SlashCommands.test.ts, packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionChannelTypesMixin.ts, packages/discord.js/src/managers/ThreadManager.js, packages/discord.js/src/structures/BaseGuildTextChannel.js, packages/discord.js/src/structures/Guild.js, packages/discord.js/src/structures/Message.js, packages/discord.js/src/structures/NewsChannel.js, packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/src/util/Channels.js, packages/discord.js/src/util/Constants.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Replaces the usage of the deprecated news/thread `ChannelType`s 
https://github.com/discordjs/discord-api-types/commit/817884184bf295e8d550898e1e28dc674b50600f (Released in 0.37.6)
https://github.com/discordjs/discord.js/blob/d14d47b62fea9a57570f24195ca486886751c6fa/packages/discord.js/package.json#L57
=> refactor: replace usage of deprecated `ChannelType`s

packages/builders/src/components/ActionRow.ts, packages/builders/src/components/button/Button.ts, packages/builders/src/components/selectMenu/SelectMenu.ts, packages/builders/src/components/selectMenu/SelectMenuOption.ts, packages/builders/src/components/textInput/TextInput.ts
Documents the constructors of the components, and fixed the current documentation of the ButtonBuilder
=> docs(builders/components): document constructors

packages/discord.js/src/client/actions/MessageCreate.js, packages/discord.js/src/client/actions/MessageDelete.js, packages/discord.js/src/client/actions/MessageDeleteBulk.js
> The `message_count` and `total_message_sent` fields on threads created in a forum will increment on `MESSAGE_CREATE` and will decrement on `MESSAGE_DELETE`/`MESSAGE_DELETE_BULK`. There will be no `CHANNEL_UPDATE` event through gateway notifying those fields' changes (similar to `last_message_id` changes). Clients should update those values when receiving corresponding events.
https://discord.com/developers/docs/topics/threads#forums
=> fix: update `messageCount`/`totalMessageSent` on message events

packages/discord.js/src/structures/ThreadChannel.js
This caused an internal error when used in a forum post. This now fetches the original message in the forum post!
=> fix(ThreadChannel): Make `fetchStarterMessage()` work in forum posts

packages/discord.js/src/managers/GuildForumThreadManager.js, packages/discord.js/src/managers/GuildTextThreadManager.js, packages/discord.js/src/managers/ThreadManager.js, packages/discord.js/typings/index.d.ts
The channel of such thread managers can be narrowed down!
=> types: Narrow channel type in thread managers

packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/typings/index.d.ts
This required a full object, but only the ids are necessary.
In addition:
- The return type is corrected on the helper method
- `ThreadEditData` now possesses this property
- The return type of the method in the typings no longer possibly returns a private thread
=> fix: Correct applied tags type

packages/discord.js/src/structures/Guild.js, packages/discord.js/src/structures/WelcomeChannel.js, packages/discord.js/typings/index.d.ts
Forum channels can be set via bots as a welcome channel as well as in the client. This pull request reflects this functionality.
=> feat(WelcomeChannel): Add forum channel as a type

packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/typings/index.d.ts
=> fix(GuildChannelManager):  typo in `flags` property name when editing

packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/typings/index.d.ts
Allowing threads to edit flags which was overlooked in #8637.
=> fix(ThreadChannel): Allow editing flags

packages/discord.js/typings/index.d.ts
This will allow these managers to be specified for caching restrictions.
=> types(Caches): Allow `GuildForumThreadManager` and `GuildTextThreadManager`

packages/discord.js/src/structures/ForumChannel.js, packages/discord.js/typings/index.d.ts
Resolves #8654 by implementing the missing properties and methods.
=> fix(ForumChannel): Implement missing properties and methods

packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/typings/index.d.ts
Allows creating webhooks on ForumChannels from the GuildChannelManager
=> fix(GuildChannelManager): allow creating webhooks on forums

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Guild channel managers were not correctly returning the type if chosen to be a forum channel due to a leftover to-do.
=> types(GuildChannelManager): Handle forum channel overload

packages/discord.js/src/managers/GuildBanManager.js
Adds a runtime deprecation warning for `deleteMessageDays`.
=> refactor(GuildBanManager): Add deprecation warning for `deleteMessageDays`

packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
`ThreadChannel#parent` now documents and types forum channels.
=> fix(ThreadChannel): Add forum channel to parent

packages/collection/src/collection.ts
This PR changes the type signature for all function parameters in the Collection class by making their return types unknown. This brings the types in line with the TypeScript lib types for the corresponding array methods. Since we're simply checking for truthiness in an if statement, the return type can be converted to a boolean automatically and doesn't need to be provided as one necessarily
=> types(Collection): make fn return type unknown

packages/discord.js/src/managers/GuildForumThreadManager.js
This PR fixes duplicate typedefs for `GuildForumThreadCreateOptions`
=> docs: fix duplicate typedefs

packages/rest/src/lib/utils/constants.ts
Fixes #8629 
Fixes #8489 
Repeated issue:
- https://discord.com/channels/222078108977594368/999007780524535978
- https://discord.com/channels/222078108977594368/1023364907619602522
I have no way of testing this but 30 seconds seems to work for others.
The issue seems to be with misconfigured ipv6, see https://github.com/nodejs/undici/issues/1531#issuecomment-1229889136
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed) (Not really sure. Increases the time allowed to establish a connection.)
=> feat(rest): use Agent with higher connect timeout

packages/proxy/src/handlers/proxyRequests.ts
Prior to this we weren't forwarding query parameters at all.
=> fix(proxyRequests): forward query parameters

packages/discord.js/src/managers/CategoryChannelChildManager.js, packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/src/structures/ForumChannel.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/typings/index.d.ts
- discordjs/discord-api-types#589
- discord/discord-api-docs#5488
- #8685
=> feat(ForumChannel): add `defaultSortOrder`

packages/rest/src/lib/errors/HTTPError.ts, packages/rest/src/lib/handlers/SequentialHandler.ts
This PR fixes #8615 by overwriting the error of `HTTPError` with the name of the class (as I think is how sub-classed errors should generally work) and synthesizing an error message based on the http status (as undici apparently does not expose the status text?).
=> fix(SequentialHandler): throw http error with proper name and more useful message

packages/discord.js/src/index.js
`@discordjs/util` is currently only being re-exported from the typings and the `@discordjs/builders` package. This does not allow for using named exports from /util in djs with ESM, so the answer to
https://github.com/discordjs/discord.js/pull/8591#discussion_r980146605 is yes
=> fix: re-export util

packages/discord.js/src/managers/CategoryChannelChildManager.js, packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/typings/index.d.ts
This PR allows one to create channels with a default archive duration set.
=> feat(GuildChannelManager): allow creating channels with a default auto archive duration

packages/discord.js/src/client/Client.js
Fixes an oversight from moving to /rest. Any request that sends its own token should be set to auth false to avoid erroneously unsetting the client token.
=> fix(Client): don't auth for webhook fetches with token

package.json, packages/builders/package.json, packages/builders/src/index.ts, packages/builders/tsup.config.js, packages/collection/package.json, packages/collection/src/index.ts, packages/collection/tsup.config.js, packages/rest/package.json, packages/rest/src/index.ts, packages/rest/src/lib/utils/constants.ts, packages/rest/tsup.config.js, packages/voice/package.json, packages/voice/src/index.ts, packages/voice/src/util/generateDependencyReport.ts, packages/voice/tsup.config.js, packages/ws/package.json, packages/ws/src/index.ts, packages/ws/src/utils/constants.ts, packages/ws/tsup.config.js, tsup.config.js, yarn.lock
Voice, Rest and WS were relying on package.json imports which were path specific and as shown in #8720 that is prone to errors. Not to mention that it also has downsides of either at runtime requiring a package.json file (voice) or having it inlined in the JS file (ws) by tsup, these are not ideal solutions.
The alternative: use an esbuild plugin to inject the version at build time so it's a constant string for end-users.
While adding it to the 3 packages mentioned above I figured might as well also add `version` exports to /collection and /builders, in case anyone is interested in having that information in their bots.
- Code changes have been tested against the Discord …
=> build: switch to `esbuild-plugin-version-injector` for injecting version strings

packages/discord.js/src/util/Components.js
Fixes a bug where `createComponentBuilder` was constructing a `TextInputComponent` instead of a `TextInputBuilder`.
=> fix: correctly construct a builder

apps/guide/src/util/constants.ts, apps/website/src/pages/docs/[...slug].tsx, packages/actions/src/uploadCoverage/action.yml
The guide and the website now live in /apps instead of /packages
=> fix: app paths

packages/builders/src/index.ts, packages/collection/src/index.ts, packages/rest/src/index.ts, packages/voice/src/index.ts, packages/ws/src/index.ts
- Removed the "Note to developers" from the documentation
- Fixed the `ws` package link
=> chore: make 'Note to developers' on version constant a regular comment

src/util/Util.js, test/escapeMarkdown.test.js, typings/index.d.ts
Backports #7587, #7638, and #8701 to v13
- This PR includes *potentially* breaking changes (methods removed or renamed, parameters moved or removed) (see #8701)
=> feat(Util): backport `escapeMarkdown` PRs to v13

packages/discord.js/typings/index.d.ts
This PR fixes the module augmentation for `node:events`
Fixes #8634 
=> types: fix events augmentation

packages/ws/src/ws/WebSocketShard.ts
Closes #8726
This is quite the "easy fix", by just removing the guard on dispatch events, since it was quite frankly unnecessary for a lib as low level as ws is.
Possibly related to #8558 (i.e. might improve the behavior there; otherwise that issue will need additional research)
=> fix(WebSocketShard): dispatch race condition

packages/builders/src/index.ts, packages/collection/src/index.ts, packages/rest/src/index.ts, packages/voice/src/index.ts, packages/ws/src/index.ts
=> chore: use `@link` instead of markdown link in tsdocs

apps/website/src/util/summary.ts
Previously link tag text would be omitted in descriptions.
=> fix: extract text from link tags for descriptions

packages/discord.js/src/structures/Embed.js
Uses the [`embedLength()`](https://discordjs.dev/docs/packages/builders/main/embedLength:Function) function from /builders in `Embed#length` to reduce code duplication
=> refactor(Embed): use `embedLength` function from builders

packages/rest/src/lib/handlers/SequentialHandler.ts
related to #8757
The ``ref`` option doesn't require the Node.js event loop to remain active when waiting for the timeout causing the program to end if there isn't an active gateway connection.
=> fix: make ratelimit timeout require event loop to be active

packages/discord.js/src/errors/ErrorCodes.js, packages/discord.js/src/structures/interfaces/InteractionResponses.js, packages/discord.js/typings/index.d.ts
* https://github.com/discord/discord-api-docs/pull/5570
Breaking because it no longer throws an error, but a bugfix because it shouldn't throw an error here anymore.
=> feat: allow deletion of ephemeral messages

packages/builders/src/interactions/contextMenuCommands/Assertions.ts
Current regex validation in the context menu builder only allows - and _  
Fixes #8781
=> feat: allow punctuation characters in context menus

src/util/Util.js
Backports #8798 to v13
Regressed by #8703
=> fix(escapeMarkdown): fix double escaping (v13)

packages/discord.js/src/client/websocket/WebSocketShard.js, packages/discord.js/typings/index.d.ts
Resume urls was not added in v14 despite on changelogs saying it is, was only added on `@discordjs/ws`
=> feat: support resume urls

packages/discord.js/src/structures/SelectMenuBuilder.js, packages/discord.js/src/structures/SelectMenuComponent.js, packages/discord.js/src/structures/SelectMenuInteraction.js, packages/discord.js/src/structures/SelectMenuOptionBuilder.js
This PR adds the `@extends` to the old select menu classes. Without these, the docs didn't show any methods or properties.
=> docs: add `@extends` for select menu classes

packages/discord.js/src/structures/interfaces/TextBasedChannel.js
This pull request resolves #8833 - `ActionRowOptions[]` was not the correct type here, whatever it was. It should (obviously) accept `ActionRowBuilder[]`.
=> docs: Specify `ActionRowBuilder` for `components`

turbo.json
Cache `coverage` directories on the `test` pipeline
There's a chance this will fix the wack coverage reports by codecov on pull requests
=> chore: turbo cache coverage

src/structures/Presence.js
This PR fixes `Activity.equals()` not checking for differing emojis, leading `presenceUpdate` to not fire if only a custom status emoji was updated.
=> fix(Activity): Fix equals() not checking for differing emoji (v13)

src/structures/interfaces/InteractionResponses.js, typings/index.d.ts
=> feat(InteractionResponses): add message parameter (v13)

src/errors/Messages.js, src/structures/interfaces/InteractionResponses.js
Backport allow deletion of ephemeral messages to v13 from [this commit](https://github.com/discordjs/discord.js/commit/fc107744618857bf28c2167f204253baf690ede8)
It's my first pull request to discord.js so I don't know if I did it right
> None
=> fix: backport allow deletion of ephemeral messages to v13

apps/guide/src/components/PageButton.tsx, apps/guide/src/components/SidebarLayout.astro
Adds buttons at the bottom of the page to go to the next and/or previous page.
=> feat(guide): add next and previous page buttons

packages/discord.js/src/structures/Webhook.js, packages/discord.js/typings/index.d.ts
This PR adds a `channel` getter for webhooks
=> feat(Webhook): add `channel` property

packages/rest/__tests__/utils.test.ts, packages/rest/src/lib/utils/utils.ts
I didn't realize how painful it was to use the utility until I saw #8736 using them extensively. This patch ensures that:
1. We can pass non-Records:
```diff
declare options: RESTGetAPIApplicationCommandsQuery;
- makeURLSearchParams(options as Record<string, unknown>);
+ makeURLSearchParams(options);
```
1. We can cast types:
```diff
// Expects `RESTGetAPIApplicationCommandsQuery`:
- makeURLSearchParams({ withLocalizations: true }); // Should be `with_localizations``, doesn't raise type error.
+ makeURLSearchParams<RESTGetAPIApplicationCommandsQuery>({ withLocalizations: true }); // Raises type error due to mismatching types.
```
- Code changes have been tested against the …
=> refactor: update `makeURLSearchParams` to accept readonly non-`Record`s

apps/website/src/app/docs/packages/page.tsx
Adds an extra package link to the discord-api-types documentation.
=> feat(website): add link to discord-api-types

packages/core/src/api/applicationCommands.ts, packages/core/src/api/channel.ts, packages/core/src/api/guild.ts, packages/core/src/api/invite.ts, packages/core/src/api/user.ts, packages/core/src/api/webhook.ts
These casts are no longer needed since
- #8868
=> fix: remove casts when using `makeURLSearchParams()`

.github/labeler.yml, packages/scripts/src/createPackage.ts
The labeler file should formatted as `label-name: [file-globs]`
=> fix(createPackage): invalid label/path on labeler file

.github/labeler.yml, .github/labels.yml, packages/scripts/src/createPackage.ts
Automatically sorts the `labels.yml` and `labeler.yml` files when creating a package
=> feat(createPackage): sort label files

packages/ws/src/utils/constants.ts, packages/ws/src/ws/WebSocketShard.ts
Closes #8558
Refer to https://github.com/discordjs/discord.js/issues/8558#issuecomment-1332187881 for an explanation of the actual underlying problem.
Also related: #8399, #8405, #8479, #8731
All in all, this PR:
1) fixes a bad condition with the ratelimit `resetAt` check
2) accounts for some edge cases related to a connection being destroyed while a payload is being sent out
3) adds some more debug logs that were much needed for fixing this issue
4) adds a new `close` event that's needed for some of the new internal behavior - **making this as semver minor PR**
- I know how to update …
=> fix(WebSocketShard): send ratelimit handling

packages/ws/__tests__/strategy/WorkerShardingStrategy.test.ts, packages/ws/src/strategies/context/IContextFetchingStrategy.ts, packages/ws/src/strategies/context/SimpleContextFetchingStrategy.ts, packages/ws/src/strategies/context/WorkerContextFetchingStrategy.ts, packages/ws/src/strategies/sharding/SimpleShardingStrategy.ts, packages/ws/src/strategies/sharding/WorkerShardingStrategy.ts, packages/ws/src/strategies/sharding/worker.ts, packages/ws/src/utils/IdentifyThrottler.ts, packages/ws/src/ws/WebSocketShard.ts
This PR makes `IContextFetchingStrategy` responsible for throttling identifies.
Prior to those changes, control over not spamming identify was handed to `WebSocketShard#connect`'s caller, which does NOT work correctly in the case of multiple shards reconnecting at the same time (e.g. there would be no regard to `max_concurrency`).
With this change, `/sharder` (see #8859) can now also get everything working even with cross-process sharding and such.
- This PR changes the library's interface (methods or …
=> refactor(WebSocketShard): identify throttling

package.json, yarn.lock
This new version will fix our auto deprecation workflow (https://github.com/discordjs/discord.js/actions/workflows/npm-auto-deprecate.yml).
=> fix: Deprecate workflow fix

packages/discord.js/src/index.js, packages/discord.js/typings/index.d.ts
#8699 for `@discordjs/formatters`
=> fix: re-export formatters

packages/discord.js/src/client/websocket/WebSocketShard.js
This PR should solve resolve #8486 and maybe even resolve #8592
When a WebSocketShard doesn't receive a heartbeat in time it tries to close the Websocket. If the close event of the socket doesn't emit in time either it assumes a zombie connection and emits its own close event, but the old connection still has the onClose and other event listeners attached. So if the old Websocket finally emits the close event the WebSocketShard receives that event and assumes it's from the new (re-)connection and closes again.
=> fix(WebSocketShard): clear listeners on reconnect

packages/discord.js/src/structures/CommandInteractionOptionResolver.js, packages/discord.js/typings/index.d.ts
It is fine to use `getRole()`, `getUser()` and `getMember()` with a mentionable option type.
=> refactor(CommandInteractionOptionResolver): Loosen mentionable checks

packages/discord.js/src/client/WebhookClient.js, packages/discord.js/src/managers/ApplicationCommandPermissionsManager.js, packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/src/managers/GuildEmojiManager.js, packages/discord.js/src/managers/GuildInviteManager.js, packages/discord.js/src/managers/GuildMemberManager.js, packages/discord.js/src/managers/GuildStickerManager.js, packages/discord.js/src/managers/RoleManager.js, packages/discord.js/src/structures/BaseGuildTextChannel.js, packages/discord.js/src/structures/BaseGuildVoiceChannel.js, packages/discord.js/src/structures/ClientUser.js, packages/discord.js/src/structures/ForumChannel.js, packages/discord.js/src/structures/Guild.js, packages/discord.js/src/structures/GuildChannel.js, packages/discord.js/src/structures/GuildEmoji.js, packages/discord.js/src/structures/GuildMember.js, packages/discord.js/src/structures/GuildScheduledEvent.js, packages/discord.js/src/structures/GuildTemplate.js, packages/discord.js/src/structures/InteractionWebhook.js, packages/discord.js/src/structures/MessagePayload.js, packages/discord.js/src/structures/Role.js, packages/discord.js/src/structures/Sticker.js, packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/src/structures/VoiceState.js, packages/discord.js/src/structures/Webhook.js, packages/discord.js/src/structures/interfaces/InteractionResponses.js, packages/discord.js/typings/index.d.ts
This PR refactors the `XOptions`/`XData` interfaces to all follow the same format
Create options format: `StructureCreateOptions`
Edit options format: `StructureEditOptions`
=> refactor: use consistent naming for options

packages/discord.js/src/structures/InteractionResponse.js, packages/discord.js/typings/index.d.ts
InteractionResponses have IDs, we can just destructure it and get createdAt and createdTimestamp, (it's a getter because other such properties on other classes were getters)
Close #8916 
=> feat(InteractionResponse): createdTimestamp

packages/discord.js/src/sharding/Shard.js, packages/discord.js/src/sharding/ShardClientUtil.js
Internally we use switch else-where instead of `else if` statements, this also opens the gate up to more shard spawning implementations in the future without an `else if` mess.
- This PR **only** includes internal code changes.
=> refactor(sharding): use switch statement

packages/brokers/src/brokers/Broker.ts, packages/brokers/src/brokers/redis/RPCRedis.ts, packages/formatters/src/formatters.ts, packages/rest/src/lib/utils/constants.ts, packages/ws/src/utils/constants.ts
We need a couple eslint-ignores because of https://github.com/typescript-eslint/typescript-eslint/issues/6077
=> chore: use `satisfies` where applicable

packages/discord.js/package.json, packages/discord.js/src/managers/CategoryChannelChildManager.js, packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/src/structures/ForumChannel.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/typings/index.d.ts, yarn.lock
Upstream:
- discord/discord-api-docs#5693
- discord/discord-api-docs#5745
Depends on:
- discordjs/discord-api-types#658
=> feat(ForumChannel): add `defaultForumLayout`

packages/discord.js/package.json, yarn.lock
https://github.com/discordjs/discord.js/blob/c76e17078602914c3e1d227a3acc98eaa99c18d4/packages/discord.js/src/index.js#L209
=> fix: add `@discordjs/formatters` to dependency list

packages/discord.js/src/managers/GuildForumThreadManager.js
`StickerResolvable` is the correct type to document here.
=> docs(GuildForumThreadManager): Fix `sticker` type

packages/discord.js/src/client/websocket/WebSocketShard.js
Fixes the bug introduced with #8927 where the timeout in `WebSocketShard#setWsCloseTimeout()` tries to cleanup a connection even if none exists anymore.
=> fix(WebSocketShard): only cleanup the connection if a connection still exists

packages/discord.js/src/structures/BaseSelectMenuComponent.js, packages/discord.js/src/structures/ButtonComponent.js, packages/discord.js/typings/index.d.ts
This PR changes `BaseSelectMenuComponent#disabled` and `ButtonComponent#disabled` to only return booleans.
Fixes #8964 
=> fix: return only boolean for `disabled`

packages/discord.js/src/client/websocket/WebSocketShard.js
#7626 introduced a `WebSocketShard#wsCloseTimeout()` to listen for zombie connections and reconnect when zombie connections get detected.
This fix was going a bit too far, as the timeout was also starting if `WebSocketShard#destroy()` was emitting the `WebSocketShard#destroyed` event. In those cases we don't need to listen for zombie connections anymore, as the `WebSocketManager`will reconnect the shard anyway.
But this lead to the Websocket connection being unneccessarily destroyed after the reconnect, because the timeout happened after the new connection already got made.
This PR now only starts the `wsCloseTimeout` if the `WebSocketShard#destroy()` method doesn't emit the `WebSocketShard#destroyed` event. …
=> fix(WebSocketShard): either start close timeout or emit destroyed but never both

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
`options` is a required field in subcommand group options.
=> types: subcommand group `options` is required

packages/discord.js/src/structures/AutoModerationRule.js, packages/discord.js/typings/index.d.ts
This PR fixes the type for `actions` in `AutoModerationRuleCreateOptions` and `setActions()`. They should take an array.
Fixes #8963 
=> types: fix actions type in automod

packages/discord.js/typings/index.d.ts
This PR updates the type for `SelectMenuOptionBuilder`. `SelectMenuOptionBuilder` is deprecated, and replaced with `StringSelectMenuOptionBuilder`
Fixes #8948 
=> types: use StringSelectMenuOptionBuilder

packages/discord.js/src/structures/AutoModerationRule.js
Why? Because setting each property was resetting whole triggerMetadata.
=> fix: keep other properties in triggerMetadata

packages/discord.js/src/managers/GuildManager.js, packages/discord.js/typings/index.d.ts
I am sure that this approach is better than setting snake case names and deleting the camel case properties. It's also the approach of other areas of the library and helps tackle #5267.
I noticed `icon` is nullable here, but [Discord's documentation](https://discord.com/developers/docs/resources/guild#create-guild-json-params) doesn't seem to accept a `null` value.
I also reordered the parameters as they are in Discord's documentation.
=> refactor(GuildManager): Better handling of creation code

packages/discord.js/src/managers/BaseGuildEmojiManager.js, packages/discord.js/src/managers/ReactionManager.js, packages/discord.js/typings/index.d.ts
Resolves #8968 by somewhat swapping the types for `EmojiIdentifierResolvable` and `MessageReactionResolvable`.
=> types: Swap message reaction and emoji identifier types

packages/discord.js/src/structures/Guild.js, packages/discord.js/typings/index.d.ts
This style of code isn't consistent with other parts of the library. I think destructuring the object here looks pretty neat and seems to result in code that's easier to look at. Personally, every time I've come across this, I think about doing this but end up not bothering. But now's the time, apparently!
I also reordered the parameters as they are in Discord's documentation.
There was also a pretty suspicious max-len rule modification here which I removed. It must have served an ideal purpose in the past, but presently, it doesn't seem to do much at all.
- I know how to update typings …
=> refactor(Guild): Destructure object in guild editing

packages/discord.js/src/client/websocket/WebSocketShard.js
Fixes #8486, fixes #8984 and supersedes #8981 
- Fix backport #7626 missing changes
- Reverted the pull request #8956
- Removed unref of wsCloseTimeout
- ~~We are resuming the connection for zombie instead of starting a new~~ To not mess it up we didn't push this. Will create a separate pr for this.
=> fix(WebSocketShard): Zombie connection fix

package-lock.json, src/client/websocket/WebSocketShard.js, test/shard.js
=> fix(websocketshard): backport zombie connection fix

packages/discord.js/src/structures/BaseInteraction.js
There was a typo in the link specified in https://github.com/discordjs/discord.js/blob/d3e9f2a355a1f5272d62a507eb6ecd8808904fff/packages/discord.js/src/structures/BaseInteraction.js#L325 and I've fixed it.
=> docs: Fix a typo in the MentionableSelectMenuInteraction link

packages/discord.js/src/structures/ApplicationCommand.js, packages/discord.js/typings/index.d.ts
It wasn't possible to use a `SlashCommandChannelOption` in conjunction with discord.js's `ApplicationCommandChannelOption` as the types were different.
=> types: Allow builders to set channel types in discord.js

packages/discord.js/src/structures/Integration.js, packages/discord.js/src/structures/Role.js, packages/discord.js/typings/index.d.ts
Upstream:
- discord/discord-api-docs#5724
=> feat: add role subscriptions

packages/discord.js/src/structures/Guild.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/5821
=> feat(GuildAuditLogs): Support `after`

packages/proxy-container/package.json, yarn.lock
This has been possible since 9922151266a8ac618f41b7583c984a8755eccf14
I have tested locally using `docker build -t discordjs/proxy:latest -f packages/proxy-container/Dockerfile .` and the image still builds.
=> chore: remove proxy dep hack

src/managers/GuildEmojiManager.js, src/managers/GuildMemberManager.js, src/managers/ThreadMemberManager.js, src/structures/BaseGuildVoiceChannel.js, src/structures/Guild.js, src/structures/GuildChannel.js, src/structures/GuildEmoji.js, src/structures/GuildMember.js, src/structures/Invite.js, src/structures/Message.js, src/structures/ThreadChannel.js, src/structures/VoiceChannel.js, src/structures/VoiceState.js, typings/index.d.ts
- #7526
- #7669
- #8258
In addition, a deprecation warning now emits for `Guild#me`.
=> refactor: Move `me` and add `fetchMe()`

typings/index.d.ts
Backports #8978 to version 13.
=> types(widget): Add missing `name`

src/structures/ThreadChannel.js, typings/index.d.ts
This was simply missing. Functionality for this already exists.
=> types(ThreadEditOptions): Add `appliedTags`

packages/discord.js/src/structures/ThreadChannel.js
This was accidentally moved in #8026 and took a few adventures into other properties since. It's home now.
=> docs(ThreadEditOptions): Move info tag back to `invitable`

src/structures/ThreadChannel.js
`reason` is improperly being passed here. It is the second parameter, not the first:
https://github.com/discordjs/discord.js/blob/546ac439115f4017f01e0c02dee2ff80b789c28b/src/structures/ThreadChannel.js#L330-L341
=> fix(ThreadChannel): `reason` as second parameter

packages/core/src/api/guild.ts
Fixes GuildsAPI#getMembers to properly return an array of guild members.
=> types: fix `GuildsAPI#getMembers` return type

packages/discord.js/src/structures/AutoModerationActionExecution.js, packages/discord.js/src/structures/ModalSubmitFields.js
[`@type`](https://jsdoc.app/tags-type.html#syntax) has no description, causing some text to not show up in the documentation.
=> docs: no `@type` description and reveal info block

.github/workflows/issue-triage.yml
This has become a nuisance. Not sure how the implementation is wrong, but it should be fine anyway to check only when opened.
=> ci: don't run issue triage on edit

packages/builders/package.json, packages/core/package.json, packages/discord.js/package.json, packages/discord.js/typings/index.d.ts, packages/formatters/package.json, packages/next/package.json, packages/proxy/package.json, packages/rest/package.json, packages/scripts/package.json, packages/voice/package.json, packages/ws/package.json, yarn.lock
Bumps discord-api-types to 0.37.35 and undici to 5.19.1 (see #9138).
=> chore: bump discord-api-types and undici

.github/issue-labeler.yml
on formatters and next the n of \n was missing
=> chore: fix \n breaks

packages/discord.js/src/util/BitField.js
The iterator should only calculate (and yield) values that the user consumes, while the current implementation calculates all of the values by calling `toArray()`, and then yields them
This PR makes the iterator do the calculations, which `toArray()` consumes. The end-user behaviour is still the same
=> refactor(BitField): reverse iterator/toArray responsibilities

packages/discord.js/src/structures/ThreadChannel.js
Threads created in forum channels return the message object within the payload[^1]. discord.js ignored detecting if `message` was in `data` here leaving it to the later `MESSAGE_CREATE` event to populate, but we can do this straight away.
One may ask if it could be possible for both the handler and the WebSocket to inject a duplicate message into the cache here. I have found that the gateway does not emit the message—only via REST it does.
[^1]: https://discord.com/developers/docs/resources/channel#start-thread- …
=> fix(ThreadChannel): insert starter message from threads created in forum channels

.github/ISSUE_TEMPLATE/bug_report.yml, packages/discord.js/src/client/actions/ActionsManager.js, packages/discord.js/src/client/actions/GuildAuditLogEntryCreate.js, packages/discord.js/src/client/websocket/handlers/GUILD_AUDIT_LOG_ENTRY_CREATE.js, packages/discord.js/src/client/websocket/handlers/index.js, packages/discord.js/src/managers/GuildBanManager.js, packages/discord.js/src/structures/GuildAuditLogs.js, packages/discord.js/src/structures/GuildAuditLogsEntry.js, packages/discord.js/src/util/Events.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Implements basic support for the `GUILD_AUDIT_LOG_ENTRY_CREATE` event
Changes:
- Add `Client#guildAuditLogEntryCreate` event
- `GuildAuditLogsEntry#targetId` and `GuildAuditLogsEntry#executorId` to address https://github.com/discordjs/discord.js/pull/9058#issuecomment-1382655421
- Moved `logs` to the last constructor parameter of `GuildAuditLogsEntry` (which is private) so as to not make it nullable (we don't received it via the gateway)
Upstream:
- discord/discord-api-docs#5849
=> feat(Client): `guildAuditLogEntryCreate` event

packages/discord.js/src/structures/AutoModerationActionExecution.js, packages/discord.js/src/structures/AutoModerationRule.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/src/util/Transformers.js, packages/discord.js/src/util/Util.js
The typings did not match the code here as we were not properly parsing the returned data. This resolves #9110.
=> fix(AutoModerationActionExecution): transform `action`

packages/core/src/api/oauth2.ts
https://discord.com/channels/222078108977594368/1070696353434452038/1070696353434452038
Pass the `body` (`URLSearchParams`) as it is instead of `JSON.stringify()`ing it and overriding the content-type header
=> fix(oauth2): pass through body

packages/discord.js/typings/index.d.ts
this PR fixes the type of Attachment#name which previously allowed null.
References
https://discord-api-types.dev/api/discord-api-types-v10/interface/APIAttachment
https://discord.js.org/#/docs/discord.js/main/class/Attachment?scrollTo=name
=> types: fix type of Attachment#name

packages/discord.js/src/index.js, packages/discord.js/src/managers/GuildMemberManager.js, packages/discord.js/src/structures/GuildMember.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/src/util/GuildMemberFlagsBitField.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Upstream:
- discord/discord-api-docs#5874
Depends on:
- discordjs/discord-api-types#700
=> feat(GuildMember): add `flags`

src/index.js, src/managers/GuildMemberManager.js, src/structures/GuildMember.js, src/util/GuildMemberFlags.js, typings/index.d.ts
=> feat(GuildMember): v13 add `flags`

src/structures/Guild.js, typings/index.d.ts
Adds  `INVITES_DISABLED` feature
And backports #8801
=> feat v13: add `INVITES_DISABLED` guild feature

src/managers/GuildChannelManager.js, src/structures/NewsChannel.js, typings/index.d.ts
Backports #8567
It includes no braking changes, because `NewsChannel#addFolower` cant be changed to return webook id :(
=> feat v13: add `addFollower` on GuildChannelManager

packages/discord.js/src/structures/InteractionResponse.js, packages/discord.js/typings/index.d.ts
This PR adds the `delete`, `edit`, and `fetch` methods to the `InteractionResponse` class.
=> feat(InteractionResponse): add new methods

packages/ws/README.md, packages/ws/__tests__/strategy/WorkerShardingStrategy.test.ts, packages/ws/__tests__/ws/WebSocketManager.test.ts, packages/ws/src/utils/constants.ts, packages/ws/src/ws/WebSocketManager.ts
Removes `manager#setStrategy` in favor of a new `buildStrategy` manager option.
=> refactor(WebSocketManager): passing in strategy

packages/discord.js/typings/index.d.ts
Leftover from #8957
This interface lives in `@discordjs/formatters` now
https://github.com/discordjs/discord.js/blob/9681f348770b0e2ff9b7c96b1c30575dd950e2ed/packages/formatters/src/escapers.ts#L3
=> types: remove `EscapeMarkdownOptions`

packages/discord.js/src/structures/Message.js
This PR fixes an issue in which attempting to use the  `bulkDeletable` getter on a message originating from a DM channel will throw an error.
**Status and versioning classification:** minor
=> fix(Message): `bulkDeletable` permissions should be retrieved later for DMs

packages/discord.js/src/structures/Message.js, packages/discord.js/src/util/Constants.js, packages/discord.js/typings/index.d.ts
This PR adds check for deletable message types in `Message#deletable`
https://github.com/discord/discord-api-docs/pull/5148
=> fix(Message#deletable): add check for deletable message types

packages/discord.js/src/structures/AutoModerationActionExecution.js, packages/discord.js/typings/index.d.ts
Adds `channel` and `user` getters
Code changes have been tested against the Discord API
I know how to update typings and have done so
This PR changes the library's interface (methods or parameters added)
=> feat(AutoModerationActionExecution): add `channel`, `user` and `member` getters

packages/discord.js/src/structures/InteractionCollector.js, packages/discord.js/src/structures/Message.js
I think pr name is self-explaining
- This PR **only** includes non-code changes, like changes to documentation
=> docs: make interactionResponse as optional

packages/discord.js/src/managers/GuildForumThreadManager.js, packages/discord.js/src/structures/interfaces/TextBasedChannel.js, packages/discord.js/typings/index.d.ts
This PR allows sending messages with `SuppressNotifications` flag in TypeScript
Closes #9176
=> types: allow sending messages with `SuppressNotifications` flag

src/managers/GuildForumThreadManager.js, src/structures/interfaces/TextBasedChannel.js, src/util/MessageFlags.js, typings/index.d.ts
=> feat: v13 support `SUPPRESS_NOTIFICATIONS` flag

src/client/actions/Action.js, src/client/actions/ActionsManager.js, src/structures/Message.js
Backports (?) https://github.com/discordjs/discord.js/pull/9203
=> fix(Actions): inject built data by using a symbol

packages/voice/__tests__/VoiceUDPSocket.test.ts, packages/voice/src/networking/VoiceUDPSocket.ts
Supersedes #9195 
Takes a part in solving part of #8482 and #9185 as recommended in DDevs. While UDP keepAlives aren't documented (and technically not needed either), we need to keep them in order to ensure voice receivers still work.
Tested too on a bot, and this change helped the audio not cut out after 1 minute (ala 12 keep alives packets sent)
=> fix(Voice): send keep alives without awaiting a response

src/rest/RequestHandler.js
I use a proxy with discord.js and when deferring interaction responses, I get the following error:
```
TypeError: Cannot read properties of null (reading 'startsWith')
at parseResponse (/node_modules/discord.js/src/rest/RequestHandler.js:14:38)
```
In the main branch, this issue has been fixed already, although a bit more extensively. I'm still on v13 myself and this small change fixed the error for me and hasn't caused any other issues.
=> Fix a rare error regarding interactions

src/structures/ThreadChannel.js
v13 does not use `.fetch({ message })`. This PR fixes internal code for `ThreadChannel#fetchStarterMessage()` which uses that syntax.
=> fix(ThreadChannel): fetch starter message properly

packages/ws/src/ws/WebSocketShard.ts
Puts us more in line with https://discord.com/developers/docs/topics/gateway#sending-heartbeats - where the impl prior to this PR effectively just meant a hardcoded jitter of `1`.
Closes #9197
=> feat(WebSocketShard): heartbeat jitter

packages/ws/src/ws/WebSocketShard.ts
Prior to this PR, calling `#send` in a `Ready` listener will cause `#send` to infinitely hang due to how we set the internal `status`.
Also guarantees session info will be up-to-date when ready is fired.
=> fix(WebSocketShard): #send race condition due to ready state

packages/discord.js/src/managers/MessageManager.js
**Please describe the changes this PR makes and why it should be merged:** [Discord's documentation](https://discord.com/developers/docs/resources/channel#get-channel-messages) mentions that you can only use `before`, `after` or `around` when fetching messages. This is not mentioned in D.JS documentation, and after some time trying to figure out why I was getting more messages than I should, decided to read the documentation.
This only changes the documentation.
- Code changes have been tested against the Discord API, or there are **no code changes**
- I know how to update typings and have done so, **or typings don't need updating**
*I submitted this before …
=> docs(MessageManager): add clarification to fetch messages

packages/discord.js/src/managers/ThreadManager.js, packages/discord.js/src/util/Util.js, packages/rest/src/lib/RequestManager.ts
Snowflakes length depends on the UInt64 max value length and the Discord epoch.
- `2^64` max length is 20.
- A snowflake created a week after Discord epoch is 16 length minimum.
This PR change all snowflakes regex to `\d{16,20}`.
=> fix(snowflake): snowflakes length

packages/collection/src/collection.ts, packages/discord.js/src/client/Client.js, packages/discord.js/src/managers/GuildBanManager.js, packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/src/managers/GuildManager.js, packages/discord.js/src/managers/GuildMemberManager.js, packages/discord.js/src/managers/GuildScheduledEventManager.js, packages/discord.js/src/managers/RoleManager.js, packages/discord.js/src/managers/ThreadManager.js, packages/discord.js/src/structures/ApplicationCommand.js, packages/discord.js/src/structures/ClientPresence.js, packages/discord.js/src/structures/ClientUser.js, packages/discord.js/src/structures/CommandInteractionOptionResolver.js, packages/discord.js/src/structures/DMChannel.js, packages/discord.js/src/structures/Guild.js, packages/discord.js/src/structures/GuildChannel.js, packages/discord.js/src/structures/InviteGuild.js, packages/discord.js/src/structures/MessagePayload.js, packages/discord.js/src/structures/VoiceState.js, packages/discord.js/src/util/BitField.js, packages/docgen/src/types/param.ts, packages/docgen/src/types/typedef.ts, packages/formatters/src/formatters.ts, packages/voice/src/DataStore.ts, packages/voice/src/VoiceConnection.ts, packages/voice/src/audio/AudioResource.ts, packages/voice/src/networking/Networking.ts, packages/voice/src/networking/VoiceWebSocket.ts, packages/voice/src/receive/AudioReceiveStream.ts
Updated all of the `typeof x === "undefined"` into `x === undefined` (also !==) as it is needlessly verbose since in strict mode the only reason to use `typeof` is if `x` might not be declared
This also brings in more consistency since `x === undefined` was already being used in some places (!== too), e.g.
https://github.com/discordjs/discord.js/blob/dc142c47e4021d6d37712453cc2fad6e4fe4e9f7/packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionWithChoicesAndAutocompleteMixin.ts#L34
https://github.com/discordjs/discord.js/blob/dc142c47e4021d6d37712453cc2fad6e4fe4e9f7/packages/discord.js/src/managers/ChannelManager.js#L22
- Code changes have been …
=> refactor: compare with `undefined` directly

packages/discord.js/src/util/Constants.js
This PR adds `GuildStageVoice` channel type to the TextBasedChannelTypes constant, which was already present in the typings.
=> fix(TextBasedChannelTypes): add `GuildStageVoice`

packages/ws/src/ws/WebSocketShard.ts
Bug introduced by #9223 
See https://canary.discord.com/channels/222078108977594368/1086244458900750367/1086618807059087470 or https://canary.discord.com/channels/222078108977594368/1086616622959177788/1086616763086680134 (internal)
=> fix(WebSocketShard): cancel initial heartbeat in destroy

packages/builders/package.json, packages/builders/tsconfig.json, packages/collection/package.json, packages/next/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, tsconfig.json, yarn.lock
Mentioning @vladfrangu and @didinele here as they were part of a discussion on this topic on Discord.
---
My attempt at summarizing it all for other readers:
The issue was two-fold.
First of all, tsup starts using swc when `emitDecoratorMetadata` and `@swc/core` is installed. `@swc/core` is installed transiently, which still causes the problem. Okay, sure, so we move the `emitDecoratorMetadata` option to just `packages/builders/tsconfig.json` seeing as the other packages don't use decorators anyway. But that still leaves solving the issue for builders. @vladfrangu ended up finding out that there was a bug in how esbuild handles plugins causing the esbuild-plugin-version-injector plugin to not get loaded. This is …
=> build: resolve issue with esbuild-plugin-version-injector not working

packages/rest/src/lib/RequestManager.ts, packages/rest/src/lib/handlers/SequentialHandler.ts, packages/rest/src/lib/utils/constants.ts, tsconfig.json
The motivation is that `const enum` produces ambient const enums when compiling which in turn causes issues with TypeScript 5.x when `verbatimModuleSyntax` is enabled.
Furthermore, the generally accepted best practice is to avoid `const enum`s when writing libraries. Can back this up with statements from TS maintainers if needed, I know they made them, I just can't be bothered to find the GitHub links lmao. @vladfrangu will probably be able to find those links much easier than me as it was also the motivation to remove `const enum`'s from discord-api-types.
- I know how to update typings …
=> fix(rest): remove `const enum`s in favour of regular enums

packages/ws/src/ws/WebSocketShard.ts
https://canary.discord.com/channels/222078108977594368/1086244458900750367/1087367405623332884
=> fix(WebSocketShard): don't close in #destroy when status is connecting

.github/workflows/lock.yml
Running at 16:00 every day, this will lock **closed** issues after 365 days of inactivity to help prevent the bumping of outdated issues.
=> ci: Lock ancient issues

packages/discord.js/src/managers/ThreadManager.js
The API uses the `archive_timestamp` when using `before`.
=> docs(FetchArchivedThreadOptions): `before` respects `archive_timestamp`, not creation timestamp

packages/discord.js/src/managers/ThreadManager.js
This method was internally not passing `cache` and `force` correctly:
https://github.com/discordjs/discord.js/blob/51edba78bc4d4cb44b4dd2b79e4bbc515dc46f5b/packages/discord.js/src/managers/ChannelManager.js#L106-L117
=> fix(ThreadManager): Respect `cache` and `force` in fetching

packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/src/managers/ThreadManager.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
- Fetching active threads in a guild does not yield the `has_more` property.[^1]
- `has_more` does not appear to be marked as missing or potentially `null`.[^2][^3][^4]
- `members` was not returned when fetching active threads in a guild.
- The permission requirement to fetch active threads in the guild did not seem to be true. Discord's API documentation does not state this,[^1] but does for other thread-fetching methods.[^2][^3][^4]
[^1]: https://discord.com/developers/docs/resources/guild#list-active-guild-th …
=> fix(ThreadManager): add `members` and conditionally include `hasMore`

packages/discord.js/src/structures/Message.js
[Recent changes](https://discord.com/developers/docs/change-log#update-to-locked-threads) regarding locked threads were rolled out this week.
If a bot does not have permission to manage threads, it will not be able to edit its own message even if the thread is not archived.
I've also added a check that was probably forgotten, a bot can't edit its own message if the thread is archived.
=> fix(Message#editable): update editable check in threads locked

packages/discord.js/src/util/Constants.js, packages/discord.js/typings/index.d.ts
Since 14.8.0, Constants.TextBasedChannelTypes is no longer assignable to ApplicationCommand#channelTypes due to the DM type not being accepted, so this fixes that
=> feat: add GuildBasedTextChannelTypes

apps/website/src/components/documentation/ObjectHeader.tsx, apps/website/src/components/model/TypeAlias.tsx, apps/website/src/components/model/Variable.tsx, apps/website/src/components/model/enum/Enum.tsx, apps/website/src/pages/api/og.tsx, apps/website/src/pages/api/og_model.tsx
Oversight from the website refactor.
This also fixes a build issue issue with our og routes, the latest nextjs wants you to use `experimental-edge` instead of `edge`.
=> fix(website): show headers for type aliases

src/util/Formatters.js, typings/index.d.ts
Backports `chatInputApplicationCommandMention` formatter
Its done in *manual* way as builders cannot be updated
=> feat: backport `chatInputApplicationCommandMention`

apps/website/package.json, apps/website/src/app/docs/packages/[package]/[version]/[item]/page.tsx, apps/website/src/app/docs/packages/[package]/[version]/layout.tsx, apps/website/src/app/docs/packages/[package]/[version]/page.tsx, apps/website/src/app/layout.tsx, apps/website/src/components/Anchor.tsx, apps/website/src/components/CmdK.tsx, apps/website/src/components/Footer.tsx, apps/website/src/components/Header.tsx, apps/website/src/components/Nav.tsx, apps/website/src/components/Panel.tsx, apps/website/src/components/Property.tsx, apps/website/src/components/PropertyList.tsx, apps/website/src/components/Sidebar.tsx, apps/website/src/components/documentation/MemberContainerDocumentation.tsx, apps/website/src/components/documentation/section/DocumentationSection.tsx, apps/website/src/components/documentation/section/MethodsSection.tsx, apps/website/src/components/documentation/tsdoc/TSDoc.tsx, apps/website/src/components/model/Class.tsx, apps/website/src/components/model/Interface.tsx, apps/website/src/components/model/Variable.tsx, apps/website/src/components/model/enum/Enum.tsx, apps/website/src/components/model/method/MethodHeader.tsx, apps/website/src/styles/cmdk.css, packages/ui/src/lib/components/Section.tsx
=> refactor(website): redesign

packages/discord.js/scripts/generateRequires.mjs, packages/discord.js/src/client/actions/ActionsManager.js
Resolves #9289 by ensuring symbols are kept.
=> fix: Keep symbols in actions manager

packages/core/src/api/interactions.ts
=> fix(core): include data for defer

src/util/MessageFlags.js
Fix a little typo which added in #9184
=> fix: Typo in `src/util/MessageFlags.js`

packages/brokers/src/brokers/Broker.ts, packages/brokers/src/brokers/redis/BaseRedis.ts, packages/builders/src/interactions/contextMenuCommands/ContextMenuCommandBuilder.ts, packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts, packages/builders/src/interactions/slashCommands/SlashCommandSubcommands.ts, packages/builders/src/messages/embed/Embed.ts
As stated in [`@see`](https://tsdoc.org/pages/tags/see), an explicit `@link` tag is required for linking. Wherever we put a link, it must be in a `@link` tag.
=> docs: Use `@link` in `@see`

apps/website/src/components/documentation/util.ts
This method is called in three different places:
https://github.com/discordjs/discord.js/blob/1b9d07f941dc3edf20cd5e65c56b70d009880893/apps/website/src/app/docs/packages/%5Bpackage%5D/%5Bversion%5D/layout.tsx#L40-L47
https://github.com/discordjs/discord.js/blob/1b9d07f941dc3edf20cd5e65c56b70d009880893/apps/website/src/components/InheritanceText.tsx#L5-L17
https://github.com/discordjs/discord.js/blob/1b9d07f941dc3edf20cd5e65c56b70d009880893/apps/website/src/components/documentation/tsdoc/TSDoc.tsx#L40-L48
An extra `/` was being prepended unnecessarily, causing URLs to have `//` somewhere. This pull request removes that.
=> fix(util): Remove extra slash

packages/discord.js/src/managers/ApplicationCommandManager.js, packages/discord.js/src/managers/GuildStickerManager.js, packages/discord.js/src/managers/MessageManager.js, packages/discord.js/src/structures/ActionRow.js, packages/discord.js/src/structures/ActionRowBuilder.js, packages/discord.js/src/structures/AttachmentBuilder.js, packages/discord.js/src/structures/ButtonBuilder.js, packages/discord.js/src/structures/ChannelSelectMenuBuilder.js, packages/discord.js/src/structures/EmbedBuilder.js, packages/discord.js/src/structures/MentionableSelectMenuBuilder.js, packages/discord.js/src/structures/MessagePayload.js, packages/discord.js/src/structures/ModalBuilder.js, packages/discord.js/src/structures/RoleSelectMenuBuilder.js, packages/discord.js/src/structures/StringSelectMenuBuilder.js, packages/discord.js/src/structures/StringSelectMenuOptionBuilder.js, packages/discord.js/src/structures/TextInputBuilder.js, packages/discord.js/src/structures/UserSelectMenuBuilder.js, packages/discord.js/src/structures/interfaces/TextBasedChannel.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/src/util/Components.js
I think we should stop referencing this TypeScript interface in our _JavaScript_ documentation.
Look at this:
https://github.com/discordjs/discord.js/blob/1b9d07f941dc3edf20cd5e65c56b70d009880893/packages/discord.js/src/structures/ActionRowBuilder.js#L19-L31
`JSONEncodable<APIActionRowComponent<APIActionRowComponentTypes>>|APIActionRowComponent<APIActionRowComponentTypes>`. Well damn. This is the same type duplicated with `JSONEncodable`.
The proposed modification: `ActionRow|ActionRowBuilder|APIActionRowComponent`. Wow, much more _understandable_, right?
JavaScript users only need to know what they can pass without needing to deeply understand all associated typings. One may pass a received (immutable) `ActionRow` …
=> docs: Remove `JSONEncondable`

apps/website/src/components/documentation/util.ts, apps/website/src/util/constants.ts, packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts
Currently, the only `@link`s that work are those that do not have parents. Those look like `{@link JSONEncodable}`, `{@link RedisBrokerOptions}`, `{@link JSONEncodable}` etc. However, if we were to do `{@link JSONEncodable.toJSON}`, the link becomes malformed. We are looking for the `toJSON` symbol of `JSONEncodable`, but the code had no parent check.
I have opted to fix this by checking if the parent is the `ApiItemKind.EntryPoint`. If this condition is met, it _should_ have no parent and we proceed as we always have. If it is not `ApiItemKind.EntryPoint`, then we can parse the parent.
=> fix: Correct `@link` tags that involve parents

packages/discord.js/src/managers/RoleManager.js
Stored the position of the roles to not call the `position` getter twice per role as it is a reasonably heavy operation
<details>
<summary>Role#position</summary>
https://github.com/discordjs/discord.js/blob/b2eec5f9fcf37ebb3b7f87a67a6ee3160c182183/packages/discord.js/src/structures/Role.js#L186-L189
https://github.com/discordjs/discord.js/blob/b2eec5f9fcf37ebb3b7f87a67a6ee3160c182183/packages/discord.js/src/structures/Guild.js#L1296-L1298
https://github.com/discordjs/discord.js/blob/b2eec5f9fcf37ebb3b7f87a67a6ee3160c182183/packages/discord.js/src/util/Util.js#L270-L277
</details>
- I know …
=> perf(RoleManager): dont call Role#position getter twice per role

apps/website/src/components/documentation/tsdoc/BlockComment.tsx, apps/website/src/components/documentation/tsdoc/TSDoc.tsx
Adds support for the `@defaultValue` tag. Like the `@example` tag, this had to be found in the custom blocks.
=> feat: Support `@defaultValue`

packages/ws/src/ws/WebSocketShard.ts
yet again, because this stuff was a mess.
all in all, this PR does the following things:
- `waitForEvent` now properly cancels if the connection closes while waiting (oops!!! this was a giant oversight that caused niche bugs)
- got rid of the separate bubble error method, since it wasn't all that great
- `connect` no longer throws if something times out during the initial connect, it'll just keep trying until we get Ready (unless something is hard-thrown, like no-auth)
- deals with sessions better, no longer caching them on the class itself
- adds a nice debug log that should help users identify if their `updateSessionInfo` callback is being nasty
tagged as draft until @vladfrangu messes with it.
**Status and …
=> refactor(WebSocketShard): waitForEvent and its error handling

src/client/actions/WebhooksUpdate.js, src/structures/BaseGuildVoiceChannel.js, src/structures/StageChannel.js, src/structures/VoiceChannel.js, src/structures/Webhook.js, src/util/Constants.js, typings/index.d.ts, typings/index.test-d.ts
Backports:
- #9134
And that was sorted alphabetically so that's why changes looks terrible
=> feat(StageChannel): v13 support messages

apps/guide/src/content/03-additional-info/02-collections.mdx
Seems `/[a-z]/i` after this markdown disrupts it. I've added a word after so it properly applies markdown.
=> fix(collection): `filter()` markdown

.github/workflows/issue-triage.yml, .github/workflows/lighthouse.yml
issue-labeler has been updated after a year. This will stop deprecation warnings from emitting in the logs, most importantly.
Also updated github-script.
=> ci: Update actions

packages/discord.js/README.md, packages/discord.js/src/util/Partials.js
This PR converts the documentation examples from CommonJS to ESM.
=> docs: use ESM code in examples

packages/discord.js/src/structures/interfaces/InteractionResponses.js, packages/discord.js/src/util/APITypes.js
**Please describe the changes this PR makes and why it should be merged:** Updates the various showModal docs so it's showing the acceptable parameters
**Status and versioning classification:** v14
=> docs(InteractionResponses): showModal docs change

packages/discord.js/src/structures/interfaces/TextBasedChannel.js
For embeds, an array of `EmbedBuilder`s were missing.
For action rows, an array of `APIActionRowComponent`s were missing (this is typed already).
Also, they're now all within the same array as we simply call the JSON transformer or rebuild from the passed data, so it's technically accurate now.
=> docs(BaseMessageOptions): Fix embeds and components

packages/discord.js/src/util/APITypes.js
These are used in the documentation but were missing references.
=> docs(APITypes): Document role & user select menu components

apps/guide/package.json, apps/website/package.json, packages/actions/package.json, packages/api-extractor-utils/package.json, packages/brokers/package.json, packages/builders/package.json, packages/collection/package.json, packages/core/package.json, packages/discord.js/package.json, packages/docgen/package.json, packages/formatters/package.json, packages/next/package.json, packages/proxy-container/package.json, packages/proxy/package.json, packages/rest/package.json, packages/scripts/package.json, packages/scripts/src/createPackage.ts, packages/scripts/src/template/template.package.json, packages/ui/package.json, packages/util/package.json, packages/voice/package.json, packages/ws/package.json
This PR adds the directory property to the repository in all the `package.json`'s inside the monorepo (apps and packages).
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository
> If the `package.json` for your package is not in the root directory (for example if it is part of a monorepo), you can specify the directory in which it lives:
```json
{
"repository": {
"type": "git",
"url": "https://github.com/facebook/react.git",
"directory": "packages/react-dom"
}
}
```
- This PR **only** includes …
=> chore: Add directory to package.json

packages/discord.js/src/structures/AutoModerationRule.js
Update the docs descriptions for some of the AutoModerationRule methods to make them clearer and easier to understand
**Status and versioning classification:** Minor/patch/docs only
Comment below to which docs page you think needs updating next!  The post with the most thumbs up will be my next project!  Don't forget to star the repo!
=> docs(AutoModerationRule): update docs

README.md, docs/README.md, src/client/Client.js, src/managers/ApplicationCommandManager.js, src/managers/ChannelManager.js, src/managers/RoleManager.js, src/structures/CategoryChannel.js, src/structures/Channel.js, src/structures/ThreadChannel.js, src/structures/interfaces/TextBasedChannel.js, src/util/LimitedCollection.js, src/util/Options.js, src/util/Sweepers.js, typings/index.d.ts
Backports:
- https://github.com/discordjs/discord.js/pull/9437
- https://github.com/discordjs/discord.js/pull/9322
- https://github.com/discordjs/discord.js/pull/9326
- https://github.com/discordjs/discord.js/pull/9335
- https://github.com/discordjs/discord.js/pull/9327
- https://github.com/discordjs/discord.js/pull/9352
- https://github.com/discordjs/discord.js/pull/9343
=> fix: Miscellaneous fixes 

src/util/Constants.js, typings/enums.d.ts, typings/index.d.ts
After sorting the TypeScript constant alphabetically, I began to notice inconsistencies.
- #8886 removed `ApplicationCommandOptionTypes` from the typings
- #7431 added `ModalComponentTypes` in the typings, but it is not used anywhere or exported in JavaScript
- #9072 did not add `ApplicationRoleConnectionMetadataTypes` to the typings
- `MessageTypes` was never documented (yes, this is very old)
- #5570 added `ThreadChannelTypes` in the typings but was lacking documentation
Also sorted the JavaScript constant. It should be easier to detect these things when comparing them now.
- I know how …
=> fix(Constants): Ordering and missing information

packages/discord.js/src/client/websocket/WebSocketManager.js
Fixes the missing emitting of raw WebSocketManager events.
=> fix(WebSocketManager): emit raw ws events again

apps/guide/src/components/DocsLink.tsx, apps/guide/src/content/05-additional-info/03-updating-to-v14.mdx, apps/guide/src/util/constants.ts
An unfortunate port introduced `<PackageLink name="ws" />`. This component does not exist.
`DocsLink` has been tweaked to allow _only_ a package, which then links to their entry points in the documentation.
I also updated the discord.js version to 14.10.2 and fixed the `BaseFetchOptions` link I happened to come across (this is a `typedef`, not a `class`).
=> fix(guide): Fix unknown component in v14 update guide

packages/core/src/api/roleConnections.ts
`RESTPutAPIApplicationCommandPermissionsJSONBody` is the wrong type for this. The correct type is `RESTPutAPIApplicationRoleConnectionMetadataJSONBody` (as evident from the name).
=> fix(roleConnections): Fix `body` type for `updateMetadataRecords()`

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
The options of a string select menu are required. Sending a request without `options` will yield an error:
```xl
DiscordAPIError[50035]: Invalid Form Body
components[0].components[0].options[BASE_TYPE_BAD_LENGTH]: Must be between 1 and 25 in length.
```
=> types(StringSelectMenuComponentData): `options` is required

packages/ws/__tests__/ws/WebSocketManager.test.ts, packages/ws/src/ws/WebSocketShard.ts
=> fix(WebSocketShard): wait a little before reconnecting

packages/proxy-container/Dockerfile
Closes #9088
because apparently root cli dev deps were inaccessible in the late stage of `yarn` ??
either way, once https://github.com/vercel/turbo/issues/2791 is completely resolved, we can move to something like this:
```dockerfile
FROM node:18-alpine as builder
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /usr/proxy
COPY . .
RUN yarn dlx turbo prune --scope=@discordjs/proxy-container --docker
FROM node:18-alpine AS installer
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /usr/proxy
COPY .gitignore .gitignore
COPY .yarn/ .yarn/
COPY .yarnrc.yml .yarnrc.yml
COPY --from=builder /usr/proxy/out/json/ .
COPY --from=builder /usr/proxy/out/yarn.lock ./yarn.lock
RUN yarn install --immutable …
```
=> fix(proxy-container): docker builds

packages/core/README.md, packages/core/package.json, packages/discord.js/package.json, packages/proxy-container/package.json, packages/proxy/README.md, packages/proxy/package.json, packages/proxy/src/util/responseHelpers.ts, packages/rest/README.md, packages/rest/__tests__/BurstHandler.test.ts, packages/rest/__tests__/REST.test.ts, packages/rest/__tests__/RequestHandler.test.ts, packages/rest/__tests__/UndiciRequest.test.ts, packages/rest/package.json, packages/rest/src/lib/REST.ts, packages/rest/src/lib/RequestManager.ts, packages/rest/src/lib/global/fetch.d.ts, packages/rest/src/lib/handlers/BurstHandler.ts, packages/rest/src/lib/handlers/SequentialHandler.ts, packages/rest/src/lib/handlers/Shared.ts, packages/rest/src/lib/interfaces/Handler.ts, packages/rest/src/lib/utils/constants.ts, packages/rest/src/lib/utils/utils.ts, packages/rest/src/strategies/undiciRequest.ts, packages/rest/tsup.config.ts, packages/ws/README.md, packages/ws/package.json, vitest.config.ts, yarn.lock
Undici request was originally chosen for performance reasons. ~~At the scale of discord bots, this performance difference is irrelevant.~~ This instead is the first step towards cross environment compatability.
This refactor also changes the actual network request portion into a strategy. By default, this will use `undici.request`. This strategy has also been provided and exported as /undiciRequest
=> refactor(rest): switch api to fetch-like and provide strategies

packages/discord.js/src/structures/Role.js
New getter is around 10x faster
roles itself is a getter which iterates over guild roles
And _roles is just an array of pure ids, which we need
=> perf(Role): improve `members` getter

src/managers/AutoModerationRuleManager.js, src/structures/AutoModerationRule.js
`AutoModerationRuleTriggerTypes` does not exist. The correct documentation link is [`AutoModerationRuleTriggerType`](https://old.discordjs.dev/#/docs/discord.js/v13/typedef/AutoModerationRuleTriggerType).
=> docs: Fix `AutoModerationRuleTriggerTypes` link

apps/guide/src/components/DocsLink.tsx
There are edge cases where we need to override the documentation link's text wholly.
=> feat(DocsLink): Support overriding text

packages/discord.js/package.json, yarn.lock
#9416 pinned the version of `/rest` in discord.js but `/ws` also had the node version bump and it's being used in discord.js, which is a breaking change
=> chore(deps): pin `@discordjs/ws` version in discord.js

apps/guide/src/components/DiscordAPITypesLink.tsx, apps/guide/src/components/Mdx.tsx, apps/guide/src/content/04-popular-topics/02-audit-logs.mdx, apps/guide/src/content/05-additional-info/03-updating-to-v14.mdx, apps/guide/src/util/constants.ts
Like `<DocsLink>`, this will be for discord-api-types.
<details>
<summary>I've written some test cases which you may wish to see the changes with (alongside your own, if necessary).</summary>
```tsx
<DiscordAPITypesLink> f</DiscordAPITypesLink>.
<DiscordAPITypesLink />.
<DiscordAPITypesLink scope="gateway" type="interface" parent="GatewayURLQuery">
etyhetyhth
</DiscordAPITypesLink>
<DiscordAPITypesLink scope="gateway" type="interface" parent="GatewayURLQuery"></DiscordAPITypesLink>.
<DiscordAPITypesLink scope="globals" parent="Snowflake"></DiscordAPITypesLink>.
<DiscordAPITypesLink scope="payloads" parent="PermissionFlagsBits"></DiscordAPITypesLink>.
<DiscordAPITypesLink scope="payloads" type="interface" …
```
=> feat: Create discord-api-types documentation component

packages/ws/src/ws/WebSocketShard.ts
=> fix(WebSocketShard): handle initial connect being a resume

packages/discord.js/src/structures/AutocompleteInteraction.js
The `jsonTransformer()` was converting locales like `zh-TW` to `zh_TW` resulting in an API error being returned.
=> fix(AutocompleteInteraction): Prevent snake casing of locales

packages/core/src/api/guild.ts
`getMemberBan()` isn't implemented at all and `getMemberBans()` currently doesn't support query options.
=> feat(api): add `getMemberBans()` query options and `getMemberBan()`

packages/core/src/api/guild.ts
[The Discord API docs for this route](https://discord.com/developers/docs/resources/guild#modify-guild-mfa-level-json-params) say to use `level`, not `mfa_level`. [Discord API Types](https://discord-api-types.dev/api/discord-api-types-v10/interface/RESTPostAPIGuildsMFAJSONBody#Properties) say the same thing.
Additionally, using `mfa_level` won't actually do anything but using `level` will.
=> fix(GuildsAPI): use `level` rather than `mfa_level` when editing MFA

packages/core/src/api/guild.ts, packages/core/src/api/webhook.ts
There were two instances where `string` instead of `Snowflake` were being used.
=> types: use `Snowflake` instead of `string` for snowflakes

packages/core/src/api/applicationCommands.ts, packages/core/src/api/guild.ts, packages/core/src/api/interactions.ts, packages/core/src/api/webhook.ts
This PR mainly contains corrections for incorrect typings that were overlooked.
In addition this also makes `InteractionsAPI#followUp()` return a result which should always be `Promise<APIMessage>` on success (according to the [Discord docs](https://discord.com/developers/docs/interactions/receiving-and-responding#create-followup-message) on the creation of followup messages: "Functions the same as Execute Webhook, but `wait` is always true.")
=> fix(api): various fixes for overlooked stuff

packages/discord.js/src/client/websocket/WebSocketManager.js
I use the client itself as an event emitter for testing, without callling login.
I have overridden the `destroy()` method to include file io closing and realized that the application crashes because `._ws` is null
this is a patch
=> fix(Client): safe call for possibly null WebSocket

packages/ws/src/ws/WebSocketManager.ts
For small bots with only one shard the result of `WebSocketManager#fetchGatewayInformation()` wasn't cached, because discord sends `session_start_limit.reset_after` of 0 in that case.
=> fix(WebSocketManager): always cache result of fetchGatewayInformation

packages/discord.js/typings/index.d.ts
Just like the property below this, it's only available in guilds.
=> types(BaseInteraction): `appPermissions` not `null` in guilds

packages/discord.js/src/structures/ModalSubmitInteraction.js, packages/discord.js/typings/index.d.ts
This PR simply fixes an issue in ModalSubmitFields#components as it wasn't marked as an array and instead was simply an action row
=> types(ModalSubmitFields): components is an array

apps/website/src/components/ExcerptText.tsx
This fixes the duplicate keys in the ItemLinks which causes the duplication of elements.
resolves #9599
=> fix(website): Overload switcher duplicates reference links

packages/builders/src/interactions/slashCommands/mixins/NameAndDescription.ts
setNameLocalization typo
fixed a JSDoc typo in NameAndDescription.ts > setNameLocalization
This PR **only** includes non-code changes, like changes to documentation, README, etc.
=> setNameLocalization typo

packages/core/src/api/channel.ts
Implements [Edit Channel Permissions](https://discord.com/developers/docs/resources/channel#edit-channel-permissions) and [Delete Channel Permission](https://discord.com/developers/docs/resources/channel#delete-channel-permission).
=> feat(ChannelsAPI): add permission overwrites

packages/discord.js/src/structures/User.js, packages/discord.js/typings/index.d.ts
This PR removes the deprecation warning from User#tag, simply because, as Discord stated, bots will continue on the legacy username system for the time being, so it's still needed, as well as with users that haven't completed the migration yet/haven't had accesses to it, thus there is no reasonable way a developer can remove all access to the tag property just yet. I would even argue that there's no need to check for discriminators equal to "0" here and let devs do that check on their end, but that's out of the scope of this PR and something I'd rather not touch on.
- I know how to update …
=> refactor(User): remove deprecation warning from tag

packages/discord.js/src/sharding/Shard.js, packages/discord.js/src/util/ShardEvents.js, packages/discord.js/typings/index.d.ts
With #9626, `resume` events can now be received within the sharding process.
Therefore, this PR is to make it possible to listen to the `Shard#resume` event even in shards.
This allows modern code using callbacks to know when to resume without having to check the `Shard#ready` flag regularly.
=> feat: add resume event in shard

packages/ws/src/ws/WebSocketShard.ts
Resolves #9621.
~~It seems like the errors could only occur when using `WebSocketShard#connect` (and I didn't want to modify much code), so my approach was to listen to the close event and throw the errors directly from `connect`, therefore making them catchable.~~
Swaps all `throw`s on close errors with emitting `WebSocketShardEvents.Error`, then catching and throwing them directly inside of `connect`.
=> fix(WebSocketShard): close errors not being catchable

src/structures/User.js, src/util/Constants.js, typings/index.d.ts
v14: #8914 
Supersedes: #9018 
> Added:
- `User#avatarDecoration`
- `User#avatarDecorationURL()`
- This PR does not include any braking changes
=> feat: user avatar decorations

apps/website/src/components/CmdK.tsx
This fixes the symbol for type aliases an the search.
=> fix(website): type alias search symbol

packages/core/src/api/webhook.ts
Allows [Get Webhook with Token](https://discord.com/developers/docs/resources/webhook#get-webhook-with-token), [Modify Webhook with Token](https://discord.com/developers/docs/resources/webhook#modify-webhook-with-token), and [Delete Webhook with Token](https://discord.com/developers/docs/resources/webhook#delete-webhook-with-token) to be used without bot authentication.
Also moves `get`'s `token` parameter to options.
=> feat(WebhooksAPI): allow `with token` requests without bot auth

packages/discord.js/src/structures/BaseChannel.js
This already exists (and was being overwritten) here:
https://github.com/discordjs/discord.js/blob/bc83cabfdad76fec9352ddb9a7d488e058ede180/packages/discord.js/src/util/APITypes.js#L43-L46
=> docs(BaseChannel): Remove `APIChannel`

packages/discord.js/src/structures/ChannelSelectMenuInteraction.js, packages/discord.js/src/util/Channels.js
`Channel` does not exist in our definitions. The correct one is `BaseChannel`.
=> docs: Change `Channel` to `BaseChannel`

packages/create-discord-bot/src/create-discord-bot.ts
Throw an error if the given directory is not actually a directory.
See [#9570 (review)](https://github.com/discordjs/discord.js/pull/9570#discussion_r1264713786).
=> feat(create-discord-bot): throw error if the directory is a file

packages/rest/.eslintrc.json, packages/rest/.lintstagedrc.js, packages/rest/__tests__/setup.ts, packages/rest/package.json, packages/rest/src/agnostic.ts, packages/rest/src/environment.ts, packages/rest/src/index.ts, packages/rest/src/lib/CDN.ts, packages/rest/src/lib/REST.ts, packages/rest/src/lib/RequestManager.ts, packages/rest/src/lib/errors/HTTPError.ts, packages/rest/src/lib/handlers/BurstHandler.ts, packages/rest/src/lib/handlers/SequentialHandler.ts, packages/rest/src/lib/handlers/Shared.ts, packages/rest/src/lib/utils/constants.ts, packages/rest/src/lib/utils/utils.ts, packages/rest/src/shared.ts, packages/rest/src/strategies/undiciRequest.ts, packages/rest/src/web.ts, packages/rest/tsup.config.ts, packages/rest/vitest.config.ts, packages/util/src/functions/index.ts, packages/util/src/functions/runtime.ts, packages/util/src/functions/userAgentAppendix.ts, packages/ws/src/ws/WebSocketShard.ts, yarn.lock
This PR brings in out-of-the-box support for:
- Deno
- Bun
- Cloudflare Workers
- Vercel Functions
and whatever else floats your boat. 
*note:* Bun is currently blocked with this PR due to https://github.com/oven-sh/bun/issues/3392, but 🤞 they get that fixed
=> feat: no-de-no-de, now with extra buns

packages/discord.js/src/client/websocket/WebSocketManager.js, packages/discord.js/src/util/Options.js, packages/discord.js/typings/index.d.ts
Adds support for custom identify throttlers
=> feat: add ws option support for "buildIdentifyThrottler"

packages/actions/src/uploadCoverage/action.yml
Upload the test coverage of the formatters package to codecov
=> ci: upload /formatters test coverage

packages/create-discord-bot/src/create-discord-bot.ts, packages/create-discord-bot/src/index.ts
Bug intoduced in https://github.com/discordjs/discord.js/pull/9570
Found in [djs-questions post by rob0520](https://canary.discord.com/channels/222078108977594368/1136741339476803728/1136741339476803728)
=> fix(create-discord-bot): add shebang in main file

packages/discord.js/src/index.js, packages/discord.js/src/structures/Role.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/src/util/RoleFlagsBitField.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/6269
- https://github.com/discordjs/discord-api-types/pull/782
=> feat(Role): add `flags`

packages/discord.js/src/structures/ClientApplication.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/5971
- https://github.com/discordjs/discord-api-types/pull/728
=> feat(ClientApplication): Approximate guild count and new `GET` route

packages/discord.js/src/client/actions/Action.js
Resolves #9754.
The object being sent to `GenericAction#getPayload()` might contain keys that were `undefined`. In this specific case, an ephemeral message with the direct messages intent would not contain a `guild_id`.[^1] In combination with the partial, this would lead to `manager._add(data, cache)` which would then lead to here:
https://github.com/discordjs/discord.js/blob/7295a3a94a853086f781e7810b37c77d0c7e5283/packages/discord.js/src/structures/GuildChannel.js#L66-L68
Causing `guildId` to lose its value. …
=> fix(Action): Do not set `undefined` values

packages/discord.js/typings/index.d.ts
The CachedManager's constructor has three arguments in the JS files but only two in the type declaration. I fixed that so it matches.
=> fix(types): fixed CachedManager constructor arguments in type

packages/discord.js/src/managers/CachedManager.js, packages/discord.js/src/managers/MessageManager.js, packages/discord.js/src/managers/ThreadManager.js, packages/discord.js/src/util/Options.js, packages/discord.js/src/util/Symbols.js, packages/discord.js/typings/index.d.ts
I think this has only been breaking for MessageManager and ThreadManager. It probably applies to others as well though long term.
fixes: #9759 
=> fix(CachedManager): allow overriding constructor for makeCache

packages/discord.js/src/structures/ClientUser.js, packages/discord.js/typings/index.d.ts
Discord docs says that the activity name is required, discord,js also checks that  
https://github.com/discordjs/discord.js/blob/b3c85d34a6ced8a8e2cd15a6e3879fb2dd5121d0/packages/discord.js/src/structures/ClientPresence.js#L51-L53
=> typings: Make activity name required

packages/discord.js/src/structures/ClientPresence.js, packages/discord.js/src/structures/ClientUser.js, packages/discord.js/typings/index.d.ts
custom status for bots!
* https://github.com/discord/discord-api-docs/pull/6345
=> feat(ClientPresence): allow setting activity state

apps/guide/package.json, apps/website/package.json, package.json, packages/actions/package.json, packages/brokers/package.json, packages/builders/package.json, packages/collection/package.json, packages/core/package.json, packages/create-discord-bot/package.json, packages/formatters/package.json, packages/next/package.json, packages/proxy/package.json, packages/rest/package.json, packages/scripts/package.json, packages/ui/package.json, packages/ui/vite.config.ts, packages/util/package.json, packages/ws/package.json, turbo.json, vitest.config.ts, yarn.lock
@vitest/coverage-c8 was deprecated in favour of @vitest/coverage-v8.
This also resolves the CI errors (caused by a deprecation ~~warning~~ error) in packages/ui/vite.config.ts. `"outputMode": "full"` was specified in turbo.json to see better debug logs which has since been changed to `"errors-only"`.
=> build: Update vite and other related dependencies

packages/discord.js/src/structures/Webhook.js
These were already typed, but not documented:
https://github.com/discordjs/discord.js/blob/aa27775c753cc9ee2afc97dd9bc52d04c78fe376/packages/discord.js/typings/index.d.ts#L6400-L6405
=> docs(WebhookEditOptions): Add all of the types

packages/discord.js/src/client/actions/Action.js
With this code sample:
```JavaScript
const user = await client.users.fetch("user_id");
const dm = await user.createDM();
await user.send("Hi");
```
`dm.recipientId` would change from `user_id` to the client user's id during `await user.send("Hi");`.
When `await user.send("Hi")` is called, we receive that message from the gateway and it eventually finds its way to `GenericAction#getChannel()`:
https://github.com/discordjs/discord.js/blob/188877c50af70f0d5cffb246620fa277435c6ce6/packages/discord.js/src/client/actions/MessageCreate.js#L9
https://github.com/discordjs/discord.js/blob/188877c50af70f0d5cffb246620fa277435c6ce6/packages/discord.js/src/client/actions/Action.js#L30-L41
The issue is line 31 here. The payload …
=> fix(Action): Do not add the client user as a recipient

.github/workflows/documentation.yml
This package has no documentation, so it is bound to always fail as seen [here](https://github.com/discordjs/discord.js/actions/runs/5895202930).
=> ci: Stop documentation upload for create-discord-bot

apps/guide/src/content/02-installations-and-preparations/01-installing-node-discordjs.mdx, apps/guide/src/content/03-creating-your-bot/01-configuration-files.mdx, apps/guide/src/content/05-additional-info/03-updating-to-v14.mdx, packages/create-discord-bot/README.md, packages/create-discord-bot/src/helpers/packageManager.ts, packages/discord.js/README.md, packages/formatters/README.md, packages/next/README.md, packages/proxy/README.md, packages/rest/README.md, packages/util/README.md, packages/voice/README.md, packages/ws/README.md
=> docs(create-discord-bot): support bun in create-discord-bot

packages/core/src/api/applications.ts
=> docs(ApplicationsAPI): Fix `getCurrent()` options description

packages/builders/package.json, packages/core/package.json, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, pnpm-lock.yaml
Bumps discord-api-types to 0.37.56.
=> build: Bump discord-api-types to 0.37.56

.github/workflows/publish-dev.yml
`pnpm` does not allow publishing with an unclean git tree by default, as seen [here.](https://github.com/discordjs/discord.js/actions/runs/6049153994/job/16415895720#step:6:23)
I'm not entirely sure why we do the whole `|| true` thing in the workflow, since it made it not fail despite clearly failing. I assume it's a workaround for cases where we publish a version that's already been published (e.g. due to manual workflow triggers or things of that sort), so I didn't touch it.
=> ci: fix npm dev release workflow

src/structures/GuildChannel.js, src/structures/Role.js, src/util/Util.js
Backports:
- https://github.com/discordjs/discord.js/pull/9497
The other [pr](https://github.com/discordjs/discord.js/pull/9493) isnt backported as current performance is 59 ms per 100_000 iterations
Where kyra's is 132 ms
=> perf: linear speed position getters

packages/discord.js/src/util/Options.js, packages/rest/src/lib/REST.ts
=> docs: Fix "its" typo

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
=> types(Client): fix isReady narrowing

packages/ws/src/ws/WebSocketManager.ts
See https://canary.discord.com/channels/222078108977594368/1138772709896097863/1149286266022670336
=> fix(WebSocketManager): available sessions check

packages/discord.js/typings/index.d.ts
> As soon as discord.js is imported, typescript/vscode will start suggesting browser-only variables and classes. This makes this issue unavoidable, since it occours in your whole project as soon as you simply import discord.js, which is why I'd argue that this is not low priority.
There isn't really a reason to include DOM types for undici, and the commit that introduced it doesn't explain any further behind the reasons for this change
Closes #9737
=> types: don't include dom types

packages/discord.js/src/managers/GuildManager.js, packages/discord.js/src/structures/Guild.js, packages/discord.js/src/structures/Widget.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/typings/index.d.ts
Supersedes #8589 in implementing the widget image URL.
Since the client does not need to be a member of any guild to return this URL, I have placed the implementation on the `GuildManager`. I added helper methods to the `Guild` class and the `Widget` class for ease.
=> feat: Support widget image URL

packages/discord.js/typings/index.d.ts
It was pointed out in the Discord server[^1] that this should be nullable in case a user is no longer in a guild.
[^1]: https://discord.com/channels/222078108977594368/937420598383108167/1153904233830170654
=> types(UserContextMenuCommandInteraction): Nullify `targetMember`

packages/builders/package.json, packages/core/package.json, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, pnpm-lock.yaml
Bumps discord-api-types to 0.37.59 to, most notably, make use of https://github.com/discordjs/discord-api-types/pull/824.
=> build: Bump discord-api-types to 0.37.59

apps/guide/package.json, apps/website/package.json, eslint.config.js, package.json, packages/actions/package.json, packages/api-extractor-utils/package.json, packages/brokers/package.json, packages/builders/package.json, packages/collection/package.json, packages/core/package.json, packages/create-discord-bot/package.json, packages/docgen/package.json, packages/formatters/package.json, packages/next/package.json, packages/proxy-container/package.json, packages/proxy/package.json, packages/rest/package.json, packages/scripts/package.json, packages/ui/package.json, packages/util/package.json, packages/voice/package.json, packages/ws/package.json, pnpm-lock.yaml
Bumping eslint-config-neon to stop import/extensions incorrectly reporting.
=> build: Disable import/extensions

packages/create-discord-bot/template/TypeScript/tsconfig.json
The `module` in `tsconfig.json` was changed as it was causing an error because since the `moduleResolution` is set to `NodeNext`, it must also be set to `NodeNext`.
=> fix: update module to `NodeNext` in tsconfig.json

packages/discord.js/src/structures/Role.js
Positions were not calculated right if a guild had raw positions equal across roles
This happened due to not noticing the previous sorting behavior which was (cleaned up from old v13)
```js
function discordSort(collection) {
return collection.sorted(
(a, b) => a.rawPosition - b.rawPosition || Number(BigInt(b.id) - BigInt(a.id)),
);
}
```
Peep the order: `b.id - a.id`. In current code, it's equivalent to `a.id - b.id`
v13 PR: #9872
=> fix(Role): calculate position correctly when rawPositions are equal

packages/builders/package.json, packages/core/package.json, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, pnpm-lock.yaml
Bumps discord-api-types to 0.37.60 which unblocks #9709.
=> build: Bump discord-api-types to 0.37.60

.github/workflows/publish-dev.yml
`::set-output` is deprecated per https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands. This is tested with a [release needed](https://github.com/discordjs/discord.js/actions/runs/6443524641) & [not needed](https://github.com/discordjs/discord.js/actions/runs/6443560000).
=> ci: Use non-deprecated output parameters

packages/discord.js/src/managers/MessageManager.js, packages/discord.js/typings/index.d.ts
Resolves #9667.
As pointed out in that issue, `JSONEncodable<AttachmentPayload>[]` was the wrong type.
Discord's documentation states that only the `id` is required.[^1][^2] It also states that descriptions are optional, but that is handled already via `files`. Therefore, an array of `Attachment` and `MessageEditAttachmentData` would be the correct type.
No change in code is needed.
[^1]: https://discord.com/developers/docs/resources/channel#edit-message-jsonform-params
[^2]: …
=> types(MessageEditOptions): Correct `attachments` type

packages/core/src/api/sticker.ts
The deprecation message does not contain the link.[^1] Using the class name should fix it.
[^1]: https://discordjs.dev/docs/packages/core/main/StickersAPI:Class#getNitroStickers
=> docs(stickers): Reveal link in the website

packages/discord.js/src/managers/ApplicationCommandPermissionsManager.js, packages/discord.js/src/structures/ApplicationCommand.js, packages/discord.js/src/structures/AttachmentBuilder.js, packages/discord.js/src/structures/ClientPresence.js, packages/discord.js/src/structures/CommandInteraction.js, packages/discord.js/src/structures/Guild.js, packages/discord.js/src/structures/GuildMember.js, packages/discord.js/src/structures/MessagePayload.js, packages/discord.js/src/structures/Role.js, packages/discord.js/src/structures/Sticker.js, packages/discord.js/src/structures/User.js, packages/discord.js/src/util/APITypes.js
I've moved all remaining API type definitions into APITypes.js. There were some deviations:
- `APIAttachment` was unused
- `APIApplicationCommandPermissions` was unused
- `APIEmoji` will move with #9880
- `APIPresence` should be `GatewayPresenceUpdateData`
=> docs: Consolidate API types

packages/core/src/api/applications.ts, packages/discord.js/src/structures/ClientApplication.js, packages/discord.js/src/util/ApplicationFlagsBitField.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/6297
- https://github.com/discordjs/discord-api-types/pull/810
=> feat: Support new application properties and patch endpoint

apps/website/src/components/ExcerptText.tsx
Fixes #9780
Previous:
Corrected [link](https://discord-api-types.dev/api/discord-api-types-v10/enum/ApplicationCommandOptionType#Attachment):
=> fix(website): generate right dapi-types URLs for enum members

packages/proxy/src/handlers/proxyRequests.ts
Resolves an issue with djs/proxy where the `X-Audit-Log-Reason` header was not being forwarded, preventing audit log reasons from appearing for any requests that specified them.
=> fix: forward x-audit-log-reason header

packages/discord.js/src/structures/GuildMember.js
Fixes #9842
Clarifies that GuildMember display color is based on user's role.
=> docs(GuildMember): clarify display color

.github/labels.yml
Fixes errors raised with https://github.com/discordjs/discord.js/actions/runs/6444316257.
`5663e9` would be transformed into `5663000000000` due to it ending in `e9` and `008672` was interpreted as a number rather than a string which is expected by this action.
=> ci(labels): Use strings in values

packages/api-extractor-utils/src/parse.ts
One could not run the build:search_indices script in website because the script requires this file which lacks the .js reference.
=> fix: Add extension

packages/discord.js/src/structures/Message.js
This commit removes the secondary 'of' in the description for the Message structure. This doesn't change anything drastically in terms of the actual code as it's just a JSDoc comment.
N/A
=> docs(Message): remove duplicated word 'of' in description

src/client/actions/Action.js, src/client/websocket/handlers/GUILD_CREATE.js, src/structures/ClientApplication.js, src/structures/ClientPresence.js, src/structures/ClientUser.js, src/structures/MessageAttachment.js, src/structures/Role.js, src/util/AttachmentFlags.js, src/util/Constants.js, src/util/RoleFlags.js, typings/index.d.ts
Backports:
Yeah quite much backported there
- #9743
- #9765 
- #9761
- #9755
- #9713
- #9694
- #9686
- #9692
- #9735
=> chore: Miscellaneous backports

packages/discord.js/src/structures/BaseGuildEmoji.js, packages/discord.js/src/structures/Emoji.js, packages/discord.js/typings/index.d.ts
Supersedes #8493.
This allows both `extension` and `size`. The getter has been deprecated in favour of the method, which is consistent with every other image URL method. `forceStatic` cannot be used as that option relies on a hash which does not exist for emojis.
Requires:
- #9787
=> feat(Emoji): Add `imageURL()`

packages/formatters/src/formatters.ts
The documentation website does not support rendering markdown
=> docs: remove markdown

packages/api-extractor-utils/src/parse.ts, packages/voice/src/audio/TransformerGraph.ts
Lazy calls the functions in the root of `TransformerGraph.ts`, which are called the first time the file is imported(which is through any time **@discordjs/voice** is imported. More importantly, the call to `canEnableFFmpegOptimizations`, [which is a loop that synchronously spawns child processes](https://github.com/amishshah/prism-media/blob/4ef1d6f9f53042c085c1f68627e889003e248d77/src/core/FFmpeg.js#L123C1-L123C1) is now deferred until the first time you actually attempt to play audio. 
This improves bot startup time by 100ms for people importing @discordjs/voice:
Before:
After:
I tested this locally and can confirm audio plays correctly and the call is only called then. 
Resolves #9859  …
=> refactor: Move `getNode`/`canEnableFFmpegOptimizations` into a lazy loaded call

packages/collection/__tests__/collection.test.ts, packages/collection/src/collection.ts
Stage 3 proposal:
- https://github.com/tc39/proposal-set-methods
Overview of the changes:
- `intersect` -> `intersection`
- `difference` -> `symmetricDifference`
- `subtract` -> `difference`
- Added `union`
=> feat: align some methods with the Set Methods proposal

packages/collection/__tests__/collection.test.ts, packages/collection/src/collection.ts
This PR modifies the toJSON method in the collection package to return entries instead of just values. Currently, the toJSON method only returns values from the collection, which makes it impossible to create a new collection from the JSON output.
To fix this issue, this PR modifies the toJSON method to return entries instead of just values. This will preserve the keys and allow the creation of a new collection/map from the returned data. (FIXES #9310 ).
- (Status Classification) This PR includes breaking changes …
=> feat: return entries instead of values in toJSON method

packages/api-extractor/src/generators/ExcerptBuilder.ts
This transforms primitives that are considered keywords to psuedo-referenced types in the api-extractor. This allows for downstream tasks of syntax highlighting and linking for primitives rather than it being merged with surrounding plain text.
Before api-extractor would give the following tokens for `Promise<string>`
```
[
{
text: "Promise"
kind: Reference,
},
{
text: "<string>",
kind: Content
}
]
```
Now it more accurately gives:
```
[
{
text: "Promise"
kind: Reference,
},
{
text: "<",
kind: Content
},
{
text: "string",
kind: Reference
},
{
text: ">",
kind: Content
},
]
```
This should prevent the need for a lot of the edge cases found in #9913
=> fix: treat primitives as references instead of content

packages/discord.js/src/client/BaseClient.js, packages/discord.js/src/sharding/ShardingManager.js, packages/discord.js/src/util/Util.js, packages/discord.js/typings/index.d.ts
Removes `mergeDefault`, which not only mutates, but also has an incomplete implementation that doesn't handle cases some edge cases.
On the other hand, `BaseClient`'s constructor and `ShardingManager`'s constructor not longer mutate the `options` parameter.
=> refactor(utils): remove `mergeDefault`

packages/create-discord-bot/bin/index.ts
Running: `npm create discord-bot@0.2.2` throws commonjs module error caused by importing picocolors
=> fix: import picocolors as default

packages/discord.js/src/structures/Emoji.js
Fixes #9948
Regression from #7772
Previously, the `resolvePartialEmoji()` function returned `id: null` for Unicode emojis, but it was changed in the mentioned pull request. This makes it so the emoji is parsed as `{ animated: false, name: "<unicode>", id: undefined }`
https://github.com/discordjs/discord.js/blob/f0ec70dfdab55e477e7fc2782064c33b87670e68/packages/discord.js/src/util/Util.js#L100
Most of the time, a MESSAGE_REACTION_ADD gateway event is received before the REST call resolves, meaning the emoji will have an `id` set to `null` (in the case of Unicode emojis). However, if the REST call resolves before the gateway event arrives, the `id` property will be set to `undefined`, as that's what it was parsed as …
=> fix(Emoji): `id` set as `undefined` edge case

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts, packages/rest/src/lib/utils/types.ts
There were some places where the `Promise<T> | T` pattern was still used, despite having moved to `Awaitable<T>` in most places. This PR fixes that by using `Awaitable<T>` where applicable.
Furthermore there was an instance of `{ toJSON: () => T }` being used which could be refactored to `JSONEncodable<T>`.
=> types: use wrapper utilities

packages/discord.js/src/managers/GuildMemberManager.js, packages/discord.js/src/structures/ApplicationCommand.js, packages/discord.js/src/structures/GuildMember.js, packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/src/structures/VoiceState.js, packages/discord.js/src/structures/interfaces/Collector.js, packages/discord.js/src/structures/interfaces/TextBasedChannel.js, packages/discord.js/src/util/Sweepers.js
Nullable values in JSDocs should be `?T` rather than `T | null` as that's the preferred convention, this PR updates the remaining instances of the latter into the former.
=> docs: use preferred nullable syntax (`?T` over `T | null`)

packages/api-extractor/src/generators/ApiModelGenerator.ts
`Object<` in docgen should be `Record<` in api-extractor, not `object`.
=> fix: replace Object< with Record<

packages/discord.js/typings/index.d.ts
Change links in mainlib typings from `@deprecated {@link Class#method}` to correct TSDoc syntax `@deprecated {@link Class.method}`.
=> docs: fix links in @deprecated tags

apps/website/src/components/ExcerptText.tsx, apps/website/src/components/ParameterTable.tsx, apps/website/src/components/Property.tsx, apps/website/src/components/SignatureText.tsx, apps/website/src/components/TypeParamTable.tsx, apps/website/src/components/documentation/HierarchyText.tsx, apps/website/src/components/documentation/util.ts, apps/website/src/components/model/enum/EnumMember.tsx, apps/website/src/components/model/method/MethodHeader.tsx, apps/website/src/util/addPackageToModel.ts, apps/website/src/util/fetchMember.ts, packages/api-extractor-model/src/model/ApiPackage.ts, packages/api-extractor-model/src/model/DeserializerContext.ts, packages/api-extractor/src/generators/ApiModelGenerator.ts
drastically reduce api.json file size by shortening all object keys. api-extractor-model will map those to their original form on load of the JSON to not affect anything outside of the JSON file itself.
Also fixes #9967 
Get doc links from canonicalReference in the JSON directly, not the parsed model tree.
=> refactor: minify api.json by shortening keys

apps/website/src/app/api/dynamic-open-graph.png/route.tsx, apps/website/src/util/model.ts, apps/website/src/util/resolvePackageName.ts
Images generated from the discord.js documentation will yield "@discordjs/discord.js" for the package name. The @discordjs suffix has thus been conditionally added.
=> fix(route): Conditionally prefix package names

packages/create-discord-bot/src/create-discord-bot.ts
There was a typo in `create-discord-bot` for `Bun/TypeScript` template which caused it to throw errors at time of install.
=> fix(Bun): Fix typo for Bun template

apps/website/src/app/docs/packages/[package]/[version]/[item]/page.tsx, apps/website/src/app/docs/packages/[package]/[version]/layout.tsx, apps/website/src/util/addPackageToModel.ts, apps/website/src/util/fetchMember.ts, packages/api-extractor-utils/src/parse.ts, packages/discord.js/typings/index.d.ts, packages/scripts/src/generateIndex.ts
- Removed the addPackageToModel function as it now was a one-liner that can be done directly where needed.
- fixed event links from search index
=> refactor(website): remove unneccessary addPackageToModel function

packages/proxy/src/util/responseHelpers.ts, packages/rest/src/lib/handlers/Shared.ts
The `@returns` tag does not require a hyphen, otherwise, this leads to this description starting with a hyphen in the documentation.
=> docs: Remove hyphen after `@returns`

apps/website/src/components/ExcerptText.tsx, apps/website/src/components/documentation/tsdoc/TSDoc.tsx, apps/website/src/components/documentation/util.ts, packages/api-extractor/src/generators/ApiModelGenerator.ts, packages/discord.js/src/client/BaseClient.js, packages/discord.js/src/client/voice/ClientVoiceManager.js, packages/discord.js/src/structures/Guild.js, packages/discord.js/src/util/Sweepers.js
- fixes `@link` tags linking to discord-api-types or URL links directly not showing correctly on new docs site
- some minor doc comment issues in mainlib
supersedes #9988 
fixes #9984 
=> fix(website): discord-api-types links, URL links and some minor doc issues

apps/website/src/components/ExcerptText.tsx, apps/website/src/components/ItemLink.tsx, apps/website/src/components/ParameterTable.tsx, apps/website/src/components/Property.tsx, apps/website/src/components/SignatureText.tsx, apps/website/src/components/TypeParamTable.tsx, apps/website/src/components/documentation/HierarchyText.tsx, apps/website/src/components/documentation/tsdoc/TSDoc.tsx, apps/website/src/components/documentation/util.ts, apps/website/src/components/model/enum/EnumMember.tsx, apps/website/src/components/model/method/MethodHeader.tsx, packages/api-extractor/src/generators/ApiModelGenerator.ts
Assures links to other packages of the monorepo link to the appropriate version used by the currently viewed version.
Also removes inherited methods from the api.json, as they get correctly parsed from inheritance tree and caused issues by being duplicated in the api.json causing wrong type links and missing inheritance information.
=> fix(website): doc links to other packages

packages/api-extractor/src/generators/ApiModelGenerator.ts
Links to other packages still were sometimes wrong, if the property or method was documented in the inheriting class while only being defined in the inherited class. For example `cache` in Managers.
Fixes #9982
=> fix: cross package links again

.github/workflows/documentation.yml
have manual runs of documentation workflow work as expected, emitting .api.json files for the selected tag/branch
=> ci: fix documentation manual dispatch run on tag

packages/discord.js/.eslintrc.json, packages/discord.js/.gitignore, packages/discord.js/package.json, packages/discord.js/scripts/esmDts.mjs, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/rawDataTypes.d.ts
Closes https://github.com/discordjs/discord.js/issues/9985
=> fix: export "ESM" types when discord.js is imported in ESM land

packages/discord.js/src/managers/ThreadMemberManager.js, packages/discord.js/typings/index.d.ts
Adds the ability to pass a resolvable to `ThreadMemberManager#remove`, in keeping with other manager functions.
Note that this deliberately accepts a UserResolvable to pass to `UserManager#resolveId`, rather than a ThreadMemberResolvable to pass to `ThreadMemberManager#resolveId`. There are two reasons for this:
- `UserManager#resolveId` accepts a ThreadMember as an argument anyway;
- If the client lacks the privileged GUILD_MEMBERS intent, then the ThreadMemberManager cache is never populated, so `ThreadMemberManager#resolveId` always returns null. ([ref](https://discord.com/developers/docs/topics/gateway-events#thread-members-update))
The new argument type is a superset of the old one, and so this is suitable for …
=> refactor(ThreadMemberManager): #remove accepts UserResolvable

apps/website/src/components/model/method/MethodDocumentation.tsx, apps/website/src/util/model.ts
Adds the type parameter documentation on methods that have type parameters too.
Also fixes overloads other than the first one not having any documentation.
=> feat(website): type parameters on methods and overloads

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Omits the `getUser` and `getMember` methods from the `CommandOptionResolver` on a `MessageContextMenuCommandInteraction` and similar for `getMessage` on `UserContextMenuCommandInteraction`.
Also omits `getAttachment` on both as it seems to not have been omitted when it got added to the resolver.
Supersedes #9606 
-
=> types: omit unnecessary methods from <ContextMenuCommandInteraction>.options

packages/discord.js/src/client/Client.js, packages/discord.js/src/index.js, packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/src/managers/GuildEmojiManager.js, packages/discord.js/src/managers/GuildInviteManager.js, packages/discord.js/src/managers/GuildManager.js, packages/discord.js/src/managers/GuildScheduledEventManager.js, packages/discord.js/src/managers/RoleManager.js, packages/discord.js/src/structures/ClientApplication.js, packages/discord.js/src/structures/ClientUser.js, packages/discord.js/src/structures/Guild.js, packages/discord.js/src/structures/GuildTemplate.js, packages/discord.js/src/structures/MessagePayload.js, packages/discord.js/src/structures/Webhook.js, packages/discord.js/src/util/Channels.js, packages/discord.js/src/util/DataResolver.js, packages/discord.js/src/util/Util.js, packages/discord.js/test/resolveGuildTemplateCode.test.js, packages/discord.js/typings/index.d.ts
Marking types as `@internal` where appropriate. Also decided to make `DataResolver` a file of functions instead of a class that had only static symbols.
=> refactor: Document relevant types as `@internal`

packages/discord.js/typings/index.d.ts
Not all overloads of this method were documented as `@internal`.
=> docs(resolvePartialEmoji): Add `@internal` to all overloads

packages/ws/src/ws/WebSocketShard.ts
Bun fixed the WebSocket issue (https://github.com/oven-sh/bun/issues/3392). WS now reports correct close codes and everything! Now, fingers crossed their WebSocket client doesn't have some hidden bugs 🤞 
=> feat: use globally available WebSocket client in runtimes that have it

.github/workflows/documentation.yml
On manual runs of documentation.yml workflow additionally checks out main branch if targeting another tag/branch. Before uploading runs api-extractor from main branch on the packages in target branch.
=> ci: always generate docs with latest main ae

packages/brokers/package.json, packages/core/package.json, packages/core/src/client.ts, packages/rest/package.json, packages/rest/src/lib/REST.ts, packages/rest/src/lib/utils/types.ts, packages/ws/__tests__/types/WebSocketManager.test-d.ts, packages/ws/package.json, packages/ws/src/ws/WebSocketManager.ts, packages/ws/src/ws/WebSocketShard.ts, pnpm-lock.yaml
Turn the mapped types for events in `rest/REST`, `ws/WebSocketManager,` `ws/WebSocketShard` and `core/Client` into interfaces for better documentation purposes.
Also turns `WebSocketManagerOptions` into an interface for the same reason.
Some interfaces are simple aliases of already existing interfaces, to keep the named export and make this possible as a non-breaking change even in TS land.
`@discordjs/brokers` still uses types for event maps, but they are dynamic so not as easily adjustable.
=> refactor: use interfaces for AsyncEventEmitter event maps

packages/formatters/__tests__/formatters.test.ts, packages/formatters/src/formatters.ts
This addresses the issue where the formatter is named `underscore` and its escaper is named `escapeUnderline` as pointed out in [Discord server](https://discord.com/channels/222078108977594368/937420598383108167/1185666172792868914). I went with underline because that's what Discord refers it as in [Markdown Text 101](https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-).
=> fix: deprecate `underscore` in favor of `underline`

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Directory channels when stringified cannot possibly be a user mention (which is typed through the inheritance chain):
https://github.com/discordjs/discord.js/blob/1f5d71e087f3e86f092634f798c33bd63029977f/packages/discord.js/typings/index.d.ts#L2901
https://github.com/discordjs/discord.js/blob/1f5d71e087f3e86f092634f798c33bd63029977f/packages/discord.js/typings/index.d.ts#L938-L955
Also added tests for the remaining channels.
=> types(DirectoryChannel): Ensure directory channels cannot contain user mentions when stringified

packages/core/src/Gateway.ts, packages/core/src/index.ts
This interface should be exported.
=> fix(Gateway): Export interface

packages/discord.js/src/structures/Emoji.js, packages/formatters/__tests__/formatters.test.ts, packages/formatters/src/formatters.ts
- Supersedes #10072 
- Resolves #10067 
- Add support for passing name parameter in `formatEmoji()`
- Add support for passing objects instead of `emojiId`, `animated` parameters 
=> refactor(formatters): Add support for object and name param in `formatEmoji()`

packages/ws/README.md
utf-8-validate is only for legacy versions of Node.js, so having it in the readme like this is a footgun and will cause the ecosystem to install useless dependencies.
=> docs: remove utf-8-validate

apps/website/src/components/CmdK.tsx
`cmdk` package builds the list based on `value`, which gets inferred from the content if not explicitly set. This caused the render to majorly lag for things with long descriptions because it was using a recursive function to build information for the value from `command-score` on that long string.
=> fix(website): search hanging on complex types

packages/discord.js/src/structures/BaseInteraction.js
The return type should be `APIInteractionGuildMember` instead of `APIGuildMember`, the typings are correct, just the documentation seems to be incorrect here.
=> docs(BaseInteraction): correct return type of `member`

packages/discord.js/src/util/Sweepers.js
Fixes #10069. It would seem that certain properties do not get set properly if the guild is not available, so when we go to sweep them, the property is undefined (.stickers, .emojis etc). Skipping unavailable guilds on a sweep pass should resolve the issue.
Patch
=> Skip sweeping if the guild is not available

packages/discord.js/typings/index.d.ts
The return type currently shows like this in the new documentation site:
Converted the comment into `@privateRemarks` to work around it
=> docs: convert comment into private remark

packages/discord.js/src/errors/Messages.js, packages/discord.js/src/util/Util.js
Improves the error by specifying what was unable to be converted. This may resolve in quicker debugging. Also resolves a possible mutation in `resolveColor()`.
=> refactor(Messages): Improve `ColorConvert` error

packages/rest/__tests__/RequestManager.test.ts, packages/rest/src/lib/REST.ts, packages/rest/src/lib/handlers/BurstHandler.ts, packages/rest/src/lib/handlers/SequentialHandler.ts, packages/rest/src/lib/utils/types.ts, packages/rest/src/lib/utils/utils.ts
=> feat(REST): dynamic rate limit offsets

packages/discord.js/src/client/BaseClient.js
We're currently getting an `undefined` string in our user agent strings (if an appendix is not specified):
```
Request {
headersTimeout: undefined,
bodyTimeout: undefined,
throwOnError: false,
method: 'GET',
abort: null,
body: null,
completed: false,
aborted: false,
upgrade: null,
path: '/api/v10/gateway/bot',
origin: 'https://discord.com',
idempotent: true,
blocking: false,
reset: null,
host: null,
contentLength: null,
contentType: null,
headers: 'User-Agent: DiscordBot (https://discord.js.org, 2.2.0) undefined\r\n' +
'Authorization: Bot [REDACTED]\r\n',
expectContinue: false,
servername: null,
[Symbol(handler)]: RequestHandler {
responseHeaders: null,
opaque: null,
callback: [Function (anonymous)],
res: null, …
```
=> fix(BaseClient): Fall back to `userAgentAppendix`

packages/discord.js/src/util/Util.js
It's more logical to check for a number first before doing `resolvedColor < 0 || resolvedColor > 0xffffff`.
=> refactor(resolveColor): Prioritise number type check

apps/website/src/components/CmdK.tsx
Resolves duplicate results in cmdk dialog from being highlighted/selected on hover or with arrow navigation.
=> fix(website): cmdk duplicate values

packages/discord.js/src/structures/Message.js, packages/discord.js/src/util/Constants.js, packages/discord.js/typings/index.d.ts
Discord has inverted their deletable message types list to be an undeletable message types list instead:
- https://github.com/discord/discord-api-docs/issues/6551#issuecomment-1894758069
Replicated this on our side and deprecated the previous `DeletableMessageTypes` array.
=> fix: invert deletable message types list

.husky/commit-msg, .husky/pre-commit, package.json, pnpm-lock.yaml
- This PR includes non-code changes, mostly affects improved DX.
=> build: Update husky to v9

packages/scripts/src/generateIndex.ts
Resolves LinkTagNodes in meta description. Fixes djs links, dapi links, and uses linkText when applicable.
[GuildChannel](https://discordjs.dev/docs/packages/discord.js/main/GuildChannel:Class)
[MentionableSelectMenuInteraction](https://discordjs.dev/docs/packages/discord.js/main/MentionableSelectMenuInteraction:Class)
[version](https://discordjs.dev/docs/packages/builders/main/version:Variable)
=> fix(website): resolve linkTags in meta description

apps/website/src/components/documentation/section/UnionMembersSection.tsx, apps/website/src/components/documentation/tsdoc/TSDoc.tsx, apps/website/src/components/model/TypeAlias.tsx, packages/api-extractor/src/generators/ApiModelGenerator.ts
Previously only (most) Union types had links to their members. This now adds linked Excerpts for all `TypeAlias`es.
Also fixes an issue with markdown lists in JSDoc not being shown in the generated TSDoc in `api-extractor`.
=> fix(website): always link in TypeAlias

packages/api-extractor/src/generators/ApiModelGenerator.ts
- Fixes #10080
- Removes `undefined` in Excerpts of inherited properties that have no access modifier set in docgen JSON
=> fix(api-extractor): link to enum types on inherited properties

apps/website/src/components/model/function/Function.tsx
This moves top level function headers into the overload switcher in order to sync the exerpt text to the overload.
=> fix(website): move function header into switcher

.github/CONTRIBUTING.md
Previously with yarn you needed to link the entire workspace and then manually install each local package to test. With pnpm all we need to do is just run `link` against the individual packages we want to test.
=> fix: Correct testing local changes in `CONTRIBUTING.md`

packages/discord.js/src/util/Util.js
Resolves #10114: the logic for handling a number was removed in #10108 due to no longer overwriting the parameter.
=> fix(resolveColor): Address case for numbers

packages/api-extractor/src/generators/ApiModelGenerator.ts, packages/api-extractor/src/generators/ExcerptBuilder.ts
=> fix(docs): use ts types for inherited properties instead of jsdoc

packages/api-extractor/src/generators/ExcerptBuilder.ts
Types with nested type parameters still had unneccessary spaces like `Type<Type<Type | Type> >`
=> fix(docs): remove spaces in type parameter brackets

packages/discord.js/typings/index.d.ts
Removed the internal mixin function `DiscordjsErrorMixin` in order to provide better documentation
<https://discord.js.org/docs/packages/discord.js/14.14.1/DiscordjsError:Class>
=> refactor: remove usage of mixin on error classes

packages/discord.js/src/managers/ApplicationCommandPermissionsManager.js
=> docs(ApplicationCommandPermissionsManager): remove incorrect comment

packages/discord.js/src/errors/ErrorCodes.js, packages/discord.js/src/errors/Messages.js, packages/discord.js/src/structures/MessagePayload.js, packages/discord.js/src/structures/interfaces/TextBasedChannel.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/6647
=> feat(MessageCreateOptions): add `enforceNonce`

packages/core/src/api/oauth2.ts
This change removes an unnecessary dependency on 'node:url', which fixes a runtime error when using '@discordjs/core/http-only' on Cloudflare Workers.
Related links:
- https://github.com/discordjs/discord.js/discussions/8428#discussioncomment-6955659
- https://developers.cloudflare.com/workers/runtime-apis/nodejs/
- **Code changes have been tested against the Discord API**, ~or there are no code changes~
- ~I know how to update typings and have done so, or~ **typings don't need updating**
=> refactor(oauth2): remove unnecessary dependency on 'node:url'

packages/discord.js/.eslintrc.json, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Added an ESLint rule to enforce the use of readonly Array and Collection types in function/method parameters and interface properties
=> types: use readonly array / collection types for user input

packages/discord.js/src/structures/ActionRow.js
Updated the deprecated message for clarity; now suggests "ActionRowBuilder#from" instead of just "from."
=> docs(ActionRow): fix deprecated message

packages/collection/src/collection.ts
Omit the `clear()` method on `ReadonlyCollection`s as it mutates the original array.
=> fix(ReadonlyCollection): omit `clear` method

packages/discord.js/typings/index.d.ts
These two classes had (explicit) accessibility modifiers added to their constructors.
=> types: Update accessibility modifiers on constructors

packages/formatters/__tests__/formatters.test.ts, packages/formatters/src/formatters.ts
On stable, the value of `Shrug` is `¯_(ツ)_/¯`, which is incorrect. This PR fixes the error by escaping the backslash.
=> fix(Faces): Escape backslash in `Shrug`

.github/workflows/publish-dev.yml, .github/workflows/publish-release.yml, packages/api-extractor-utils/package.json, packages/brokers/package.json, packages/builders/package.json, packages/collection/package.json, packages/core/package.json, packages/create-discord-bot/package.json, packages/discord.js/package.json, packages/docgen/package.json, packages/formatters/package.json, packages/next/package.json, packages/proxy-container/package.json, packages/proxy/package.json, packages/rest/package.json, packages/scripts/turbo/generators/templates/package.json.hbs, packages/ui/package.json, packages/util/package.json, packages/voice/package.json, packages/ws/package.json
See https://github.blog/2023-04-19-introducing-npm-package-provenance/ and https://docs.npmjs.com/generating-provenance-statements
pnpm has supported the `--provenance` option since [8.4.0](https://github.com/pnpm/pnpm/releases/tag/v8.4.0)
Also enabled it in every (public) package.json to error out if someone tries to publish it in an environment where provenance is not supported (i.e. their own computer)
=> ci: enable npm provenance

packages/builders/__tests__/interactions/SlashCommands/SlashCommands.test.ts, packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionChannelTypesMixin.ts, packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionWithChoicesMixin.ts
This PR changes ApplicationCommandOption methods to allow both rest and array params, which previously wasn't consistent with other builders. This was done by widening the parameter from `...T[]` to `RestOrArray<T>` and normalizing it inside the method. Since arrays are still allowed, this is not a breaking change. The test file has been modified to test both rest and array parameters.
=> feat: allow RestOrArray for command option builders

packages/discord.js/package.json, packages/discord.js/tsconfig.json, packages/discord.js/typings/index.d.ts, pnpm-lock.yaml
Remove the `ws` dependency of `discord.js`main library which is not used anymore since incorporating `@discordjs/ws` into main library.
=> chore: remove ws dependency

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Introduce a type parameter `Webhook<Type extends WebhookType>` that determines the type of Webhook to correclty narrow its properties. The typeguard methods of `Webhook` now use this type parameter. 
Resolves #9182
=> types: generic for Webhook type

packages/builders/package.json, packages/core/package.json, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, pnpm-lock.yaml
=> build: bump discord-api-types to 0.37.78

packages/discord.js/src/structures/BaseInteraction.js
Removes the unused typedef, as requested in the reviews
=> docs: remove unused `Locale` typedef

packages/core/src/api/guild.ts
Added a `bulkBanUsers()` method to the guilds api in /core.
Upstream:
- https://github.com/discord/discord-api-docs/pull/6720
=> feat(GuildsAPI): bulk ban users

packages/discord.js/src/structures/ClientUser.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/6710
=> feat(ClientUser): Add support for setting bot banner

.github/workflows/documentation.yml
Fixes documentation.yml CI to run the correct generateSplitDocumentation**.js** when run against a tag or branch.
=> ci: fix call to generateSplitDocumentation if run on tag

apps/website/src/components/DocNode.tsx, apps/website/src/components/ExcerptNode.tsx, apps/website/src/util/fetchNode.ts, apps/website/src/util/fetchSitemap.ts
Links to types in other subpackages use the correct version of that subpackage now, instead of the version of the current package.
Fixes for example https://discord.js.org/docs/packages/discord.js/14.14.1/Client:Class#rest
Also fixed two small issues for local testing of the docs website
=> fix(website): use correct version for cross-package links

apps/website/src/components/ui/CmdK.tsx, packages/actions/src/uploadSearchIndices/index.ts, packages/scripts/src/generateIndex.ts
Adds a `type` property to the meilisearch documents, which then is used in CmdK search to sort the results in the following order:
- Class,
- Interface,
- TypeAlias,
- Function,
- Enum,
- Variable,
- Event,
- Method,
- Property,
- MethodSignature,
- PropertySignature,
- EnumMember,
The following `ApiItemKind` are added at the end of the enum used for sorting, although they should never appear in the index:
Package, Namespace, IndexSignature, CallSignature, Constructor, ConstructSignature, EntryPoint, Model, None
=> feat(website): add type field to search index to sort by

packages/api-extractor/src/analyzer/ExportAnalyzer.ts, packages/builders/package.json, pnpm-lock.yaml
api-extractor now supports `export * as ___` syntax, making the `downlevel-dts` in `@discordjs/builders` doc toolchain obsolete.
This also fixes `Omit<...>` getting downleveled to `Pick<...,Exclude<keyof ..., ...>>` in docs.
=> feat(api-extractor): support `export * as ___` syntax

packages/api-extractor/src/generators/ApiModelGenerator.ts
Fixes parameter types linking to the the class instead of the (merged) interface for cases where interface merging happened. (e.g. GuildMember, User, DMChannel, TextChannel, Webhook, ...)
=> fix(api-extractor): link class in docs if interface merging happened

.github/workflows/tests.yml
This PR makes tests check run first than linter, because tests check is faster and fails quite often
=> ci: optimize tests

packages/api-extractor-model/src/model/ModelReferenceResolver.ts
=> fix(api-extractor-model): resolve doc reference for classes with merged interfaces

packages/rest/__tests__/RequestHandler.test.ts
A bump in undici's version has broken this particular test (since 6759f5b9c523da33beb982232b97872ff1ce82f4)
=> test: skip flaky rest test

package.json, packages/builders/package.json, packages/core/package.json, packages/core/src/client.ts, packages/discord.js/package.json, packages/formatters/package.json, packages/next/package.json, packages/rest/package.json, packages/voice/package.json, packages/ws/package.json, pnpm-lock.yaml
Bumped discord-api-types to the latest version in order to unblock:
- #10185
=> build: bump discord-api-types to 0.37.82

apps/guide/package.json, apps/website/package.json, package.json, packages/actions/package.json, packages/api-extractor-model/package.json, packages/api-extractor-utils/package.json, packages/api-extractor/package.json, packages/brokers/package.json, packages/builders/package.json, packages/collection/package.json, packages/core/package.json, packages/create-discord-bot/package.json, packages/discord.js/package.json, packages/docgen/package.json, packages/formatters/package.json, packages/next/package.json, packages/proxy-container/package.json, packages/proxy/package.json, packages/rest/package.json, packages/scripts/package.json, packages/scripts/turbo/generators/templates/package.json.hbs, packages/ui/package.json, packages/util/package.json, packages/voice/package.json, packages/ws/package.json
This PR adds funding to apper in npm pages
=> chore: Add funding field to package.json

packages/discord.js/src/managers/MessageManager.js, packages/discord.js/src/structures/Poll.js, packages/discord.js/src/structures/PollAnswer.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Add `endPoll` and `fetchPollAnswerVoters`  methods to the `MessageManager` class to allow interacting with polls without them being cached.
=> feat(MessageManager): poll methods

packages/discord.js/src/structures/Message.js
Messages are not crosspostable if they have a poll.
=> fix(Message): not crosspostable if has a poll

packages/discord.js/src/managers/MessageManager.js, packages/discord.js/src/structures/Poll.js, packages/discord.js/src/structures/PollAnswer.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
average discord.js release (blundered)
=> fix(MessageManager): poll methods don't need a channel id

packages/discord.js/src/structures/PollAnswer.js
Poll.fetchVoters() function was throwing error cause it used the Channel Internally, so i changed to use the MessageManager Instead.
=> fix(PollAnswer): fetchVoters route changed to MessageManager

packages/builders/__tests__/interactions/SlashCommands/SlashCommands.test.ts, packages/builders/src/components/textInput/TextInput.ts, packages/builders/src/index.ts, packages/builders/src/interactions/slashCommands/SlashCommandBuilder.ts, packages/builders/src/interactions/slashCommands/mixins/SharedSlashCommand.ts, packages/builders/src/interactions/slashCommands/mixins/SharedSubcommands.ts
`SlashCommandBuilder#setDefaultMemberPermissions()` and other methods were wrongly omitted when adding options. Also fixed an issue where `toJSON()` returned the wrong type and fixed docs for `TextInputBuilder#equals()`
=> fix: slashcommand builder type split

packages/scripts/src/generateIndex.ts
Inherited members now show up in generated search indices for docs. 
=> fix: add inherited properties to search index

apps/website/src/components/DocNode.tsx, packages/scripts/src/generateSplitDocumentation.ts
Links like the one to `Array` builtin to JS in summary of `BitField#toArray()` didn't resolve correctly.
=> fix(website): links to builtin documentation not showing in summary

packages/discord.js/src/client/actions/MessagePollVoteAdd.js, packages/discord.js/src/client/actions/MessagePollVoteRemove.js
`poll` will be missing if `GUILD_MESSAGE_POLLS` is enabled but `MESSAGE_CONTENT` is not, or if a message containing a poll was uncached but the appropriate partials were enabled. This caused a crash:
```
/Users/jiralite/Documents/code/GitHub/discordjs/discord.js/packages/discord.js/src/client/actions/MessagePollVoteRemove.js:16
const answer = poll.answers.get(data.answer_id);
^
TypeError: Cannot read properties of null (reading 'answers')
at MessagePollVoteRemoveAction.handle (/Users/jiralite/Documents/code/GitHub/discordjs/discord.js/packages/discord.js/src/client/actions/MessagePollVoteRemove.js:16:25)
at module.exports [as MESSAGE_POLL_VOTE_REMOVE] (/Users/jiralite/Documents/code/GitHub/discordjs/discord.js/packa …
```
=> fix(actions): Handle missing poll object

packages/ws/README.md, packages/ws/src/utils/constants.ts, packages/ws/src/ws/WebSocketManager.ts, packages/ws/src/ws/WebSocketShard.ts
#9279 again, but supports both
=> refactor: native zlib support

packages/brokers/README.md, packages/brokers/__tests__/index.test.ts, packages/brokers/src/brokers/Broker.ts, packages/brokers/src/brokers/redis/BaseRedis.ts, packages/brokers/src/brokers/redis/PubSubRedis.ts, packages/brokers/src/brokers/redis/RPCRedis.ts
BREAKING CHANGE: Classes now take redis client as standalone parameter, various props from the base option interface moved to redis options
=> refactor(brokers): make option props more correct

apps/website/src/components/DocNode.tsx, packages/api-extractor-model/src/model/ModelReferenceResolver.ts, packages/discord.js/src/managers/GuildManager.js, packages/discord.js/src/managers/GuildTextThreadManager.js, packages/discord.js/src/managers/ThreadManager.js, packages/discord.js/src/sharding/ShardingManager.js, packages/discord.js/src/structures/Guild.js, packages/discord.js/src/structures/GuildScheduledEvent.js, packages/discord.js/src/structures/PermissionOverwrites.js, packages/discord.js/src/structures/ReactionCollector.js, packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/src/util/Constants.js, packages/discord.js/typings/index.d.ts
Fixes docs to resolve and show (hopefully) all link tags correctly now.
=> fix(docs): some link tags didn't resolve correctly

packages/discord.js/typings/index.d.ts
Added 'defaultValues' typings on ChannelSelectMenuComponentData, RoleSelectMenuComponentData, and UserSelectMenuComponentData.
=> types: Add `defaultValues` to respective select menu components data

packages/builders/__tests__/interactions/SlashCommands/SlashCommands.test.ts, packages/builders/__tests__/types.test.ts, packages/builders/src/interactions/slashCommands/mixins/SharedSlashCommand.ts, vitest.config.ts
Following #10253, other properties were observed to also not be present when using options or subcommands. This PR adds those properties on the type level where they are present during runtime.
=> fix(SlashCommandBuilder): add missing shared properties

packages/discord.js/typings/index.d.ts
Bring the types in line with what is [documented
Manually confirmed that forum starter messages do not support polls as well.
=> types: Forum starter messages do not support polls

packages/discord.js/src/client/actions/Action.js
User-installable applications are in the wild, and this is one problem I have noticed so far, despite not being exactly relevant.
When a command is invoked in a **group** direct message channel and the channel partial is enabled, discord.js will proceed to create a channel (as direct message channels not initially cached). This is an example payload:
```JavaScript
{
type: 3,
owner_id: 'user_id',
name: '💛💜🖤',
last_pin_timestamp: '2023-06-26T16:59:39+00:00',
last_message_id: 'message_id',
id: 'id',
icon: null,
flags: 0
}
```
Notice `type` is `3`. discord.js results in this channel:
```JavaScript
DMChannel {
type: 1,
flags: ChannelFlagsBitField { bitfield: 0 },
id: 'id',
recipientId: undefined,
lastMessageId: …
```
=> fix(Action): Ensure all properties on `getChannel()` are passed

packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/typings/index.d.ts
This appears to be the last incidence of a naked `Error` being thrown within the d.js library. Changed to throw `DiscordjsTypeError` on failed resolution, along with individualising the parameter checks for easier debugging.
Adds a `NewsChannelResolvable` type for semantic purposes. This is a non-breaking type change.
=> refactor(GuildChannelManager): improve addFollower errors

packages/builders/src/components/Components.ts
Fixes a typo in the docs for text input components.
=> docs(MappedComponentTypes): fix "inpiut" typo

packages/brokers/src/brokers/Broker.ts, packages/brokers/src/brokers/redis/BaseRedis.ts, packages/brokers/src/brokers/redis/RPCRedis.ts, packages/discord.js/src/structures/Message.js
~~A small fix~~ A complete refactor to address the issue described in https://github.com/discordjs/discord.js/issues/10273 where the broker keeps pooling even when there's no subscribed events causing a `Redis` `ReplyError`.
This PR fixes this by stop pooling when there's no subscriptions and adds a cleanup to the event emitter listeners on the destroy as discussed in https://github.com/discordjs/discord.js/issues/10273 
- …
=> refactor(brokers): re-design API to make groups a constructor option

packages/builders/src/components/textInput/TextInput.ts
Fixes incorrect references to select menu options in text input docs.
=> docs(TextInputBuilder): correct constructor documentation

packages/core/src/api/oauth2.ts
**Please describe the changes this PR makes and why it should be merged:** Currently, requests made by the [OAuth2API](https://discord.js.org/docs/packages/core/main/OAuth2API:Class) class require the `Authorization` header by default. If no token is set on the underlying REST client, this produces an error:
```
Error: Expected token to be set for this request, but none was present
```
However, for requests such as exchanging an authorization code for a token or refreshing using a refresh token, an existing token isn't required by the Discord API and doesn't really make sense; if the client already has a valid token, there's no need to exchange a code for a new token. (See [here](https://stackblitz.com/edit/node-vaut2g?file=index.js) for a simple StackBlitz reproduction.) This PR disables …
=> fix(OAuth2API): enable token exchange without token

packages/ws/README.md, packages/ws/src/utils/constants.ts, packages/ws/src/ws/WebSocketManager.ts, packages/ws/src/ws/WebSocketShard.ts
This reverts commit 20258f94bf1a62ec1989ef04d839e2800f6e6d28.
This is to ensure discord.js gets #10271 through a non-breaking version.
=> revert: refactor: native zlib support

packages/actions/src/uploadCoverage/action.yml
#10270 updated the codecov action version which uses the cli now. the cli searches for files by default and still does even with the file option???? This should disable that so that the coverage reports properly again (hoping we don't have to delete all the coverage data for this to report properly)
=> ci: fix coverage upload

packages/rest/__tests__/CDN.test.ts, packages/rest/src/lib/CDN.ts, packages/rest/src/lib/REST.ts, packages/rest/src/lib/utils/constants.ts, packages/rest/src/lib/utils/types.ts
GIF stickers must be accessed via the media proxy.[^1]
[^1]: https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints
=> fix: Correct base path for GIF stickers

.github/workflows/pr-triage.yml
Splits the job up as it semantically makes sense.
Also looks better when observing the workflows:
=> ci(pr-triage): Split job up

packages/scripts/src/generateSplitDocumentation.ts
Removes interface links from the sitemap for classes with merged interfaces.
Also fixes the links for properties of variables in discord-api-types (namely FormattingPatterns.Role etc.).
=> fix(website): remove merged interface from sitemap

packages/api-extractor-model/src/model/ModelReferenceResolver.ts
Fixes missing links for cases where we link to an event of a class that has a method of the same name. Realistically only happening for Collectors.
=> fix(website): link tags to events named same as methods

.commitlintrc.json, .github/COMMIT_CONVENTION.md, .github/workflows/pr-triage.yml
- "types" is the preferred scope to use over "typings". This has been kept in cliff.toml files (for changelogs) as some prior commits used this scope
- "ci" is the preferred scope over "workflow"
- "wip" was not allowed in the first place
=> chore: Remove "typings", "wip", and "workflow" scope

packages/ws/src/utils/constants.ts, packages/ws/src/ws/WebSocketShard.ts
This makes it so we try reconnecting for this error code.
=> feat(WebSocketShard): explicit time out network error handling

packages/builders/__tests__/components/button.test.ts, packages/builders/src/components/Assertions.ts, packages/builders/src/components/button/Button.ts, packages/core/src/api/interactions.ts, packages/discord.js/src/structures/interfaces/InteractionResponses.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts, packages/formatters/__tests__/formatters.test.ts, packages/formatters/src/formatters.ts
- https://github.com/discord/discord-api-docs/pull/6875
- https://github.com/discordjs/discord-api-types/pull/1010
=> feat: Premium buttons

packages/discord.js/src/managers/GuildChannelManager.js
Removes redundant code, such as this:
```diff
- (options.name ?? channel.name).trim(),
+ options.name,
```
In this example, `.trim()` is redundant as the API performs trimming. The `??` is also redundant (here and later in the code) as the properties are optional. Methods like these work just fine still:
```TypeScript
await channel.setRTCRegion(null);
// " hello " is trimmed API-side.
await channel.edit({ name: " hello ", bitrate: 96000, userLimit: 13, rtcRegion: null });
```
Also avoided reassigning the parameter.
- I know how to update typings and have done so, or typings don't need …
=> refactor(GuildChannelManager): Remove redundant edit code

packages/ws/src/utils/constants.ts
=> fix: retry for EAI_AGAIN I/O error

packages/scripts/src/generateSplitDocumentation.ts
Fixes the links to enum members from excerpt texts like `HeadingLevel.One` on https://discord.js.org/docs/packages/formatters/main/heading:Function and similar.
=> fix(website): links to enum members from excerpts

packages/builders/__tests__/interactions/SlashCommands/SlashCommands.test.ts, packages/builders/src/interactions/slashCommands/mixins/SharedSlashCommand.ts
This PR makes the `SlashCommandBuilder` explicitly specify its type (`ApplicationCommandType.ChatInput`) when building, by modifying the `SharedSlashCommand` mixin.
One useful scenario for this is when mapping data received from the API (which always contains the type) to a builder's generated data (which currently doesn't contain the type for chat inputs), without relying on a fallback or assuming Discord's default.
I also asked about the issue on the developing-djs channel and a maintainer suggested I should open a PR for it.
- I know how to update typings and have done so, or typings …
=> feat(SlashCommandBuilder): Add explicit command type when building

packages/formatters/__tests__/formatters.test.ts, packages/formatters/src/formatters.ts
Adds a formatter for the new subtext markdown feature which can be found [here](https://support.discord.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline) under "Organizational Text Formatting"
=> feat: add subtext formatter

packages/core/src/client.ts, packages/ws/__tests__/strategy/WorkerShardingStrategy.test.ts, packages/ws/src/strategies/sharding/SimpleShardingStrategy.ts, packages/ws/src/strategies/sharding/WorkerShardingStrategy.ts, packages/ws/src/utils/WorkerBootstrapper.ts, packages/ws/src/ws/WebSocketManager.ts, packages/ws/src/ws/WebSocketShard.ts
Breaking the whole library.
`discord.js` needs updating, but it's currently pinned to an older version so that'll have to be a TODO for someone else.
=> refactor(ws): event layout

packages/collection/__tests__/collection.test.ts, packages/collection/src/collection.ts
Small changes relating to the typed method definitions for `reduce()` and `reduceRight()`:
- Fix the "without-initial-value" signature of `reduceRight()`.
- When `initialValue` was not provided, this method would previously accept a callback with any arbitrary type for `previousValue`, or infer the type as `unknown` without explicit type annotation:
```ts
declare const coll: Collection<string, number>;
coll.reduceRight((a, x) => a + x); // error: 'a' is of type 'unknown'
coll.reduceRight((a: string, x) => a.repeat(x)); // compiles OK, but will raise a TypeError at runtime
```
- With this change, if an initial value for the accumulator is not provided, the callback's `previousValue` type is always the collection …
=> types(collection): reduce* method signatures

packages/ws/src/strategies/context/IContextFetchingStrategy.ts, packages/ws/src/utils/constants.ts, packages/ws/src/ws/WebSocketManager.ts
=> feat(WebsocketManager): retroactive token setting

.github/workflows/documentation.yml
Fixes sourcecode links for tagged versions of subpackages like `@discordjs/builders@1.8.2` using full tag name instead of just the semver part.
=> ci: fix docs source url on tag push

packages/scripts/src/generateIndex.ts
Previously the search index for e.g. `GuildMember#guild` had just `guild` as name for the entry and only the path it links to and maybe the description told you what class it belongs to.
With this small change the name now includes the Classname too and also distinguishes methods from properties. I.e. `fetch` is now `GuildMember.fetch()`.
=> refactor(website): search index name of members includes class now

packages/scripts/src/generateIndex.ts
With #10415 the name on search index includes the name of the class now, but for inherited properties it's the name of the defining class instead of the one the entry links to.
This PR fixes this and also changes the delimiter so the name for https://discord.js.org/docs/packages/discord.js/14.15.3/ClientUser:Class#bot would be `ClientUser#bot` instead of `User.bot`now.
=> fix(scripts): show name of inheriting class on search index

packages/discord.js/src/client/Client.js, packages/discord.js/src/util/Options.js, packages/discord.js/typings/index.d.ts
This reverts commit 8f97d2bacf78544e60935405316024a6bc4a4a50.
After internal discussion, we decided to revert this change. See https://github.com/discordjs/discord.js/pull/10426#discussion_r1703174908 for more info
=> revert: chore: deprecate client options presence

.commitlintrc.json, .github/COMMIT_CONVENTION.md, .github/workflows/pr-triage.yml
With most commits being done via PR, it's sometimes hard to properly mark commits as breaking, this allows us to do so via the PR title
=> chore: allow `!` to indicate breaking changes

packages/discord.js/package.json, pnpm-lock.yaml
There have been breaking changes in /ws which discord.js doesn't support, so pinning the version to not break potential future v14 releases
=> chore: pin /ws version in discord.js

packages/ws/src/utils/constants.ts, packages/ws/src/ws/WebSocketManager.ts, packages/ws/src/ws/WebSocketShard.ts
Fixes #10397
Internal ref: https://discord.com/channels/222078108977594368/999796393810067607/1271166923500945419
=> refactor(WebSocketShard): error event handling

packages/ws/src/ws/WebSocketShard.ts
=> fix(WebSocketShard): buffer native zlib decompression payload

packages/api-extractor/src/generators/ApiModelGenerator.ts, packages/scripts/src/generateSplitDocumentation.ts
Fixes an issue where `User#send()` shows twice on documentation website, one of them with invalid links and missing JSDoc.
See https://discord.js.org/docs/packages/discord.js/main/User:Class#send
=> fix(website): duplicate method in docs when interface merging

packages/discord.js/typings/index.d.ts
Resolves #10390. The correct key is `"AutoModeration"` as defined in JavaScript:
https://github.com/discordjs/discord.js/blob/efa16a6095e012ff4d138b21d128df5f407fc93c/packages/discord.js/src/structures/GuildAuditLogsEntry.js#L391
https://github.com/discordjs/discord.js/blob/efa16a6095e012ff4d138b21d128df5f407fc93c/packages/discord.js/src/structures/GuildAuditLogsEntry.js#L32
=> types: Fix wrong auto moderation target type

packages/builders/package.json, packages/builders/src/components/Assertions.ts, packages/builders/src/components/textInput/Assertions.ts, packages/builders/src/interactions/contextMenuCommands/Assertions.ts, packages/builders/src/interactions/modals/Assertions.ts, packages/builders/src/interactions/slashCommands/Assertions.ts, packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionChannelTypesMixin.ts, packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionWithAutocompleteMixin.ts, packages/builders/src/interactions/slashCommands/mixins/ApplicationCommandOptionWithChoicesMixin.ts, packages/builders/src/interactions/slashCommands/options/integer.ts, packages/builders/src/interactions/slashCommands/options/number.ts, packages/builders/src/interactions/slashCommands/options/string.ts, packages/builders/src/messages/embed/Assertions.ts, pnpm-lock.yaml
This updates the Shapeshift dependency and related code to @sapphire/shapeshift v4. This does not yet add custom messages to all the functions, which needs further discussion on what to set where. In a way this PR can also be a jumping-off point for @Qjuh. This PR also has a relation to #10117. 
While this concerns a new major version of Shapeshift, there are no user-facing breaking changes to @discordjs/builders in this version that would incur the need for a new major version of @discordjs/builders.
=> feat(builders): update to @sapphire/shapeshift v4

packages/core/src/api/oauth2.ts
This change completes the OAuth2 Authorization flow by supporting the [`Token Revocation URL`](https://discord.com/developers/docs/topics/oauth2)
Fixes #10439
This PR relies on:
- https://github.com/discordjs/discord-api-types/pull/1050
- #10446
=> feat(OAuth2API): add `revokeToken` method

packages/core/src/api/applications.ts, packages/discord.js/src/index.js, packages/discord.js/src/managers/ApplicationEmojiManager.js, packages/discord.js/src/structures/ApplicationEmoji.js, packages/discord.js/src/structures/ClientApplication.js, packages/discord.js/src/structures/Emoji.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts, packages/discord.js/typings/rawDataTypes.d.ts
Adds application emojis support for core and discord.js and resolves #10396
Depends on changes from:
- https://github.com/discordjs/discord-api-types/pull/1036
=> feat: application emojis

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Fixes a build failure in TypeScript 5.5.
Resolves #10358.
See discussion at the associated issue.
Currently, the static `on()` and `once()` methods on Node's `EventEmitter` are overloaded in the discord.js typings to allow for type-checked event handling.
TypeScript 5.5.1-rc fixed the bug that allowed class merging here, and this approach is no longer possible. The `EventEmitter` class declaration in typings.d.ts causes breaking errors for `node:events` module imports in TS >=5.5.1, and needs to be removed.
It would still be useful for these methods to have access to this type-safe behaviour for client events, but we can't add static method overloads to `EventEmitter` itself.
Instead, we can override those methods …
=> types(Client): `EventEmitter` static method overrides

packages/core/src/api/guild.ts, packages/core/src/api/voice.ts, packages/discord.js/src/managers/VoiceStateManager.js, packages/discord.js/src/structures/VoiceState.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/rawDataTypes.d.ts
- Added methods for fetching VoiceState (see https://github.com/discord/discord-api-docs/pull/7061).
- Deprecated and moved `editUserVoiceState` and `setVoiceState` from GuildsAPI to VoiceAPI in core to be more in line with API documentations
Depends on
- https://github.com/discordjs/discord-api-types/pull/1046
- https://github.com/discord/discord-api-docs/pull/7061
- #10452 
=> feat(VoiceState): add methods for fetching voice state

packages/core/src/api/sticker.ts, packages/discord.js/src/client/Client.js, packages/discord.js/src/structures/Sticker.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Add the ability to fetch a single sticker pack
Upstream:
- https://github.com/discord/discord-api-docs/pull/7065
Depends on:
- https://github.com/discordjs/discord-api-types/pull/1053
=> feat: use get sticker pack endpoint

packages/collection/src/collection.ts
This updates the build to be forwards compatible with https://github.com/microsoft/TypeScript/pull/58243, which uses a stricter return type for built-in iterators under the new `strictBuiltinIteratorReturn` option, which is enabled by default when building with `strict`.
=> fix(build): update to support strictBuiltinIteratorReturn

packages/discord.js/src/structures/MessagePayload.js
`this.client` is undefined meaning this code currently crashes
Regression from #10381
=> fix(MessagePayload): crash when resolving body

packages/discord.js/src/structures/MessageReaction.js
This PR fixes an edge case where MessageReaction#countDetails was not initialized before a new reaction has been added.
Fixes https://github.com/discordjs/discord.js/issues/10468
=> fix: message reaction crash

packages/brokers/cliff.toml, packages/builders/cliff.toml, packages/collection/cliff.toml, packages/core/cliff.toml, packages/create-discord-bot/cliff.toml, packages/discord.js/cliff.toml, packages/formatters/cliff.toml, packages/next/cliff.toml, packages/proxy/cliff.toml, packages/rest/cliff.toml, packages/scripts/turbo/generators/templates/default/cliff.toml, packages/util/cliff.toml, packages/voice/cliff.toml, packages/ws/cliff.toml
Adds in:
- `by @username` for each commit where we have an author
- `New Contributors` section for new contribs in that release flow, similar to the built-in generate release notes feature
=> chore: add in more data to changelog entries

packages/discord.js/src/util/Transformers.js
`_transformAPIMessageInteractionMetadata`'s recursive call wasn't passing the first parameter (`client`) along.
=> fix(Transformers): pass client to recursive call

packages/discord.js/src/client/actions/Action.js, packages/discord.js/src/client/actions/MessageReactionAdd.js
Fixes Message#react returning undefined. Wouldn't be a release without a patch version
=> fix(Message): reacting returning undefined

packages/discord.js/src/managers/ApplicationEmojiManager.js
Fixes the `ApplicationEmojiManager#fetch` example, `<Message>.application` doesn't exist
=> docs(ApplicationEmojiManager): fix fetch example

packages/discord.js/typings/index.d.ts
Export the helper type used to remove  `PartialGroupDMChannel` as possible value for `Structure#channel` as it’s also useful for users.
=> types: export GroupDM helper type

packages/discord.js/src/structures/Message.js, packages/discord.js/typings/index.d.ts
An oversight from #10227. Deprecates `<Message>.interaction` in JSDoc comments and `MessageInteraction` in typings.
=> docs(Message): mark `interaction` as deprecated

packages/discord.js/src/structures/BaseChannel.js, packages/discord.js/src/util/Constants.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Adds in `BaseChannel#isSendable`, which is a mix of `isTextBased()` and checking if you can actually send messages in the channel. This way, we can have the correct types for interaction.channel, and you can assert whether you got the interaction from a Group DM Channel or not
=> fix: type guard for sendable text-based channels

packages/core/src/api/channel.ts, packages/discord.js/src/structures/Message.js, packages/discord.js/src/structures/interfaces/TextBasedChannel.js
Updates Discord documentation links after https://github.com/discord/discord-api-docs/pull/7034 and also some broken/outdated links.
=> docs: update discord documentation links

packages/discord.js/src/structures/ApplicationCommand.js
Raised in support: https://discord.com/channels/222078108977594368/824411059443204127/1283275617667780628
=> fix(ApplicationCommand): incorrect comparison in equals method

apps/website/src/util/fetchDependencies.ts
`discord.js` now depends on `@discordjs/builders` `^1.9.0` which includes an invalid character (`^`) for the search index
=> fix: docs search

packages/discord.js/src/client/actions/MessageCreate.js, packages/discord.js/src/client/actions/MessageDelete.js, packages/discord.js/src/client/actions/MessagePollVoteAdd.js, packages/discord.js/src/client/actions/MessagePollVoteRemove.js, packages/discord.js/src/client/actions/MessageReactionAdd.js, packages/discord.js/src/client/actions/MessageReactionRemove.js, packages/discord.js/src/client/actions/MessageReactionRemoveAll.js, packages/discord.js/src/client/actions/MessageReactionRemoveEmoji.js, packages/discord.js/src/client/actions/MessageUpdate.js, packages/discord.js/src/client/actions/TypingStart.js
Fixes #10495.
`guild_id` only gets passed to `Action#getChannel()` if it exists in the payload as key.
=> fix: `GuildChannel#guildId` not being patched to `undefined`

packages/api-extractor/src/generators/ApiModelGenerator.ts, packages/scripts/src/generateSplitDocumentation.ts
Adds default values to docs website as `(default: <value>)` at the end of the summary for properties.
=> feat: show default values in docs

packages/api-extractor/src/generators/ApiModelGenerator.ts
Adds `| null` to the types on website for parameter of events that are nullable. This was a regression ever since js events were parsed into api-extractor generated docs.
See https://discord.js.org/docs/packages/discord.js/main/Client:Class#presenceUpdate for an example, oldPresence here is nullable but not shown as such. This PR fixes that.
=> fix(website): nullable parameters on events

packages/discord.js/src/structures/Webhook.js, packages/discord.js/src/structures/interfaces/InteractionResponses.js, packages/discord.js/src/structures/interfaces/TextBasedChannel.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Fixes https://github.com/discordjs/discord.js/issues/10508
=> types(MessageEditOptions): Omit `poll`

packages/discord.js/src/structures/AutocompleteInteraction.js, packages/discord.js/src/structures/BaseInteraction.js, packages/discord.js/src/structures/CommandInteraction.js, packages/discord.js/typings/index.d.ts
=> fix(BaseInteraction): add missing props

packages/discord.js/src/structures/Message.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/6833
=> feat: message forwarding

packages/discord.js/src/managers/GuildScheduledEventManager.js, packages/discord.js/src/structures/GuildScheduledEvent.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/src/util/Transformers.js, packages/discord.js/test/random.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Upstream:
- https://github.com/discord/discord-api-docs/pull/7058
Depends on:
- https://github.com/discordjs/discord-api-types/pull/1058
- #10452
=> feat: recurring scheduled events

packages/discord.js/src/managers/BaseGuildEmojiManager.js, packages/discord.js/src/structures/MessageReaction.js, packages/discord.js/typings/index.d.ts
When using typescript you can't react to a message with an `ApplicationEmoji` because `EmojiResolvable` lacks the type.
Edit: I also updated BaseGuildEmojiManager.js and added `ApplicationEmoji` to the `MessageReaction#emoji` getter.
=> feat: Add ApplicationEmoji to EmojiResolvable and MessageReaction#emoji

packages/discord.js/README.md
Like #10059 but for mainlib
Closes #10530
=> docs(discord.js): remove `utf-8-validate`

packages/discord.js/src/client/Client.js
Some managers had incorrect descriptions, which applied only to the cache of the manager
=> docs(Client): fix incorrect managers descriptions

packages/discord.js/src/managers/UserManager.js, packages/discord.js/src/structures/User.js, packages/discord.js/src/util/Util.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Deprecates the fetching of user flags that were removed with #8755.
=> refactor: Deprecate fetching user flags

packages/discord.js/src/managers/ThreadMemberManager.js, packages/discord.js/src/structures/ThreadMember.js, packages/discord.js/src/util/Util.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Deprecates the `reason` parameter on adding and removing thread members that were removed with #10023.
=> refactor: Deprecate `reason` parameter on adding and removing thread members

packages/api-extractor-model/src/mixins/ApiItemContainerMixin.ts, packages/api-extractor-model/src/model/ApiPackage.ts, packages/api-extractor/extends/tsdoc-base.json, packages/builders/src/interactions/commands/chatInput/ChatInputCommand.ts, packages/builders/tsdoc.json
For documenting members of mixins that are merged into a class definition `api-extractor` now supports the `@mixes` TSDoc tag.
Before: https://discord.js.org/docs/packages/builders/main/ChatInputCommandBuilder:Class
After:
=> docs: allow `@mixes` TSDoc tag for documenting mixins

packages/discord.js/src/client/Client.js, packages/discord.js/src/errors/ErrorCodes.js, packages/discord.js/typings/index.d.ts
#10420 introduced some bugs that get fixed with this:
- `Client#shard` registers listeners on `Client#ws` so it needs to be initialized after `Client#ws`
- `Client#ping` was `NaN` before the first heartbeat from the gateway was received, now it'll return `null` instead
- erroneous rebase of #10420 caused deprecated DiscordjsErrorCodes to reappear in `src/errors/ErrorCodes.js`
Fixes #10555.
BREAKING CHANGE: `Client#ping` is nullable now
- This PR includes breaking changes (methods removed or renamed, parameters …
=> refactor!: fix several issues with /ws incorporation

packages/api-extractor-model/src/model/ApiPackage.ts
Fixes failing docs CI because old api.json files omitted the tsdocConfig but newer files have it to support the `@mixes` tag.
=> fix: missing tsdocConfig in api.json preventing index generation

packages/discord.js/src/structures/MessagePayload.js, packages/discord.js/src/structures/interfaces/InteractionResponses.js, packages/discord.js/src/util/MessageFlagsBitField.js, packages/discord.js/typings/index.d.ts
Deprecates the `ephemeral` option due to #10564.
=> refactor(InteractionResponses): Deprecate ephemeral response option

packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/src/managers/GuildMemberManager.js, packages/discord.js/src/managers/GuildScheduledEventManager.js
Some code was eventually making its way back to itself. The redundancy has been removed.
=> refactor: remove extra traversing

packages/core/src/api/channel.ts, packages/core/src/api/guild.ts, packages/core/src/api/index.ts, packages/core/src/api/soundboardSounds.ts, packages/core/src/client.ts
Adds soundboard for core
Depends on changes from:
- https://github.com/discordjs/discord-api-types/pull/1113
- https://github.com/discord/discord-api-docs/pull/6260
=> feat: add soundboard

packages/discord.js/src/managers/GuildMemberRoleManager.js
It's not clear to users that the behaviour of #add and #remove calls changes based on if a singular or multiple roles are supplied. We should explicitly note that, as it can lead to issues (for example when multiple role-state bots interact and use patch calls).
=> docs: add note about idempotence to role add/remove routes

packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/typings/index.d.ts
Resolves #10578.
In addition, this method cannot return `null`, so the typings and documentation had `null` removed (remnant of #10421).
=> fix(ThreadChannel): Address parameter type on `fetchOwner()`

packages/collection/__tests__/collection.test.ts, packages/collection/src/collection.ts
The callback variant of `Array.from()` is slow in V8. Changing the method of array generation from:
```js
Array.from({ length: amount }, () => ...)
```
to
```js
const results = new Array(amount)
for (let index = 0; index < amount; index++) results[index] = ...
```
produces a ~90-95% reduction in execution time, when tested with all current LTS versions of Node.
Note that this is deliberately `new Array(n)` and not `Array.from({ length: n })`:
- The first of these just creates an empty array with a length property of `n`, and is an O(1) operation.
- The second of these is an O(n) operation: it creates an empty array of length `n`, then for all `i` in `0 <= i < n`, it reads the property `obj[i]` from the object parameter (which in this case will always be undefined), and sets `array[i]` to …
=> perf(collection): optimisations

packages/formatters/__tests__/formatters.test.ts, packages/formatters/src/formatters.ts
Discord doesn't verify emoji names, meaning you only actually need to include a valid ID for an emoji to display properly. Discord.js uses `_` as a fallback name when formatting emojis with just an ID. However, since `_` is not a valid emoji name, if you were to parse that emoji, it would fail, which could be unexpected behavior.
Additionally, if you were to have multiple emojis with the `_` name placeholder and invalid IDs (or if the bot doesn't have access to the emoji), they fail to render in Discord and the text between them becomes unintentionally italicized. For example, `<:_:123678901234578> foobar <:_:123678901234578>`
This is another unintentional side-effect of using `:_:` as a placeholder emoji name that …
=> refactor(formatters): Change `:_:` emoji name placeholder

packages/discord.js/src/structures/interfaces/InteractionResponses.js
Currently no check is done when calling `deleteReply()`, similar to `editReply()`, `followUp()`, you cannot delete an interaction response if the interaction is not acknowledged first, this leads to getting `Unknown Webhook` error.
=> fix(InteractionResponses): throw error on deleting response of unacknowledged interaction

packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/typings/index.d.ts
=> fix(ThreadChannel): Address parameter type on fetchOwner()

packages/core/src/api/channel.ts
For these methods, the emoji must be encoded which is done via `encodeURIComponent()`. However, there is no indication that discord.js handles this internally without checking the source code. Therefore, it is plausible to assume that one must encode their emoji before passing it into the method, resulting in a double encoding. This pull request clarifies the internal behaviour and provides examples.
=> docs(channel): Clarify emoji parameter

packages/core/src/api/monetization.ts, packages/core/src/api/poll.ts
Nothing in these query options are required, so they have been defaulted to `{}`.
=> fix: `query` is optional for some endpoints

packages/discord.js/src/client/actions/ThreadListSync.js, packages/discord.js/src/managers/BaseGuildEmojiManager.js, packages/discord.js/src/managers/GuildBanManager.js, packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/src/managers/GuildMemberManager.js, packages/discord.js/src/managers/PresenceManager.js, packages/discord.js/src/managers/ThreadMemberManager.js, packages/discord.js/src/structures/GuildMember.js, packages/discord.js/src/structures/GuildOnboardingPromptOption.js, packages/discord.js/src/structures/Invite.js, packages/discord.js/src/structures/Message.js, packages/discord.js/src/structures/PermissionOverwrites.js, packages/discord.js/src/structures/PollAnswer.js, packages/discord.js/src/structures/ThreadMember.js, packages/discord.js/src/structures/Webhook.js, packages/discord.js/src/structures/WelcomeChannel.js
This makes it consistent to use `cache.get()` for snowflakes and `resolve()` for everything else.
=> refactor: use `cache.get()` for snowflakes, `resolve()` otherwise

packages/discord.js/src/managers/ApplicationCommandManager.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/typings/index.d.ts
`LocaleString` is deprecated. Switching to `Locale`.
=> refactor(FetchApplicationCommandOptions): Use `Locale` over `LocaleString`

packages/builders/__tests__/interactions/ChatInputCommands/ChatInputCommands.test.ts, packages/builders/__tests__/interactions/ContextMenuCommands.test.ts, packages/builders/src/util/validation.ts, packages/core/src/api/interactions.ts, packages/discord.js/src/client/websocket/handlers/VOICE_CHANNEL_EFFECT_SEND.js, packages/discord.js/src/sharding/ShardClientUtil.js, packages/discord.js/src/sharding/ShardingManager.js, packages/discord.js/src/structures/ThreadOnlyChannel.js, packages/voice/README.md, packages/voice/__tests__/AudioPlayer.test.ts
=> docs: Typos

packages/collection/__tests__/collection.test.ts, packages/collection/src/collection.ts
The documentation for `Collection#sort` and `Collection#toSorted` implies that if no comparison function is passed to the method, the default comparison behaviour mirrors that of `Array.prototype.sort` &ndash; in other words, stringwise comparison by UTF-16 code points.
As things stand, that's not the case. There are a couple of significant issues with the current implementation of `defaultSort`:
- The function doesn't implement stringwise comparison but instead just uses the `>` operator, which preferentially performs numeric comparison of its operands.
- For example, `'1.0'` is sorted after `1` with stringwise comparison, but `'1.0' > 1` is false.
- The function returns -1 (_ie._ A before B) if A is neither …
=> fix(collection)!: default sort comparison algorithm

packages/discord.js/.eslintrc.json, packages/discord.js/README.md, packages/discord.js/src/util/Events.js, packages/discord.js/test/createGuild.js, packages/discord.js/test/random.js, packages/discord.js/test/reactionCollectorCreated.test.js, packages/discord.js/test/sendtest.js, packages/discord.js/test/shard.js, packages/discord.js/test/templateCreateGuild.js, packages/discord.js/test/tester1000.js, packages/discord.js/test/tester2000.js
This updates the JSDoc reference for `clientReady` which was missed in https://github.com/discordjs/discord.js/commit/a65c76295065df303f42b90d874630248a91cb2a, it was pointed out [here](https://canary.discord.com/channels/222078108977594368/937420598383108167/1313591770252185681). Also updated the readme and tests references as well.
=> fix: update `clientReady` event name references

packages/discord.js/src/client/Client.js, packages/discord.js/typings/index.d.ts
Fixes an error in Client#lastPingTimestamps typing introduced by #10420
=> types: fix Client#lastPingTimestamps

packages/discord.js/src/structures/interfaces/InteractionResponses.js
Moves `flags` down beneath `withResponse` so `<info>` is associated to the correct property.
=> docs(InteractionDeferReplyOptions): Associate `flags` with its `<info>`

packages/discord.js/typings/index.test-d.ts
Missed with #6867. As it stands, this is doing nothing.
=> test: Remove unused test

packages/formatters/src/formatters.ts
Removed the deprecated method.
BREAKING CHANGE: Removed the `underscore()` formatter. Use `underline()` instead.
=> refactor!: Remove underscore

packages/core/src/api/interactions.ts
`with_response` was missing implementations in some methods as well as some had wrong return types
=> fix(interactions): wrong return type and missing implementation of with_response in core

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Missed with #10499. Tests passed because the overloads intersected with the property being present, but the property is not actually present on the interface itself.
=> types(InteractionReplyOptions): Add `withResponse`

packages/ws/src/strategies/context/IContextFetchingStrategy.ts
This has been a pain on multiple occasions. It's worth to just name the properties explicitly.
=> refactor(IContextFetchingStrategy): explicitly name forwarded properties

packages/discord.js/src/structures/InteractionCollector.js, packages/discord.js/src/structures/interfaces/InteractionResponses.js
`Message#interaction` has been removed since #10647  but was still being used internally in some places
=> fix: use Message#interactionMetadata

packages/discord.js/src/structures/BaseInteraction.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Replaces `BaseInteraction#isAnySelectMenu()` with `BaseInteraction#isSelectMenu()`. Internal discussion [here](https://canary.discord.com/channels/222078108977594368/1209960895141388389/1310972169534046208)
BREAKING CHANGE: `BaseInteraction#isAnySelectMenu()` has been removed. Use `BaseInteraction#isSelectMenu()` instead.
=> refactor!: replace `isAnySelectMenu` with `isSelectMenu`

apps/website/src/util/fetchSitemap.ts
Visiting a page with an unknown version causes a 500. Example: https://discordjs.dev/docs/packages/discord.js/mainn/Client:Class
This was caused by `fetchSiteMap()`:
https://github.com/discordjs/discord.js/blob/fd1958bd67b35faa0222b3c125c9265596f054de/apps/website/src/util/fetchSitemap.ts#L21-L27
The version doesn't exist. We do not check `ok`, so this eventually bubbles up to here and causes a 500 (the `if` statement is not reached):
https://github.com/discordjs/discord.js/blob/fd1958bd67b35faa0222b3c125c9265596f054de/apps/website/src/components/Navigation.tsx#L31-L35
Checking if `fileContent` is `ok` resolves this.
=> fix: Handle unknown versions

packages/discord.js/src/structures/MessagePayload.js, packages/discord.js/src/structures/interfaces/InteractionResponses.js
Addressed internally [here](https://canary.discord.com/channels/222078108977594368/1209960895141388389/1316436894766338049).
- `deferReply()` - Passing string message flags would lead to an API error as they were not being resolved.
- `reply()` - `ephemeral` was not being set properly, it was using the flags the user passed and not the resolved bits.
- Also removed some redundant code in `MessagePayload`
=> fix(InteractionResponses): properly resolve message flags

.github/workflows/documentation.yml
Prevents CI failing on pnpm version mismatch between main branch and version tag.
=> ci: make docs run succeed for old tags

packages/discord.js/src/errors/ErrorCodes.js, packages/discord.js/src/errors/Messages.js, packages/discord.js/src/structures/PermissionOverwrites.js, packages/discord.js/typings/index.d.ts
Resolves #10450.
The linked issue relates to the current cache-dependent behaviour of `PermissionOverwrites.resolve()`, specifically that passing identical parameters to `.resolve()` can conditionally pass or fail validation depending on the state of the cache.
This isn't ideal, and the function would be better placed resolving the target via `.resolveId()` in a cache-independent manner.
This approach doesn't allow for `overwrite.type` to be optional if `overwrite.id` is a Snowflake, since it would no longer attempt to seek the respective member/role object from the cache to identify it as one or the other. There are two options for how to handle this:
1. always enforce `overwrite.type` as mandatory, even if …
=> refactor(PermissionOverwrites)!: cache-independent resolve

packages/core/src/api/interactions.ts
Mistakenly made required in #10512.
=> fix(interactions): `options` should be optional

packages/discord.js/src/managers/BaseGuildEmojiManager.js, packages/discord.js/src/managers/GuildChannelManager.js, packages/discord.js/src/managers/GuildMemberManager.js, packages/discord.js/src/structures/PermissionOverwrites.js
This fixes an issue where `cache.get()` was used because of #10626, causing `PermissionOverwrites#resolve` to return undefined when `overwrite.id` may be a Role or User instance. Also updated `super.cache.get()` to `this.cache.get()` for clarity.
=> fix: use `resolve()` for `PermissionOverwrites`

packages/discord.js/src/structures/Message.js
`channel` may be `null` and thus when passing to `cleanContent()`, a crash will occur on valid types. This is reproducible in 2 (known) ways:
1. Calling `cleanContent` on a forwarded message from a guild one is not in
2. Calling `cleanContent` on a interaction's response message from a guild one is not in
Stack trace:
```
TypeError: Cannot read properties of null (reading 'client')
at /Users/jiralite/Documents/GitHub/Soulobby/Soulobby/node_modules/.pnpm/discord.js@14.17.2_patch_hash=uqmtazwjzsnpehwi2ldoqezswq/node_modules/discord.js/src/util/Util.js:389:44
at [Symbol.replace] (<anonymous>)
at String.replaceAll (<anonymous>)
at cleanContent (/Users/jiralite/Documents/GitHub/Soulobby/Soulobby/node_modules/.pnpm/discor …
```
=> fix(Message): Ensure channel is defined for clean content

packages/core/__tests__/types.test.ts, packages/core/tsconfig.json, vitest.d.ts
I believe it's a good idea to add type tests for overloads due to the following pull requests:
- #10644
- #10683
Including this to run resulted in global type errors, which is the result of an upstream bug (https://github.com/vitejs/vite/issues/9813). vitest.d.ts has been added to temporarily mitigate this.
#10683 needs to merge for tests on this pull request to pass.
=> test: Add `with_response` overload tests

apps/website/package.json, apps/website/src/components/ui/PackageSelect.tsx, apps/website/src/components/ui/VersionSelect.tsx, pnpm-lock.yaml
Opening the version select and package select drawers on the mobile documentation site was broken due to an issue in the vaul package after a version bump from 0.9.2 in https://github.com/discordjs/discord.js/commit/a6685a319efbb8892d65dbda9a9c1db1f64f1fc9.
- https://github.com/emilkowalski/vaul/issues/457
This PR bumps vaul to 1.1.2 and removes `dismissible={false}` from the drawers. (I'm not exactly sure why that was added? It doesn't allow me to stay on the current package/version on mobile by clicking on the current package/version (so I have to refresh the page), and this behaviour isn't present on the desktop select menu.)
- Code changes have been tested against the …
=> fix: make version and package select openable on mobile

packages/builders/__tests__/components/textInput.test.ts, packages/builders/__tests__/interactions/ContextMenuCommands.test.ts, packages/builders/tsconfig.json
Turns out builders had type checks too, but they were not doing anything as they were not being type checked. You can test this: change some types in the file and run the test script prior to this pull request. Tests will pass.
Now that types are checked in the directory, it picked up some undeclared variables, which I've removed.
=> test: Include type checks on builders

packages/actions/package.json, packages/actions/src/uploadSplitDocumentation/index.ts, pnpm-lock.yaml
with the massive amount of files we're uploading to blob storage we're running into ratelimits. This is making a conservative estimate of the ratelimit to avoid hitting it but also handles hitting it better
=> fix(actions): respect ratelimits on split docs upload

packages/discord.js/src/index.js, packages/discord.js/typings/index.d.ts
These functions are private
Resolves DJS-60
=> refactor: remove data resolver exports

packages/discord.js/src/managers/GuildMessageManager.js, packages/discord.js/src/managers/MessageManager.js
Moved `MessageManager#crosspost()` to `GuildMessageManager` as messages can't be crossposted to DMs. The typings already had the `crosspost` method under `GuildMessageManager` and didn't need updating.
BREAKING CHANGE: The `crosspost()` method from `MessageManager` has been moved to `GuildMessageManager`. 
=> fix!: move `crosspost()` to `GuildMessageManager`

packages/discord.js/src/structures/interfaces/TextBasedChannel.js, packages/discord.js/typings/index.d.ts
We had to add `undefined` as a return type per #8410. This was because when message ids are supplied and deleted, they are attempted to be resolved from the cache. This removes the cache hit, and will now only return the ids that were removed. Users will have access to the messages they have cached before running this method anyway.
=> refactor!: Return only snowflakes for bulk delete

packages/discord.js/src/structures/BaseGuildEmoji.js, packages/discord.js/src/structures/Emoji.js, packages/discord.js/typings/index.d.ts, packages/rest/__tests__/CDN.test.ts, packages/rest/src/lib/CDN.ts
BREAKING CHANGE: The `REST#emoji` method now has a `animated` required parameter.
I think it'd be better if `Emoji#imageURL()` changes the extension dynamically as others `...URL()` functions.
=> refactor(Emoji)!: make imageURL() change extension dynamically

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
=> types(ThreadOnlyChannel): remove incorrect `messages` property

packages/discord.js/package.json, packages/discord.js/src/client/BaseClient.js, packages/discord.js/src/sharding/Shard.js, packages/discord.js/src/sharding/ShardClientUtil.js, packages/discord.js/src/sharding/ShardingManager.js, packages/discord.js/src/structures/interfaces/Collector.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts, pnpm-lock.yaml
BREAKING CHANGE: The `BaseClient`, `Shard`, `ShardingManager`, and `Collector` classes now extend `AsyncEventEmitter` instead of `EventEmitter`.
Besides the obvious change, I also renamed `ClientEvents` to `ClientEventTypes` for consistency with the rest of the emitters.
Fixes #10577
Supersedes #10581, and #10584 partially
=> refactor!: use `AsyncEventEmitter` instead of `EventEmitter`

packages/core/src/api/guild.ts
This endpoint does not fetch all the members. It's bound by a limit of a maximum of 1,000.
=> docs(guild): Remove "all" for listing guild members

packages/discord.js/typings/index.test-d.ts
Assuming these failed due to #10710.
`MessageComponentInteraction` didn't pass the tests, but what did was `SelectMenuInteraction | ButtonInteraction`.
=> test: Fix collector tests

packages/discord.js/.eslintrc.json, packages/discord.js/src/managers/GuildBanManager.js, packages/discord.js/src/managers/GuildEmojiRoleManager.js, packages/discord.js/src/managers/GuildInviteManager.js, packages/discord.js/src/managers/GuildMemberManager.js, packages/discord.js/src/managers/PermissionOverwriteManager.js, packages/discord.js/src/sharding/Shard.js, packages/discord.js/src/sharding/ShardingManager.js, packages/discord.js/src/structures/GuildChannel.js, packages/discord.js/src/structures/Message.js, packages/discord.js/src/structures/PartialGroupDMChannel.js, packages/discord.js/src/structures/Poll.js, packages/discord.js/src/structures/Sticker.js, packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/src/structures/interfaces/InteractionResponses.js
Refactored functions previously using `Promise.{reject, resolve}()` to use the more concise `throw` syntax, converting them to `async` functions.
Also fixed a rejection from #6210 by making the `Shard#spawn` method `async`.
=> refactor: use throw instead of Promise.reject

packages/discord.js/src/managers/ApplicationCommandManager.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Removes `options` as the second parameter. The first parameter now accepts `id` or `options` which can also have the `id` property. Internal discussion [here](https://canary.discord.com/channels/222078108977594368/1209960895141388389/1330584992564379648)
BREAKING CHANGE: `ApplicationCommandManager#fetch` and `GuildApplicationCommandManager#fetch` no longer accept 2 parameters. Instead, the first parameter accepts `id` or `options` which can now also have the `id` property. …
=> refactor!: consolidate parameters into a single `options` object

packages/collection/__tests__/collection.test.ts, packages/collection/src/collection.ts
Collection methods feature subclassing support via `Symbol.species`. This currently doesn't apply to the one static method, which calls the Collection constructor specifically.
This change brings the behaviour of static methods in line with instance methods, such that `DerivedCollection.combineEntries(...)` returns a DerivedCollection, not a Collection.
=> feat(collection): honour subclassing via `@@species` in static methods

packages/discord.js/src/managers/GuildManager.js, packages/discord.js/src/structures/Guild.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/src/util/Transformers.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/7360
- https://github.com/discordjs/discord-api-types/pull/822
=> feat: Incident Actions

packages/discord.js/src/managers/ThreadManager.js, packages/discord.js/src/sharding/ShardClientUtil.js, packages/discord.js/src/structures/interfaces/TextBasedChannel.js
Using `@link` will allow the links to be clickable on the documentation.
=> docs: Use link tags to render links on the documentation

README.md, packages/brokers/README.md, packages/builders/README.md, packages/collection/README.md, packages/core/README.md, packages/create-discord-bot/README.md, packages/discord.js/README.md, packages/formatters/README.md, packages/next/README.md, packages/proxy/README.md, packages/rest/README.md, packages/util/README.md, packages/voice/README.md, packages/ws/README.md
This pull request enhances the `README.md` file by introducing the npm logo and two new badges: one for the last commit and one for contributions. These additions provide viewers and contributors with clear information on the latest commit activity and the number of contributors. The badge colors have also been updated for improved contrast and visual appeal, creating a more attractive and informative layout compared to the previous version.
- This PR **only** includes non-code changes, such as updates to documentation and README files.
=> chore: Add contributors and last commit badges

packages/brokers/cliff.toml, packages/builders/cliff.toml, packages/collection/cliff.toml, packages/core/cliff.toml, packages/create-discord-bot/cliff.toml, packages/formatters/cliff.toml, packages/next/cliff.toml, packages/proxy/cliff.toml, packages/rest/cliff.toml, packages/scripts/turbo/generators/templates/default/cliff.toml, packages/ui/cliff.toml, packages/util/cliff.toml, packages/voice/cliff.toml, packages/ws/cliff.toml
We do not use the "typings" scope any more, so this has been removed from the generator for new packages.
This has also been removed from existing packages where commits to them never had any "typings" scope. The only one that remained was discord.js.
=> chore: Remove "typings" scope from cliff.toml

packages/builders/__tests__/messages/embed.test.ts, packages/builders/src/messages/embed/Assertions.ts
=> fix(EmbedFieldBuilder): allow empty `name` and `value`

packages/builders/__tests__/messages/embed.test.ts, packages/builders/src/messages/embed/Assertions.ts
=> fix(EmbedBuilder): allow empty `name` and `value` on fields

packages/proxy-container/Dockerfile
- Upgraded the Node.js image to version 22
- Removed the installation of libc6-compat as it seems to no longer be necessary
- Install the latest version of corepack, and then use the package manager version from the workspace instead of latest
=> chore: use Node.js 22 and fix corepack installation

packages/discord.js/typings/index.d.ts
Renamed `CategoryChannelType` to `CategoryChannelChildTypes` for clarity. Also changed the use of `Exclude` to explicit listing for future-proofing.
=> types: rename `CategoryChannelType` to `CategoryChannelChildTypes`

apps/website/src/components/ParameterNode.tsx, packages/api-extractor/src/generators/ApiModelGenerator.ts
Fixes default falsy values not showing up on docs, like `BaseFetchOptions`' force:
=> fix: Do not omit falsy default values

packages/discord.js/src/managers/ChannelManager.js, packages/discord.js/src/managers/MessageManager.js, packages/discord.js/src/structures/BaseGuildTextChannel.js, packages/discord.js/src/structures/BaseGuildVoiceChannel.js, packages/discord.js/src/structures/DMChannel.js, packages/discord.js/src/structures/GuildMember.js, packages/discord.js/src/structures/Message.js, packages/discord.js/src/structures/MessagePayload.js, packages/discord.js/src/structures/PartialGroupDMChannel.js, packages/discord.js/src/structures/ThreadChannel.js, packages/discord.js/src/structures/ThreadOnlyChannel.js, packages/discord.js/src/structures/User.js, packages/discord.js/src/structures/Webhook.js, packages/discord.js/src/structures/interfaces/TextBasedChannel.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Adds a centralized spot where the creation of messages go through.
BREAKING CHANGE: `MessageCreateOptions` no longer accepts `forward` or `reply`. Use `messageReference` instead.
=> feat!: create forwards and add `ChannelManager#createMessage()`

packages/discord.js/src/managers/GuildChannelManager.js
It was only resolving when avatar was a string, but it is also typed to accept `BufferResolvable` and by extension a `Buffer`.
Fixes #10770 
=> fix(GuildChannelManager): properly resolve avatar for createWebhook

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Adds the missing `InGuild` generic to `<InteractionCallbackResponse>.resource?.message`
=> types(InteractionCallbackResponse): add missing `InGuild` generic

packages/discord.js/src/structures/MessagePayload.js
=> fix(MessagePayload): preserve existing flags when editing

packages/discord.js/typings/index.d.ts
Removed from runtime in:
- #10420
Missed from the typings
=> types(ShardClientUtil): remove `count` and `ids`

apps/website/src/components/ui/PackageSelect.tsx
When selecting another package, it is likely a better idea to redirect to the stable version, rather than the in-development version.
=> refactor(PackageSelect): Redirect to stable

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Resolves #10577.
A sticking plaster for v14 to cover this issue, which causes compiler errors when using TS 5.6 or higher under [specific conditions](https://github.com/discordjs/discord.js/issues/10577#issuecomment-2434353380). The underlying problem is that the `EventEmitter.on()` iterator now extends AsyncIteratorObject in TS 5.6+, which becomes an AsyncDisposable if lib.esnext.disposable is loaded, whereas the override signature in the v14 types uses the older AsyncIterableIterator, which isn't AsyncDisposable and so causes an assignability mismatch.
AsyncIteratorObject doesn't exist in TypeScript 5.5 and earlier, so this change provides a custom AsyncIterableIterator interface that matches whether the return …
=> types: make `Client.on()` compatible with esnext.disposable in TS5.6+

packages/discord.js/src/client/BaseClient.js, packages/rest/src/lib/REST.ts
Re-emit /rest debug event on discord.js' debug event, just like the debug event from /ws
To provide better context, added a seemingly missing prefix from REST's class debug logs, which is already present on the individual handlers, like
https://github.com/discordjs/discord.js/blob/1054f4abce14969429e6c84e095f9f0f0b10fa85/packages/rest/src/lib/handlers/SequentialHandler.ts#L118
=> feat: re-emit REST debug logs

packages/builders/__tests__/messages/poll.test.ts, packages/builders/src/messages/poll/Assertions.ts, packages/builders/src/messages/poll/Poll.ts, packages/builders/src/messages/poll/PollAnswer.ts, packages/builders/src/messages/poll/PollAnswerMedia.ts, packages/builders/src/messages/poll/PollMedia.ts, packages/builders/src/messages/poll/PollQuestion.ts
- Fixed validations
- Added missing documentation
- Removed redundant code
- Consistency™️
=> fix: poll builders

packages/builders/__tests__/interactions/ContextMenuCommands.test.ts, packages/builders/src/interactions/commands/contextMenu/Assertions.ts
=> fix(ContextMenuCommandBuilder): allow emoji in name

packages/discord.js/src/managers/GuildMemberManager.js
A regression from #10715: when doing `fetch()`, an error is thrown:
```
/Users/jiralite/Documents/GitHub/discord.js/discord.js/packages/discord.js/src/managers/GuildMemberManager.js:220
limit = 0,
^
TypeError: Cannot read properties of undefined (reading 'limit')
at GuildMemberManager._fetchMany (/Users/jiralite/Documents/GitHub/discord.js/discord.js/packages/discord.js/src/managers/GuildMemberManager.js:220:5)
at GuildMemberManager.fetch (/Users/jiralite/Documents/GitHub/discord.js/discord.js/packages/discord.js/src/managers/GuildMemberManager.js:201:31)
at Client.<anonymous> (/Users/jiralite/Documents/GitHub/Soulobby/Soulobby/source/test.ts:11:58)
at Client.emit …
```
=> fix(GuildMemberManager): Ensure empty object for fetching many guild members

packages/builders/__tests__/messages/embed.test.ts, packages/builders/src/messages/embed/Assertions.ts
Embed thumbnails and images may use the `attachment://` protocol. Icon URLs and footer icon URLs are currently fine as-is.
=> fix(embed): Allow attachment protocols for thumbnails and images

.github/CODEOWNERS, .github/workflows/cleanup-cache.yml, packages/builders/src/components/ActionRow.ts, packages/builders/src/components/selectMenu/StringSelectMenu.ts, packages/builders/src/interactions/commands/chatInput/mixins/SharedChatInputCommandOptions.ts, packages/builders/src/interactions/modals/Modal.ts, packages/builders/src/messages/embed/Embed.ts, packages/builders/src/messages/poll/Poll.ts, packages/collection/src/collection.ts, packages/discord.js/src/client/Client.js, packages/discord.js/src/structures/interfaces/Collector.js, packages/rest/src/lib/REST.ts
Removed hardcoded locale links from external links, so each user can open the page directly in their preferred locale
=> docs: remove hardcoded locale from links

packages/builders/__tests__/messages/message.test.ts, packages/builders/src/index.ts, packages/builders/src/messages/AllowedMentions.ts, packages/builders/src/messages/Assertions.ts, packages/builders/src/messages/Attachment.ts, packages/builders/src/messages/Message.ts, packages/builders/src/messages/MessageReference.ts
=> feat: message builder

packages/scripts/src/generateSplitDocumentation.ts
Links to Type Parameters in docs were using the wrong suffix so they 404d.
For example the link to CachedType or RawType on https://discord.js.org/docs/packages/discord.js/14.18.0/CacheTypeReducer:TypeAlias
=> fix(website): correctly link type parameters in docs

packages/builders/src/components/textInput/Assertions.ts
Will throw this error otherwise: `data.components[1].components[0].value[BASE_TYPE_MIN_LENGTH]: Must be 1 or more in length.`
=> fix(textInput): Value must be at least 1 character in length

packages/discord.js/src/client/Client.js
`process.env.SHARDS` only has the shard id (not an array). This meant that we were passing `shardIds: 0` to WebSocketManager, which fails this the following `if` statement, making /ws fetch get all shards and start them on the current process. 
https://github.com/discordjs/discord.js/blob/4d1942681077c5c49abaf90873cf1cafb21de84f/packages/ws/src/ws/WebSocketManager.ts#L346-L347
=> fix: all shards spawning on shard 0 with sharding manager

packages/discord.js/src/structures/Poll.js
I use polls but I don't subscribe to the `messageUpdate` event, but I've been occassionally seeing this pop up. It doesn't seem to happen for every poll so I'm not 100% sure on reproduce steps. I think it's a minor bug that stems from the overhaul https://github.com/discordjs/discord.js/pull/10328
```ts
[UnhandledPromise] TypeError: Cannot read properties of undefined (reading 'get')
Promise {
<rejected> TypeError: Cannot read properties of undefined (reading 'get')
at Poll._patch (/app/node_modules/discord.js/src/structures/Poll.js:58:37)
at new Poll (/app/node_modules/discord.js/src/structures/Poll.js:46:10)
at Message._patch (/app/node_modules/discord.js/src/structures/Message.js:425:21)
at Message._update …
```
=> fix(Poll): ensure `this.answers` is set before we reference it

packages/discord.js/src/structures/PollAnswer.js
This causes an error `TypeError: Cannot redefine property: _emoji`.
=> fix(PollAnswer): only define _emoji property once

.npmrc, apps/website/.gitignore, biome.json, package.json, pnpm-lock.yaml, pnpm-workspace.yaml, turbo.json, unocss.config.ts
Since pnpm [10.5](<https://github.com/pnpm/pnpm/releases/tag/v10.5.0>) and [10.6](<https://github.com/pnpm/pnpm/releases/tag/v10.6.0>), the `pnpm-workspace.yaml` file can hold settings from `package.json`'s `pnpm` key and `.npmrc` files.
Upgrade pnpm to 10.8
Removed the `resolution-mode=highest` setting as that is the default value
=> chore: move pnpm settings to pnpm-workspace.yaml

packages/discord.js/typings/index.d.ts
#9283 introduced `BaseMessageCreateOptions` in JSDoc but didn't update typings to reflect that. So documentation was missing the description of some of its fields.
=> types: add missing BaseMessageCreateOptions

packages/core/README.md
This PR updates the "Independent REST API Usage" section in the README to include the appropriate import statements, ensuring consistency with the structure and format of other examples in the documentation. This makes the usage clearer and aligns with the overall style of the README.
=> docs(readme): add import statement for pure REST usage to align with other examples

packages/discord.js/src/structures/Guild.js
Guild's soundboard sounds are sent with the guild create event but are never cached before fetching them.
=> fix(Guild): cache soundboard sounds when patching

packages/discord.js/src/structures/MessagePayload.js, packages/discord.js/src/structures/UnfurledMediaItem.js, packages/discord.js/src/util/Components.js, packages/discord.js/typings/index.d.ts
Fixes an issue where allowedMentions don't get used in MessagePayload if `IsComponentsV2`.
Fixes #10855
Adds the missing `UnfurledMediaItem#toJSON()`.
Fixes `MessageComponentInteraction#component` not working for components in an ActionRow inside a Container.
=> fix: allowedMentions, container, media item `toJSON()` for components v2

packages/discord.js/src/structures/GuildAuditLogsEntry.js, packages/discord.js/src/structures/SoundboardSound.js
Fixes `emojiId` and `emojiName` still being used in `equals` even when they don't exist anymore (changed in [`7b3cfe4` (#10590)](https://github.com/discordjs/discord.js/pull/10590/commits/7b3cfe4c19ab7b84406379fb0ed11c5a17d98237))
Also removes the duplicate `AuditLogEvent.SoundboardSoundUpdate` in GuildAuditLogsEntry
=> fix(SoundboardSound): wrong emoji comparison in `equals`

packages/discord.js/src/managers/GuildSoundboardSoundManager.js, packages/discord.js/typings/index.d.ts
`reason` property was missing in `GuildSoundboardSoundEditOptions`
=> types(GuildSoundboardSoundEditOptions): add missing `reason`

packages/builders/src/components/v2/Assertions.ts, packages/builders/src/components/v2/Container.ts, packages/builders/src/components/v2/Thumbnail.ts
Removes the assertion limiting amount of components in a container
- https://github.com/discord/discord-api-docs/pull/7534
Also adds `.setValidationEnabled(isValidationEnabled)` to two shapes that were missing it.
=> chore: remove container limit

packages/ws/package.json, pnpm-lock.yaml
zlib-sync 0.1.9 was unable to compile on recent MacOS versions. This fixes that.
Supersedes #10868 
=> chore: bump zlib-sync to 0.1.10

apps/website/src/components/DocItem.tsx, apps/website/src/components/SyntaxHighlighter.tsx, packages/scripts/src/generateSplitDocumentation.ts
Because all instances in JS have a `.constructor` property the check in website was checking the wrong thing *and* the docs were overwriting that property.
This PR fixes that by renaming the property of the docs to document constructors.
Down side: all docs need to be regenerated after this merges or no constructors will show in docs.
=> fix(website): constructors show on too many items

packages/brokers/src/brokers/redis/BaseRedis.ts
<https://discord.js.org/docs/packages/brokers/main/BaseRedisBroker:Class#STREAM_DATA_KEY>
=> docs: fix missing type

apps/website/src/components/ConstructorNode.tsx, packages/scripts/src/generateSplitDocumentation.ts
Mark constructors as external too on external classes to fix their source code link
example: https://discord.js.org/docs/packages/discord.js/14.19.2/ContainerBuilder:Class#constructor
=> fix(website): link to external constructors

apps/website/src/components/DocItem.tsx, apps/website/src/components/DocNode.tsx
This fixes SyntaxHighlighter background not properly expanding to fill Scrollbars horizontally.
Affects both mobile and PC.
https://discord.js.org/docs/packages/discord.js/14.19.3/ComponentBuilder:Class
https://discord.js.org/docs/packages/discord.js/14.19.3/ApplicationEmojiManager:Class
=> fix: syntaxhighlighter fill scrollbar width

packages/discord.js/package.json
Removed the `typings/index.d-test.ts` from the published package
=> build: exclude type tests from pack

packages/discord.js/src/structures/PartialGroupDMChannel.js
When fetching a group direct message invite, I encountered this:
`icon` and `recipients` were `undefined`. Looking at the specification, only `id` and `type` are definitely sent:
https://github.com/discord/discord-api-spec/blob/507909d1ea5a921064d599e1f3b57163af2037d6/specs/openapi.json#L23049-L23052
This pull request puts sensible defaults into place.
=> fix(PartialGroupDMChannel): Prevent `undefined` values

packages/api-extractor-utils/src/parse.ts
Previously searching for enum members like `DiscordJsError#InteractionAlreadyReplied` resulted in the URL https://discord.js.org/docs/packages/discord.js/14.19.2/DiscordjsErrorCodes:Enum instead of the correct https://discord.js.org/docs/packages/discord.js/14.19.2/DiscordjsErrorCodes:Enum#InteractionAlreadyReplied
Fixes #10874 
=> fix(website): link to enum members in search index

packages/discord.js/src/managers/GuildManager.js, packages/discord.js/src/managers/GuildSoundboardSoundManager.js, packages/discord.js/src/structures/Guild.js, packages/discord.js/src/structures/SoundboardSound.js, packages/discord.js/typings/index.d.ts
Forwardports things from:
- https://github.com/discordjs/discord.js/pull/10850
- https://github.com/discordjs/discord.js/pull/10854
- https://github.com/discordjs/discord.js/pull/10857
- https://github.com/discordjs/discord.js/pull/10863
Also fixes `emojiId` and `emojiName` still being used in `equals` even when they don't exist anymore (changed in [`7b3cfe4` (#10590)](https://github.com/discordjs/discord.js/pull/10590/commits/7b3cfe4c19ab7b84406379fb0ed11c5a17d98237))
=> feat: soundboard forward port

apps/website/src/components/EntrypointSelect.tsx, apps/website/src/middleware.ts, apps/website/src/util/constants.ts, apps/website/src/util/parseDocsPathParams.ts, packages/api-extractor-model/src/model/ApiEntryPoint.ts, packages/api-extractor/src/api/ExtractorConfig.ts, packages/api-extractor/src/api/IConfigFile.ts, packages/api-extractor/src/generators/ApiModelGenerator.ts, packages/api-extractor/src/schemas/api-extractor-defaults.json, packages/api-extractor/src/schemas/api-extractor-template.json, packages/api-extractor/src/schemas/api-extractor.schema.json, packages/scripts/src/generateSplitDocumentation.ts
Removes several special treatments for the `discord-api-types` package in docs pipeline that are obsolete now that they are on the same website.
Also moves the special treatment of `v10` as default entryPoint for `discord-api-types` to the generateSplitDocumentation` script instead of website.
=> fix(website): remove several obsolete special handling of dtypes

packages/api-extractor/src/generators/DeclarationReferenceGenerator.ts, packages/scripts/src/generateSplitDocumentation.ts
Links in docs for discord-api-types didn't include the /v10 part for the entrypoint. Now they do
=> fix(api-extractor): include entrypoint in links

packages/discord.js/src/util/Transformers.js
=> fix: use resolvePartialEmoji on MessagePayload#options#components

packages/discord.js/src/client/actions/InteractionCreate.js, packages/discord.js/src/index.js, packages/discord.js/src/managers/ApplicationCommandManager.js, packages/discord.js/src/structures/ApplicationCommand.js, packages/discord.js/src/structures/BaseInteraction.js, packages/discord.js/src/structures/CommandInteraction.js, packages/discord.js/src/structures/MessageComponentInteraction.js, packages/discord.js/src/structures/ModalSubmitInteraction.js, packages/discord.js/src/structures/PrimaryEntryPointCommandInteraction.js, packages/discord.js/src/structures/interfaces/InteractionResponses.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
=> feat: backport entrypoint command

packages/next/api-extractor.json
Currently we generate all sub-package docs another time in /next and upload them as entrypoints. This removes that.
=> docs: don't generate all sub-package docs for /next

apps/website/src/app/docs/packages/layout.tsx
Fixes the background of the main content not occupying the entire screen on pages with little content
Before:
https://discord.js.org/docs/packages/discord.js/14.19.3/applicationDirectory:Function
After:
https://discord-js-git-fix-full-page-content-discordjs.vercel.app/docs/packages/discord.js/14.19.3/applicationDirectory:Function
=> fix: background on pages with little content

packages/discord.js/typings/index.d.ts
Adds missing `guildSoundboardSoundsUpdate`, also updates other soundboard sound-related events to be specific
=> types(ClientEventTypes): add missing `guildSoundboardSoundsUpdate`

packages/discord.js/src/structures/GuildMember.js, packages/discord.js/typings/index.d.ts
Resolves #10940
Also removes leftover parameter from `User#avatarDecorationURL`
=> feat(GuildMember): add `avatarDecorationData`

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Backports https://github.com/discordjs/discord.js/pull/10767
=> types(InteractionCallbackResponse): add missing InGuild generic

packages/collection/src/collection.ts
This small change to the derivation for `ReadonlyCollection` future-protects the definition against the addition of mutating methods to the Map prototype, as will soon occur with [proposal-upsert](https://github.com/tc39/proposal-upsert) reaching stage 3.
=> types(ReadonlyCollection): derivation logic

packages/discord.js/src/managers/GuildMemberRoleManager.js, packages/discord.js/src/managers/RoleManager.js, packages/discord.js/src/structures/Role.js, packages/discord.js/src/util/Constants.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/7549
- https://github.com/discord/discord-api-docs/pull/7661
=> feat!: role gradient colors

packages/core/src/api/channel.ts, packages/core/src/api/guild.ts
These should allow `reason` per https://discord.com/developers/docs/resources/channel.
=> fix: Adjust `reason` in methods options

packages/rest/__tests__/CDN.test.ts, packages/rest/src/lib/CDN.ts, packages/rest/src/lib/REST.ts
The constructor of `CDN` had two optional parameters with defaults, so it semantically makes sense to use an object.
=> refactor(CDN)!: Use an object for the constructor

packages/discord.js/src/client/websocket/WebSocketManager.js, packages/discord.js/src/util/Events.js, packages/discord.js/typings/index.d.ts
`clientReady` is what should be used moving forward.
=> refactor: Deprecate `ready` event in favor of `clientReady`

packages/discord.js/src/client/Client.js, packages/discord.js/src/structures/BaseGuildEmoji.js, packages/discord.js/src/structures/Emoji.js, packages/discord.js/typings/index.d.ts, packages/rest/__tests__/CDN.test.ts, packages/rest/src/lib/CDN.ts
=> feat: Support animated WebP

packages/discord.js/src/structures/User.js, packages/discord.js/typings/index.d.ts, packages/rest/__tests__/CDN.test.ts, packages/rest/src/lib/CDN.ts
=> feat: support user guilds

packages/builders/src/components/v2/Container.ts
Using discord-api-types v10 for imports instead of being mixed.
=> fix(Container): Use the same discord-api-types version

packages/builders/__tests__/interactions/ContextMenuCommands.test.ts, packages/builders/src/interactions/contextMenuCommands/Assertions.ts
=> fix(contextMenuCommands): Remove regular expression validation

packages/discord.js/src/managers/RoleManager.js, packages/discord.js/src/structures/GuildMember.js, packages/discord.js/src/structures/Role.js
- Updated the documentation of `RoleManager#fetch()` to use `colors`
- `GuildMember#displayColor` was always returning `0` as it referenced a non-existent property
- Getting the `hexColor` of a role will cause a crash as `this.color` does not exist
=> fix: Remove trailing `color` references

README.md
Adds @discordjs/structures to the main README.md with the other packages.
=> docs: Add structures to main README.md

packages/discord.js/src/structures/Guild.js, packages/discord.js/src/structures/GuildTemplate.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/7715
- Guild creation was removed with #11012
- https://github.com/discord/discord-api-docs/pull/7720
- https://github.com/discord/discord-api-docs/pull/7722
=> fix!: Remove API related to guild ownership

.github/workflows/release.yml, packages/actions/src/releasePackages/releasePackage.ts
Still need to set a user...since we have an app now we'll use that instead
=> ci(release): use app user

packages/actions/src/releasePackages/index.ts
`program.args` is empty if no arguments are passed via CLI, despite us passing a default value.
`program.processedArgs` seems to work as we expect.
=> build: fix package name argument parsing

packages/discord.js/scripts/generateRequires.mjs, packages/discord.js/src/client/actions/ActionsManager.js
I've changed the way actions are registered in ActionsManager to use the file name of the action instead of the action class' name which is just the file name with 'Action' added on the end.
Currently discord.js is unable to be minified as minifiers change class names, with this change, it loads actions without the use of the class name.
I've had a project for more then a year that uses a modified discord.js (only this change) with no issues whatsoever when minified, which has allowed me to give a nice and small sized build to users.
This isn't really a breaking change as the method changed isn't used anywhere externally to the ActionsManager (which makes sense), and also isn't typed. I've marked it as breaking as …
=> refactor(ActionsManager): register actions without using class name

packages/discord.js/src/structures/GuildChannel.js
When calculating permissions after overwrites, the base permission of the at-everyone role need to be accounted for. Role#permissions is not sufficient, as it only describes base permissions of the role itself.
fixes #11052
- I know how to update typings and ~~have done so~~, or typings don't need updating
=> fix(GuildChannel): account for everyone base permissions

packages/discord.js/src/client/actions/Action.js, packages/discord.js/src/client/actions/MessagePollVoteAdd.js, packages/discord.js/src/client/actions/MessagePollVoteRemove.js, packages/discord.js/src/index.js, packages/discord.js/src/managers/PollAnswerVoterManager.js, packages/discord.js/src/structures/Message.js, packages/discord.js/src/structures/Poll.js, packages/discord.js/src/structures/PollAnswer.js, packages/discord.js/src/util/Partials.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Backports:
- #10328
- #10809
- #10811
Additionally:
- Added a runtime deprecation warning to `PollAnswer#fetchVoters`
=> feat: polls overhaul

packages/discord.js/src/structures/Guild.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/7720
=> fix(Guild)!: Remove setting owner

.github/workflows/pr-triage.yml
Imagine this scenario:
1. A user opens a pull request that is out of date with main. The pull request title does not match the regular expression
2. The user updates their branch 
When the user updates their branch, synchronisation occurs. This means validation will be skipped, and the error will go away. This means a bad actor could merge a pull request with any name they like if the pull request was in an approved state.
This pull request makes validation always run.
=> ci(pr-triage): Make validate title run always

packages/actions/src/releasePackages/generateReleaseTree.ts
Moved the creation of the timestamp part of release versions outside of the loop, so all the versions released in each run will have the same timestamp. This is mostly a QoL change for people (me) when upgrading packages.
e.g., this is the way the versions are currently: 
```json
{
"dependencies": {
"@discordjs/core": "3.0.0-dev.1756512122-cc43dadca",
"@discordjs/rest": "3.0.0-dev.1756512128-cc43dadca",
"@discordjs/ws": "3.0.0-dev.1756512132-cc43dadca"
}
}
```
Everything matches but the timestamp, which is off by a few seconds... Upgrading this manually would entail opening the npm page (or whatever else) for each of those to get the correct timestamp for the version. Now all the versions will have the same timestamp, simplifying the upgrade
=> build: use the same timestamp for release versions

packages/discord.js/src/index.js, packages/discord.js/src/structures/GuildInvite.js, packages/discord.js/src/util/APITypes.js, packages/discord.js/src/util/InviteFlagsBitField.js, packages/discord.js/typings/index.d.ts
- https://github.com/discord/discord-api-docs/pull/6247
=> feat: Guest invites

packages/discord.js/src/managers/GuildForumThreadManager.js, packages/discord.js/src/structures/Attachment.js, packages/discord.js/src/structures/AttachmentBuilder.js, packages/discord.js/src/structures/MessagePayload.js, packages/discord.js/src/structures/Webhook.js, packages/discord.js/src/structures/interfaces/InteractionResponses.js, packages/discord.js/src/structures/interfaces/TextBasedChannel.js, packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Adds the ability to send voice messages
Resolves #10298
Depends on:
- https://github.com/discord/discord-api-docs/pull/7267
=> feat: send voice messages

packages/discord.js/src/structures/ApplicationCommand.js, packages/discord.js/src/structures/ApplicationRoleConnectionMetadata.js, packages/discord.js/src/structures/ClientApplication.js, packages/discord.js/src/util/APITypes.js
Changed the doc string to match the typings.
https://discord.com/channels/222078108977594368/824411059443204127/1421464797760720936
=> docs: use LocalizationMap where applicable

.github/workflows/release.yml, packages/actions/src/releasePackages/action.yml, packages/actions/src/releasePackages/index.ts
Makes the Release CI always use the main workflow which allows us to release from branches that don't have the workflow. Doing this in the dev workflow adds an extra layer of security, that will be done in or after #11120
(yes, no build step for the action is correct, bun negates that)
=> ci(release): use main action always

packages/brokers/src/brokers/redis/BaseRedis.ts, packages/brokers/src/brokers/redis/RPCRedis.ts
Convenient for situations where you want to fan out events.
=> feat(RedisBroker): ability to explicitly tell the library to pick a random group

packages/voice/package.json, packages/voice/src/receive/VoiceReceiver.ts, packages/voice/src/util/Secretbox.ts, pnpm-lock.yaml
Changed the type of `key` in the Secretbox methods to `Uint8Array` to match what is actually being passed, as in the newer TypeScript versions `Uint8Array` doesn't satisfy the `ArrayBufferLike` constraint.
https://github.com/discordjs/discord.js/blob/cf89260c9862d5101d6583bfe7a55ad9238631db/packages/voice/src/networking/Networking.ts#L158
For the VoiceReceiver changes, the direct assignment in the declaration was narrowing `packet` to `Buffer<ArrayBuffer>` while further down it's being widened to `Buffer<ArrayBufferLike>`. Added a type annotation to keep the type wide from the start, which the consumers of this method can handle.
***
There is a newer version of TypeScript, but I kept it the same as the other versions from the workspace. Dependency bump pull request will come later.
=> fix: adjust types for typescript upgrade

packages/discord.js/typings/index.d.ts, packages/discord.js/typings/index.test-d.ts
Webhooks can't send messages not in guild
=> types(Webhook): specify message type

apps/guide/content/docs/legacy/meta.json
As discussed[^1], we will change the name to "discord.js" without changing the "legacy" path.
[^1]: https://canary.discord.com/channels/222078108977594368/1078692758153351278/1424895025703157760
=> chore(guide): Update name of legacy path
